### ISSUE TITLE
Method : SetOrientation 

### ISSUE THREAD

**Issue by blackHoleNgc1277** [DavBfr/dart_pdf#1]
"setOrientation" method does not change the display of the page. the irientation is always portrait orientation mode.  How to change orientation of a page (Portrait, Landscape).

**Comment by DavBfr** [comment]
SetOrientation is not used yet. You can reverse the page Width and Height for landscape.

**Comment by DavBfr** [comment]
SetOrientation has been removed in 1.0.1
