### ISSUE TITLE
new flutter 1.7 update after find this issue

### ISSUE THREAD

**Issue by mitesh77** [DavBfr/dart_pdf#100]
Launching lib\main.dart on Nokia 6 1 Plus in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
file:///C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/printing-2.0.4/lib/src/asset_utils.dart:49:27: Error: The argument type 'Future<void> Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'Future' is from 'dart:async'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.removeListener(listener);
                          ^
file:///C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/printing-2.0.4/lib/src/asset_utils.dart:64:32: Error: No named parameter with the name 'onError'.
  stream.addListener(listener, onError: errorListener);
                               ^^^^^^^
file:///C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.2.5/lib/photo_view.dart:279:24: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.addListener(listener);
                       ^
file:///C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.2.5/lib/photo_view.dart:281:29: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      stream.removeListener(listener);
                            ^
Compiler failed

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugArm64'.
> Process 'command 'C:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by MarcelEdward** [comment]
Getting the same issue, while trying to upgrade to flutter 1.7

**Comment by arv1989** [comment]
Yes this  issues exists . 

In asset_utils.dart the code used to create the listener is 

`  Future<void> listener(ImageInfo image, bool sync) async {
    final PdfImage result =
        await pdfImageFromImage(pdf: pdf, image: image.image);
    if (!completer.isCompleted) {
      completer.complete(result);
    }
    stream.removeListener(ImageStreamListener(listener));
  }`

But in the updated flutter Stream (image_stream.dart) the add listener and remove listener methods accepts only ImageStreamListener
`
  void addListener(ImageStreamListener listener) {}
  void setCompleter(ImageStreamCompleter value) {)
`
It can be resolved by changing the parameters passed to these functions as ImageStreamCompleter.

**Comment by DavBfr** [comment]
Version 2.1 should fix the issue.

**Comment by PaitoAnderson** [comment]
Not sure if it's related, but I got this error now with Flutter 1.7 and Printing 2.1:
```
Compiler message:
file:///Users/paitoanderson/Developer/flutter/.pub-cache/hosted/pub.dartlang.org
/printing-2.1.0/lib/src/widgets.dart:33:11: Error: No named parameter with the
name 'compress'.
          compress: compress,
          ^^^^^^^^
Compiler failed on
```

**Comment by robospot** [comment]
> Not sure if it's related, but I got this error now with Flutter 1.7 and Printing 2.1:
> 
> ```
> Compiler message:
> file:///Users/paitoanderson/Developer/flutter/.pub-cache/hosted/pub.dartlang.org
> /printing-2.1.0/lib/src/widgets.dart:33:11: Error: No named parameter with the
> name 'compress'.
>           compress: compress,
>           ^^^^^^^^
> Compiler failed on
> ```
> 
> **Update: Disregard, `flutter upgrade` fixed it.**

same issue:
`Compiler message:
file:///C:/Users/Timak/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/printing-2.1.2/lib/src/widgets.dart:33:11: Error: No named parameter with the name 'compress'.
          compress: compress,
          ^^^^^^^^`
flutter upgrade does not help.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.885], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

**Comment by ethanliew** [comment]
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

Package version: Printing-2.1.0

I cloned latest git source code and getting ImageStreamListener class not found......

Compiler message:
pkg/printing-2.1.0/lib/src/asset_utils.dart:43:3: Error: 'ImageStreamListener' isn't a type.
  ImageStreamListener listener;
  ^^^^^^^^^^^^^^^^^^^
pkg/printing-2.1.0/lib/src/asset_utils.dart:44:14: Error: Method not found: 'ImageStreamListener'.
  listener = ImageStreamListener((ImageInfo image, bool sync) async {
             ^^^^^^^^^^^^^^^^^^^
Compiler terminated unexpectedly.
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      17.2s
Gradle task assembleRelease failed with exit code 1

Please help

**Comment by DavBfr** [comment]
Update to flutter 1.7+, run: 
```shell
flutter upgrade
```
