### ISSUE TITLE
Kurdish Language Problome !

### ISSUE THREAD

**Issue by AkamBarznji** [DavBfr/dart_pdf#1001]
Hello everyone,

i got this problome ! i use Kurdish language

https://drive.google.com/file/d/1-f9ljOkvp9Vr7zoorMpuhM1iigRKtQS7/view?usp=sharing

My words in kurdish language was damaged only in kurdish in arabic + English there's no issue!

for example one of words I selected in above pic is : شیوازی گەیاندن ١
٢-ژمارەی وەرگر

those images and every word in kurdish language was damaged !

Thanks for help

**Comment by DavBfr** [comment]
Relates to #198
