### ISSUE TITLE
TextField value vs. TextField child widget

### ISSUE THREAD

**Issue by BerlinLion** [DavBfr/dart_pdf#1002]
**Describe the bug**

When creating a Textfield, there should be a difference between the value and the child. Obviously the coders, who are about top deprecate the good concept, are not aware of the difference between the value and the child of a textfield widget. The value should be kept hidden. It's just the value of the field, which is not necessarily what you want to show on the document. Whereas the child widget, is what you want to show on the document. Besides, obviously the rendering of the color is buggy, since it doesn't recognize the opacity at all, but uses obviously a jpeg encoding, which has no opacity in its codec at all. You should better use png or other codecs with opacity values.
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
I don't understand what you mean.

**Comment by BerlinLion** [comment]
When you create a textfield in the pdf, you have two variables, which you
can set.
1. Value
2. Child

In the newest version, you are about to deprecate the "child" variable and
replace it fully with the "value" variable.
And you just print out the value as text.

But most of the times, you don't want to orint the value as text, but the
value looks much different, than what you want to print out BASED ON THAT
value. For example you have a yes or no as value, but want to print out its
value as a check-i on or as a X-icon, instead of printing out "yes" or "no"
as text.

But in the new version, you force the value to be printed in the odf
document as text and this us wrong. It's not even possible to give that
text the color "transparent" to hide it away at least.

This change is a total fail in my opinion.

Best regards,
Hamid Aminirad 🙂

David PHAM-VAN ***@***.***> schrieb am So., 10. Apr. 2022,
13:00:

**Comment by BerlinLion** [comment]
When you create a textfield for the pdf, you have two variables, which you
can set.
1. Value
2. Child

In the newest version, you are about to deprecate the "child" variable and
replace it fully with the "value" variable.
And you just print out the value as text.

But most of the times, you don't want to print the value as text, but the
value looks much different, than what you want to print out BASED ON THAT
value. For example you have a "true" or "false" as value, but want to print
out its value as a check-icon or as a X-icon, instead of printing out "yes"
or "no" as text.

But in the new version, you force the value to be printed in the pdf
document as text and this is basically wrong. It's not even possible to
give that text the color "transparent" to hide it away at least and print
only the child widget.

So for the future releases you plan obviously even to deprecate the
variable "child" fully and then you can only have a text and there is then
no difference to the text-widget and then you will fully deprecate the
textfield, just because your coders obviously didn't understand the
difference between the textfield and text. Most likely because they
themselves don't use pdf-creation with this library.

However this change-development is a total fail in my opinion.

Best regards,
Hamid Aminirad 🙂

**Comment by DavBfr** [comment]
@BerlinLion I understand. And totally agree with you. I don't plan to deprecate the `child` property.

**Comment by BerlinLion** [comment]
But why is then the value being shown as text in the pdf, forcibly? It
wasn't possible for me to hide it away, even mit a color with 0 opacity. :)

**Comment by BerlinLion** [comment]
And besides, I took a look inside the code, and the value is being
rendered. It shouldn't be rendered at all actually. Only the child
variable-widget should be rendered, but not the value. The value should
only be an object or a String or the like. But not be rendered at all.

**Comment by DavBfr** [comment]
Ok, while you're in the code, you can change and provide a PR. It will be easier to see what you need.
Thanks.

**Comment by BerlinLion** [comment]
In your library in the file forms.dart, between the lines 295 and 308 is obviously the part, where the string of the value is forcibly printed out. The string of the variable "value" should not be printed, but only be saved as a variable inside the pdf-document. Here's the screenshot of the code.

![Bildschirmfoto 2022-04-27 um 10 49 26](https://user-images.githubusercontent.com/26392032/165482069-3a203c2b-a722-4b38-a9ff-8996edeb88a3.png)


And here some screenshots of the generated pdf-documents, where you can see, that the values are being forcibly printed out and I have tried at the zip-code and city, to make the forcibly printed variable value of the Textfield, transparent, but it's being turned to white instead of becoming transparent. And it's not even possible to put that printed variable "value" in the background, so that it's over rendered by the desired content of the "child" variable. There's no way to work around this **BUG**. Please fix it.

<img width="319" alt="Bildschirmfoto 2022-04-27 um 11 11 37" src="https://user-images.githubusercontent.com/26392032/165485534-5addae5a-04c9-46d2-8f6e-d0b2a0375949.png">
<img width="839" alt="Bildschirmfoto 2022-04-27 um 11 11 58" src="https://user-images.githubusercontent.com/26392032/165485552-884cc8da-6632-4ca0-9dba-37a04d6eebcf.png">
<img width="252" alt="Bildschirmfoto 2022-04-27 um 11 12 14" src="https://user-images.githubusercontent.com/26392032/165485571-dd2406b6-7448-48cc-9b21-08ecaf5e7551.png">
<img width="255" alt="Bildschirmfoto 2022-04-27 um 11 14 52" src="https://user-images.githubusercontent.com/26392032/165485610-76ae27d6-acc6-415f-9ba6-1cd01d6b4800.png">

**Comment by BerlinLion** [comment]
This is another screenshot and the related code, which causes the bug to clarify things a bit more.

<img width="540" alt="Bildschirmfoto 2022-04-27 um 12 47 41" src="https://user-images.githubusercontent.com/26392032/165502635-a0e69480-da76-4214-932b-4693012ed8fb.png">

![Bildschirmfoto 2022-04-27 um 12 53 00](https://user-images.githubusercontent.com/26392032/165502932-cdd648b2-1954-4e47-9796-7cdde6d96628.png)

**Comment by BerlinLion** [comment]
I've found a workaround, which is but not really a solution, but at least, it makes the value to stay hidden. This issue is basically caused only with the last textfield-widget-element in a column widget.
To make the "value" not to be shown, you can add a SizedBox after the textfield-widget but still inside the column-widget-array, which should have a height at least, of the same fontsize of your text, plus 2 for linespacing. In my case it was a sizedbox with the height of 13, that did the trick.
