### ISSUE TITLE
Arguement fontFamily not present in TextStyle, 'package:money/api/pdf_api.dart';

### ISSUE THREAD

**Issue by chetanshivaji** [DavBfr/dart_pdf#1003]
FontFamily  not present as shown blow.

 TextStyle(
    fontSize: 15,
    fontWeight: FontWeight.bold,
    fontFamily: tableHeadingFontFamily,
  );

(new) TextStyle TextStyle({
  bool inherit = true,
  PdfColor? color,
  Font? font,
  Font? fontNormal,
  Font? fontBold,

How can I add font family to Text Style coming from PDF3.7.1

**Comment by DavBfr** [comment]
You can't use FontFamily, the PDF library needs a ttf file.
