### ISSUE TITLE
getting Exception('Unable to guess the image type ${bytes.length} bytes') while fetching image from internet

### ISSUE THREAD

**Issue by GayeKone222** [DavBfr/dart_pdf#1005]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
which image?

**Comment by kostas95** [comment]
Im facing the same issue. When I run my app in the localhost everything works fine. But in the deployed app on the server, this error occurs. I've removed all the images from my pdf, but the error still happens.

I have no idea what's wrong

The following is the error log from the console

```
Uncaught Exception: Unable to guess the image type 3308 bytes
    at Object.wrapException (https://myapp/main.dart.js:9294:17)
    at Object.MemoryImage_MemoryImage (https://myapp/main.dart.js:86597:17)
    at https://myapp.app/main.dart.js:96130:49
    at _wrapJsFunctionForAsync_closure.$protected (https://myapp.app/main.dart.js:11903:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://myapp.app/main.dart.js:127292:12)
    at _awaitOnObject_closure.call$1 (https://myapp/main.dart.js:127280:32)
    at _RootZone.runUnary$2$2 (https://myapp/main.dart.js:130291:18)
    at _RootZone.runUnary$2 (https://myapp/main.dart.js:130295:19)
    at _Future__propagateToListeners_handleValueCallback.call$0 (https://myapp/main.dart.js:128261:51)
    at Object._Future__propagateToListeners (https://myapp/main.dart.js:12159:93)
```

**Comment by DavBfr** [comment]
Print the image data to the console, as a string. I'm guessing it's a server error.

```dart
print(String.fromCodeUnits(bytes))
```

**Comment by kostas95** [comment]
Ok I finally found out the problem. I was using the `networkImage(logoPath)` to load an asset image.

I changed it to `imageFromAssetBundle(logoPath)` and now it's working.

The weird thing in this case was that in localhost no error was shown as I mentioned before.

Thanks for your time

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by 565537905qqcom** [comment]
各位好!
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:docx_template/docx_template.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter_pdfview/flutter_pdfview.dart';

import 'dart:typed_data';

class PdfViewer extends StatefulWidget {
  final Map<String, dynamic> template;
  final List<Map<String, dynamic>> bankDetailsList;

  const PdfViewer({Key? key, required this.template, required this.bankDetailsList})
      : super(key: key);

  @override
  _PdfViewerState createState() => _PdfViewerState();
}

class _PdfViewerState extends State<PdfViewer> {
  String? docxFilePath;
  String? pdfFilePath;

  @override
  void initState() {
    super.initState();
    final contractNumber = widget.bankDetailsList.isNotEmpty ? widget.bankDetailsList.first['contract_number'] : '';
    _generatePdfFromTemplate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Word Viewer'),
      ),
      body: pdfFilePath == null
          ? Center(child: CircularProgressIndicator())
          : PDFView(
              filePath: pdfFilePath!,
              enableSwipe: true,
              swipeHorizontal: true,
              autoSpacing: false,
              pageFling: false,
              onRender: (_pages) {
                setState(() {});
              },
              onError: (error) {
                print(error.toString());
              },
              onPageError: (page, error) {
                print('$page: ${error.toString()}');
              },
              onViewCreated: (PDFViewController pdfViewController) {
                // _controller.complete(pdfViewController);
              },
              onPageChanged: (int? page, int? total) {
                print('page change: $page/$total');
              },
            ),
    );
  }
  Future<void> _generatePdfFromTemplate() async {
    try {

    
      // 从模板文件中创建 DocxTemplate 实例
      final docx = await DocxTemplate.fromBytes(await File(widget.template['pdfFilePath']).readAsBytes());
      
      // 准备图像数据
      final imageBytes = await File(widget.template['sealImagePath']).readAsBytes();

    

      final listNormal = ['Foo', 'Bar', 'Baz'];
      final listBold = ['ooF', 'raB', 'zaB'];
      final contentList = <Content>[];
      final bold = listBold.iterator;
      for (var n in listNormal) {
        bold.moveNext();
        final plainContent = PlainContent('value')
          ..add(TextContent('normal', n))
          ..add(TextContent('bold', bold.current));
        contentList.add(plainContent);
      }

      Content content = Content();
      content
        ..add(TextContent('docname', 'Simple docname'))
        ..add(TextContent('passport', 'Passport NE0323 4456673'))
        ..add(TableContent('table', [
          RowContent()
            ..add(TextContent('key1', 'Paul'))
            ..add(TextContent('key2', 'Viberg'))
            ..add(TextContent('key3', 'Engineer'))
            ..add(ImageContent('img', imageBytes)),
          RowContent()
            ..add(TextContent('key1', 'Alex'))
            ..add(TextContent('key2', 'Houser'))
            ..add(TextContent('key3', 'CEO & Founder'))
            ..add(ListContent('tablelist', [
              TextContent('value', 'Mercedes-Benz C-Class S205'),
              TextContent('value', 'Lexus LX 570')
            ]))
            ..add(ImageContent('img', imageBytes))
        ]))
        ..add(ListContent('list', [
          TextContent('value', 'Engine')
            ..add(ListContent('listnested', contentList)),
          TextContent('value', 'Gearbox'),
          TextContent('value', 'Chassis')
        ]))
        ..add(ListContent('plainlist', [
          PlainContent('plainview')
            ..add(TableContent('table', [
              RowContent()
                ..add(TextContent('key1', 'Paul'))
                ..add(TextContent('key2', 'Viberg'))
                ..add(TextContent('key3', 'Engineer')),
              RowContent()
                ..add(TextContent('key1', 'Alex'))
                ..add(TextContent('key2', 'Houser'))
                ..add(TextContent('key3', 'CEO & Founder'))
                ..add(ListContent('tablelist', [
                  TextContent('value', 'Mercedes-Benz C-Class S205'),
                  TextContent('value', 'Lexus LX 570')
                ]))
            ])),
          PlainContent('plainview')
            ..add(TableContent('table', [
              RowContent()
                ..add(TextContent('key1', 'Nathan'))
                ..add(TextContent('key2', 'Anceaux'))
                ..add(TextContent('key3', 'Music artist'))
                ..add(ListContent(
                    'tablelist', [TextContent('value', 'Peugeot 508')])),
              RowContent()
                ..add(TextContent('key1', 'Louis'))
                ..add(TextContent('key2', 'Houplain'))
                ..add(TextContent('key3', 'Music artist'))
                ..add(ListContent('tablelist', [
                  TextContent('value', 'Range Rover Velar'),
                  TextContent('value', 'Lada Vesta SW Sport')
                ]))
            ])),
        ]))
        ..add(ListContent('multilineList', [
          PlainContent('multilinePlain')
            ..add(TextContent('multilineText', 'line 1')),
          PlainContent('multilinePlain')
            ..add(TextContent('multilineText', 'line 2')),
          PlainContent('multilinePlain')
            ..add(TextContent('multilineText', 'line 3'))
        ]))
        ..add(TextContent('multilineText2', 'line 1\nline 2\n line 3'))
        ..add(ImageContent('img', imageBytes));
      // 生成 Word 文档，根据传入的 Content 对象进行替换占位符
      final docGenerated = await docx.generate(content);

      // print('docGenerated的类型是：${docGenerated.runtimeType}');


      // 获取存储目录
      final directory = await getApplicationDocumentsDirectory();
      // 生成路径
      final outputFile = File('${directory.path}/generated_docx_with_replaced_content.docx');
        
      if (docGenerated != null) {
        // 写入文件
        await outputFile.writeAsBytes(docGenerated);
 
      // 创建 PDF 文档
      final pdf = pw.Document();

      // 从 Word 文件中读取内容，并添加到 PDF 文档中
      final wordFile = File(outputFile.path);
      
      print('Word 文件路径: ${wordFile.path}');

      // 将 Word 文件内容转换为 Uint8List
      final wordBytes = await wordFile.readAsBytes();

      print('Word 文件内容: $wordBytes');
      
      // 使用临时文件创建 pw.Image
        final tempImage = pw.MemoryImage(
          Uint8List.fromList(wordBytes),
        );

        // 添加图像到 PDF 文档中
        pdf.addPage(
          pw.Page(
            build: (pw.Context context) {
              return pw.Center(
                child: pw.Image(tempImage),
              );
            },
          ),
        );

        // 保存 PDF 文件路径以便稍后使用
        setState(() {
          pdfFilePath = outputFile.path;
        });
      }
  } catch (e, stackTrace) {
    print('Exception: $e');
    print('StackTrace: $stackTrace'); // 调用方法获取堆栈跟踪
    }
  }
} 此为我的代码,为什么会报错I/flutter ( 3281): Word 文件路径: /data/user/0/com.example.my_flutter_project/app_flutter/generated_docx_with_replaced_content.docx
I/flutter ( 3281): Word 文件内容: [80, 75, 3, 4, 20, 0, 0, 8, 8, 0, 152, 69, 58, 236, 177, 192, 13, 16, 177, 1, 0, 0, 163, 9, 0, 0, 19, 0, 0, 0, 91, 67, 111, 110, 116, 101, 110, 116, 95, 84, 121, 112, 101, 115, 93, 46, 120, 109, 108, 205, 86, 73, 79, 219, 64, 20, 190, 87, 226, 63, 88, 115, 69, 241, 4, 14, 168, 66, 113, 56, 116, 57, 2, 18, 169, 212, 235, 100, 252, 236, 76, 59, 155, 230, 189, 0, 249, 247, 125, 182, 131, 169, 82, 136, 75, 179, 148, 139, 37, 107, 252, 45, 111, 245, 76, 174, 30, 157, 205, 238, 33, 161, 9, 190, 16, 103, 249, 88, 100, 224, 117, 40, 141, 175, 11, 241, 109, 246, 117, 244, 81, 100, 72, 202, 151, 202, 6, 15, 133, 88, 1, 138, 171, 233, 201, 135, 201, 108, 21, 1, 51, 70, 123, 44, 196, 130, 40, 94, 74, 137, 122, 1, 78, 97, 30, 34, 120, 62, 169, 66, 114, 138, 248, 53, 213, 50, 42, 253, 83, 213, 32, 207, 199, 227, 11, 169, 131, 39, 240, 52, 162, 134, 67, 76, 39, 55, 108, 32, 153, 18, 178, 91, 149, 232, 90, 57, 214, 145, 122, 137, 20, 220, 119, 103, 165, 33, 112, 183, 41, 68, 60, 203, 153, 84, 100, 159, 58
I/flutter ( 3281): Exception: Exception: Unable to guess the image type 1311710 bytes
I/flutter ( 3281): StackTrace: #0      new MemoryImage (package:pdf/src/widgets/image_provider.dart:103:7)
I/flutter ( 3281): #1      _PdfViewerState._generatePdfFromTemplate (package:my_flutter_project/erp/sales/contract/pdf_viewer.dart:187:30)
I/flutter ( 3281): <asynchronous suspension>.请能帮忙解决一下吗?盼复!万分感谢!
