### ISSUE TITLE
Getting message 'unable to display document' on tablet (android)

### ISSUE THREAD

**Issue by GayeKone222** [DavBfr/dart_pdf#1006]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
What version of Android is it?
