### ISSUE TITLE
How can I add dot value to the linear graph?

### ISSUE THREAD

**Issue by Sardor6628** [DavBfr/dart_pdf#1007]
var chart1 = pw.Container(
      margin: pw.EdgeInsets.symmetric(vertical: 4, horizontal: 12),
      height: 30,
      child: pw.Container(
          child: pw.Chart(
        grid: pw.CartesianGrid(
          xAxis: pw.FixedAxis.fromStrings([
            for (int i = 0; i < dataset.length; i++)
              '${DateFormat("yy.MM.dd\n  HH:mm").format(dates[i])}'
          ],
              margin: 1,
              color: PdfColors.white,
              textStyle: pw.Theme.of(context)
                  .defaultTextStyle
                  .copyWith(fontSize: 6, color: PdfColors.black)),
          yAxis: pw.FixedAxis([0, 50, 100],
              color: PdfColors.white,
              textStyle: pw.Theme.of(context)
                  .defaultTextStyle
                  .copyWith(fontSize: 8, color: PdfColors.white)),
        ),
        datasets: [
          pw.LineDataSet(
            color: PdfColors.blue400,
            pointColor: PdfColors.black,
            pointSize: 2,
            legend: 'chest',
            data: List<pw.LineChartValue>.generate(
              dataset.length,
              (i) {
                final num v = dataset[i];
                return pw.LineChartValue(i.toDouble(), v.toDouble());
              },
            ),
          ),
        ],
      )));

  return chart1;

**Comment by Sardor6628** [comment]
@DavBfr  Hello, is there a way of adding a dot value to the graph in the package?

**Comment by DavBfr** [comment]
What's a dot value?

**Comment by Sardor6628** [comment]
![Screen Shot 2022-04-14 at 18 00 27](https://user-images.githubusercontent.com/39268406/163395773-396eebf0-17e7-41bf-90b8-f8dd0b3fa8a8.png)
@DavBfr  now it looks like this. I want a value to be displayed above the dot.

**Comment by DavBfr** [comment]
That's an improvement to make.

**Comment by Sardor6628** [comment]
I see, @DavBfr  is there any alternative that I can use now? I need to finish function implementation by this week.  So I would be very glad for any advice

**Comment by Sardor6628** [comment]
![Screen Shot 2022-04-14 at 18 16 30](https://user-images.githubusercontent.com/39268406/163398699-76b4bfec-3a88-4230-babd-7b9b49fbe0bb.png)
I would like to get a graph like this.

**Comment by DavBfr** [comment]
There is no support for drawing values.
Can be related to #1000 and #838
