### ISSUE TITLE
Display correctly a dynamic HTML code in a paragraph

### ISSUE THREAD

**Issue by theFreeman96** [DavBfr/dart_pdf#1008]
Hi, I'm new to programming and I'm trying to code a simple app to render a few hundred songs from a local db.
I want to display an HTML string (which is the songText from local db) inside a paragraph in my PDF files.
Those songText are mainly ordered lists.

The problem is that the PDF display even the HTML tags so I used a package that converts HTML to markdown.
While it works (in a way), I think it's not ok and there are some problems.
Is there a method or a widget to display correctly HTML code inside a paragraph or text in a PDF file?

Here's my paragraph code, I'm looking for suggestions:

            pw.Paragraph(
              padding: const pw.EdgeInsets.only(top: 5.0 * PdfPageFormat.mm),
              // currenlty I'm using this other package but it would be neat to have an HTML widget
              text: html2md.convert(songText),
              style: pw.TextStyle(fontSize: textSize, lineSpacing: textHeight),
            ),

Let me know if you need more code or screenshots.
And thanks for your work!!

**Comment by DavBfr** [comment]
The best would be to parse the HTML content for semantic data and render it your way.

**Comment by tffajari** [comment]
I have the sampe problem here, did anyone have the solution?

**Comment by theFreeman96** [comment]
Hi @tffajari , what's going on with your code?
In my case it worked after tweaking a bit of html2md custom rules.
It's not perfect but it works, I hope it helps you out!



            
          pw.Paragraph(
            padding: const pw.EdgeInsets.only(top: 5.0 * PdfPageFormat.mm),
            text: html2md.convert(songText, rules: [
              // Emphasis
              html2md.Rule('emphasis', filters: ['em', 'i'],
                  replacement: (content, node) {
                if (content.trim().isEmpty) return '';
                return content.replaceFirst("\n", "");
              }),
              // Strong
              html2md.Rule('strong', filters: ['strong', 'b'],
                  replacement: (content, node) {
                if (content.trim().isEmpty) return '';
                return content;
              })
            ]),
            style: pw.TextStyle(fontSize: textSize, lineSpacing: textHeight),
          ),

If you check [this other package documentation](https://pub.dev/packages/html2md) you'll have an idea of whitch rules are available.
