### ISSUE TITLE
Support retrieving the page count from the PDF

### ISSUE THREAD

**Issue by hillelcoren** [DavBfr/dart_pdf#1011]
The PdfPreview widget has a pages property which can be used to change the pages but I don't believe it's currently possible to determine the number of pages in the PDF if you're previewing an external PDF file.

One option may be to add a pageCount property to the PdfPageFormat class and then set it in the onPageFormatChanged callback.

If there's already a way to do this I'd very much appreciate to know how.

Thanks for the excellent package!

**Comment by DavBfr** [comment]
The raster method is used to create the images of the pages. If you ask the library to raster all the PDF, you'll get the number of pages.

Something like:

```dart
final pdf = await File('document.pdf).readAsBytes();
final pages = await Printing.raster(pdf, dpi:5).toList();
print('The document has ${pages.length} pages');
```

Use a low DPI number if you don't plan to display the images.
