### ISSUE TITLE
Repeat Header in every page of PDF

### ISSUE THREAD

**Issue by KrishnaSoftwareSolution** [DavBfr/dart_pdf#1013]
In case of multipage pages we want to repeat header at every page.

**Comment by DavBfr** [comment]
The multipage object has a header callback for that.

**Comment by KrishnaSoftwareSolution** [comment]
header is displaying only on first page can you please explain with example

**Comment by DavBfr** [comment]
Check this example: https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/document.dart
