### ISSUE TITLE
Duplex Output if i click again to Save Button

### ISSUE THREAD

**Issue by berkayhh** [DavBfr/dart_pdf#1016]
Home_controller.dart
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:polsterhof_auftrag/app/routes/app_pages.dart';
import 'package:printing/printing.dart';

var depo = GetStorage();

class HomeController extends GetxController {
  ///https://kkspro.de/license/license-erol1.json
  var now = DateTime.now();
  var formatterDate = DateFormat('dd/MM/yy');
  var formatterTime = DateFormat('kk:mm');
  late var dosyaAdresi1 = "".obs;
  late var dosyaAdresi2 = "".obs;
  late var dosyaAdresi3 = "".obs;
  late var dosyaAdresi4 = "".obs;
  late var dosyaAdresi5 = "".obs;
  late var dosyaAdresi6 = "".obs;
  var directoryss = "".obs;
  final pdf = pw.Document();
  TextEditingController namet = TextEditingController();
  TextEditingController adresset = TextEditingController();
  TextEditingController telefont = TextEditingController();
  TextEditingController abholdatumt = TextEditingController();
  TextEditingController lieferdatumt = TextEditingController();
  TextEditingController firmamaterialt = TextEditingController();
  TextEditingController bestelltt = TextEditingController();
  TextEditingController preist = TextEditingController();
  TextEditingController wasmachent = TextEditingController();
  TextEditingController notizt = TextEditingController();
  late final image = pw.MemoryImage(
    File(dosyaAdresi1.value).readAsBytesSync(),
  );
  late final image2 = pw.MemoryImage(
    File(dosyaAdresi2.value).readAsBytesSync(),
  );
  late final image3 = pw.MemoryImage(
    File(dosyaAdresi2.value).readAsBytesSync(),
  );
  late final image4 = pw.MemoryImage(
    File(dosyaAdresi2.value).readAsBytesSync(),
  );
  late final image5 = pw.MemoryImage(
    File(dosyaAdresi2.value).readAsBytesSync(),
  );
  late final image6 = pw.MemoryImage(
    File(dosyaAdresi2.value).readAsBytesSync(),
  );

  getDirectory() async {
    if (depo.read('fileAdress') == null) {
      String? selectedDirectory = await FilePicker.platform.getDirectoryPath();
      if (selectedDirectory == null) {
        // User canceled the picker
        Get.snackbar("Abgebrochen", "Zielordner Auswahl Abgebrochen",
            snackPosition: SnackPosition.BOTTOM);
      }
      String filepath = "";
      filepath = selectedDirectory.toString().replaceAll(r"\", "/");
      depo.write("fileAdress", filepath);
      print(filepath);
      //print(dosyaAdresi1.value);
    }
    String dir = Directory.current.path;
    String bildadress = dir.replaceAll(r"\", "/");
    dosyaAdresi1.value = bildadress + "/bild/bild2.png";
    dosyaAdresi2.value = bildadress + "/bild/bild2.png";
    dosyaAdresi3.value = bildadress + "/bild/bild2.png";
    dosyaAdresi4.value = bildadress + "/bild/bild2.png";
    dosyaAdresi5.value = bildadress + "/bild/bild2.png";
    dosyaAdresi6.value = bildadress + "/bild/bild2.png";
    //print(dosyaAdresi1.value);
    //print(dosyaAdresi2.value);
  }

  editFileDirectory() async {
    String? selectedDirectory = await FilePicker.platform.getDirectoryPath();
    if (selectedDirectory == null) {
      // User canceled the picker
    }
    String filepath = "";
    filepath = selectedDirectory.toString().replaceAll(r"\", "/");
    depo.write("fileAdress", filepath);
    print(filepath);
  }

  writeonPdf(String name, adresse, telefon, abholdatum, lieferdatum,
      firmamaterial, bestellt, preis, wasmachen, notiz) async {
    String actualDate = formatterDate.format(now);
    String actualTime = formatterTime.format(now);
    pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(8),
        build: (pw.Context context) {
          return <pw.Widget>[
            /*   pw.Watermark(
              child: pw.Image(image2, width: 250, height: 250),
            ), */
            pw.Text(
                'Polsterhof-Auftragannahme ' + actualDate + "-" + actualTime,
                textAlign: pw.TextAlign.center,
                style: const pw.TextStyle(
                  fontSize: 25,
                )),
            pw.Row(children: [
              pw.Container(
                width: 170,
                child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    mainAxisAlignment: pw.MainAxisAlignment.start,
                    children: [
                      pw.Paragraph(text: "Name:"),
                      pw.Text(name.toString()),
                    ]),
              ),
              pw.Container(
                width: 170,
                child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    mainAxisAlignment: pw.MainAxisAlignment.start,
                    children: [
                      pw.Paragraph(text: "Adresse:"),
                      pw.Text(adresse.toString()),
                    ]),
              ),
              pw.Container(
                width: 170,
                child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    mainAxisAlignment: pw.MainAxisAlignment.start,
                    children: [
                      pw.Paragraph(text: "Telefon:"),
                      pw.Text(telefon.toString()),
                    ]),
              ),
            ]),
/* 
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Name:"),
            pw.Text(name.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Adresse:"),
            pw.Text(adresse.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Telefon:"),
            pw.Text(telefon.toString()), */
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Abholdatum - Lieferdatum:"),
            pw.Text(abholdatum.toString() + " - " + lieferdatum.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Material:"),
            pw.Text(firmamaterial.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Bestellt am:"),
            pw.Text(bestellt.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Preis:"),
            pw.Text(preis.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Was machen:"),
            pw.Text(wasmachen.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Notiz:"),
            pw.Text(notiz.toString()),
            pw.Divider(thickness: 1),
            pw.SizedBox(height: 30),
            pw.Column(children: [
              pw.Row(mainAxisAlignment: pw.MainAxisAlignment.center, children: [
                pw.Column(children: [
                  pw.Text("Material"),
                  pw.Image(image, width: 250, height: 250),
                ]),
                pw.SizedBox(width: 30, height: 20),
                pw.Column(children: [
                  pw.Text("Objekt"),
                  pw.Image(image2, width: 250, height: 250),
                ]),
              ]),
              pw.SizedBox(height: 20),
              pw.Row(mainAxisAlignment: pw.MainAxisAlignment.center, children: [
                pw.Column(children: [
                  pw.Text("Bild 1"),
                  pw.Image(image3, width: 250, height: 250),
                ]),
                pw.SizedBox(width: 30, height: 20),
                pw.Column(children: [
                  pw.Text("Bild-2"),
                  pw.Image(image4, width: 250, height: 250),
                ]),
              ]),
              pw.SizedBox(height: 20),
              pw.Row(mainAxisAlignment: pw.MainAxisAlignment.center, children: [
                pw.Column(children: [
                  pw.Text("Bild 3"),
                  pw.Image(image5, width: 250, height: 250),
                ]),
                pw.SizedBox(width: 30, height: 20),
                pw.Column(children: [
                  pw.Text("Bild 4"),
                  pw.Image(image6, width: 250, height: 250),
                ]),
              ]),
            ])
          ];
        }));
    String id = "-MitPreis-";
    savePdf(id);
  }

/*   writeonPdfNull(String name, adresse, telefon, abholdatum, lieferdatum,
      firmamaterial, stoffmeter, leder, bestellt, wasmachen, notiz) async {
    String actualDate = formatterDate.format(now);
    String actualTime = formatterTime.format(now);
    pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(8),
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Text('Polsterhof-Auftragannahme' + actualDate + "-" + actualTime,
                textAlign: pw.TextAlign.center,
                style: const pw.TextStyle(
                  fontSize: 20,
                )),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Name:"),
            pw.Text(name.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Adresse:"),
            pw.Text(adresse.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Telefon:"),
            pw.Text(telefon.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Abholdatum - Lieferdatum:"),
            pw.Text(abholdatum.toString() + lieferdatum.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Firma/Material:"),
            pw.Text(firmamaterial.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Stoff-Meter:"),
            pw.Text(stoffmeter.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Leder:"),
            pw.Text(leder.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Bestellt am:"),
            pw.Text(bestellt.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Was machen:"),
            pw.Text(wasmachen.toString()),
            pw.Divider(thickness: 1),
            pw.Paragraph(text: "Notiz:"),
            pw.Text(notiz.toString()),
            pw.Divider(thickness: 1),            
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.center, children: [
              pw.Image(image, width: 250, height: 250),
              pw.SizedBox(width: 10),
              pw.Image(image2, width: 250, height: 250),
            ]),
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.center, children: [
              pw.Image(image3, width: 250, height: 250),
              pw.SizedBox(width: 10),
              pw.Image(image4, width: 250, height: 250),
            ]),
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.center, children: [
              pw.Image(image5, width: 250, height: 250),
              pw.SizedBox(width: 10),
              pw.Image(image6, width: 250, height: 250),
            ]),
          ];
        }));
    String id = "OhnePreis";
    await savePdf(id);
  }
 */
  getFileAdress() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      dialogTitle: "Bitte Image Auswählen",
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png'],
    );
    if (result == null) return;
    PlatformFile file = result.files.single;
    /*  String deneme = file.path!.replaceAll(r"\$", r"/"); */
    dosyaAdresi1.value = file.path!;
    //print(file.path);
    adressDegis(file.path.toString());
    //print(dosyaAdresi1.value);
  }

  getFileAdress2() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      dialogTitle: "Bitte Image Auswählen",
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png'],
    );
    if (result == null) return;
    PlatformFile file = result.files.single;
    /*  String deneme = file.path!.replaceAll(r"\$", r"/"); */
    dosyaAdresi2.value = file.path!;
    //print(file.path);
    adressDegis(file.path.toString());
    //print(dosyaAdresi1.value);
  }

  getFileAdress3() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      dialogTitle: "Bitte Image Auswählen",
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png'],
    );
    if (result == null) return;
    PlatformFile file = result.files.single;
    /*  String deneme = file.path!.replaceAll(r"\$", r"/"); */
    dosyaAdresi3.value = file.path!;
    //print(file.path);
    adressDegis(file.path.toString());
    //print(dosyaAdresi1.value);
  }

  getFileAdress4() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      dialogTitle: "Bitte Image Auswählen",
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png'],
    );
    if (result == null) return;
    PlatformFile file = result.files.single;
    /*  String deneme = file.path!.replaceAll(r"\$", r"/"); */
    dosyaAdresi4.value = file.path!;
    //print(file.path);
    adressDegis(file.path.toString());
    //print(dosyaAdresi1.value);
  }

  getFileAdress5() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      dialogTitle: "Bitte Image Auswählen",
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png'],
    );
    if (result == null) return;
    PlatformFile file = result.files.single;
    /*  String deneme = file.path!.replaceAll(r"\$", r"/"); */
    dosyaAdresi5.value = file.path!;
    //print(file.path);
    adressDegis(file.path.toString());
    //print(dosyaAdresi1.value);
  }

  getFileAdress6() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      dialogTitle: "Bitte Image Auswählen",
      type: FileType.custom,
      allowedExtensions: ['jpg', 'png'],
    );
    if (result == null) return;
    PlatformFile file = result.files.single;
    /*  String deneme = file.path!.replaceAll(r"\$", r"/"); */
    dosyaAdresi6.value = file.path!;
    //print(file.path);
    adressDegis(file.path.toString());
    //print(dosyaAdresi1.value);
  }

  adressDegis(String gelen) {
    String giden = gelen.replaceAll(r"\", "/");
    print(giden);
    // ignore: avoid_print
  }

  savePdf(String fileid) async {
    var now = DateTime.now();
    var formatterDate = DateFormat('dd_MM_yy');
    var formatterTime = DateFormat('kk_mm');
    String actualDate = "_" + formatterDate.format(now);
    String actualTime = formatterTime.format(now);
    String fileadress = depo.read("fileAdress") + "/";
    fileadress.replaceAll(r"\", "/");
    print(fileadress);
    File file = File(fileadress + "${namet.text + actualDate + fileid}.pdf");
    file.writeAsBytesSync(List.from(await pdf.save()));
    print("PDF saved");
    return await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: "${namet.text + actualDate + fileid}-P_Auftrag.pdf");
  }

  /*  savePdf2() async {
    var now = DateTime.now();
    var formatterDate = DateFormat('dd_MM_yy');
    var formatterTime = DateFormat('kk_mm');
    String actualDate = "_" + formatterDate.format(now);
    String actualTime = formatterTime.format(now);
    String fileadress = depo.read("fileAdress") + "/";
    fileadress.replaceAll(r"\", "/");
    print(fileadress);
    File file = File(fileadress +
        "${namet.text + actualTime + actualDate} -OhnePreis- .pdf");
    file.writeAsBytesSync(List.from(await pdf.save()));
    print("PDF saved");
    await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: "${namet.text + actualTime + actualDate}-P_Auftrag.pdf");
  } */
  @override
  Future<void> onInit() async {
    await getDirectory();
    super.onInit();
  }

  @override
  Future<void> onReady() async {
    super.onReady();
    await getDirectory();
  }

  @override
  void onClose() {}
}

Home View 

import 'dart:io';

import 'package:flutter/material.dart';

import 'package:get/get.dart';
import 'package:path_provider/path_provider.dart';

import '../controllers/home_controller.dart';

class HomeView extends GetView<HomeController> {
  @override
  Widget build(BuildContext context) {
    controller.getDirectory();

    return Scaffold(
        appBar: AppBar(
          title: Text('Polsterhof-PDF'),
          centerTitle: true,
        ),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(20.0),
            child: Center(
                /*  width: Get.width,
              height: Get.height, */
                child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  "Auftragsannahme",
                  style: TextStyle(fontSize: 40),
                ),
                TextFormField(
                  controller: controller.namet,
                  decoration: InputDecoration(
                    labelText: "Name:",
                  ),
                ),
                TextFormField(
                  controller: controller.adresset,
                  decoration: InputDecoration(
                    labelText: "Adresse:",
                  ),
                ),
                TextFormField(
                  controller: controller.telefont,
                  decoration: InputDecoration(
                    labelText: "Telefon:",
                  ),
                ),
                TextFormField(
                  controller: controller.abholdatumt,
                  decoration: InputDecoration(
                    labelText: "Abholdatum:",
                  ),
                ),
                TextFormField(
                  controller: controller.lieferdatumt,
                  decoration: InputDecoration(
                    labelText: "Lieferdatum:",
                  ),
                ),
                TextFormField(
                  controller: controller.firmamaterialt,
                  decoration: InputDecoration(
                    labelText: "Material:",
                  ),
                ),
                TextFormField(
                  controller: controller.bestelltt,
                  decoration: InputDecoration(
                    labelText: "Bestellt am:",
                  ),
                ),
                TextFormField(
                  controller: controller.preist,
                  decoration: InputDecoration(
                    labelText: "Preis:",
                  ),
                ),
                TextFormField(
                  controller: controller.wasmachent,
                  decoration: InputDecoration(
                    labelText: "Was machen:",
                  ),
                ),
                TextFormField(
                  maxLines: 5,
                  controller: controller.notizt,
                  decoration: const InputDecoration(
                    labelText: "NOTIZ:",
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(30.0),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          InkWell(
                            onTap: () {
                              controller.getFileAdress();
                            },
                            child: Obx(() => Column(
                                  children: [
                                    Text("Material"),
                                    Image.file(
                                      File(controller.dosyaAdresi1.value),
                                      height: Get.height * 0.2,
                                      width: Get.width * 0.2,
                                    ),
                                  ],
                                )),
                          ),
                          SizedBox(
                            width: 40,
                          ),
                          InkWell(
                            onTap: () {
                              controller.getFileAdress2();
                            },
                            child: Obx(() => Column(
                                  children: [
                                    Text("Objekt"),
                                    Image.file(
                                      File(controller.dosyaAdresi2.value),
                                      height: Get.height * 0.2,
                                      width: Get.width * 0.2,
                                    ),
                                  ],
                                )),
                          ),
                        ],
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          InkWell(
                            onTap: () {
                              controller.getFileAdress3();
                            },
                            child: Obx(() => Column(
                                  children: [
                                    Text("Bild 1"),
                                    Image.file(
                                      File(controller.dosyaAdresi3.value),
                                      height: Get.height * 0.2,
                                      width: Get.width * 0.2,
                                    ),
                                  ],
                                )),
                          ),
                          SizedBox(
                            width: 40,
                          ),
                          InkWell(
                            onTap: () {
                              controller.getFileAdress4();
                            },
                            child: Obx(() => Column(
                                  children: [
                                    Text("Bild 2"),
                                    Image.file(
                                      File(controller.dosyaAdresi4.value),
                                      height: Get.height * 0.2,
                                      width: Get.width * 0.2,
                                    ),
                                  ],
                                )),
                          ),
                        ],
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          InkWell(
                            onTap: () {
                              controller.getFileAdress5();
                            },
                            child: Obx(() => Column(
                                  children: [
                                    Text("Bild 3"),
                                    Image.file(
                                      File(controller.dosyaAdresi5.value),
                                      height: Get.height * 0.2,
                                      width: Get.width * 0.2,
                                    ),
                                  ],
                                )),
                          ),
                          SizedBox(
                            width: 40,
                          ),
                          InkWell(
                            onTap: () {
                              controller.getFileAdress6();
                            },
                            child: Obx(() => Column(
                                  children: [
                                    Text("Bild 4"),
                                    Image.file(
                                      File(controller.dosyaAdresi6.value),
                                      height: Get.height * 0.2,
                                      width: Get.width * 0.2,
                                    ),
                                  ],
                                )),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                /*  Wrap(
                children: [
                  Positioned(
                    child: FloatingActionButton(
                        child: Icon(Icons.payment), onPressed: () {}),
                    bottom: 30,
                    right: 20,
                  ),
                ],
              ), */
                Column(
                  children: [
                    Text("Zielordner \n Ändern"),
                    IconButton(
                        onPressed: (() {
                          controller.editFileDirectory();
                        }),
                        icon: Icon(Icons.file_open_rounded)),
                  ],
                ),
              ],
            )),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            await controller.writeonPdf(
              controller.namet.text,
              controller.adresset.text,
              controller.telefont.text,
              controller.abholdatumt.text,
              controller.lieferdatumt.text,
              controller.firmamaterialt.text,
              controller.bestelltt.text,
              controller.preist.text,
              controller.wasmachent.text,
              controller.notizt.text,
            );

            /* Get.defaultDialog(
              title: "Ohne Preis Ausdrucken ? ",
              content: Container(
                child: Column(
                  children: [
                    Text("Möchten Sie auch ohne Preis Version Ausdrucken ?"),
                    ElevatedButton(
                      onPressed: () async {
                        await controller.writeonPdfNull(
                          controller.namet.text,
                          controller.adresset.text,
                          controller.telefont.text,
                          controller.abholdatumt.text,
                          controller.lieferdatumt.text,
                          controller.firmamaterialt.text,
                          controller.stoffmetert.text,
                          controller.ledert.text,
                          controller.bestelltt.text,
                          controller.wasmachent.text,
                          controller.notizt.text,
                        );
                        Get.back();
                      },
                      child: Text("JA"),
                    ),
                    ElevatedButton(
                      onPressed: () {
                        Get.back();
                      },
                      child: Text("NEIN"),
                    ),
                  ],
                ),
              ),
            ); */
          },

          child: Icon(Icons.save),
          //Test
        ));
  }
}

Debug : 
 Restarted application in 339ms.
flutter: true
flutter: License Valid
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /home
[GETX] Instance "HomeController" has been created
[GETX] Instance "HomeController" has been initialized
flutter: C:/Users/burqm/Desktop/Polsterhof-App
flutter: Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
flutter: C:/Users/burqm/Desktop/Polsterhof-App/
flutter: PDF saved
flutter: C:/Users/burqm/Desktop/Polsterhof-App/

<img width="1932" alt="Bildschirmfoto 2022-05-02 um 23 48 07" src="https://user-images.githubusercontent.com/6962686/166332987-df917458-88a9-485d-a34b-b4e399e8abf0.png">

<img width="298" alt="Bildschirmfoto 2022-05-02 um 23 47 55" src="https://user-images.githubusercontent.com/6962686/166332966-5b52ddf1-fc9a-4cee-9bf6-70c2caa47bf0.png">

flutter: PDF saved
<img width="279" alt="Bildschirmfoto 2022-05-02 um 23 47 26" src="https://user-images.githubusercontent.com/6962686/166332927-7808651f-c187-44fb-b3b8-517ae59c760a.png">

Note: If i reload the App , its working nice , its creating 2 page only how i want , but if edit the Data and click again to save button its creating with correct datas but adding 2 Blank page more , total 4 Page but 2 is blank and first 2 page is filled. if i click again to save with another datas , datas incomming but with 6 Pages 4 are blank and first 2 is filled, i think its a cache Problem or i have to reset the Memory or Page Count. 
Thanks for Feedback !

**Comment by DavBfr** [comment]
Because you reuse the Document() object. So it keeps adding pages to it.

**Comment by burqman01** [comment]
> Because you reuse the Document() object. So it keeps adding pages to it.

Hey DavBfr , Thanks for your Feedback, but can u explain it how i reusing the Document object ? or how can i fix that Problem ? 
King Regards !

**Comment by burqman01** [comment]
Can i close the Proccess adding the Pages end line on pdf.addpage ()  ? 
with return;  ?
<img width="900" alt="Bildschirmfoto 2022-05-08 um 20 26 41" src="https://user-images.githubusercontent.com/6962686/167310144-411c4e2e-6801-4e68-bbea-00d582f096ca.png">

Thank u so much for ur Feedback !

**Comment by DavBfr** [comment]
Each time you create a new PDF document, you have to create a new `Document()` object.

**Comment by burqman01** [comment]
> 
Allright, i would know how can i do this :D  ? or what is the False Code Block, what can i edit in my Code, u saw my Completly Code , can u give me a tick from that ? 
Thanks  @DavBfr !

**Comment by DavBfr** [comment]
Remove this line: `final pdf = pw.Document();` and move it to the method `writeonPdf(...)` then add the pdf parameter to each methods where it's needed.

**Comment by berkayhh** [comment]
GREATTT !! Its Working ! Thanks @DavBfr !!!!! 👍🏻 👍🏻 👍🏻  :):):):)

**Comment by berkayhh** [comment]
Thanks for your Support , u are a Great Man !
