### ISSUE TITLE
Capture PDF page names

### ISSUE THREAD

**Issue by garrettApproachableGeek** [DavBfr/dart_pdf#1017]
It would be great if when using the `pdf_crypto` package that the call
```
final pdf = Document.load(
  PdfDocumentParser(template),
);
```
would be able to parse the page names from an existing PDF

**Describe the solution you'd like**

The DocumentParser parses the page names and the names are exposed per page of the pdf

**Describe alternatives you've considered**

- Using https://pub.dev/packages/syncfusion_flutter_pdf to parse the PDF to get the page names, but I have already paid for pdf_crypto and it would be great to keep it to a single parsing of the PDF.
- Have the user type in the page names

**Additional context**

The data for page names that I would expect to be extracted is shown by Mac Preview in the screenshot is `A100`, `A101`, `A102`, and `A103`
![Screen Shot 2022-05-02 at 2 57 42 PM](https://user-images.githubusercontent.com/68708352/166334080-a0027238-62a8-424d-9bcc-9b875df1c1d0.png)

**Comment by DavBfr** [comment]
Do you have an example PDF file with page names? I didn't know it existed!

**Comment by garrettApproachableGeek** [comment]
Here are two pdfs:
This one has the page names/labels A100, A101, A102
[example_with_page_labels.pdf](https://github.com/DavBfr/dart_pdf/files/8606439/example_with_page_labels.pdf)
This one is the same PDF without the page names/labels, hope that helps
[example_no_page_labels.pdf](https://github.com/DavBfr/dart_pdf/files/8606440/example_no_page_labels.pdf)

**Comment by DavBfr** [comment]
And what do you want to do with these labels?

**Comment by garrettApproachableGeek** [comment]
Extract the labels from an existing PDF. Allowing them to be used within an app, without the end user having to write them out.

**Comment by DavBfr** [comment]
@garrettApproachableGeek The generator part is done in the pdf library master branch.
