### ISSUE TITLE
FullPage widget in Multipage with header and footer causes error

### ISSUE THREAD

**Issue by otmi100** [DavBfr/dart_pdf#1018]
**Describe the bug**

Creating a FullPage widget inside a MultiPage while having a header and footer results in an exeption.

a4:
Exception: Widget won't fit into the page as its height (728.503937007874) exceed a page height (728.5039370078739). You probably need a SpanningWidget or use a single page layout

a4 landscape:
Exception: Widget won't fit into the page as its height (481.8897637795275) exceed a page height (481.88976377952747). You probably need a SpanningWidget or use a single page layout

**To Reproduce**
```dart
import 'package:test/test.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

void main() async {
  late pw.Document pdf;

  setUpAll(() async {
    pw.Document.debug = true;
    pdf = pw.Document();
  });

  test('create pdf', () {
    pdf.addPage(pw.MultiPage(
        header: (pw.Context context) {
          return pw.Text("Header");
        },
        footer: (pw.Context context) {
          return pw.Text("Footer");
        },
        build: (pw.Context context) => <pw.Widget>[
              pw.FullPage(
                  ignoreMargins: false,
                  child: pw.Rectangle(fillColor: PdfColors.blue))
            ]));
    pdf.save();
  });
}
```

**Expected behavior**
FullPage fits content.

**Screenshots**

**Flutter Doctor**
```
[✓] Flutter (Channel stable, 2.10.5, on Arch Linux 5.17.4-arch1-1, locale de_DE.UTF-8)
    • Flutter version 2.10.5 at /home/mitch/flutter-sd/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (vor 2 Wochen), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/mitch/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 100.0.4896.127 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [x] Linux

**Smartphone (please complete the following information):**
-
**Additional context**
-

**Comment by DavBfr** [comment]
Why would you use FullPage in a MultiPage?

**Comment by otmi100** [comment]
Because I want the child of the FullPage use all available space on that page.
I did noch use document.addPage(Page(..)), because that would leave me without the header/footer. Or am I wrong?

**Comment by DavBfr** [comment]
You can use Page(..) if you need only one page. The header and footer are only convenient for MultiPage because it repeats on each page. On the page's body you can add a header and footer just by creating:
```dart
 Column( children: [ header, Flexible(child: body), footer ] );
```

**Comment by otmi100** [comment]
Thanks for the advise (and of course for the awesome lib btw!). Imho it still sounds like a workaround. 

I do have a multiple page document anyhow (the snipped I posted was just to have minimal reproducible example). Adding a single page between multipages with a "different way" of setting the header creates more code. Also as far as the user is concerned the lib might handle header/footer differently than the "main" area, thus using a Column() might result in a different layout. I guess then prefer the ContrainedBox "workaround". 

Why is using FullPage in a MultiPage not considered a correct way? What is it used for? 

Anyhow I'm happy with the "workarounds" - just wanted to contribute! Feel free to close the issue :)

**Comment by DavBfr** [comment]
It's not a workaround, it's how the header and footer are handled internally.
