### ISSUE TITLE
Image inside BoxDecoration is not obeying shape property.

### ISSUE THREAD

**Issue by ictsolved** [DavBfr/dart_pdf#102]
**Describe the bug**
When there is no image the container is circular but when I use image property it's always rectangular.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pdf.Container(
                      height: 200.0,
                      width: 200.0,
                      decoration: pdf.BoxDecoration(
                        shape: pdf.BoxShape.circle,
                        image: pdf.DecorationImage(
                            image: myImage, fit: pdf.BoxFit.cover),
                      ),
                    )
```

**Expected behavior**
The container should be circular.

**Desktop (please complete the following information):**
 - [ ] Android

**Comment by DavBfr** [comment]
Fixed in Pdf version 1.3.15. Thanks.
