### ISSUE TITLE
Wrong Character Ordering of Burmese Unicode Font when generate PDF 

### ISSUE THREAD

**Issue by waihanko** [DavBfr/dart_pdf#1021]
**I already tried many ways but got same result. I tried following ways**
    

**To Reproduce**

I use ``` pdf: ^3.7.4```

Following link can grab a lot of burmese unicode fonts.
https://github.com/AungMyoKyaw/Myanmar-Unicode-Fonts

- I tried many ways as following.
```dart
 //From Assets
await fontFromAssetBundle('"assets/fonts/myanmar_unicode.ttf"')
.then((value) => myanmarFont = value);

pw.Text('သီဟိုဠ်မှ ဉာဏ်ကြီးရှင်သည်အာယုဝဎ္ဍနဆေးညွှန်းစာကို ဇလွန်ဈေးဘေးဗာဒံပင်ထက် အဓိဋ္ဌာန်လျက် ဂဃနဏဖတ်ခဲ့သည်။',
       style: pw.TextStyle(,
       font: myanmarFont,
       color: PdfColors.grey,
       fontWeight: pw.FontWeight.bold,
       fontSize: 10),
),


//From File
pw.Text('သီဟိုဠ်မှ ဉာဏ်ကြီးရှင်သည်အာယုဝဎ္ဍနဆေးညွှန်းစာကို ဇလွန်ဈေးဘေးဗာဒံပင်ထက် အဓိဋ္ဌာန်လျက် ဂဃနဏဖတ်ခဲ့သည်။',
       style: pw.TextStyle(,
       font: pw.Font.ttf(fontData.buffer.asByteData()
       color: PdfColors.grey,
       fontWeight: pw.FontWeight.bold,
       fontSize: 10),
),


//Theme applied 
pw.Text('သီဟိုဠ်မှ ဉာဏ်ကြီးရှင်သည်အာယုဝဎ္ဍနဆေးညွှန်းစာကို ဇလွန်ဈေးဘေးဗာဒံပင်ထက် အဓိဋ္ဌာန်လျက် ဂဃနဏဖတ်ခဲ့သည်။',),
```

**Expected Result**
![Snipaste_2022-05-04_20-44-48](https://user-images.githubusercontent.com/37291373/166704954-a500b4fb-d058-462a-a0a7-290fc2c7d9c9.jpg)

**Result that I got**
![JYgnt](https://user-images.githubusercontent.com/37291373/166704814-0f85abff-6097-4e11-a4cc-fb0b828b54aa.png)

**Comment by DavBfr** [comment]
Relates to #198
