### ISSUE TITLE
This is not a simple glyph #0 

### ISSUE THREAD

**Issue by gfb-47** [DavBfr/dart_pdf#1025]
**Describe the bug**
I'm using fonts from Google Fonts on my project and once in a hundred I get this error messages, I found this [issue](https://github.com/DavBfr/dart_pdf/issues/157) where you said to update the fonts, I did it (re-downloaded the fonts from Google Fonts and updated on project) and it worked. I just want to share, and also wonder if there is any explanation.

**To Reproduce**
I'm sorry, I don't know what makes this error happen. 

**Expected behavior**
No error should be throwed, and pdf should be generated.

**Screenshots**
<img width="977" alt="Screen Shot 2022-05-06 at 10 00 04" src="https://user-images.githubusercontent.com/46033500/167136282-2910f1d7-c17b-4918-9484-32a744a549e0.png">

**Flutter Doctor**

![Screen Shot 2022-05-06 at 10 07 36](https://user-images.githubusercontent.com/46033500/167137637-a25bb3c8-454a-4b26-94e4-776d3b2757ce.png)

**Desktop (please complete the following information):**
 - [X] iOS
 - [X] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: iPhone 11, Redmi Y2, Others, It will happen on any device

**Additional context**
I have a lot of cards that will become PDF's, there is a specific card which always throw this error, maybe there is some relation with the input from this card to the package (that was my first thought), the thing is, I solved it by just updating the fonts.

**Comment by DavBfr** [comment]
Do you use the latest version of the library?

**Comment by gfb-47** [comment]
I wasn't using it, but I just tested the 3.7.4 and the brand new 3.8.0, and none of them work.

**Comment by DavBfr** [comment]
So do you have a minimal example that reproduces it?

**Comment by HuseynHuseyni** [comment]
> **Describe the bug** I'm using fonts from Google Fonts on my project and once in a hundred I get this error messages, I found this [issue](https://github.com/DavBfr/dart_pdf/issues/157) where you said to update the fonts, I did it (re-downloaded the fonts from Google Fonts and updated on project) and it worked. I just want to share, and also wonder if there is any explanation.
> 
> **To Reproduce** I'm sorry, I don't know what makes this error happen.
> 
> **Expected behavior** No error should be throwed, and pdf should be generated.
> 
> **Screenshots** <img alt="Screen Shot 2022-05-06 at 10 00 04" width="977" src="https://user-images.githubusercontent.com/46033500/167136282-2910f1d7-c17b-4918-9484-32a744a549e0.png">
> 
> **Flutter Doctor**
> 
> ![Screen Shot 2022-05-06 at 10 07 36](https://user-images.githubusercontent.com/46033500/167137637-a25bb3c8-454a-4b26-94e4-776d3b2757ce.png)
> 
> **Desktop (please complete the following information):**
> 
> * [x]  iOS
> * [x]  Android
> * [ ]  Browser
> * [ ]  Windows
> * [ ]  Linux
> 
> **Smartphone (please complete the following information):**
> 
> * Device: iPhone 11, Redmi Y2, Others, It will happen on any device
> 
> **Additional context** I have a lot of cards that will become PDF's, there is a specific card which always throw this error, maybe there is some relation with the input from this card to the package (that was my first thought), the thing is, I solved it by just updating the fonts.

Hi In my case, the problem was with the custom font. If you change the font, change it. It will probably work.
