### ISSUE TITLE
Print doesn't support MultiPage objects in a Document. 

### ISSUE THREAD

**Issue by Pebsie** [DavBfr/dart_pdf#103]
I'm not sure what I'm doing wrong or how to troubleshoot this problem.

I'm creating a pdf and adding content to it. When running `await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());` the dialog appears and fully displays the content as I've laid it out but when saving the file it produces is blank. 

I have requested permission and received it on the phone. I've tried with the share function too and the same problem occurs.

EDIT: Sharing to Messages and then tapping on the file attachment in Messages THEN adding to Drive works just fine. However adding straight to Drive causes a "Synchronisation Error" to occur.

**Comment by DavBfr** [comment]
You have to build the full Pdf each time the callback onLayout is called. I'm not sure pdf.save() can be called multiple times.

**Comment by Pebsie** [comment]
I managed to fix it by changing the addPage from a MultiPage to a regular Page returning a Column. I couldn't get adding a MultiPage to work with any data.

**Comment by DavBfr** [comment]
That must be an issue with an async call.

**Comment by DavBfr** [comment]
This is fixed in Pdf 1.3.17
