### ISSUE TITLE
EXCEPTION CAUGHT BY PRINTING 

### ISSUE THREAD

**Issue by tiyebm** [DavBfr/dart_pdf#1034]
Using Printing on Flutter Web, this is the simple code that causes this exception:

`  await Printing.layoutPdf(
                        onLayout: (PdfPageFormat format) async =>
                            await Printing.convertHtml(
                              format: format,
                              html: '<html><body><p>Hello!</p></body></html>',
                            ));`

Exception:

╡ EXCEPTION CAUGHT BY PRINTING ╞══════════════════════════════════════════════════════════════════
The following UnimplementedError was thrown while generating a PDF:
UnimplementedError
When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/printing/printing_web.dart 269:5                                                                                  convertHtml
packages/printing/src/printing.dart 191:38                                                                                 convertHtml
packages/ane/main.dart 193:44                                                                                              <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/ane/main.dart 192:50                                                                                              <fn>
packages/printing/printing_web.dart 124:30                                                                                 layoutPdf
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/printing/printing_web.dart 114:25                                                                                 layoutPdf
packages/printing/src/printing.dart 49:38                                                                                  layoutPdf
packages/ane/main.dart 191:36                                                                                              <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/ane/main.dart 189:28                                                                                              <fn>
packages/flutter/src/material/ink_well.dart 989:21                                                                         [_handleTap]
packages/flutter/src/gestures/recognizer.dart 198:24                                                                       invokeCallback
packages/flutter/src/gestures/tap.dart 608:48                                                                              handleTapUp
packages/flutter/src/gestures/tap.dart 296:5                                                                               [_checkUp]

packages/flutter/src/gestures/tap.dart 230:7                                                                               handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 563:9                                                                        handleEvent
packages/flutter/src/gestures/pointer_router.dart 94:12                                                                    [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 139:9                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/gestures/pointer_router.dart 137:17                                                                   [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 123:7                                                                    route
packages/flutter/src/gestures/binding.dart 439:19                                                                          handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                                                          dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                                                         dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                                                           [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                                                           handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                                                           [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                                                          [_handlePointerDataPacket]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1026:13           invoke1
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 184:5             invokeOnPointerDataPacket
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 130:39                [_onPointerData]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 543:18                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 496:21                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 210:16                loggedHandler
PageFormat: "PdfPageFormat 595.275590551181x841.8897637795275 margins:56.69291338582677,

  56.69291338582677, 56.69291338582677, 56.69291338582677"
════════════════════════════════════════════════════════════════════════════════════════════════════
Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:54619/dart_sdk.js:5067:11)
at printing_web.PrintingPlugin.new.convertHtml (http://localhost:54619/packages/printing/printing_web.dart.lib.js:247:17)
at Function.convertHtml (http://localhost:54619/packages/printing/src/printing.dart.lib.js:165:51)
at http://localhost:54619/packages/ane/main.dart.lib.js:800:58

**Comment by DavBfr** [comment]
convertHtml is only available on Android, iOS and macOS.
