### ISSUE TITLE
 EXCEPTION CAUGHT BY RENDERING LIBRARY 

### ISSUE THREAD

**Issue by tiyebm** [DavBfr/dart_pdf#1035]
Using PdfPreview in Printing library on Flutter web, with this simple implementation:

`

PdfPreview(
                        build: (format) =>
                            _generatePdf(format, "TITLE"),
                      )

 Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
          pageFormat: format,
          build: (context) {
            return pw.Text(title);
          }),
    );
    return pdf.save();
  }
`

 I got the following:

 EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderFlex children have non-zero flex but incoming height constraints are unbounded.
When a column is in a parent that does not provide a finite height constraint, for example if it is
in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
space in the vertical direction.
These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
cannot simultaneously expand to fit its parent.
Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
children (using Flexible rather than Expanded). This will allow the flexible children to size
themselves to less than the infinite remaining space they would otherwise be forced to take, and
then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
constraints provided by the parent.
If this message did not help you determine the problem, consider using debugDumpRenderTree():
  https://flutter.dev/debugging/#rendering-layer
  http://api.flutter.dev/flutter/rendering/debugDumpRenderTree.html
The affected RenderFlex is:
  RenderFlex#c63a7 relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE(creator: Column ← PdfPreviewController ← PdfPreview ← Container ← Column ← Center ← ConstrainedBox ← Container ← Column ← Center ← FutureBuilder<Agent> ← Column ← ⋯, parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size), constraints: BoxConstraints(0.0<=w<=250.0, 0.0<=h<=Infinity), size: MISSING, direction: vertical, mainAxisAlignment: center, mainAxisSize: max, crossAxisAlignment: center, verticalDirection: down)
The creator information is set to:
  Column ← PdfPreviewController ← PdfPreview ← Container ← Column ← Center ← ConstrainedBox ←
  Container ← Column ← Center ← FutureBuilder<Agent> ← Column ← ⋯
The nearest ancestor providing an unbounded width constraint is: RenderFlex#57104 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: Column ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
    CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#2edef ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 56.0); id=_ScaffoldSlot.body (can use size)
  constraints: BoxConstraints(0.0<=w<=1366.0, 0.0<=h<=556.0)
  size: Size(1366.0, 556.0)
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
See also: https://flutter.dev/layout/
If none of the above helps enough to fix this problem, please don't hesitate to file a bug:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
The relevant error-causing widget was:
PdfPreview

When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/rendering/flex.dart 926:9                                                                             <fn>
packages/flutter/src/rendering/flex.dart 928:14                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                          layout
packages/flutter/src/rendering/layout_helper.dart 56:10                                                                    layoutChild
packages/flutter/src/rendering/flex.dart 829:43                                                                            [_computeSizes]
packages/flutter/src/rendering/flex.dart 931:32                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                          layout
packages/flutter/src/rendering/shifted_box.dart 437:7                                                                      performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                          layout
packages/flutter/src/rendering/proxy_box.dart 277:7                                                                        performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                          layout
packages/flutter/src/rendering/layout_helper.dart 56:10                                                                    layoutChild
packages/flutter/src/rendering/flex.dart 829:43                                                                            [_computeSizes]
packages/flutter/src/rendering/flex.dart 931:32                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                          layout
packages/flutter/src/rendering/shifted_box.dart 437:7                                                                      performLayout
......................

The following RenderObject was being processed when the exception was fired: RenderFlex#c63a7 relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: Column ← PdfPreviewController ← PdfPreview ← Container ← Column ← Center ← ConstrainedBox ←
    Container ← Column ← Center ← FutureBuilder<Agent> ← Column ← ⋯
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=250.0, 0.0<=h<=Infinity)
  size: MISSING
  direction: vertical
  mainAxisAlignment: center
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderConstrainedBox#e8f6f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderDecoratedBox#a062b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

**Comment by DavBfr** [comment]
That's a basic flutter layout mistake: Don't put PdfPreview in a listview as it already is a listview.
