### ISSUE TITLE
The library increased the weight of the APK

### ISSUE THREAD

**Issue by miguelflores1993** [DavBfr/dart_pdf#1036]
The library increased the weight of the APK by + 35MB.

Before it weighed 30MB, now 65MB.

I do not know if it will affect production for download that was previously 10MB.

and I do not know if it will go up to more.

This is normal?

**Comment by DavBfr** [comment]
It should not increase too much, it just uses the Java API to print.

**Comment by DavBfr** [comment]
I see an increase of 1.3MB on my tests.
