### ISSUE TITLE
flutter 3.0.0 is detecting issue with the library

### ISSUE THREAD

**Issue by Bahrom2101** [DavBfr/dart_pdf#1039]
/D:/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/printing-5.9.0/lib/src/preview/controller.dart(70,35): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\FlutterProjects\billz_cashier_desktop\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by DavBfr** [comment]
I saw it, but for people using Flutter < 3.0 this WidgetsBinding.instance is nullable.

**Comment by DavBfr** [comment]
Fixed in master branch.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by Saikiran24** [comment]
> and what ABOUT >=3.0 ?

**Comment by DavBfr** [comment]
It's not published yet.
