### ISSUE TITLE
Fillable Text Form Fields

### ISSUE THREAD

**Issue by nonComBen** [DavBfr/dart_pdf#104]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A Text Form Field widget that is fillable after writing to Pdf

**Describe alternatives you've considered**
I've looked through your library and didn't find any type of form field widget.  I've also looked into creating a pdf form with acrobat, uploading it to my assets folder and allowing the app to access the form, fill in the fields and save as to the users device, but have not found a solution for that method either.

**Additional context**
I have a leader management database app that stores relevant information on subordinates, but due to privacy/security concerns, the app only stores nonsensitive information.  A hardcopy version of my app is customary in my profession and thus, I would like my app to not only supplement the hardcopy, but also create it. Thus, I would like my app to create the pdf forms, fill in the information from the app's database and allow the user to fill in the sensitive information on the pdf form itself.  Not sure if that's feasible, but any help would be greatly appreciated.

**Comment by DavBfr** [comment]
I have no plan to support that, but PR are welcome.

**Comment by nonComBen** [comment]
Fair enough, thanks for the quick response.

**Comment by DavBfr** [comment]
If you really need this feature, send me a mail.
