### ISSUE TITLE
PDF paper print is with irregular characters

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#1041]
Some of the users reported this issue to us in the app.
PdfPreview is fine. Print Preview is also fine.
But When they print the document it is with irregular characters. It is not the actual which is displayed on PdfPreview and Print preview.

**Print:**
![20220512_140952](https://user-images.githubusercontent.com/14223997/168159008-48647873-19ff-45de-8fc1-6ea613eff3d6.jpeg)

**Print preview settings**
![Screen Shot 2022-05-13 at 1 30 50 AM](https://user-images.githubusercontent.com/14223997/168159127-422f3332-f5d8-49f7-9770-3b65b7da7b56.png)

Only Android users reported this issue so far.
They are also saying the print is working fine for other apps.

Is there an issue with this library?
Could you please check?

**Comment by DavBfr** [comment]
Maybe an issue with the printer's firmware. I can't test if I don't have this exact same printer.

**Comment by deepak786** [comment]
But the user says that it is working fine with other applications.
I will ask the user to save the PDF somewhere (Files) and then try to print from there.

**Comment by deepak-agendaboa** [comment]
We still have this issue reported by many users.
