### ISSUE TITLE
Loading html appears oom

### ISSUE THREAD

**Issue by mdddj** [DavBfr/dart_pdf#1043]
<img width="1241" alt="wecom-temp-d3f84792d3f5cb8f18e9309dc0a566e1" src="https://user-images.githubusercontent.com/29020213/168417555-31dad28a-f97a-40cd-ab81-954663d0ec16.png">
How to deal with this situation, can you catch the error?

**Comment by DavBfr** [comment]
That's the Java API somewhere here: https://github.com/DavBfr/dart_pdf/blob/master/printing/android/src/main/java/net/nfet/flutter/printing/PrintingJob.java#L448

You can take a look and provide a PR.
