### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. in printing 5.9.0

### ISSUE THREAD

**Issue by Saikiran24** [DavBfr/dart_pdf#1049]
/C:/Users/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/printing-5.9.0/lib/src/preview/controller.dart:70:35: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Users/Flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
    final locale = WidgetsBinding.instance!.window.locale;

**Comment by DavBfr** [comment]
Duplicates #1039

**Comment by Saikiran24** [comment]
WHAT ABOUT FLUTTER >=3.0
