### ISSUE TITLE
drawing arc on a circle

### ISSUE THREAD

**Issue by GayeKone222** [DavBfr/dart_pdf#1050]
hi, i'm trying to draw an dynamic arc on a circle according to a percentage value intervals. Just like in the image.
![Screenshot from 2022-05-18 10-33-45](https://user-images.githubusercontent.com/36001171/169019535-9257628c-0b97-47ef-82fc-78a607b4d84e.png)

**Comment by DavBfr** [comment]
Look at how this widget is implemented: https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/src/widgets/progress.dart#L23

**Comment by GayeKone222** [comment]
thanks, i'll check it

**Comment by GayeKone222** [comment]
it works. Thanks so much.

**Comment by GayeKone222** [comment]
How can i tranform the widget to a customPainter ?

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
