### ISSUE TITLE
Pick the first viable printer

### ISSUE THREAD

**Issue by marcusbrostrom** [DavBfr/dart_pdf#1055]
I would like to be able to use the first viable printer instead of choosing from the useActions panel. The goal is to use the package to print receipt on a function call. Is this possible?

**Comment by DavBfr** [comment]
On which platform?

**Comment by DavBfr** [comment]
There is no API other than Window.print() to print a document and that's what I use.
https://developer.mozilla.org/en-US/docs/Web/API/Window/print
