### ISSUE TITLE
css color not working (nearly always gray)

### ISSUE THREAD

**Issue by lehnen** [DavBfr/dart_pdf#1056]
**Package version**
  printing: ^5.9.1
  pdf: ^3.8.1

**Describe the bug**
If you style a text by using a color, Printing.convertHtml renders nearly alway some kind of gray

**To Reproduce**
`<html lang="en"><body><div style="color:#FFFFFF; font-size:32pt">Hello World!</div><div style="color:rgba(255, 255, 255, 1); font-size:32pt">Hello World!</div></body></html>`

**Expected behavior**
Text should be white and so not visible. But the text is rendered in gray. In this case it's realy useless, but in my scenario, there is a colored background image on which the text should be rendered in white.

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Desktop (please complete the following information):**
 - MAC

**Comment by DavBfr** [comment]
It's just using the Apple html to pdf API, nothing I can do here.
