### ISSUE TITLE
How to set a one page only in the state of zoomable by default in PDFPreview

### ISSUE THREAD

**Issue by Arcttyx** [DavBfr/dart_pdf#1058]
I have an application which generates small receipts. These receipts are always one page pdf as a result.
It is necessary to zoom to the generated preview of the receipt so the user can confirm small details.

I know the package supports zoom in PdfPreview when you double tap a page, and then you pinch on it.

I would like to know if there's any way I can configure the preview of the receipt, so it can be pre-selected (double tap) by default at the moment of the creation of the Preview without the need of the user to do this for zooming the page.

**Comment by DavBfr** [comment]
If it's one page only, you can use the raster method to get an image and render it in Flutter with an InteractiveViewer

**Comment by Arcttyx** [comment]
So, basically transform the resulting pdf file to an image and show it in another screen?, Sounds good. Thank you for the idea
But what if they need to send the receipt to the printer to give it to the customer?, thats why I'm using printing packages in first place :o
