### ISSUE TITLE
Cannot save pdf on device

### ISSUE THREAD

**Issue by byrek3d** [DavBfr/dart_pdf#106]
When using the example, everything seems to work correctly with the exception of saving in the device's memory. I thought that maybe it was a permission issue with the simulator so I tried on a real device, but still I couldn't see the pdf anywhere in the Files. Unless I understand incorrectly, there should be a pdf called my-resume.pdf located somewhere in the devices memory. 
On the android emulator it also didn't work. It created the directory Android/data/my.domain/files/Document, but there was nothing there...
One more thing, when deploying the app with Xcode I could see this message when saving: 
`Runner[6740:3819384] flutter: Save as file /var/mobile/Containers/Data/Application/91FE2617-1BBE-4E45-8B4B-965CCD06F172/Documents/document.pdf ...`. This didn't appear when running it on the simulator.
I am really not used to iPhones so maybe the default location is somewhere hidden?

**Comment by DavBfr** [comment]
On iOS, there is no way to write on shared disk space. The Documents/document.pdf file is what you are looking for. But it is accessible only to your application.

**Comment by DavBfr** [comment]
You can make the files in Documents available to the Files app by adding this to your `ios/Runner/Info.plist`:

```xml
<dict>
...
  <key>UIFileSharingEnabled</key>
  <true/>    
  <key>LSSupportsOpeningDocumentsInPlace</key>
  <true/>
...
</dict>
```

I will add that to the example app.

**Comment by byrek3d** [comment]
That's it, now I can save the pdf. Thanks so much. Maybe consider adding this in the "installation" part you have on the readme, could be helpful to others.
