### ISSUE TITLE
 Creating a dynamic size list

### ISSUE THREAD

**Issue by jonathancmatos** [DavBfr/dart_pdf#1060]
Hello how are you ?
I'm trying to generate a report where I have a dynamic size list inside the other.

**Follow the example in the image below.**

![print](https://user-images.githubusercontent.com/37823427/170114119-e26d4b7f-5f2e-4510-8c3c-5acc4025e5de.PNG)

The question is: How can I generate this list so that there is no page break between one group and another, and if the content of the group is greater than the page, continue on the other page.

**Follow the current code**

```
doc?.addPage(pw.MultiPage(
        margin: pw.EdgeInsets.zero,
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context ctx) => <pw.Widget>[
          Partitions(
            children: <Partition>[
              Partition(
                flex: 1618,
                child: Column(
                  children: List<Widget>.generate(groupedLists.length, (int index){
                    final key = groupedLists.keys.toList()[index];
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        _headList(index: index+1, value: key),
                        Partitions(
                        children: <Partition>[
                          Partition(
                              flex: 1618,
                              child: Column(
                                  children: List<Widget>.generate(50, (int index){
                                    return pw.Container(
                                      alignment: Alignment.centerLeft,
                                      height: 30,
                                      margin: EdgeInsets.only(bottom: 16),
                                      width: double.infinity,
                                      color: PdfColors.grey300,
                                      child: Text("Item Produto")
                                    );
                                  }
                              )
                          ))]
                        )
                      ]);
                  }),
                ),
              ),
            ],
          ),
        ])
    );
```

I am currently getting this error.

`Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.`

**Thank you in advance**

**Comment by DavBfr** [comment]
Just wrap your groups in a container, and have those containers direct children of the multipage.

**Comment by jonathancmatos** [comment]
Hello, this question is urgent because the application is already in production. Can you help me?

**Comment by DavBfr** [comment]
Send me a real sample if you need debugging.

**Comment by jonathancmatos** [comment]
Hello @DavBfr,
As requested, below I will leave the link of the example project I created that has basically the same structure as the list I need.

[https://github.com/jonathancmatos/flutter-pdf-example](url)

When opening, you will see the error ` Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue.`

I will be waiting for your response and solution to the problem.
Thanks.

**Comment by jonathancmatos** [comment]
Hello @DavBfr 
Any news on the above case?
