### ISSUE TITLE
I want to know if printer is online (new property or method)

### ISSUE THREAD

**Issue by samo92** [DavBfr/dart_pdf#1063]
**Is your feature request related to a problem? Please describe.**
Hi, when i use Printing.listPrinters i want to know if printers are online (turn on, connnected to the usb, etc)

**Describe the solution you'd like**
A property in Printer object called "online"

**Describe alternatives you've considered**
No one.

**Additional context**
User's get angry because the printer shows but they need a test print to verifiy if printer is online.

**Comment by DavBfr** [comment]
Which OS?
