### ISSUE TITLE
Printing Exception with printing: ^5.9.1   pdf: ^3.8.1

### ISSUE THREAD

**Issue by shakirpa** [DavBfr/dart_pdf#1068]
**Describe the bug**

in WebApp, with the package printing: ^5.9.1 and   pdf: ^3.8.1, I am able to generate the PDF by reading the information from firebase, but when I press on print or share button I am getting following exception, If I commend the line, 117
![image](https://user-images.githubusercontent.com/71609109/171497551-7560a00f-7cbb-4dd0-a270-55ee83b83f3b.png)

 its working fine, 

![image](https://user-images.githubusercontent.com/71609109/171496385-4e64f243-c499-468f-bc31-abc953de9106.png)

when I press 1, pdf is generated as in the screenshot, when I press on 2, I am getting following error

======== Exception caught by printing ==============================================================
The following assertion was thrown while generating a PDF:
Assertion failed: file:///C:/Users/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-3.8.1/lib/src/widgets/document.dart:117:12
!_paint
"The document has already been saved."

When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/pdf/src/widgets/document.dart 117:13                                                                              addPage
packages/finnkassaweb/view/screens/admin/reports/expense_report.dart 428:9                                                 printPosMonthlyInvoice
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1685:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 159:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 601:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
PageFormat: "PdfPageFormat 594.9156327543424x841.6898263027294 margins:14.173228346456694, 14.173228346456694, 14.173228346456694, 14.173228346456694"
====================================================================================================

code : 

SizedBox(
                                      width: size.width * 0.3,
                                      height: size.height * 0.8,
                                      child: PdfPreview(
                                        build: (format) =>
                                        printPosMonthlyInvoice(expenses
                                            .elementAt(
                                            selectedExpense)),
                                        allowSharing: true,
                                        canChangeOrientation: false,
                                        canChangePageFormat: false,
                                        canDebug: false,
                                        allowPrinting: true,
                                        onPrinted: (context) {
                                          Navigator.pop(context);
                                        },
                                        onPrintError:
                                            (context, error) {
                                          print(
                                              "Printing Error... $error");
                                        },
                                      ),
                                    )

Future<Uint8List> printPosMonthlyInvoice(Expense expense) async {
    await getImage();
    pdf.addPage(
      pw.MultiPage(
        pageFormat:
        PdfPageFormat.a4.copyWith(marginBottom: 1.5 * PdfPageFormat.cm),
        crossAxisAlignment: pw.CrossAxisAlignment.start, 
        build: (context) => <pw.Widget>[
          pw.Text('Test Printing),
          pw.SizedBox(height: 20),//to add a space          
        ],
      ),
    );
    return pdf.save();
  }

**Desktop (please complete the following information):** 
 - [ ] Browser

**Comment by DavBfr** [comment]
That's because you reuse the pw.Document object for multiple outputs. You must recreate the entire document from start for each action.

**Comment by shakirpa** [comment]
Thank you...
