### ISSUE TITLE
Can't able to asses image by all image providers

### ISSUE THREAD

**Issue by ShashankSirmour** [DavBfr/dart_pdf#107]
**Describe the bug**

 

can't able to call MemoryImage or NetworkImage it create error
```
D/skia    ( 9287): Shader compilation error
D/skia    ( 9287): ------------------------
D/skia    ( 9287): Errors:
D/skia    ( 9287):
```

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  final PdfImage image = await pdfImageFromImageProvider(
      pdf: pdf.document,
      image: NetworkImage(imageUrl),
    );

```

**Expected behavior**
wanted to create pdf by fetching network image or by downloading the image.
 as it works fine with AssetImage but gives an error in other image providers 

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.18362.239], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] VS Code, 64-bit edition (version 1.36.1)
[√] Connected device (1 available)

• No issues found!
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser

**Smartphone (please complete the following information):**
 - Device: Pixel_XL
 - OS: oreo

**Comment by DavBfr** [comment]
Can I have a full example?

**Comment by ShashankSirmour** [comment]
Future addPage(String imageUrl, int page, int totalPage) async {
    var imageProvider = NetworkImage(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: imageProvider);

    pdf.addPage(pw.Page(build: (pw.Context context) {
      return pw.Center(
        child: pw.Image(image),
      ); // Center
    })); // Page
  }

function to add image one by one

**Comment by ShashankSirmour** [comment]
> Can I have a full example?

**Comment by DavBfr** [comment]
That's not full example. I don't see anything wrong here. Just I don't know what is pdf and how it is passed to addPage, and how you call addPage.

One question: you use the network to access the images. Have you enabled INTERNET permission in your android/app/src/main/AndroidManifest.xml file?

This full example works:
```dart
import 'dart:async';

import 'package:flutter/material.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  Future<void> addPage(
      pw.Document pdf, PdfPageFormat format, String imageUrl) async {
    final NetworkImage imageProvider = NetworkImage(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: imageProvider);

    pdf.addPage(pw.Page(build: (pw.Context context) {
      return pw.Center(
        child: pw.Image(image),
      );
    }));
  }

  Future<pw.Document> generateDocument(PdfPageFormat format) async {
    final pw.Document doc = pw.Document();

    await addPage(
      doc,
      format,
      'http://instantlogosearch.ils.netdna-cdn.com/png?id=instantlogosearch-facebook',
    );

    await addPage(
      doc,
      format,
      'http://instantlogosearch.ils.netdna-cdn.com/png?id=instantlogosearch-microsoft-word',
    );

    await addPage(
      doc,
      format,
      'http://instantlogosearch.ils.netdna-cdn.com/png?id=instantlogosearch-coca-cola',
    );

    return doc;
  }

  void _printPdf() {
    Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async =>
            (await generateDocument(format)).save());
  }

  @override
  Widget build(BuildContext context) => Scaffold(
      body: Center(
          child: RaisedButton(
              child: const Text('Print Document'), onPressed: _printPdf)));
}
```

**Comment by ShashankSirmour** [comment]
> ```dart
> http://instantlogosearch.ils.netdna-cdn.com/png?id=instantlogosearch-facebook
> ```

thank you very much sorry to bother you it's my fault I called document from dom class so it nither creating pdf nor giving an error
