### ISSUE TITLE
Printing 5.9.1 contains performance issues compared with 5.9.0

### ISSUE THREAD

**Issue by alexda12** [DavBfr/dart_pdf#1070]
**Describe the bug**
We upgraded to 5.9.1 to remove the v3.0 null-aware warnings.

Having upgraded to Printing 5.9.1 - there are **NOW** noticeable performance issues and the whole scrolling of a PDF is very laggy/not smooth anymore. 

Loading a PDF in 5.9.1 takes much longer. Also - once a PDF appears - when you try and scroll very quickly - pages appear to get 'STUCK' (Nothing happens - the scrolling halts).  5.9.1 no longer appears to support 'Fling' gestures. In 5.9.0 one could load a PDF and then **immediately** fling upwards - this would have the effect of paging down extremely quickly - showing a blank page placeholder and then after a few milliseconds show the rendered page. Now - it would appear this is not possible, quick Fling gestures do not have the desired effect, they appear to get 'swallowed up' until the rendered page appears.

**To Reproduce**
All I did was upgrade the Plugin from 5.9.0 to 5.9.1 - and use the PdfViewer on a file approx 1-2 mb with a mixture of images and text. No more than 10 pages.

**Expected behavior**
At least the same performance (not worse) then what we had in 5.9.0

**Screenshots**

**Flutter Doctor**

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.1 21C52 darwin-x64,
    locale en-GB)
    • Flutter version 3.0.1 at /Users/d/workspace/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29
      -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
    • Android SDK at /Users/d/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/d/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/d/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • iPhone 13 mini (mobile)      •
      2C68EB8B-4DC4-425F-85F7-F4413A64A15B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • iPad Pro (9.7-inch) (mobile) •
      CF162478-B546-4581-AF88-BF382EDD7180 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)              • macos
      • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)                 • chrome
      • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available 
```

**Desktop (please complete the following information):**
 - [X] iOS
 - [X] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
Tested on both Android and iOS simulators. Also tested on live devices Samsung S11 Pro, iPhone 11 Pro Max etc.

**Additional context**

Would appear to be related to the new memory performance work in 5.9.1 
->Improve PdfPreview memory consumption

**Comment by therealjohnsummer** [comment]
@alexda12 

I have the exact same issue.

Fling gestures seem to get paused - you cannot load a PDF and then immediately fling upwards. There is a noticeable delay. It seems that the PDF is still loading which cancel's any Fling gesture.

The OLD version works without fail - 5.9.0 - I have switched to using syncfusion pdf viewer which works without issue.
