### ISSUE TITLE
Can not render image in background service

### ISSUE THREAD

**Issue by nothingdhsp** [DavBfr/dart_pdf#1074]
**Describe the bug**

I want to render image from pdf for printing in background service. How ever I got following exception.
The code work perfectly in noral mode, but doesn't work in background service 
I am using https://pub.dev/packages/flutter_background_service

D/BackgroundService(19714): runService
E/flutter (19714): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method rasterPdf on channel net.nfet.printing)
E/flutter (19714): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (19714): <asynchronous suspension>
E/flutter (19714): 
I/flutter (19714): *** Response ***
I/flutter (19714): uri: https://api.mmenu.io/v2/restaurants/62922d0342059718fd754a00/getPrinterJob
I

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
      final pdf = pw.Document();
      final pdfPageFormat = _pdfPageFormat(paperSize);
///  to produce pdf
...
    final pdfBytes = await pdf.save();
      PdfDocument pdfDocument ;
      late Uint8List utf8List;
      await for (final page in Printing.raster(pdfBytes)) {
        utf8List = await page.toPng();
      }
      final image = image_lib.decodePng(utf8List);
      return image!;

```

**Expected behavior**

To render image 
**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**

 - [x] Android

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
That's a Flutter limitation.
