### ISSUE TITLE
Failed to load resource issue in Flutter web when offline

### ISSUE THREAD

**Issue by tiyebm** [DavBfr/dart_pdf#1076]
I am using `pdf: 3.8.1` and my application works fine when connected to the internet, but when offline I get the following error in web console:

`Failed to load resource: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.13.216/pdf.min.js net::ERR_INTERNET_DISCONNECTED`

Usually, this type of errors could be resolved by bundling the required resources with the project, but that requires some configurations to use them locally.

**Comment by DavBfr** [comment]
You can provide your own version of the pdf.js library and load it in your index.html.

**Comment by tiyebm** [comment]
Thank you for response, I downloaded the file in assets and added the script in `index.html` 
`<script src="assets/pdf.min.js"></script> `
I also declared the file in `pubspec.yaml`, but I still get the same error!
I have to mention that I am still using the PDF in dependancies, I think the call is initiated from the PDF lib.

**Comment by DavBfr** [comment]
You need to add something like this to your web/index.html file:

```html
<script src="pdf.min.js"></script>
<script type="text/javascript">
    pdfjsLib.GlobalWorkerOptions.workerSrc = "pdf.worker.min.js";
</script>
```

then the printing library will detect it's already loaded and will not load the external version.

**Comment by tiyebm** [comment]
Now it is working offline! Thank you for your support.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
