### ISSUE TITLE
addPage with index value 

### ISSUE THREAD

**Issue by ShashankSirmour** [DavBfr/dart_pdf#108]
**Is your feature request related to a problem? Please describe.**
I want to load images Asynchronously download image and wanted to addPage with some Specific Index. so after loading  page will be added according to its index
**Describe the solution you'd like**
an index parameter in addPage  may be a great solution so it will dynamically add pages according to index

**Comment by DavBfr** [comment]
That's not possible, but you can preload all the images and create the pages after. Anyways you need all images to be downloaded before the user can print or see the pdf.

**Comment by ShashankSirmour** [comment]
thank you  very much
