### ISSUE TITLE
XmlParserException "</" expected ad 3.1

### ISSUE THREAD

**Issue by socialclusterltda** [DavBfr/dart_pdf#1084]
I'm using the original code from dart_pdf, with all original examples.

The important example for my project is "Invoice".

When I emulate the original code, all runs ok.
But when I deploy to web, the example type 'Invoice', appears a grey screen with the message "XmlParserException "</" expected ad 3.1".

The same situation occurs in Android, Ios and web.

Help please. Thanks..!

**Comment by DavBfr** [comment]
Maybe the SVG file is tempered on your prod builds.

**Comment by socialclusterltda** [comment]
Thanks for fast return. I'll 'buy you a coffe' soon..  can you explain how to solve it?

**Comment by socialclusterltda** [comment]
Solved man! The image path was wrong.. 
Let me know the link to 'pay you a coffee'.. 

Your codes are great.

**Comment by socialclusterltda** [comment]
I just bought you a coffee.

Are you interested to develop an aditional code for me? Make a good price.

That's what I need:

1. When the PDF invoice is generated, this invoice.pdf must be saved on firebase, automatically. At same time, I need to save the PDFpath+clientName in a doc, in the firebase too.

3. Before generating the PDF, I need to pass the data to the invoice.pdf (company name, client name, items list, etc), from a Provider, before.

That's it. Thanks.
I hope you are interested.

**Comment by DavBfr** [comment]
Send me a mail

**Comment by socialclusterltda** [comment]
Hi David!

That's my need:

- Before generating the PDF, I need to pass the data, from a Provider
(client name, company name, items list, etc)
- I'm using a invoice structure similar your project (dart_pdf).
- I need that, when I click to generate the PDF preview, automatically save
this PDF file in firebase.
- I also need to save the path is a Doc in firebase, that contains
clientName + PDFpath, for future access/view

Constructing a model structure, I can implement the rest.

That is it.
If interested, please make a good price.

Greetings,
Leandro Seidel



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua., 22 de jun. de 2022 às 11:16, David PHAM-VAN <
***@***.***> escreveu:

**Comment by DavBfr** [comment]
@socialclusterltda dev.nfet.net@gmail.com
