### ISSUE TITLE
 There is no way to enable it in Objective-C, not Swift.

### ISSUE THREAD

**Issue by shinxxxxwon** [DavBfr/dart_pdf#1085]
First of all, thank you for sharing the `Printing` package.
My Flutter package is using JAVA and OBJC. This is set up like this in order to use the C API in conjunction with the native. I saw the Printing package of Pub.dev, but only how to enable it in Swift. How do I enable it in OBJC?

**Comment by DavBfr** [comment]
It's designed for Dart/Flutter, no need for Objective-C or Swift.
