### ISSUE TITLE
texImage2D: width or height out of range

### ISSUE THREAD

**Issue by rickypid** [DavBfr/dart_pdf#1087]
**Describe the bug**

When I try to generate a preview of a pdf on a screen with a width >~ 900px the preview shows a completely blank page, if I do a resize of the screen the preview is displayed correctly. Furthermore, if I make a print with the white preview, the print is done correctly.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pp.PdfPreview(
    allowSharing: false,
    canDebug: kDebugMode,
    pageFormats: {
      'Scontrino': const pw.PdfPageFormat(
        56 * pw.PdfPageFormat.mm,
        1024 * pw.PdfPageFormat.mm,
        marginLeft: 6 * pw.PdfPageFormat.mm,
        marginRight: 6 * pw.PdfPageFormat.mm,
      ).portrait
    },
    canChangeOrientation: false,
    build: (format) => generatePdf(
      context,
      format,
      generateReport(/*More code*/)
    ),
  )
```

**Flutter Doctor**
```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Versione 10.0.19043.1766], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.67.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

**Platform:**
 - Browser

**Device:**
 - Device: [Desktop]
 - OS: [Windows 10]
 - Browser [Chrome/Edge]
 - Version [103.0.5060.53 (Build ufficiale) (a 64 bit)/Versione 103.0.1264.37 (Build ufficiale) (64 bit)]

**Additional context**

Error in web console wen screen widh is >~ 900px

```
256 WebGL: INVALID_VALUE: texImage2D: width or height out of range canvaskit.js:21 
WebGL: too many errors, no more errors will be reported to the console for this context.
```

![image](https://user-images.githubusercontent.com/19270983/176146839-dcf03fca-fae0-4abe-a527-ad36ee2300ae.png)

**Comment by DavBfr** [comment]
use the `maxWidth` parameter of PdfPreview.
Seems your GPU is not able to load large textures.
