### ISSUE TITLE
Lost connection to device (on Windows)

### ISSUE THREAD

**Issue by uktamjon-komilov** [DavBfr/dart_pdf#1089]
**Describe the bug**
I am using this package (printing) to print some docs in flutter desktop (Windows). On both, debug and release it is printing, but navigating to other screen crashes the app saying "Lost connection to device"

**To Reproduce**
Code snippet to reproduce the behavior:
```dart

final pdf = pw.Document();

for (int i = 0; i < 25; i++) {
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.roll57,
        margin: pw.EdgeInsets.zero,
        build: (pw.Context context) {
          return Text("test");
        },
      ),
    );
  }

Uint8List data = await pdf.save();

File file = File("example.pdf");
file.writeAsBytes(data);

await Printing.layoutPdf(
    onLayout: (_) => Uint8List.fromList(data),
    format: PdfPageFormat.roll57,
    usePrinterSettings: false,
    dynamicLayout: false,
);

```

**Screenshots**
![image](https://user-images.githubusercontent.com/71062282/176451220-e4ae246a-4cd6-4bf3-a699-05630edf3c16.png)

**Flutter Doctor**
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1766], locale en-US)
    • Flutter version 3.0.1 at C:\libs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0) 
    • Android SDK at C:\Users\uktam\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)    
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community   
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\uktam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

**Desktop (please complete the following information):**
 - [+] Windows

**Comment by Quintonvv** [comment]
I am experiencing the same problem, with our own code, as well as with the code provided above.
