### ISSUE TITLE
PdfPreview is incomplete on web

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#1093]
Check the attached screenshot.
![Screen Shot 2022-07-01 at 7 22 25 PM](https://user-images.githubusercontent.com/14223997/176908124-bb010df7-7c3a-48a4-b81e-004a05e8acfa.png)

It is only showing the Images. But the Text data is missing.
The downloaded PDF is fine with everything.

```
Google Chrome
Windows 7
```

```
pdf: 3.7.1
printing: 5.7.2
```

**Comment by deepak-agendaboa** [comment]
@DavBfr We still have this issue. 

```
pdf: 3.10.4
printing: 5.11.0
```

**Comment by deepak786** [comment]
@DavBfr We still have this issue.

```
pdf: 3.10.4
printing: 5.11.0
```

**Comment by rohansohonee1** [comment]
Facing this issue on:
```
Windows 7 (32 bit)
Chrome version: 109.0.5414.120
```

Console log:
```
Warning: decodeScan - unexpected MCU data, current marker is: ff00 [pdf.worker.min.js: 22]
```

**Comment by deepak786** [comment]
@DavBfr Can you please look into this issue as we have more findings now https://github.com/DavBfr/dart_pdf/issues/1093#issuecomment-1623367284?
