### ISSUE TITLE
pdf/widgets is not support svg style 

### ISSUE THREAD

**Issue by prestojapan2021** [DavBfr/dart_pdf#1094]
**Describe the bug**
SvgImage of pdf/widgets is not support <style> property

**To Reproduce**
Code snippet to reproduce the behavior:
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 26.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 187.3 187.3" style="enable-background:new 0 0 187.3 187.3;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#F7A663;}
	.st1{fill:#FFC80A;}
	.st2{fill:#FDD633;}
	.st3{fill:#F4CA19;}
</style>
<g>
	<polygon class="st0" points="101.7,40.7 93.7,0 85.6,40.7 93.7,40.7 	"/>
	<polygon class="st1" points="67.2,47.8 74.1,43.8 46.8,12.5 60.2,51.8 	"/>
	<polygon class="st0" points="47.8,67.2 51.8,60.2 12.5,46.8 43.8,74.1 	"/>
	<polygon class="st1" points="40.7,93.7 40.7,85.6 0,93.7 40.7,101.7 	"/>
	<polygon class="st0" points="47.8,120.1 43.8,113.2 12.5,140.5 51.8,127.1 	"/>
	<polygon class="st1" points="60.2,135.5 46.8,174.8 74.1,143.5 67.2,139.5 	"/>
	<polygon class="st0" points="85.6,146.6 93.7,187.3 101.7,146.6 93.7,146.6 	"/>
	<polygon class="st1" points="120.1,139.5 113.2,143.5 140.5,174.8 127.1,135.5 	"/>
	<polygon class="st0" points="139.5,120.1 135.5,127.1 174.8,140.5 143.5,113.2 	"/>
	<polygon class="st1" points="187.3,93.7 146.6,85.6 146.6,93.7 146.6,101.7 	"/>
	<polygon class="st0" points="139.5,67.2 143.5,74.1 174.8,46.8 135.5,60.2 	"/>
	<polygon class="st1" points="127.1,51.8 140.5,12.5 113.2,43.8 120.1,47.8 	"/>
	<path class="st2" d="M93.7,45.3v96.8c26.7,0,48.4-21.7,48.4-48.4S120.4,45.3,93.7,45.3z"/>
	<path class="st3" d="M45.3,93.7c0,26.7,21.7,48.4,48.4,48.4V45.3C66.9,45.3,45.3,66.9,45.3,93.7z"/>
</g>
</svg>


```

**Expected behavior**
The attribute specified by style is not reflected. For example, all colors will be black

**Screenshots**

![blacksun](https://user-images.githubusercontent.com/36428714/177074343-d152189b-fffd-4f4a-97f2-119498541303.png)

**Flutter Doctor**

\demo> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.22000.739], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [* ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: Android simulator

**Additional context**

**Comment by DavBfr** [comment]
No, it does not support CSS and will not. The goal is not to implement a web browser, just a basic SVG image. You can use a tool to convert your SVG to a simpler version, like:

- https://github.com/RazrFalcon/resvg/tree/master/usvg
- https://github.com/scour-project/scour

**Comment by prestojapan2021** [comment]
Thanks a lot. I will try it.

**Comment by prestojapan2021** [comment]
Thanks a lot.
