### ISSUE TITLE
How to execute action only once PdfPreview is done ? 

### ISSUE THREAD

**Issue by carpentierchloe** [DavBfr/dart_pdf#1097]
Hello,

My PDFPreview is shown in a page with a download button. If I click on this button and the preview is loading, I have an error. How to detect the preview is done, or execute action once is done to disable my button while it is loading ?

```
Expanded(
            child: PdfPreview(
              useActions: false,
              build: (format) => pdf.save(),
            ),
          ),
Button()
```
Thanks a lot.

**Comment by thirtyninetythree** [comment]
Where is this function in the docs? I can't find PdfPreview in the docs

**Comment by DavBfr** [comment]
You can add a setState to the build method to set a boolean
