### ISSUE TITLE
Non english language characters are not rendered properly in PDF even after loading the necessary fonts.

### ISSUE THREAD

**Issue by techttiru** [DavBfr/dart_pdf#1100]
I am using PDF package in flutter web. Everything is good but when i try to use non-english language, its not showing the character properly. for example (Tamil + english) , Tamil is a language and when i use the character from this language its not showing the character properly. 

I did research multiple issues that are related to similar problem and i did load the necessary font in application but characters are not showing correctly.

here is the code.

```
Future<Uint8List> createSecondPdf(
    List<AttendeeListViewModel> attendeeListViewModelList) async {
  var mytheme = ThemeData.withFont(
    base: Font.ttf(await rootBundle.load("assets/HindMadurai-Regular.ttf")),
    bold: Font.ttf(await rootBundle.load("assets/HindMadurai-Regular.ttf")),
    italic: Font.ttf(await rootBundle.load("assets/HindMadurai-Regular.ttf")),
    boldItalic:
        Font.ttf(await rootBundle.load("assets/HindMadurai-Regular.ttf")),
  );
  // final pdf = Document(theme: mytheme);
  final pdf = Document();
  //final f1 = await PdfGoogleFonts.hindGunturRegular();
  // final f2 = await rootBundle.load("assets/TAU-Marutham_Bold.ttf");
  print(
      '   ${attendeeListViewModelList[2].attendeeDataModel?.pNameAndProfession ?? ''}');

  final data = await rootBundle.load('assets/HindMadurai-Regular.ttf');
  final loadedfont = Font.ttf(data);

  pdf.addPage(
    MultiPage(
      // theme: mytheme,
      build: ((context) {
        return [
          Table.fromTextArray(
            headers: ['Sl.No', 'Name', 'Data'],
            cellAlignments: {0: Alignment.center},
            cellStyle: TextStyle(font: loadedfont),
            columnWidths: {
              0: const FlexColumnWidth(0.6),
              1: const FlexColumnWidth(4.0),
              2: const FlexColumnWidth(2.0),
            },
            data: <List<String>>[
              <String>[
                'Hello',
                attendeeListViewModelList[2]
                        .attendeeDataModel
                        ?.pNameAndProfession ??
                    '',
                'ஜெயப்பாண்டி'
              ]
            ],
          ),
        ];
      }),
    ),
  );

  return pdf.save();
}
```

tried multiple options but no luck so far. Any help is really appreciated. Below screen shot show the characters in different way than what i have given in the code.

<img width="367" alt="Screen Shot 2022-07-19 at 7 33 04 PM" src="https://user-images.githubusercontent.com/106634012/179865467-3a8806bb-eb40-49e8-a51f-91e8be6a42cd.png">

The below are packages that i am using.
  pdf: ^3.8.1
  printing: ^5.9.1

Appreciate the response!. 
Thanks.

**Comment by aliaafreen** [comment]
I also facing same issue. I am using Hindi and English characters in receipt. I have applied Hind font for Hindi characters but it gives text in non proper format. 
![Screenshot_2022-07-22-12-27-39-021_cn wps xiaomi abroad lite](https://user-images.githubusercontent.com/70006255/180382082-814e9a5d-3cf0-47ee-aeaa-a1d39e42cd1d.jpg)

**Comment by techttiru** [comment]
Here is the work around for tamil font issue.
https://github.com/DavBfr/dart_pdf/issues/198#issuecomment-1193298083

**Comment by DavBfr** [comment]
Duplicates #198

**Comment by mohit28infotech** [comment]
same issue with Gujarati Font

**Comment by selvam920** [comment]
can you check indian laungage, i tested tamil it's working

https://github.com/selvam920/dart_pdf
