### ISSUE TITLE
Compatibility with ffi v2

### ISSUE THREAD

**Issue by deckerst** [DavBfr/dart_pdf#1104]
**Is your feature request related to a problem? Please describe.**
Among dependencies in my project, some package latest versions depend on `ffi` v2 but `printing` is stuck with `ffi ^1.1.0`.

**Describe the solution you'd like**
The `printing` package would depend on `ffi` v2.

**Describe alternatives you've considered**
Not upgrading other packages, which will be more and more problematic with time.

**Additional context**
n/a

**Comment by DavBfr** [comment]
Can you try with a dependency like:

```yaml
ffi: ">=1.1.0 <3.0.0"
```

**Comment by deckerst** [comment]
This override works fine, thank you.

But I am worried `printing` may brake at runtime in unexpected ways if `ffi` version is actually beyond its declared dependency constraints.

**Comment by DavBfr** [comment]
The API is not supposed to change on minor releases. So 2.0.0 should remain compatible with < 3.0.0.
