### ISSUE TITLE
[Feature] MultiPage: Get "local" pages instead global ones (multiple reports in one PDF)

### ISSUE THREAD

**Issue by henry2man** [DavBfr/dart_pdf#1107]
**Is your feature request related to a problem? Please describe.**
I'm creating a single PDF file using several MultiPage widgets. When you print the report I'm able to get "whole document" page number and page count but... 

Would it be possible to get the "local" page number of each added MultiPage?

This PDF represents multiple joined reports (multiple MultiPage widgets) where each one represents a certain report which may have one or several pages.

The idea would be to have something like this:

- Page 1/1
- Page 1/2 - Page 2/2
- Page 1/1
- Page 1/3 - Page 2/3 - Page 3/3

and so on and so forth.

**Describe the solution you'd like**

An alternative API that lets me obtain current "local/page" and current "total pages" of a parent MultiPage widget.

**Describe alternatives you've considered**
N/A
**Additional context**
n/a

**Comment by DavBfr** [comment]
You can try with `pageLabels`
Here's the unit test: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/page_labels_test.dart
You can set the page label on a Context object. But only when the page number is known. Like on header or footer callbacks.

**Comment by henry2man** [comment]
> You can set the page label on a Context object

For now the only workaround is try to estimate number of pages given the objects that prints in the report (which in fact is mainly a table with same height rows). But probably something native could be done.

**Comment by henry2man** [comment]
> For now the only workaround is try to estimate number of pages given the objects that prints in the report (which in fact is mainly a table with same height rows). But probably something native could be done

For the workaround you need to consider that getHeader/getFooter is in fact called twice (https://github.com/DavBfr/dart_pdf/issues/712#issuecomment-855219356), so I've implemented a custom counter starting at 0 that increments on every "multipage". For totalPages I've estimated how many items fit on each page, so using this formula will probably work:

```dart
int totalLocalPages = (total/itemsPerPage).ceil();
```
