### ISSUE TITLE
ClipPath

### ISSUE THREAD

**Issue by n1kStas** [DavBfr/dart_pdf#1109]
Good afternoon, is it possible to use ClipPath in PDF somehow?

**Comment by DavBfr** [comment]
You can use a CustomPainter to do the same:

```dart
        pw.CustomPaint(
            child: pw.SizedBox.expand(
              child: pw.Column(
                children: [
                  pw.SizedBox(
                    width: double.infinity,
                    child: pw.FittedBox(
                      child: pw.Text(title),
                    ),
                  ),
                  pw.SizedBox(height: 20),
                  pw.Flexible(child: pw.FlutterLogo()),
                ],
              ),
            ),
            painter: (canvas, size) {
              canvas
                ..saveContext()
                ..moveTo(20, 650)
                ..lineTo(20, 40)
                ..lineTo(400, 40)
                ..closePath()
                ..clipPath();
            },
            foregroundPainter: (canvas, size) {
              canvas.restoreContext();
            },
          );
```

**Comment by n1kStas** [comment]
> Вы можете использовать CustomPainter, чтобы сделать то же самое:
> 
> ```dart
>         pw.CustomPaint(
>             child: pw.SizedBox.expand(
>               child: pw.Column(
>                 children: [
>                   pw.SizedBox(
>                     width: double.infinity,
>                     child: pw.FittedBox(
>                       child: pw.Text(title),
>                     ),
>                   ),
>                   pw.SizedBox(height: 20),
>                   pw.Flexible(child: pw.FlutterLogo()),
>                 ],
>               ),
>             ),
>             painter: (canvas, size) {
>               canvas
>                 ..saveContext()
>                 ..moveTo(20, 650)
>                 ..lineTo(20, 40)
>                 ..lineTo(400, 40)
>                 ..closePath()
>                 ..clipPath();
>             },
>             foregroundPainter: (canvas, size) {
>               canvas.restoreContext();
>             },
>           );
> ```
using ClipPath, I controlled that the child objects would not go beyond the form, but this method does not work

**Comment by DavBfr** [comment]
Use ClipRect then

**Comment by n1kStas** [comment]
> Use ClipRect then

return Center(
                  child: SizedBox(
                    width: width,
                    height: height,
                    child: PolygonAnnotation(
                      points: form(window),
                      color: PdfColors.green,
                      child: CustomPaint(
                        painter: (PdfGraphics canvas, PdfPoint size) {
                          final startPoint =
                              window.vectorsAndSides.first.endPosition;
                          canvas.moveTo(size.x * startPoint.x,
                              size.y - size.y * startPoint.y);
                          for (var vectorAndSide in window.vectorsAndSides) {
                            var vector = vectorAndSide.endPosition;
                            canvas.lineTo(
                              size.x * vector.x,
                              size.y - size.y * vector.y,
                            );
                          }
                          final color =
                              RALColor(numberRalColor: window.numberRalColor)
                                  .toColor()
                                  .value
                                  .toRadixString(16);

                          canvas
                            ..setLineWidth(4)
                            ..setStrokeColor(
                                PdfColor.fromInt(int.parse(color, radix: 16)))
                            ..strokePath(close: false);
                          canvas.closePath();
                        },
                        child: ClipRect(
                          child: Container(
                            color: PdfColors.red,
                          ),
                        ),
                      ),
                    ),
                  ),
                );

the container is still visible outside the shape

**Comment by n1kStas** [comment]
```
                return Center(
                  child: SizedBox(
                    width: width,
                    height: height,
                    child: PolygonAnnotation(
                      points: form(window),
                      color: PdfColors.green,
                      child: CustomPaint(
                        foregroundPainter: (PdfGraphics canvas, PdfPoint size) {
                          final startPoint =
                              window.vectorsAndSides.first.endPosition;
                          canvas.moveTo(size.x * startPoint.x,
                              size.y - size.y * startPoint.y);
                          for (var vectorAndSide in window.vectorsAndSides) {
                            var vector = vectorAndSide.endPosition;
                            canvas.lineTo(
                              size.x * vector.x,
                              size.y - size.y * vector.y,
                            );
                          }
                          final color =
                              RALColor(numberRalColor: window.numberRalColor)
                                  .toColor()
                                  .value
                                  .toRadixString(16);

                          canvas
                            ..setLineWidth(4)
                            ..setStrokeColor(
                                PdfColor.fromInt(int.parse(color, radix: 16)))
                            ..strokePath(close: false);
                          canvas.closePath();
                        },
                        child: ClipRect(
                          child: Container(
                            color: PdfColors.red,
                          ),
                        ),
                      ),
                    ),
                  ),
                );
```

**Comment by DavBfr** [comment]
Can you provide a full example I can actually run? This has external data.

**Comment by n1kStas** [comment]
```
                 Center(
                  child: SizedBox(
                    width: 75,
                    height: 75,
                    child: CustomPaint(
                      foregroundPainter: (PdfGraphics canvas, PdfPoint size) {
                        canvas.moveTo(size.x * 0.5, size.y - size.y * 0);
                        canvas.lineTo(
                          size.x * 1,
                          size.y - size.y * 1,
                        );
                        canvas.lineTo(
                          size.x * 0,
                          size.y - size.y * 1,
                        );
                        canvas.lineTo(
                          size.x * 0.5,
                          size.y - size.y * 0,
                        );

                        canvas
                          ..setLineWidth(3)
                          ..setStrokeColor(PdfColors.brown)
                          ..strokePath(close: true)
                          ..closePath();
                      },
                      child: ClipRect(
                        child: Container(
                          color: PdfColors.red,
                        ),
                      ),
                    ),
                  ),
                );
```

**Comment by n1kStas** [comment]
![image](https://user-images.githubusercontent.com/30822299/181253990-8c11c473-73b2-498d-b5f0-a08c8afd8fec.png)
marked that should not be displayed

**Comment by DavBfr** [comment]
Like this:

```dart
Center(
    child: SizedBox(
      width: 75,
      height: 75,
      child: CustomPaint(
        foregroundPainter: (PdfGraphics canvas, PdfPoint size) {
          canvas.restoreContext();
        },
        painter: (PdfGraphics canvas, PdfPoint size) {
          canvas.saveContext();
          canvas.moveTo(size.x * 0.5, size.y - size.y * 0);
          canvas.lineTo(
            size.x * 1,
            size.y - size.y * 1,
          );
          canvas.lineTo(
            size.x * 0,
            size.y - size.y * 1,
          );
          canvas
            ..closePath()
            ..clipPath();
        },
        child: Container(
          color: PdfColors.red,
        ),
      ),
    ),
  );
```

**Comment by n1kStas** [comment]
Good
