### ISSUE TITLE
prevent `TextSpan`s from effecting the wrapping on `RichText` widgets

### ISSUE THREAD

**Issue by DetachHead** [DavBfr/dart_pdf#1110]
**Is your feature request related to a problem? Please describe.**

i'm trying to create a pdf simplar to [this example](https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/document.dart) but i want to be able to do stuff like make certain words in the paragraphs bold, italic, etc.

**Describe the solution you'd like**

a widget that takes a `List<Text>` and wraps to the next line automatically the same way that the individual `Text` widgets do, allowing you to specify a different style for each `Text` widget

**Describe alternatives you've considered**

wrapping a `List<Text>` in a `Flex` but that seemed to break the text wrapping

**Comment by DavBfr** [comment]
Use RichText() it's designed for that.

**Comment by DetachHead** [comment]
@DavBfr thanks! that's what i was looking for.

one question, is it possible to stop the individual `TextSpan`s from effecting the wrapping? eg.
```dart
pw.RichText(
  text: pw.TextSpan(
    children: [
      pw.TextSpan(
        text:
            'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      ),
      pw.TextSpan(
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
        text:
            'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      ),
    ],
  ),
);
```

renders like this:
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> **aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa**

when i want it to render like this:
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa**aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa**

**Comment by DavBfr** [comment]
Not possible.

**Comment by DetachHead** [comment]
i renamed the issue so i don't think it should be stale

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/189006892-afe799dc-e10d-4940-833c-9bad91fb9f5c.png)

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/192911749-75919c34-5002-469d-a073-eed4675339ad.png)

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/197086425-8969ceb6-d738-4234-8805-dedff94fabf6.png)

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/201798902-c4fa0df2-4076-4708-b729-ea4e7fabf26f.png)

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/209742938-30a61166-00f0-4ad8-9d44-4c7838cbae81.png)

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/213040966-fc58216c-5aec-429d-b8c0-533647cd8b24.png)
