### ISSUE TITLE
Flutter web - Unable to connect USB POS printer

### ISSUE THREAD

**Issue by techttiru** [DavBfr/dart_pdf#1116]
Unable to connect USB POS printer in flutter web app. I am creating flutter web app in which i am able to generate the PDF using this package and able to manually print from pdf to printer but when i try to connect the printer directly and try to send the pdf data to printer directly, i am unable to connect. is it possible to connect USB POS printer in flutter web app?

here are the two options that i have based on the documentations but i dont know how to get the URL for USB printer because my USB printer has only the USB interface and does not have ethernet or any other interface. hence it does not any ip address associated to this USB printer. So, my requirement is i need to connect this USB printer without the ip address. is there a way to do this?

Option:1

  ```
 final printer = PrinterNetworkManager('Since i dont have ip address, what should i give if i follow this approach??',
          port: 9100, timeout: const Duration(seconds: 10));
      final res = await printer.connect();

      if (res != PosPrintResult.success) {
        print('response of the connection - ${res.msg}');
        throw Exception('Unable to connect to the printer');
      }

      final profile = await CapabilityProfile.load();
      final generator = Generator(PaperSize.mm80, profile);
      var ticket = <int>[];

      await for (var page in Printing.raster(
          await _generatePdf(PdfPageFormat.roll80, title),
          dpi: 203)) {
        final image = page.asImage();
        ticket += generator.image(image);
        ticket += generator.feed(2);
        ticket += generator.cut();
      }

      printer.printTicket(ticket);
      printer.disconnect();
```

Option:2

```
    await Printing.directPrintPdf(
                        printer: const Printer(url: 'What is the url i should give here to connect - note: i am using windows machine'),
                        // printer: (await Printing.listPrinters()).first,
                        onLayout: (format) => _generatePdf(format, title),
                      );
```

Please share if any other options available to connect. is there any other package i should use to connect? 

Appreciate your quick response!..

**Comment by DavBfr** [comment]
You can't connect to a random local network IP address from a web browser.

**Comment by techttiru** [comment]
> Since

@DavBfr - Thanks for responding.. if i have POS printer with valid ip address, then can we connect using PrinterNetworkManager api to connect via flutter web?

**Comment by techttiru** [comment]
> You can't connect to a random local network IP address from a web browser.

@DavBfr - Hi, I got a POS printer with ethernet interface and i able to do the necessary setup in my windows machine and able to do the test print in windows machine using ethernet cable. but if i try connecting this printer via my flutter web application (chrome browser), its getting time out. i did adjust the time out configuration but its still failing. I followed your example link that was provided at [https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin](https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin) and not sure whether anything that i am missing. My requirement is to connect the POS printer from flutter web and send the pdf to printer directly to print. Is it possible or any other workaround to do this or any other package i should use to connect? can you please share some insight on this?
```

      final printer = PrinterNetworkManager('192.168.1.23');
      //   port: 9100, timeout: const Duration(seconds: 30));
      final res = await printer.connect();

      if (res != PosPrintResult.success) {
        print('response of the connection - ${res.msg}');
        throw Exception(
            'Unable to connect to the printer - ${res.msg}');
      }

      print('printer connected successfully - ${res.msg}');

      final profile = await CapabilityProfile.load();
      final generator = Generator(PaperSize.mm80, profile);
      var ticket = <int>[];

      await for (var page in Printing.raster(
          await _generatePdf(PdfPageFormat.roll80),
          dpi: 203)) {
        final image = page.asImage();
        ticket += generator.image(image);
        ticket += generator.feed(2);
        ticket += generator.cut();
      }

      printer.printTicket(ticket);
      printer.disconnect();
```

**Comment by DavBfr** [comment]
A web browser cannot connect to something else than a web server. It cannot connect to a printer via ethernet. That would be a huge security issue worldwide.

**Comment by techttiru** [comment]
> 

@DavBfr - Thank you for the quick response.. so how can i solve my problem? is there a way i can connect to the local machine printer? because my user does not want to see the pdf page opens up every time and click the print to print the content.  can you please suggest some workaround?

**Comment by DavBfr** [comment]
You can write a Windows service that creates a web service to print locally.

**Comment by techttiru** [comment]
> You can write a Windows service that creates a web service to print locally.

@DavBfr - ok great. is there any example that i can follow to achieve this? how can i create windows service from flutter web application that creates web service? any example/pointer would be really appreciated.. sorry for more questions as i am new to flutter and web application.

**Comment by DavBfr** [comment]
At this point, you'd better write a full windows flutter application, if the user has to install something besides the web browser.

**Comment by techttiru** [comment]
@DavBfr - yes thats one option but at this point of time firestore sdk does not to support completely for windows app. my web app completely depends on firestore. Thats the reason i continue to stick to web. is there any other alternative other than converting the application to windows?

**Comment by techttiru** [comment]
@DavBfr , also i am ok to create this print functionality alone as a windows application to print and ask user to install in their local machine but somehow, this functionality should be connected to the action that user takes in web application. for ex, if user click the print button in web application, somehow it should connect windows application to print immediately. is that possible?

**Comment by DavBfr** [comment]
Yes, it's absolutely possible. You can do that with Dart if you like, or something else. I don't have any examples in mind.

**Comment by techttiru** [comment]
@DavBfr - awesome.. Thank you. i will look at this option. other than this option, is there any other options that you can suggest? is this the option that you refer in your response? the option that you referred below is completely writing the entire application in windows or just writing the print functionality alone in windows and connect to web application or is it something other these two? Just to clarify your recommendation.

`You can write a Windows service that creates a web service to print locally.`

**Comment by DavBfr** [comment]
just writing the print functionality alone in windows and connect to web application

**Comment by techttiru** [comment]
@DavBfr - Thank for your response and support!. I will move forward with this approach.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by techttiru** [comment]
@DavBfr  Thank you!. Just did it.

**Comment by techttiru** [comment]
> just writing the print functionality alone in windows and connect to web application

@DavBfr Hi, I understand that this issue is closed but based on some suggestions from flutter community, there is another option to connect the local USB POS printer from flutter web. So, there is a package called 'web_usb" in pub.dev which helps to connect the device from flutter web. if we are able to sort out this issue then you can add this is also one of the option to connect from web to local printer in your document.
[https://pub.dev/packages/web_usb](https://pub.dev/packages/web_usb)

here is the code that so fart i had tried.

 ```
static Future<void> connectUsbPrinter() async {
    bool canUse = canUseUsb();
    if (canUse) {
     //* connect the specific USB printer device using the device's vendor id and product id.
      UsbDevice requestDevice = await usb.requestDevice(
        RequestOptions(
          filters: [
            RequestOptionsFilter(
              vendorId: 0x04B8,
              productId: 0x0E02,
            ),
          ],
        ),
      );
      
         await requestDevice.open();
         await requestDevice.reset();
         int firstInterfaceNumber =
         requestDevice.configuration?.interfaces[0].interfaceNumber ?? 0;
         await requestDevice.claimInterface(firstInterfaceNumber);

           //* this is taken from your example to generatePdf for 80 mm size. so it returns the Uint8List type.
           final pdfDataInUint8ListType = await generatePdf(PdfPageFormat.roll80);

          //* this is the api from web_usb to send data to device. 
           var usbOutTransferResult =   await requestDevice.transferOut(1, pdfDataInUint8ListType);
           
          //* all of them are working and i am able to connect the local machine device from flutter web and able to send the data but the problem is, data is being printed as undisplayable character in paper.  as per your example,  i see below code in your example.
          
               final profile = await CapabilityProfile.load();
      final generator = Generator(PaperSize.mm80, profile);
      var ticket = <int>[];

      await for (var page in Printing.raster(
          await generatePdf(PdfPageFormat.roll80),
          dpi: 203)) {
        final image = page.asImage();
        ticket += generator.image(image);
        ticket += generator.feed(2);
        ticket += generator.cut();
      }
      
      //* ideally the question is, how to convert the Uint8List to printable character type and send to transferOut api. transferOut api accepts TypedData type to send data.
          
          
    }
```

**Comment by techttiru** [comment]
@DavBfr  here is the attached image or PDF that i wanted to print.
[margin_15.pdf](https://github.com/DavBfr/dart_pdf/files/9277960/margin_15.pdf)
<img width="433" alt="Screen Shot 2022-08-07 at 9 05 08 PM" src="https://user-images.githubusercontent.com/106634012/183320102-e93c9cea-da1f-400b-ba12-3715a3d82c13.png">


But below is what i see in printed paper. So this could conversation problem. thats why looking for your input. 

![image](https://user-images.githubusercontent.com/106634012/183320165-5fa5c57c-109d-46d5-ba83-ab2d02585aa5.png)

**Comment by perret123** [comment]
@techttiru 
For my POS app I had the same problem that printing wasn't possible in the Web. I also use Firestore, so maybe my solution could work for you as well. Btw, are we developing the same app? :D

I solved it this way: As I am developing a multiplattform app in any case and Android/iOS have no problems connecting to the network printer, I used Firestore to add a "PrintAction" inside a collection. When an app with print capability is running, it will observe this collection and print the incoming "PrintActions". The downside is, that at least one app-version must be running, so web only is no option. But I figured this is not really a problem, as everybody has an old iOS or Android phone lying around which can concentrate on this task. I found this the better solution than a "Windows Service", as I guess not everybody has a Windows PC always running.

But yeah, there is one other solution, which I didn't like to use as it complicates the setup: Epson POS Printers have the ability to use a Web-API. But this also doesn't work from the web, as the address is a usual "http"-address without SSL. But there is also the option to add a SSL-Certificate to the Epson POS Printer. I didn't do this, but I think if you add a SSL certificate to the Printer and use the Web-API for printing, you could also print from a website. 

Hope this helps you and good luck with your app :-)

**Comment by techttiru** [comment]
@perret123 , Hi Thanks for responding.. Not sure whether we both are developing same app :). However, let me try to understand your solution.  So you are saying, add "printAction" attribute in the document and store in collection. then another windows based flutter app listens this collection/document with this "printAction" attribute and print?
1. Write document in collection as is from web app.
2. Create new windows app which will have only print functionality alone 
3. From the windows app, listen the doc from collection for which we need to print
4. print in local POS printer

is that what you are suggesting? please clarify. if so, yes this is one of the option but the observation on this option is, 
1. it adds additional read count in firestore collection
2. it takes time to print it because it goes to sever and then it goes to local and then it prints.

but currently what i am doing now is, 
```
  return await Printing.layoutPdf(
      onLayout: (format) =>
          _generatePdf(parameters);
```

This code will ask user permission to print from web for every print (basically it will show the pdf in preview mode and it will show a "print" button in it and then user have to print this button every time. so ever print this will happen). but my intension is to not to ask user to click the print button for every print. so i tried to bypass this user permission using chrome option.

[https://sapaad-help-center.groovehq.com/help/how-to-enable-auto-printing-from-google-chrome](https://sapaad-help-center.groovehq.com/help/how-to-enable-auto-printing-from-google-chrome)

It actually works as it bypass the user permission and able to print from web to local usb pos printer. but again my core root problem is not solved here. yes, not asking user permission is one problem but the other problem is time taken. This option is just bypassing the user permission but it actually generate the pdf, trying to show in preview mode and then it bypasses. so the time taken for this process is almost same even if we allow user to manually click the print button every-time.

so currently, if a put a new data entry via my web app, it takes 0.5 second to store in firestore collection but it takes another 4 to 5 seconds for printing alone if i go with this kind of bypass option which actually deviates my app purpose. i want to send the data directly to printer with much faster way.

Thats the reason, i tried using web-usb package and i able to connect the local printer from web app and able to print as well. but as i mentioned/attached the screen shot in above message, it prints some kind of non-readable characters. I think the reason could be i am not sending the correct formatted chars/data to printer. Thats why i was asking how to convert Uint8List chars to printable characters in pos printer. i tried this raster option that was provided in dart-pdf example but its not working in my web-usb interface.

any help would be really appreciated.

**Comment by perret123** [comment]
> @perret123 , Hi Thanks for responding.. Not sure whether we both are developing same app :). However, let me try to understand your solution. So you are saying, add "printAction" attribute in the document and store in collection. then another windows based flutter app listens this collection/document with this "printAction" attribute and print?
> 
> 1. Write document in collection as is from web app.
> 2. Create new windows app which will have only print functionality alone
> 3. From the windows app, listen the doc from collection for which we need to print
> 4. print in local POS printer
> 
> is that what you are suggesting? please clarify. if so, yes this is one of the option but the observation on this option is,
> 

Yes, if it is USB-Only printer, I guess you don't have another option. But why limit yourself to a USB-Only printer? A network thermal printer would do the job probably more well with less work to setup. And it doesn't cost the world in compare to development costs :D

> 1. it adds additional read count in firestore collection
> 2. it takes time to print it because it goes to sever and then it goes to local and then it prints.

1. Yes it adds additional reads and writes, but I don't think that is what makes a project expensive. 
2. Yes it adds more time - but I also think it is neglectable because for my project, the web-version is more of a "nice to have" but I expect most people to use the app-versions which can print directly.

> 
> but currently what i am doing now is,
> 
> ```
>   return await Printing.layoutPdf(
>       onLayout: (format) =>
>           _generatePdf(parameters);
> ```
> 
> This code will ask user permission to print from web for every print (basically it will show the pdf in preview mode and it will show a "print" button in it and then user have to print this button every time. so ever print this will happen). but my intension is to not to ask user to click the print button for every print. so i tried to bypass this user permission using chrome option.
> 
> https://sapaad-help-center.groovehq.com/help/how-to-enable-auto-printing-from-google-chrome
> 
> It actually works as it bypass the user permission and able to print from web to local usb pos printer. but again my core root problem is not solved here. yes, not asking user permission is one problem but the other problem is time taken. This option is just bypassing the user permission but it actually generate the pdf, trying to show in preview mode and then it bypasses. so the time taken for this process is almost same even if we allow user to manually click the print button every-time.
> 
> so currently, if a put a new data entry via my web app, it takes 0.5 second to store in firestore collection but it takes another 4 to 5 seconds for printing alone if i go with this kind of bypass option which actually deviates my app purpose. i want to send the data directly to printer with much faster way.
> 
> Thats the reason, i tried using web-usb package and i able to connect the local printer from web app and able to print as well. but as i mentioned/attached the screen shot in above message, it prints some kind of non-readable characters. I think the reason could be i am not sending the correct formatted chars/data to printer. Thats why i was asking how to convert Uint8List chars to printable characters in pos printer. i tried this raster option that was provided in dart-pdf example but its not working in my web-usb interface.
> 
> any help would be really appreciated.

There I can't give any input sadly, I use a EPSON T88-TMVI and use the EPOS-XML-Interface to print ... never tried printing with a PDF ... I use the PDF Library to print on normal "printers" and the EPOS-XML-Interface to print on these Epson Thermal Printers. 

But yeah maybe your USB-Printer has special commands as well, maybe it is worth it to look at this: https://pub.dev/packages/esc_pos_printer - but this seems for Bluetooth and Network printers only as well. But yeah, good luck :D
