### ISSUE TITLE
ability to customize what can be split into a new page in `MultiPage`

### ISSUE THREAD

**Issue by DetachHead** [DavBfr/dart_pdf#1118]
**Is your feature request related to a problem? Please describe.**
i have a `Header` and a `RichText` widget. i want to make it so that if they both can't fit on the same page, then it puts them both on the next page:

![image](https://user-images.githubusercontent.com/57028336/182836066-4d0eea46-2f44-45a1-ab31-2673da2c16be.png)

**Describe the solution you'd like**
a widget i can wrap widgets in that forces `MultiPage` to keep them on the same page if possible.

**Describe alternatives you've considered**
i tried wrapping them in other widgets like `Container`, since according to [the `MultiPage` documentation](https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html),
> A [Widget](https://pub.dev/documentation/pdf/latest/widgets/Widget-class.html) cannot be drawn partially on one page and the remaining on another page: It's insecable.

however this doesn't seem to be true for the widgets i tried wrapping them in: `Container` and `Wrap`. perhaps i'm misunderstanding?

**Comment by DetachHead** [comment]
currently working around this by wrapping the widgets in a `Table` with one cell, is there a better way?

**Comment by ljmatan** [comment]
Another example, even though both the title and the table are placed into Column they get split in separate pages. 

![Screenshot 2022-08-20 at 21 57 29](https://user-images.githubusercontent.com/73232684/185764247-e95f9590-50f7-4713-a3f5-79c1b74d9cf5.png)

**Comment by yurikong** [comment]
@DavBfr Good sir, you have made an amazing library! It's so easy to use yet so powerful, really appreciate it!
I am trying to make tables with data potentially more than a page. I read the doc, and some other people's issues and posts here, and confirmed that spanning widgets can't be larger than a page. It would be nice if the table cells wraps on a new page!
Is this gonna be implemented? Are there workarounds for now?

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale

**Comment by isaque-martins** [comment]
I am using the Inseparable widget to split the page and prevent headers from being on one page and the text on another.

```
pw.Inseparable(
  child: pw.Column(
    children: [
      Topic(title: dataTask["fields"][i]["title"]),
      StartText(
        title: dataTask["fields"][i]["title"],
        // content: field["value"],
      ),
    ],
  ),
)

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
Not stale
