### ISSUE TITLE
`TableOfContent` shows incorrect page number when footer margin pushes `Header` to the next page in `MultiPage`

### ISSUE THREAD

**Issue by DetachHead** [DavBfr/dart_pdf#1120]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
import 'dart:io';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

void main() async {
  final file = File('asdf.pdf');
  final pdf = await (pw.Document(pageMode: PdfPageMode.outlines)
        ..addPage(
          pw.Page(
            build: (final context) {
              return pw.Column(
                children: [pw.TableOfContent()],
              );
            },
          ),
        )
        ..addPage(
          pw.MultiPage(
            footer: (final pw.Context context) {
              return pw.Container(
                margin: const pw.EdgeInsets.only(top: 1.0 * PdfPageFormat.cm),
                child: pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                ),
              );
            },
            build: (final context) => [
              pw.Header(text: 'a', level: 1),
              pw.Text(pw.LoremText().paragraph(600)),
              pw.Header(text: 'b', level: 1),
            ],
          ),
        ))
      .save();
  await file.writeAsBytes(pdf);
}
```

**Expected behavior**

table of contents says "a" is on page 2 and "b" is on page 3

**Screenshots**

![image](https://user-images.githubusercontent.com/57028336/183273756-63f5c75b-1fd4-4edd-9268-c712b54115b6.png)
![image](https://user-images.githubusercontent.com/57028336/183273771-17febd10-61df-469c-9b8f-0eb92e486102.png)

**Flutter Doctor**

```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.1826], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.3)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
[√] VS Code, 64-bit edition (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Desktop (please complete the following information):**
 - [X] iOS
 - [X] Android
 - [ ] Browser
 - [X] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 15.1.1
 - Browser safari
 - Version idk

**Comment by DetachHead** [comment]
Not stale

**Comment by DetachHead** [comment]
I said not stale @DavBfr

**Comment by DavBfr** [comment]
@DetachHead Why don't you fix it if you need that?

**Comment by DetachHead** [comment]
I don't have the time or knowledge. I understand that you probably don't have the time either but I don't see why that means the issue should be closed, in case someone else who does decides to work on it

I don't get the point of stale bots. Just because no one is currently able to work on an issue doesn't mean it's not an issue

**Comment by KotlinIsland** [comment]
@DetachHead Stale bots are very useful as they indicate when an issue is "invalid", as in, noone has commented on the issue for a week. This is very helpful to maintainers as it helps remove issues that don't make sense, or were raised by accident.
