### ISSUE TITLE
MissingPluginException in Android with package printing: ^5.9.2

### ISSUE THREAD

**Issue by finnkassaoy** [DavBfr/dart_pdf#1121]
**Describe the bug**

I/flutter (24015): PrintingInfo:
I/flutter (24015):   canPrint: true
I/flutter (24015):   directPrint: false
I/flutter (24015):   dynamicLayout: true
I/flutter (24015):   canConvertHtml: true
I/flutter (24015):   canListPrinters: false
I/flutter (24015):   canShare: true
I/flutter (24015):   canRaster: true
E/flutter (24015): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method pickPrinter on channel net.nfet.printing)
E/flutter (24015): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (24015): <asynchronous suspension>
E/flutter (24015): #1      MethodChannelPrinting.pickPrinter (package:printing/src/method_channel.dart:226:21)
E/flutter (24015): <asynchronous suspension>
E/flutter (24015): #2      Printing.pickPrinter (package:printing/src/printing.dart:116:12)
E/flutter (24015): <asynchronous suspension>
E/flutter (24015): #3      _MyHomePageState.testPrint (package:directprint/main.dart:51:21)
E/flutter (24015): <asynchronous suspension>
E/flutter (24015): #4      _MyHomePageState.build.<anonymous closure> (package:directprint/main.dart:89:15)
E/flutter (24015): <asynchronous suspension>
E/flutter (24015): 

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```
 void testPrint() async{
    final doc = pw.Document();
    List<String> printers = [];
    doc.addPage(pw.Page(
        pageFormat: PdfPageFormat.roll57,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Text('Hello World, Testing the printer'),
          ); // Center
        }));
    await Printing.info().then((value) => print("Info ::: \n$value"));
    var myPrinter = await Printing.pickPrinter(context:context,);
    print('Selected printer: $myPrinter');

    await Printing.listPrinters().then((value) async {
      print("**** Printing Printers");
      value.forEach((element) {
        print('Printer: ${element.name}');
        print('Model: ${element.model}');
        printers.add(element.name);
        printers.add(element.model!);
        description.text = '${element.name} : ${element.model} \n';
      });
      if(value.isNotEmpty){
        var result = await Printing.directPrintPdf(
            printer: value[0],
            onLayout: (PdfPageFormat format) async => doc.save()
        );
        print("result : $result");
      }
    });
    
  }

**Desktop (please complete the following information):** 
 - [ ] Android

**Comment by DavBfr** [comment]
canListPrinters: false in the Printing.info() result means you can't call listPrinters. Because it's not something the Android API provides.

**Comment by finnkassaoy** [comment]
ok so directPrint also not possible from Android ?

**Comment by DavBfr** [comment]
Exactly

**Comment by finnkassaoy** [comment]
Thank you ...
