### ISSUE TITLE
HowTo: create file with landscape orientation, but in horizontal mode

### ISSUE THREAD

**Issue by eldarkk** [DavBfr/dart_pdf#1123]
How to create file with landscape orientation, but in horizontal mode?

Content is layed out in landscape mode, but opened file is in portrait mode. So for reading content i need to rotate my head by 90 degrees by clock time direction =).

hlp pls. Thx.

My code is:

```  
final doc = pw.Document(pageMode: PdfPageMode.outlines);

doc.addPage(pw.MultiPage(
      theme: pw.ThemeData(
          tableCell: ...,
      pageFormat: PdfPageFormat.a4,
      margin: pw.EdgeInsets.all(20),
      orientation: pw.PageOrientation.landscape,
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      build: (pw.Context ctx) => <pw.Widget>[ ...  ... ... ]
      
      return await doc.save();```

**Comment by DavBfr** [comment]
use pageFormat: PdfPageFormat.a4.landscape

**Comment by jeff9315** [comment]
I also have this exact problem. I tried adding **pageFormat: PdfPageFormat.letter.landscape** but that didn't work. I also tried removing the **orientation** paramter and adding **pageFormat: PdfPageFormat.letter.landscape** but that also didn't work.
