### ISSUE TITLE
Problem with newline in RichText (Flutter vs Server)

### ISSUE THREAD

**Issue by marciopaim-elevata** [DavBfr/dart_pdf#1124]
**Describe the bug**
When printing a text with more than one newline in sequence, it shows up in Flutter but not on the pdf generate on the server.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pw.RichText(
  text: pw.TextSpan(
      text: 'TEST\n\nTEST'),
),
```

**Expected behavior**
The only way I got it to work was with \r\n but then it shows a strange character at the end of the line.

**Screenshots**
![richtext_bug](https://user-images.githubusercontent.com/99829990/183510702-4bc1d1f6-a3f7-410e-aea2-aae26e5045e9.png)

**Flutter Doctor**
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.4 LTS 5.15.0-43-generic, locale pt_BR.UTF-8)
    • Flutter version 2.8.1 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/marcio/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • ASUS Z01MD (mobile) • HAAZB601X591EKG • android-arm64  • Android 7.1.1 (API 25)
    • Chrome (web)        • chrome          • web-javascript • Google Chrome 104.0.5112.79

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [X] Linux

**Smartphone (please complete the following information):**
 - Device: Asus Zenphone, Android 7.1.1

**Additional context**
I'm trying to use (almost) the same code to generate pdf both from Flutter and on the Server, with text loaded from database.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=LLBoRBAQIw0
