### ISSUE TITLE
Font height now working

### ISSUE THREAD

**Issue by woshitom** [DavBfr/dart_pdf#1125]
**Describe the bug**
I want to display Thai characters, to do so I'm using Kanit font (https://fonts.google.com/betterspecimen/Kanit?subset=thai)
Thai characters require a higher height than latin characters.

For example I want to display this character: พื้

my code is 

**To Reproduce**
```dart
var data_kanit_bold = await rootBundle.load("fonts/Kanit-Bold.ttf");
var kanitBold = pw.Font.ttf(data_kanit_bold);
pw.Text('พื้', textAlign: pw.TextAlign.center, style: pw.TextStyle(fontSize: 10, height: 5, font: kanitBold)),
```

Even though I added a height = 5, the character is being cropped:

<img width="26" alt="Screen Shot 2565-08-10 at 20 20 08" src="https://user-images.githubusercontent.com/7259389/183988047-bb0e225a-2e89-4f56-a796-2592b07353dd.png">

**Comment by DavBfr** [comment]
Seems to be an issue with the font decoding library.

**Comment by mahmoud-araby** [comment]
any updates on the issue @DavBfr when will be fixed

**Comment by Blue-Cheesecake** [comment]
Hi, I have this similar problem. Any resolution for this issue?
