### ISSUE TITLE
table couldn't create more than 20 page?

### ISSUE THREAD

**Issue by huongtran84** [DavBfr/dart_pdf#1126]
**Describe the bug**

If only small data table.fromTextArray  generate smaller 20 pages but big data .it raise exception "this widget created more than 20 pages:

` Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);
    final image = await imageFromAssetBundle('assets/images/sidebar-logo.png');
    final image1 = pw.Image(image, width: 80, height: 80);

    pdf.addPage(
      pw.MultiPage(
        
        pageTheme: _buildTheme(
            format.landscape,
            await PdfGoogleFonts.beVietnamProMedium(),
            await PdfGoogleFonts.beVietnamProBold(),
            await PdfGoogleFonts.beVietnamProMediumItalic(),
            await PdfGoogleFonts.beVietnamProBoldItalic(),
            image1),
        build: (context) => [
          //_contentHeader(context, image1),
          _contentTable(context),
         // _sumTable(),
          // pw.SizedBox(height: 4),
          // _termsAndConditions(context)
        ],
      ),
    );

    return pdf.save();
  }

 pw.Widget _contentTable(pw.Context context) {
    const tableHeaders = [
      'title 1',
      'title2',
      'title 3,
      'title 4',
      'title 5',
      'title 6',
      'title 7',
      'title 8',
    ];
    
    return pw.Table.fromTextArray(
      border: pw.TableBorder.all(
        color: PdfColors.black,
        width: .5,
      ),
      cellAlignment: pw.Alignment.center,
      headerDecoration: const pw.BoxDecoration(
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(2)),
        color: PdfColors.white,
      ),
      headerHeight: 25,
      cellHeight: 30,
      columnWidths: {
        0:const pw.FixedColumnWidth(150),
        1:const pw.FixedColumnWidth(250)},
      // cellAlignments: {
      //   0: pw.Alignment.centerLeft,
      //   1: pw.Alignment.centerLeft,
      //   2: pw.Alignment.centerLeft,
      //   3: pw.Alignment.center,
      //   4: pw.Alignment.center,
      //   5: pw.Alignment.centerRight,
      // },
      headerStyle: pw.TextStyle(
        color: PdfColors.black,
        fontSize: 10,
        fontWeight: pw.FontWeight.bold,
      ),
      cellStyle: const pw.TextStyle(
        color: PdfColors.black,
        fontSize: 8,
      ),
      rowDecoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(
            color: PdfColors.black,
            width: .5,
          ),
        ),
      ),
      headers: List<String>.generate(
        tableHeaders.length,
        (col) => tableHeaders[col],
      ),
      data: List<List<String>>.generate(
        donhangList.length,
        (row) => List<String>.generate(
          tableHeaders.length,
          (col) => donhangList[row].getIndexHoSo(col, row),
        ),
      ),
    );
  }

`

**Comment by Milad-Akarie** [comment]
@huongtran84 I believe there's a optional max pages limit property that defaults to 20 in MultiPage constructor

**Comment by huongtran84** [comment]
@Milad-Akarie  Thanks ! I found it
