### ISSUE TITLE
Format is selected as Letter for iOS even when the format is given as A4

### ISSUE THREAD

**Issue by sachin-dahal** [DavBfr/dart_pdf#1127]
**Describe the bug**
I've tested in both android and iOS to print the files. On Android, everything works fine and the printing paper format is selected as an A4 but while testing on iOS part, the `paper format` is selected as a `Letter`.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Printing.layoutPdf(
  format: PdfPageFormat.a4,
  name:
      "my_pdf_name.pdf",
  onLayout: (pdfFormat) async {
    return await file.save();
  },
);
```

**Expected behavior**
**`Paper Size`** for iOS needs to be selected as **`A4`**

**Comment by HasanAlqaisi** [comment]
Same issue, any solution?

**Comment by sachin-dahal** [comment]
> Same issue, any solution?

not fixed yet
