### ISSUE TITLE
How can I open a PDF file already existing on device

### ISSUE THREAD

**Issue by ResetPower** [DavBfr/dart_pdf#113]
Please forgive me.I am a Chinese, so I can't speak English very well.There will be a lot of things that go wrong in my issue.

How can I open a PDF file already existing on device? The examples that I can see are only say how to create a PDF file.If the "pdf" can't open a PDF file already existing on device, please add this new feature, if the "pdf" can, please teach me how to do it.

Thank you so much.

**Comment by DavBfr** [comment]
That's not supported, and will not.
