### ISSUE TITLE
Printing.layoutPdf() generates blank page on Firefox (web)

### ISSUE THREAD

**Issue by leoortolan96** [DavBfr/dart_pdf#1130]
**Describe the bug**
I am getting a blank page when trying to print a pdf generated using _Printing.layoutPdf()_ on Firefox.

**To Reproduce**
I am facing the issue when trying to print a document using my own code and also when trying to print from the demo (https://davbfr.github.io/dart_pdf/#/) on Firefox. My code and the demo both work on Chrome and Edge, but not on Firefox. Firefox shows me the print dialog with a blank document and if I save or print the document, I get a blank page as well. (See screenshots below)

**Expected behavior**
I expect the feature to work consistently across all web browsers, so my app's users can use the printing feature on the browser of their own choosing.

**Screenshots**
Feature works on Chrome:
![image](https://user-images.githubusercontent.com/63107101/185955423-65104d14-c34f-41bb-8fda-d7bf2220afbb.png)

But it does not work on Firefox:
![image](https://user-images.githubusercontent.com/63107101/185955606-8d5a4a4f-b05f-4d9a-a3fa-1ca568c075ca.png)

**Flutter Doctor**
(not relevant, since the demo itself is not working properly)

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [x] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: Asus Laptop
 - OS: Windows 7 64-bit
 - Browser: Firefox
 - Version: 103.0.2 (64-bit)

**Comment by ameenvga** [comment]
The same issue in firefox. works well in Google chrome.
