### ISSUE TITLE
Grouping elements which should not be breaked

### ISSUE THREAD

**Issue by obrunsmann** [DavBfr/dart_pdf#1138]
I use a multi page widget to generate a PDF with ~8-10 pages. Inside this PDF file I have sections with headlines and some content. The problem I have now is that the page break happens right between the headline and the content. I need a way to group the two elements and prevent pagination between them:

![image](https://user-images.githubusercontent.com/763812/187957078-46ae8bc3-a45b-49eb-8c0f-9d5b3eb45081.png)

**Comment by carpentierchloe** [comment]
Any solution on this ?

**Comment by DavBfr** [comment]
You can create your own:

```dart
class Inseparable extends pw.SingleChildWidget {
  Inseparable({required pw.Widget child}) : super(child: child);
  @override
  bool get canSpan => false;

  @override
  bool get hasMoreWidgets => false;

  @override
  void paint(pw.Context context) {
    super.paint(context);
    paintChild(context);
  }
}
```
