### ISSUE TITLE
 Widget won't fit into the page as its height (823.408) exceed a page height (728.5039370078739). You probably need a SpanningWidget or use a single page layout

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#114]
E/flutter (11562): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: Widget won't fit into the page as its height (823.408) exceed a page height (728.5039370078739). You probably need a SpanningWidget or use a single page layout

**The PDF pages will be multiple. So, How to use Spanning Widget in Multipage?**

**Comment by DavBfr** [comment]
the only SpanningWidgets are Table and Wrap. Use one of them.

**Comment by SNNafi** [comment]
any sample code ?? how to use?

**Comment by harmjanr** [comment]
@DavBfr Any example on this? I can't find anything about SpanningWidgets in the either the documentation or the source of the plugin.. 
I have a multipage PDF as well, and get the same error as @jazzbpn

**Comment by DavBfr** [comment]
You can find plenty of examples here:
https://github.com/DavBfr/dart_pdf/tree/master/pdf/test

**Comment by harmjanr** [comment]
@DavBfr Perfect. Thanks, I got it working 👍🏻

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by jagan999** [comment]
Hi
I have a use case where I need to export a large chart into PDF. Simple PdfImage gives me an error that my widget exceeds the page height and I need to use a Spanning Widget. Using the examples in the location above, I mimicked the Wrap functionality as below in the code snippet. This completes successfully but the PDF comes out empty. I thought this was a problem with PdfImage within a Wrap (shouldn't be the case) but if you see below, I only added a Text widget inside a Wrap and the PDF still comes out empty. Any suggestions on what I might be doing wrong here?

Thanks
Jagan


`      pdfwidgets.Document pdf = pdfwidgets.Document(deflate: zlib.encode);

      pdfWidgets.add(pdfwidgets.Center(
          child: pdfwidgets.Text("Income vs Expenses",
              style: pdfwidgets.TextStyle(
                  fontWeight: pdfwidgets.FontWeight.bold, fontSize: 16))));

      boundary = _globalKeyIncomeVSExpenses.currentContext.findRenderObject();
      if (boundary.debugNeedsPaint)
        await Future.delayed(const Duration(milliseconds: 20));
      image = await boundary.toImage(pixelRatio: 3.0);
      byteData = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
      imageBytes = byteData.buffer.asUint8List();
      pdfWidgets.add(pdfwidgets.Image(PdfImage(pdf.document,
          image: imageBytes, width: image.width, height: image.height)));

      pdf.addPage(pdfwidgets.Page(
        pageFormat: const PdfPageFormat(400, 800),
        build: (pdfwidgets.Context context) =>
            pdfwidgets.Wrap(children: <pdfwidgets.Widget>[
          pdfwidgets.Center(
              child: pdfwidgets.Text("Income vs Expenses",
                  style: pdfwidgets.TextStyle(
                      fontWeight: pdfwidgets.FontWeight.bold, fontSize: 16)))
        ]),
      ));

      file = File(fileName);
      file.writeAsBytesSync(pdf.document.save());
`

**Comment by DavBfr** [comment]
Yes, the last line: use pdf.save()

**Comment by Kiirous** [comment]
@harmjanr How did you made it? Even with DavBfr examples I didn't made it =/
In my case, Im using a ListView.Builder:

```
void _printDocument() async {
    Printing.layoutPdf(
      onLayout: (pageFormat) {
        final doc = pw.Document();
        doc.addPage(
          pw.MultiPage(
              pageFormat: PdfPageFormat.a4,
              margin: pw.EdgeInsets.fromLTRB(50, 16, 0, 0),
              build: (context){
                return <pw.Widget>[
                  pw.Header(
                    text: 'Produtos',
                  ),
                  pw.Table.fromTextArray(
                    cellStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      defaultColumnWidth: pw.IntrinsicColumnWidth(flex: 1),
                      columnWidths: {0: pw.FractionColumnWidth(.3), 1: pw.FractionColumnWidth(.2), 2: pw.FractionColumnWidth(.2), 3: pw.FractionColumnWidth(.1), 4: pw.FractionColumnWidth(.1)},
                      cellAlignments: {0: pw.Alignment.centerLeft, 1: pw.Alignment.centerLeft, 2: pw.Alignment.centerRight},
                      data: <List<String>>[
                        <String>['Código de barras', 'Nome', 'Valor de venda', 'Ativo', 'Estoque'],
                      ]
                  ),
                      pw.ListView.builder(
                        itemCount: widget.listItems.length,
                        itemBuilder: (context, index){
                          return buildPdfTable(widget.listItems[index]);
                        },
                      ),
                ];
              }
          ),
        );
        return doc.save();
      },
    );
  }
```
```
pw.Widget buildPdfTable(ProductItem item){
    return pw.Table.fromTextArray(
          defaultColumnWidth: pw.IntrinsicColumnWidth(flex: 1),
          cellAlignment: pw.Alignment.center,
          columnWidths: {0: pw.FractionColumnWidth(.3), 1: pw.FractionColumnWidth(.2), 2: pw.FractionColumnWidth(.2), 3: pw.FractionColumnWidth(.1), 4: pw.FractionColumnWidth(.1)},
          cellAlignments: {0: pw.Alignment.centerLeft, 1: pw.Alignment.centerLeft, 2: pw.Alignment.centerRight},
          data: <List<String>>[
            <String>['${item.barCode}', '${item.name}', '${FormatterUtils.toCurrency(item.saleValue)}', '${item.isActive ? 'Sim' : 'Não'}', '${item.stockCurrent.toStringAsFixed(3).replaceAll('.', ',')}'],
          ],
        );
  }
```
The error: 

I tried to wrap the ListView.builder with Wrap Widget, but it shows another error: 

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: Widget won't fit into the page as its height (865.8559999999999) exceed a page height (825.8897637795275). You probably need a SpanningWidget or use a single page layout`

`E/flutter ( 7239): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.`

Pls, any help?

**Comment by Cressplant** [comment]
Like this:

`pdf.addPage(MultiPage(
      pageTheme: pageTheme,
      build: (Context context) {
        return [
Widget(...),
Widget(...),
Table(...)
        ];
      }));`

**Comment by yusufferdogan** [comment]
======== Exception caught by gesture ===============================================================
```
The following _Exception was thrown while handling a gesture:
Exception: This widget created more than 20 pages. This may be an issue in the widget or the document. See https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html
```
I was facing with Widget won't fit error then
I just wrap Paragraph with wrap what's wrong ?

**Comment by LeapingSwan** [comment]
Hi @DavBfr 

I too am getting the following error:

Exception: Widget won't fit into the page as its height (1073.4532283464557) exceed a page height (777.8897637795275). You probably need a SpanningWidget or use a single page layout

In my case this is a data from a Textfield passed in as a Paragraph, where the number of lines can vary.  In most cases it is likely to be small and no problem but I am testing for when an end user could make an entry longer than a page.  

I see the error is testing both the height of the page and the child (using child.box!.height).  Is there any way I can access the height of the child before the error exception is thrown?  This would allow me to pass the text through a function and create a series of paragraphs that meet the requirements.

Similarly if the PDF is going to exceed the 20 page limit can I:
a) change that limit to be higher if I want to and
b) whatever the limit is, test if it will exceed that so I can warn the user rather than throw an exception?

Thanks

Stephen

**Comment by tuan-binh-ntd** [comment]
You should use ...List.generate to handle this exception.

**Comment by hayelom123** [comment]
if the text  length is more than one page  it is not wrapping it to the next page .it is throwing the same error

**Comment by naseerx** [comment]
Hello @DavBfr 
I was facing the same issue and then i use the Wrap widget. Now the error is

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'TooManyPagesException'
#0      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:251:9)
#1      Document.addPage (package:pdf/src/widgets/document.dart:117:10)
#2      _QuillPageState.generatePdf (package:daiaryapp/pages/addDairyPage/quill_page.dart:76:9)
<asynchronous suspension>
#3      _QuillPageState.build.<anonymous closure>.<anonymous closure> (package:daiaryapp/pages/addDairyPage/quill_page.dart:320:48)
<asynchronous suspension>
```

This is my Code :

```

   pdf.addPage(pw.MultiPage(
      build: (pw.Context context) {
        final content = <pw.Widget>[];

        // Add a title to the PDF
        content.add(
          pw.Center(
            child: pw.Text(
              post.dairyName.toString(), // Replace with your desired title
              style: customTitle,
            ),
          ),
        );

        int itemsPerPage = 8;

        for (var i = 0; i < deltaData['ops'].length; i++) {
          final op = deltaData['ops'][i];

          if (op.containsKey('insert')) {
            if (op['insert'] is String) {
              final lines = (op['insert'] as String).split('-');

              for (var line in lines) {
                final textWidget = pw.Padding(
                  padding: pw.EdgeInsets.all(1.0),
                  child: pw.Text(
                    line.trim(), // Trim to remove extra spaces
                    style: customTextStyle, // Apply custom text style here
                  ),
                );

                content.add(textWidget);
              }
            } else if (op['insert'] is Map &&
                op['insert'].containsKey('image')) {
              final imageData = op['insert']['image'].split(',')[1];
              final Uint8List decodedImage = base64Decode(imageData);

              final imageWidget = pw.Padding(
                padding: pw.EdgeInsets.all(1.0),
                child: pw.Image(
                  pw.MemoryImage(
                    decodedImage,
                  ),
                  fit: pw.BoxFit.cover,
                  height: 245.0,
                ),
              );

              content.add(imageWidget);
            }
          }

          if (i > 0 && (i + 1) % itemsPerPage == 0) {
            content.add(pw.Container(width: 1.0, height: 1.0));
          }
        }

        // return content;
        return [
          pw.Wrap(
            children: content,
          ),
        ];
      },
    ));
```

**Comment by Mubashir-Saeed1** [comment]
> @DavBfr Perfect. Thanks, I got it working 👍🏻

Can you give me an example code of this working. Thanks in advance
