### ISSUE TITLE
PlayStore detects REQUEST_INSTALL_PACKAGES even when app never uses it

### ISSUE THREAD

**Issue by sharmaAshish-dev** [DavBfr/dart_pdf#1153]
Hi, we recently got an inbox from Play Store stating that our app contains REQUEST_INSTALL_PACKAGES permission and that we have to declare this on Play Store. However, the problem is we never use it, no calls made to Permission.requestInstallPackages across our codebase.

The question is, how do I remove unused permission requests from our app? If currently not possible, is there any suggestion?

![WhatsApp Image 2022-09-21 at 3 32 15 PM](https://user-images.githubusercontent.com/60459068/191493532-41bb8b8f-d349-455e-9ced-33cf538d70fb.jpeg)

Also, In my Manifest merger log it is clearly shown that the permission is been merged with apps menifest.
![image](https://user-images.githubusercontent.com/60459068/191493982-b2ff922b-c8b9-4f31-bd40-131679d2ced2.png)

**Comment by DavBfr** [comment]
Sorry, it's not the printing package, it has no mention of `REQUEST_INSTALL_PACKAGES` in the sources, and has no dependencies except pdf.
Check that your pub cache is not compromised or that you have this defined somewhere else.

**Comment by cassioseffrin** [comment]
Hello DavBr,

I am also getting the same issue of @sharmaAshish-dev. Although the library printing is not declaring the  REQUEST_INSTALL_PACKAGES it is been added to apk according with logs : 

`build/app/outputs/logs/manifest-merger-release-report.txt`

		ADDED from [:printing] _MY_PREFIX_PATH_build/printing/intermediates/library_manifest/release/AndroidManifest.xml:9:13-71
uses-permission#android.permission.REQUEST_INSTALL_PACKAGES


Do you have any ideia why this is happening?

**Comment by sharmaAshish-dev** [comment]
> Hello DavBr,
> 
> 
> pubspec.yml:
> `  printing: ^4.0.0`
> 
> `flutter: 1.22.6`
> 
> I am also getting the same issue of @sharmaAshish-dev. Although the library printing is not declaring the  REQUEST_INSTALL_PACKAGES it is been added to apk according with logs : 
> 
> `build/app/outputs/logs/manifest-merger-release-report.txt`
> 
> ```
> ADDED from [:printing] _MY_PREFIX_PATH_build/printing/intermediates/library_manifest/release/AndroidManifest.xml:9:13-71
> uses-permission#android.permission.REQUEST_INSTALL_PACKAGES
> ```
> 
> Therefore the google analytic bot is automatically rejecting the app submission. Do you have any ideia why the flutter build apk is automatically including this forbidden REQUEST_INSTALL_PACKAGES on the APK?
> 

It's actually not related to this plugin. Could you please share some more lines from logs.txt from below this specific line.

**Comment by cassioseffrin** [comment]
Thks the prompt response @sharmaAshish-dev  I will put the entire log file tomorrow. However the log is pretty clear: ADDED from [:printing].  If it's not came from printing it means that the LOG is not correct. I will also try to remove the printing from pubspec.yml and check it again to see if this REQUEST despairs.

**Comment by DavBfr** [comment]
printing: ^4.0.0, really? This is from 2 years ago. Please upgrade to 5.10.1 first.

**Comment by cassioseffrin** [comment]
@DavBfr yes really. The entire project is on flutter 1.22.6 without null safety. For versions of printing upper to 4 I need to refactor the entire project to null safety and it's hard! Do you think it's a possibility of v4 has this issue?

**Comment by DavBfr** [comment]
Yes, that's possible.

**Comment by cassioseffrin** [comment]
Thks so much @DavBfr. I will work in this direction to fix it.

**Comment by cassioseffrin** [comment]
@DavBfr my feedback:

As I don't have enough time to upgrade my app and consequently the printing I have managed to solve it by adding this to Androidmanifest.xml of my app: 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" //Add this line
    package="com.example.app">

    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove"/> 
...
</manifest>
```

The tools:node='remove' will remove the permission from final manifest.xml

This technique can be used to remove other permissions also. In my case I Had another lib called open_file that also make  this REQUEST of INSTALL_PACKAGES.
