### ISSUE TITLE
[Flutter Web] Release Printing Page doesn't work

### ISSUE THREAD

**Issue by iamar1k92** [DavBfr/dart_pdf#1157]
**Describe the bug**
Printing works fine on debug localhost, but on hosting it doesn't work.
it gives error: Nosuchmethoderror: method not found: 'L' (a.L is not a function. (In 'a.L(0,10)','a.L' is undefined))

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  Get.to(
      () => PreviewPrint(generate: pdf.save(), name: 'invoice#$serialNo.pdf'));

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:printing/printing.dart';

class PreviewPrint extends StatelessWidget {
  final Future<Uint8List> generate;
  final String name;
  const PreviewPrint({super.key, required this.generate, required this.name});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Scaffold(
      appBar: AppBar(title: Text('Print Preview')),
      body: PdfPreview(
        canChangePageFormat: false,
        canDebug: false,
        onPrinted: ((context) => {Get.back()}),
        onShared: ((context) => {Get.back()}),
        pdfFileName: name,
        build: (format) => generate,
      ),
    ));
  }
}

```

**Expected behavior**
It should open the default preview page in release mode as it do in debug mode.
**Screenshots**
https://i.imgur.com/xtCsilJ.png

**Flutter Doctor**

```
sultan@Sultans-MacPro ~ % flutter doctor -v
[✓] Flutter (Channel master, 3.4.0-19.0.pre.333, on macOS 12.6 21G115
    darwin-arm64, locale en-PK)
    • Flutter version 3.4.0-19.0.pre.333 on channel master at
      /Users/sultan/Developments/softwares/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ed2b55a70b (11 days ago), 2022-09-17 19:01:24 -0400
    • Engine revision f144ceca15
    • Dart version 2.19.0 (build 2.19.0-213.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sultan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/sultan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Desktop (please complete the following information):**
 - [x] Browser

**Smartphone (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [e.g. safari, chrome]
 - Version [e.g. latest]

**Additional context**

**Comment by iamar1k92** [comment]
I was struggling with this issue for last 2 days, today; i tried again today but this time tried to change my pdf creation code, removing some of the elements, i was able to make a perfect print preview on release mode as well.

Make sure that you're pdf code doesn't contain Expanded, Flexible, Spacer or any other relevent outbounding area widgets.

i had expanded and spacer widgets, removing them solved my problem.

Expanded do give Nosuchmethoderror: method not found: 'L' (a.L is not a function. (In 'a.L(0,10)','a.L' is undefined))
Spacer gives Unsupported operation: Infinity.toInt()

and moreover, i also removed a pdffont which it downloads from google fonts before creating the pdf - that i used to add emoji in pdf. I haven't check if it caused any problem, but if you have it, you can try to remove that as well.

Thing is pretty much strange, you don't have these issues on debug mode, while it can be so stressing to find and fix on production mode , which usually done on hit and trial basis.

Also want to mention, you're plugin is great!!, there is no issue evolving it, i found that pdf code had it. thank you for helping with very good plugin!

**Comment by adiomas** [comment]
In my case, it is also working in debug mode, but on hosting I get an error "Unable to display the document". (I added scripts in index.html)
