### ISSUE TITLE
Issue with memory allocation

### ISSUE THREAD

**Issue by MichelMelhem** [DavBfr/dart_pdf#1158]
Hello,
The is an issue with memory allocation that seems to affect a lot of users.
This can be found in these :
#1141
#1154
#1140
#1128

Can you take a look ?

Best regards

**Comment by DavBfr** [comment]
Can someone create a test project that reproduces the issue?

**Comment by MichelMelhem** [comment]
Here you can find a  demo with the error in the readme https://github.com/MichelMelhem/demo_error.git

**Comment by DavBfr** [comment]
@MichelMelhem That works perfectly.

If you want to lower the memory, add a `dpi` parameter to `pw.MamoryImage`:

```dart
List<pw.Widget> pictures = List.generate(
        40,
        (index) => pw.Padding(
            child: pw.Image(
              pw.MemoryImage(bytes, dpi: 100),
              width: 40,
              height: 20,
            ),
            padding: const pw.EdgeInsets.all(8)));
```

**Comment by DavBfr** [comment]
Always use jpeg image that are the right dimensions. otherwise they will be embedded as is in the PDF and all have to fit in memory.
