### ISSUE TITLE
unwanted margins 

### ISSUE THREAD

**Issue by evalsxonted** [DavBfr/dart_pdf#1160]
**Describe the bug**
no matter what I tried, I can not remove or modify the margins of the generated pdf
**To Reproduce**

```
`await Printing.layoutPdf(
                      onLayout: (format) {
                        return Printing.convertHtml(
                            html: "<!DOCTYPE html> <html> <head> <style> body { background-color: #cccccc;  margin: 0px; padding: 0px;} </style> </head> <body> hi from html </body> </html>",
                            format: format.copyWith(marginLeft: 100, marginBottom: 0, marginRight: 0, marginTop: 0)
                        );
                      },
                      format: PdfPageFormat.a4.copyWith(marginLeft: 0),
                      // dynamicLayout: false
                  );`
```

```dart
`await Printing.layoutPdf(
                      onLayout: (format) {
                        return Printing.convertHtml(
                            html: "<!DOCTYPE html> <html> <head> <style> body { background-color: #cccccc;  margin: 0px; padding: 0px;} </style> </head> <body> hi from html </body> </html>",
                            format: format.copyWith(marginLeft: 100, marginBottom: 0, marginRight: 0, marginTop: 0)
                        );
                      },
                      format: PdfPageFormat.a4.copyWith(marginLeft: 0),
                      // dynamicLayout: false
                  );`
```

**Expected behavior**
the margins should change when I change them!

**Screenshots**

![Screenshot_1664626323](https://user-images.githubusercontent.com/43685413/193409115-35bd7809-7319-460b-81cb-80cf28709612.png)

**Flutter Doctor**

> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.2006], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
>     X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
>         MSVC v142 - VS 2019 C++ x64/x86 build tools
>          - If there are multiple build tool versions available, install the latest
>         C++ CMake tools for Windows
>         Windows 10 SDK
> [√] Android Studio (version 2021.2)
> [√] VS Code (version 1.71.2)
> [√] Connected device (4 available)
> [√] HTTP Host Availability
> 
> ! Doctor found issues in 1 category.

```
```

**Desktop (please complete the following information):**
 - [ -] iOS
 - [ -] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
I've tried different types of devices, yet the same issue for all, this device is an example
 - Device: [Nexus 4 API 30 (AVD)]
 - OS: [Android 11.0]
 - Browser [none]
 - Version [none]

**Additional context**
its just a simple use, nothing complicated directly the code that i provided.

**Comment by salih588** [comment]
I m facing same margin issue!. is there any solution for this?

**Comment by evalsxonted** [comment]
I think this issue has nothing to do with the package itself, it is solved by editing the html code.
I solved it by adding this style:
    `<style type="text/css" media="print">
    @page
    {
        margin: 0mm; 
    }
    html
    {
        margin: 0px; 
    }
    body
    {
        margin: 0mm; /* margin you want for the content */
    }
    </style>`
