### ISSUE TITLE
Missing letters only when printing PDF

### ISSUE THREAD

**Issue by igbenic** [DavBfr/dart_pdf#1162]
**Describe the bug**

When opening the PDF looks fine, but only when printing the PDF some letters are missing. We are using OpenSans regular, bold italic and bold italic from assets with no errors so I believe the font should be embedded. Checking with `strings /path/to/document.pdf | grep -i FontName` they are indeed listed on the PDF file.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

Printing PDF should keep the same letters as when viewing.

**Screenshots**

<img width="439" alt="Screenshot 2022-10-04 at 06 23 44" src="https://user-images.githubusercontent.com/10614250/193733973-a3f63f14-4b4e-4035-8da0-256e4ab554ff.png">
Attached is the screenshot of a part of the scanned document on the left and the same part when viewing the document on the right.

**Flutter Doctor**

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-HR)
    • Flutter version 3.3.3 on channel stable at /Users/igbenic/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (5 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/igbenic/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS16
 - Browser stock browser, safari
 - Version 22

**Additional context**

**Comment by deepak-agendaboa** [comment]
@igbenic It seems that it is related with https://github.com/DavBfr/dart_pdf/issues/1041
