### ISSUE TITLE
Text Widget doesn't support middle eastern language

### ISSUE THREAD

**Issue by AriDevC** [DavBfr/dart_pdf#1163]
**Describe the bug**
Text Widget from the pdf lib shows texts in Middle Eastern languages such as Kurdish or Arabic in a mixed sequence

**To Reproduce**
1- Make a new pdf doc with a Text widget that is in some middle eastern language
2- Display the pdf (using the printing package)

```
  final ttf = await fontFromAssetBundle('assets/fonts/myFont.ttf');  // using the printing package

final doc = pw.Document(title: 'Care');

doc.addPage(pw.Page(
      pageTheme: pageTheme,
      build: (pw.Context context) => pw.Center(
            child: pw.Text(
              'سڵاو چۆنی',
              style: pw.TextStyle(font: ttf),
            ),
          )));```




**Expected behavior**
Text Widget from the Material lib doesn't behave that way.


**Desktop (please complete the following information):**
 - macOs

**Comment by AriDevC** [comment]
<img width="747" alt="Screen Shot 2022-10-07 at 10 25 03 PM" src="https://user-images.githubusercontent.com/107554424/194639458-cef4cce6-acee-4b48-8bab-1b05f0cec323.png">

**Comment by AriDevC** [comment]
If anyone came across this issue, consider using the `flutter's screenshot plugin` to screenshot your widget and use it to make the pdf.

**Comment by AriDevC** [comment]
@DavBfr any updates on this issue?

**Comment by AriDevC** [comment]
@DavBfr any updates on this issue?

**Comment by DavBfr** [comment]
@AriDevC I'm not working on that, I don't know how LTR languages work, sorry. Someone has to take over this and implement it.
