### ISSUE TITLE
Can't change Icon color

### ISSUE THREAD

**Issue by JeffTyfoom** [DavBfr/dart_pdf#1168]
Can't change these Icon color (see attach file)

I used this following code

 final doc = pw.Document(
      theme: pw.ThemeData(
          iconTheme: const pw.IconThemeData(color: PdfColors.purple200)));
          
<img width="443" alt="Screen Shot 2022-10-14 at 1 02 17 AM" src="https://user-images.githubusercontent.com/91708709/195660412-9fe4e4e5-cb40-4259-9079-90a5a7059d2f.png">

But no effect.

**Comment by DavBfr** [comment]
That's the Android print dialog. I don't know if it's possible to change.
