### ISSUE TITLE
Content overlaps on footer.

### ISSUE THREAD

**Issue by hillol3786** [DavBfr/dart_pdf#117]
**I tried print and HTML document using the below method:**
```
await Printing.layoutPdf(
    onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
          format: format,
          html: '',
        ));
```
**I made :**
```
<style>
footer {
            position: fixed;
            left: 0;
            bottom: 0px;
            width: 100%;
        }
</style>
```
**so that the footer repeats on each page.**
**but while printing other contents overlap on it.**
**here is the output:**
[sample gp.pdf](https://github.com/DavBfr/dart_pdf/files/3431616/sample.gp.pdf)
**Please provide me a solution for this. I need footer in each page without overlapping with other content in that page.**

**Comment by DavBfr** [comment]
That's a CSS issue, nothing I can fix.
