### ISSUE TITLE
How can the page be printed as full page without the wide margin?

### ISSUE THREAD

**Issue by JmyW** [DavBfr/dart_pdf#1171]
Hi 
That is indeed a great package. Thanks for offering it. I just implemented a printing function in my Flutter Web app. The printing is functioned good but the margin is too much. Please refer the screenshot I attached. How can I remove or reduce the wide margin of 4 sides like full page? I have taken two days, cannot find a way to reduce the margin. Please kindly help, thanks a lot. 

![image](https://user-images.githubusercontent.com/26256681/196196410-f9f180f9-fb06-4761-98ad-f3df9eafd5f2.png)

**Comment by DavBfr** [comment]
Just change the page format, that's where the margin is configured.

**Comment by JmyW** [comment]
@DavBfr Thanks for prompt reply. I just tried PdfPageFormat.standard, PdfPageFormat.letter, PdfPageFormat.legal, no one change that. 
Could you give more information how to change the PageFormat? any example code?

pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Text("1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890-1234567890"),
         ]
       }
)

**Comment by JmyW** [comment]
@DavBfr Hi Dav, Please kindly help how to set PageFormat. Thanks!
