### ISSUE TITLE
Devanagari text not render properly

### ISSUE THREAD

**Issue by iamshivkumar** [DavBfr/dart_pdf#1172]
**Describe the bug**
Truetype font does not support Marathi/Hindi text. Complex script.

**To Reproduce**

    final font = await PdfGoogleFonts.poppinsRegular();
    doc.addPage(pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Text(
              '''ज्याप्रमाणे जीवनात प्रत्येक गोष्ट महत्वाची असते त्याच प्रमाणे आणि त्यापैकी एक गोष्ट म्हणजे मोटिवेशन, कधी कधी आपण कठीण परिस्थितीचा सामना करताना हतबल होऊन लगेच हार मानतो पण अश्या परिस्थिती मध्ये जर आपल्याला उत्साह निर्माण करणारे काही विचार कानावर पडले तर किंवा आपल्या वाचनात काही उत्साह पूर्वक विचार आलेत तर.''',
              style: pw.TextStyle(
                font: font
              )
            ),
          ); // Center
        }));
**Expected behavior**
It should render text as it is
**Screenshots**
<img width="303" alt="Screenshot 2022-10-18 at 10 28 38 PM" src="https://user-images.githubusercontent.com/59016883/196497500-512c67d3-37bb-4861-8679-105f34b05376.png">

**Flutter Doctor**
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.2 on channel stable at /Users/shivkumarkonade/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/shivkumarkonade/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • My phone (mobile) • A316D9A7-BAB0-4BC5-8E0B-186C7E57D8AF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.6
      21G115 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome
      106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nixrajput** [comment]
Same issue.

**Comment by nixrajput** [comment]
Is there any solution for this?

**Comment by niraj8763** [comment]
same issue
