### ISSUE TITLE
UrlLink not working with web

### ISSUE THREAD

**Issue by jimmy-vo** [DavBfr/dart_pdf#1174]
**Describe the bug**
it works with android, but not on web and windows platform:
1. tap print, save as pdf
2. check hyperlink text => not open url on tap

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
UrlLink(
  child: Text('this is a link}'),
  destination: item.organizationUrl ?? "#",
)
```

**Expected behavior**
 - works on web

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [x] Windows
 - [ ] Linux

**Comment by jimmy-vo** [comment]
@DavBfr No rush but I desperately need this working on Web platform. I can take a look and create a PR to fix it, but I'd like to hear your thoughts on this first. You may have a good idea where to look at.

**Comment by DavBfr** [comment]
I have no clue. The code is just dart. Maybe a js compilation edge case

**Comment by DavBfr** [comment]
Can't you click on the link on the PDF generated here? https://davbfr.github.io/dart_pdf/#/

**Comment by jimmy-vo** [comment]
alright, we can narrow down the case. If I choose print, and save as pdf, it doesn't work. But if I save it by clicking on the share button, it works for me. This work around is good enough for me

**Comment by DavBfr** [comment]
Ok, so it's not a bug in the PDF library, but a bug in your web browser where it removes the links when you use "save as PDF".

**Comment by jimmy-vo** [comment]
by the way, I used chrome and edge to test it. But your explanation makes sense, closing this now. Thanks. I appreciate this useful library!
