### ISSUE TITLE
Landscape to display as landscape orientation rather than landscape content with portrait orientation

### ISSUE THREAD

**Issue by MrHarrisOnline** [DavBfr/dart_pdf#118]
I would like a way to display the resulting pdf file as landscape content with a landscape orientation. Having the content as landscape but the page orientation remain in portrait is not great for me because my users with often refer to the content via the file. Very few people will bother to print or edit the pdf in anyway. They will want to read the file constatly for reference. They are calendars...

Maybe we could have it so I can select the page orientation and the content orientation independantly?

Is there something I am over looking, is there a way to rotate the actual page orientation as it appears in the pdf file when it is created? Please let me know.

<img width="537" alt="Screenshot 2019-07-25 at 20 00 02" src="https://user-images.githubusercontent.com/43497902/61901145-084ec780-af17-11e9-9093-bef458abcbea.png">

**Comment by DavBfr** [comment]
You used:
```dart
Page(
  pageFormat: PdfPageFormat.a4,
  orientation: PageOrientation.landscape
)
```

where you wanted to use:

```dart
Page(
  pageFormat: PdfPageFormat.a4.landscape,
)
```

**Comment by MrHarrisOnline** [comment]
Thanks very much, All sorted!
