### ISSUE TITLE
how to get ttf Metrics Info

### ISSUE THREAD

**Issue by shinxxxxwon** [DavBfr/dart_pdf#1186]
I am drawing text by specifying coordinates in pdf.  
```
  final data = await rootBundle.load('assets/fonts/SourceHanSans-Medium.ttf');

  pdfWidget.Widget drawText(
      double startX, double startY, String text, pdfWidget.Font font) {
    return pdfWidget.Positioned(
      left: startX,
      top: startY,
      child: pdfWidget.Text(text, style: pdfWidget.TextStyle(font: font)),
    );
  }
```  
I want to get glyph information of text  
![image](https://user-images.githubusercontent.com/82139229/199206200-f479eb4a-7f86-4f4e-b53b-407a07b5f9eb.png)  

Searching the API, I realized that you can get glyph information from `TtfParser class`.  

I checked that the information is saved in `glyphInfoMap`, but I want to know how to get the glyph information about the entered text by entering the text.

**Comment by DavBfr** [comment]
Look at this example: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/metrics_test.dart

**Comment by shinxxxxwon** [comment]
I used the code below to use the ttf file for assets.  
```
inal data = await rootBundle.load('assets/fonts/SourceHanSans-Medium.ttf');
 pdfWidget.Font font = pdfWidget.Font.ttf(data);
```
Looking at the example of the attached URL, I need the data below.
```
  final metricsUnscaled = font.glyphMetrics(codeUnit);
  final fontSizeW = size.x / metricsUnscaled.maxWidth;
  final fontSizeH = size.y / metricsUnscaled.maxHeight;
  final fontSize = min(fontSizeW, fontSizeH);
  final metrics = metricsUnscaled * fontSize;
  final m = metricsUnscaled * font.unitsPerEm.toDouble();

  final x = (size.x - metrics.maxWidth) / 2.0;
  final y = (size.y - metrics.maxHeight) / 2.0 - metrics.descent;
```
Is there another way to cast `pdfWidget.Font` data to `PdfFont` data? `as PdfFont` seems to be the wrong way to go.

**Comment by DavBfr** [comment]
PdfWidget.Font should have a getFont method to retrieve the font object.

**Comment by shinxxxxwon** [comment]
I got the width and height of a single text via `emSize`.  

But something went wrong. The difference is that the width and height of the same text are compared in `win32` and `flutter`. I think it's probably the difference in `dpi`. Is there any way to solve this problem? `font` and `emSize` were tested under identical conditions.
