### ISSUE TITLE
[Bugs][Windows] print on windows can not get the extra printer settings

### ISSUE THREAD

**Issue by cuishijie1991** [DavBfr/dart_pdf#1187]
printing-5.9.3

print_job.cpp
method printPdf()
 Line 88   
dmExtra = DeviceCapabilities(fromUtf8(printer).c_str(), NULL, DC_EXTRA,
                                 NULL, NULL);
get the size of dmExtra, but didn't read dmExtra data.This causes additional Settings of the printer driver, such as print speed, print concentration, etc., to be random.
please fix it, thank u!

**Comment by DavBfr** [comment]
Looks you know what you're talking about. Please create a PR.

**Comment by cuishijie1991** [comment]
![5594A896-3494-4F2B-8927-8CA2C5AEAB90](https://user-images.githubusercontent.com/17976216/199469455-0f2123fc-94f7-4122-9c7a-adc1bc45ff2a.png)
Unfortunately, I'm not very good at Windows-related programming, but I think there is a problem here, and I want to make it as clear as possible in terms of code.
In the windows  print_job.cpp, in the windows printPdf method:
1.  Line 92, applies the dm size is dmSize+dmExtra, but line 97, only the dmSize space is initialized, This results in random memory space data corresponding to dmExtra.
2. I think the memory space of dmEtra is either initialized to 0 or the corresponding value is read from the printer. Random memory leads to random problems when printing, such as random black background, or wrong concentration and speed parameters.
3. I am using a thermal printer for testing, usePrinterSettings=false. Hope you can understand some of what I am saying and hope to get your reply
