### ISSUE TITLE
Using custom font the cursive letters are rendered but I am unable to render the Chinese Text. I checked out both issue #111 and #76

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#119]
**I checked out both issue regarding the rendering problems of Chinese or Japanese letters [#111](https://github.com/DavBfr/dart_pdf/issues/111) and #76**. 

**The cursive letters are rendering** but using the same way to render the Chinese letters it's not rendering.  By taking the reference of issue no #111 and #76, It's not resolving my problem. So, Please let me know how to resolve this issue.

Future<Document> generateDocument(PdfPageFormat format) async {
  final Document pdf = Document(title: 'My Résumé', author: 'David PHAM-VAN');
  ByteData cursiveFont =
      await rootBundle.load("assets/fonts/cursive.ttf").catchError((error) {
    print(error);
  });
  ByteData chineseFont =
      await rootBundle.load("assets/fonts/chinese.ttf").catchError((error) {
    print(error);
  });

  pdf.addPage(MultiPage(
      pageFormat: PdfPageFormat.a4,
      build: (Context context) => <Widget>[
            Wrap(
              children: <Widget>[
                Container(
                    padding: const EdgeInsets.only(left: 30, bottom: 20),
                    child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Text("Flutter Demo",
                              textScaleFactor: 2,
                              style: TextStyle(font: Font.ttf(cursiveFont))),
                          Padding(padding: const EdgeInsets.only(top: 10)),
                          Text(
                            "教程",
                            style: TextStyle(
                              font: Font.ttf(chineseFont),
                            ),
                          ),
                        ])),
              ],
            ),
          ]));

  return pdf;
}

**Comment by DavBfr** [comment]
What font are you using? Does it contain those runes?
Do you have a link to download it?

**Comment by jazzbpn** [comment]
Download the font via [DOWNLOAD_LINK](https://fonts2u.com/download/gojuon.font)

**Comment by DavBfr** [comment]
This is not a real Chinese font, please try with
<https://github.com/ButTaiwan/genyo-font/raw/master/TW/GenYoMinTW-Heavy.ttf>

**Comment by jazzbpn** [comment]
Yeah using this font it works. **Which font do we have to use to render ARABIC and JAPANESE text?**

**Comment by DavBfr** [comment]
I don't know, ask native people what they use or look into another pdf document.
