### ISSUE TITLE
networkImage function doesn't support SVG image?

### ISSUE THREAD

**Issue by Lawati97** [DavBfr/dart_pdf#1191]
My case is that am getting URL from the backend and I view them, so what I am trying to do is that I get the URL and put it in the network image function and it returns an error that the decoder is null, hence I digged deeper and found out that there is no decoder for SVG?

**Comment by juandelgado** [comment]
I've just opened #1200 to add a quick example on how to display SVGs.  It's a 2 steps process:

- Get hold of the SVG data, which is basically an XML file. You can do this however way you want, from a HTTP request or a bundled asset.
- Then feed that XML to `SvgImage` which takes a parameter `svg` in its constructor.

It definitely could do with a higher level method, but at least it can be done.

Hope it helps.
