### ISSUE TITLE
Web app freezes during document.save()

### ISSUE THREAD

**Issue by gh-pap** [DavBfr/dart_pdf#1193]
**Describe the bug**

When calling await document.save() my web app freezes, even the circular progress indicator freezes. Once the call finishes then everything goes back to normal.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Uint8List savedPdf = await pdf.save();
```
Here's an [example](https://drive.google.com/file/d/1IezyvGYd2Kf6B8GRuBlbL2Wa4o0YrhWB/view?usp=share_link) of a file the app creates with the PDF library and which freezes the web app (for over 1 minute for a 10 page document) when .save() is called.

**Expected behavior**

I expect the app to not freeze and the circular progress indicator would indicate to the user that something is happening.

**Screenshots**

![image](https://user-images.githubusercontent.com/106000676/201507268-31648f8e-d866-4149-8357-29ab4361f6cb.png)

**Flutter Doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19044.2251], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)       
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.73.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dannndi** [comment]
any update ?

**Comment by gh-pap** [comment]
Glad someone else is interested in this. Users really think the (web) app is broken when this happens. @DavBfr is this a solvable problem or is it an underlying Flutter web issue? If solvable, is there anything I can do to help? Happy to buy you some coffees!

**Comment by gustav984** [comment]
maybe you need to check the format of the images
[here a similar question](https://github.com/DavBfr/dart_pdf/issues/1114)
