### ISSUE TITLE
Unable to build on windows

### ISSUE THREAD

**Issue by ATHUL3120** [DavBfr/dart_pdf#1195]
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)

Exception: Unable to generate build files

**Comment by Mr-Hsiao** [comment]
I'm having the same issue too

**Comment by edsonboldrini** [comment]
Me too! Does anybody find a solution?

**Comment by Mr-Hsiao** [comment]
> Launching lib\main.dart on Windows in debug mode... Building Windows application... CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message): Build step for pdfium failed: 1 Call Stack (most recent call first): flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
> 
> Exception: Unable to generate build files

The network is not connected to the git caused by
