### ISSUE TITLE
Can you change the bottom toolbars color ?  if so how? 

### ISSUE THREAD

**Issue by r2obd** [DavBfr/dart_pdf#1199]
**Is your feature request related to a problem? Please describe.**
The bottom toolbar is blue with white icons/text - i cant find a way to change this color.

**Describe the solution you'd like**
Be able to match my apps theme

**Describe alternatives you've considered**
taken a look at source code and couldn't find the answer

**Additional context**

**Comment by bksbora** [comment]
I guess you can change it in 'package:pdf/pdf.dart'; but i do not suggest it without a good understanding of packages.
