### ISSUE TITLE
Is there any way to use CachedNetworkImageProvider?

### ISSUE THREAD

**Issue by mirozahorak** [DavBfr/dart_pdf#1203]
Is there any way to speed up creation of pdf by loading cached images through CachedNetworkImageProvider from cached_network_image package?

The argument type 'CachedNetworkImageProvider' can't be assigned to the parameter type 'ImageProvider'

**Comment by bksbora** [comment]
I think you are trying to improve waiting time, to do that can you try .jpeg or .jpg format ?

**Comment by mehul425** [comment]
Hi @mirozahorak,
May be you can try this way
`  final imageProvider = await flutterImageProvider(
            const CachedNetworkImageProvider(
                "https://fastly.picsum.photos/id/1/200/300.jpg?hmac=jH5bDkLr6Tgy3oAg5khKCHeunZMHq0ehBZr6vGifPLY"));`
