### ISSUE TITLE
svg widget not rendering correctly

### ISSUE THREAD

**Issue by ranvirsahota** [DavBfr/dart_pdf#1207]
**Describe the bug**
Using PDF SVG widget has what is belived to be a rendering issue. There are certian spots on image that are not being displayed in the correct colour

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
          Container(
            width: 100,
            height: 50,
            child: SvgImage(svg: headerLogo),
          ),
```

**Expected behavior**
The screenshot is the intended result, the image is being displayed on chrome by searching the filepath:
![image](https://user-images.githubusercontent.com/18485561/205133537-b8b6fa7e-1ba8-48d7-9728-252efa9d2818.png)

**Screenshots**
This is what I get in my application when deployed locally on the web also to chrome:
![Screenshot_20221201_171312](https://user-images.githubusercontent.com/18485561/205134118-cb2f1525-1c25-483e-931b-fa6a4278ef38.png)

**Flutter Doctor**
```
[✓] Flutter (Channel master, 3.6.0-4.0.pre.1, on Manjaro Linux 5.15.78-1-MANJARO, locale en_GB.UTF-8)
    • Flutter version 3.6.0-4.0.pre.1 on channel master at /home/ranvir/.local/share/ProgrammingFrameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e54c8a8e27 (2 weeks ago), 2022-11-16 03:45:09 -0500
    • Engine revision 3e15c19256
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/ranvir/.local/share/ProgrammingFrameworks/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/ranvir/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.3
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/ranvir/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 5.15.78-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.71 unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: [PC]
 - OS: [5.15.78-1-MANJARO]
 - Browser [Google Chrome]
 - Version [108.0.5359.71]

**Additional context**

**Comment by DavBfr** [comment]
I need the SVG file to be able to see if something is wrong.

**Comment by ranvirsahota** [comment]
I have now fixed by replacing the class values with the acutal fill values.
From 
```
.st1{fill:url(#SVGID_1_);}
class="st1"
```
To e.g.:
```
fill="#2E93E6
```

I see if I can temp revert changes to get you file before and after as well

**Comment by ranvirsahota** [comment]
As the file names say "logo-not-working" is where the file changes were not made and "logo-working" is where they have been made as previous comment i made above explains. TY

![logo_not_working](https://user-images.githubusercontent.com/18485561/205155473-495a6871-fd5d-4b8f-af52-557b59b78189.svg)
![logo_working](https://user-images.githubusercontent.com/18485561/205155477-b43f1120-6dff-47f6-ace9-2d1df2c6081e.svg)

**Comment by DavBfr** [comment]
Yes, style and classes are not supported.
