### ISSUE TITLE
I am trying to load ttf file and use it inside the table 

### ISSUE THREAD

**Issue by Renkon117** [DavBfr/dart_pdf#121]
Hello, Sorry for questioning again and again. I looked into other issues if they have the same problem as mine. 

Thankfully, I was able to load ttf file and use it inside of Text widget and other, but except _Table widget_. Is there any way I can use unique characters in Table???

Please help

this one works!
`Text('コンビニ店　this is the name with unique character',
                          textScaleFactor: 1,
                          textAlign: TextAlign.left,
                          style: TextStyle(font: font))`

this one doesn't
`Table.fromTextArray(context: context, data: <List<String>>[
              <String>[
                'Date --the unique character is supposed to be here',
              ],---------------------------------------------------------`
I wanna use those same ttf font inside this widget

**Comment by DavBfr** [comment]
You can create a new Theme:

```dart
final Theme theme = Theme.base().copyWith(
      tableHeader: TextStyle(font: fontBold),
      tableCell: TextStyle(font: font),
);

pdf.addPage(Page(
      theme: theme,
      build: (Context context) => Table.fromTextArray(.....)))
```

**Comment by Renkon117** [comment]
It works!!!!! Thank you so much!!!! I really appreciate it.

**Comment by krtliv** [comment]
tried with theme but i get the same error 

> If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.

```
pdf.addPage(Page(
      pageFormat: PdfPageFormat.a4,
      theme: theme,
      build: (Context context) =>
          Table.fromTextArray(context: context, data: const <List<String>>[
            <String>['ビニ店', 'ビニ店', 'ビニ店'],
          ])));
```

**Comment by Renkon117** [comment]
`Future<dynamic> getFontData() async {
    final ByteData bytes =
        await rootBundle.load('assets/fonts/OpenSans-Regular.ttf');
    final Uint8List fontData = bytes.buffer.asUint8List();
    return Font.ttf(fontData.buffer.asByteData());
  }`

`var font = await getFontData()`

I tried so many ways to solve this problem. hope this work for you.

**Comment by krtliv** [comment]
thanks for the quick reply, i finally solved it by creating the table myself and adding text widgets inside tableRows. For anyone else having the same problem you can see my solution bellow.

if i find some time i will try what you mentioned @Renkon117 and see if it helps.

Thanks! 

```
build: (Context context) => Table(
              tableWidth: TableWidth.min,
              border:
                  TableBorder(top: true, left: true, right: true, bottom: true),
              children: <TableRow>[
                TableRow(children: <Widget>[
                  Text(SPECIAL_TEXT_HERE,
                      style: TextStyle(font: ttf)),
                  Text(SPECIAL_TEXT_HERE,
                      style: TextStyle(font: ttf))
                ]),
              ])));
```
