### ISSUE TITLE
Printer not found using this package. (Another package finds the printer)

### ISSUE THREAD

**Issue by san-stha** [DavBfr/dart_pdf#1212]
@DavBfr 
i tried this package to print images in a label printer. It kept on searching for printers. I also tried to add the printer through ip address, but the printer could not be found. If you could help me then i would be grateful for your help.

IMAGES:
![317231088_420849070136948_7781193917845566638_n](https://user-images.githubusercontent.com/110322326/206161620-0b9da0be-8f1c-47d2-98df-0b1d66b840ec.jpg)

![317870175_720124983142144_176031880489900956_n](https://user-images.githubusercontent.com/110322326/206161687-28fd3929-9db6-4816-b125-3c6d3ddb2514.jpg)

![318317486_655713606234242_4691963170756478676_n](https://user-images.githubusercontent.com/110322326/206161714-677733b8-4265-4dee-8f68-2bd7b462ca52.jpg)

![318230460_723961368714543_5718486259237685828_n](https://user-images.githubusercontent.com/110322326/206161750-bf02cabf-2a9e-400e-92fe-c4e25739d604.jpg)

**Comment by DavBfr** [comment]
Your printer vendor must provide a driver for Android to make it work.

**Comment by rahul260792** [comment]
@san-stha did you found any solution for this?
