### ISSUE TITLE
Tamil Font not supported

### ISSUE THREAD

**Issue by Desiaraj** [DavBfr/dart_pdf#1214]
Tamil Font not supported while print the final document. I have used lot of fonts. But it's not working fine

Font  -> noto_regular.ttf  ( I checked other font also)

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=LLBoRBAQIw0

**Comment by selvam920** [comment]
[multilanguage_sample.pdf](https://github.com/user-attachments/files/22624194/multilanguage_sample.pdf)

use below, it's working
https://github.com/selvam920/dart_pdf
