### ISSUE TITLE
line 365 pos 18: 'childSize <= maxChildExtent': is not true.

### ISSUE THREAD

**Issue by MuhammadNumanMallik** [DavBfr/dart_pdf#1217]
I'm facing this error please help

Error= line 365 pos 18: 'childSize <= maxChildExtent': is not true.

**Comment by igbenic** [comment]
> I'm facing this error please help
> 
> Error= line 365 pos 18: 'childSize <= maxChildExtent': is not true.

I hope you solved it, but for those, like me, that are just now getting this error; look at the code before the assertion failure, in Android studio the child object can be inspected for details on it and it's children for more info on which children are overflowing I guess.
