### ISSUE TITLE
The name 'Image' is defined in the libraries 'package:image/src/image.dart' and 'package:pdf/widgets.dart', Try using 'as prefix' for one of the import directives.

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#122]
The name 'Image' is defined in the libraries 'dart:ui', 'package:image/src/image.dart' and 'package:pdf/widgets.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

    return Container(
      width: size,
      height: size,
      decoration: new BoxDecoration(
        color: layoutbg,
      ),
      child: Image(image),
    );

**Comment by DavBfr** [comment]
use a namespace im your import:
```dart
import "package:image/src/image.dart" as im;
```

then prefix all image related objects with `im`.

**Comment by jazzbpn** [comment]
Unable to resolve the issue:

**How to use this in flutter to load local image without using async?** Reason we can't use async in build function. Using FutureBuilder it shows issue.

`Image image = decodeImage(File('test.webp').readAsBytesSync());
`

I am using this but unable to figure out the way to resolve the problem: 
```
var imageProvider = AssetImage('assets/test.jpg');
// how to convert imageProvider to Uint8List?

final image = PdfImage(
  pdf.document,
  image:???, /// Uint8List required
  width: img.width,
  height: img.height,
);
```

**Comment by DavBfr** [comment]
Use this:
```dart
PdfImage pdfImage = await pdfImageFromImageProvider(
      pdf: pdf.document,
      image: imageProvider,
);
```

**Comment by jazzbpn** [comment]
Yeah you had already mentioned this answer in another question. This time my question is, **How to create image in stateless widget of new child widget(without passing PdfImage as constructor)?**
