### ISSUE TITLE
Paragraph line break is not working as expected.

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#1220]
**UseCase:**
We are creating the letter generator service where user put their dynamic content. When user press enter to TextFormField it will break the line once, but when he tries to additional space using enter the space is not visible and line only break once.

**Expected Result:**
When user press enter twice. First enter will break the line and Second enter will give the additional empty line spacing. Thank you! (At least if we get two lines break would be helpful.)

**CODE:**

_**text =**_ 'I’m tendering my resignation now so that I can be as helpful as possible to you during the transition. I’ve truly enjoyed my time working with you and everyone else on our team at LMK. It’s rare to find a customer service role that offers as much opportunity to grow and learn and such a positive, I’ve recently decided to go\nyghgggghhhhhh back to \n\n\n\n\n\n\n\njkgghhhhhjschool, and my program starts in early September. I’m tendering my resignation now so that I can be as helpful as possible to you during the transition. I’ve truly enjoyed my time working with you and everyone else on our team at LMK. It’s rare to find a customer service role that offers as much opportunity to grow and learn and such a positive';

pw.Paragraph(
                text: **_text_** ?? '',
                textAlign: textAlign ?? pw.TextAlign.left,
                style: pw.TextStyle(
                  fontStyle: fontStyle ?? pw.FontStyle.normal,
                  // fontSize: fontSize ?? getFontSizeDesc(),
                  fontSize: getFontSizeDesc(),
                  lineSpacing: lineSpacing ?? 3,
                  fontWeight: fontWeight ?? pw.FontWeight.normal,
                  color: color ?? PdfColors.black,
                ),
              )
              
**OUTPUT**

              
![1671641934410](https://user-images.githubusercontent.com/11361035/208963399-f04f29b3-7fe6-4cf8-baf8-f582e2a9fc13.jpg)

**Comment by deepak-agendaboa** [comment]
See https://github.com/DavBfr/dart_pdf/issues/991

**Comment by jazzbpn** [comment]
Any updates
