### ISSUE TITLE
Using the commercial package for dart_pdf

### ISSUE THREAD

**Issue by abiselvaraj** [DavBfr/dart_pdf#1221]
Hello,

I came across your commercial package for dart_pdf because I require the functionality of loading and updating an existing pdf document. I followed the steps and made a payment through the PayPal link provided on the pdf_crypto documentation site.

Unfortunately, I am unsure of the next steps in order to obtain the license in order to use the paid functionality, as I keep going back to the payment page. Please help me understand how to get the perpetual license, or whom I should contact to proceed further.

**Comment by DavBfr** [comment]
You'll receive the details on your Paypal email account.
Thanks.

**Comment by abiselvaraj** [comment]
That is perfect. Thank you very much.

**Comment by ramsmart-inno** [comment]
Hi @DavBfr, 

I require dart_pdf Commercial Package access to edit existing pdf documents. Can you share the advantages of the Commercial Package? And how to make payment for that. 

Thank You.

**Comment by DavBfr** [comment]
@ramsmart-inno It's available here: https://pub.nfet.net/pdf_crypto/

**Comment by ramsmart-inno** [comment]
@DavBfr What actions can I do on the commercial page like edit the existing PDF page? Share elaborate notes on it. I little confused.

**Comment by DavBfr** [comment]
Yes you can load an existing PDF and add pages to it and add content on top of the existing pages. Like image or text. To do that, you load the document, use the editPage method passing it a widget to draw. And the usual save at the end.
