### ISSUE TITLE
Ability to locate the share sheet on iOS

### ISSUE THREAD

**Issue by agpdl** [DavBfr/dart_pdf#1224]
**Is your feature request related to a problem? Please describe.**
My app has a share option on the top right corner of the app bar, when we tap on the share option, we're using the method `Printing.sharePDF` and the share sheet on iOS is opened on the top left corner of the screen with an arrow pointing to the air. We would like to have the ability to locate the share sheet where it should be.

**Describe the solution you'd like**
Maybe a property to locate the share sheet on the screen (top left, top right, bottom left, bottom right, etc) I have seen other packages do it like[ this one.](https://pub.dev/packages/share_plus)

**Describe alternatives you've considered**
I don't have any. 

**Additional context**

![IMG_7DE9C00B14DC-1](https://user-images.githubusercontent.com/52173599/209975036-3ebea42c-390d-4957-8e20-30d8a60cd76b.jpeg)

**Comment by DavBfr** [comment]
`Printing.sharePdf()` takes a `bounds` `Rect` parameter to define where to put the iOS dialog arrow. You can use a RenderBox object to locate where your button is and it will automatically show the popup as expected.

Check this: https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/src/preview/actions.dart#L37
