### ISSUE TITLE
Image library dependency version is too outdated

### ISSUE THREAD

**Issue by royale1223** [DavBfr/dart_pdf#1228]
The pdf and printing package depends on an old version of image library - `image:3.0.1.` This library is now at `4.0.7` and has added many features.This dependency prevents us from using newer features in that library like pixel iteration.

**Comment by tp** [comment]
This was implemented in https://github.com/DavBfr/dart_pdf/commit/3a63614b4ae501a087eb51b4896919819fb3cf8f, just not yet release on `pub.dev`.

**Comment by DavBfr** [comment]
Fixed
