### ISSUE TITLE
How to display image from asset in Category widget without passing the image object as constructor?

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#123]
Hello dav, I am new to flutter. How to load image in new Category(example class) widget?

**1. How to display image(with color) in new Category widget without passing the image object as constructor? (Reason I want to separate all the smaller widget)?**

```
class Category extends StatelessWidget {
  Category({this.title});

  final String title;

  // how to use this in this class
  PdfImage pdfImage = await pdfImageFromImageProvider(
      pdf: pdf.document,
      image: fw.Image.asset(
        "assets/images/ic_skills.png",
        color: Colors.red, // How to set color?
      ).image);

  @override
  Widget build(Context context) {
    return Container(
        decoration: const BoxDecoration(color: lightGreen, borderRadius: 6),
        margin: const EdgeInsets.only(bottom: 10, top: 20),
        padding: const EdgeInsets.fromLTRB(10, 7, 10, 4),
        child: Text(title, textScaleFactor: 1.5)); // load image as child inlace of text without passing image object as constructor
  }
}
```

**Comment by DavBfr** [comment]
There is no way to do that as everything is synchronous. You have to pass the image to the constructor.

If you don't want to pass the image, it's possible to get the SVG version of this icon and extract the path string. You can then use the Shape widget to draw it.
This also allows you to change the color.

Take a look at the PdfLogo Widget as an example.

**Comment by jazzbpn** [comment]
Ok thank you. Is there any future schedule for that feature?

**Comment by DavBfr** [comment]
The Png image is transformed into an array of 32bits RGBA values. You should be able to do any filtering you need to it before passing it to the pdf.

The Svg is a way better solution as it's vector image it can scale to any size. You can specify the dimensions if you wrap it in a SizedBox widget

**Comment by jazzbpn** [comment]
From the flutter documentation I found, _The channels used by this image, indicating whether the alpha channel is used or not. All images have an implicit alpha channel due to the image data being stored in a Uint32, but some images, such as those decoded from a Jpeg, don't use the alpha channel. This allows image encoders that support both rgb and rgba formats, to know which one it should use._ Sorry, I do not know how to transformed Png image into an array of 32bits RGBA values. Please help!

**Comment by DavBfr** [comment]
```dart
await image.toByteData(format: ui.ImageByteFormat.rawRgba);
```
