### ISSUE TITLE
Change the language of the print option

### ISSUE THREAD

**Issue by SimonTellier** [DavBfr/dart_pdf#1233]
Hi, 

I'm trying to change the language used by the printer service in my iOS application (English to French) as shown in the pictures.
I tried to add Localization as below but it doesn't work

```
 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: const [
        GlobalCupertinoLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale("fr", "FR"), // OR Locale('ar', 'AE') OR Other RTL locales
      ],
      locale: const Locale("fr", "FR"),
      navigatorKey: locator<NavigationService>().navigatorKey,
      debugShowCheckedModeBanner: false,
      navigatorObservers: [NavigationHistoryObserver()],
      onGenerateRoute: _appRouter.onGenerateRoute,
    );
  }

```

Do you have a solution to my problem?

![IMG_3127](https://user-images.githubusercontent.com/51329066/212358385-2181a7aa-9f5f-41e5-baad-87c9de551bba.PNG)

![IMG_3128](https://user-images.githubusercontent.com/51329066/212358460-2bd23350-3a45-42cb-9698-f2ab6fc2ca3a.PNG)

**Comment by 2S-Software** [comment]
I have the same question. Is there a solution to use the language according to the current system?
