### ISSUE TITLE
The non-abstract class '_FlutterView' is missing implementations for these members: -FlutterView.viewId

### ISSUE THREAD

**Issue by alaincruz06** [DavBfr/dart_pdf#1235]
I'm using [pdf package](https://pub.dev/packages/pdf) and printing to generate/preview and save text to .pdf format. Everythings works fine when testing on my own laptop (flutter build works fine on web), but when I deploy to [vercel](https://vercel.com) the following error appears and prevents my project to deploy:
![Screenshot 2023-01-15 at 15-34-28 Deployment Overview – Dashboard – Vercel](https://user-images.githubusercontent.com/82970898/212567259-7474828d-b97a-4ba5-a6e1-b6bb640d2722.png)

Later I changed branch in my project and removed printing package in the next commit to see if that was the problem, and indeed it was, my project deployed and builded succesfully. I've tried to go under "the hood" of your package but couldn't find the error, any ideas, suggestions, improvements are welcome. Thanks for your package too.

PS: not including flutter doctor because everything's happening on vercel environment.

**Comment by Alijaaan** [comment]
same problem here, is there a temporary solution?

**Comment by DavBfr** [comment]
Should be fixed in the master branch

**Comment by Flaminiat** [comment]
I do get this error (among many others) in the master channel:
Launching lib/main.dart on Chrome in debug mode...
../../../.pub-cache/hosted/pub.dev/printing-5.9.3/lib/src/widget_wrapper.dart:231:7: Error: The non-abstract class '_FlutterView' is missing implementations for these members:
 - FlutterView.viewId
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _FlutterView extends ui.FlutterView {
      ^^^^^^^^^^^^
org-dartlang-sdk:///lib/ui/window.dart: Context: 'FlutterView.viewId' is defined here.
Waiting for connection from debug service on Chrome...             27.7s
Failed to compile application.

**Comment by Flaminiat** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.8.0-13.0.pre.23, on macOS 13.2.1 22D68 darwin-arm64, locale en-IT)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/flaminia/develop/flutter. Consider adding /Users/flaminia/develop/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
