### ISSUE TITLE
raspberry pi 4 error

### ISSUE THREAD

**Issue by AndroidDesigner** [DavBfr/dart_pdf#1236]
Hi.
I have a raspberry pi 4 (arm64) and used the below code to print a text directly to my usb printer:
```
List<Printer> printers = await Printing.listPrinters();                   
await Printing.directPrintPdf(
  format: const PdfPageFormat(50 * PdfPageFormat.mm, 30*PdfPageFormat.mm),
  dynamicLayout: false,
  printer: printers.first,
  onLayout: (PdfPageFormat format) => _generatePdf(format),
);
```

But I got the below error:
```
 Unhandled Exception: MissingPluginException(No implementation found for method listPrinters on channel net.nfet.printing)
```

what is the problem?

**Comment by DavBfr** [comment]
It should work with Flutter Linux. You'll have to specify that ARM64 arch in your `CmakeLists.txt`, that's all.
like: `set(PDFIUM_ARCH "arm64" CACHE STRING "Architecture of pdfium used")`

**Comment by AndroidDesigner** [comment]
Dear @DavBfr 
Thank you for your response.
I have 2 question. can you clarify me please?

1. what do I have to do exactly with the ``pdfium``? I think their documentation is not good.
I downloaded the ``pdfium-linux-arm.tgz`` and  ``pdfium-linux-arm64.tgz`` files (from their github page) to the my Linux system and raspberry pi respectively, and then set the path variable of ``PDFium_DIR`` to refer to that directory.
Is it enough?

2. I changed ``CmakeLists.txt`` file in the ``Linux`` directory of my project as you said. but running  ``flutter build bundle`` results in error (My Linux system arch is x64 not arm64).
Do I have to build my flutter project in the raspberry pi only (when I added the ``printing`` package and the ``Pdfium`` binary)? 

Thank you

**Comment by AndroidDesigner** [comment]
@DavBfr 
Thanks for reply.
Are you sure that ``listPrinters`` is implemented for an arm64 too?
I added ``set(PDFIUM_ARCH "arm64" CACHE STRING "Architecture of pdfium used")`` to my ``CmakeLists.txt`` file in the ``Linux`` directory and also I did everything is related to the ``Pdfium``, but I received the above error again:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method listPrinters on channel net.nfet.printing)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelPrinting.listPrinters (package:printing/src/method_channel.dart:207:9)
<asynchronous suspension>
#2      _SapcoBarcodeViewState._row.<anonymous closure>.<anonymous closure>
<asynchronous suspension>
```

**Comment by AndroidDesigner** [comment]
Also note that I'm using ``flutter-pi`` in the raspberry pi.
I did steps as the below :

1. Download `` pdfium-linux-arm64.tgz `` from the pdfium [link](https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F5554/pdfium-linux-arm64.tg)
2. add the above directory to the ``/etc/environments`` file and make it source.
``PDFium_DIR="/path-to-the-pdfium-linux-arm64" ``
3. Modify ``CMakeLists.txt`` in the Linux directory of the app and added the below to it:
``find_package(PDFium)``
4. flutter clean
5. flutter pub get
6. flutter build bundle
7. run the app by ``flutter-pi myProject``

But again I will receive the below error when I want to print something :
``
 Unhandled Exception: MissingPluginException(No implementation found for method listPrinters on channel net.nfet.printing)
``

**Comment by DavBfr** [comment]
Ok makes sense. The printing plugin is not compatible with flutter-pi. Only with the official flutter build system. The flutter-pi documentation reads:

> You can now **theoretically** run every flutter app you want using flutter-pi, including apps using packages & plugins, just that **you'd have to build the platform side of the plugins you'd like to use yourself**.

**Comment by AndroidDesigner** [comment]
Thank you for reply.
But I'm using multiple Linux packages that are working fine with the flutter-pi also.
I need to work with a usb-printer in my project. what is the solution?
