### ISSUE TITLE
Rupee symbol not getting printed in PDF

### ISSUE THREAD

**Issue by WasimMemon** [DavBfr/dart_pdf#1238]
**Describe the bug**
while printing rupee symbol ('₹') and even unicode '\u20B9' with this also it gives below error.

library
pdf: ^3.8.4
printing: ^5.9.3

Flutter version - 3.3.10

Getting error message "flutter: Unable to find a font to draw "₹" (U+20b9) try to provide a TextStyle.fontFallback"

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pw.Text('in \\u20B9'
    style: pw.TextStyle(
    fontSize: 15.0,
    color: PdfColors.black,
    fontWeight: pw.FontWeight.bold,
    fontFallback: [
          pw.Font.symbol(),
          pw.Font.timesBold()
    ]),
)
```

**Expected behavior**

**Screenshots**
<img width="185" alt="Screenshot 2023-01-23 at 11 19 34 PM" src="https://user-images.githubusercontent.com/6543095/214114754-9ebde319-681f-41a8-9562-80467edc05f4.png">

**Desktop (please complete the following information):**
 - [X] Mac
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Comment by hmamigo** [comment]
I have the same problem.

**Comment by WasimMemon** [comment]
> flutter: ################################# flutter: Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management flutter: Unable to find a font to draw "€" (U+20ac) try to provide a TextStyle.fontFallback flutter: Unable to find a font to draw "€" (U+20ac) try to provide a TextStyle.fontFallback
> 
> You can find your character not supported by fonts in console log... please see the mentioned link or use your fonts as a fontFallback like this:
> 
> first find a font which support your characters, (InstrumentSans fonts has support for € character, but it doesn't support u20B9), alternatively you can get help from [fonts support /u20B9](https://www.fileformat.info/info/unicode/char/20b9/fontsupport.htm)
> 
> After you find the right font then put it in your project assets the:
> 
> ```
> final fallbackFontByteData  = await rootBundle.load("assets/fonts/InstrumentSans-Medium.ttf");
> 
> pw.Text('in \\u20B9'
>     style: pw.TextStyle(
>     fontSize: 15.0,
>     color: PdfColors.black,
>     fontWeight: pw.FontWeight.bold,
>     fontFallback: [
>           pw.Font.ttf(fallbackFontByteData)
>     ]),
> )
> ```

In simple flutter Text widget with same font it loads symbol of rupees.  
But in pdf preview same font can't load that symbol.

**Comment by Shahriyar13** [comment]
> > flutter: ################################# flutter: Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management flutter: Unable to find a font to draw "€" (U+20ac) try to provide a TextStyle.fontFallback flutter: Unable to find a font to draw "€" (U+20ac) try to provide a TextStyle.fontFallback
> > You can find your character not supported by fonts in console log... please see the mentioned link or use your fonts as a fontFallback like this:
> > first find a font which support your characters, (InstrumentSans fonts has support for € character, but it doesn't support u20B9), alternatively you can get help from [fonts support /u20B9](https://www.fileformat.info/info/unicode/char/20b9/fontsupport.htm)
> > After you find the right font then put it in your project assets the:
> > ```
> > final fallbackFontByteData  = await rootBundle.load("assets/fonts/InstrumentSans-Medium.ttf");
> > 
> > pw.Text('in \\u20B9'
> >     style: pw.TextStyle(
> >     fontSize: 15.0,
> >     color: PdfColors.black,
> >     fontWeight: pw.FontWeight.bold,
> >     fontFallback: [
> >           pw.Font.ttf(fallbackFontByteData)
> >     ]),
> > )
> > ```
> 
> In simple flutter Text widget with same font it loads symbol of rupees. But in pdf preview same font can't load that symbol.

I thing it's because of pdf behaviour, when you use font in your system, your system automatically load the fonts, and if a characters not supported by that font it use another fonts (I thing, I am not sure), but for PDF, you have to submit your font in the pdf file, did you try it with the way I mentioned? Didn't work for you?

**Comment by DavBfr** [comment]
> I thing it's because of pdf behaviour, when you use font in your system, your system automatically load the fonts, and if a characters not supported by that font it use another fonts (I thing, I am not sure), but for PDF, you have to submit your font in the pdf file, did you try it with the way I mentioned? Didn't work for you?

@Shahriyar13 you're right!

**Comment by WasimMemon** [comment]
> > > flutter: ################################# flutter: Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management flutter: Unable to find a font to draw "€" (U+20ac) try to provide a TextStyle.fontFallback flutter: Unable to find a font to draw "€" (U+20ac) try to provide a TextStyle.fontFallback
> > > You can find your character not supported by fonts in console log... please see the mentioned link or use your fonts as a fontFallback like this:
> > > first find a font which support your characters, (InstrumentSans fonts has support for € character, but it doesn't support u20B9), alternatively you can get help from [fonts support /u20B9](https://www.fileformat.info/info/unicode/char/20b9/fontsupport.htm)
> > > After you find the right font then put it in your project assets the:
> > > ```
> > > final fallbackFontByteData  = await rootBundle.load("assets/fonts/InstrumentSans-Medium.ttf");
> > > 
> > > pw.Text('in \\u20B9'
> > >     style: pw.TextStyle(
> > >     fontSize: 15.0,
> > >     color: PdfColors.black,
> > >     fontWeight: pw.FontWeight.bold,
> > >     fontFallback: [
> > >           pw.Font.ttf(fallbackFontByteData)
> > >     ]),
> > > )
> > > ```
> > 
> > 
> > In simple flutter Text widget with same font it loads symbol of rupees. But in pdf preview same font can't load that symbol.
> 
> I thing it's because of pdf behaviour, when you use font in your system, your system automatically load the fonts, and if a characters not supported by that font it use another fonts (I thing, I am not sure), but for PDF, you have to submit your font in the pdf file, did you try it with the way I mentioned? Didn't work for you?

Thanks 👍 @Shahriyar13 
It worked with different font for symbol.

**Comment by ahmeedev** [comment]
i followed "fontFallback" approach but it did not work for me. I have even a problem with \n character. when I put strings with \n it replaces the new line character with a box-type character.

![image](https://github.com/DavBfr/dart_pdf/assets/75003816/e62e3dfd-d00e-4458-88ad-6e1fc08c835a)

**Comment by bksbora** [comment]
```dart
 String dovizSembolu = "₺";

  void dovizName() {
    if (_localModelForDevelop.cizimeTanimliGlobalDovizTuru == "USD") {
      dovizSembolu = "\$";
    } else if (_localModelForDevelop.cizimeTanimliGlobalDovizTuru == "EUR") {
      dovizSembolu = "€";
    } else {
      dovizSembolu = "₺";
    }
    
    -------------------------------------------
    
    pdf.addPage(
// Page Ayarları
      pw.MultiPage(
          maxPages: 100,
          theme: pw.ThemeData.withFont(
            base: font,
            bold: font,
            icons: await PdfGoogleFonts.materialIcons(), // this line
          ),
          pageFormat: format,
          orientation: pw.PageOrientation.portrait,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          build: (context) {
            return FinalPDF;
          }),
    );
    ```

**Comment by anmolthedeveloper** [comment]
I'm facing the same issue [Unable to find a font to draw "₹"]
