### ISSUE TITLE
printing bug

### ISSUE THREAD

**Issue by Ashish-Raturi** [DavBfr/dart_pdf#1240]
**Describe the bug**
Hi thank you for the plugin. I'm printing one page 2 times. Using the following code. 
1. When I print pdf it's asking for the location every time.
2. When I send it to the printer, it's not printing continuously.
 
Can you tell me how can I fix it?

```dart
OutlinedButton(
  child: const Text('Print'),
  onPressed: () async {
    final pdf = await _generatePdf(PdfPageFormat.a4, title);
    final printer = await Printing.pickPrinter(context: context);
    if (printer == null) return;
    for (var page = 0; page < 2; page++) {
      await Printing.directPrintPdf(
        printer: printer,
        onLayout: (_) => pdf,
      );
    }
  },
```

**Screenshots**
![image](https://user-images.githubusercontent.com/50191855/215027343-fa9c766e-5f4e-4167-8263-9fbed8af04e3.png)

https://user-images.githubusercontent.com/50191855/215027271-2838b1d4-b6e5-4db6-bb7c-f432c83ea435.mp4

0191855/215025890-85f4b8a1-8b6d-4b7c-bf13-15fb96bc7eae.png)

**Comment by bksbora** [comment]
page < 1 ??
