### ISSUE TITLE
Error: The superclass, 'ui.FlutterView', has no unnamed constructor that takes no arguments.

### ISSUE THREAD

**Issue by Aljnk** [DavBfr/dart_pdf#1241]
**Describe the bug**
/AppData/Local/Pub/Cache/hosted/pub.dev/printing-5.9.3/lib/src/widget_wrapper.dart:232:3:
Error: The superclass, 'ui.FlutterView', has no unnamed constructor that takes no arguments.
  _FlutterView({required this.configuration});

**To Reproduce**
When I run my app in android studio after "flutter clean"
Flutter 3.7.0. (yesterday version)

**Comment by DavBfr** [comment]
Yes it's fixed in the master branch

**Comment by Aljnk** [comment]
The current Flutter SDK version is 3.7.0-29.0.pre.1.

Because app depends on printing >=5.10.0 which requires Flutter SDK version >=3.7.0, version solving failed.

**Comment by Aljnk** [comment]
D:\flutter\bin\flutter.bat --no-color upgrade
Flutter is already up to date on channel master
Flutter 3.7.0-29.0.pre.1 • channel master • https://github.com/flutter/flutter.git
Framework • revision 27f8ebdaed (8 hours ago) • 2023-01-26 22:16:17 -0500
Engine • revision ade610ec88
Tools • Dart 3.0.0 (build 3.0.0-171.0.dev) • DevTools 2.20.1

**Comment by Aljnk** [comment]
Sorry, switch back to
flutter channel stable
Work :) Thanks

**Comment by mxkdev** [comment]
> The current Flutter SDK version is 3.7.0-29.0.pre.1.
> 
> Because app depends on printing >=5.10.0 which requires Flutter SDK version >=3.7.0, version solving failed.

Is there any way that we could still use the master channel of flutter with Dart 3.0.0. and Printing 5.10.0?

**Comment by DavBfr** [comment]
> Is there any way that we could still use the master channel of flutter with Dart 3.0.0. and Printing 5.10.0?

Not really: the static analysis would return some errors.
