### ISSUE TITLE
textAlign property in Text Widget does not exist

### ISSUE THREAD

**Issue by carpentierchloe** [DavBfr/dart_pdf#1243]
I need to center my text in a Container. I am already using pw.Container(alignment: pw.Alignment.center), the text is centered in my Container, but the text himself is still aligned on the left. TextAlign property doest not exist for the pw.Text widget, which other solution are there ? Thanks a lot.

**Comment by zam101** [comment]
It exists you can see it's definition in this [File](https://github.com/DavBfr/dart_pdf/blob/be71711e442fa014aa59e1534c438c46b13cfdd9/pdf/lib/src/widgets/text.dart)   and it works fine for me
Example 
`
pw.Text("test",textAlign:pw.TextAlign.center")
`
