### ISSUE TITLE
A larger-than-a-page widget inside Flex is broken (Out of Memory)

### ISSUE THREAD

**Issue by jochemc** [DavBfr/dart_pdf#1246]
If there is a widget inside a Flex that is larger than a single page (but definitely not close to 20 pages), the app anyway throws the 'more than 20 pages' exception in debug mode, and even crashes Out of Memory in release mode. A minimal example at the end.

Ideally, I'd say multi-page spanning should work recursively so that a Text in a Column also gets broken up. I don't see that work easily given the current architecture, but at least I'd expect a (relevant) error instead of eating up all memory.

The cause seems to be that there is no mechanism to detect this: MultiPage invites the Column widget to output as many of its children as it can fit, which is 0 in this case, after which MultiPage creates a new page. This repeats until the assert kicks in (debug) or all memory is gone (release).

Edit: this is seen in the latest version of pdf (3.9.0 at the time) and flutter itself (3.7.0 at the time).

<pre>
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

pw.Document().addPage(
  pw.MultiPage(
    build: (context) => [
      pw.Column(
        children: [
          pw.Text(
            List.filled(400, "Some words.").join(),
            overflow: pw.TextOverflow.span,
          )
        ],
      )
    ],
  ),
);
</pre>

**Comment by jochemc** [comment]
I assume this is not fixed and thus still relevant!

**Comment by jochemc** [comment]
I'm not sure if I agree with this approach, I put effort into reporting a bug, which others seem to run into as well, but I provide a minimal sample and an analysis. The issue is acknowledged and then a bot closes it as completed.

I fully understand if there is no time to fix it, this is a free product after all, so no hard feelings there at all. But I think we fool ourselves if we let a bot close it as completed just because it hasn't been dealt with.

**Comment by szuwest** [comment]
This is a big problem. Nobody to solve this?
@jochemc Have you solved it by yourself?

**Comment by jochemc** [comment]
> This is a big problem. Nobody to solve this? [@jochemc](https://github.com/jochemc) Have you solved it by yourself?

Sort of. How I did it goes against all my programming principles, but I just had to get something working. I copied Column to MyColumn and did some fixes in there and used that throughout my application. I don't think this covers everything but it worked for us.
