### ISSUE TITLE
No widget is available to add html content as widget in pdf

### ISSUE THREAD

**Issue by VenkataRaoRayala** [DavBfr/dart_pdf#1251]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Duplicates #257
