### ISSUE TITLE
drawing signature point with canvas is flipping out signature.

### ISSUE THREAD

**Issue by VenkataRaoRayala** [DavBfr/dart_pdf#1252]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart

take signature points as below as example:
var signatureValue = "251.111 116.426,254.074 113.463,269.630 97.907,285.926 84.574,309.630 69.018,330.370 57.907,345.926 52.722,356.296 50.500,365.926 49.759,370.370 48.278,374.815 48.278,377.778 48.278,379.259 48.278,380.000 48.278,381.482 48.278,382.222 49.018,382.963 49.759,383.704 51.241,385.185 53.463,385.926 63.833,385.926 74.204,385.926 84.574,385.926 93.463,385.185 98.648,382.963 105.315,380.741 109.759,379.259 112.722,378.518 114.204,377.778 116.426,377.037 117.167,376.296 117.907,375.556 118.648,374.815 119.389,374.074 119.389,373.333 120.130,373.333 120.870,372.593 120.870";
var spList= signatureValue.split(',');

---> widget in pdf
        pw.Container(
          width: 800 * 0.25,
          height: 305 * 0.25,
          child: pw.CustomPaint(painter: (canvas, size) {
List<Offset> pointsScaled=[];
            canvas.reset();
          for (String sp in spList) {
      var dx = double.parse(sp.split(' ').first);
      var dy = double.parse(sp.split(' ').last);
      pointsScaled.add(Offset(dx, dy));
    }
            pointsScaled = points.map((e) => e * 0.25).toList();

            for (int i = pointsScaled.length - 2; i > 0; i--) {
              if (pointsScaled[i].dx >= 0 && pointsScaled[i - 1].dx >= 0) {
                canvas.drawLine(pointsScaled[i - 1].dx, pointsScaled[i - 1].dy,
                    pointsScaled[i].dx, pointsScaled[i].dy);
              }
            }
          }),
        ),
```

**Expected behavior**
canvas drawing should not flip out

**Screenshots**

**Flutter Doctor**
Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.22000.1455], locale en-US)
    • Flutter version 3.3.7 on channel stable at C:\Users\rayala.venkatrao\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (3 months ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

 Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\rayala.venkatrao\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

 Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32804.467
    • Windows 10 SDK version 10.0.19041.0
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

VS Code, 64-bit edition (version 1.74.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.58.0

Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1455]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.70

 HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
The coordinates are not flipped.
The coordinate system on a PDF file is different: 0,0 is at the bottom left and increments to the top right corner.
If you want to flip everything vertically, use a transformation matrix.
