### ISSUE TITLE
WebView deprecated in macOS error

### ISSUE THREAD

**Issue by dkakkuk** [DavBfr/dart_pdf#1253]
flutter .pub-cache/hosted/pub.dev/printing-5.10.1/macos/Classes/PrintJob.swift:233:23: warning: 'WebView' was deprecated in macOS 10.14: No longer supported; please adopt WKWebView.
        let webView = WebView()
                      ^

**Comment by Ashish-Raturi** [comment]
hi, got any solution for this bug

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=LLBoRBAQIw0
