### ISSUE TITLE
Thermal printer availability

### ISSUE THREAD

**Issue by Farrukh1198** [DavBfr/dart_pdf#1254]
Is it possible to use this package with 80mm thermal printers as Xprinter via USB?

**Comment by Mindstormsnxt** [comment]
I've successfully used this package with an 80mm XPrinter, just generate the pdf's size accordingly

**Comment by Farrukh1198** [comment]
> I've successfully used this package with an 80mm XPrinter, just generate the pdf's size accordingly

Thank you for your reply!

**Comment by NiranjanShah** [comment]
> I've successfully used this package with an 80mm XPrinter, just generate the pdf's size accordingly

can you please place the code over here to print on thermal printer
