### ISSUE TITLE
Natively merge a list of pdf documents 

### ISSUE THREAD

**Issue by lemohammed** [DavBfr/dart_pdf#1255]
## Is your feature request related to a problem? Please describe. 
Currently, there is not way to merge two pdf documents 

## Describe the solution you'd like
Given a list of documents, It would be nice to have a way to merge them:
```dart

FutureOr<Document> mergeDocuments(List<Document> documents) { ... }

```
## Describe alternatives you've considered
Printing.raster, converting each document page to an image (slow). Using a web based API ( too slow and requires an internet connection )
**Additional context**
N/A

**Comment by georgerappel** [comment]
Also quite interested.

Funny how it seems so simple to open one PDF as one/multiple pages using a PDF builder. Been looking at the classes and methods trying to find a way without addind a new dependency.

**Comment by DavBfr** [comment]
@georgerappel No it won't. But the premium version can't merge PDFs either.

**Comment by vicajilau** [comment]
Any news about this topic? 👀
