### ISSUE TITLE
Pdf Multipage issue

### ISSUE THREAD

**Issue by aliaafreen** [DavBfr/dart_pdf#1265]
My pdf will have multiple page the content will not be fitted on single page so I have used Multipage but it gives me error -
Exception: Widget won't fit into the page as its height (622.625) exceed a page height
(575.275590551181). You probably need a SpanningWidget or use a single page layout

Is there any solution for it?

flutter -3.3.9
pdf-3.8.4

I am working on flutter desktop windows.

**Comment by bksbora** [comment]
Please share code 🔢

**Comment by yurikong** [comment]
break the Widget into smaller SpanningWidgets

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=LLBoRBAQIw0

**Comment by tulioccalazans** [comment]
@DavBfr Is there any way for us to know when a widget crosses the page boundaries?

I have a Text inside a Container with background color.
The text size is varied and this is causing problems in PDF generation, especially when there is very large text or line breaks.

What do you suggest in this case?

**Comment by bksbora** [comment]
> @DavBfr Is there any way for us to know when a widget crosses the page boundaries?
> 
> I have a Text inside a Container with background color. The text size is varied and this is causing problems in PDF generation, especially when there is very large text or line breaks.
> 
> What do you suggest in this case?

Take the array , split into a list , put it into a builder.
