### ISSUE TITLE
[Bug][package:pdf][3.9.0] Arabic font rendering broke after 3.9.0

### ISSUE THREAD

**Issue by ahmednfwela** [DavBfr/dart_pdf#1267]
**Describe the bug**
3.8.4:
![image](https://user-images.githubusercontent.com/63286031/218353636-2cdbfcb3-dc34-485c-8d6f-c4ff75df5d26.png)

3.9.0:
![image](https://user-images.githubusercontent.com/63286031/218353596-f37f139f-182a-451c-8e2a-5f9adfbcb2bf.png)

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
final myTheme = pw.ThemeData.withFont(
  base: pw.Font.ttf(
    await rootBundle.load(
      "assets/fonts/cairo/Cairo-Regular.ttf",
    ),
  ),
  bold: pw.Font.ttf(
    await rootBundle.load(
      "assets/fonts/cairo/Cairo-Bold.ttf",
    ),
  ),  
);
final res = pw.Document(
  theme: myTheme,
);
res.addPage(
  pw.MultiPage(
    margin: const pw.EdgeInsets.all(16),
    pageFormat: PdfPageFormat.a4,
    theme: myTheme,
    textDirection: pw.TextDirection.rtl,
    crossAxisAlignment: pw.CrossAxisAlignment.stretch,
    build: (context) => [    
      pw.Table(
        border: pw.TableBorder.all(),
        children: [
          pw.TableRow(
            verticalAlignment: pw.TableCellVerticalAlignment.middle,
            children: [
              pw.Text(
                'طريقة الدفع\nPayment Method',
                textAlign: pw.TextAlign.center,
              ),
              pw.Text(
                'مرجع بوابة الدفع\nPayment Ref. No',
                textAlign: pw.TextAlign.center,
              ),
              pw.Text(
                'المدفوع\nPaid amount',
                textAlign: pw.TextAlign.center,
              ),
            ].reversed.toList(),
          ),
        ],
      ),
    ],
  ),
);
```

**Comment by Baghdady92** [comment]
i face same issue with last version 
i hope we can get fix soon

**Comment by salahturkmen** [comment]
i face same issue with last version
i hope we can get fix soon

**Comment by DavBfr** [comment]
This might be an issue with the dart_bidi package.

**Comment by Baghdady92** [comment]
i disabled dart_bidi package and revert the change to arabic.dart file 
everything now working

**Comment by salahturkmen** [comment]
> i disabled dart_bidi package and revert the change to arabic.dart file everything now working
more details by code

**Comment by ahmednfwela** [comment]
any news on this ? @DavBfr

**Comment by Baghdady92** [comment]
> any news on this ? @DavBfr

use fix version 
still not merged yet 
  printing: 
    git: 
      url: https://github.com/Baghdady92/dart_pdf.git
      path: printing
  pdf: 
    git: 
      url: https://github.com/Baghdady92/dart_pdf.git
      path: pdf

**Comment by hosamyousof** [comment]
I face the same issue with the latest version. @DavBfr any workarounds to fix this?

**Comment by Baghdady92** [comment]
> I face the same issue with the latest version. @DavBfr any workarounds to fix this?

use mine for now @hosamyousof

**Comment by Baghdady92** [comment]
> @Baghdady92 Thanks for your help but there is a conflict:
> 
> Can you please check
> 
> ```
> [OXO.Flutter.POS] flutter pub get
> Resolving dependencies...
> Because oxo_pos depends on printing from git which depends on pdf ^3.10.0, pdf from hosted is required.
> So, because oxo_pos depends on pdf from git, version solving failed.
> exit code 1
> ```
> 
> ![image](https://user-images.githubusercontent.com/16549201/240906871-9f1062eb-314b-43ec-86f9-fb72dca00d55.png)

add these 
dependency_overrides: 
  intl: 0.18.1
  pdf: 
    git: 
      url: https://github.com/Baghdady92/dart_pdf.git
      path: pdf

**Comment by Baghdady92** [comment]
```
dependency_overrides: 
  intl: 0.18.1
  pdf: 
    git: 
      url: https://github.com/Baghdady92/dart_pdf.git
      path: pdf
```
