### ISSUE TITLE
Chart Bar Graph Single Value Broken

### ISSUE THREAD

**Issue by CarterVE** [DavBfr/dart_pdf#1269]
**Describe the bug**
I cannot generate a bar graph with a single value. I know this isn't a super common use case, but I am generating a series of graphs for a report, and there are times where I would need a single bar on the chart. When I create a chart with one value nothing appears, and the label is all the way to the left, even when the margins are set to something like 50.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  Widget chart() {
    List<BarDataSet> barData = [];
    for (int i = 1; i < subLen; i++) {
      double offset = subLen > 2 ? (-40 + ((i - 1) * 20)) : 0;
      barData.add(BarDataSet(
        color: PdfColor.fromHex(pdfColors[i - 1]),
        legend: legend[i - 1],
        width: width,
        offset: offset,
        data: List<PointChartValue>.generate(
          chartData.length,
          (idx) {
            final v = chartData[idx][i] as num;
            return PointChartValue(idx.toDouble(), v.toDouble());
          },
        ),
      ));
    }

    return Chart(
        overlay: ChartLegend(
            direction: Axis.horizontal,
            position: const Alignment(0, -1.1),
            decoration: BoxDecoration(
                border: Border.all(color: PdfColors.black, width: 0.5))),
        grid: CartesianGrid(
            xAxis: FixedAxis.fromStrings(
                List<String>.generate(
                    chartData.length, (index) => chartData[index][0] as String),
                marginStart: margin,
                marginEnd: margin,
                angle: 45,
                ticks: true),
            yAxis: FixedAxis([0, 25, 50, 75, 100],
                format: (v) => '$v%', divisions: true)),
        datasets: barData);
```

**Expected behavior**
A chart will be generated, even with a single value

**Screenshots**

<img width="1675" alt="Screenshot 2023-02-16 at 4 12 44 PM" src="https://user-images.githubusercontent.com/18474523/219488090-75a97a01-da3b-43a3-9a6b-bbd03026c60e.png">
<img width="1639" alt="Screenshot 2023-02-16 at 4 11 43 PM" src="https://user-images.githubusercontent.com/18474523/219488091-f48afa28-483c-43b8-b8d6-b3d44cbc9dab.png">

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [X] iOS
 - [X] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by herna** [comment]
Hi,

I have this same issue and I have to test whether there's one single value in order to not print the bar graph at all, otherwise an exception is thrown.

In order to reproduce, just take the example at https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/report.dart

Now just modify the `dataTable` variable like this in order to have one single record:

```dart
const dataTable = [
    ['Phone', 80, 95],
    //['Internet', 250, 230],
    // ['Electricity', 300, 375],
    // ['Movies', 85, 80],
    // ['Food', 300, 350],
    // ['Fuel', 650, 550],
    // ['Insurance', 250, 310],
  ];
```

This is the stack trace you get:

> ════════ Exception caught by printing ══════════════════════════════════════════
> The following assertion was thrown while generating a PDF:
> 'package:pdf/src/pdf/format/num.dart': Failed assertion: line 32 pos 12: '!value.isNaN': is not true.
> 
> When the exception was thrown, this was the stack:
> #2      PdfNum.output (package:pdf/src/pdf/format/num.dart:32:12)
> num.dart:32
> #3      PdfNumList.output (package:pdf/src/pdf/format/num.dart:81:25)
> num.dart:81
> #4      PdfGraphics.drawRect (package:pdf/src/pdf/graphics.dart:413:30)
> graphics.dart:413
> #5      BarDataSet._drawSurface (package:pdf/src/widgets/chart/bar_chart.dart:80:24)
> bar_chart.dart:80
> #6      BarDataSet.paint (package:pdf/src/widgets/chart/bar_chart.dart:111:9)
> bar_chart.dart:111
> #7      CartesianGrid.paint (package:pdf/src/widgets/chart/grid_cartesian.dart:114:15)
> grid_cartesian.dart:114
> #8      Stack.paint (package:pdf/src/widgets/stack.dart:236:13)
> stack.dart:236
> #9      SingleChildWidget.paintChild (package:pdf/src/widgets/widget.dart:318:14)
> widget.dart:318
> #10     Flexible.paint (package:pdf/src/widgets/flex.dart:566:5)
> flex.dart:566
> #11     Flex.paint (package:pdf/src/widgets/flex.dart:493:13)
> flex.dart:493
> #12     SingleChildWidget.paintChild (package:pdf/src/widgets/widget.dart:318:14)
> widget.dart:318
> #13     Flexible.paint (package:pdf/src/widgets/flex.dart:566:5)
> flex.dart:566
> #14     Flex.paint (package:pdf/src/widgets/flex.dart:493:13)
> flex.dart:493
> #15     Chart.paint (package:pdf/src/widgets/chart/chart.dart:130:12)
> chart.dart:130
> #16     SingleChildWidget.paintChild (package:pdf/src/widgets/widget.dart:318:14)
> widget.dart:318
> #17     Flexible.paint (package:pdf/src/widgets/flex.dart:566:5)
> flex.dart:566
> #18     Flex.paint (package:pdf/src/widgets/flex.dart:493:13)
> flex.dart:493
> #19     Page.paint (package:pdf/src/widgets/page.dart:232:13)
> page.dart:232
> #20     Page.postProcess (package:pdf/src/widgets/page.dart:176:5)
> page.dart:176
> #21     Document.save (package:pdf/src/widgets/document.dart:130:14)
> document.dart:130
> #22     generateReport (package:printing_demo/examples/report.dart:304:19)
> report.dart:304
> <asynchronous suspension>
> #23     PdfPreviewRaster._raster (package:printing/src/preview/raster.dart:125:13)
> raster.dart:125
> <asynchronous suspension>
> (elided 2 frames from class _AssertionError)
>
