### ISSUE TITLE
how to display pngbytes its not working, image.memory not available

### ISSUE THREAD

**Issue by pgmoorthy1411** [DavBfr/dart_pdf#1274]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=LLBoRBAQIw0

**Comment by bksbora** [comment]
You haven't mentioned or explained anything solid without any effort and expecting us to answer you with a magic solution ?
