### ISSUE TITLE
Need to draw Y axis downwards

### ISSUE THREAD

**Issue by Evaldas256** [DavBfr/dart_pdf#1276]
Dear Sirs,
I can create Linear graph from my data, but I need to display Y axis downwards but with positive values.
![image](https://user-images.githubusercontent.com/94120605/221181839-1ed948f2-54b3-4a44-9309-bbc5008baa5e.png)
Is it possible with this package?

**Comment by DavBfr** [comment]
It can't do that, but feel free to implement it and contribute.
