### ISSUE TITLE
Directionality not Implemented Correctly

### ISSUE THREAD

**Issue by Ayad-Ben-Saliem** [DavBfr/dart_pdf#1279]
`pdf` is an awesome package, but I faced some issues with `Directionality`.

When setting `textDirection` to `rtl` for an entire page, I expect that the page will flip horizontally, but it didn't.
`pdf` just sets the alignment to the `Text`, where **Alignmentation** is part of **Direction**.

I think the confusion starts from the name of `TextDirection`, It should be just `Direction` not `TextDirection`, where text direction should follow the character direction itself, not the UI direction, where every character belongs to language, and every language has an own direction.

Eg:
The word **Name** will not be written as **emaN** if we change the direction to Right-to-Left (`rtl`).
So far, the word **اسم** should not be written **مسا** if the text direction is Left-to-Right (`ltr`).

This is an explanation code for how I generate the document.
```dart
final doc = Document();

final page = Page(
  theme: ThemeData.with font(base: font),
  textDirection: TextDirection.ltr,
  // textDirection: TextDirection.rtl,
  pageFormat: PdfPageFormat.roll80,
  margin: EdgeInsets.all(4),
  build: (Context context) {
    return _buildDocument();
  },
);

doc.addPage(page);

return PdfPreview(build: (format) => doc.save());

```

These screenshots for both `ltr` and `rtl` respectively.

- ### **Left-to-Right Direction:**
> <img src="https://user-images.githubusercontent.com/11043231/222176475-7e3b0013-3310-49ba-b347-4a171eb9df7c.png" width=40%>
> 

- ### **Right-to-Left Direction:**
> <img src="https://user-images.githubusercontent.com/11043231/222176898-9d7c7f72-a89a-4d86-8e8b-b485918dd00a.png" width=40%>
> 

Looking at the first screenshot, we note that the Arabic word **خبزة** is flipped horizontally **ة ز ب خ**, which is not readable. that's because the Arabic language is written in `rtl` mode.
Also by looking at the second image, where the text direction is `rtl`, why the word **Name** doesn't flip to **emaN**? that's because the English characters are always written in `ltr` mode.

Also, `pdf` package doesn't implement the `textDirection` property to all components as Flutter did.
**Eg:**
`pdf` components `Column`, `Row`, and `Flex` doesn't implement `textDirection` where these components in Flutter did.

### **Conclusion**

> It's clear that the directionality is not implemented correctly `pdf` package.
> To solve this issue should work in two branches.
> - **First:**
>   The direction of text should follow the character's direction, not the UI direction.
> - **Second:**
>   The `textDirection` property (UI direction) should be implemented and inherited for all components and set the alignment of components based on this direction.
> 
> _**Note:**_
>   Some components should be directionless, like some `Icons` as example
> 

**Flutter Doctor**

```
[✓] Flutter (Channel stable, 3.7.4, on Ubuntu 22.04.2 LTS 5.19.0-32-generic, locale en_US.UTF-8)
    • Flutter version 3.7.4 on channel stable at /home/ayad/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b4bce91dd0 (9 days ago), 2023-02-21 09:50:50 +0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/ayad/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.2 LTS 5.19.0-32-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

_Tested on Flutter Desktop (**Linux**).
Ubuntu 22.04.2 LTS_

**Comment by Ayad-Ben-Saliem** [comment]
I noted that `textDirection` is not implemented in most of `pdf` components except text-related components like `Text`, RichText, and TextSpan.
That gives me an impression that the `pdf` developers understand `textDirection` is used for texts only, where it should be used for UI direction.

**Eg:**
`Column`, `Row`, `Flex`, `TableRow`, and `Wrap` should consider `textDirection` to build their children from Left to Right or from Right to Left.

I hope this feature implements soon.

**Comment by DavBfr** [comment]
@Ayad-Ben-Saliem I kind of know how that works. I just did not implement it because it was not my priority: I'll probably never use it.

If you want that feature, a PR is welcome to add it to the right Widgets.
