### ISSUE TITLE
Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#128]
**Hello dav, when I tried to create the inner TableView in the multipage, it's showing the error like this. I have paste the code below. Please have a look. Thank you!!**

E/flutter (14427): #0      MultiPage.generate.<anonymous closure> 
package:pdf/widgets/multi_page.dart:134
E/flutter (14427): #1      MultiPage.generate 
package:pdf/widgets/multi_page.dart:138
E/flutter (14427): #2      Document.addPage 
package:pdf/widgets/document.dart:61
E/flutter (14427): #3      generateDocument 
package:flutter_cv_builder/…/pdf_utils/template_2.dart:77
E/flutter (14427): <asynchronous suspension>
E/flutter (14427): #4      _ResumeSectionState._saveAsFile 
package:flutter_cv_builder/…/resume_section/ResumeSections.dart:44
E/flutter (14427): <asynchronous suspension>
E/flutter (14427): #5      _ResumeSectionState.makeFab.<anonymous closure> 
package:flutter_cv_builder/…/resume_section/ResumeSections.dart:230
E/flutter (14427): #6      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:635
E/flutter (14427): #7      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:711
E/flutter (14427): #8      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (14427): #9      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
E/flutter (14427): #10     TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:312
E/flutter (14427): #11     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter (14427): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter (14427): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (14427): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (14427): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (14427): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (14427): #17     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (14427): #18     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (14427): #19     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (14427): #20     _invoke1  (dart:ui/hooks.dart:250:10)
E/flutter (14427): #21     _dispatchPointerDataPacket  (dart:ui/hooks.dart:159:5)
E/flutter (14427):

```
    MultiPage(
      pageFormat: PdfPageFormat.a4,
      build: (Context context) => <Widget>[
Table(children: [
          TableRow(children: [
            Expanded(
              flex: 3,
              child:
                  Container(Text("child view")),
            ),
            Expanded(
              flex: 8,
              child: Table(children: [
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
                TableRow(children: [Text("Tutorial")]),
              ]),
            ),
          ]),
        ]),
]);
```

**Comment by DavBfr** [comment]
This is because your inner table will generate a layout higher than the A4 page format. And as it's a inner widget, it can't create a new page to split the table.

**Comment by jazzbpn** [comment]
Please tell me the ideas to create the layout in such type of use cases? How to resolve this type of use cases.

**Comment by DavBfr** [comment]
I don't know what layout you want to build. Maybe `Wrap` can work for you, it can span across pages.

**Comment by jazzbpn** [comment]
Hello dave, I tried using Wrap but it doesn't work. 

**Use-Case: I want to build the inner table inside the TableRow which height might be greater than A4 page.**

Note: In the native platform when I tried to create the same thing using **iTextPdf or PSPfdKit library** it works, but in Flutter it is showing the issue like: _This widget created more than 20 pages. This may be an issue in the widget or the document_. 

So, Is there any idea to create a view like the above use-cases? if not do you have any plan to built such type of features in the near future?

**Comment by DavBfr** [comment]
In this case, you can use the HtmlConverter:

await Printing.layoutPdf(onLayout: (PdfPageFormat format) async {
      return await Printing.convertHtml(format: format, html: '<html><body><table> ... ');
});

**Comment by jazzbpn** [comment]
How to save as a file and render a PDF file like as:

```
  Future<void> _saveAsFile() async {
    final Directory appDocDir = await getApplicationDocumentsDirectory();
    final String appDocPath = appDocDir.path;
    final File file = File(appDocPath + '/' + 'document.pdf');
    print('Save as file ${file.path} ...');
    await file.writeAsBytes((await generateDocument(PdfPageFormat.a4)).save());
    Navigator.push<dynamic>(
      context,
      MaterialPageRoute<dynamic>(
          builder: (BuildContext context) => PdfViewer(file: file)),
    );
  }
```

**Comment by DavBfr** [comment]
This returns a pdf data, you just have to save as a file
```dart
await Printing.convertHtml(format: format, html: '<html><body><table> ... ')
```

I have no plan to support complex nested tables

**Comment by jazzbpn** [comment]
Ok thank you.
