### ISSUE TITLE
I am getting this error on running pdf package in my flutter project.

### ISSUE THREAD

**Issue by Moammar1498** [DavBfr/dart_pdf#1286]
**Describe the bug**
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/random/auto_seed_block_ctr_random.dart:26:8: Error: Type 'BlockCtrRandom' not found.
  late BlockCtrRandom _delegate;
       ^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/stream/ctr.dart:10:31: Error: Type 'SICStreamCipher' not found.
class CTRStreamCipher extends SICStreamCipher {
                              ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:64:14: Error: Type 'ExpressionGroup' not found.
  final List<ExpressionGroup<T>> _groups = [];
             ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:65:9: Error: Type 'SettableParser' not found.
  final SettableParser<T> _loopback = undefined();
        ^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:68:3: Error: Type 'ExpressionGroup' not found.
  ExpressionGroup<T> group() {
  ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/asymmetric/oaep.dart:89:16: Error: The getter 'Platform' isn't defined for the class 'OAEPEncoding'.
 - 'OAEPEncoding' is from 'package:pointycastle/asymmetric/oaep.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/asymmetric/oaep.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    var seed = Platform.instance.platformEntropySource().getBytes(32);
               ^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/block/modes/ctr.dart:18:39: Error: The argument type 'CTRStreamCipher' can't be assigned to the parameter type 'StreamCipher'.
 - 'CTRStreamCipher' is from 'package:pointycastle/stream/ctr.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/stream/ctr.dart').
 - 'StreamCipher' is from 'package:pointycastle/api.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/api.dart').
                underlying.blockSize, CTRStreamCipher(underlying));
                                      ^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/block/modes/ccm.dart:130:35: Error: The method 'SICStreamCipher' isn't defined for the class 'CCMBlockCipher'.
 - 'CCMBlockCipher' is from 'package:pointycastle/block/modes/ccm.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/block/modes/ccm.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SICStreamCipher'.
        SICBlockCipher(blockSize, SICStreamCipher(underlyingCipher));
                                  ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/block/modes/sic.dart:19:39: Error: Method not found: 'SICStreamCipher'.
                underlying.blockSize, SICStreamCipher(underlying));
                                      ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/macs/poly1305.dart:20:5: Error: The getter 'Platform' isn't defined for the class 'Poly1305'.
 - 'Poly1305' is from 'package:pointycastle/macs/poly1305.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/macs/poly1305.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    Platform.instance.assertFullWidthInteger();
    ^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/macs/poly1305.dart:25:5: Error: The getter 'Platform' isn't defined for the class 'Poly1305'.
 - 'Poly1305' is from 'package:pointycastle/macs/poly1305.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/macs/poly1305.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    Platform.instance.assertFullWidthInteger();
    ^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/random/auto_seed_block_ctr_random.dart:26:8: Error: 'BlockCtrRandom' isn't a type.
  late BlockCtrRandom _delegate;
       ^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/random/auto_seed_block_ctr_random.dart:37:17: Error: The method 'BlockCtrRandom' isn't defined for the class 'AutoSeedBlockCtrRandom'.
 - 'AutoSeedBlockCtrRandom' is from 'package:pointycastle/random/auto_seed_block_ctr_random.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/random/auto_seed_block_ctr_random.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BlockCtrRandom'.
    _delegate = BlockCtrRandom(cipher);
                ^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/signers/rsa_signer.dart:41:38: Error: Method not found: 'PKCS1Encoding'.
  final AsymmetricBlockCipher _rsa = PKCS1Encoding(RSAEngine());
                                     ^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/stream/ctr.dart:20:56: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  CTRStreamCipher(BlockCipher underlyingCipher) : super(underlyingCipher);
                                                       ^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/stream/ctr.dart:22:34: Error: The getter 'underlyingCipher' isn't defined for the class 'CTRStreamCipher'.
 - 'CTRStreamCipher' is from 'package:pointycastle/stream/ctr.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/stream/ctr.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'underlyingCipher'.
  String get algorithmName => '${underlyingCipher.algorithmName}/CTR';
                                 ^^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/src/utils.dart:328:7: Error: Undefined name 'Platform'.
  if (Platform.instance.isNative) {
      ^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/ecc/ecdh.dart:34:13: Error: The method 'PlatformException' isn't defined for the class 'ECDHBasicAgreement'.
 - 'ECDHBasicAgreement' is from 'package:pointycastle/ecc/ecdh.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/ecc/ecdh.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformException'.
      throw PlatformException('ECDH public key has wrong domain parameters');
            ^^^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/ecc/ecdh.dart:42:13: Error: The method 'PlatformException' isn't defined for the class 'ECDHBasicAgreement'.
 - 'ECDHBasicAgreement' is from 'package:pointycastle/ecc/ecdh.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/ecc/ecdh.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformException'.
      throw PlatformException('Infinity is not a valid public key for ECDH');
            ^^^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/ecc/ecdh.dart:55:13: Error: The method 'PlatformException' isn't defined for the class 'ECDHBasicAgreement'.
 - 'ECDHBasicAgreement' is from 'package:pointycastle/ecc/ecdh.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/ecc/ecdh.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformException'.
      throw PlatformException(
            ^^^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/ecc/ecdh.dart:66:11: Error: Method not found: 'PlatformException'.
    throw PlatformException('Point must be on the same curve');
          ^^^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart:59:5: Error: The getter 'Platform' isn't defined for the class 'Argon2BytesGenerator'.
 - 'Argon2BytesGenerator' is from 'package:pointycastle/key_derivators/argon2_native_int_impl.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    Platform.instance.assertFullWidthInteger();
    ^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart:341:19: Error: The method 'Blake2bDigest' isn't defined for the class 'Argon2BytesGenerator'.
 - 'Argon2BytesGenerator' is from 'package:pointycastle/key_derivators/argon2_native_int_impl.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blake2bDigest'.
      var blake = Blake2bDigest(digestSize: outLen);
                  ^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart:347:20: Error: The method 'Blake2bDigest' isn't defined for the class 'Argon2BytesGenerator'.
 - 'Argon2BytesGenerator' is from 'package:pointycastle/key_derivators/argon2_native_int_impl.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blake2bDigest'.
      var digest = Blake2bDigest(digestSize: blake2bLength);
                   ^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart:375:16: Error: The method 'Blake2bDigest' isn't defined for the class 'Argon2BytesGenerator'.
 - 'Argon2BytesGenerator' is from 'package:pointycastle/key_derivators/argon2_native_int_impl.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blake2bDigest'.
      digest = Blake2bDigest(digestSize: lastLength);
               ^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart:388:17: Error: The method 'Blake2bDigest' isn't defined for the class 'Argon2BytesGenerator'.
 - 'Argon2BytesGenerator' is from 'package:pointycastle/key_derivators/argon2_native_int_impl.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/key_derivators/argon2_native_int_impl.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blake2bDigest'.
    var blake = Blake2bDigest(digestSize: ARGON2_PREHASH_DIGEST_LENGTH);
                ^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:64:14: Error: 'ExpressionGroup' isn't a type.
  final List<ExpressionGroup<T>> _groups = [];
             ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:65:9: Error: 'SettableParser' isn't a type.
  final SettableParser<T> _loopback = undefined();
        ^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:65:39: Error: Method not found: 'undefined'.
  final SettableParser<T> _loopback = undefined();
                                      ^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:69:19: Error: The method 'ExpressionGroup' isn't defined for the class 'ExpressionBuilder<T>'.
 - 'ExpressionBuilder' is from 'package:petitparser/src/expression/builder.dart' ('/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExpressionGroup'.
    final group = ExpressionGroup<T>(_loopback);
                  ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/petitparser-5.1.0/lib/src/expression/builder.dart:78:19: Error: The method 'build' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'build'.
      (a, b) => b.build(a),
                  ^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/src/registry/registration.dart:27:21: Error: Undefined name 'PKCS1Encoding'.
  registry.register(PKCS1Encoding.factoryConfig);
                    ^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/src/registry/registration.dart:48:21: Error: Undefined name 'Blake2bDigest'.
  registry.register(Blake2bDigest.factoryConfig);
                    ^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/src/registry/registration.dart:105:21: Error: Undefined name 'ECCurve_secp192k1'.
  registry.register(ECCurve_secp192k1.factoryConfig);
                    ^^^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/src/registry/registration.dart:126:21: Error: Undefined name 'RSAKeyGenerator'.
  registry.register(RSAKeyGenerator.factoryConfig);
                    ^^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/src/registry/registration.dart:147:21: Error: Undefined name 'BlockCtrRandom'.
  registry.register(BlockCtrRandom.factoryConfig);
                    ^^^^^^^^^^^^^^
/C:/Users/Ahmer%20Ali/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pointycastle-3.6.2/lib/src/registry/registration.dart:163:21: Error: Undefined name 'SICStreamCipher'.
  registry.register(SICStreamCipher.factoryConfig);
                    ^^^^^^^^^^^^^^^

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksbora** [comment]
Brother are you kidding us , we are not machine summarise the code please ...

**Comment by Moammar1498** [comment]
Sorry for inconvenience. Actually, I am trying to print the repaint boundary image of the widget as an image and pdf. I have done that for image option but struggling with these errors for pdf option. Whenever I pub get this pdf library in my pubsec yml file I got these errors.. I am unable to understand what's going on?!?
