### ISSUE TITLE
Table.fromTextArray doesn't working some things

### ISSUE THREAD

**Issue by pedroserretti** [DavBfr/dart_pdf#1288]
I'm building an PDF, and i need that my headers don't exceed one line, but i'm having some problems with this.
I've tried in so many ways, but the Text keeps going past one line 

static buildTabelaPdf(Pdf pdf) {
    final lista = [];
    final palavras = [
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'bbbbbbbbbbbbbbb',
      'ccccccccccccccc',
      'ddddddddddddddd',
      'eeeeeeeeeeeeeee',
      'fffffffffffffff',
      'ggggggggggggggg',
      'hhhhhhhhhhhhhhh',
      'iiiiiiiiiiiiiii',
      'jjjjjjjjjjjjjjj',
      'kkkkkkkkkkkkkkk',
    ];
    for (int i = 0; i < 11; i++) {
      final teste2 = Teste2(texto: palavras[i], maxLines: 1);
      lista.add(teste2);
    }

    final headers = lista.map((header) => header.textoTeste()).toList();

    final data = pdf.produtos.map((item) {
      final total = item.precoUnit * item.qtd;

      return [
        item.descricaoProd,
        Util.formatDate(item.data),
        '${item.qtd}',
        '\$ ${item.precoUnit}',
        '\$ ${total.toStringAsFixed(2)}',
        '\$ ${item.teste1}',
        '\$ ${item.teste2}',
        '\$ ${item.teste3}',
        '\$ ${item.teste4}',
        '\$ ${item.teste5}',
        '\$ ${item.teste6}',
      ];
    }).toList();

    return Table.fromTextArray(
      headers: headers,
      data: data,
      border: null,
      headerStyle: TextStyle(fontWeight: FontWeight.bold),
      headerDecoration: BoxDecoration(color: PdfColors.grey300),
      cellPadding: EdgeInsets.symmetric(vertical: 10),
      columnWidths: {
        0: FractionColumnWidth(0.25),
        1: FractionColumnWidth(0.15),
        2: FractionColumnWidth(0.15),
        3: FractionColumnWidth(0.1),
        4: FractionColumnWidth(0.1),
        5: FractionColumnWidth(0.1),
        6: FractionColumnWidth(0.1),
        7: FractionColumnWidth(0.1),
        8: FractionColumnWidth(0.1),
        9: FractionColumnWidth(0.1),
        10: FractionColumnWidth(0.1),
      },
      cellHeight: 10,
      cellAlignments: {
        0: Alignment.centerLeft,
        1: Alignment.centerLeft,
        2: Alignment.center,
        3: Alignment.centerLeft,
        4: Alignment.centerLeft,
        5: Alignment.centerLeft,
        6: Alignment.centerLeft,
        7: Alignment.centerLeft,
        8: Alignment.centerLeft,
        9: Alignment.centerLeft,
        10: Alignment.centerLeft,
        11: Alignment.centerLeft,
      },
    );
  }

The class Teste2: 

import 'package:flutter/material.dart';

class Teste2 {
  final String texto;
  final int maxLines;

  const Teste2({
    required this.texto,
    required this.maxLines,
  });

textoTeste() {

    Text(
      texto,
      maxLines: maxLines,
      style: TextStyle(
        color: Colors.black,
        fontSize: 16,
        fontFamily: 'Poppins',
      )
    );
    return texto;
  }
}

**(i know that i'm not using TextOverflow in this code, but i've tried to use before and didn't work, so i was testing just with the maxLines, but it didn't work too)**

**Comment by pedroserretti** [comment]
anyone can help me????

**Comment by pedroserretti** [comment]
@DavBfr

**Comment by bksbora** [comment]
You put into a builder and can arrange your font size on spesific cell or completely , dont know there are so many ways to do that.  Also you can make it responsive. You may use just Table widget. 
```dart 
headerStyle: KanatNo == 0
                        ? tableHeaderStyle
                        : pw.TextStyle(
                            fontWeight: pw.FontWeight.normal,
                          ),
```

**Comment by pedroserretti** [comment]
> You can put into a builder and can arrange your font size on spesific cell or completely , dont know there are so many ways to do that. Also you can make it responsive. You may use just Table widget.
> 
> ```dart
> headerStyle: KanatNo == 0
>                         ? tableHeaderStyle
>                         : pw.TextStyle(
>                             fontWeight: pw.FontWeight.normal,
>                           ),
> ```

The problem is that I am testing it to use it in the company, so there would have to be some limitation to not exceed one line, regardless of the font size, if the name is longer than expected, it will exceed it anyway, understand? and the customer was not satisfied

I already tried to limit the characters but it would not solve my problem.

For example, "Manga Manga Manga Manga Manga Manga..." and exceeding the line, somehow it should limit only the amount of characters according to the column size.

![3](https://user-images.githubusercontent.com/109255580/225960576-df00f81e-e51e-46cc-8eab-5506be1c146c.png)

**Comment by bksbora** [comment]
Okey , think like that : 

I dont know where you take your data (API or a list) but you can make manipulation on your data before your table build. 

-We know the  page measurements, we know the font size soo we know how many character it would fit into it. ( or try and find)

1) Create a stateful widget
2)  Create your table '' late pw.Container TABLOPDF; ''
3) In initstate fetch your data with function and put it into a model or an array.
4) Manuplate your data with a function
something like : 
```dart
String limitText(String text, int maxLength) {
    if (text.length > maxLength) {
      return text.substring(0, maxLength) + "...";
    } else {
      return text;
    }
```
5) Now time to build your table  =>TABLOPDF
6 )create a Future<Uint8List> _generatePdf() async {
THİS İS YOUR PLAYGORUND,
TABLOPDF}
```dart
pdf.addPage(
// Page Ayarları
      pw.MultiPage(
          maxPages: 100,
          theme: pw.ThemeData(
              defaultTextStyle: pw.TextStyle(font: font, fontSize: fontsize)),
          pageFormat: format,
          orientation: pw.PageOrientation.portrait,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          build: (context) {
            return FinalPDF;
          }),
    );

    return pdf.save();
    
```
Hope i can explain it :) Good luck !
