### ISSUE TITLE
Specifying the Paper Tray (Source of the paper)

### ISSUE THREAD

**Issue by jeff9315** [DavBfr/dart_pdf#1289]
In Windows 11 and an HP printer .... is there a way to specify which paper tray to use automatically? This is the Windows Print Dialog. With this particular document, I want to change the **Source** from **Alternative Tray** to **Main Tray** programmatically since this particular document should **always** use the **Main Tray**.

![image](https://user-images.githubusercontent.com/20246623/224553160-9111d341-172a-4fc2-9edb-e0ec7be227a7.png)

**Comment by moritz157** [comment]
@jeff9315 Did you find a workaround?

**Comment by jeff9315** [comment]
> [@jeff9315](https://github.com/jeff9315) Did you find a workaround?

No. I never did
