### ISSUE TITLE
How to adjust the space between two paragraphs?

### ISSUE THREAD

**Issue by animator** [DavBfr/dart_pdf#129]
```
<Widget>[ Paragraph(
                text: 'xyz',textAlign: TextAlign.center),
          Paragraph(
                text: 'see line', textAlign: TextAlign.center),
          Paragraph(
                text: 'abcd'),
            ...... ]
```

I want to adjust the space between two paragraphs above. Is there a widget to do that?

Thanks!

**Comment by DavBfr** [comment]
Use this: `SizedBox(height: 20)`

**Comment by animator** [comment]
@DavBfr thanks for the quick reply. It worked for increasing the space between paragraphs.
Is there a feature for decreasing the default spacing between paragraphs something on the lines of \vspace in latex (https://www.complang.tuwien.ac.at/anton/latex/ltx-347.html) which accepts both positive and negative spacing.

Thanks!

**Comment by DavBfr** [comment]
You can use margin or padding:
```dart
Paragraph(margin: EdgeInsets.only(bottom: 20),
                text: 'abcd'),
```

**Comment by animator** [comment]
Thanks! It worked like a charm.

**Comment by victormutuku** [comment]
This does not work when you have a large block of text. My expectation was that it would seperate paragraphs from a given text but that is not the case. If a given text is too large, it displays a blank where the text is supposed to be.

> You can use margin or padding:
> 
> ```dart
> Paragraph(margin: EdgeInsets.only(bottom: 20),
>                 text: 'abcd'),
> ```

**Comment by victormutuku** [comment]
As you can see, it works perfectly fine for short text.

![Screenshot_20231031_184703_Drive 1](https://github.com/DavBfr/dart_pdf/assets/71630718/5888c28e-3d7b-4951-ad30-b9ce6335ee7c)

When it comes to lengthy text, it does not work the same. Here is an output without using the Paragraph widget. There is supposed to be a blank line after each paragraph.

![Screenshot_20231031_184654_Drive 1](https://github.com/DavBfr/dart_pdf/assets/71630718/fb4059bb-90f7-4c1f-87e7-ffd6a8eff865)

Here is the output when using the Paragraph widget.  As you can see, the text is not output. 

![Screenshot_20231031_184506_Drive 1](https://github.com/DavBfr/dart_pdf/assets/71630718/b373c35b-334b-4c33-ad44-a87489a1d225)

Again, it was my assumption that it would separate the paragraphs automatically from the given text.
