### ISSUE TITLE
Digital Signature Not Supported

### ISSUE THREAD

**Issue by kttary** [DavBfr/dart_pdf#1292]
I have pdf with digital signature. The signature specimen (image) do not appear. Any setting i should set?

**Comment by DavBfr** [comment]
Can you give more details on what you do?

**Comment by kttary** [comment]
I have a pdf file with digital signature. If i open it from browser, i can see the signature image:
![signature](https://user-images.githubusercontent.com/39557649/224867794-4b774cdf-25e2-4e0a-9920-ad98312c015b.png)

But if i load the same pdf with printing library, the signature image disappear:
![image](https://user-images.githubusercontent.com/39557649/224868162-7ebbef57-33bd-4b98-80e7-0f7a8ecb0593.png)

Here is the pdf file
[partialpage.pdf](https://github.com/DavBfr/dart_pdf/files/10963256/partialpage.pdf)
