### ISSUE TITLE
Unable to display document is web

### ISSUE THREAD

**Issue by lpemeg** [DavBfr/dart_pdf#1293]
**Describe the bug**
I'm having problems running PdfPreview, the error "unable to display the document" appears, then I checked it is not loading the pdfjs pdf.min and pdf.worker.min, in the documentation it says that it loads alone, but this is not happening When it is published, in debug it works normally, but when I build it it doesn't work anymore.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
body: PdfPreview(
        maxPageWidth: 700,
        canChangePageFormat: false,
        canChangeOrientation: false,
        canDebug: false,
        build: (f) => buildPdf(f),
        onPrinted: (context) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Documento compartilhado com sucesso'),
            ),
          );
        },
      ),
```

**Flutter Doctor**
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [versÆo 10.0.22621.1265], locale pt-BR)
    • Flutter version 3.7.0 on channel stable at D:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (7 weeks ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\lprs1\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.76.1)
    • VS Code at C:\Users\lprs1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22621.1265]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari, chome]

**Comment by Maztermo** [comment]
I'm having the same issue.
Works in chrome debug, but the published version gives me a grey site with "Unable to display the document".

**Comment by DavBfr** [comment]
Fixed.
