### ISSUE TITLE
projec broken on latest sdk

### ISSUE THREAD

**Issue by gedw99** [DavBfr/dart_pdf#13]
seems they changed some things about how things need to be laid out.
Gradle was going bananas !

Basically you just need to make the examples directory a proper Flutter project.
1. Just go into ./pdf && ```flutter create example```

2. then from the example folder pubspec.yaml, reference your plugin using the ../ notation.

3. then just copy your example main.dart  into it

EDIT:
here is an example: https://github.com/memspace/zefyr/blob/master/packages/zefyr/example/pubspec.yaml

**Comment by gedw99** [comment]
also i think in the example you need to use the FileSystem Provider

https://flutter.io/cookbook/persistence/reading-writing-files/

**Comment by DavBfr** [comment]
The example in pdf is not for flutter but for command line dart. Just run 
`dart example/main.dart` and it creates a pdf file.

For Flutter, the example is in printing/example/

**Comment by gedw99** [comment]
yeah i realise al that.

Its more that the tooling for flutter complains about the example folder if it does not have its own pubspec.  I knwo its a bit OTT i dont think i got these error messages a week ago on the previous SDK, and so just trying to e thorough.
