### ISSUE TITLE
The euro Sign   € or '\u{20AC}' not appear in pdf file

### ISSUE THREAD

**Issue by tarikmsr** [DavBfr/dart_pdf#1300]
**Describe the bug**
The euro Sign € or '\u{20AC}' not appear in pdf file
I tried or replace it by \€ and '\u{20AC}'  and it still doesn't work !

**Packages**
  pdf: ^3.9.0
  printing: ^5.10.1 

  

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
 var logoImage = imageFromAssetBundle('assets/images/IconScreenSplash.png');
                               
                                final fontData = await rootBundle.load('assets/fonts/Roboto-Regular.ttf');
                                final font = pw.Font.ttf(ByteData.view(fontData.buffer));

                                final pdfDoc = pw.Document();
                                pdfDoc.addPage(
                                  pw.Page(
                                    pageFormat: PdfPageFormat.a4,
                                    build: (pw.Context context) {
                                      return pw.Center( child:Tex('10.000 \u{20AC}',
                                       style: pw.TextStyle(
                                              fontSize: 18,
                                            ),
                                            ),
                                            );
                                            }
                                            .....
                                              
                                   await Printing.sharePdf(bytes: await pdfDoc.save(),
                            filename: filename);
                                      
```

**Screenshots**

![image](https://user-images.githubusercontent.com/64175026/226118609-1cdbdc33-3bf9-4742-9be8-b0fb3c98fe5c.png)

**Desktop (please complete the following information):**
 - [ ] Browser

**Comment by DavBfr** [comment]
You didn't use the font.
Try:

```dart
    final font = await PdfGoogleFonts.robotoRegular();

    pdfDoc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) =>
            pw.Text('10.000 \u{20AC}', style: pw.TextStyle(font: font)),
      ),
    );
```

**Comment by tarikmsr** [comment]
Thanks, I used a global font, and it worked for me.
`
 robotoTheme = pw.ThemeData.withFont(
      base: pw.Font.ttf(await rootBundle.load("assets/fonts/Roboto/Roboto-Regular.ttf")),
      bold: pw.Font.ttf(await rootBundle.load("assets/fonts/Roboto/Roboto-Bold.ttf")),
      italic: pw.Font.ttf(await rootBundle.load("assets/fonts/Roboto/Roboto-Italic.ttf")),
    );
   

    var pdfDoc = pw.Document(
                                  theme: robotoTheme,
                                );
                                
    pdfDoc.addPage(
      pw.Page(......                            


`
