### ISSUE TITLE
When I load a white image, the colors don't come right

### ISSUE THREAD

**Issue by RamiHI** [DavBfr/dart_pdf#1303]
**Describe the bug**
I am loading a white image, and it comes with a black mask and a yellow color

**To Reproduce**
pw.MemoryImage aboutMe = pw.MemoryImage(
    (await rootBundle.load('assets/templates_icons/template_1/aboutMe.png'))
        .buffer
        .asUint8List(),
  );

pw.Image(aboutMe),

**Screenshots**
![photo_2023-03-21_17-11-10](https://user-images.githubusercontent.com/107990736/226632973-e4500c8e-41ca-48ae-bbec-62eb8323b74f.jpg)
![photo_2023-03-21_17-11-05](https://user-images.githubusercontent.com/107990736/226633003-4beb587e-ca67-4c60-9fc5-e27b18e5a9ba.jpg)

**Desktop (please complete the following information):**
 - Android

**Smartphone (please complete the following information):**
 - Device: Redmi Note 11 pro

**Comment by DavBfr** [comment]
What is the source image?

**Comment by RamiHI** [comment]
![aboutMe](https://user-images.githubusercontent.com/107990736/227184943-75ce009b-17b8-4b71-9b7e-a513f599237e.png)

**Comment by DavBfr** [comment]
Seems to be a bug in the image package. You can change the file to RGBA instead of Grey palette and see if it solves the issue.
