### ISSUE TITLE
[printing] Windows layoutPdf default size is always on first and paper size is not get save.

### ISSUE THREAD

**Issue by NickYoung-max** [DavBfr/dart_pdf#1306]
printing version : 5.10.1

 flutter doctor:
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows
[Version 10.0.19044.2728], locale zh-CN)
[√] Windows Version (Installed version of Windows is
version 10 or higher)
[√] Android toolchain - develop for Android devices
(Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio
Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

![企业微信截图_16795438837868](https://user-images.githubusercontent.com/38856823/227100104-ad92d843-0c59-4fa0-88c9-5440e1c1a3cd.png)
size is always selected on 4x4 each time layoutPdf()( I want to select USER as default ). And, if I change the selection to USER in this 
main dialog first ,then go to 'Properties' page,  the USER's originer paper size lose (USER originer paper size shuoul be 70x35,but turn to 101.6x101.6,as the same size of selection 4x4). 
![image](https://user-images.githubusercontent.com/38856823/227103761-a0540053-d747-45bd-800b-6aae2a6d8bcd.png)

But, if I go to 'Properties' page first 
![image](https://user-images.githubusercontent.com/38856823/227103051-7ab7cafd-9e8d-4f24-83ac-2f87ca9ec14b.png)
then I change the selection from 4x4 to USER, the USER's paper size is correct(70x35)
![image](https://user-images.githubusercontent.com/38856823/227103635-69bca1af-21c6-4bd2-9520-4a557d85e8da.png)

**Comment by AriDevC** [comment]
any updates on this?
