### ISSUE TITLE
App crashes when using PdfPreview

### ISSUE THREAD

**Issue by affmferraz** [DavBfr/dart_pdf#1310]
**Describe the bug**
When using the PdfPreview on the iPad the app is crashing. It loads the PDF and shows on the screen, but when scrolling down it crashes. I've attached the PDF I'm trying to preview. It always happens when the device is in landscape orientation, in portrait it runs fine on most devices, but it crashes sometimes as well.
[Wader Logbook 45.pdf](https://github.com/DavBfr/dart_pdf/files/11068374/Wader.Logbook.45.pdf)

The error message is: 
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=3072 MB, unused=0x0)
    frame #0: 0x000000020c8b4734 libsystem_platform.dylib`_platform_memmove + 100
libsystem_platform.dylib`:
->  0x20c8b4734 <+100>: stnp   x8, x9, [x3]
    0x20c8b4738 <+104>: stnp   x10, x11, [x3, #0x10]
    0x20c8b473c <+108>: add    x3, x3, #0x20
    0x20c8b4740 <+112>: ldnp   x8, x9, [x1]
Target 0: (Runner) stopped.
```

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
PdfPreview(
        pdfFileName: '${user.fullName} - Wader Logbook',
        canDebug: false,
        canChangeOrientation: false,
        canChangePageFormat: false,
        build: (format) => _pdf.save(),
)
```

**Flutter Doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2 22D49 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.0)
[✓] VS Code (version 1.68.0-insider)
[✓] VS Code (version 1.68.0-insider)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: iPad Pro (10.5-inch)
 - OS: 16.3.1

**Comment by bummsa** [comment]
I also experience the same problem - but only with large PDF files.

**Comment by ChristianAdrian** [comment]
Same issue experienced on pdf files with more than 4 pages

**Comment by affmferraz** [comment]
It's still happening here as well, if anyone found a solution I'd really appreciate if you could share.
