### ISSUE TITLE
table splitting between pages in pdf

### ISSUE THREAD

**Issue by priya-iyer9** [DavBfr/dart_pdf#1319]
When there is more than accommodated data in a section the table is to move to the next page, but instead it splits between the header and content section as such:

<img width="445" alt="Screenshot 2023-03-30 171618" src="https://user-images.githubusercontent.com/73986264/228826666-b0d5491f-c1e6-4820-bccc-f6ccf7ef1a5b.png">

this is the code:

pw.Padding(
        padding: const pw.EdgeInsets.only(left: 10.0, right: 10.0, bottom: 30.0),
        child: pw.Table(
          defaultColumnWidth: const pw.IntrinsicColumnWidth(),
          children: [
            pw.TableRow(
              children: [
                headerContainer(
                  "header text goes here",
                ),
              ],
            ),
            pw.TableRow(
              children: [
                pw.Container(
                  margin: const pw.EdgeInsets.only(top: 15.0, left: 10.0, right: 10.0),
                  child: pw.Table(
                    border: pw.TableBorder.all(color: PdfColors.black),
                    // defaultColumnWidth: const pw.IntrinsicColumnWidth(),
                    columnWidths: {
                      0: const pw.FixedColumnWidth(100.0),
                      1: const pw.FixedColumnWidth(300.0),
                      2: const pw.FixedColumnWidth(100.0),
                      3: const pw.FixedColumnWidth(300.0),
                    },
                    children: [
                      pw.TableRow(
                        children: [
                          pw.Container(height: 60.0),
                        ],
                      ),
                      pw.TableRow(
                        children: [
                          pw.Container(height: 60.0),
                        ],
                      ),
                      pw.TableRow(
                        children: [
                          pw.Container(height: 60.0),
                        ],
                      ),
                      pw.TableRow(
                        children: [
                          pw.Container(height: 60.0),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ],
        ),
      );

why is the header splitting? and is there a solution to this?

**Comment by bksbora** [comment]
You put table into a table(it splits between them i guess) ? Can you try just 1 table and if thats not work put that table into a container .

**Comment by priya-iyer9** [comment]
that does not work @bksbora

**Comment by bksbora** [comment]
Okey, did you try datatable ?

**Comment by priya-iyer9** [comment]
the datatable also doesn't work. is there a workaround for this @DavBfr ?
