### ISSUE TITLE
how to add printer manually 

### ISSUE THREAD

**Issue by maxzod** [DavBfr/dart_pdf#1321]
in ios  i can list printers
so i made a form so the user can add a printer and print directly 

the forms conations 2 fields the printer name and url 
and url for example 
`http://192.168.1.23.53000`
still the app crashes after a few prints i windows
and i can't figure out why there is not logs besides the app closes

**Comment by DavBfr** [comment]
Try to run it with visual studio in debug mode see the backtrace.
