### ISSUE TITLE
Space between some letters is larger than rendered in browser

### ISSUE THREAD

**Issue by QiuranHu** [DavBfr/dart_pdf#1323]
**Describe the bug**
Space between some letters (like space between Y and o in "York") is larger than the text rendered in a browser using the same font.

I used the flutter pdf demo(https://davbfr.github.io/dart_pdf/#/). In the CERTIFICATE tab, I entered the name as "New York". In the generated pdf, the space between Y and o seems to be larger than rendered in browser (I used google fonts to see it in the browser). As shown in the screenshots below.

Is it possible to achieve the same space as rendered in browser?

**Screenshots**

Flutter PDF demo:
<img width="1017" alt="Screenshot 2023-04-02 at 11 48 49" src="https://user-images.githubusercontent.com/55808904/229330298-978550d5-a7cf-47d4-a2ba-47952f3342e9.png">

Google fonts:
<img width="1016" alt="Screenshot 2023-04-02 at 12 00 48" src="https://user-images.githubusercontent.com/55808904/229330601-0033fcb8-ca04-4896-aefd-d74933db558b.png">
[Link to google fonts](https://fonts.google.com/specimen/Libre+Baskerville?preview.text=New%20York&preview.text_type=custom)

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [x] Browser
 - [ ] Windows
 - [ ] Linux

**Comment by DavBfr** [comment]
Implement font kerning and/or GPOS 
https://learn.microsoft.com/en-us/typography/opentype/spec/recom#kern-table

**Comment by QiuranHu** [comment]
Sorry I'm not familiar with text rendering. Do you mean that after font kerning is implemented in OpenType layout engine of dart_pdf, we can achieve the same effect as rendered in web?

Thank you for making this amazing library by the way.

**Comment by DavBfr** [comment]
Yes, that's the way to do it. Kerning is a map in the font file that defines for this example that a Y immediately followed by an o will be shifted a few pixels to the left.

**Comment by yzxben** [comment]
This issue is still relevant - Please reopen
