### ISSUE TITLE
Underline on TextSpan inside RichText  is not marking the last and first word of a sentance

### ISSUE THREAD

**Issue by RomanIvn** [DavBfr/dart_pdf#1325]
`  PdfRect? _getBox(List<_Span> spans) {
    if (_box != null) {
      return _box;
    }

    final x1 = spans[startSpan].offset.x + spans[startSpan].left >>>>>+spans[startSpan].advancedWidth<<<<<;
    final x2 = spans[endSpan].offset.x + spans[endSpan].left + spans[endSpan].width >>>>>>- spans[endSpan].advancedWidth<<<<;
    var y1 = spans[startSpan].offset.y + spans[startSpan].top;
    var y2 = y1 + spans[startSpan].height;

    for (var n = startSpan + 1; n <= endSpan; n++) {
      final ny1 = spans[n].offset.y + spans[n].top;
      final ny2 = ny1 + spans[n].height;
      y1 = math.min(y1, ny1);
      y2 = math.max(y2, ny2);
    }

    _box = PdfRect.fromLTRB(x1, y1, x2, y2);
    return _box;
  }
`

Only after adding the following changes (and advancedWidth to _Span class)   i was able to see the underline on the whole sentance.
Otherwise the underline is not present in the first and last span.

**Comment by DavBfr** [comment]
@RomanIvn Can you provide an example of what was wrong here?
Otherwise, I'll have to revert this commit.

**Comment by DevMensIT** [comment]
@DavBfr  underline is not working properly here is the example.
![image](https://github.com/DavBfr/dart_pdf/assets/11617013/b5d01422-74e8-4466-99ed-fdb9aa3625a1)


code : 

```
pw.Text(
          "UNDER LINE IS NOT WORKING PROPERLY",
          style: pw.TextStyle(
              fontSize: 22, decoration: pw.TextDecoration.underline),
        ),
```
