### ISSUE TITLE
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is  not set. 

### ISSUE THREAD

**Issue by vinodh013** [DavBfr/dart_pdf#1327]
**Describe the bug**

CMake Warning (dev) at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/ExternalProject.cmake:3071 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/ExternalProject.cmake:4167 (_ep_add_download_command)
  CMakeLists.txt:9 (ExternalProject_Add)
This warning is for project developers.  Use -Wno-dev to suppress it.

I am getting this error while building the flutter run, I tried to clean the build and rebuild but I am getting the same error.
Anybody who can tell me How to solve this issue?  "Thanks in advance"

**Comment by jemisgoti** [comment]
This issue is already fixed by me and i have generated PR for that. Now waiting for the approval. 
Ref : #1332

**Comment by vinodh013** [comment]
Thank you @jemisgoti  It's working
