### ISSUE TITLE
How can I draw such a figure?

### ISSUE THREAD

**Issue by RamiHI** [DavBfr/dart_pdf#1328]
I want to draw a shape like this, from the left a full-height red rectangle, and from the right, information that I had previously prepared.
![image](https://user-images.githubusercontent.com/107990736/230121224-5eff0542-b132-4af9-80cb-46a2d536cc24.png)

**Comment by bksbora** [comment]
Think like its a column with background . You can divide with row either partitions.

**Comment by RamiHI** [comment]
I actually divided it by row but the red rectangle does not take up the full height

**Comment by bksbora** [comment]
Can you give it try with partitions widget :)

**Comment by RamiHI** [comment]
The same problem

**Comment by bksbora** [comment]
Suggestion 1) 
const double inch = 72.0;
const double cm = inch / 2.54;
    decleare this variables and use page measurements  to give your container or partitions measure (what u are using )like if your page is A4 21cm and 29.7cm so your container height : 28.7 * cm (-- if you cant decleare use : 28.7 * 72.0 / 2.54
    --) , width : 20 * cm

**Comment by RamiHI** [comment]
but i want the red rectangle height as the right part that unknown height

**Comment by DavBfr** [comment]
try to use `height: double.infinity` for the Container

**Comment by RamiHI** [comment]
It gives me an error : 
Exception: This widget created more than 20 pages. This may be an issue in the widget or the document. See https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html

**Comment by DavBfr** [comment]
Yes, it won't work with MultiPage as it's virtually infinite height.

Try that instead:
```dart
    final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);
    final font = await PdfGoogleFonts.nunitoExtraLight();

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: format.applyMargin(
            left: 100,
            bottom: 0,
            right: 0,
            top: 0,
          ),
          buildBackground: (context) {
            return pw.FullPage(
              ignoreMargins: true,
              child: pw.Align(
                alignment: pw.Alignment.centerLeft,
                child: pw.Container(
                  color: PdfColors.red,
                  width: 80,
                  child: pw.Center(
                    child: pw.Transform.rotateBox(
                      unconstrained: true,
                      angle: pi / 2,
                      child: pw.Text(
                        'EXPERIENCE',
                        style: const pw.TextStyle(
                          color: PdfColors.white,
                          fontSize: 30,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            );
          },
        ),
        build: (context) {
          return [
            pw.SizedBox(
              width: double.infinity,
              child: pw.FittedBox(
                child: pw.Text(title, style: pw.TextStyle(font: font)),
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Flexible(child: pw.FlutterLogo())
          ];
        },
      ),
    );
```

**Comment by RamiHI** [comment]
The right section has flexible height depending on the user input and the number of the elements included.
So the red element needs to take the same size of the right section.
