### ISSUE TITLE
[printing-5.10.3] After updating printing: ^5.9.1 to printing: ^5.10.3, I can't build my android app.

### ISSUE THREAD

**Issue by TakaTeke** [DavBfr/dart_pdf#1331]
After updating printing: ^5.9.1 to printing: ^5.10.3, I can't build my android app.
printing-5.10.3/lib/src/widget_wrapper.dart:178:7: Error: No named parameter with the name 'window'.

**execution log**
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...

../../../../.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7: Error: No named parameter with the name 'window'.
      window: view,
      ^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/view.dart:68:3: Context: Found this candidate, but the arguments don't match.
  RenderView({
  ^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/taka/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/taka/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Flutter Doctor**
/Users/taka/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 3.9.0-22.0.pre.102, on macOS 13.3.1 22E261 darwin-arm64, locale ja-JP)
    • Flutter version 3.9.0-22.0.pre.102 on channel master at /Users/taka/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3ea2d72446 (13 hours ago), 2023-04-07 19:45:14 -0700
    • Engine revision 1f5433d4e4
    • Dart version 3.0.0 (build 3.0.0-417.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/taka/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.49

[✓] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

**Comment by DavBfr** [comment]
Yes, it's not compatible with Flutter 3.9.0.

**Comment by TakaTeke** [comment]
Thank you.
After downgrading to Flutter version 3.7.10 on channel stable, everything works fine.
