### ISSUE TITLE
Horizontal scroll in generated pdf file

### ISSUE THREAD

**Issue by DhvanitVaghani** [DavBfr/dart_pdf#1333]
**Is your feature request related to a problem? Please describe.**

I have one case where I need a horizontal scroll in pdf. I faced this issue because my data length is dynamic. Also, this feature is required while pdf creation. It would be appreciated if you will give any solution. 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavBfr** [comment]
What do you mean by horizontal scroll?

**Comment by DhvanitVaghani** [comment]
I have one case where I am using table view in pdf. In this table, the column number is not fixed. When I add 12-15 columns, the pdf starts to shrink horizontally rather than scroll. So I am requesting that it would be great if my number of columns increases so it will scroll instead of shrinking.

**Comment by DavBfr** [comment]
It cannot scroll, think of it as a piece of paper. You cannot scroll the content of a hard copy.

**Comment by DhvanitVaghani** [comment]
Thanks, @DavBfr. Now I totally understand. The explanation is great.
