### ISSUE TITLE
Support flutter 3.10.x

### ISSUE THREAD

**Issue by asaarnak** [DavBfr/dart_pdf#1338]
https://docs.flutter.dev/release/breaking-changes/window-singleton

Error when building:

Running Xcode build...
Xcode build done.                                           41.6s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7: Error: No named parameter with the name 'window'.

**Comment by asaarnak** [comment]
Found that this is already done here: https://github.com/DavBfr/dart_pdf/commit/029c8f53d623a1f991ece3c548cb7d83a83aff49

**Comment by iamdineshkumar** [comment]
I am getting following error with latest flutter
```
/.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7:
 _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
Error: No named parameter with the name 'window'.
```
