### ISSUE TITLE
Printing - Build on windows stops after updating cmake to 3.25 

### ISSUE THREAD

**Issue by romulocrj** [DavBfr/dart_pdf#1339]
**Describe the bug**
After updating visual studio to version 2022 (17.5.3) a flutter application for windows with Printing no longer builds.
Visual Studio  (17.5.3) comes with cmake version cmake-3.25 wich throws this error:

CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:45 (include):
  include could not find requested file:
  ../build/windows/pdfium-src/PDFiumConfig.cmake
  Exception: Unable to generate build files

**To Reproduce**
Just add Printing on Flutter Windows Project with visual studio 2022 (17.5.3) installed.

**Expected behavior**
Build

**Comment by DavBfr** [comment]
Duplicates #1375
