### ISSUE TITLE
Getting issue after Flutter SDK upgrade

### ISSUE THREAD

**Issue by jogindergur** [DavBfr/dart_pdf#1340]
I just upgraded my SDK to Flutter (Channel master, 3.10.0-6.0.pre.19, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)

and getting this error.

../../../.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7: Error: No named parameter with the name 'window'.
      window: view,
      ^^^^^^
../../../Downloads/flutter/packages/flutter/lib/src/rendering/view.dart:68:3: Context: Found this candidate, but the arguments don't match.
  RenderView({

I have tried flutter clean & dart pub cache clean

but nothing worked for me.

Finally, I have to edit in library and changed parameter from "window" to "view" then it worked for me.

Kindly have a look at this issue so we will automatically get correct parameters.

Thank You!

**Comment by DavBfr** [comment]
Duplicates #1338

**Comment by jogindergur** [comment]
Hi @DavBfr,

I didn't know it was already list issue. Please release new version with fix as every time I clean project need to set it.
