### ISSUE TITLE
using oft with chinese characters is returning an error

### ISSUE THREAD

**Issue by Wassiem-Ibrahim** [DavBfr/dart_pdf#1345]
I am trying to add noto sans TC .otf to use to generate pdf, so each time I try to do it, it throws this error:

The following ArgumentError was thrown while generating a PDF:
Invalid argument (string): Contains invalid characters.: "美國印第安納州第34號百老匯街"

When the exception was thrown, this was the stack: 
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      PdfFont.stringMetrics (package:pdf/src/pdf/obj/font.dart:311:28)
#3      PdfTtfFont.stringMetrics (package:pdf/src/pdf/obj/ttffont.dart:185:20)
#4      RichText.layout._buildLines (package:pdf/src/widgets/text.dart:936:36)
#5      RichText.layout (package:pdf/src/widgets/text.dart:1128:5)
#6      Flex.layout (package:pdf/src/widgets/flex.dart:285:15)
#7      Padding.layout (package:pdf/src/widgets/basic.dart:90:14)
#8      SingleChildWidget.layout (package:pdf/src/widgets/widget.dart:302:14)
#9      ConstrainedBox.layout (package:pdf/src/widgets/basic.dart:434:14)
#10     StatelessWidget.layout (package:pdf/src/widgets/widget.dart:240:15)
#11     Flex.layout (package:pdf/src/widgets/flex.dart:285:15)
#12     ConstrainedBox.layout (package:pdf/src/widgets/basic.dart:434:14)
#13     StatelessWidget.layout (package:pdf/src/widgets/widget.dart:240:15)
#14     SingleChildWidget.layout (package:pdf/src/widgets/widget.dart:302:14)
#15     StatelessWidget.layout (package:pdf/src/widgets/widget.dart:240:15)
#16     Partition.layout (package:pdf/src/widgets/partitions.dart:57:11)
#17     Partitions.layout (package:pdf/src/widgets/partitions.dart:181:15)
#18     MultiPage.generate (package:pdf/src/widgets/multi_page.dart:314:13)
#19     Document.addPage (package:pdf/src/widgets/document.dart:117:10)
#20     generateResume1 (package:cvuim/app/core/cv_templates/template_1.dart:146:7)
<asynchronous suspension>
#21     PdfPreviewRaster._raster (package:printing/src/preview/raster.dart:125:13)
<asynchronous suspension>
PageFormat: "PdfPageFormat 595.275590551181x841.8897637795275 margins:56.69291338582677, 56.69291338582677, 56.69291338582677, 56.69291338582677"

However, whenever I try to use a ttf font for Chinese it works fine, and this is how I call the font:
final ttfRegular = pw.Font.ttf(await rootBundle.load(
            'assets/fonts_templates/noto_sans_ch_tr/noto_sans_regular.otf'));
and I have the font in my assets folder.

So, my question what is the problem with oft, and what should I add to make it work with oft?

**Comment by richardchui** [comment]
@Wassiem-Ibrahim  What ttf fonts are you using? I have a hard time finding good ttf fonts for traditional and simplifed Chinese.  The curious thing is, when converting otf to ttf, I will get a very small file and could not be used in the program.

**Comment by minhdanh** [comment]
Hi @Wassiem-Ibrahim could you have your problem solved? If yes can you share a bit about it?
