### ISSUE TITLE
Barcode Numbers Stacking

### ISSUE THREAD

**Issue by jerckov40** [DavBfr/dart_pdf#1346]
**Describe the bug**
After Upgrading from 3.9 to 3.10 Barcode numbers are printing wrong. All the numbers are printing one stacked to the other.

**To Reproduce**
`import 'package:pdf/widgets.dart' as pw;

pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.center,
      children: <pw.Widget>[
        pw.Flexible(
          fit: pw.FlexFit.tight,
          child: pw.Center(
            child: pw.BarcodeWidget(
              barcode: pw.Barcode.code128(),
              data: '1713',
              width: 100,
              height: 40,
              margin: pw.EdgeInsets.symmetric(vertical: 0),
              textStyle: const pw.TextStyle(fontSize: 12),
            ),
          ),
        ),
      ],
    );`

**Expected behavior**
Print the numbers alongside the othes.

**Screenshots**
3.9
![image](https://user-images.githubusercontent.com/11053810/233080531-c3562092-66da-489d-810e-2f28f56aef85.png)

3.10
![image](https://user-images.githubusercontent.com/11053810/233080706-b9ae0cd7-fb6f-4a74-9829-9608a96a04a8.png)

**Flutter Doctor**
[√] Flutter (Channel stable, 3.7.11, on Microsoft Windows [versÆo 10.0.22621.1555], locale pt-BR)
    • Flutter version 3.7.11 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (8 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\AndroidSDK
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = D:\AndroidSDK
    • Java binary at: D:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22621.1555]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.48

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Desktop (please complete the following information):**
 - [X] iOS
 - [X] Android
 - [ ] Browser
 - [X] Windows
 - [ ] Linux

**Comment by DavBfr** [comment]
I can't reproduce that.

**Comment by jerckov40** [comment]
> I can't reproduce that.

what can I do to help ?

**Comment by DavBfr** [comment]
I get this:

<img width="489" alt="Screenshot 2023-05-02 at 12 59 18" src="https://user-images.githubusercontent.com/1387855/235720789-7b44cad9-c44a-496e-ab60-e1f70890b910.png">

**Comment by jerckov40** [comment]
> I see, it's a bug fixed in the master branch. Try to add this to your pubspec.yaml:
> 
> ```yaml
> dependency_overrides:
>   pdf:
>     git:
>       url: https://github.com/DavBfr/dart_pdf
>       ref: master
>       path: pdf
> ```

That Solved the problem. Thank you.

**Comment by DavBfr** [comment]
Fixed.
