### ISSUE TITLE
buildBackground of PageTheme is bounded by the PageTheme's margin

### ISSUE THREAD

**Issue by edmonddc** [DavBfr/dart_pdf#1349]
**Describe the bug**
I think the background should cover the whole page without margins. If the developer wants it under the margin, he can enclosed the widget in a padding.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
      pageTheme: PageTheme(
        pageFormat: PdfPageFormat.a5,
        margin: const EdgeInsets.all(6.0 * PdfPageFormat.mm),
        buildBackground: (context) {
          return Stack(children: [
            Placeholder(),
            Watermark.text("Confidential")
          ]);
        },
      ),
```

**Expected behavior**
The background widget (in the code above, it should be the PlaceHolder widget) should cover the whole page.

**Flutter Doctor**
```
[✓] Flutter (Channel stable, 3.7.11, on Manjaro Linux 5.15.108-1-MANJARO, locale en_PH.UTF-8)
    • Flutter version 3.7.11 on channel stable at /home/edmondd/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (13 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [x] Browser
 - [ ] Windows
 - [x] Linux
 - [x] MacOS

**Comment by DavBfr** [comment]
There is a `FullPage` widget for that.

**Comment by edmonddc** [comment]
FullPage widget works!
