### ISSUE TITLE
base64

### ISSUE THREAD

**Issue by jbtjprojetos** [DavBfr/dart_pdf#1352]
can I put images that come from the database in base64 in the pdf? how do I do that?

**Comment by DavBfr** [comment]
Yes, decode the base64 and use MemoryImage

**Comment by jbtjprojetos** [comment]
![image](https://github.com/DavBfr/dart_pdf/assets/112245492/aedec84f-7570-4da4-a81d-32fecd8c7eae)

**Comment by jbtjprojetos** [comment]
this is happening ..... can you help me?

**Comment by jbtjprojetos** [comment]
the code like this...
`pw.Container(
                margin: const pw.EdgeInsets.fromLTRB(20, 0, 20, 0),
                child: pw.TableHelper.fromTextArray(
                  headerAlignment: pw.Alignment.center,
                  cellAlignment: pw.Alignment.center,
                  context: context,
                  headers: header,
                  data: data,
                ),
              ),
              pw.SizedBox(
                width: 20,
                height: 10,
              ),
              pw.Container(
                margin: const pw.EdgeInsets.fromLTRB(20, 0, 20, 0),
                child: pw.GridView(
                  crossAxisCount: 2,
                  crossAxisSpacing: 5,
                  mainAxisSpacing: 5,
                  childAspectRatio: 1,
                  children: [
                    ...imagens.map<pw.Widget>(
                      (item) {
                        print(item.imagem.toString());
                        return pw.Wrap(
                            children: [pw.Image(imagelogo, height: 100)]);
                      },
                    ),
                  ],
                ),
              ),
            ],`

**Comment by jbtjprojetos** [comment]
pw.Container(
                margin: const pw.EdgeInsets.fromLTRB(20, 0, 20, 0),
                child: pw.TableHelper.fromTextArray(
                  headerAlignment: pw.Alignment.center,
                  cellAlignment: pw.Alignment.center,
                  context: context,
                  headers: header,
                  data: data,
                ),
              ),
              pw.SizedBox(
                width: 20,
                height: 10,
              ),
              pw.Container(
                margin: const pw.EdgeInsets.fromLTRB(20, 0, 20, 0),
                child: pw.GridView(
                  crossAxisCount: 2,
                  crossAxisSpacing: 5,
                  mainAxisSpacing: 5,
                  childAspectRatio: 1,
                  children: [
                    ...imagens.map<pw.Widget>(
                      (item) {
                        print(item.imagem.toString());
                        return pw.Wrap(
                            children: [pw.Image(imagelogo, height: 100)]);
                      },
                    ),
                  ],
                ),
              ),
            ],
