### ISSUE TITLE
ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: This widget created more than 100 pages. This may be an issue in the widget or the document. See https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html

### ISSUE THREAD

**Issue by DineshJat123** [DavBfr/dart_pdf#1354]
**Describe the bug**
ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: This widget created more than 100 pages. This may be an issue in the widget or the document. See https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksbora** [comment]
Mate , you just shared an error , no code no explanation any effort to explain anything and expect from us to help you with a magic wound ? 
- Your 1 child widget bigger than the physical page, divide it part by part .

**Comment by MuhamadHaydar** [comment]
I've got the same issue with Column, my widget's height is bigger than the 1-page size, I used a multipage widget, and it throws an exception.
