### ISSUE TITLE
PDF not rendered

### ISSUE THREAD

**Issue by ckp78** [DavBfr/dart_pdf#1357]
**Describe the bug**

An existing pdf file is not rendered when using the PdfPreview widget. Instead, a blank page is displayed. The problem occurs whether the file is downloaded or made available using the assets folder.

As a workaround, we have found that the PDF will render if a` pdf.editPage()` code block is inserted, though it is unclear exactly what is needed in the content of this code block for this workaround to be effective.

**To Reproduce**

Step 1 - add the test pdf to the assets folder:

[test_example.pdf](https://github.com/DavBfr/dart_pdf/files/11364510/test_example.pdf)

Code snippet to reproduce the behavior:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf_crypto/pdf_crypto.dart';
import 'package:printing/printing.dart';

class TestDocument extends StatelessWidget {
  const TestDocument({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Title'),
      ),
      body: Center(child: PdfPreview(
        build: (format) async {
          final doc = (await rootBundle.load('assets/test_example.pdf'))
              .buffer
              .asUint8List();

          final pdf = pw.Document.load(
            PdfDocumentParser(
              doc,
            ),
          );

          return pdf.save();
        },
      )),
    );
  }
}
```

**Expected behavior**
The PDF renders.

**Actual behavior**
A blank page is displayed.

**Workaround**
Insert the following block before `return pdf.save();`
```dart
pdf.editPage(
            0,
            pw.Page(
              build: (context) => pw.Center(
                child: pw.Container(
                  width: 0,
                  height: 0,
                  color: PdfColors.amber,
                ),
              ),
            ),
          );
```

Note that this workaround fails if the Container widget is created simply via `pw.Container()`

**Flutter Doctor**

[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.2846], locale en-GB)
    • Flutter version 3.7.12 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (13 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Charlie\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.33)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    • Visual Studio Community 2017 version 15.9.28307.1401
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.19.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • HRY LX1 (mobile)  • VFFDU19321001220 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.2846]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 112.0.1722.34

[√] HTTP Host Availability
    • All required HTTP hosts are available
```
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [x] Browser
 - [untested] Windows
 - [untested] Linux

**Smartphone (please complete the following information):**
 - Devices: iPad 5th gen, Honor 10 Lite
 - OS: iOS 16.4.1, Android 10
 - Browser: Chrome

**Comment by DavBfr** [comment]
Why would you edit the file if you don't change anything on it?

You just have to return your data like this:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf_crypto/pdf_crypto.dart';
import 'package:printing/printing.dart';

class TestDocument extends StatelessWidget {
  const TestDocument({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Title'),
      ),
      body: Center(child: PdfPreview(
        build: (format) async {
          return (await rootBundle.load('assets/test_example.pdf'))
              .buffer
              .asUint8List();
        },
      )),
    );
  }
}
```

**Comment by DavBfr** [comment]
Fixed in the master branch
