### ISSUE TITLE
RenderView changed 

### ISSUE THREAD

**Issue by nkolentcev** [DavBfr/dart_pdf#1360]
**Describe the bug**
4 week ago, parameter window has changed on view in class RenderView ...flutter/lib/src/rendering/view.dart - 

 /root/.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7:
#21 57.38 Error: No named parameter with the name 'window'.
#21 57.38       window: view,
#21 57.38       ^^^^^^
#21 57.38 /usr/local/flutter/packages/flutter/lib/src/rendering/view.dart:68:3:
#21 57.38 Info: Found this candidate, but the arguments don't match.
#21 57.38   RenderView({

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [x] Windows
 - [ ] Linux

**Comment by DavBfr** [comment]
Yes, it's fixed in the master branch.

**Comment by jireh-father** [comment]
@DavBfr 
I have installed pdf 3.10.1 and printing 5.10.3. However, the same RederView error occurs. You said you fixed it in the master branch, but it hasn't been reflected in the latest version yet?

**Comment by DavBfr** [comment]
Yes, it's not published yet.

**Comment by nkolentcev** [comment]
1. Clone master branch local
2. Change one line code from window on view
3. Add path to dependecies in pubspec.yaml
ex.
 printing: 
    path: dep_packages/printing-5.10.3/
and all is work)) Thanks @DavBfr
