### ISSUE TITLE
flutter 3.10 web has the following error messages.

### ISSUE THREAD

**Issue by zhushuihua** [DavBfr/dart_pdf#1372]
TypeError: Cannot set properties of null (setting 'exports')
https://unpkg.com/pdfjs-dist@3.2.146/build/pdf.min.js 22:113  webpackUniversalModuleDefinition
https://unpkg.com/pdfjs-dist@3.2.146/build/pdf.min.js 22:294  <fn>
Error: NoSuchMethodError: '[]'
Dynamic call of null.
Receiver: null
Arguments: ["GlobalWorkerOptions"]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 813:3   defaultNoSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 807:56  noSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 283:12  callNSM
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 294:25  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 435:5   dsend
packages/printing/printing_web.dart 90:29                                         _initPlugin
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 575:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1581:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37263:58                              <fn>

**Comment by DavBfr** [comment]
Please check the master branch with:

```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf
      ref: master
      path: pdf
```

in your `pubspec.yaml`.

**Comment by zhushuihua** [comment]
Thanks, it worked. However also need to add printing dependency

**Comment by mellowcello77** [comment]
Shall we wait for a fix?
