### ISSUE TITLE
Add color property to PdfPreview class

### ISSUE THREAD

**Issue by royale1223** [DavBfr/dart_pdf#1374]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to modify the color of the PdfPreview widget bottombar.

**Describe the solution you'd like**

It would be much easier if there was a color property in the PdfPreview widget that will change the color of the bottombar.

**Comment by Solutionstbd** [comment]
Current workaround if you need this urgently is to wrap with a Theme widget and change the primaryColor field to change the bottombar background color and the primaryIconTheme.color field to change the icon colors.
```dart

final preferredBackgroundColor = Colors.black;
final iconColor = Colors.red;

  Theme(
     data:  Theme.of(context).copyWith(
         // set your background color here
         primaryColor: preferredBackgroundColor ,
         // set your icon color here
         primaryIconTheme: Theme.of(context).primaryIconTheme.copyWith(color: iconColor ) ,
      ),
      child: PdfPreview( .... ),
    )
```

**Comment by royale1223** [comment]
@Solutionstbd is there a workaround for cupertino?
