### ISSUE TITLE
Signature is not displayed in the PdfPreview

### ISSUE THREAD

**Issue by bummsa** [DavBfr/dart_pdf#1379]
**Describe the bug**

When I open a signed PDF file, we do not see the signature.

Open the same pdf file in Acrobat (Windows) or in a Browser works fine.

**Expected behavior**

Be able to see the signature image

**Screenshots**

![signed_file](https://github.com/DavBfr/dart_pdf/assets/43012414/5060475f-9366-4ef6-b235-03923da23656)

(See bottom right corner)
Here is the PDF file that I signed using the pdf_crypto library: [signed_file.pdf](https://github.com/DavBfr/dart_pdf/files/11464489/signed_file.pdf)

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [ ] Browser (not tested)
 - [x] Windows
 - [ ] Linux (not tested)

**Comment by DavBfr** [comment]
Yes, none of the desktop/mobile PDF rasterizers renders annotations. Try another PDF viewer.
