### ISSUE TITLE
Question on how to use dart_pdf with Provider plugin

### ISSUE THREAD

**Issue by Chimbi** [DavBfr/dart_pdf#138]
I am trying to connect an object that I have populated using the Provider plugin. Now I need to print it in pdf. The problem that I'm having is that the Page class (https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/widgets/document.dart) ask for a Context in the build parameter and the Provider plugin ask me for a BuildContext. The code that I use to plug the object in is: `var polizaObj = Provider.of<Object>(context);` It says context but is BuildContext. Thank you for your time.

**Comment by DavBfr** [comment]
you have to use a namespace if you mix flutter's widgets and pdf widgets:
```dart
import 'package:pdf/widgets.dart' as pw;
```
then prefix everything using pw

**Comment by Chimbi** [comment]
I try to use the namespace forcing to use BuildContext but build sends Context:
`build:
          (Context context){
                var polizaObj = Provider.of<Poliza>(fw.BuildContext);
                return Column(children: <Widget>[
                      Row(children: <Widget>[
                       //Logo Image
                        Container(`...

The problem persists since the pdf page is asking for Context and the widgets in provider find the object all way up in the Widget tree using BuildContext.

**Comment by Chimbi** [comment]
I solve the issue passing the object to Page from where I call the function that did have the BuildContext that I needed. :)
