### ISSUE TITLE
No named parameter with the name 'bytesOffset'

### ISSUE THREAD

**Issue by giovanni256** [DavBfr/dart_pdf#1382]
Hi there.
I'm using the Master branch of Flutter (v3.11.0-6.0.pre.21).

I just updated PDF plugin from 3.10.1 to 3.10.3 and it isn't working anymore giving me this error while compiling:

```
../../../AppData/Local/Pub/Cache/hosted/pub.dev/pdf-3.10.3/lib/src/pdf/raster.dart:132:7: Error: No named parameter with the name 'bytesOffset'.
      bytesOffset: pixels.offsetInBytes,
      ^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/image-4.0.15/lib/src/image/image.dart:198:3: Context: Found this candidate, but the arguments don't match.
  Image.fromBytes(
  ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
```

**Comment by WasimMemon** [comment]
You have to update image library also with this update. Put below code in pubspec.yaml

dependency_overrides:
  image: 4.0.17

**Comment by giorell** [comment]
@WasimMemon This fixed my issue, thank you.

**Comment by giovanni256** [comment]
> You have to update image library also with this update. Put below code in pubspec.yaml
> 
> dependency_overrides: image: 4.0.17

Thanks, issue resolved

**Comment by giovanni256** [comment]
> You have to update image library also with this update. Put below code in pubspec.yaml
> 
> dependency_overrides: image: 4.0.17

Thanks, issue resolved
