### ISSUE TITLE
how i can add AssetImage to BoxDecoration

### ISSUE THREAD

**Issue by MTEV** [DavBfr/dart_pdf#1383]
hi 
how i can add image  to  pw.BoxDecoration(
                    image:  pw.DecorationImage(image: pw.ImageImage(pw.AssetImage("assets/myimage.png")))
                  );

**Comment by Solutionstbd** [comment]
What able to accomplish with the following
```dart
  const assetImageLocation = 'assets/image/path.png';
  ByteData byteData = await rootBundle.load(assetImageLocation);
  final uint8List = byteData.buffer.asUint8List();
  final desiredImage = MemoryImage(uint8List);
  final decoration = BoxDecoration(image: DecorationImage(image: desiredImage));
```
I am new to this package and am not sure if there is a straight forward way to use AssetImages within the pdf package so I have been converting my asset images to ByteData as needed.
