### ISSUE TITLE
CustomPainter The Y-axis coordinates are reversed, 'drawString' How to wrap lines and set rich text

### ISSUE THREAD

**Issue by MeiYuLong** [DavBfr/dart_pdf#1385]
**### CustomPainter The Y-axis coordinates are reversed, 'drawString' How to wrap lines and set rich text;**
I have a scene, according to the Json data return, to render the label, print it.
`
{
	"id": "ib3m6boej",
	"name": "fruit",
	"type": "TextUi",
	"control": "TextControl",
	"title": "text_setting",
	"position": {
		"clientX": 3.4,
		"clientY": 57.9
	},
	"props": {
		"text": "BG",
		"align": "center",
		"fontSize": "15",
		"isBold": true,
		"isSlant": false,
		"hasUnderline": false,
		"hasDeleteline": false,
		"color": "#ffffff",
		"backgroundColor": "#000000"
	},
	"rect": {
		"width": "11.5",
		"height": "7"
	},
	"updateId": "1650282299141"
}
`

Use Rect to determine position；
I use pw.CustomPaint , eg.
`
pw.CustomPaint(
      size: PdfPoint(data.widthPx, data.heightPx),
      painter: (canvas, size) {
        canvas
          ..setColor(PdfColors.black)
          // ..fillAndStrokePath(evenOdd: true)
          ..setLineWidth(1)
          ..setLineCap(PdfLineCap.round);
        _drawText(canvas, data);
        canvas.strokePath();
      },
      foregroundPainter: (canvas, size) {
        canvas.restoreContext();
      }
    );

void _drawText(PdfGraphics canvas, PrintDrawData data) {
    final font = (data.props?.isBold ?? false) ? boldPdfFont : basePdfFont;
    final x = data.position?.clientXpx ?? 0;
    final y = data.position?.clientYpx ?? 0;
    print(data.props?.text ?? '');
    final PdfFontMetrics metrics = basePdfFont.stringMetrics(data.props?.text ?? '');
    canvas.drawString(
        basePdfFont, data.props?.fontSize ?? 14, data.props?.text ?? '', x, y);
  }
`
But the effect Y coordinate is reversed，
Now The larger the value, the higher the position.

And   'drawString' How to wrap lines and set rich text?  i can't find a way.

**Comment by DavBfr** [comment]
It's reversed compared to what? In math class a paper, you usually have your Y axis going up and X axis to the right. Adobe used the same coordinate system to do that with PDFs.


drawString can't wrap or use rich text. But you can use `Widget.measure()` and `Widget.draw()`

**Comment by MeiYuLong** [comment]
On the computer or mobile phone screen, take the upper left corner as the origin.
Does pdf CustomPaint take the lower left corner as the origin?
![image](https://github.com/DavBfr/dart_pdf/assets/20105390/58db2e70-234b-4f8d-8651-b9e5773753f9)
The same set of data is used, and the Rect is the same.

**Comment by bksbora** [comment]
You may reverse your array ?

**Comment by MeiYuLong** [comment]
> 

It is the value of the Y-axis coordinates, and has nothing to do with the array sorting

**Comment by DavBfr** [comment]
Nothing to fix here.

**Comment by WANGNEWMAN** [comment]
The pdf coordinate system looks like the one described in the following article 
[https://www.leadtools.com/help/leadtools/v18/dh/to/leadtools.topics.pdf~pdf.topics.pdfcoordinatesystem.html](url)
But after trying to draw the guesture drawing in CustomPainter, at same time,Drawing on the canvas of the current page, but I don't know how to deal with the coordinate (0,0) and the coordinate mapping relationship，such as a customer coordinate line (0,0)to(255)

an more.PdfPageFormat 595.275590551181x841.8897637795275 margins:56.69291338582677, 56.69291338582677, 56.69291338582677, 56.69291338582677
