### ISSUE TITLE
Deprecation documentation mistake

### ISSUE THREAD

**Issue by llama2all** [DavBfr/dart_pdf#1386]
**Describe the bug**
Documentation says "@Deprecated('Use TextHelper.fromTextArray() instead.')"

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Table.fromTextArray()
```
After migration to flutter 3.10.

**Expected behavior**
Correct warning is "@Deprecated('Use TableHelper.fromTextArray() instead.')"

**Comment by DavBfr** [comment]
Fixed, thanks
