### ISSUE TITLE
Underline decoration on text doesnt work

### ISSUE THREAD

**Issue by rohan-mehta** [DavBfr/dart_pdf#1389]
**Describe the bug**
When using `decoration: pw.TextDecoration.underline`, it doesn't underline the first or last word. So 
- For the string "hello world", it will only underline the space between hello and world
- For the string "hello my name is john", it will underline the words except hello and jon

**To Reproduce**

```dart
  final pdf = pw.Document();
  pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      build: (pw.Context context) {
        return pw.Center(
          child: pw.Text("Hello my name is John",
              style:
                  const pw.TextStyle(decoration: pw.TextDecoration.underline)),
        ); // Center
      }));
```

**Expected behavior**
All words should be underlined

**Tested on**
iOS phone, android phone, ios emulator

Using version ` pdf: ^3.10.3`

**Comment by DavBfr** [comment]
Introduced by #1326 / #1325

**Comment by RamiHI** [comment]
any update?

**Comment by oranageHasu** [comment]
any update?

**Comment by dibsal85** [comment]
bug is still present! (first and last word not underlined)
