### ISSUE TITLE
Table.fromTextArray is deprecated

### ISSUE THREAD

**Issue by Hachilles** [DavBfr/dart_pdf#1390]
**Describe the bug**
Documentation is misleading in VSCode editor
I can see below documentation in the vs code for deprecated method 

```
'Table.fromTextArray' is deprecated and shouldn't be used. Use TextHelper.fromTextArray() instead.
Try replacing the use of the deprecated member with the 
```

But the class TextHelper does not exists. I think it should be TableHelper instead TextHelper

**Comment by DavBfr** [comment]
Fixed.
