### ISSUE TITLE
[Web] 'decodeImage' isn't defined printing 5.10.4

### ISSUE THREAD

**Issue by Sangiovanni** [DavBfr/dart_pdf#1391]
**Describe the bug**
I Just install the plugin using "flutter pub add printing" so really basic. And then when I run my project as web, I have some issue at the compilation. 

![error-printing-flutter](https://github.com/DavBfr/dart_pdf/assets/48123595/6a0e7d1b-d247-49f9-97e8-039a5c79bc05)

**To Reproduce**
just install the last version (5.10.4) and then try to compile as web application.

**Expected behavior**
Not having this compilation error. I don't have it when I try compiling with a mobile emulator, so I guess it's only a web problem.

**Flutter Doctor**
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [version 10.0.19045.2965], locale fr-BE)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
[√] Android Studio (version 2021.3)
[!] Android Studio (version 4.1)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.78.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Desktop (please complete the following information):**
Chrome (web-javascript) 

**Additional context**
Only the pdf 3.10.3 is installed before installing this plugin.

**Comment by DavBfr** [comment]
Should be fixed with printing 5.11
