### ISSUE TITLE
pdf_widget_wrapper is failing to render animated widgets

### ISSUE THREAD

**Issue by ekuleshov** [DavBfr/dart_pdf#1392]
**Describe the bug**

The `WidgetWrapper` fail to render PDF with the following exception when child widget has some animation. Unfortunately it is not always possible to disable animation, e.g. for some 3rd party widgets.

```
The following assertion was thrown:
'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 3465 pos 12: '!debugNeedsPaint': is not true.

When the exception was thrown, this was the stack: 
#2      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:3465:12)
#3      WidgetWrapper.fromWidget (package:pdf_widget_wrapper/src/widget_wrapper.dart:204:41)
```

**To Reproduce**

At the moment I don't have an easy way to reproduce this issue in an isolated example. If it would help to fix this issue I can look at creating such example. Please let me know.

**Expected behavior**

Need some way to handle animated widgets. The `screenshot` package provides somewhat similar functionality for capturing widget images and it provides some options to handle animated widgets and "dirty" paint information. E.g. see:

https://github.com/SachinGanesh/screenshot/blob/ae826081dc7e026b19763f2a53fac9bce956e15c/lib/screenshot.dart#L173-L181

**Screenshots**

N/A

**Flutter Doctor**

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.6.1 21G217 darwin-arm64, locale en-CA)
    • Flutter version 3.7.12 on channel stable at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (5 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at ...
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] Connected device (2 available)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 113.0.5672.126
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [x] Windows
 - [x] MacOS
 - [ ] Linux

**Smartphone (please complete the following information):**
 
Chrome

**Additional context**

N/A

**Comment by ekuleshov-idexx** [comment]
Any update on this?

**Comment by ekuleshov** [comment]
Any update on this?

**Comment by DavBfr** [comment]
> Any update on this?

No one is working on that. You can fix it if it's needed, or use another way.

**Comment by ekuleshov** [comment]
It is just auto closing issues when no one is working on them is like sweeping bugs under the carpet... Very unfortunate.

Anyhow, will you accept a PR and if so, how would you prefer this issue would be addressed? Generally it will require some kind of wait until animation completes and the paint region is not being "dirty".

**Comment by DavBfr** [comment]
Yes, PRs are welcome!
I don't know what kind of widgets you plan to use. Some will animate indefinitely, so it can be until it's not dirty, with a timeout.

**Comment by ekuleshov** [comment]
Right, that is how the screenshot package handles it. In my case it is a syncfusion chart widget which doesn't have an option to disable animation for the axis labels. Have to work around that.
