### ISSUE TITLE
conflicts on using printing with flutter_esc_pos_utils 

### ISSUE THREAD

**Issue by hosamyousof** [DavBfr/dart_pdf#1393]
**Describe the bug**

I would like to use flutter_esc_pos_utils to print bitmap images loaded from the plugin image but there is a conflict on adding flutter_esc_pos_utils and flutter_esc_pos_network to pubspec.yaml

[test_printing] flutter pub get
Resolving dependencies...
Because flutter_esc_pos_utils >=0.1.6 depends on image ^3.1.3 and test_printing depends on image ^4.0.17, flutter_esc_pos_utils >=0.1.6 is forbidden.
So, because test_printing depends on flutter_esc_pos_utils ^0.1.8, version solving failed.
exit code 1

**To Reproduce**
Code snippet to reproduce the behavior:

Just add the following dependencies to pubspec.yaml

```dependencies:
  flutter:
    sdk: flutter
  printing: ^5.10.4
  image: ^4.0.17
  flutter_esc_pos_utils: ^0.1.8
  flutter_esc_pos_network: ^1.0.2
```

**Screenshots**
![image](https://github.com/DavBfr/dart_pdf/assets/16549201/65e956f2-d92b-4e87-9192-3d3b7ee9dd57)

**Flutter Doctor**

```[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Hosam\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\Hosam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • 22081283G (mobile) • 192.168.1.84:5555 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)  • windows           • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)       • chrome            • web-javascript • Google Chrome 113.0.5672.126
    • Edge (web)         • edge              • web-javascript • Microsoft Edge 113.0.1774.50

[√] Network resources
    • All expected network resources are available.
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [-] Windows
 - [ ] Linux

**Comment by DavBfr** [comment]
When you have something working, can you update the example for the Wiki page?

**Comment by hosamyousof** [comment]
@DavBfr 
I've working example and the wiki page is updated in my forked repo. 

https://github.com/hosamyousof/dart_pdf.wiki.git

Thank you,

**Comment by DavBfr** [comment]
@hosamyousof Seems to be a private repo. I get a 404

**Comment by hosamyousof** [comment]
@DavBfr the previous URL is to clone the wiki locally.

Here you can find the updated **Using another plugig** example.
https://github.com/hosamyousof/dart_pdf/wiki/Document-Output

**Comment by DavBfr** [comment]
Thanks!
