### ISSUE TITLE
Colors are wrong, items are rotated and mirrored

### ISSUE THREAD

**Issue by Zhanerkeb** [DavBfr/dart_pdf#1395]
I'm giving to text green color, however it looks like red. And all items are rotated and mirrored
<img width="339" alt="Screenshot 2023-05-24 at 18 16 45" src="https://github.com/DavBfr/dart_pdf/assets/55015545/93de79c6-8b9a-4b3b-817c-998e72711225">

**Comment by Zhanerkeb** [comment]
My code: 
 pdfItem.addPage(
      pw.Page(
        build: (context) {
          return  pw.Text('gold', style: pw.TextStyle(color: pdf.PdfColor.fromInt(0xff9ce5d0), fontSize: 50 ));
        },
      ),
    );

**Comment by DavBfr** [comment]
Can you give more context? How are you displaying your document?
The color is blueish. It's not AARRGGBB but RRGGBBAA, so your 0xff must be at the end.

**Comment by Zhanerkeb** [comment]
> 

  Future<Uint8List> _generatePdf(pdf.PdfPageFormat format) async {
    final pdfItem = pw.Document(version: pdf.PdfVersion.pdf_1_5);
    pdfItem.addPage(
      pw.Page(
        build: (context) {
          return  pw.Text('gold', style: pw.TextStyle(color: pdf.PdfColor.fromInt(0xff9ce5d0), fontSize: 50 ));
        },
      ),
    );

    return pdfItem.save();
  }
  
  PdfPreview(
                allowPrinting: false,
                allowSharing: false,
                canChangeOrientation: false,
                canChangePageFormat: false,
                actions: [],
                build: (format) => _generatePdf(format),
              )

**Comment by Zhanerkeb** [comment]
Displaying using PdfPreview

**Comment by Zhanerkeb** [comment]
also when I try to load my PDF document, some filters are applied. I will attach images. First one how it looks with your library, second one is original document
<img width="361" alt="Screenshot 2023-05-24 at 20 40 49" src="https://github.com/DavBfr/dart_pdf/assets/55015545/17df4f94-34ec-4178-b7cd-c0ce38e6761c">
<img width="378" alt="Screenshot 2023-05-24 at 20 41 13" src="https://github.com/DavBfr/dart_pdf/assets/55015545/f020ec06-8826-4df5-afc0-cbb1dfca35eb">

**Comment by Zhanerkeb** [comment]
Maybe I'm missingg smth, please, help)

**Comment by DavBfr** [comment]
Which operating system / version / device?

**Comment by Zhanerkeb** [comment]
MacOS
I am using printing package(5.10.4)
iPhone 14, Pixel 3A
