### ISSUE TITLE
 underline text

### ISSUE THREAD

**Issue by grubehome** [DavBfr/dart_pdf#142]
How to underline text in the Widget Library?

Thank you very much

**Comment by DavBfr** [comment]
This is not implemented yet.
[![Buy Me A Coffee](https://bmc-cdn.nyc3.digitaloceanspaces.com/BMC-button-images/custom_images/orange_img.png "Buy Me A Coffee")](https://www.buymeacoffee.com/JORBmbw9h "Buy Me A Coffee")

**Comment by DavBfr** [comment]
Implemented in Pdf version 1.3.21. Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
