### ISSUE TITLE
Custom page size option

### ISSUE THREAD

**Issue by indrajitsinh** [DavBfr/dart_pdf#1433]
**Is your feature request related to a problem? Please describe.**
Well right, now I can't able to generate any custom page size PDF and page size is dependent on what the Library supports like A4 and such But there should many cases where we don't want to print a few lines of Data in A4 page size, for example, receipt of supermarket bill etc..

**Describe the solution you'd like**
it should have an additional page size option like .custom(height,width) and it will generate PDF according to that size)

**Describe alternatives you've considered**
Don't have any

**Additional context**
Don't have any

**Comment by bksbora** [comment]
```dart 
 pdf.addPage(
// Page Ayarları
      pw.MultiPage(
          maxPages: 100,
          theme: pw.ThemeData.withFont(
            base: await PdfGoogleFonts.openSansRegular(),
            bold: await PdfGoogleFonts.openSansBold(),
            icons: await PdfGoogleFonts.materialIcons(), // this line
          ),
          pageFormat: PdfPageFormat(21.0 * cm, 29.7 * cm, marginAll: 0.5 * cm),,
          orientation: pw.PageOrientation.portrait,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          build: (context) {
            return FinalPDF;
          }),
    );
    ````
