### ISSUE TITLE
XCODE Member not found: 'uint8'.

### ISSUE THREAD

**Issue by febryanaep** [DavBfr/dart_pdf#1440]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/pdf-3.10.4/lib/src/pdf/raster.dart:36:36: Error: Member not found: 'uint8'.

flutter 3.10.16
PDF : 3.10.4
please help me

**Comment by MzeeAlii** [comment]
Just upgraded to Flutter 3.10.6. Getting the same bug.

**Comment by febryanaep** [comment]
solve..
sorry that's my fault

**Comment by mahmoudalaa97** [comment]
@febryanaep  can you tell me what the issue is and how you solve it, I had the same problem when I was upgrading the Flutter version

**Comment by hcaz** [comment]
I had this issue, the uint8 comes from the `image` package. Upgrading that package to a newer version in my project seems to resolve the issue.
