### ISSUE TITLE
Build fails on arm64 beacause of hardcoded target

### ISSUE THREAD

**Issue by nik012003** [DavBfr/dart_pdf#1448]
Both flutter and pdfium openly support arm64 linux targets. 
In fact, if I change [this line](https://github.com/DavBfr/dart_pdf/blob/master/printing/linux/CMakeLists.txt#L20)  to be 
```
set(PDFIUM_ARCH "arm64" CACHE STRING "Architecture of pdfium used")
```
everything compiles correctly on the linux/arm64 target.

We should add a way to change the architecture programmatically.

**Desktop:**
 - [x] Linux - arm64

**Comment by DavBfr** [comment]
You can use this in your own CmakeList.txt

```
set(PDFIUM_ARCH "arm64" CACHE STRING "Architecture of pdfium used" FORCE)
```

**Comment by nik012003** [comment]
Thanks! Woudn't it make more sense to use `FLUTTER_TARGET_PLATFORM` in dart_pdf's CmakeList.txt instead of hardcoding it?

**Comment by DavBfr** [comment]
If this variable is set to the target arch, yes absolutely.

**Comment by nik012003** [comment]
```
# Compilation setting for dart_pdf. 
# 
# This is required to download and link against the correct build of pdfium
string(REPLACE "linux-" "" TARGET_ARCH ${FLUTTER_TARGET_PLATFORM})
set(PDFIUM_ARCH ${TARGET_ARCH} CACHE STRING "Architecture of pdfium used" FORCE)
```
It does work on linux-arm64 can't test right now on x64 plaform, but it should work

**Comment by DavBfr** [comment]
If you create a PR, github-actions will test the x64 flag.
