### ISSUE TITLE
This widget created more than 20 pages. 

### ISSUE THREAD

**Issue by therealjohnsummer** [DavBfr/dart_pdf#145]
Dave - This looks like a great Flutter plugin and I'm hoping the issue below is something that is easily corrected.

I'm starting out trying use the plugin and getting an exception when I use the Paragraph widget. My text is more than an A4 page. So what I would like to know :

1) How can this library be used to automatically render text that can span **automatically** pages based on the content. I have tried to wrap the **Paragraph** widget within Column, ListView, Wrap and still get the exception.  I have content where I do not know the size and was hoping wrapping within a MultiPage would suffice. 
```

_pdf.addPage(MultiPage(
        pageFormat:
            PdfPageFormat.letter.copyWith(marginBottom: 1.5 * PdfPageFormat.cm),
        crossAxisAlignment: CrossAxisAlignment.start,
        header: (Context context) {
          return Container(
              alignment: Alignment.centerRight,
              margin: const EdgeInsets.only(bottom: 3.0 * PdfPageFormat.mm),
              padding: const EdgeInsets.only(bottom: 3.0 * PdfPageFormat.mm),
              decoration: const BoxDecoration(
                  border: BoxBorder(
                      bottom: true, width: 0.5, color: PdfColors.grey)),
              child: Text('Portable Document Format',
                  style: Theme.of(context)
                      .defaultTextStyle
                      .copyWith(color: PdfColors.grey)));
        },
        build: (context) => [
              Header(text: 'Header 1'),
              Lorem(length: 50),
              Header(text: 'Header 2'),
              
                      Paragraph(
                        text: ................... lots of text here .............
 
```
2) Are there any examples on how one can (say) draw shapes such as a rectangle bar which would (say) represent a progress bar ?

**Comment by sallymariehollywood** [comment]
Hi there David - is this specialized widget available now - can you point me to this in the API Docs ? I  have the same requirement. I need to create a PDF that can wrap onto multiple pages and needs to display customer data. One field is customer comments which can be quite long (dynamic in nature) and consequently wrap onto another page. Looking at the sample code and implementing that with some changes, I get the same error mentioned here. What is the best way to implement a MultiPage PDF when data is dynamic and driven from say List<ModelCustomerData> which needs to display both freeform fields and also a list of data for each entity ? I looked through the example code and the examples from what I can see concentrate on static Paragraph widgets which is fine when you know what you need to report on but when data is dynamic and variable length, Paragraph widget gives this error.

**Comment by DavBfr** [comment]
No, there is no such widget, but usually, people will not write a full page of text without any newline. So you can split your text and create a Paragraph for each block. This way, the text will not be too long.
See  #146 for some explanations too.

**Comment by parthvora25** [comment]
hi dav, sorry for troubling you, but let me know one thing if i want to use listview in which the pdf content will be generated automatically then how can i add code for new line, because it is creating same data repeated on other page instead of limiting it into 1 page or half content. Instead it creates 2 page with same content. How to solve this if i have dynamic content?

**Comment by DavBfr** [comment]
Can you show me some code?

**Comment by sallymariehollywood** [comment]
This sounds like an issue with your code rather than the PDF plugin. I needed to do exactly the same thing and the PDF plugin works perfectly.

**Comment by parthvora25** [comment]
pdf.Widget getPdfListTile(BuildContext context, SessionExercise exercise,
    List<PdfImage> imagesByteList, PdfDocument doc, pdf.Font pdfFont) {
  return pdf.Container(
    margin: const pdf.EdgeInsets.all(1.0 * PdfPageFormat.cm),
    child: pdf.Column(children: <pdf.Widget>[
      pdf.Row(
        mainAxisSize: pdf.MainAxisSize.max,
        mainAxisAlignment: pdf.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pdf.CrossAxisAlignment.start,
        children: <pdf.Widget>[
          pdf.Column(
            crossAxisAlignment: pdf.CrossAxisAlignment.start,
            children: <pdf.Widget>[
              pdf.Row(
                crossAxisAlignment: pdf.CrossAxisAlignment.start,
                children: <pdf.Widget>[
                  pdf.Container(
                    margin: pdf.EdgeInsets.only(top: 3),
                    decoration: pdf.BoxDecoration(
                      shape: pdf.BoxShape.circle,
                      color: PdfColors.black,
                    ),
                    width: 10,
                    height: 10,
                  ),
                  pdf.SizedBox(width: 5),
                  pdf.Paragraph(
                    text: exercise.exercise.title,
                    style: pdf.TextStyle(
                        fontWeight: pdf.FontWeight.bold, font: pdfFont),
                  ),
                ],
              ),
              pdf.Container(
                width: getSizeOf(MediaQuery.of(context).size.width),
                child: pdf.Paragraph(text: exercise.exercise.description),
              ),
              pdf.Row(
                children: <pdf.Widget>[
                  pdf.Paragraph(
                    text: 'Sets, Reps & Rest ',
                    style: pdf.TextStyle(fontWeight: pdf.FontWeight.bold),
                  ),
                  pdf.SizedBox(width: 30),
                  pdf.Paragraph(
                      text:
                          '${exercise.sets} x ${exercise.reps} x ${exercise.rest}'),
                ],
              ),
            ],
          ),
          pdf.Column(
            crossAxisAlignment: pdf.CrossAxisAlignment.end,
            children: <pdf.Widget>[
              pdf.Container(
                height: 100,
                width: 200,
                child: pdf.Image(
                  imagesByteList[0],
                ),
              ),
              imagesByteList.length > 1
                  ? pdf.SizedBox(height: getSizeOf(15))
                  : pdf.SizedBox(height: 0, width: 0),
              imagesByteList.length > 1
                  ? pdf.Container(
                      height: 100,
                      width: 200,
                      child: pdf.Image(
                        imagesByteList[1],
                      ),
                    )
                  : pdf.SizedBox(height: 0, width: 0),
            ],
          ),
        ],
      ),
      pdf.SizedBox(height: 10),
      pdf.Row(
        crossAxisAlignment: pdf.CrossAxisAlignment.start,
        children: <pdf.Widget>[
          pdf.Paragraph(
            text: 'Personal comment',
            style: pdf.TextStyle(fontWeight: pdf.FontWeight.bold),
          ),
          pdf.SizedBox(width: 30),
          pdf.Expanded(
            child: pdf.Paragraph(text: exercise.comment),
          ),
        ],
      ),
    ]),
  );
}

**Comment by parthvora25** [comment]
in some cases it is working perfectly but in some it tends to create multiple pages with data repeatation

**Comment by parthvora25** [comment]
Also i would want to know how can i support emojis in pdf i am using roboto fonts in app and i have added them in title above as  pdfFont but it doesnt support in pdf

**Comment by parthvora25** [comment]
https://github.com/DavBfr/dart_pdf/issues/48#issuecomment-520147999
also check above issue about how can i use isolates in flutter app for creating pdf on other process as you mentioned.

**Comment by DavBfr** [comment]
It doesn't support Emojis as fare as I know. But I never tested.

**Comment by DavBfr** [comment]
In your code, you mix Flutter context and Pdf context, they are not compatible. Using MediaQuery.of(context).size.width means nothing for the Pdf output, It's the width of the screen, not the width of the paper.

**Comment by parthvora25** [comment]
> In your code, you mix Flutter context and Pdf context, they are not compatible. Using MediaQuery.of(context).size.width means nothing for the Pdf output, It's the width of the screen, not the width of the paper.

ok so how can i solve this i mean what width should i provide because i am creating row with text to take 50% width and the rest 50% is for images

**Comment by DavBfr** [comment]
Use a Column widget, with some Flexible as children.
https://api.flutter.dev/flutter/widgets/Column-class.html

**Comment by parthvora25** [comment]
> Use a Column widget, with some Flexible as children.
> https://api.flutter.dev/flutter/widgets/Column-class.html

ok i got it. At that time i didnt knew about it. Now i know it will take half screens for both children in it. Thanks

**Comment by parthvora25** [comment]
hi i have tried to call it from ui button click but every time i am getting this issue.
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function 'validateSession':.)

**Comment by DavBfr** [comment]
Please look at the dart documentation: https://dart.dev/guides/language/language-tour#isolates

**Comment by yogishShenoy** [comment]
Hello mam whether you yot any solution for that ? Ecen i am facing same problem. In my prf i used dynamic table if there is less data then it will work fine when there is more data it simply doesn't render the pdf at all and it shows me an error as mentioned above.
I want my pdf to react as when ever there is increase in size of the table then it need to move to next page .....
Please can u help me in this?

**Comment by OPJP** [comment]
@DavBfr , I have a Table that has been converted from an array:  pw.Table.fromTextArray(...)
However, this normally is larger than one page so thrown this error: "This widget created more than 20 pages". The Table acts as a "PDF calendar". I tried wrapping with other widgets and hasn't worked, what would you recommend I do?

**Comment by DavBfr** [comment]
If you know you will generate more than 20 pages, you can specify it on the MultiPage object. But in all cases, this is just during development. a release application will not check the number of pages generated.

**Comment by OPJP** [comment]
Thanks so much for responding so quickly! The table itself is usually only slightly larger than one page yet the error is still thrown. I think that maybe it is treated as one widget so it tries to transfer the whole table to the next page continuously. What would be your recommendations in this situation?

> If you know you will generate more than 20 pages, you can specify it on the MultiPage object. But in all cases, this is just during development. a release application will not check the number of pages generated.

**Comment by MujibBasha** [comment]
I get the same issue "This widget created more than 20 pages."  when I use this code 
because it can not add all question inside of page
Please can u help me in this?

```
doc.addPage(
    pw.MultiPage(
      pageTheme: pageTheme,
      build: (pw.Context context) => [
        pw.Partitions(
          children: [
            pw.Partition(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: <pw.Widget>[
                  pw.Container(
                    padding: const pw.EdgeInsets.only(left: 30, bottom: 20),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: <pw.Widget>[
                       
                  _Category(title: 'Project Information'),
                           
                           // I want show list of question and answer

                  pw.ListView.builder(
                    itemCount: 15,//
                    itemBuilder: (pw.Context pwContext, index) {
                      return _Block(
                        title: Provider.of<ProviderData>(con, listen: false)
                            .ProjectInfoDocumentData[index]["question"],
                        desc: Provider.of<ProviderData>(con, listen: false)
                            .ProjectInfoDocumentData[index]["answer"],
                        icon: const pw.IconData(0xe530),
                      );
                    },
                  ),
                ],
              ),
            ),


```

**Comment by DavBfr** [comment]
You need your _Block objects to be direct children of pw.Partition

**Comment by Klabauterman** [comment]
> You need your _Block objects to be direct children of pw.Partition

Partion has only one child, how can you add multiple children? If you use container widget like a column the page break fails.

**Comment by DavBfr** [comment]
@Klabauterman You can have a Column widget as child of Partition.

**Comment by Zee604** [comment]
make chunks of your data or text.

**Comment by michhhh99** [comment]
Hi, I'm using this package to create a pdf that has more than 20 pages and its giving me this error. 
"Exception: This widget created more than 20 pages. This may be an issue in the widget or the document."

Can anyone advice on this. 

I am sure that the error is not caused by the overflow of content.
