### ISSUE TITLE
How to use networkImage and FutureBuilder

### ISSUE THREAD

**Issue by pencill-ram** [DavBfr/dart_pdf#1452]
Hi,

Is there a equivalent for FutureBuilder in this like pw.FutureBuilder?

**Comment by bksbora** [comment]
Hi,  you can fetch the image with initState and use in a builder.  Hope it helps , if not give more spesific example , i will try my best :) 
```dart
  Future getPicture(var ref2) async {
    var response = await http
        .get(Uri.parse("***************************"));

    return response.bodyBytes;
  }
``
