### ISSUE TITLE
Unable to display this document (desktop)

### ISSUE THREAD

**Issue by pedroserretti** [DavBfr/dart_pdf#1456]
**Describe the bug**
On the desktop, this message appears when I try to view the PDF, but on the web and mobile it works, how can I solve it?

**My code**
```dart
class VisualizarPdf extends StatefulWidget {
  const VisualizarPdf(
      {Key? key,
      required this.menuSelecionado,
      required this.item,
      required this.objetoFinal})
      : super(key: key);

  final MenuV12 menuSelecionado;
  final Object item;
  final Object objetoFinal;

  @override
  VisualizarPdfState createState() => VisualizarPdfState();
}

class VisualizarPdfState extends State<VisualizarPdf> {
  @override
  Widget build(BuildContext context) {
    final actions = <PdfPreviewAction>[
      if (!(kIsWeb || Platform.isWindows || Platform.isMacOS))
        const PdfPreviewAction(
          icon: Icon(Icons.save),
          onPressed: PdfApi.salvarNoPreviewPDF,
        ),
    ];
    return SafeArea(
        top: true,
        child: Scaffold(
            appBar: AppBar(
              backgroundColor: FCoresBasicas().cinzaEscuro,
              centerTitle: true,
              title: AutoSizeText(
                "PDF",
                style: context.textStyles.tLabelL
                    .copyWith(fontWeight: FontWeight.bold),
                maxLines: 2,
                minFontSize: 10,
                textAlign: TextAlign.center,
                overflow: TextOverflow.ellipsis,
              ),
              automaticallyImplyLeading: false,
              actions: [
                IconButton(
                  icon: const Icon(Icons.close_rounded),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                ),
              ],
            ),
            body: Padding(
              padding: edgeIAll0,
              child: PdfPreview(
                build: (format) => EstruturaPdf.criarPDFPreview(
                    widget.menuSelecionado,
                    widget.item,
                    context,
                    widget.objetoFinal),
                actions: actions,
                canChangeOrientation: false,
                canChangePageFormat: false,
                canDebug: false,
                maxPageWidth: 700,
              ),
            )));
  }
}
```

**Screenshots**

![issue](https://github.com/DavBfr/dart_pdf/assets/109255580/fc1849d3-6490-4c13-952b-f196e567969f)

**Flutter Doctor**

[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [versÆo 10.0.22621.1848], locale pt-BR)
    • Flutter version 3.10.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\desenvolvimento06\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33502.453
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.80.0)
    • VS Code at C:\Users\desenvolvimento06\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.67

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by pedroserretti** [comment]
closing this issue (resolved) 

i added this on my web > index.html:

```html5
<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.7.570/pdf.min.js"></script>
<script type="text/javascript">
    pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.7.570/pdf.worker.min.js";
</script>
```

**Comment by rohintoncollins** [comment]
@pedroserretti This didn't work for me. Do you have a reference?
