### ISSUE TITLE
Can we create an empty pdf/merge pdfs/split pdf in dart_pdf

### ISSUE THREAD

**Issue by insinfo** [DavBfr/dart_pdf#1462]
Hi,

pdfbox (Java tool for working with pdf documents) has functionality implemented for creating an empty pdf, splitting a pdf document and merging multiple pdf documents (tutorial links below)

1. https://www.tutorialspoint.com/pdfbox/pdfbox_creating_a_pdf_document.htm
2. https://www.tutorialspoint.com/pdfbox/pdfbox_splitting_a_pdf_document.htm
3. https://www.tutorialspoint.com/pdfbox/pdfbox_merging_multiple_pdf_documents.htm
4. https://pdfium.patagames.com/

I wanted to know if these features are available in dart_pdf and if yes, how to use them. Could you please let me know?

Thanks & Regards,

**Comment by DavBfr** [comment]
Merge is available here: https://pub.nfet.net/pdf_crypto/ splitting would be just using the merge function with one document and selecting pages.
