### ISSUE TITLE
enhancement request.

### ISSUE THREAD

**Issue by kenthinson** [DavBfr/dart_pdf#147]
Ability to get a callback from Android and iOS native print screens when the user presses cancel or print buttons.

**Comment by DavBfr** [comment]
This is not implemented. It will require native code.

**Comment by DavBfr** [comment]
Implemented in Printing version 2.1.5.

layoutPdf() returns a future with a boolean set to true if the document is printed and false if it is canceled.
It throws an exception in case of error.

Thanks for the Coffee :+1:

**Comment by kenthinson** [comment]
Thanks for the help and quick response. Great library you got going.
