### ISSUE TITLE
Page size (heigth) on paper roll80 with multiple pages

### ISSUE THREAD

**Issue by th1m0r** [DavBfr/dart_pdf#1477]
Hi,

there is any way to break page in last element when using papel roll 80mm ? when i put more then one page, the default size is a4 height.

thanks.

**Comment by bksbora** [comment]
You should look for previous solitions. => You should divide your widget. Think like its a physical object and you are forcing to fit a small box.

**Comment by th1m0r** [comment]
my solution to issue was did use a for. instead of make one document with many pages, i did call print function with one page many times.
