### ISSUE TITLE
Column inside Container with defined height does not obey size.

### ISSUE THREAD

**Issue by kenthinson** [DavBfr/dart_pdf#148]
`Container(child: Column(children: [Row(children: [Image(qrImage),Container(width: 10), Container(child: Image(warning), width: 100, height: 100)]), Text(box.name , style: TextStyle(fontSize: 30))]), decoration: BoxDecoration(border: BoxBorder(right: true, width: 1, bottom: true, left: true, top: true)), height: 150);`

The outside container should limit the inside column height to 150. However the column is filling the full height of the page.

![IMG_0045](https://user-images.githubusercontent.com/2245494/64932032-d44e9f00-d801-11e9-9793-5b39e692d935.jpg)

**Comment by DavBfr** [comment]
What do you use before this code? I can't reproduce that.
```dart
pdf.addPage(
  Page(
    build: (Context context) => Container(
        child: Column(children: <Widget>[
          Row(children: <Widget>[
            Placeholder(fallbackWidth: 100, fallbackHeight: 100),
            Container(width: 10),
            Container(child: Placeholder(), width: 100, height: 100)
          ]),
          Text('Hello', style: TextStyle(fontSize: 30))
        ]),
        decoration: const BoxDecoration(
          border: BoxBorder(
              right: true, width: 1, bottom: true, left: true, top: true),
        ),
        height: 150),
  ),
);
```

**Comment by kenthinson** [comment]
Hi it seems the behavior is a problem when the container is placed inside a GridView. My app generates a bunch of the containers and then attempts to lay them out on the page using GridView.

**Comment by kenthinson** [comment]
@DavBfr How many coffees do you need to get this one working and the other issue I opened implemented? :)

**Comment by DavBfr** [comment]
This one has the same behavior as Flutter. The Container size is ignored and forced by the GridView.
The result is different from Flutter because using Pdf, the page always have height, but on Flutter's GridView, the height is infinite.
I think you should give Wrap a try to achieve what you want to do.
https://youtu.be/z5iw2SeFx2M

For the other issue, you can give as many coffees you want, and I'll implement it.

**Comment by kenthinson** [comment]
Thanks! Got it looking the way I needed using wrap.
