### ISSUE TITLE
The app is freezing while building a pdf on web 

### ISSUE THREAD

**Issue by khaledSayedAbdellah** [DavBfr/dart_pdf#1480]
Hello,
while using the pdf lib i notices that my app freezed for secconds while i'm building my pdf.
The app is unusable while the pdf is building.

and i can't use isolate on web 
try some packages like isolate_manager but nothing works

Do you have any idea how i can dealing with this?
Thank you !

**Comment by bastulli** [comment]
Same problem here. Looking into trying to create a web service worker. I tired a package called squadron but could not get the web js worker to be seen.

**Comment by khaledSayedAbdellah** [comment]
> Same problem here. Looking into trying to create a web service worker. I tired a package called squadron but could not get the web js worker to be seen. What did work for me was not using PNGs but Jpegs and that made my pdf creation almost instant.

oh, this is very helpful
thanks, pro

**Comment by khaledSayedAbdellah** [comment]
.
