### ISSUE TITLE
1.3.21 breaks text align

### ISSUE THREAD

**Issue by jimmyff** [DavBfr/dart_pdf#149]
TextAlign is broken in 1.3.21, 

1.3.20:
<img width="545" alt="Screenshot 2019-09-17 at 17 53 53" src="https://user-images.githubusercontent.com/298850/65062607-4cd56d00-d974-11e9-9f3e-1619722a689d.png">

1.3.21:
<img width="547" alt="Screenshot 2019-09-17 at 17 53 42" src="https://user-images.githubusercontent.com/298850/65062604-4a731300-d974-11e9-97e2-1440109b3afb.png">

**Comment by DavBfr** [comment]
Yes, sorry about that, this was a bug and it's now working as Flutter's Text widget.
To Fix your rendering, use:
```dart
Align(alignment: Alignment.centerRight, child:Text('Hello'))
```
