### ISSUE TITLE
New lines are not correctly processed by `Text` and `TextSpan` widgets

### ISSUE THREAD

**Issue by bambinoua** [DavBfr/dart_pdf#1495]
If I create a widget
```dart
Text('1st line\n\n\n2nd line);
```
I expect to see the **2nd line** which follows **1st line** after 3 line feeds. But it is not so. I see only single new line.

**Comment by 007AnupamSharma** [comment]
@bambinoua I can fix this, please assign me this task

**Comment by DavBfr** [comment]
Fixed in pdf 3.10.7
