### ISSUE TITLE
How to use image from assets?

### ISSUE THREAD

**Issue by aureliopetrone** [DavBfr/dart_pdf#15]
Hi, i don't understand how i can print image loaded from Flutter assets.

That's my code, the only thing i get is:

> Exception has occurred.
> RangeError (index): Index out of range: index should be less than 15107: 15108

```
 Future<PDFDocument> _generateDocument() async{
    final pdf = new PDFDocument(deflate: zlib.encode);
    final page = new PDFPage(pdf, pageFormat: PDFPageFormat.A4);
    final g = page.getGraphics();
    final font = new PDFFont(pdf);
    final top = page.pageFormat.height;

    ByteData data = await rootBundle.load('assets/images/back.png');

    
    PDFImage image = new PDFImage(
      pdf,
      image: data.buffer.asUint8List(),
      width: 86,
      height: 80);
    g.drawImage(image, 100.0, 100.0, 86.0);
    


    g.setColor(new PDFColor(0.3, 0.3, 0.3));
    g.drawString(font, 12.0, "Qui verranno i dati del PDF!", 10.0 * PDFPageFormat.MM,
        top - 20.0 * PDFPageFormat.MM);
    g.drawString(font, 12.0, "Qui verranno i dati del PDF!", 10.0 * PDFPageFormat.MM,
        top - 30.0 * PDFPageFormat.MM);
    g.drawString(font, 12.0, "Qui verranno i dati del PDF!", 10.0 * PDFPageFormat.MM,
        top - 40.0 * PDFPageFormat.MM);
    g.drawString(font, 12.0, "Qui verranno i dati del PDF!", 10.0 * PDFPageFormat.MM,
        top - 50.0 * PDFPageFormat.MM);

    return pdf;
  }
  void _printPdf() async{
    final pdf = await _generateDocument();

    print(pdf);
    Printing.printPdf(document: pdf);
  }
```

**Comment by DavBfr** [comment]
You need to first decode the png to RGBA pixel data.
Use https://docs.flutter.io/flutter/dart-ui/Image/toByteData.html for that
or the Image library: https://pub.dartlang.org/packages/image

**Comment by aureliopetrone** [comment]
Isn't this already bytedata?

`ByteData data = await rootBundle.load('assets/images/back.png');`

**Comment by DavBfr** [comment]
ByteData here is the image encoded in PNG: compressed. The pdf library needs uncompressed pixels

**Comment by aureliopetrone** [comment]
Thank you very much, i solved in this way

 ByteData data = await rootBundle.load('assets/images/back.png');

    var codec = await instantiateImageCodec ( data.buffer.asUint8List() );
    var frame = await codec.getNextFrame();

    var imageBytes = await frame.image.toByteData();


    
    PDFImage image = new PDFImage(
      pdf,
      image: imageBytes.buffer.asUint8List(),
      width: 86,
      height: 80);
    g.drawImage(image, 100.0, 100.0, 86.0);

**Comment by GautamChibde** [comment]
> Thank you very much, i solved it this way
> 
> ```
> ByteData data = await rootBundle.load('assets/images/back.png');
> 
>    var codec = await instantiateImageCodec ( data.buffer.asUint8List() );
>    var frame = await codec.getNextFrame();
> 
>    var imageBytes = await frame.image.toByteData();
> 
> 
>    
>    PDFImage image = new PDFImage(
>      pdf,
>      image: imageBytes.buffer.asUint8List(),
>      width: 86,
>      height: 80);
>    g.drawImage(image, 100.0, 100.0, 86.0);
> ```

@aureliopetrone can you provide the function `instantiateImageCodec `?

**Comment by jeanadam** [comment]
> 
> 
> > Thank you very much, i solved it this way
> > ```
> > ByteData data = await rootBundle.load('assets/images/back.png');
> > 
> >    var codec = await instantiateImageCodec ( data.buffer.asUint8List() );
> >    var frame = await codec.getNextFrame();
> > 
> >    var imageBytes = await frame.image.toByteData();
> > 
> > 
> >    
> >    PDFImage image = new PDFImage(
> >      pdf,
> >      image: imageBytes.buffer.asUint8List(),
> >      width: 86,
> >      height: 80);
> >    g.drawImage(image, 100.0, 100.0, 86.0);
> > ```
> 
> @aureliopetrone can you provide the function `instantiateImageCodec `?
it is from a package, import 'dart:ui';
