### ISSUE TITLE
Rendering a PDF Image in a circle fails when BoxFit.Contain used

### ISSUE THREAD

**Issue by sallymariehollywood** [DavBfr/dart_pdf#150]
Trying to render an image within a circle works successfully when using the default BoxFit.cover for the DecorationImage class - however, if we change this to **BoxFit.Contain** as in :

```
Container(
        height: 300,
        width: 300,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          image: DecorationImage(image: _myPhoto, fit: BoxFit.contain),
        ),
),
);
```

We no longer get a circle.

**Using BoxFit.Cover**

![image](https://user-images.githubusercontent.com/54941250/65139609-d92f7080-da04-11e9-81c5-c5abe0bf6525.png)

**Using BoxFit.Contain**
![image](https://user-images.githubusercontent.com/54941250/65139587-d2a0f900-da04-11e9-9ed7-304942743569.png)

**Comment by DavBfr** [comment]
This looks perfectly normal for me. The image is contained as this is the full width of the image.
Do you have the same result using Flutter?

**Comment by sallymariehollywood** [comment]
No - flutter works as intended. Here is a screen shot of the same picture in the app : 

![image](https://user-images.githubusercontent.com/54941250/65140784-31677200-da07-11e9-81f8-c35938d205f1.png)

![image](https://user-images.githubusercontent.com/54941250/65140984-a3d85200-da07-11e9-9f2b-7ebd6ed07db1.png)

Both of these images use BoxFit.Contain - compared to the first image which uses BoxFit.cover, with these images we can see more detail of the animals , nose, eyes, ears etc - also , we get a perfect circle , not clipped on the sides.

**Comment by DavBfr** [comment]
I think it's a bug in Flutter! For the same result use `BoxFit.fill`, but the images will be stretched. `BoxFit.cover` would be the best solution.

**Comment by sallymariehollywood** [comment]
You've gone to the trouble of writing that quick snippet that shows all the possible fit strategies, thats very kind of you. I agree , I was certain we were using BoxFit.contain but my bad, your right, we were using Boxfit.fill. Will change to cover. 

Thank you.

**Comment by DavBfr** [comment]
No worries. 
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
