### ISSUE TITLE
Dotted border widget

### ISSUE THREAD

**Issue by CoderNamedHendrick** [DavBfr/dart_pdf#1522]
Dotted borders are commonplace in lots of PDFs and I believe it is a widget that should ship with the package.

At my current workplace, I've written an implementation for dotted borders whose code is heavily inspired by a [package](https://pub.dev/packages/dotted_border) of the same name. This should fit nicely with the rest of the package's widgets.

My [answer](https://stackoverflow.com/a/77169748/15178119) on StackOverflow shows an example.

I would very much like to make a PR ensuring this widget comes shipped with dart_pdf

**Comment by CoderNamedHendrick** [comment]
@DavBfr can this be assigned to me? Thanks in advance for the quick reply

**Comment by DavBfr** [comment]
There is already some dashed border support, backed by a PDF feature.

It's implemented in BorderStyle.

Can you check if it's enough?
Otherwise you're welcome to create a PR.

**Comment by CoderNamedHendrick** [comment]
The dashed borderstyle is enough, unfortunately, I didn't notice that before.
I'll be closing the PR now, thanks for the quick reply.
