### ISSUE TITLE
Printing documents directly causes a freeze on iOS13

### ISSUE THREAD

**Issue by Kaktusbaum** [DavBfr/dart_pdf#153]
**Describe the bug**
If you want to print a document directly on iOS13, the screen freezes. It's possible, that the freeze was caused by this line: https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/src/printing.dart#L65

The freeze does not occur on iOS12 or on Android 9. 

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  Future<void> printPDF(String pdfurl) async {
      var request = await client.getUrl(Uri.parse(url + pdfurl));
      var response = await request.close();
      Uint8List bytes = await consolidateHttpClientResponseBytes(response);
      await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => bytes);
  }

```

**Expected behavior**
The screen freezes.

**Screenshots**
![ios13-printing-freeze](https://user-images.githubusercontent.com/16017838/65451512-9d027280-de3f-11e9-9d3a-5c38416e002b.png)

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    en-DE)
    • Flutter version 1.9.1+hotfix.2 at
      /Users/xxxxxxxxxx/development/tools/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxxxxxxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxxxxxxxxx/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 6EDCBACF-6ECB-461C-8362-A8A3CFC8983F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Desktop (please complete the following information):**
 - [X ] iOS
 - [ ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max Simulator
 - OS: iOS13

**Additional context**
Works on Android 9 and iOS12, but not on iOS13

**Comment by DavBfr** [comment]
Ok, same issue. It's because iOS 13 can no longer do background printing using a thread.
Not sure this can be fixed. It would require a big change in flutter's platform plugins to be able to handle the messages in a separate thread.

**Comment by DavBfr** [comment]
Printing version 2.1.7 has a workaround, but you will have to guess the paper size before printing.

**Comment by Kaktusbaum** [comment]
> Printing version 2.1.7 has a workaround, but you will have to guess the paper size before printing.

Thanks a lot. Could you please give us an example how to use the workaround? Because now I get a **MissingPluginException(No implementation found for method printPdf on channel printing)** error, when I want to use sharePdf and printPdf (on iOS12/iOS13) with 2.1.7. 
sharePdf works again, if you downgrade to 2.1.6 (on iOS12/iOS13).

**Comment by DavBfr** [comment]
I think you have to clean your project first.

**Comment by allanwolski** [comment]
Same issue here:

**MissingPluginException(No implementation found for method printPdf on channel printing)**

**Comment by DavBfr** [comment]
Fixed in Printing 2.1.8, that was a configuration change for flutter master (1.10.5+) not compatible with flutter stable (1.9.1)

**Comment by DavBfr** [comment]
Is it all good?

**Comment by Kaktusbaum** [comment]
Yeah, it works like a charm. Thanks a lot.
