### ISSUE TITLE
Dont Draw AnnotationPolygon

### ISSUE THREAD

**Issue by FeofanGreek** [DavBfr/dart_pdf#1534]
No matter how many options you have searched, AnnotationPolygon is not displayed
All other annotation types are displayed, but the polygon is not.

Here is an example of my code:
pdf.addPage(
          pw.Page(
              pageFormat: PdfPageFormat.a4,
              build: (pw.Context context) {
                return pw.Stack(
                  children: [

                    pw.Center(
                      child: pw.Image(image),
                    ),
                    pw.Annotation(
                      child: pw.Container(
                          //color: PdfColors.red,
                          width: 300,
                          height: 300
                      ),
                     builder: pw.AnnotationPolygon(
                      
                           [
                             PdfPoint(10, 120),
                             PdfPoint(10, 120),
                             PdfPoint(20, 220),
                             PdfPoint(20, 220),
                           ],
                          color: PdfColors.black ,
                           interiorColor: PdfColors.red,
                          border: PdfBorder(PdfDocument(), 20),
                           author: 'sdhkshfjkdsjhf sdfjh',
                           date: DateTime.now(),
                           subject: 'dsfkjghsjkdhg sdgkj dfkjh dfgkj hdfgkdfjghdf dfhgfd',
                           content: 'sdfjh sdfhjg jsdfg jdshga gjdsgjhagfjhds gfdsjhfg jdshfg jdfgsj sdgjhf dsfg'
                      ),
                    )
                  ]
                ); // Center
              }));

**Comment by bksbora** [comment]
Brother , i am sorry i couldn't find any example of AnnotationPolygon to look at it . Can you explain what you want to do with it . We may find another way to do it :)

**Comment by FeofanGreek** [comment]
i am find way to draw it

prepare page, and i have list with annotations

 final pdf = pw.Document();
    for(int i = 0; i < bytes.length; i++){
      final image = pw.MemoryImage(bytes[i]);
      pdf.addPage(
          pw.Page(
            margin: const pw.EdgeInsets.fromLTRB(0,0,0,0),
              pageFormat: PdfPageFormat.a4,
              build: (pw.Context context) {
                return pw.Stack(
                  children: [

                    pw.Center(
                      child: pw.Image(image),
                    ),
                    ...annotations!.where((el) => el.page == i).toList().map((e) => e.child).toList()
                  ]
                ); // Center
              }));
    }

then add selected type of annotation using switch

 switch(annotationType){
      case AnnotationType.polygonAnnotation : {
        result = pw.PolygonAnnotation(
            points: points ?? [],
            color: color,
            interiorColor: interiorColor,
            border: border,
            author: author,
            date: date,
            subject: subject,
            content: content
        );
        break;
      }
      case AnnotationType.polyLineAnnotation : {
        result = pw.PolyLineAnnotation(
            points: points ?? [],
            color: color,
            //border: border,
            author: author,
            date: date,
            subject: subject,
            content: content
        );
        break;
      }
      case AnnotationType.inkAnnotation : {
        result = pw.InkAnnotation(
            points: pointsInk ?? [],
            color: color,
            border: border,
            author: author,
            date: date,
            subject: subject,
            content: content
        );
        break;
      }
      case AnnotationType.annotationUrl : {

        result = pw.Positioned(
            left: left,
            top: top,
            child: pw.Annotation(
                child: pw.Container(
                    width: width,
                    height: height
                ),
                builder: pw.AnnotationUrl(content ?? '')

            )
        );
        break;
      }
      case AnnotationType.annotationTextField : {

        result = pw.Positioned(
            left: left,
            top: top,
            child: pw.Annotation(
                child: pw.Container(
                    width: width,
                    height: height
                ),
                builder: pw.AnnotationTextField(
                  name: 'Annotation$page',
                  border: PdfBorder(PdfDocument(), 2),
                  flags: {PdfAnnotFlags.readOnly} ,
                  date: DateTime.now(),
                  subject: subject,
                  author: author,
                  color: color,
                  backgroundColor: interiorColor,
                  highlighting: PdfAnnotHighlighting.push,
                  maxLength: 100,
                  //alternateName: 'Anno',
                  //mappingName: '',
                  //fieldFlags: ,
                  value: subject,
                  //defaultValue: '',
                  //textStyle:
              )
            )
        );
        break;
      }
    }

and vuola! :-)

**Comment by FeofanGreek** [comment]
I think we can close it issuse
