### ISSUE TITLE
Why is generating of PDF with 17 PNG images so slow?

### ISSUE THREAD

**Issue by bambinoua** [DavBfr/dart_pdf#1535]
I create a report for web which contains 17 images. One image is ~90Kb and each one from 16tis ~30Kb.
So I use the simple code:
```dart
for(final image in images)
  MultiPage(
    pageTheme: pageTheme,
    build: (context) {
      return [
        Text(image.title),
        Center(
          child: Image(
            MemoryImage(
              image.bytes, 
              alignment: Alignment.topCenter,
              width: pageFormat.availableWidth,
            ),
          ),
        ),
      ];
    },
    footer: (context) => _getFooter(),
  ),
```

The generation is extremely slow! It takes 2 minutes and 17 seconds! Is there any idea how to fix this? I am not sure that generating of PDF can be so slow.

**Comment by DavBfr** [comment]
The PDFs don't support PNG images directly so they have to be converted to a format it understands: it's slow to convert and the compression is less efficient.
On the other hand, it supports JPEG images directly. So you can pass it jpeg images: there is no conversion so you keep the size and speed.

**Comment by bambinoua** [comment]
The challenge is I create a PDF from images which are captured from widgets wrapped `RepaintBoundary` but it allows to store only `PNG`.
