### ISSUE TITLE
Hyphenation

### ISSUE THREAD

**Issue by ilaurillard** [DavBfr/dart_pdf#1560]
Would it be possible to support "soft-hyphenation" symbols (\u00AD) in text output line calculations?

So we might include an external library to hyphenate texts and have automatic word/syllable hyphenation.

**Comment by ilaurillard** [comment]
thank you @DavBfr , you merged my PR, so we have support for hyphenation.
If anybody is interested, please contact me for an example ..

**Comment by richard457** [comment]
@ilaurillard may you kindly share example on how you achieved this?
