### ISSUE TITLE
Method pickPrinter() won't work

### ISSUE THREAD

**Issue by ChinaskiJr** [DavBfr/dart_pdf#158]
**Describe the bug**
On Android.
Unhandled Exception: MissingPluginException(No implementation found for method pickPrinter on channel printing)
When I call method 'pickPrinter()' in order to open UI and let the user chose a printer one for all. After that I would like to save the printer in memory and use Printing.directPrintPdf()

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
        Printer printer = await Printing.pickPrinter();
        Printing.directPrintPdf(
          printer: printer,
          onLayout: (PdfPageFormat format) async => bytes
        );
```

**Expected behavior**
I would like the UI printer's picking page to open

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/robin-colombier/dev/flutter
    • Framework revision 2d2a1ffec9 (il y a 4 semaines), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/robin-colombier/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/78/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/78/android-studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • TC25                      • 19198521404469 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [X] Android
 - [ ] Browser

**Smartphone (please complete the following information):**
 - Device: [Zebra TC25]
 - OS: [Android 8.1]
 - Version [API 27]

Thank you very much for answering

**Comment by DavBfr** [comment]
This is expected because the Android SDK does not provide a direct print feature like iOS.

**Comment by ChinaskiJr** [comment]
Thank you for your quick answer. 
My bad ! I'm brand new with Android development, sorry for disturbance.

**Comment by jonathantribouharet** [comment]
@DavBfr You should at least indicate it in the documentation of the method and maybe just return `false` so it would crash.
