### ISSUE TITLE
How to fetch and set image from asset or file path for printing document from html?

### ISSUE THREAD

**Issue by fldvlpr** [DavBfr/dart_pdf#1585]
Hi @DavBfr  

Thanks for this maintaining this useful package. It is working great. But, I also need help for one of my app use case on this.

I was writing my app to print a document using this package.

Following is my code,
```
static Future<void> printAppointmentPrescription() async {
    await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
            html: htmlContent, format: format));
  }
```

Here html content is a valid html value and inside there I want to add an image from asset or file path from device.

`<img src="assets/img/profile.png" style="height: 75px" />`

Any work around on this?

**Comment by DavBfr** [comment]
Don't use convertHtml. Write your own code or use the package [HTMLtoPDFWidgets](https://pub.dev/packages/htmltopdfwidgets)
