### ISSUE TITLE
No named parameter with the name 'size'   Build process failed on windows

### ISSUE THREAD

**Issue by walulyafrancis** [DavBfr/dart_pdf#1593]
I have tried to build windows app using version 5.11.1 but i keep geting this error 
which appears to be caused by a breaking change in flutter version 3.19.0.5-5.0.pre.45 according to issue #141562 at https://github.com/flutter/flutter/issues/141562 from RenderView ViewConfiguration(), parameter 'size ' is missing from the constructor and it has been replaced with 
 `final renderView = RenderView(
      view: lastView,
      child: RenderPositionedBox(alignment: Alignment.center, child: repaintBoundary),
      configuration: ViewConfiguration(
        physicalConstraints: BoxConstraints.tight(logicalSize) * lastView.devicePixelRatio,
        logicalConstraints: BoxConstraints.tight(logicalSize),
        devicePixelRatio: lastView.devicePixelRatio,
      ),
    );`

or 

```
ViewConfiguration(
          constraints: ui.ViewConstraints.tight(Size(
              computedConstraints.maxWidth, computedConstraints.maxHeight)),
          devicePixelRatio: view.devicePixelRatio)
```

in my case since am using Flutter version 3.18.0-7.0.pre.59 on channel master , i tried changing that from cache and it worked 
Here is my error message
```

../../../../AppData/Local/Pub/Cache/hosted/pub.dev/printing-5.11.1/lib/src/widget_wrapper.dart(173,11): error GC6690633: No named parameter with the name 'size'. [C:\Users\HP\OneDrive\Documents\FlutterDev\demo_printer\build\windows\x64\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Users\HP\OneDrive\Documents\FlutterDev\demo_printer\build\windows\x64\CMakeFiles\27c20b21665d2e6f7756a89c0f630592\flutter_windows.dll.rule;C:\Users\HP\OneDrive\Documents\FlutterDev\demo_printer\build\windows\x64\CMakeFiles\38aaa44b608238b8a857ab86b5171a1a\flutter_assemble.rule' exited with code 1. [C:\Users\HP\OneDrive\Documents\FlutterDev\demo_printer\build\windows\x64\flutter\flutter_assemble.vcxproj]
Error: Build process failed.
```

here is my flutter doctor -v

[√] Flutter (Channel master, 3.18.0-7.0.pre.59, on Microsoft Windows [Version 10.0.22621.3007], locale en-UG)
    • Flutter version 3.18.0-7.0.pre.59 on channel master at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9ae39df67 (8 weeks ago), 2023-12-11 01:17:19 -0500
    • Engine revision 7eb6b7cab6
    • Dart version 3.3.0 (build 3.3.0-215.0.dev)
    • DevTools version 2.30.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.86.0)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.83.20240201

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.98

[√] Network resources
    • All expected network resources are available.

**Comment by Keatr0n** [comment]
+1

**Comment by DavBfr** [comment]
Please use the stable version of Flutter.

**Comment by Keatr0n** [comment]
I do.
Flutter 3.22.1 • channel stable

**Comment by plokko** [comment]
I can confirm the bug:
a Flutter downgrade from Flutter (Channel stable, 3.22.2, on Microsoft Windows [Versione 10.0.22631.3737], locale it-IT) to v3.19.6 did fix the issue but please do fix compatibility issue with the latest stable Flutter version.

**Comment by DavBfr** [comment]
Run a `flutter clean` and `flutter pub upgrade` to fix the issue.

**Comment by plokko** [comment]
> Run a `flutter clean` and `flutter pub upgrade` to fix the issue.

Already tried multiple `flutter clean`, `dart pub clean` and `flutter pub upgrade` but did not solve the issue.
I tried upgrading again to Flutter v3.22.2, run `flutter clean` and `dart pub upgrade` and got the same error:
```
../../AppData/Local/Pub/Cache/hosted/pub.dev/pdf_widget_wrapper-1.0.3/lib/src/widget_wrapper.dart:173:11: Error: No named parameter with the name 'size'.
          size: Size(
          ^^^^
/C:/lib/flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
```

**Comment by SittiphanSittisak** [comment]
> Run a `flutter clean` and `flutter pub upgrade` to fix the issue.

My error is gone but when I run my app with Chrome, this Chrome always freezes with the splash screen.
The console always be like this.
```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
```

**Comment by Guilherme-ctrl** [comment]
Any solutions yet?

**Comment by conormvickers** [comment]
No promises but after fiddling with flutter cleans and pub gets 
`flutter pub upgrade` finally updated 
`> pdf_widget_wrapper 1.0.4 (was 1.0.3)`

This particular error went away, hope that helps someone (building for android on windows machine)

**Comment by motazKhogali** [comment]
I had the same issue 
thank to @conormvickers  comment I figure out I solution by 


```
dependency_overrides:

  pdf_widget_wrapper: ^1.0.4
```
hope that helps someone 

my issue log is slitty different in MAC OS , after upgrading flutter from 3.16.0 to 3.22.2
`Error (Xcode): ../../.pub-cache/hosted/pub.dev/pdf_widget_wrapper-1.0.1/lib/src/widget_wrapper.dart:173:11: Error: No named parameter with the name 'size'.`

**Comment by ling350181** [comment]
> No promises but after fiddling with flutter cleans and pub gets `flutter pub upgrade` finally updated `> pdf_widget_wrapper 1.0.4 (was 1.0.3)`
> 
> This particular error went away, hope that helps someone (building for android on windows machine)

it works for me.Thanks

**Comment by JaredEzz** [comment]
A single `flutter clean` and `flutter pub upgrade` worked for me. I did not need to downgrade flutter. Was having the same issues building to Windows with `Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)`

**Comment by exajai** [comment]
> A single `flutter clean` and `flutter pub upgrade` worked for me. I did not need to downgrade flutter. Was having the same issues building to Windows with `Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)`

This solution worked for me as well thank you @JaredEzz

**Comment by cantomris** [comment]
In my case this error occured beacuse of the printing package.
I upgraded it but no luck, then I went into `External Libraries / Flutter Plugins / printing / pubspec.yaml` and manually change the `pdf_widget_wrapper >=1.0.0 <2.0.0` to `1.0.4`

That worked for me.

**Comment by IbrahimHasan93** [comment]
simply update the printing: ^5.11.0 to printing: ^5.13.1 with flutter pub upgrade
