### ISSUE TITLE
Is it possible to implement an page index for PDF?

### ISSUE THREAD

**Issue by bambinoua** [DavBfr/dart_pdf#1598]
I have a PDF in which I would like to have an index page.

```
Brief ....................... 1
Tables ...................... 2
....
Charts ...................... 10
...
```
Is it possible to do this somehow?

**Comment by bambinoua** [comment]
I've found the widget `TableOfContents()` and I've added it into my project as:
```dart
Page(
  pageTheme: ...
  build: (context) => Column(
    children: [
      Text('Index'),
      SizedBox(height: 30),
      TableOfContent(),
    ],
  ),
)
```

but it is not shown.

**Comment by DavBfr** [comment]
Yes, you need to provide titles.
Check this example: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_toc_test.dart
