### ISSUE TITLE
Reading PDF

### ISSUE THREAD

**Issue by lastant** [DavBfr/dart_pdf#16]
How about the other way around, opening the PDF? Even the plain text alone would be great for a start!

**Comment by DavBfr** [comment]
That is not planned for now

**Comment by MichalMisiaszek** [comment]
I am using another plugin to show created PDF, for most cases it works fine:
https://github.com/CrossPT/flutter_plugin_pdf_viewer/

**Comment by DavBfr** [comment]
Ok, I close it then.

**Comment by lastant** [comment]
But the issue is not about displaying the PDF, it's about parsing its content.

**Comment by DavBfr** [comment]
That is not planned for now
