### ISSUE TITLE
Widgets Doc 

### ISSUE THREAD

**Issue by salime45** [DavBfr/dart_pdf#160]
I dont see the widgets documentation. There are any page for ?

**Comment by DavBfr** [comment]
Yes, it's the same as flutter's layout widgets, you can use flutter documentation.

**Comment by DavBfr** [comment]
You can use any widget implemented by the Pdf Library.
You can use `pdfImageFromImageProvider` to load an image from an asset.

**Comment by salime45** [comment]
Thanks
