### ISSUE TITLE
Upgrade to js ^0.7.0

### ISSUE THREAD

**Issue by Aerofluxx** [DavBfr/dart_pdf#1602]
**Describe the bug**
Other packages using a newer version of the [official js](https://pub.dev/packages/js) package will not have a good time together. Can we maybe get an update to the printing package?

Because no versions of printing match >5.11.1 <6.0.0 and printing 5.11.1 depends on js ^0.6.3, printing ^5.11.1 requires js ^0.6.3.
And because pdfrx >=0.4.11 depends on js ^0.7.0, printing ^5.11.1 is incompatible with pdfrx >=0.4.11.
So, because bestellcenter depends on both pdfrx ^1.0.3 and printing ^5.11.1, version solving failed.

**To Reproduce**
Code snippet to reproduce the behavior:
Using this two packages in pubspec.yaml
```dart
  pdfrx: ^1.0.3
  printing: ^5.11.1
```

Thanks!

**Comment by asaarnak** [comment]
Because wakelock_plus >=1.1.5 depends on js ^0.7.0 and printing 5.11.1 depends on js ^0.6.3, wakelock_plus >=1.1.5 is incompatible with printing 5.11.1.

**Comment by ivanzhadnov** [comment]
i'm also need to update JS packege

**Comment by DavBfr** [comment]
Done.

**Comment by Aerofluxx** [comment]
Thank you so much for your support!!
