### ISSUE TITLE
Long `RichText` data is not spawned to the next page

### ISSUE THREAD

**Issue by MacDeveloper1** [DavBfr/dart_pdf#1606]
I have this PDF widget:
```dart
MultiPage(
  pageTheme: pageTheme,
  build: (context) => [
    Text(
      t.securityPolygon.capitalizeWords(),
      style: context.theme.header1,
    ),
    _verticalGap30px,
    Image(
      MemoryImage(_image),
      fit: BoxFit.contain,
      alignment: Alignment.topCenter,
      width: pageFormat.availableWidth,
      height: pageFormat.availableHeight,
    ),
    _verticalGap15px,
    if (_polygon.notes.isNotEmpty)
    RichText(                  // <----------------- Rich text contains long text which overflows the page
      text: spans.isNotEmpty
          ? TextSpan(children: spans)
          : const TextSpan(text: ''),
      softWrap: true,
    ),
  ],
  footer: _getFooter,
),
```

On PDF generation I got this error
> Exception: Widget won't fit into the page as its height (812.6953125) exceed a page height
> (796.535433070866). You probably need a SpanningWidget or use a single page layout

How to avoid this exception if I already used the `SpanningWidget`.

P.S. What does the _single page layout_ means? Using of `Page` intead of `MultiPage`? If so how does it help?

**Comment by DavBfr** [comment]
Just add `overflow: TextOverflow.span` to your RichText

**Comment by MacDeveloper1** [comment]
> Just add `overflow: TextOverflow.span` to your RichText

Just revealed out it myselft and wanted to close this issue :)
