### ISSUE TITLE
Merge PDF in Premium Version

### ISSUE THREAD

**Issue by markbreuss** [DavBfr/dart_pdf#1630]
I need to merge two pdf files.

I am aware that this is only possible in the premium version (for wich 250 USD is completly reasonable)

My question is if its possible to merge pdfs in a web environment or in a pure dart environment (server side)?

**Comment by DavBfr** [comment]
Yes, the premium library is 100% pure Dart with no dependency on Flutter.

**Comment by markbreuss** [comment]
Nice - thanks for the quick response!
