### ISSUE TITLE
Bangla text Rendering issue. 

### ISSUE THREAD

**Issue by helper-bud** [DavBfr/dart_pdf#1639]
getting this bangla text. 
![Screenshot 2024-03-30 112609](https://github.com/DavBfr/dart_pdf/assets/96073081/fd93d1fa-eed4-470f-bf53-50ec26ef6e08)
want this  bangla text. 
![Screenshot 2024-03-30 144903](https://github.com/DavBfr/dart_pdf/assets/96073081/a77b653b-fe5c-435e-a915-79d2dd418699)

when i am copying from the generated pdf, and pasting some where else the text gets right. 

code : 
final pdf = pw.Document();
    var logger = Logger();

    final banglaFont =
        await rootBundle.load("assets/fonts/AnekBangla/kalpurush.ttf");
    final banglaFontTtf = pw.Font.ttf(banglaFont);

pw.Table(
                border: pw.TableBorder.all(),
                children: [
                  pw.TableRow(
pw.Text("${innerLoop.groupid} - ${innerLoop.grpnam}",
                            style: pw.TextStyle(
                              font: banglaFontTtf,
                              fontSize: 6,
                            ),
                            textAlign: pw.TextAlign.center,
                            maxLines: 1),
                            )
                            ]
                            
)

**Comment by bksbora** [comment]
Kemon acho vai ,it seems same to me :D I don't know the solution i just wanted to say hi !

**Comment by bksbora** [comment]
Oh you should look at this, i guess for Bangla help needed. #219

**Comment by Tarikul-Islam-Shykat** [comment]
solved it.  using unicode to bijoy.
suppose this is the text : 
**innerLoop.grpnam.toString()**
in this code : 

pw.Text(
                            "${innerLoop.groupid} - ${CodeUtil.unicodeToBijoyText(innerLoop.grpnam.toString())}",
                            style: pw.TextStyle(
                              font: banglaFontTtf,
                              fontSize: 6,
                            )
                        
      
       static String unicodeToBijoyText(String text) {
    return unicodeToBijoy(utf8.decode(utf8.encode(text)));
  }

**Comment by Tarikul-Islam-Shykat** [comment]
i found that solution by on the day when i found it. 
but posting it hope it helps.

**Comment by joy2012bd** [comment]
> unicodeToBijoy

How to use this? Any example will be helpful.

**Comment by helper-bud** [comment]
I already showed my approach to solve it. You can check above.

**Comment by joy2012bd** [comment]
> I already showed my approach to solve it. You can check above.

I already fixed it another way. Thanks for your quick response.

**Comment by Tarikul-Islam-Shykat** [comment]
Another Solution if you have text which is English and Bangla mixed.  Then applying the whole format as bangla font will change everything. But you still need the unicodeToBijoy package. 

```
List<Map<String, dynamic>> splitBanglaAndEnglish(String text) {
      final RegExp banglaRegExp = RegExp(r'[\u0980-\u09FF]+');
      List<Map<String, dynamic>> segments = [];
      text.splitMapJoin(
        banglaRegExp,
        // IF BANGLA REGULAR EXPRESSION MATCHED.
        onMatch: (match) {
          segments.add({"text": unicodeToBijoy(match.group(0)!) + " ", "isBangla": true});
          return '';
        },
        // IF BANGL REGULAR EXPRESSION OT MATCHED
        onNonMatch: (nonMatch) {
          segments.add({"text": formateText(nonMatch), "isBangla": false}); // Apply formateText to English parts
          return '';
        },
      );
      /*
      Map resonse : 
      [
      {text: DG BATTERY WATER LEVEL (, isBangla: false}, {
      text: wWwR , isBangla: true}, 
      {text:  , isBangla: false}, 
      {text: e¨vUvwii , isBangla: true}, 
      {text:  , isBangla: false}, 
      {text: cvwbi , isBangla: true}, 
      {text:  , isBangla: false}, 
      {text: ‡j‡f‡ji , isBangla: true}, 
      {text:  , isBangla: false}, 
      {text: Ae¯’v , isBangla: true}, 
      {text: ), isBangla: false}
      ]
      */
      log("splitBanglaAndEnglish $segments");
      return segments;
    }
```
formateText function was for me only. so its not necessary. it was used to if i have a short form and need to fix it. 
how my text was sent : 

```
pw.Padding(
                    padding: const pw.EdgeInsets.all(3),
                    child: pw.Wrap(
                      children: splitBanglaAndEnglish(item['cid']).map((segment) {
                        return pw.Text(
                          segment["text"],
                          style: pw.TextStyle(
                            font: segment["isBangla"] ? pw.Font.ttf(bangla_font) : null,
                          ),
                        );
                      }).toList(),
                    ),
                  ),

```
