### ISSUE TITLE
Can you add rotated box widget

### ISSUE THREAD

**Issue by MichelMelhem** [DavBfr/dart_pdf#164]
Hello,
Can you please add the rotated box widget because i have some pictures that are not rotated correctly so i want to rotate them.
Thank you

**Comment by DavBfr** [comment]
```dart
Transform.rotateBox(
                angle: PI / 2,
                child: Text('Hello'),
),
```

**Comment by MichelMelhem** [comment]
Are you sure the rotated box work correctly beacause this is my original picture :
![image](https://user-images.githubusercontent.com/25546627/67301774-316bfd80-f4f0-11e9-8c30-684a46bcad85.png)
If i rotate it 90 ° i'm getting this :
![image](https://user-images.githubusercontent.com/25546627/67301988-7728c600-f4f0-11e9-9c25-6161f8d29ac4.png)

I'm pretty sur that is not a 90° rotation 😅

**Comment by DavBfr** [comment]
Hmm, for me it looks good. This is 90 radians. If you're looking for 90 degrees you have to use 0.5 * 3.1416.

**Comment by MichelMelhem** [comment]
Thank you !
