### ISSUE TITLE
Use native views inside our pdf

### ISSUE THREAD

**Issue by MichelMelhem** [DavBfr/dart_pdf#166]
Hello,
My app use some native view for some specific work and i was wondering if it was possible to integrate it into the pdf generated with your lib.
If you could support using directly native views inside your pdf it would be nice.
I alredy tried to convert my native view into picture and then adding them to the pdf but when i do that i'm getting blank screen so it is not a sulution.
Thank you !

**Comment by DavBfr** [comment]
Unfortunately, that's not possible.
