### ISSUE TITLE
Support `--wasm` flag in Flutter 3.22 for web

### ISSUE THREAD

**Issue by Gustl22** [DavBfr/dart_pdf#1664]
**Is your feature request related to a problem? Please describe.**
Now that WASM is supported by Flutter in v3.22 via the `flutter build web --wasm` flag, the `html` package should be replaced to support it.

**Describe the solution you'd like**

```diff
- import 'dart:html';
+ import 'dart:js_interop';
```

```diff
# pubspec.yaml
dependencies:
  ...
-  js: ^0.6.4
+  web: ^0.5.1
```

**Describe alternatives you've considered**
Leave it like it is (?)

**Additional context**
https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm

**Comment by DavBfr** [comment]
Just finished it. It's available on the master branch and works with wasm.

**Comment by Gustl22** [comment]
Wow that was fast! Didn't expect you to implement it immediately :smile: so I could have helped out. Big thanks, I'll try it out soon!

**Comment by johannesstricker** [comment]
@DavBfr Awesome that you have fixed it that quickly. Thank you 🙏  But will there be an official release anytime soon?
