### ISSUE TITLE
cells merge

### ISSUE THREAD

**Issue by avdisx** [DavBfr/dart_pdf#167]
Hello there. I want to do cell merge on some rows when creating a table. The table I want to do is as follows. cell colors are insignificant. I just want it to be as style. Thank you.
![Screenshot_1571945586](https://user-images.githubusercontent.com/55236238/67518978-85244580-f6ae-11e9-8519-2f82445cc904.png)

**Comment by DavBfr** [comment]
That is not supported, sorry.

**Comment by avdisx** [comment]
Is there any future support? or is there a plugin that will allow me to do this style? good coding.

**Comment by DavBfr** [comment]
is this supported on flutter?
PR are welcome if you want to implement it.

**Comment by avdisx** [comment]
I do not know. I was just wondering if it is possible to create a table this way
