### ISSUE TITLE
Adding a background color to PDF

### ISSUE THREAD

**Issue by callumclift** [DavBfr/dart_pdf#168]
Is there a way to add a background color to PDF's? my current method of making the whole page a container and giving it a color does not really work when using multipage PDFs as if any widgets inside the container force the page onto a second page it doesn't work. Can this be done using the pageTheme possibly? Thanks!

**Comment by callumclift** [comment]
never-mind i figured it out!!

**Comment by KevinBeckers** [comment]
Can you share how you did it?

**Comment by DavBfr** [comment]
```dart
    final PageTheme pageTheme = PageTheme(
      buildBackground: (Context context) => Container(color: PdfColors.pink),
    );

    pdf.addPage(
      Page(
        pageTheme: pageTheme,
        build: (Context context) => Center(
          child: Text(
            'Hello World',
          ),
        ),
      ),
    );
```

**Comment by karanjarich** [comment]
is it possible for the theme color to cover the whole page

**Comment by JonasWanke** [comment]
@karanjarich Yes, by wrapping the colored container in a [`FullPage`](https://pub.dev/documentation/pdf/latest/widgets/FullPage-class.html) with `ignoreMargins: true`:

```dart
final pageTheme = pw.PageTheme(
  buildBackground: (context) => pw.FullPage(
    ignoreMargins: true,
    child: pw.Container(color: PdfColors.pink),
  ),
);
```

**Comment by fldvlpr** [comment]
@DavBfr @JonasWanke @Jon-Salmon How can we change pdf background color for this flow?

await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
            html: '<html><body><p>Hello!</p></body></html>', format: format));
