### ISSUE TITLE
Is there trial licence for pdf_crypto?

### ISSUE THREAD

**Issue by xpwmaosldk** [DavBfr/dart_pdf#1684]
I have some desired features and I'd like to see if they actually work

Where should I inquire about this?

@DavBfr

**Comment by DavBfr** [comment]
There is no trial license. What are you looking to achieve?

**Comment by xpwmaosldk** [comment]
I am now trying to evaluate the web.
I would like to assess whether there is more freedom in manipulation and whether it is possible to directly process the files loaded from the local as a document (it appears that in the free version, only raster images can be controlled when loaded from the local).
I also want to evaluate the difference in document saving speed and other various aspects.

**Comment by DavBfr** [comment]
There is no difference in speed, the pdf_crypto package adds some edition possibilities, like adding pages, adding elements to a page, reorder/remove pages. It's doing all that keeping the vector elements of the original PDF.
There is no trial because you get the full source code when buying.

**Comment by xpwmaosldk** [comment]
Thank you for your response. I will consider it further.
