### ISSUE TITLE
Support for Icons

### ISSUE THREAD

**Issue by Imgkl** [DavBfr/dart_pdf#169]
Lack of this feature is really annoying.

**Comment by DavBfr** [comment]
What icon? how?

**Comment by Imgkl** [comment]
I couldn't use material icons.

**Comment by tomasbaran** [comment]
You haven't shared how you used the icon, @Imgkl Can you please do so? I'm also unable to use material icons in the pdf package...

**Comment by manoellribeiro** [comment]
I would like to know as well.

**Comment by BenPoell** [comment]
@tomasbaran @manoellribeiro better late than never. It was mentioned in #383 how it works with material icons.
I had to adjust it a bit but for me this solution worked:
```dart
final material = pw.Font.ttf(await rootBundle.load('fonts/MaterialIcons-Regular.ttf'));
...
pw.Icon(pw.IconData(0xe834), font: material)
````
Only downside is that you have to download the material font and place it in your assets.

Downloadable here:
https://google.github.io/material-design-icons/

Note you find the unicode in the codepoints file:
![image](https://user-images.githubusercontent.com/24900930/106044543-284ce180-60e0-11eb-9a19-dff1bb2583be.png)
