### ISSUE TITLE
I have an error I believe with this package Has anyone seen anything like this? Brand new install of flutter dart android studio. Its just this one file with pdf import

### ISSUE THREAD

**Issue by Isonomic** [DavBfr/dart_pdf#171]
![Screenshot (119)](https://user-images.githubusercontent.com/37713396/68148047-82202500-fef8-11e9-8b57-16b28f5a7a09.png)

**Comment by Isonomic** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/37713396/68148120-9c5a0300-fef8-11e9-9141-a819c37058d8.png)
![Screenshot (120)](https://user-images.githubusercontent.com/37713396/68148125-9ebc5d00-fef8-11e9-9910-fd2aeea2672a.png)

**Comment by DavBfr** [comment]
You have to use a namespace for the Pdf widget import:
```dart
import 'package/pdf/widget.dart' as pw;
```

then prefix all pdf objects with `pw`
