### ISSUE TITLE
Flutter 3.24 + Android fails to compile

### ISSUE THREAD

**Issue by jonmountjoy** [DavBfr/dart_pdf#1714]
I get a build failure when trying to run `flutter build apk` on Flutter 3.24.

In particular, this error:

```
 FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':audio_session:generateReleaseRFile'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable
[        ]    > /Users/x/.gradle/caches/transforms-3/15cd1ad0d6c033e4dc7ee3f576ea73c7/transformed/androidx.media2.session-r.txt
```

I'm using:
```
minSdk = 23
targetSdk = 34
compileSdk = 34
id "org.jetbrains.kotlin.android" version "1.9.10" apply false
```

You can see the demo repository here:
https://github.com/jonmountjoy/printingbug/tree/main

Any advice on how I can resolve this?

(Thanks)

**Comment by DavBfr** [comment]
```shell
git clone git@github.com:jonmountjoy/printingbug.git
flutter pub upgrade --major-versions
flutter build apk
```

Running Gradle task 'assembleRelease'...                           22.9s
✓ Built build/app/outputs/flutter-apk/app-release.apk (40.4MB)

**Comment by jonmountjoy** [comment]
Oh. 

@DavBfr I'm sorry for wasting your time - it looks like that version bump implicit in your run there, made all the difference.  
It works for me too.
On the positive side, I guess supplying a repo makes life easier.

Thanks again
