### ISSUE TITLE
unable build web app with printing 5.13.2

### ISSUE THREAD

**Issue by mbeloded** [DavBfr/dart_pdf#1719]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Waiting for connection from debug service on Chrome...
../../../../../../.pub-cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:217:16: Error: A value of type 'JSString' can't be assigned to a variable of type 'String'.
              .toJS;
               ^
Failed to compile application.
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [* ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: [iPhone12]
 - OS: [16.4]
 - Browser [Chrome]
 - Version [3.24.0]

**Additional context**

**Comment by ali4fun** [comment]
are you find any solution for this bug? @mbeloded

**Comment by vagnerac** [comment]
Hello @mbeloded.

Was any solution applied for this issue? I still get this error even using the latest version (^5.6.0).

**Comment by vagnerac** [comment]
Hello @mbeloded.

Did you apply any solution to this issue? I am still getting same error even using latest version:
Local Run Chrome:
../../../../Local/Pub/Cache/hosted/pub.dev/printing-5.13.3/lib/printing_web.dart:217:16: Error: A value of type 'JSString' can't be assigned to a variable of type 'String'.

**Comment by ashitaprasad** [comment]
@ali4fun @vagnerac Opened a new issue https://github.com/DavBfr/dart_pdf/issues/1791 to seek some solution from the package author.
