### ISSUE TITLE
If content is more in one page, It's clipping the data

### ISSUE THREAD

**Issue by CyberGhost007** [DavBfr/dart_pdf#173]
I am using .addPage() method to generate pdf, but if the content is more on that specific page, it's clipping the information. I want the clipped data to go to the next page.

Exception:  Widget won't fit into the page as its height (775.936) exceed a page height (728.5039370078739). You probably need a SpanningWidget or use a single page layout

**Comment by DavBfr** [comment]
Using a MultiPage() page, only the top-level widget will create new pages, or second level Wrap, Table or GridView.
All other widgets are one block and cannot be separated across multiple pages.

**Comment by CyberGhost007** [comment]
I want to add watermark on pdf bg, I was using Stack() but it's making the whole body as one widget, is there any way to add watermark (Image in bg)

**Comment by CyberGhost007** [comment]
Is there any way to give the desired background to pgf addPage?

**Comment by CyberGhost007** [comment]
Done, Used theme. Thanks for an awesome package
