### ISSUE TITLE
how to create multi page pdf am facing this issue:

### ISSUE THREAD

**Issue by Vaibhav-echno** [DavBfr/dart_pdf#1732]
: Instance of 'TooManyPagesException'
I/flutter (12077): #0      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:259:9)
I/flutter (12077): #1      Document.addPage (package:pdf/src/widgets/document.dart:117:10)

**Comment by Vaibhav-echno** [comment]
This issue resolved for me. I have just removed column and placed inside []

**Comment by nurullahturkoglu** [comment]
> This issue resolved for me. I have just removed column and placed inside []

ty, after doing a lot of research this method worked
