### ISSUE TITLE
Add ability to add Rows

### ISSUE THREAD

**Issue by CyberGhost007** [DavBfr/dart_pdf#175]
I am designing a CV template that has two rows, and If I am wrapping the UI with Row, it's taking the whole widget tree as a single widget. Is there is a way to build such kind of Layout?
Check this image as a reference: https://www.freesumes.com/wp-content/uploads/2018/04/contrast-resume-design.jpg

**Comment by DavBfr** [comment]
You can take this as an example CV: https://github.com/DavBfr/dart_pdf/blob/master/printing/example/lib/document.dart

**Comment by CyberGhost007** [comment]
Yea I did, but I want this for multiple pages, if the content exceeds, it should go to another page

**Comment by DavBfr** [comment]
I think it requires the development of a specialized widget that handles this.

**Comment by DavBfr** [comment]
I added `Partitions` Widget to fix this. It can create any number of columns on multiple pages.
Take a look at this for an example: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_partitions_test.dart
