### ISSUE TITLE
TooManyPagesException exactly after 21 pages?

### ISSUE THREAD

**Issue by saif-ellafi** [DavBfr/dart_pdf#1755]
**Describe the bug**
Hello all, first of all amazing plugin, thank you. It is working like a charm.

Buuut, for some reason I get `TooManyPagesException` exactly after reaching the page number 22. So after page 21 of the PDF it blows up. I can generate 21 pages with no problem.

I am dumping a log trace of entries, unfortunately I need to support a large number of pages. But I can't find any documentation or reference that talks about this hard limit? Any chance or any way to bypass it?

I have tried different documents and different page sizes, and I can confirm it is the number of pages, nothing to do with splitting, or wrapping, or else.

```dart
      pdf.addPage(
        pw.MultiPage(
          pageTheme: pw.PageTheme(
            pageFormat: pdfFormat,
            buildBackground: (pw.Context pwContext) {
              return pw.FullPage(
                ignoreMargins: true,
```
```
flutter: Number of pages: 16
flutter: Number of pages: 17
flutter: Number of pages: 18
flutter: Number of pages: 19
flutter: Number of pages: 20
flutter: Number of pages: 21
flutter: Instance of 'TooManyPagesException'
```

Cheers

**Comment by saif-ellafi** [comment]
Sorry I didn't see the parameter `maxPages` in `MultiPage`.
Cheers!

**Comment by DavBfr** [comment]
And it's only for debug builds, there is no limit with release builds.

**Comment by saif-ellafi** [comment]
@DavBfr 
debug builds??
how do I know where am I? because I ... did not set that number.

**Comment by DavBfr** [comment]
this maxPages and the limit check is only used when you build for debugging, like from your IDE. But a production application, when you run flutter build ... it won't check any limit. It's just to prevent infinit pages loop during development, which would prevent hot-reload to work.

**Comment by saif-ellafi** [comment]
oh, but my users in production informed me of this issue @DavBfr ... is there any possibility I could have included a debug build in the release version of the flutter app?

Thanks by the way

**Comment by saif-ellafi** [comment]
If it helps, I am reproducing this in "Release Mode"

```dart
import 'package:flutter/foundation.dart';

    if (kReleaseMode) {
      print('Running in release mode');
    } else {
      print('Running in debug mode');
    }
```

**Comment by DavBfr** [comment]
My bad, it's there for release builds too. Just put a big number for maxPages like 0x20000000000000 and you should be fine.

**Comment by saif-ellafi** [comment]
Thanks - should I leave this open as a bug? The internal documentation indicates it is for debug releases only still.

**Comment by swapnilgaikwad1507** [comment]
I am also facing this issue. I have tried putting maxPages as a large number but that did not work. Has anyone found a workaround for the same?
