### ISSUE TITLE
[PERFORMANCE] - The app is freezing while building a pdf

### ISSUE THREAD

**Issue by MichelMelhem** [DavBfr/dart_pdf#176]
Hello,
Recently while using the pdf lib i notices that my app freez severals secconds while i'm building my pdf.
The app is unusable while the pdf is building.For building my pdf i use a ```futureBuilder``` that call a function that build my pdf.
In my debug console i get these error messages :
```
W/System  (15312): A resource failed to call end.
W/System  (15312): A resource failed to call end.
W/System  (15312): A resource failed to call end.

```
Do you have any idea how i can improve the performance of my app ?
Thank you !

**Comment by DavBfr** [comment]
You can use an isolate.
An example can be found here: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/isolate_test.dart

**Comment by MichelMelhem** [comment]
Can you give me a more precise example that use a flutter ui beacause i couldn get how i use Isolate with a future builder

**Comment by DavBfr** [comment]
This has nothing to do with Flutter, it's just dart.
You will have a function you call whenever you need the Pdf to be created, that's all. And you can await it and even cancel it if it takes too much time.

**Comment by cleong98** [comment]
Hello sir is available any sample code for flutter web? because that flutter web cannot using isolate.

**Comment by khaledSayedAbdellah** [comment]
app freezing on web and can't use isolate .
any solution? @DavBfr

**Comment by ahmeedev** [comment]
How can we fix this in flutter ? when i try to use a separate isolate, it show me this 

![image](https://github.com/DavBfr/dart_pdf/assets/75003816/541583ac-fb3e-4578-ac1c-6476e6c63ade)

And, once i ensure the binding it says 

![image](https://github.com/DavBfr/dart_pdf/assets/75003816/c3ab65dd-0f63-43ab-879f-19dcec123c09)
