### ISSUE TITLE
Registering plugin with other plugins such as Flutter Messaging causes an exception

### ISSUE THREAD

**Issue by georgesitoniv** [DavBfr/dart_pdf#179]
**Describe the bug**
Tried to implement this on an app that uses Flutter FCM and during Flutter FCM configuration, the following exception occurred: PlatformException(error, Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference, null)

**To Reproduce**
1. install Flutter FCM and configure it with a background message handler. 
2. install the printing package
3. notice that the an exception was thrown at net.nfet.flutter.printing.PrintingPlugin.registerWith(PrintingPlugin.java:77)

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x ] Android
 - [ ] Browser

only occurs on android

**Comment by DavBfr** [comment]
Maybe they already use "printing" as the channel name

**Comment by DavBfr** [comment]
Can you try using the master branch?

**Comment by georgesitoniv** [comment]
I think I am already using your master branch. The exception occurs on registerWith method of PrintingPlugin.java

**Comment by georgesitoniv** [comment]
We have applied a fix for the the issue locally.

We have modified PrintingPlugin.registerWith from
`
public static void registerWith(Registrar registrar) {
        final MethodChannel channel = new MethodChannel(registrar.messenger(), "net.nfet.printing");
        channel.setMethodCallHandler(new PrintingPlugin(registrar.activity(), channel));
        printManager = (PrintManager) registrar.activity().getSystemService(Context.PRINT_SERVICE);
    }
`

to the following:
`
    public static void registerWith(Registrar registrar) {
        try {
            final MethodChannel channel = new MethodChannel(registrar.messenger(), "printing");
            final PrintingPlugin plugin = new PrintingPlugin(registrar.activity(), channel);
            channel.setMethodCallHandler(plugin);

            if (printManager == null) {
                printManager = (PrintManager) registrar.activity().getSystemService(Context.PRINT_SERVICE);
            }
        } catch (Exception e) {
            Log.e("PrintingPlugin", "Registration failed", e);
        }
    }
`

**Comment by DavBfr** [comment]
What is the exception message and backtrace?

**Comment by georgesitoniv** [comment]
Please see exception message below

```
/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at net.nfet.flutter.printing.PrintingPlugin.registerWith(PrintingPlugin.java:77)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at com.sulog.elotto.pcso.Application.registerWith(Application.java:18)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:164)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:134)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by georgesitoniv** [comment]
I added some more logging using log cat and below are the results:

```
11-26 20:24:21.863  8252  8252 W PrintingPlugin: registerWith
11-26 20:24:21.863  8252  8252 W PrintingPlugin: Activity: {our app id}.MainActivity@3a53934
11-26 20:24:21.863  8252  8252 W PrintingPlugin: set print manager
11-26 20:24:30.678  8252  8252 W PrintingPlugin: registerWith
11-26 20:24:30.678  8252  8252 W PrintingPlugin: Activity: null
11-26 20:24:30.678  8252  8252 W PrintingPlugin: set print manager
11-26 20:24:30.680  8252  8252 E PrintingPlugin: Registration failed
11-26 20:24:30.680  8252  8252 E PrintingPlugin: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
```

It seems that registerWith is indeed called several times. On the second time, activity is null. If it is safe to set the printManager multiple times I think we could just check if activity is not null. If it is not, we could do some null checking on both print manager and activity.

**Comment by georgesitoniv** [comment]
@DavBfr Do you agree with the changes we have made? Can we request a PR for this?

**Comment by DavBfr** [comment]
Yes, you can request a PR. That's easier to discuss the code change.

**Comment by georgesitoniv** [comment]
I tried creating a PR weeks ago and I tried again today. It seems that I do not have any permissions to push a newly created branch to your repo which I would need to perform in order to create a PR. Would it okay if you guys gave me the permission to do so? 

![image](https://user-images.githubusercontent.com/19515615/70365761-0a199600-18ce-11ea-9f93-5dd4f0c1ae9e.png)

**Comment by DavBfr** [comment]
Yes, that's not how github pull requests works.
You have to fork the project, create your branch, and from there you can create a pull request.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by georgesitoniv** [comment]
Thanks @DavBfr! We forked your repo and created a PR for the issue. 
Here's the link: [https://github.com/DavBfr/dart_pdf/pull/188](url)
