### ISSUE TITLE
pdf file width 75mm with auto height to fit the content

### ISSUE THREAD

**Issue by z2228391** [DavBfr/dart_pdf#18]
My questions:
1. - How to create a pdf file width 75mm with auto height to fit the content?
2. - How to create multi lines of text with different font size?

**Comment by DavBfr** [comment]
Auto-length does not exist in pdf. You have to calculate the length and provide the right paper dimensions.
This library is low-level and does not provide multi-lines text. You have to do it yourself by drawing at the right coordinates and right font style.

**Comment by magnatronus** [comment]
with reference to the original point **2. How to create multi line text.**

How would you achieve this with the current library?

I assume the process is similar to get length of text( in current font and fontSize) and break the text when the text size goes over a certain point.

I have looked at both Font.stringSize and Font.stringBounds  but they appear  to be arbitrary const values and are not related to the fontSize being used.

Is there some way to work this out  to allow a long piece of text to be wrapped  or is the library as it stands incapable of working this out correctly?

Thanks for any help you can provide.

**Comment by DavBfr** [comment]
stringBounds() is the right way to do it. You just have to multiply the resulting values with the font size to have the correct bounding box.
I did not need to do complex text handling for now, but if you create a higher level class for that, it can be included in this library.

**Comment by magnatronus** [comment]
Great don't mind giving it a go. If I am successful I will update you - thanks for the pointer.
