### ISSUE TITLE
In iOS Printer Option not working with FileImage

### ISSUE THREAD

**Issue by janardhanmupparaju** [DavBfr/dart_pdf#180]
-> when i use FileImage for printing image file. in iOS not working and hanging the app.
-> if i use AssetImage working file in iOS.

this is my code:

 Future<List<int>> buildPdf(PdfPageFormat format) async {
    final pdf.Document doc = pdf.Document();

    final PdfImage image = await pdfImageFromImageProvider(
        pdf: doc.document, image: FileImage(File('asset/avatar.png')));
    
    doc.addPage(pdf.Page(build: (pdf.Context context) {
      return pdf.Center(
        child:
            // pdf.Text(
            //   'Hello World',
            // ),
            pdf.Image(image),
      ); // Center
    }));

    return doc.save();
  }

**Comment by DavBfr** [comment]
Can you use `FileImage(File('asset/avatar.png'))` on Flutter UI?
I don't think so, it's the same here.

**Comment by janardhanmupparaju** [comment]
I am using this one 
 final PdfImage image = await pdfImageFromImageProvider(
        pdf: doc.document, image: FileImage(_imageFile));

**Comment by janardhanmupparaju** [comment]
can you help me on this issue
this my code it is working in android but not working in iOS.
in iOS it open the Printer Options and the screen freezes.

my flutter version : 

Flutter 1.10.15-pre.252 

iPad version is 13.2.3

This is my code

final PdfImage image = await pdfImageFromImageProvider(
        pdf: doc.document,
        image: FileImage(_imageFile)); 

 doc.addPage(pdf.Page(build: (pdf.Context context) {
      return pdf.Center(
          child: pdf.Container(
        child: pdf.Image(image),
      )
      
          ); // Center
    }));

**Comment by DavBfr** [comment]
This can be because it can't open the png file.

**Comment by DavBfr** [comment]
I tested it and cannot reproduce.
