### ISSUE TITLE
Error: ArgumentError (Invalid argument (string): Contains invalid characters.

### ISSUE THREAD

**Issue by GautamChibde** [DavBfr/dart_pdf#182]
App crashes when adding special characters to the Text widget.

> Exception has occurred.
> ArgumentError (Invalid argument (string): Contains invalid characters.: "*#&?✓™√π×∆¶£¢€¥~`∆]")

I am using text which was captured from flutter TextFormField.

and adding it to the PDF Text Widget.

**Flutter Doctor**

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.9.1+hotfix.6 at /Users/gautam/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gautam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Desktop (please complete the following information):**
 - [*] iOS
 - [*] Android
 - [ ] Browser

**Additional context**
N/A

**Comment by DavBfr** [comment]
Can I have more information, like more backtrace?

**Comment by GautamChibde** [comment]
using custom font open-sans.ttf for Text widget solved the issue for me [ref](https://github.com/DavBfr/dart_pdf/issues/76#issuecomment-493546844) from issue #76.

**Comment by felipedonoso** [comment]
Hi guys, I need help, My error is similar:

[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "•"

there is away. for to set a custom Fonts:

I/flutter (20488): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (20488): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (20488): ---------------------------------------------
I/flutter (20488): Cannot decode the string to Latin1.
I/flutter (20488): This font does not support Unicode characters.
I/flutter (20488): If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
I/flutter (20488): See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (20488): ---------------------------------------------
E/flutter (20488): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "•"


Thank you!
