### ISSUE TITLE
Support For Windows Embedding

### ISSUE THREAD

**Issue by kanishqgupta** [DavBfr/dart_pdf#183]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavBfr** [comment]
@kanishqgupta please write a correct message.

**Comment by anandsubbu007** [comment]
I'm new to flutter. I want to implement direct printing for windows app. is this possible with printing package. i tried windows_printing but it doesn't work. 
Is this possible with Printing package.

Feature Request

**Comment by DavBfr** [comment]
It's not yet implemented.
