### ISSUE TITLE
does any method can print pdf from ApplicationDocumentsDirectory?

### ISSUE THREAD

**Issue by elliotxin** [DavBfr/dart_pdf#184]
In the apps, if I download the PDF files from the internet, so does have any function that can just pass the pdf local path to it and directly to print out?
Sometimes, we also got the pdf base64 String from the server, so I hope in the future can provide one function that can pass the base64 String to AirPrinter and print it out.

**Comment by DavBfr** [comment]
@elliotxin please write a correct message.

**Comment by DavBfr** [comment]
Yes, you can do both: The layout callback returns a pdf data.

```dart
await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async {
return await File('my-file.pdf').readAsBytes();
}
);
```

You can use the dart base64 functions to convert to binary if needed.
