### ISSUE TITLE
Is there any way to know where we are on a page to control for page breaks?

### ISSUE THREAD

**Issue by voivoed** [DavBfr/dart_pdf#185]
I'm trying to implement invoice printing on my app and I'm having a bit of a problem figuring out when to add page breaks so the contents don't just get clipped at the bottom.

Is there any way to either:

1) break the page automatically if the contents go past the bottom according to the page format (i.e. another page gets added automatically to the document and the content starts going there instead)?

2) get some measurement of how "long" the current page is already so we can compare it to the dimensions from the page format and add pages programatically?

Thanks!

**Comment by DavBfr** [comment]
Not possible, it's like flutter: the UI is built according to a description, but the actual layout is done later. When you create the widgets, the framework has no idea of what it will look like, not even on which page the widget will sit.

To automatically break pages, use a MultiPage page, each child's widgets will be measured at layout time and trigger a new page if necessary.

**Comment by voivoed** [comment]
That's easy enough, thank you so much! I'll just switch to MultiPage.

Is there some more detailed documentation for the plugin anywhere? I haven't really had to work with PDFs before and it's hard to figure out what can be done.

**Comment by DavBfr** [comment]
The documentation is here: https://pub.dev/documentation/pdf/latest/widget/widget-library.html

But the best is to look at the test suite on github: https://github.com/DavBfr/dart_pdf/tree/master/pdf/test

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
