### ISSUE TITLE
Flutter for web

### ISSUE THREAD

**Issue by mayankjanmejay** [DavBfr/dart_pdf#186]
**Describe the bug**
The plugin does not function in flutter for web.

**To Reproduce**
generatePrint()
async {
  
  final pdf = pdfImport.Document();
  num index=0;
  pdf.addPage(pdfImport.Page(
  pageFormat: PdfPageFormat.a4,
  build: (context) {
    
    return pdfImport.Column(children: <pdfImport.Widget>[
    pdfImport.Text('labor')
    ]
    );
  }
 
  
));
  laborCodes.forEach( (labor) {
    index++;
pdf.addPage(pdfImport.Page(
  pageFormat: PdfPageFormat.a4,
  build: (context) {
    
    return pdfImport.Column(children: <pdfImport.Widget>[
    pdfImport.Text(labor)
    ]
    );
  }
 
  
));
  });
  await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save());
      print('In 1');
final file = File("/example.pdf");
await file.writeAsBytes(pdf.save());
   }

**Expected behavior**
A pdf file to be created

**Screenshots**

**Flutter Doctor**
PS P:\OneDrive - Cognitiv Control\Work\Apps\GreenTMS-PWA> flutter doctor -v
[√] Flutter (Channel dev, v1.12.0, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.12.0 at D:\flutter
    • Framework revision 9323a623bd (3 weeks ago), 2019-11-08 21:35:17 -0500
    • Engine revision 2f69e38160
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Mayank\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\Mayank\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [-] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
I have the support for Flutter Web in a branch, but it requires Flutter v1.10

**Comment by mayankjanmejay** [comment]
I dont mind downgrading to Flutter v1.10. Could you please share how to get the plugin working in Flutter for Web

**Comment by DavBfr** [comment]
Please try with the branch `flutter-1.10` which works with flutter master channel.

**Comment by DavBfr** [comment]
Implemented in printing 3.0.0
