### ISSUE TITLE
Roll Paper support for printing

### ISSUE THREAD

**Issue by preekmr** [DavBfr/dart_pdf#189]
**Is your feature request related to a problem? Please describe.**
There is no way currently available to set the page height to automatic which is necessary if the print happens on a Roll Paper where the page height could be dynamic.

**Describe the solution you'd like**
There could be a parameter such as `useRollPaper:true` that can be used to initialize `PdfPageFormat` which can set the height of the page automatically based on the content. 

**Describe alternatives you've considered**
No alternatives I have found currently.

**Comment by DavBfr** [comment]
That's implemented in the next version. You can test it using the git master branch.
To specify that the paper height is unknown, create a PdfPageFormat with the height of double.infinity. Two standard roll papers are defined:
* PdfPageFormat.roll57 for 57 mm papers (2 1/4")
* PdfPageFormat.roll80 for 80 mm papers (3 1/8")

```dart
final pdf = Document();
pdf.addPage(
  Page(
    pageFormat: PdfPageFormat.roll80,
    build: (Context context) => Text('Hello World!'),
  ),
);
```

**Comment by preekmr** [comment]
Thanks much @DavBfr . Appreciate it! 👏🏻👍🏻

**Comment by DavBfr** [comment]
You're welcome!
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by shobith10** [comment]
_AssertionError ('package:pdf/src/widgets/multi_page.dart': Failed assertion: line 198 pos 12: 'pageFormat.height > 0 && pageFormat.height < double.infinity': is not true.)

i have given widgets height double.infinity , but width size is 320 for all, does that make error

**Comment by hamzamon** [comment]
When printing in PdfPageFormat.roll80 its trimmed to a4 height in POS printer. Its okay with receipt supporting printer. What will to get full length?

![Printer device settings](https://user-images.githubusercontent.com/26362545/209674747-c324903b-ad09-45c2-942c-29e02b021104.jpeg)
