### ISSUE TITLE
Show Current Screen Content

### ISSUE THREAD

**Issue by leon2835** [DavBfr/dart_pdf#19]
Hi David,

Instead of hardcode "Hello World" when generate the PDF, is there any way to automatic show the current content screen data inside the document? Thank You.
E.g
![device-2018-10-25-163807](https://user-images.githubusercontent.com/19604759/47487105-68271d80-d874-11e8-9a5f-8e734e535895.png)

**Comment by DavBfr** [comment]
Something like that should do the trick:
```dart
    var boundary = previewContainer.currentContext.findRenderObject();
    var im = await boundary.toImage();
    var bytes = await im.toByteData(format: ui.ImageByteFormat.rawRgba);
    PDFImage image = PDFImage(
        pdf,
        image: bytes.buffer.asUint8List(), 
        width: im.width, 
        height: im.height);
    g.drawImage(image, ....);
```

**Comment by leon2835** [comment]
Hi David,
Seems like your code is works charming , but how ever it just only show the current screen, e.g if there is a list, it's not gonna "screenshot" the contents which out of the screen. :(
