### ISSUE TITLE
PDF Image issue

### ISSUE THREAD

**Issue by iosdev04** [DavBfr/dart_pdf#190]
**Describe the bug**
Adding image to PDF
**To Reproduce**
```dart
var properties = await prefix1
                .decodeImageFromList(existingImage.readAsBytesSync());
final ByteData bytes =
                await properties.toByteData(format: ImageByteFormat.rawRgba);
```

**Expected behavior**

**Screenshots**
https://pasteboard.co/IKM4qjg.png
**Desktop (please complete the following information):**
 - [X ] iOS
 - [ ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
What is your image?

**Comment by iosdev04** [comment]
im able to solve it. i was trying to resize image on the fly and was passing hardcoded width and height.

do you have any idea how can we reduce pdf file size?? Pdf file size almost 40mb with few images only

**Comment by DavBfr** [comment]
Use jpeg images with: 
```dart
Image(PdfImage.jpeg( ... ))
```

It will take a lot less space.

**Comment by iosdev04** [comment]
but actual image resolution is like 2000x2000...how it will reduce the size

**Comment by iosdev04** [comment]
I tried with this one but problem it it take min width not max. I tried with PdfImage.jpeg it reduces the PDF file size. Just a question no compression applied to PDF at the time of saving ?

**Comment by DavBfr** [comment]
A zlib compression is applied on the data yes.

**Comment by iosdev04** [comment]
i don't think zlib is applied. If i export same PDF with Quartz Filter to 'Reduce File'. It almost reduces PDF file size by almost 80%

**Comment by DavBfr** [comment]
I think it's reducing the images size or quality. 80% is a lot.

**Comment by iosdev04** [comment]
https://pasteboard.co/IKZdcFV.png
check this image

**Comment by inventvictor** [comment]
@DavBfr please what about adding PNG. PdfImage.jpeg works for jpeg images.

**Comment by DavBfr** [comment]
You can use this:
```dart
const imageProvider = const AssetImage('assets/image.png');
final PdfImage image = await pdfImageFromImageProvider(pdf: pdf.document, image: imageProvider);
```

**Comment by inventvictor** [comment]
Alright, thanks.

But this is pure dart environment and not flutter environment.

**Comment by DavBfr** [comment]
To load an image in pure dart, use the library `image`:

```dart
final img = decodeImage(File('test.png').readAsBytesSync());
final image = PdfImage(
  pdf.document,
  image: img.data.buffer.asUint8List(),
  width: img.width,
  height: img.height,
);

pdf.addPage(Page(
    build: (Context context) {
      return Center(
        child: Image(image),
      ); // Center
    })); // Page
```

**Comment by inventvictor** [comment]
Thanks. It worked.

Grateful
