### ISSUE TITLE
Is this plugin supports Bluetooth connectivity?

### ISSUE THREAD

**Issue by krishnaji-yedlapalli** [DavBfr/dart_pdf#192]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by krishnaji-yedlapalli** [comment]
I want to print a document via Bluetooth connected printing device

**Comment by DavBfr** [comment]
If your printer supports pdf printing then it will work. You just have to implement the communication layer.
If your printer is compatible ESC/POS, maybe this plugin is a better fit: https://pub.dev/packages/esc_pos_printer
