### ISSUE TITLE
Support Flutter-like "fixes" for widgets ...

### ISSUE THREAD

**Issue by weenzeel** [DavBfr/dart_pdf#193]
This library is a brilliant idea :) Using the powerful flutter widget/layout paradigm with PDF as output is something that can be really useful!

One of the things that make the Flutter developer experience great is the Dart Analysis Servers "fixes", offered to IDE:s to manage widgets.

E.g. in Visual Stuiode Code, just hit Command . to have the option to add padding, insert widgets remove widgets etc.

Is there any way this library could adjust to support the native Flutter hints?

Thanks for releasing this package as open source!

**Comment by DavBfr** [comment]
This would require a VSCode plugin. It's out of scope, unless you want to develop it.

**Comment by weenzeel** [comment]
Gotcha!
