### ISSUE TITLE
pickPrinter and DirectPrint for Android using BrotherSDK

### ISSUE THREAD

**Issue by zamvar** [DavBfr/dart_pdf#195]
hi i really want to know if its possible to add brother sdk to this current plugin?

**Comment by zamvar** [comment]
i have a very crude working implementation of printer picker using the brothersdk , what i cant get around with is implementing the directPrint (fairly new to android dev).

**Comment by DavBfr** [comment]
Use the pdf library to generate the pdf file, save it on disk and use the function `printPdfFile` from the brothersdk: https://support.brother.com/g/s/es/htmldoc/mobilesdk/reference/android/printer.html#printpdffile

**Comment by zamvar** [comment]
Thanks for the response, will look into it ,but still having a hard time communicating with the brother printer to print even the included brother sdk apk demo wont connect tl their own printers on android lols
