### ISSUE TITLE
HOW TO SOLVE THIS ?  Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/issues/76

### ISSUE THREAD

**Issue by SEMHussain** [DavBfr/dart_pdf#196]
**Describe the bug**
Dear sir, i'm using this plugin, and when i run this i got the this errors,   ### **Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/issues/76** how to slove this error ?

CAN YOU HELP ME PLEASE

**To Reproduce**
Code snippet to reproduce the behavior:

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:pdf/widgets.dart' as pdfLib;
import 'package:path_provider/path_provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    generatePDF()async{
      final pdfLib.Document pdf = pdfLib.Document(deflate: zlib.encode);

      pdf.addPage(pdfLib.MultiPage(build: (context) => [
        pdfLib.Table.fromTextArray(context: context, data:  <List<String>>[
          ['asdasasd' , 'asdsadsadsad' , 'asdasdasdasdasdasdass' , 'asd' , 'asdasdasd']
        ]),
      ]));

      final String dir = (await getApplicationDocumentsDirectory()).path;
      print(dir);
      final String path = '$dir/test_pdf.pdf';
      final File file = File(path);
      await file.writeAsBytes(pdf.save());
    }

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("PDF"),
        ),
        body: Container(
          child: Center(
            child: RaisedButton(
              onPressed: generatePDF,
              child: Text("call", style: TextStyle(fontFamily: 'Helvetica'),),
            ),
          ),
        ),
      )
    );
  }
}

```

**Expected behavior**

**Screenshots**

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SEMHussain** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/19269959/71553572-95b2ae00-29c6-11ea-8f0b-e0a6dd568032.png)

**Comment by DavBfr** [comment]
Follow the link: https://github.com/DavBfr/dart_pdf/issues/76

**Comment by SEMHussain** [comment]
dear sir, i rea the [https://github.com/DavBfr/dart_pdf/issues/76](url), but i cant understand any one can you answer me or give me a sample code please sir

**Comment by DavBfr** [comment]
To use a TrueType font from a flutter bundle:

```dart
final font = await rootBundle.load("assets/open-sans.ttf");
final ttf = Font.ttf(font);

pdf.addPage(Page(
    build: (Context context) {
      return Center(
        child: Text('Dart is awesome', style: TextStyle(font: ttf, fontSize: 40)),
      ); // Center
    })); // Page
```

**Comment by SEMHussain** [comment]
dear sir, if i give to you trouble, first i ask sorry, and im very tired sir, 2 weeks i try to generate PDF, but i cant, can you give me a complete project for pdf, idont want big projects sir, i want only generate hello world in pdf, thats enough for me sir, please give me complete small example, im very tired sir please

![Screenshot (15)](https://user-images.githubusercontent.com/19269959/71645531-011ab980-2d00-11ea-86ee-ef7415d81145.png

**Comment by DavBfr** [comment]
Something like this should do:

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:pdf/widgets.dart' as pdfLib;
import 'package:path_provider/path_provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    generatePDF() async {
      final pdfLib.Document pdf = pdfLib.Document();

      final font = await rootBundle.load("assets/open-sans.ttf");
      final ttf = pdfLib.Font.ttf(font);
      final fontBold = await rootBundle.load("assets/open-sans-bold.ttf");
      final ttfBold = pdfLib.Font.ttf(fontBold);
      final fontItalic = await rootBundle.load("assets/open-sans-italic.ttf");
      final ttfItalic = pdfLib.Font.ttf(fontItalic);
      final fontBoldItalic =
          await rootBundle.load("assets/open-sans-bold-italic.ttf");
      final ttfBoldItalic = pdfLib.Font.ttf(fontBoldItalic);
      final pdfLib.Theme theme = pdfLib.Theme.withFont(
        base: ttf,
        bold: ttfBold,
        italic: ttfItalic,
        boldItalic: ttfBoldItalic,
      );

      pdf.addPage(pdfLib.MultiPage(
          theme: theme,
          build: (context) => [
                pdfLib.Table.fromTextArray(
                    context: context,
                    data: <List<String>>[
                      [
                        'asdasasd',
                        'asdsadsadsad',
                        'asdasdasdasdasdasdass',
                        'asd',
                        'asdasdasd'
                      ]
                    ]),
              ]));

      final String dir = (await getApplicationDocumentsDirectory()).path;
      print(dir);
      final String path = '$dir/test_pdf.pdf';
      final File file = File(path);
      await file.writeAsBytes(pdf.save());
    }

    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text("PDF"),
      ),
      body: Container(
        child: Center(
          child: RaisedButton(
            onPressed: generatePDF,
            child: Text(
              "call",
              style: TextStyle(fontFamily: 'Helvetica'),
            ),
          ),
        ),
      ),
    ));
  }
}
```

and add the fonts in your assets folder and pubspec.

**Comment by SEMHussain** [comment]
dear sir , im very very sorry for troubling you , im very tired for that sir please help me, i got the some errors again, i put the 2 images, **01 - my dart file and 02 - pubspec.yaml**, please help me sir

![Screenshot (18)](https://user-images.githubusercontent.com/19269959/71669836-0e818380-2d94-11ea-8bfe-94ea5391fce2.png)
![Screenshot (19)](https://user-images.githubusercontent.com/19269959/71669845-13463780-2d94-11ea-927a-adff2233c094.png)

**Comment by DavBfr** [comment]
Can you send me a full project? This way I can take a look.

**Comment by SEMHussain** [comment]
ok sure sir, i will upload my project to google drive and send to you link sir, thanks a lot

**Comment by SEMHussain** [comment]
[https://drive.google.com/file/d/1eyPAe0amaqKlFgJTBuqSMs8yI4_pBUo0/view?usp=sharing](url)

please help me sir. ur greate , ur always help yto ur subscribers, thanks a lot sir, ur very nice

**Comment by DavBfr** [comment]
Your code works.
I just added the missing import line for rootBundle:
```dart
import 'package:flutter/services.dart';
```

**Comment by SEMHussain** [comment]
wow wow wow sir all errors are gone, ur ery very great sir, i dont know gow to thanks to you, 99999999 thousand croe times thanks to you sir and , i have a small quection where my pdf download ? how to change pdf download path ? i got the some outputs, i dont know that meaning i attach image below pleas sir help me 
![Screenshot (20)](https://user-images.githubusercontent.com/19269959/71740773-22f07980-2e83-11ea-8773-5bd6ab1ac614.png)

**Comment by DavBfr** [comment]
This is saved on your android device in an application storage. What do you want to do with it?

Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by SEMHussain** [comment]
dear sir, i search my file name and, see in full file manager, i didnt get my pdf file sir canyou help me pls 
![WhatsApp Image 2020-01-04 at 12 10 36 AM](https://user-images.githubusercontent.com/19269959/71742233-07876d80-2e87-11ea-839c-00e7cc70eb16.jpeg)

**Comment by SEMHussain** [comment]
my pdf file save path is ---> /data/user/0/com.example.semh/cache/test_pdf.pdf, but there have a no **com.example.semh** this folder,  please sir, if i done this my 2 week trouble are change to happines sir

**Comment by DavBfr** [comment]
You save it in getApplicationDocumentsDirectory() if you want the user to access it, use the share function from the package https://pub.dev/packages/printing


```dart
Printing.sharePdf(bytes: pdf.save(), filename: 'my-document.pdf');
```

**Comment by SEMHussain** [comment]
my awesome sir, this is my pdf generate complete method, is this correct ? i put the printing share code also, please chekc this, i got the some errors, so please sir 

`generatePDF() async {
      final pdfLib.Document pdf = pdfLib.Document();

      final font = await rootBundle.load("assets/OpenSans-Regular.ttf");
      final ttf = pdfLib.Font.ttf(font);
      final fontBold = await rootBundle.load("assets/OpenSans-Bold.ttf");
      final ttfBold = pdfLib.Font.ttf(fontBold);
      final fontItalic = await rootBundle.load("assets/OpenSans-Italic.ttf");
      final ttfItalic = pdfLib.Font.ttf(fontItalic);
      final fontBoldItalic =
          await rootBundle.load("assets/OpenSans-BoldItalic.ttf");
      final ttfBoldItalic = pdfLib.Font.ttf(fontBoldItalic);
      final pdfLib.Theme theme = pdfLib.Theme.withFont(
        base: ttf,
        bold: ttfBold,
        italic: ttfItalic,
        boldItalic: ttfBoldItalic,
      );

      pdf.addPage(pdfLib.MultiPage(
          theme: theme,
          build: (context) => [
                pdfLib.Table.fromTextArray(
                    context: context,
                    data: <List<String>>[
                      [
                        'asdasasd',
                        'asdsadsadsad',
                        'asdasdasdasdasdasdass',
                        'asd',
                        'asdasdasd'
                      ]
                    ]),
              ]));

       final String dir = (await getApplicationDocumentsDirectory()).path;
      print(dir);
      final String path = '$dir/test_pdf.pdf';
      final File file = File(path);
      await file.writeAsBytes(pdf.save());
      print(file);
      Printing.sharePdf(bytes: pdf.save(), filename: 'test_pdf.pdf');
    }`
![Screenshot (22)](https://user-images.githubusercontent.com/19269959/71742731-b37d8880-2e88-11ea-8f9e-3fd9964f4299.png)

**Comment by DavBfr** [comment]
Don't save the file to disk. Remove the lines:
```dart
final String dir = (await getApplicationDocumentsDirectory()).path;
  print(dir);
  final String path = '$dir/test_pdf.pdf';
  final File file = File(path);
  await file.writeAsBytes(pdf.save());
  print(file);
```

**Comment by SEMHussain** [comment]
wow awesome sir, thanks a lot for your help, i surely buy the **Buy Me a Coffee** and can you help me please, this is last help sir, i didnt troubling youafter this, **HOW TO ATTACH PDF TO EMAIL** please sir

**Comment by DavBfr** [comment]
the share feature can do that. Your users will be able to share by mail or whatsapp or any application.

**Comment by SEMHussain** [comment]
yes sir it's awesome, it;s ask share for all and i want download to my phone, how to do that ? iwant to download pdf to my specific path folder, how to i give my path ? and save that ? please sir,

**Comment by SEMHussain** [comment]
dear sir, i have a two things, please help me for that, please sir very very please, 
01 - how to download or save PDF to my specific path
02 - how to design my pdf ? put the rows, tables, circles, all, we can use html code to print pdf ?

**Comment by SEMHussain** [comment]
dear sir, this pdf share button is working properly but i have a small trouble, when i share with email to address is blank, how to fill with send address, flutter have a other plugins for **Email sender** but i dont know how to concat email plugin with pdf plugin , can you help me please, this is helpfull for all peoples, so please help me please 

im using flutter email plugin is ---> https://pub.dev/packages/flutter_email_sender
this plugin have a attachment future, but i dont know how to attach our pdf to this email, please help me sir 


![WhatsApp Image 2020-01-04 at 7 49 58 PM](https://user-images.githubusercontent.com/19269959/71767073-c39b7380-2f2d-11ea-972c-7680f2232f1d.jpg)

**Comment by DavBfr** [comment]
Please see if this documentation is useful for you: https://github.com/DavBfr/dart_pdf/wiki/Document-Output

Save to a file and use attachmentPath in flutter_email_sender to send the mail.

**Comment by SEMHussain** [comment]
dear awesome sir, small error, please help me,
im using this code, it's very helpful for me, but but my phone have a no path in that name, can u help me please, 
![Screenshot (29)](https://user-images.githubusercontent.com/19269959/71780995-91eae100-2fef-11ea-969d-90cefad7c45c.png)

**Comment by DavBfr** [comment]
Of course, it exists, otherwise, it would raise an exception line 59. But this path is private and accessible only by the application, no file explorer can see it unless your phone is rooted.

**Comment by longfit** [comment]
I have download  
SEMHussain  ,  I try to input    中文字 character instead of asdas... , it show empty box.

my final project need shown chinese in pdf
Dear DavBfr , 
help me give me expample font which can work out pdf container chinese character..

thanks

**Comment by DavBfr** [comment]
font should work: https://github.com/ButTaiwan/genyo-font/raw/bc2fa246196fefc1ef9e9843bc8cdba22523a39d/TW/GenYoMinTW-Heavy.ttf

**Comment by Saurabh7Goku** [comment]
![Screenshot (105)](https://github.com/DavBfr/dart_pdf/assets/73352093/437e2a00-cfe8-4c70-bd1c-76448436c23f)
 theme.withFont() is not working anymore pls help me;
