### ISSUE TITLE
Barcode type support (Code128)

### ISSUE THREAD

**Issue by amirulasrof** [DavBfr/dart_pdf#197]
Hi @DavBfr can you add more barcode type to render in pdf. Previously my current project is using the Code39 type but now the project requirement has changed. Thank you.

Original post : https://github.com/andrey-ushakov/esc_pos_printer/issues/23

**Comment by amirulasrof** [comment]
Workaround for now is that I am using your https://pub.dev/packages/barcode 

Code : 

// import
import 'package:barcode/barcode.dart' as exbc;
import 'package:pdf/widgets.dart' as pdf;

// render
pdf.Page(
          orientation: pdf.PageOrientation.landscape,
          pageFormat: PdfPageFormat(
            printerPaperWidth * PdfPageFormat.mm, 150 * PdfPageFormat.mm
          ),
          build: (context) => pdf.Container(
            margin: pdf.EdgeInsets.all(12),
            child: pdf.BarcodeWidget(
              type: exbc.BarcodeType.Code128,
              drawText: false,
              data: 12345,
              height: 40,
            ),
          ),      
        )

**Comment by DavBfr** [comment]
Yes, that's the way to do it.
