### ISSUE TITLE
android printing causes app freeze

### ISSUE THREAD

**Issue by Onein** [DavBfr/dart_pdf#200]
On Android 10 on a physical Pixel 2 XL and Pixel 3A as well as on a virtual Pixel 2, the whole app freezes after the print button of the nativ platform UI is pressed. That state remains till the print spooler did finish it's job (indicated by a notification) and then the app starts working again.
Any ideas or known issues?

This does not happen if you save that pdf as a file again for example. Unfortunately there is no log output when this happens.

There is nothing performed on the device, no pdf creation, just called the `Printing.layoutPdf(onLayout: (_) => pdfDataBytes)` function on an already available pdf.

**Comment by DavBfr** [comment]
I will need more context to understand your issue.
Can you show me more code?

**Comment by Onein** [comment]
That's actually most of it, I do read a base64 encoded pdf file from an api, do a decode and pass it to layoutPdf e.g.
```
Uint8List pdfDataBytes = base64.decode(base64String);
Printing.layoutPdf(onLayout: (_) => pdfDataBytes);
```
The base64String is just read from an api response.
This does work, the pdf is rendered inside the platform view correctly and is printed correctly as well, but with the described behavior that the app is freezing will system printing process is doing its job.

**Comment by DavBfr** [comment]
What size is the Pdf?
I don't see why it freezes

**Comment by Onein** [comment]
About 147 KB on disk. Will do some more tests today, if I see something new I will report back here.

**Comment by Onein** [comment]
Ok, found the issue.
AFAICT this is not gonna work out the way you expected:
https://github.com/DavBfr/dart_pdf/blob/78232de1f962ea04c7e950d0f737417a35863071/printing/android/src/main/java/net/nfet/flutter/printing/PrintingJob.java#L130-L150

You aren't supposed to wait here for the actual printing to finish, you need to release your resources and hope the best. If you really want to poll the print status you need to do it in a non blocking way.

onFinish is called on the main thread, so what's actually happening here is, when your print job is taking longer the platform UI will close but the activity will freeze till the print job is completed, which might never happen. The activity is killed after some grace period by the android system and then flutter can go on.

I would omit that step and just trust the system printservice that it will do it's job, it should inform the user anyway, like any printing service, that something went wrong.

**Comment by DavBfr** [comment]
I see. Maybe the loop can be run in a thread if the API accepts that.
Are you able to make some tests?

**Comment by Onein** [comment]
Yep no problem, but it will take some time, I'm currently busy with other stuff.

**Comment by christianarduino** [comment]
I have the same issue. I don't understand the reason since for a month now everything has worked without any problems

**How I use it:**
```
bool result = await Printing.layoutPdf(
  onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
     format: format,
     html: html,
  ),
);
return result;
```

**Where did I find the problem**
- Sunmi V2 Pro (Android 7.1.2)

**What specifically happens**
2 cases have occurred:

1. Pressed the button to print, the native spoiler of the printing device returns an error (but no feedback is returned from the library), the app exits the pdf preview and remains totally blocked.
2. Pressed on the print button, the html is printed correctly, the app exits the pdf preview, but remains blocked without returning any feedback

**IDE**
Android Studio 3.5.3

**Computer**
Macbook air 2018 with Catalina OS

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)
```

**Comment by Onein** [comment]
Probably this didn't happened because the response of the os printing services was fast enough, if you have significant delay the os will kill your activity, because of blocking for to long.

@DavBfr It seems that you still need to update the android plugin to the newest API's introduces in 1.12 https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

Maybe it would be better to release a intermediate bugfix till I have the time to take a closer look, so users aren't blocked by this e.g.
```
 public void onFinish() {
     printing.onCompleted(this, true, "");
     printJob = null; 
 }
```
Error information is still displayed by the os, but I would lack any reporting to dart for now.

**Comment by DavBfr** [comment]
@Onein now you have the new Android Plugin API in master.

**Comment by DavBfr** [comment]
Added a thread in onFinish(). Please test the master branch.

**Comment by Onein** [comment]
@DavBfr that was fast ;) tested it and it works.
Maybe a timeout would make sense.

**Comment by DavBfr** [comment]
Added a 10 minutes timeout on master.
