### ISSUE TITLE
Is it possible to style the table?

### ISSUE THREAD

**Issue by michealchow2324** [DavBfr/dart_pdf#201]
Like Is there any ways to change the background color of the table row?

**Comment by DavBfr** [comment]
You have to draw a background on each cell.

**Comment by IvanRuiz23** [comment]
Any solution for this?
![image](https://user-images.githubusercontent.com/97054151/223530447-15cb0563-b32f-4162-8eaa-a789fa6c9624.png)

pw.Container(
        child: pw.Text(col,
            softWrap: true,
            style: pw.TextStyle(
                background: pw.BoxDecoration(
              color: PdfColors.amber,
            ))),
        padding: pw.EdgeInsets.all(10),
      ),
