### ISSUE TITLE
It is possible to put a material widget inside the pdf?

### ISSUE THREAD

**Issue by rafael-ferreira3** [DavBfr/dart_pdf#203]
I have a chart widget and i would like to use it

**Comment by DavBfr** [comment]
If you can draw it on screen, then you can screenshot it and use it as an image.
See the example project.

**Comment by seikosantana** [comment]
> If you can draw it on screen, then you can screenshot it and use it as an image. See the example project.

Hi, I'm in need of this, would you mind to point out which part could be the starting point in the example? Thanks in advance.
