### ISSUE TITLE
Save PDF to File for uploading it to Firebase Storage [Flutter Web]

### ISSUE THREAD

**Issue by capce** [DavBfr/dart_pdf#204]
Hey guys,

i want to use dart_pdf with flutter web and uploading the generated PDF to Firebase Storage. Creating the PDF works very well but I stuck at writing the Document as bytes to a File, because the package dart:io is not available for web.
Is there an alternative to the example in the readme? For pushing it to Firebase Storage I need to generate a kind of a blob.

**Example in the readme (requires dart:io):**
```
// On Flutter, use the [path_provider](https://pub.dev/packages/path_provider) library:
//   final output = await getTemporaryDirectory();
//   final file = File("${output.path}/example.pdf");
final file = File("example.pdf");
await file.writeAsBytes(pdf.save());
```
**This is how I upload the file to Firebase Storage:**
```
final String filePath = 'folder/' + 'text.pdf';
fb.StorageReference storageRef = fb.storage().ref(filePath);
storageRef.put(file, fb.UploadMetadata(contentType: ContentType('application', 'pdf').toString()));
```
I already tried to use the File class of dart:html instead of dart:io to store the PDF as a blob. With this variant it was actually successful to upload the file to Firebase Storage, but I can not open it. I guess the file is broken or wrong encoded.
`final htmlIO.File file = htmlIO.File(pdf.save(), "example");`

On the debug console I get the message that the font has not unicode support:
`Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management`
Is it possible that this causes the wrong encoding?

Thank you for the great package and for your support!

**Comment by DavBfr** [comment]
You can use putData() which takes a Uint8List:
```dart
final data = Uint8List.fromList(pdf.save());
final String filePath = 'folder/' + 'text.pdf';
fb.StorageReference storageRef = fb.storage().ref(filePath);
storageRef.putData(data, fb.UploadMetadata(contentType: ContentType('application', 'pdf').toString()));
```

**Comment by capce** [comment]
Thank you very much!

I got it working with your hint to use `Uint8List.fromList(pdf.save())`. Nevertheless I have to use storageRef.put() because flutter web does not support the plugin firebase_storage but only the firebase package. 
Here is my code:
```
import 'package:firebase/firebase.dart' as fb;
...
final data = Uint8List.fromList(pdf.save());
final String filePath = 'folder/' + 'text.pdf';
fb.StorageReference storageRef = fb.storage().ref(filePath);
storageRef.put(data, fb.UploadMetadata(contentType: io.ContentType('application', 'pdf').toString()));
 ```
