### ISSUE TITLE
Text rendered with an imported font doesn't render with sufficient space 

### ISSUE THREAD

**Issue by kostaa** [DavBfr/dart_pdf#207]
When rendering a pdf page with an imported Roboto font it appears that not enough space is 
given to the text - see the attached screenshots. One is rendered with the default  Helvetica and the other one with the Roboto that is loaded from a file. 

[Roboto - incorrect](https://github.com/DavBfr/dart_pdf/files/4086803/_roboto-font.pdf)

[Helvetica - correct](https://github.com/DavBfr/dart_pdf/files/4086796/_helvetica-font.pdf)

Have I missed any additional settings?

```dart
  final theme = PageTheme(
    theme: Theme.withFont(
      base: Font.ttf(await rootBundle.load("assets/fonts/Roboto-Regular.ttf")),
      bold: Font.ttf(await rootBundle.load("assets/fonts/Roboto-Bold.ttf")),
      italic: Font.ttf(await rootBundle.load("assets/fonts/Roboto-Italic.ttf")),
      boldItalic: Font.ttf(await rootBundle.load("assets/fonts/Roboto-BoldItalic.ttf"))),
    pageFormat: PdfPageFormat(
        210 * PdfPageFormat.mm,
        297 * PdfPageFormat.mm,
        marginLeft: 15 * PdfPageFormat.mm,
        marginTop: 20 * PdfPageFormat.mm,
        marginRight: 10 * PdfPageFormat.mm,
        marginBottom: 20 * PdfPageFormat.mm)
  );

  pdfDoc.addPage(Page(
      pageTheme: theme,
      build: (Context context) {
        return Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Text(guardNull('a b c d e f g'),
                  textAlign: TextAlign.center),
              Text(guardNull('y g'),
                  textAlign: TextAlign.center),
              Text(guardNull('A B C D E F G'),
                textAlign: TextAlign.center),
          ]);
      }
  ));
```

**Comment by DavBfr** [comment]
If you need more space between lines, use the attribute `lineSpacing` of `TextStyle`.

**Comment by kostaa** [comment]
Hi the ```lineSpacing``` does not help in this case as the text is short and it does not wrap so the   ```lineSpacing``` is not applied. I suspect it is either the ascent or the descent that are not correctly set when the font is loaded from an external file.

**Comment by DavBfr** [comment]
I see. Can you test with the master branch?

Put this in your pubspec:
```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf
      path: pdf
```

**Comment by kostaa** [comment]
Yes that solved the problem. 
Thanks for a quick turnaround.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
