### ISSUE TITLE
no pdf generated on android and 

### ISSUE THREAD

**Issue by incafox** [DavBfr/dart_pdf#208]
I cant  generate pdf on android platform, im using path provider (no aditional permissions).
im using the example code.
I would like to generate a pdf on application persistent path or any directory on the phone.
Am I missing something? maybe it needs a permission in the manifest? 
Im also getting this:
Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by DavBfr** [comment]
Look at this page: https://github.com/DavBfr/dart_pdf/wiki/Document-Output
and for the second line, follow the link for more information.
