### ISSUE TITLE
Different buildBackground depending on page

### ISSUE THREAD

**Issue by Gicminos** [DavBfr/dart_pdf#209]
I am trying to show a watermark image only in the last page of my document, and if possible aligning it on the bottom right.

This is what I have tried: 

```
  final PageTheme pageTheme = PageTheme(
    pageFormat: PdfPageFormat.letter.copyWith(marginBottom: 1.5 * PdfPageFormat.cm),
    buildBackground: (Context context) => (context.pageNumber == context.pagesCount)
        ? Container(
//      width: 40,
//      alignment: Alignment.bottomRight,
            decoration: BoxDecoration(
              image: DecorationImage(
                image: myImage,
                fit: BoxFit.contain,
              ),
            ),
          )
        : Container(),
  );

  document.addPage(
    MultiPage(
      pageTheme: pageTheme,
      // rest of the code
```

But `myImage` is showing in all the pages, and if I uncomment `alignment` the image is disappearing from all the pages.

Is it a bug or I am doing something wrong? Thanks

**Comment by DavBfr** [comment]
`context.pageNumber == context.pagesCount` is always true because this function is called for each page before it's created and at this time it's always the last page.

You can add a last page after the multipage.

**Comment by Gicminos** [comment]
My content is dynamic and I cannot just move part of it in a last page because the size of it vary. I cannot even just create a last page for only the image because it is supposed to go with the content.

I also tried to put the image in the footer, in that way I managed to show it only in the last page but it increases the footer height in all the other pages even if the image is not shown and it does not go below the content.

**Comment by DavBfr** [comment]
Try with the `buildForeground` then, this one is run after all the pages layout.

**Comment by Gicminos** [comment]
buildForeground shows the image only in the last page, but it covers the text. This will not work for my case since I was trying to insert a watermark image.

**Comment by DavBfr** [comment]
I can change the page generation to make it work the right way. I will see what I can do.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by Gicminos** [comment]
If I do it do you think it is possible to see the changes done before February?

**Comment by DavBfr** [comment]
Yes!

**Comment by Gicminos** [comment]
Done :)

**Comment by DavBfr** [comment]
Can you try the master branch and tell me if it fixes your issue?

```dart
final PageTheme pageTheme = PageTheme(
      buildBackground: (Context context) =>
          (context.pageNumber == context.pagesCount)
              ? Align(
                  alignment: Alignment.topRight,
                  child: SizedBox(
                      width: 200,
                      height: 200,
                      child: PdfLogo(color: PdfColors.blue200)),
                )
              : Container(),
    );

    pdf.addPage(
      MultiPage(
        pageTheme: pageTheme,
        build: (Context context) => <Widget>[
          Wrap(
            children: List<Widget>.generate(
              670,
              (_) => Text('Hello World '),
            ),
          ),
        ],
      ),
    );
```

**Comment by Gicminos** [comment]
Is it possible to test this without having to comment the stuff I am doing with the priting package? Using the image provider from it.

pubspec.yaml
```
  pdf:
    git:
      url: git://github.com/DavBfr/dart_pdf
      ref: master
      path: pdf
      version: ^1.4.1

  printing: ^3.1.0
```

```
Because printing 3.1.0 depends on pdf ^1.3.15 and no versions of printing match >3.1.0 <4.0.0, printing ^3.1.0 requires pdf from hosted.

So, because itseccomp_mobile depends on both pdf from git and printing ^3.1.0, version solving failed.
pub get failed (1; So, because itseccomp_mobile depends on both pdf from git and printing ^3.1.0, version solving failed.)
```

**Comment by DavBfr** [comment]
Specify both repos:

```
  pdf:
    git:
      url: git://github.com/DavBfr/dart_pdf
      path: pdf
  printing:
    git:
      url: git://github.com/DavBfr/dart_pdf
      path: printing
```

**Comment by Gicminos** [comment]
I have tried but I get this:

```
Because every version of printing from git depends on pdf from hosted and itseccomp_mobile depends on pdf from git, printing from git is forbidden.

So, because app depends on printing from git, version solving failed.
pub get failed (1; So, because app depends on printing from git, version solving failed.)
```

**Comment by DavBfr** [comment]
I usually keep the dependencies section with no changes, and set an override like this:

```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf
      path: pdf
```

**Comment by Gicminos** [comment]
I had to change https:// with git:// but then it worked, and yes! I managed to do exactly what I wanted, thank you ^^
