### ISSUE TITLE
Draw Flutter's Path objects

### ISSUE THREAD

**Issue by brun0xon** [DavBfr/dart_pdf#211]
Is there any way to draw an object of type Path (from dart:ui)?

**Comment by DavBfr** [comment]
With some conversion, this might be possible.
You can draw an SVG path already.

**Comment by brun0xon** [comment]
Thanks for fast answer. 
What exactly conversion should I do?

**Comment by DavBfr** [comment]
You have to create a Path class with the same functions and map them to the equivalent functions in https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/src/graphics.dart

**Comment by brun0xon** [comment]
In my program I apply a transformation matrix to many paths, so the last quiestion is, could you tell me how to scale specified coordinates in each command? (e.g. scale cubic bezier or lineTo).

**Comment by DavBfr** [comment]
You can call `setTransform(Matrix4 t)` before drawing, it will apply the matrix to all operations.
To save and restore the context, use `saveContext()` and `restoreContext()`

**Comment by brun0xon** [comment]
The question is as follows: in the Flutter's scope, I draw Path object on a Canvas object, but before drawing I apply some transforms and assign to some objects draw offsets. As I think, I must translate and scale all corresponds to concrete object svg commands in the way so it will be painted at some point I calculate before

**Comment by DavBfr** [comment]
Using Flutter or Pdf is the same. You can calculate the new positions yourself, or let the graphic pipeline (~GPU) do it for you using setTransform which is simple and faster.
If you want to draw an SVG path, look at this example:

```dart
class PdfLogo extends StatelessWidget {
  PdfLogo({this.color = PdfColors.red, this.fit = BoxFit.contain});

  final PdfColor color;
  final BoxFit fit;

  static const String pdf =
      'M 2.424 26.712 L 2.424 26.712 C 2.076 26.712 1.742 26.599 1.457 26.386 C 0.416 25.605 0.276 24.736 0.342 24.144 C 0.524 22.516 2.537 20.812 6.327 19.076 C 7.831 15.78 9.262 11.719 10.115 8.326 C 9.117 6.154 8.147 3.336 8.854 1.683 C 9.102 1.104 9.411 0.66 9.988 0.468 C 10.216 0.392 10.792 0.296 11.004 0.296 C 11.508 0.296 11.951 0.945 12.265 1.345 C 12.56 1.721 13.229 2.518 11.892 8.147 C 13.24 10.931 15.15 13.767 16.98 15.709 C 18.291 15.472 19.419 15.351 20.338 15.351 C 21.904 15.351 22.853 15.716 23.24 16.468 C 23.56 17.09 23.429 17.817 22.85 18.628 C 22.293 19.407 21.525 19.819 20.63 19.819 C 19.414 19.819 17.998 19.051 16.419 17.534 C 13.582 18.127 10.269 19.185 7.591 20.356 C 6.755 22.13 5.954 23.559 5.208 24.607 C 4.183 26.042 3.299 26.712 2.424 26.712 Z M 5.086 21.586 C 2.949 22.787 2.078 23.774 2.015 24.33 C 2.005 24.422 1.978 24.664 2.446 25.022 C 2.595 24.975 3.465 24.578 5.086 21.586 Z M 18.723 17.144 C 19.538 17.771 19.737 18.088 20.27 18.088 C 20.504 18.088 21.171 18.078 21.48 17.647 C 21.629 17.438 21.687 17.304 21.71 17.232 C 21.587 17.167 21.424 17.035 20.535 17.035 C 20.03 17.036 19.395 17.058 18.723 17.144 Z M 11.253 10.562 C 10.538 13.036 9.594 15.707 8.579 18.126 C 10.669 17.315 12.941 16.607 15.075 16.106 C 13.725 14.538 12.376 12.58 11.253 10.562 Z M 10.646 2.1 C 10.548 2.133 9.316 3.857 10.742 5.316 C 11.691 3.201 10.689 2.086 10.646 2.1 Z';

  @override
  Widget build(Context context) {
    return Shape(pdf, width: 24, height: 27, fillColor: color, fit: fit);
  }
}
```

**Comment by brun0xon** [comment]
How this shape can be positioned?

**Comment by DavBfr** [comment]
wrap it with other widgets, the Flutter way (not tested):
```dart
Align(child: SizedBox(child:PdfLogo()), width:30, height:30), alignment: Alignment.centerLeft)
```

**Comment by brun0xon** [comment]
This is good only for few objects not for many (my app can have >1000 objects like this).

**Comment by DavBfr** [comment]
That's fine, Align and SizedBox will only set a new transform matrix, nothing else.

**Comment by brun0xon** [comment]
Objects are positioned in concrete point like (825, 400)

**Comment by DavBfr** [comment]
If you want to use the canvas, you can draw with `drawShape()`
```dart
canvas.saveContext();
canvas.setTransform(Matrix4.identity()..translate(825, 400));
canvas.drawShape('M 2.424 26.712 L 2.424 26.712 ...');
canvas.setStrokeColor(Colors.blue);
canvas.strokePath();
canvas.restoreContext();
```

**Comment by brun0xon** [comment]
Imagine the situation: there is some svg paths (converted font glyphs), which starts from "m" command and its painting constraints may be about 1024x1024. Then it be converted into Flutter Path objects to which will be applied some transformations. After all actions, I have initial svg paths (about 1024x1024 size) and its draw coordinates (which calculated for transformed paths). How can I paint this objects in a such way like I tell early (on Canvas) and having data described above?

**Comment by DavBfr** [comment]
I don't understand what is the issue.

**Comment by brun0xon** [comment]
Use `canvas.moveTo()` method for positioning does not make sense, because all svg paths have own first 'm' element, which violates previous `moveTo()` call method.

**Comment by DavBfr** [comment]
then you translate everything using the matrix: canvas.setTransform(Matrix4.identity()..translate(825, 400));

**Comment by brun0xon** [comment]
Oh, I've forgot about matrix translation. Thanks a lot for Your help.

**Comment by brun0xon** [comment]
Another questions: why shapes are drawn upside down? And why after `context.rotateX(pi)` whole picture becomes invisible? It becomes invisible if rotation angle >=pi / 2

**Comment by DavBfr** [comment]
It's upside down because the PDF coordinates are defined with the Y starting 0 at the bottom and increase to the top.
When you rotate, you also have to translate, to compensate, as the rotation is done from the origin (0, 0). A bit of math for you!

**Comment by brun0xon** [comment]
I have not forgot to translate while rotating. I did it too. I noticed that when rotation is closer to 90 degrees, translation must be significantly bigger (geometric progression, i suppose). I picked up the translation value in that way I can see shape rotated pi * 0.49. When I rotate shape to pi * 0.5 and higher then shape becomes invisible

**Comment by DavBfr** [comment]
You can look at how this widget works: https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/widgets/basic.dart#L149

**Comment by brun0xon** [comment]
Anyway I don't understand why the picture is invisible. Could you, please, tell me what exactly transformation I should apply to the context in a such way its origin will become left top corner like in Flutter's Canvas?

**Comment by DavBfr** [comment]
You can try to scale the Y-axis by -1
