### ISSUE TITLE
Styling container with no results

### ISSUE THREAD

**Issue by incafox** [DavBfr/dart_pdf#212]
**Describe the bug**
Maybe im missing something or  this library cannot do that, i cant add circular borders to my container, but nothing works, no borders no decoration, help pls.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pdfwidget.Container(
                          decoration: const pdfwidget.BoxDecoration(
                              border:
                              pdfwidget.BoxBorder(bottom: true, width: 1.5, color: PdfColors.black)),
                                  child: pdfwidget.Column(children: [
                              pdfwidget.Text("LOG",
                                  style: pdfwidget.TextStyle(fontSize: 30)),
                              pdfwidget.Container(

                                width: 250,
                                child: pdfwidget.Text("Matriz"),
                              ),
                              pdfwidget.Text("Dir"),
                              pdfwidget.Text("Space"),
                              pdfwidget.Text(
                                  "With register"),
                            ])

                              )
```

**Expected behavior**
I want borders like this: (without colors)
![image](https://user-images.githubusercontent.com/4401153/73422912-79bd6780-42f8-11ea-9662-4fbb772ee9af.png)

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser

**Comment by DavBfr** [comment]
This is not supported, but you're welcome to implement it.

**Comment by DavBfr** [comment]
Try this:

```dart
Container(
          padding: const EdgeInsets.all(20),
          decoration: const BoxDecoration(
            borderRadius: 20,
            border: BoxBorder(
              top: true,
              left: true,
              right: true,
              bottom: true,
              width: 3,
              color: PdfColors.black,
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text(
                'LOG',
                style: const TextStyle(fontSize: 30),
              ),
              Container(
                width: 250,
                child: Text('Matriz'),
              ),
              Text('Dir'),
              Text('Space'),
              Text('With register'),
            ],
          ),
        )
```

**Comment by ElZombieIsra** [comment]
@DavBfr  Although your proposed solution works, it seems a little weird to me that I have to specify every single side of a BoxBorder that I'm explicitly declaring and It's supposed to work out of the box. 
Maybe this behaviour can be modified in the BoxBorder constructor setting the default values to `true` and only denying them where you need them to NOT show themselves up?
I don't now if this is like this for a reason but what I suggest seems better to me.
