### ISSUE TITLE
Add feature to print from USB OTG

### ISSUE THREAD

**Issue by komputerboy** [DavBfr/dart_pdf#213]
**Is your feature request related to a problem? Please describe.**
My printer is not have WiFi or BT printing feature. So, it will be very great if this plugin has feature to print directly from USB OTG

**Describe the solution you'd like**
So, the user only plug USB + OTG to connect from printer to smartphone

**Comment by DavBfr** [comment]
If you have a proper driver installed on the device this should work out of the box.

**Comment by komputerboy** [comment]
But what if i don't have it?

I do have it in my PC/Laptop, but is it possible to convert it to Android?

**Comment by DavBfr** [comment]
not possible, you need a driver.
