### ISSUE TITLE
ios build fail

### ISSUE THREAD

**Issue by salime45** [DavBfr/dart_pdf#214]
/Users/builder/clone/build/ios/Release-iphoneos/printing/printing.framework/Headers/PrintingPlugin.h:19:1: error: duplicate interface definition for class 'PrintingPlugin'
    @interface PrintingPlugin : NSObject <FlutterPlugin>
    ^
    In module 'printing' imported from /Users/builder/clone/ios/Runner/GeneratedPluginRegistrant.m:92:
    /Users/builder/clone/build/ios/Release-iphoneos/printing/printing.framework/Headers/printing-Swift.h:220:12: note: previous definition is here
    @interface PrintingPlugin : NSObject <FlutterPlugin>

**Comment by DavBfr** [comment]
This must be something on your project files. Try to clear the cache: `flutter clean`

**Comment by salime45** [comment]
this happen in three different PC and the ci/cd platform. 

I dont know if there any conflict with other lib

**Comment by DavBfr** [comment]
What are your dependencies?

**Comment by salime45** [comment]
sembast: ^1.15.1
  path_provider: ^1.1.0

  equatable: ^0.2.3
  screenshot: ^0.1.1
  animator: ^1.0.0+1
  image_gallery_saver: ^1.2.0
  permission_handler: ^4.1.0
  flutter_i18n: ^0.8.3
  package_info: ^0.4.0+13

  firebase_core: ^0.4.0+6
  firebase_analytics: ^5.0.2
  firebase_performance: ^0.3.0+4
  flutter_crashlytics: ^1.0.0
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.13.0+1

  scoped_model: ^1.0.1
  get_it: ^1.0.3+2
  image_picker: ^0.6.3+1
  flutter_circle_color_picker: ^0.1.1

  flutter_platform_widgets: ^0.20.3-beta.1
  cupertino_icons: ^0.1.2
  url_launcher: ^5.2.5
  tutorial_coach_mark: ^0.2.0
  pdf: ^1.3.22
  image: ^2.1.4
  date_format: ^1.0.6
#  printing: ^2.1.9
  printing: ^3.0.0

  flutter_calendar_carousel: ^1.4.10
  open_file: ^2.0.3
  flutter_svg: ^0.16.1

  device_id: ^0.2.0

  video_player: ^0.10.5
  flutter_cupertino_date_picker: ^1.0.12
  share: ^0.6.3+5
  shared_preferences: ^0.5.6

**Comment by DavBfr** [comment]
This must be something else, I have no issues building an iOS app with this dependency list.

**Comment by salime45** [comment]
Any idea ? i dont know what to do

**Comment by DavBfr** [comment]
If you give me access to the source I can help, I don't see anything else I can do.

**Comment by Bestfastfire** [comment]
Same here...
