### ISSUE TITLE
Web - Method "rasterPdf" not implemented

### ISSUE THREAD

**Issue by ronytesler** [DavBfr/dart_pdf#215]
On web when I run:
    await for (var page in Printing.raster(pdf.save(), pages: [0,1], dpi: 72.0)) {
...
}
I get this error:
Uncaught (in promise) Error: PlatformException(error, UnimplementedError: Method "rasterPdf" not implemented, null)

**Comment by DavBfr** [comment]
yes, this is not supported on the web.

**Comment by ronytesler** [comment]
Will it be? How can I convert a pdf to an Image and/or let the user save the pdf/image as a file?
I'm using https://pub.dev/packages/pdf

**Comment by DavBfr** [comment]
No it will not. You can't convert a Pdf to an image. To save the pdf to a file, use the sharePdf() method.
