### ISSUE TITLE
problem 1. table header text unicode not support and problem 2.unicode word miss spell

### ISSUE THREAD

**Issue by angur-mia** [DavBfr/dart_pdf#219]
**Describe the bug**
 ['ID','দাতার তালিকা', 'Mobile','Start Date', 'Taka', 'Active'], this code i use for table header.
 i get error. but table multi body data is unicode but not any unicode problem . body data show only miss spell

// your code
 pdf.Table.fromTextArray(context: context, data: <List<String>>[
             ['ID','দাতার তালিকা', 'Mobile','Start Date', 'Taka', 'Active'],
              ...list.map(
                      (m) => [m.getMid().toString(), m.getName(), m.getMobile(),cdate().ddMyyyy(m.getCreate_at()), m.getTaka().toString(),m.getActive() ?'হা':'না'])
            ]),```

**Comment by DavBfr** [comment]
Bangla Unicode Fonts are not yet supported. This duplicates #198 
Can you help on this?
