### ISSUE TITLE
glyphBounds and glyphAdvance return hard coded values

### ISSUE THREAD

**Issue by magnatronus** [DavBfr/dart_pdf#22]
I have been looking at allowing text wrap, and from your suggestion have been attempting to use stringBounds().

This issue I have is that the both glyphBounds() and glyphAdvance() return hard coded values, therefore it is impossible to accurately use stringBounds() to determine the length of a string.

```
  double glyphAdvance(int charCode) {
    return 0.454;
  }

  PDFRect glyphBounds(int charCode) {
    return const PDFRect(0.0, 0.0, 0.4, 1.0);
  }
```

for example:

```
String foo = "WW";
String bar = "ii";
```

stringBounds() says these are the same length, but they are not a *W* is wider that *i*.  

Is there any other way of accurately determining the wide of a string, or is it that this is currently not possible?

**Comment by DavBfr** [comment]
Yes, those functions are correctly implemented with ttf fonts.
Look at the file /pdf/test/ttf_test.dart for an example.

**Comment by magnatronus** [comment]
Thanks for the pointer.

**Comment by magnatronus** [comment]
My first attempt at  a document generator that has text that will wrap for both line and page can be found (here)[https://github.com/magnatronus/flutter-pdf-doc]

thanks for the help so far!

**Comment by DavBfr** [comment]
@magnatronus, I'm writing a Flutter-like Widget system wor this Pdf library. It is available in the `widgets` branch. If you want to help, that would be much appreciated!

It would look like this:

```dart
var pdf = Document();
pdf.addPage(Page(
  child: Column(children: <Widget>[
    Text("Hello World"),
    Image(image),
    Shape(shape),
  ])
));
```

**Comment by magnatronus** [comment]
@DavBfr , if I can help sure,  I will take a look.

**Comment by magnatronus** [comment]
@DavBfr I have been having a look at the **widgets** branch and have come across a few issues with the way it is currently set up. 

You have defined your own classes called, for example,  **StatelessWidget**,  **Widget**, **LimitedBox** , **Context**, but as Flutter already has these define when in a Flutter environment they clash with the Flutter classes.  I know they could be name-spaced but as they are a fundamental part of the underlying Flutter building blocks I wondered whether they should be prefixed , maybe with *Pdf*  to make they unique to your library?
