### ISSUE TITLE
'File('test.webp').readAsBytesSync()' not working on web

### ISSUE THREAD

**Issue by ronytesler** [DavBfr/dart_pdf#223]
It appears in the example but not working on web.

**Comment by ronytesler** [comment]
This did work for me:
```
import 'package:image/image.dart' as imageLib;
ByteData byteData = await rootBundle.load("assets/images/" imageName);
final img = imageLib.decodeImage(byteData.buffer.asUint8List(););
```

**Comment by DavBfr** [comment]
Flutter Web or just Dart on the web has no File support as there is no access to a filesystem in a web browser.

**Comment by ronytesler** [comment]
I understand. The plugin supports web and its examples don't work in web, maybe it would be better to separate mobile examples and web examples. Anyway, the code I wrote works for me. Thanks.
