### ISSUE TITLE
can't display chinese in pdf file

### ISSUE THREAD

**Issue by wrjcs** [DavBfr/dart_pdf#224]
Hello,
I write chinese into pdf by using NotoSansSC-Regular.ttf,
But I can't be displayed in pdf file.

Could help me?
Thanks.

**Comment by wrjcs** [comment]
By the way, I use the last version, 1.5.0

**Comment by wrjcs** [comment]
var myTheme = pdf.Theme.withFont(
      base: pdf.Font.ttf(await rootBundle.load("fonts/OpenSans-Regular.ttf")),
      bold: pdf.Font.ttf(await rootBundle.load("fonts/OpenSans-Regular.ttf")),
      italic: pdf.Font.ttf(await rootBundle.load("fonts/OpenSans-Regular.ttf")),
      boldItalic:
          pdf.Font.ttf(await rootBundle.load("fonts/OpenSans-Regular.ttf")),
    );

**Comment by DavBfr** [comment]
OpenSans-Regular doesn't have Chinese Glyphs. Can you give me a link to the ttf file you use?

**Comment by wrjcs** [comment]
thanks for you reponse.
this is the link I download the ttf.
https://fonts.google.com/?query=san&selection.family=Open+Sans
Could you tell me which font can display Chinese correctly?

Thanks.

**Comment by DavBfr** [comment]
Try with this one: https://fonts.gstatic.com/s/notosanssc/v10/k3kXo84MPvpLmixcA63oeALRLoKL.otf

**Comment by wrjcs** [comment]
I save it as noto.otf name,
and I load like this:
var fd = await rootBundle.load('fonts/noto.otf');
var font = pdf.Font.ttf(fd);
pdf.Text(
                    '城市:' +
                        data['companyInfo']['postCode'] +
                        ' ' +
                        data['companyInfo']['city'],
                    textAlign: pdf.TextAlign.left,
                    style: pdf.TextStyle(fontSize: 12, font: font),
                  )

I/flutter ( 3070): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter ( 3070): Unable to print: NoSuchMethodError: The method '+' was called on null.
I/flutter ( 3070): Receiver: null
I/flutter ( 3070): Tried calling: +(0)
E/presentation( 3070): onDestroy

**Comment by DavBfr** [comment]
Well, this means data['companyInfo']['postCode'] or data['companyInfo']['city'] is null

**Comment by wrjcs** [comment]
thanks.
I'm sure that data['companyInfo']['postCode'] and data['companyInfo']['city'] is not null.
this message comes when I load the font of otf.
If I load the font ttf, or I don't use custom font, I will not have this message.

**Comment by DavBfr** [comment]
Try to convert the font to ttf: https://cloudconvert.com/otf-to-ttf

**Comment by wrjcs** [comment]
Hello,
I convert it, it displays like this.
![20200221151856](https://user-images.githubusercontent.com/7202194/75042224-5da78300-54be-11ea-872f-7da379a437b7.jpg)

**Comment by wrjcs** [comment]
before passe to Text(),should I encode the string in utf8 or others?

**Comment by DavBfr** [comment]
No, nothing specific to convert, dart uses utf16 internally.
Try with another font, like: https://github.com/ButTaiwan/genyo-font/raw/master/TW/GenYoMinTW-Heavy.ttf

**Comment by wrjcs** [comment]
Yes,I got it.
Thank you very much.

**Comment by wrjcs** [comment]
Yes I got when I display on screen.
But when I print it by printer.
there are different.

![20200221155243](https://user-images.githubusercontent.com/7202194/75044634-466a9480-54c2-11ea-955e-4ac588f8372d.png)
![20200221155252](https://user-images.githubusercontent.com/7202194/75044625-42d70d80-54c2-11ea-99e9-805b2a3d2620.png)

**Comment by wrjcs** [comment]
I print this pdf file via window, I can print correctly.
By the way, I use the same printer.

**Comment by DavBfr** [comment]
How does it look like on the preview?

**Comment by wrjcs** [comment]
on the preview , it display correctly.
just has error on print.
may be the setting of system?

**Comment by DavBfr** [comment]
Or the printer driver is not well implemented.

**Comment by wrjcs** [comment]
Thank you very much for your help.
