### ISSUE TITLE
Ability to build widgets outside and then add them to the document/page etc?

### ISSUE THREAD

**Issue by jorgevvr** [DavBfr/dart_pdf#226]
That's what i mean:

`table.addRow(TableRow());
table.addRow(TableRow());

then:

multipage.children.add(table);
document.add(multipage);
`

i'm sorry if i am not clean, i am trying build a document this way but all the fields are final so i cant add elements to them.

**Comment by DavBfr** [comment]
You can build the children first:
```dart
final data = <TableRow>[];

data.add(TableRow());
data.add(TableRow());

Table(
                children: data,
                border: const TableBorder(),
                tableWidth: TableWidth.max,
              ),
```

**Comment by jorgevvr** [comment]
> You can build the children first:
> 
> ```dart
> final data = <TableRow>[];
> 
> data.add(TableRow());
> data.add(TableRow());
> 
> Table(
>                 children: data,
>                 border: const TableBorder(),
>                 tableWidth: TableWidth.max,
>               ),
> ```

Oh thank you so much, i will see if this can fit my needs.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
