### ISSUE TITLE
Property defaultVerticalAlignment of Table doesn't work

### ISSUE THREAD

**Issue by talent-apps** [DavBfr/dart_pdf#227]
The field `defaultVerticalAlignment` of the `Table` widget, doesn't work

.
Code snippet to reproduce the bug:
```dart
final doc = pdf.Document();
doc.addPage(
  pdf.Page(
    pageFormat: PdfPageFormat.a4,
    build: (pdf.Context context) {
      return pdf.Table(
        defaultColumnWidth: pdf.FixedColumnWidth(20),
        defaultVerticalAlignment: pdf.TableCellVerticalAlignment.middle,
        children: [
          pdf.TableRow(
            children: [
              pdf.Container(child: pdf.Text("Vertical"), color: PdfColor.fromRYB(1, 0, 0)),
              pdf.Container(child: pdf.Text("alignment"), color: PdfColor.fromRYB(0, 1, 0), height: 60),
              pdf.Container(child: pdf.Text("doesn't work!"), color: PdfColor.fromRYB(0, 1, 1)),
            ]
          )
        ]
      );
    },
  ),
);
```

**Expected behavior**
The containers will be centered vertically.

**Actual behaviour**
The containers are aligned to the top in the output PDF.
See attached example: 
<img width="495" alt="example" src="https://user-images.githubusercontent.com/48091135/75294972-5f60a600-5832-11ea-9415-d6c985792277.PNG">

**Comment by DavBfr** [comment]
Fixed in the master branch. Will be available in Pdf 1.6.0
