### ISSUE TITLE
Digital Signature

### ISSUE THREAD

**Issue by abuzarsaddiqui** [DavBfr/dart_pdf#229]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavBfr** [comment]
I have a separate paid library to deal with Digital Signature and AES256 Encryption. Let me know if you're interested.

**Comment by abuzarsaddiqui** [comment]
Dear David,
I am interested and need a trail version of that library and pricing to use
it commercially.

**Comment by DavBfr** [comment]
Can I have more information on what you want to achieve and why do you need Digital Signature?
What is your use case?
and how will you manage your PKI?

I already have AES256 encryption and an RSA signature with a SHA1 hash. I'm still working on the right way to manage the certificate chain and the private key.

Feel free to use my email address to answer if you don't want to publish this information.

**Comment by abuzarsaddiqui** [comment]
Actually we will have digital certificate from the RA and use their code to
get calculate hash of the PDF file and they will also provide us the code
to access machine's keystore. So what we want is the plugin/library which
combines certificate, keystore and other signatory information into a
visible pdf signature.

**Comment by DavBfr** [comment]
That sounds good.
Here is a signed document generated using the Pdf library. Let me know if it is what you want.

[signature.pdf](https://github.com/DavBfr/dart_pdf/files/4290063/signature.pdf)

**Comment by abuzarsaddiqui** [comment]
No, I want this type of signature and sign field is also available in
signature panel when opened with adobe acrobat . please find the attached
pdf file and signature is in the last page.

**Comment by DavBfr** [comment]
You sent no file.

**Comment by abuzarsaddiqui** [comment]
[ex.pdf](https://github.com/DavBfr/dart_pdf/files/4292848/ex.pdf)

**Comment by DavBfr** [comment]
Yes, that's exactly what I sent you.
The visual signature in the document can be anything you choose to draw. The signature panel when opened with adobe acrobat is just a flag to set.

Here is an example document:

```dart
    final Document pdf = Document();

    pdf.addPage(
      Page(
        build: (Context context) => Column(
          children: <Widget>[
            Text('Click on this signature for more info:'),
            Signature(
              name: 'Signature',
              crypto: PdfSign(
                privateKey:
                    PdfSign.pemPrivateKey(File('key.pem').readAsStringSync()),
                certificates: <Uint8List>[
                  PdfSign.pemCertificate(File('cert.pem').readAsStringSync()),
                ],
              ),
              child: Container(
                margin: const EdgeInsets.all(20),
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  border: BoxBorder(width: 2, color: PdfColors.amber),
                  borderRadius: 10,
                ),
                child: Text(
                  'Document Digitally Signed\nby David PHAM-VAN\non ${DateTime.now()}',
                ),
              ),
            ),
            PdfLogo(),
          ],
        ),
      ),
    );

    final File file = File('signature.pdf');
    file.writeAsBytesSync(pdf.save());
```

With the file: [signature.pdf](https://github.com/DavBfr/dart_pdf/files/4293469/signature.pdf)

**Comment by abuzarsaddiqui** [comment]
Sounds good but how do we add at the specific location on the pre generated
pdf file?

**Comment by DavBfr** [comment]
This pdf library cannot load a pre-generated file. But it's easy to recreate.

**Comment by abuzarsaddiqui** [comment]
How can we recreate the pre-generated pdf and make it pixel perfect and
then do the singing

**Comment by DavBfr** [comment]
Pixel perfect is not possible.

**Comment by DavBfr** [comment]
I can develop Pdf loading and update as a template if it helps.

**Comment by leo8198** [comment]
@DavBfr I just copied your code to use for my application but the Widget PdfSign doesn't exist. Help me. I already have pdf package version 1.8.0

**Comment by DavBfr** [comment]
@leo8198 it's a paid feature. Drop me an email if you're interested.
