### ISSUE TITLE
Export charts

### ISSUE THREAD

**Issue by suvarna84** [DavBfr/dart_pdf#230]
Hi Dav,  Is there any way to export chart to pdf?

**Comment by DavBfr** [comment]
Hi, export charts from what?

**Comment by suvarna84** [comment]
I have a web application with the charts, i need to export that chart from the app to pdf file.

**Comment by DavBfr** [comment]
Then you have 2 options with this library:
* Convert your chart to an image and print it.
* Directly draw the lines and text using the Pdf library to recreate your chart.

**Comment by suvarna84** [comment]
I used this,but didn't work

 Future<void> _capturePng() async {
    RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();
    print(pngBytes);
  }

can you please help me out

**Comment by DavBfr** [comment]
don't save the image to png.

```dart
Future _printChart() async {
    RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
    final ui.Image im = await boundary.toImage();
    final ByteData bytes =
        await im.toByteData(format: ui.ImageByteFormat.rawRgba);
    print('Print Screen ${im.width}x${im.height} ...');

    final bool result =
        await Printing.layoutPdf(onLayout: (PdfPageFormat format) {
      final pdf.Document document = pdf.Document();

      final PdfImage image = PdfImage(document.document,
          image: bytes.buffer.asUint8List(),
          width: im.width,
          height: im.height);

      document.addPage(pdf.Page(
          pageFormat: format,
          build: (pdf.Context context) {
            return pdf.Center(
              child: pdf.Expanded(
                child: pdf.Image(image),
              ),
            ); // Center
          })); // Page

      return document.save();
    });
}
```
