### ISSUE TITLE
POS print as a PDF

### ISSUE THREAD

**Issue by danieramiz** [DavBfr/dart_pdf#232]
Hey all

I have a mobile project using "blue_thermal_printer" to print in a POS. 
But now I'm trying to export the project on flutter web, everything is working fine, but I have issues printing on a POS from the browser. 
Is there a way to generate a PDF similar to the printed in a POS? 
And then can we take that PDF and pinter it using the "printing 3.1.0" plugin?

**Comment by DavBfr** [comment]
What do you mean similar to POS?

**Comment by danieramiz** [comment]
What I mean with "similar to POS" is the same paper format :

Paper Width | 2.28 inch (58 mm)

**Comment by DavBfr** [comment]
Yes, you can choose any size.
Check out this: https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin

**Comment by danieramiz** [comment]
Hey @DavBfr  That's exactly what I was looking for. 
Now I figured out. Thank you very much

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
