### ISSUE TITLE
FullPage with multiple children

### ISSUE THREAD

**Issue by kostaa** [DavBfr/dart_pdf#233]
I was wondering how to add a watermark (following your [example](https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_watermark_test.dart)) to a page that already has a custom paint that is drawing background decoration.  

In other words is there a way to combine the Waretmark  and the CustomPaint widgets so that they can be passed to the FullPage:: child property? Or would this require the FullPage to inherit from the MultiChildWidget?

**Comment by DavBfr** [comment]
You can use Stack to ... stack multiple widgets on each other

**Comment by kostaa** [comment]
That did the trick thanks.
