### ISSUE TITLE
Hi, there. Have you met that problem?

### ISSUE THREAD

**Issue by lulululuding** [DavBfr/dart_pdf#234]
Actually I am creating PDF file that meet this problem, it happened during pdf save.
The source is from java created via JSON parsed. There are number, decimal, english and Chinese characters within the context, Chinese characters are the most. Actually, in most of the context , it is ok. But in some words, it happens this problem. I have no ideal why it happened. Could you give me some advice?

version: 1.2.4 1.5.0 (Both)
Android SDK: 29
Java 8

I/flutter (24193): RangeError (byteOffset): Index out of range: index should be less than 276: 276

The stack is down below
ByteDataView.setUint8 (dart:typed_data-patch/typed_data_patch.dart:4340:7)
I/flutter (24193): #1      TtfWriter.withChars (package:pdf/src/ttf_writer.dart:203:18)
I/flutter (24193): #2      PdfTtfFont._buildType0 (package:pdf/src/ttffont.dart:90:38)
I/flutter (24193): #3      PdfTtfFont._prepare (package:pdf/src/ttffont.dart:134:7)
I/flutter (24193): #4      PdfObject._write (package:pdf/src/object.dart:53:5)
I/flutter (24193): #5      PdfOutput.write (package:pdf/src/output.dart:69:8)
I/flutter (24193): #6      SetMixin.forEach (dart:collection/set.dart:148:30)
I/flutter (24193): #7      PdfDocument._write (package:pdf/src/document.dart:179:13)
I/flutter (24193): #8      PdfDocument.save (package:pdf/src/document.dart:187:5)
I/flutter (24193): #9      Document.save (package:pdf/widgets/document.dart:76:21)
I/flutter (24193): #10     generateJ2 (package:pve/PDF/J2LocalGen.dart:275:33)
I/flutter (24193): #11     _DirectWidgetState._save (package:pve/widgets/J2/DirectWidget.dart:89:22)
I/flutter (24193): <asynchronous suspension>
I/flutter (24193): #12     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
I/flutter (24193): #13     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
I/flutter (24193): #14

**Comment by DavBfr** [comment]
Maybe an issue with the composition map in that font.
Can you send me the font and a minimal example that produces the issue?

**Comment by zwchenlong** [comment]
Hi, I encounter exactly the same issue.  May I know the solution please?

**Comment by idootop** [comment]
> 
> 
> Maybe an issue with the composition map in that font.
> Can you send me the font and a minimal example that produces the issue?

#355 

In my case, there is no problem when I print a two-page Chinese document in separate pages, indicating that the font file is fine, but this error occurs once the two pages of the Chinese document are printed together in MultiPage. :(

**Comment by idootop** [comment]
Here's how I solved it.

![Snipaste_2020-08-10_20-08-45](https://user-images.githubusercontent.com/35302658/89781225-7cb9d000-db45-11ea-9564-20122c11a8de.png)

**Comment by shawn736** [comment]
> Here's how I solved it.
> 
> ![Snipaste_2020-08-10_20-08-45](https://user-images.githubusercontent.com/35302658/89781225-7cb9d000-db45-11ea-9564-20122c11a8de.png)

Thank you, it helps! 
I also meet the same error 'Index out of range: index should be less than 276: 276'.
But,  I don't understand why the number is 257.

**Comment by idootop** [comment]
> 
> 
> > Here's how I solved it.
> > ![Snipaste_2020-08-10_20-08-45](https://user-images.githubusercontent.com/35302658/89781225-7cb9d000-db45-11ea-9564-20122c11a8de.png)
> 
> Thank you, it helps!
> I also meet the same error 'Index out of range: index should be less than 276: 276'.
> But, I don't understand why the number is 257.

Look here.
![Snipaste_2020-08-12_07-58-11](https://user-images.githubusercontent.com/35302658/89960463-acfe8d00-dc71-11ea-9a6b-aa5a04b7dbf9.png)
When i>257，Index（i+8）will out of range: index should be less than 276: 276

**Comment by shawn736** [comment]
> > > Here's how I solved it.
> > > ![Snipaste_2020-08-10_20-08-45](https://user-images.githubusercontent.com/35302658/89781225-7cb9d000-db45-11ea-9564-20122c11a8de.png)
> > 
> > 
> > Thank you, it helps!
> > I also meet the same error 'Index out of range: index should be less than 276: 276'.
> > But, I don't understand why the number is 257.
> 
> Look here.
> ![Snipaste_2020-08-12_07-58-11](https://user-images.githubusercontent.com/35302658/89960463-acfe8d00-dc71-11ea-9a6b-aa5a04b7dbf9.png)
> When i>257，Index（i+8）will out of range: index should be less than 276: 276

Thank you.
I should have been more careful.
It helped a lot and saved me a lot of time.

**Comment by DavBfr** [comment]
I'm working on a proper fix.

**Comment by idootop** [comment]
> I'm working on a proper fix.

Thanks^^
