### ISSUE TITLE
Slight formatting issue for decoding to Latin1 exception

### ISSUE THREAD

**Issue by GregoryConrad** [DavBfr/dart_pdf#240]
**Describe the bug**
Using the ```assert(false, '''The Multiline String''');``` in ```pdf/lib/src/font.dart``` causes the exception to be improperly formatted when thrown:
```
Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
Unable to print: Assertion failed: org-dartlang-app:///packages/pdf/src/font.dart:145:14
false
"\n---------------------------------------------Can not decode the string to Latin1.\nThis font does not support Unicode characters.\nIf you want to use strings other than Latin strings, use a TrueType (TTF) font instead.\nSee https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management\n---------------------------------------------\n"
```
Although this is minor, if the exception were to be displayed to a user, it would be confusing and hard to read.

**Suggested Fix**
It looks like the assert is the cause of the formatting issue, so a different method of passing the exception back instead of assert would be needed. Not sure of how to do this at the moment, but I am trying different solutions.

**Comment by GregoryConrad** [comment]
Here is some proposed code that I can turn into a pull request:

font.dart:
```
static const String CANNOT_DECODE_TO_LATIN1_1_MESSAGE =
      '''---------------------------------------------
Can not decode the string to Latin1.
This font does not support Unicode characters.
If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
---------------------------------------------''';

PdfFontMetrics stringMetrics(String s) {
    if (s.isEmpty) {
      return PdfFontMetrics.zero;
    }

    try {
      final Uint8List chars = latin1.encode(s);
      final Iterable<PdfFontMetrics> metrics = chars.map(glyphMetrics);
      return PdfFontMetrics.append(metrics);
    } catch (e) {
      throw '$e\n$CANNOT_DECODE_TO_LATIN1_1_MESSAGE';
    }
  }

void putText(PdfStream stream, String text) {
    try {
      stream
        ..putByte(40)
        ..putTextBytes(latin1.encode(text))
        ..putByte(41);
    } catch (e) {
      throw '$e\n$CANNOT_DECODE_TO_LATIN1_1_MESSAGE';
    }
  }
```

I found the problematic handling of the message (using assert(false, ...)) in both of those functions, so I replaced it with my working version. Any suggestions before I turn this into a pull request?

**Comment by DavBfr** [comment]
Please do a PR, it will be easier to comment on it.
Remarks:
- The assert/Latin1 message is for the developer only, Production code will just raise an exception.
   If you want both, the best is to embed the message in `assert((){ print(...); return true;}());`
- I will have to check the other implementations iOS, Android and macOS.

**Comment by GregoryConrad** [comment]
Oops, apologies. I misinterpreted the expected behavior. My PR throws the Latin1 message along with the exception.

**Comment by GregoryConrad** [comment]
Fixed in recent commit
