### ISSUE TITLE
Documentation / example issue

### ISSUE THREAD

**Issue by FluerasRares** [DavBfr/dart_pdf#242]
**Describe the bug**
It is not actually a bug, it's more of an observation from my part. 

-> In the https://pub.dev/packages/printing#-example-tab- the ```import 'package:pdf/widgets.dart' as pdf;``` works as expected but the naming is a bit off. You actually import the ```pdfWidgets``` (Document, Page, etc...). Why do I mention this ? Because in the ```final Document doc = Document();``` the document is actually ```final pdfWidgets.Document doc = pdfWidgets.Document();```. So the example (copy - paste style) doesn't work.

-> It's not a big deal (as mentioned) :) but it's important for people who don't clone your repository (or a at the beginning of the journey) and check the sources understand the concept properly.

Thanks!

**Comment by DavBfr** [comment]
Thanks, I will update that.

**Comment by FluerasRares** [comment]
And by the way good job with the Widgets :) very helpful

**Comment by DavBfr** [comment]
Fixed in the master branch.
What else a newcomer can struggle with?

**Comment by FluerasRares** [comment]
When will the master be available for the new version ? I am still testing it, probably next week I'll contact you if anything else comes up :)

**Comment by FluerasRares** [comment]
This pdf / printing Widget is actually pretty important for me in the future, so I will definitely contact you for any details / observations

**Comment by DavBfr** [comment]
Maybe next week.

**Comment by DavBfr** [comment]
What's your use case?

**Comment by FluerasRares** [comment]
Do you have an example to actually load an existing PDF file in the PdfImage ? (I can't seem to find it) For the moment I just want to see how one can be printed out (properly)

**Comment by FluerasRares** [comment]
From your example I saw a .pdf generated and loaded using Dart widgets, which is fine...But I need something that is taken into consideration as an image (mostly). Do you understand ? :)

**Comment by DavBfr** [comment]
PdfImage is to load a bitmap like a jpeg or png, not a pdf file.

**Comment by FluerasRares** [comment]
I know, I expressed myself incorrectly. I wanted to ask if you have implementing something (an example) to load a PDF and add it in the .Page (similar to the flow which loads an image)

**Comment by FluerasRares** [comment]
Or if you have any ideas because building a PDF (as in your example) is also fine, but it's a bit hard to replicate a complex PDF which I need to sync with the BE

**Comment by DavBfr** [comment]
No, this library cannot load a Pdf, only build a new one.

**Comment by DavBfr** [comment]
If you don't need to change anything to the document, you can just print it using `Printing.layoutPdf`

**Comment by FluerasRares** [comment]
I am trying to create a custom Widget for this and will get back to you next week. It's not that easy to just use Printing.layoutPdf() because it expects a List<int> (Future) and because I need to actually add the content somewhere (I checked the image.dart and how the flow goes, graphics and stuff and it is not complicated but a bit of work is required). Correct ? I don't need to change anything in the document, can you give me an example of what your idea is ? (If I already have the .pdf in my assets)

**Comment by FluerasRares** [comment]
Can we discuss somewhere else :) ?

**Comment by DavBfr** [comment]
send me a mail

**Comment by DavBfr** [comment]
```dart
void _print() {
   final pdf = await rootBundle.load("document.pdf");
   Printing.layoutPdf((_) => pdf);
}
```

Not tested, you might need to convert `pdf` to a List<int>

**Comment by FluerasRares** [comment]
I was thinking a bit more complicated. Will test tomorrow, :+1:, thanks. Anyway we'll keep in touch. flueras.rares@gmail.com is my e-mail. We can discuss more there :). If it doesn't work (looks a bit too easy to work), I will create the List of int (as I have already started) using the canvas builder based on your Widgets and we'll talk more afterwards. Have a great day!

**Comment by FluerasRares** [comment]
Hello :) change of plans from my part, loading PDF no longer needed (at the moment) but I can help you with it some time in the future if you need it (looks challenging). One question though, the document.save(), does it actually store the printing document on my mobile application ? Or is it just temporarily saved ? I can't seem to find anything related to this and I'm just curious.

**Comment by FluerasRares** [comment]
Also, another question is that: can the library generate .prn files (I have a special printer) and the rendering is a bit off if I create the page content manually (example: for a simple Text widget I get issues on rendering, no matter which format I use).

**Comment by DavBfr** [comment]
document.save() generates the document in memory.
.prn files are windows output for raw proprietary printer data. Usually works only for a specific printer model and make.

**Comment by FluerasRares** [comment]
Yup, sadly that's my example printer at the moment :), will have to check another way

**Comment by MalteMagnussen** [comment]
@DavBfr - Where can I find documentation for this package? 

It is completely trial and error for me right now. 

I can't find any proper documentation and examples.

**Comment by DavBfr** [comment]
@MalteMagnussen You have a full demo here: https://github.com/DavBfr/dart_pdf/tree/master/demo
Almost all the widgets have their unit tests here: https://github.com/DavBfr/dart_pdf/tree/master/pdf/test
Some documentation in the wiki: https://github.com/DavBfr/dart_pdf/wiki
And the API doc is here: https://pub.dev/documentation/pdf/latest/widget/widget-library.html

**Comment by MalteMagnussen** [comment]
@DavBfr Thank you. I will have a look!
