### ISSUE TITLE
Printing.layoutPdf does not return on Flutter Web on master branch

### ISSUE THREAD

**Issue by GregoryConrad** [DavBfr/dart_pdf#243]
**Describe the bug**
When running the plugin from ```master``` on Flutter Web, ```Printing.layoutPdf``` never returns unless an exception is thrown. In the latest release, ```true``` is returned almost immediately, assuming the print dialog window opens (in case of an error, ```false``` is not returned and the function also does not return).

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
try {
    final doc = (pw.Document()
      ..addPage(pw.Page(build: (_) => pw.Center(child: pw.Text("Hi")))));
    print('Made it past creation');
    bool result = await Printing.layoutPdf(onLayout: (format) => doc.save());
    print('Made it past print with result: $result');
  } catch (e) {
    print('Caught the exception:\n$e');
  }
```

**Expected behavior**
```Printing.layoutPdf``` to return, if it does not throw an exception.

Note: running on Chrome 80

**Comment by GregoryConrad** [comment]
With the latest commit on master, the print dialog no longer opens and no value is returned.

**Comment by DavBfr** [comment]
Any error message?

**Comment by GregoryConrad** [comment]
Not that I can tell

**Comment by GregoryConrad** [comment]
Would you like me to try anything or give you more information about my setup?

**Comment by DavBfr** [comment]
I can't reproduce, it always returns with the latest master branch.

**Comment by GregoryConrad** [comment]
Just tried master branch again, and it didn't work.

The code never goes past ```final js.JsObject win =
          js.JsObject.fromBrowserObject(frame)['contentWindow'];``` in ```printing_web.dart```. Any ideas?

My full chrome version:
```
Google Chrome | 80.0.3987.132 (Official Build) (64-bit)
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Linux
JavaScript | V8 8.0.426.26
```

**Comment by GregoryConrad** [comment]
Looks like it is because that line throws an exception (that is absorbed somewhere):
```SecurityError: Blocked a frame with origin "http://localhost:38311" from accessing a cross-origin frame.```

I do not know this area of web development really well so I don't know how to fix it.

**Comment by DavBfr** [comment]
Does this one works: https://davbfr.github.io/dart_pdf/ ?

**Comment by GregoryConrad** [comment]
Yes, the print dialog opens.

**Comment by GregoryConrad** [comment]
Thank you! Any idea when this will be turned into a release?

**Comment by DavBfr** [comment]
Maybe this week-end.

**Comment by GregoryConrad** [comment]
Great, thanks!
