### ISSUE TITLE
Cannot vertically center Table in page

### ISSUE THREAD

**Issue by thherman** [DavBfr/dart_pdf#245]
I would like to be able to vertically center a Table on the page in a MultiPage environment.

I tried Center widget, Column with MainAxisAlignment.center, but none of these work.

The only way I found to do this is to put the Table in a container of fixed height and center it inside. However, with this solution, the Table will not be split on two pages if it gets too big.

Is it possible to do it in a more dynamic way ?

**Comment by DavBfr** [comment]
I don't have a solution for that.

**Comment by DavBfr** [comment]
It's now possible with version 1.9.0 using mainAxisAlignment
