### ISSUE TITLE
PdfImage throws error in Flutter web

### ISSUE THREAD

**Issue by robospot** [DavBfr/dart_pdf#246]
ok, I give up. I spent several days trying to pass in image to PDF in Flutter web.
Please provide a sample on how to show an image in generated PDF using Flutter web.
**Describe the bug**
pdf.save() in generatePDF() method throws an error Chrome console:
```
Uncaught (in promise) Error: RangeError (index): Index out of range: index should be less than 876: 876
    at Object.throw_ [as throw] (dart_sdk.js:4070)
    at Object._checkValidIndex (dart_sdk.js:35249)
    at Uint8Array.[dartx._get] (dart_sdk.js:34476)
    at pdf.PdfImage.__.[_prepare] (image.dart:183)
    at pdf.PdfImage.__.[_write] (object.dart:53)
    at pdf.PdfOutput.new.write (output.dart:69)
    at _HashSet.new.forEach (dart_sdk.js:42086)
    at pdf.PdfDocument.new.[_write] (document.dart:179)
    at pdf.PdfDocument.new.save (document.dart:187)
    at widgets.Document.new.save (document.dart:76)
    at generatePDF (inspection_overview_screen.dart:153)
    at generatePDF.next (<anonymous>)
    at onValue (dart_sdk.js:41547)
    at _RootZone.runUnary (dart_sdk.js:41432)
    at _FutureListener.thenAwait.handleValue (dart_sdk.js:37107)
    at handleValueCallback (dart_sdk.js:37608)
    at Function._propagateToListeners (dart_sdk.js:37640)
    at _Future.new.[_completeWithValue] (dart_sdk.js:37502)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:37519)
    at Object._microtaskLoop (dart_sdk.js:41646)
    at _startMicrotaskLoop (dart_sdk.js:41652)
    at dart_sdk.js:37845
```
**To Reproduce**
PDF generation call
```
generatePDF() async {
    ByteData logoBytes = await rootBundle.load('assets/image.png');
    var logo = logoBytes.buffer.asUint8List();
    final pdf = await generateDocument(PDF.PdfPageFormat.a4, logo);
    File file = MemoryFileSystem().file('example.pdf')
      ..writeAsBytesSync(pdf.save());
    JS.context.callMethod('ToFile', [file.readAsBytesSync()]);
  }
}
```
PDF generation
```
import 'dart:async';
import 'dart:typed_data';
import 'package:flutter/widgets.dart' as w;
import 'package:inspections/models/inspection.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' ;

Future<Document> generateDocument(
    PdfPageFormat format,  Uint8List  logo) async {
  final Document doc = Document(
    title: 'name',
    author: 'author',
  );
  PdfImage sample = PdfImage(doc.document, image: logo, width: 100, height: 100, alpha: true);

....
```
index.html
```
...
 <script>
  function ToFile(arg) {
    let blob = new Blob([arg], {type: "application/pdf"});
    let objectUrl = URL.createObjectURL(blob);
    window.open(objectUrl)
  }
  </script>
...
```

**Expected behavior**
PDF document with image should generates without errors

**Screenshots**

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.
[√] Flutter (Channel dev, v1.15.20, on Microsoft Windows [Version 10.0.18362.720], locale ru-RU)
    • Flutter version 1.15.20 at C:\flutter_SDK\flutter
    • Framework revision 4049889d9e (6 days ago), 2020-03-10 20:05:41 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Timak\AppData\Local\Android\Sdk\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Timak\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Timak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [X] Browser

**Smartphone (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 80.0.3987.132

**Additional context**

**Comment by robospot** [comment]
Also seems that await pdfImageFromImageProvider never returns value
```
import 'package:flutter/widgets.dart' as w;

ByteData byteData = await rootBundle.load('assets/image.png');
  var k = byteData.buffer.asUint8List();
  var temp = await pdfImageFromImageProvider(
          pdf: doc.document,
          image: w.MemoryImage(k));
```

**Comment by robospot** [comment]
small update:
If I set height and width of the image to 10, PDF generates without issues, but if I will increase that value, the same exception throws:
working scenario:
```
ByteData byteData = await rootBundle.load('assets/image.png');
  var k = byteData.buffer.asUint8List();
  PdfImage dd = PdfImage(doc.document, image: k, height: 10, width: 10);

...
Image(dd, height: 10, width: 10),
```

```
final pdf = await generateDocument(PDF.PdfPageFormat.a4, inspection);
    File file = MemoryFileSystem().file('example.pdf')
      ..writeAsBytesSync(pdf.save());
    JS.context.callMethod('ToFile', [file.readAsBytesSync()]);
```
when PdfImage dd = PdfImage(doc.document, image: k, height: 20, width: 20);
I am getting error:
```
Error: RangeError (index): Index out of range: index should be less than 876: 876
    at Object.throw_ [as throw] (dart_sdk.js:4066)
    at Object._checkValidIndex (dart_sdk.js:35230)
    at Uint8Array.[dartx._get] (dart_sdk.js:34457)
    at pdf.PdfImage.__.[_prepare] (image.dart:183)
    at pdf.PdfImage.__.[_write] (object.dart:53)
    at pdf.PdfOutput.new.write (output.dart:69)
    at _HashSet.new.forEach (dart_sdk.js:42067)
    at pdf.PdfDocument.new.[_write] (document.dart:179)
    at pdf.PdfDocument.new.save (document.dart:187)
    at widgets.Document.new.save (document.dart:76)
    at generatePDF (VM1043 inspection_overview_screen.dart.lib.js:2125)
    at generatePDF.next (<anonymous>)
    at onValue (dart_sdk.js:41528)
    at _RootZone.runUnary (dart_sdk.js:41413)
    at _FutureListener.thenAwait.handleValue (dart_sdk.js:37088)
    at handleValueCallback (dart_sdk.js:37589)
    at Function._propagateToListeners (dart_sdk.js:37621)
    at _Future.new.[_completeWithValue] (dart_sdk.js:37483)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:37500)
    at Object._microtaskLoop (dart_sdk.js:41627)
    at _startMicrotaskLoop (dart_sdk.js:41633)
```

**Comment by lunaticcoding** [comment]
I have the same issue on mobile right now :S

**Comment by DavBfr** [comment]
You can't pass a png image to PdfImage, It can load only raw RGBA data.

**Comment by lunaticcoding** [comment]
I changed the format to rawRGBA but the error persists :S In the function call I await the getWidget(...) call 

```
class ImageWrapper {
  static Future<pdfWidgets.Image> getWidget(PdfDocument document, BuildContext context, GlobalKey _globalkey) async {
    Uint8List imageData = await _capturePng(context, _globalkey);
    print("what");
    print(imageData.length);
    PdfImage img = PdfImage(document, image: imageData, height: 51, width: 873);
    return pdfWidgets.Image(img);
  }

  static Future<Uint8List> _capturePng(BuildContext context, GlobalKey key) async {
    RenderRepaintBoundary wrappedWidget = key.currentContext.findRenderObject();
    try {
      while (wrappedWidget.debugNeedsPaint) {
        print("Waiting for boundary to be painted.");
        await Future.delayed(const Duration(milliseconds: 20));
      }
      ui.Image image = await wrappedWidget.toImage();
      print(image.width);
      print(image.height);
      ByteData byteData =
          await image.toByteData(format: ui.ImageByteFormat.rawRgba);
      var pngBytes = byteData.buffer.asUint8List();
      return pngBytes;
    } catch (e) {
      print(e);
    }
    return null;
  }
}
```

**Comment by lunaticcoding** [comment]
<img width="998" alt="Screenshot 2020-03-19 at 21 48 04" src="https://user-images.githubusercontent.com/26603883/77113843-c89b9980-6a2b-11ea-9a79-02699097ed0f.png">

**Comment by lunaticcoding** [comment]
<img width="271" alt="Screenshot 2020-03-19 at 21 53 58" src="https://user-images.githubusercontent.com/26603883/77114070-30ea7b00-6a2c-11ea-8a2d-0c2a2b4ffa9e.png">

**Comment by DavBfr** [comment]
You need to pass in the right width and height
like:
PdfImage img = PdfImage(document, image: imageData, height: image.height, width: image.width);
imageData.length should be exactly width * height * 4

**Comment by lunaticcoding** [comment]
My bad I thought I did. Seriously, man, you're a lifesaver :P Thank you so very much :) It's working now

**Comment by robospot** [comment]
ufff.. finaly it works! David, thanks a lot!
