### ISSUE TITLE
RichText - undeline in the sentence

### ISSUE THREAD

**Issue by ElaineSchwner** [DavBfr/dart_pdf#248]
**Describe the bug**
Trying to write a contract with underline in some sentences, makes the underline goes overline.
In other widget, not the pdf, it works normally.

**To Reproduce**
    pdf.addPage(MultiPage(
        pageFormat:
            PdfPageFormat.a4.copyWith(marginBottom: 1.0 * PdfPageFormat.cm),
        build: (Context context) => <Widget>[
              Container(
                  alignment: Alignment.center,
                  margin: const EdgeInsets.only(
                      top: 1.0 * PdfPageFormat.cm,
                      bottom: 1.0 * PdfPageFormat.cm),
                  child: Text("PROCURAÇÃO",
                      style: TextStyle(
                          fontWeight: FontWeight.bold,
                          decoration: TextDecoration.underline))),
              RichText(
                softWrap: true,
                textAlign: TextAlign.justify,
                text: TextSpan(
                  style: TextStyle(),
                  children: <TextSpan>[
                    TextSpan(
                        text: 'PODERES:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          decoration: TextDecoration.underline,
                        )),
                    TextSpan(
                        text:
                            "	 Os mais amplos e ilimitados poderes para representar o(a) Outorgante perante o foro em geral, judicial, extrajudicial ou arbitral, em qualquer instância ou grau de jurisdição, a fim de defenderem seus interesses e proporem ações que julgarem necessárias, conferindo aos Outorgados os poderes das cláusulas "),
                    TextSpan(
                        text: "'ad e extra judicia'",
                        style: TextStyle(fontStyle: FontStyle.italic)),
                    TextSpan(
                        style: TextStyle(),
                        text:
                            ", para representarem-no(a) em Juízo ou fora dele, para o fim de propor e/ou contestar ações cíveis, falimentares, criminais, cautelares, requerer, promover medidas e diligências, inclusive mandado de segurança, intervir, requerer certidões, prestar cauções, habilitar créditos, assinar termos e compromissos, acompanhar feitos até final decisão, com trânsito em julgado, firmar acordos, representa-lo em cumprimento de sentença, e quaisquer outras medidas judicias ou administrativas sobre o fato abaixo narrado, outorgando-lhes ainda os "),
                    TextSpan(  style: TextStyle(
                      fontWeight: FontWeight.bold,
                      decoration: TextDecoration.underline,
                    ),
                        text:
                            'especiais poderes para confessar, reconvir, variar de ação, acordar, transigir, desistir, receber, requerer alvarás de levantamento, levantar valores e dar quitação ',
                      ),
                    TextSpan(
                        text:
                            "notificar, interpelar, protestar, impetrar mandados de segurança, assinar termos e compromissos, declarar residência e estado de hipossuficiência e substabelecer a quem convier,",
                        style: TextStyle(fontWeight: FontWeight.bold)),
                    TextSpan(
                        text:
                            " com ou sem reservas de iguais poderes, independente de necessidade de intimação ou ciência do(a) Outorgante, podendo os Outorgados enfim, praticarem todos os atos necessários ao bom e fiel cumprimento do mandato, que é outorgado com fim específico para representar o(a) Outorgante em Ações de Reparação por Dano Ambiental, Dano Moral e Material, e/ou Compensações, extra e/ou judiciais, propostas em razão dos danos morais e materiais por ele(a) sofrido por conta de danos ambientais e/ou poluições marítimas ocorridos que afetaram ou venham a afetar seu exercício profissional, e/ou a sua cultura e modo de ser e viver, especialmente no que se refere ao acidente ambiental a seguir nominado, especialmente por conta do "),
                    TextSpan(
                        text: Projeto,
                        style: TextStyle(
                          fontStyle: FontStyle.italic,
                          decoration: TextDecoration.underline,
                        )),

                    TextSpan(
                        text:
                            ", mediante o pagamento dos honorários advocatícios pactuados, que serão descontados do valor obtido na demanda ajuizada nos termos do Contrato de Prestação de Serviços Profissionais de Advogado assinado nesta data. "),

                    TextSpan(
                        text:
                            "O(A) Outorgante declara, desde já, nos termos da Lei 1.060/50 e dos arts. 98 e seguintes do Novo Código de Processo Civil, sob as penas da lei, que até a presente data não pode suportar as despesas com custas processuais sem prejuízo de sua subsistência e de sua família, pois é pessoa de baixa renda e atualmente suporta difícil condição de trabalho e subsistência, inclusive causa de pedir da ação. Declara ainda, a anuência aos substabelecimentos dos poderes que porventura se fizerem necessários a outros advogados, com ou sem reserva de poderes e independentemente de notificação prévia.",
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          decoration: TextDecoration.underline,
                        )),

 
                  ],
                ),
              ),
            
            ]));

**Flutter Doctor**
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.0)
[✓] Connected device (1 available)

**Comment by DavBfr** [comment]
This is fixed in the master branch.
Underline with justified text was not working.
I also improved the decorations with a nicer render.
