### ISSUE TITLE
Load any widget (transformed into an image) into the pdf

### ISSUE THREAD

**Issue by lunaticcoding** [DavBfr/dart_pdf#251]
**Is your feature request related to a problem? Please describe.**
I currently want to export a pdf containing charts. I currently use the code in the link to save them as images and then load them into the pdf. It would be way better if I could just pass them to a container and have the plugin do this work for me. 

**Describe the solution you'd like**
It would be nice to have some wrapper, that takes any widget and does all the transformation for you. 

**Describe alternatives you've considered**
Creating the pdf on a server in python and downloading it then.

**Additional context**
Code used to transfer a widget into an image. 
https://medium.com/flutter-community/export-your-widget-to-image-with-flutter-dc7ecfa6bafb

**Comment by lunaticcoding** [comment]
I could also work on this and submit a PR if that is okay :) Or maybe I overlooked something and this widget already exists. :O

**Comment by DavBfr** [comment]
Yes, feel free to submit a PR.

**Comment by lunaticcoding** [comment]
@DavBfr Do you prefer in Integration tests or rather no tests? Because currently Flutter only supports saving widgets to images if they are actively being rendered on a physical device.

**Comment by DavBfr** [comment]
If you can do integration tests, that's fine.

**Comment by dmvvilela** [comment]
If i may ask, how did you calculate pixelRatio in toImage method?
I am doing this too to convert widgets to PDF.
