### ISSUE TITLE
Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

### ISSUE THREAD

**Issue by Spepardy** [DavBfr/dart_pdf#252]
I get the above error when i run the below code;

`// ignore_for_file: omit_local_variable_types
import 'package:flutter/material.dart' as flutterMaterial;
import 'package:path_provider/path_provider.dart';
import 'dart:io';
//import 'dart:async';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';
//import 'package:printing/printing.dart';
//import 'package:flutter/services.dart';

class ParcelStatus extends flutterMaterial.StatefulWidget {
  final String parcelUniqueCode;
  ParcelStatus(this.parcelUniqueCode);
  @override
  _ParcelStatusState createState() => _ParcelStatusState();
}

class _ParcelStatusState extends flutterMaterial.State<ParcelStatus> {
  Future<Directory> _tempDirectory;

  @override
  void initState() {
    super.initState();
    _preview();
  }

  Future<void> _preview() async {
    final pdf = Document();

    pdf.addPage(Page(
        pageFormat: PdfPageFormat.a4,
        build: (Context context) {
          return Center(
            child: Text("Hello World"),
          );
        }));

    final file = File("/data/user/0/com.example.vip_express/app_flutter/example.pdf");
    await file.writeAsBytes(pdf.save());

    /* final File file =
        File('/data/user/0/com.example.vip_express/app_flutter/example.pdf');
    file.writeAsBytesSync(pdf.save()); */
    /* await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save()); */
  }

  @override
  flutterMaterial.Widget build(flutterMaterial.BuildContext context) {
    return flutterMaterial.Scaffold(
      appBar: flutterMaterial.AppBar(
        title: flutterMaterial.Text("Parcel Status"),
      ),
      body: flutterMaterial.Container(
        child: flutterMaterial.GestureDetector(
          onTap: () async {
            //Directory tempDir = await getTemporaryDirectory();
            _tempDirectory = getTemporaryDirectory();
            //String tempPath = _tempDirectory.path;

             Directory tempDir = await getTemporaryDirectory();
            //Future <Directory> _appDocDir = getApplicationDocumentsDirectory();
            String tempDirPath = tempDir.path;
            print(tempDir);
            print(tempDirPath);

            Directory appDocDir = await getApplicationDocumentsDirectory();
            //Future <Directory> _appDocDir = getApplicationDocumentsDirectory();
            String appDocPath = appDocDir.path;
            print(appDocDir);
            print(appDocPath);
            print(_tempDirectory);
            print('Please show preview');
            _preview();
          },
          child: flutterMaterial.Text('My God is faithful indeed.'),
        ), //_preview,//flutterMaterial.Text('My God is faithful indeed.'),
      ),
    );
  }
}`

I noticed that when i change the "Text("Hello World")" to "Container()" in the below block of code, the error disappers;

pdf.addPage(Page(
        pageFormat: PdfPageFormat.a4,
        build: (Context context) {
          return Center(
            child: Text("Hello World"),
          );
        }));

I'm expecting to save to my phone so i can access it as a pdf file.

**Flutter Doctor**
Output of `flutter doctor -v` 

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17134.1246], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Floo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Floo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Infinix NOTE 3 • 01797106A1301858 • android-arm64 • Android 6.0 (API 23)

• No issues found!

I'm using Adroid Version 6.0

**Comment by DavBfr** [comment]
Just follow the given link to get more information.

**Comment by Spepardy** [comment]
I've read everything couldn't solve my problem, Sir. 
The suggested solution was base on TextStyle and I didn't use any styling of my text or font.
Please re-look at my error.
Thank you.

**Comment by DavBfr** [comment]
This error message is just a warning, if you never use non latin strings you can ignore it. It is not displayed in release mode.

**Comment by Spepardy** [comment]
Alright, Sir. 
Thank you.
