### ISSUE TITLE
FontWeight thinner

### ISSUE THREAD

**Issue by oom-** [DavBfr/dart_pdf#253]
**Is your feature request related to a problem? Please describe.**
Impossible to set this value, only **bold** and **normal** are avaible.
``pw.FontWeight.w200``

**Describe alternatives you've considered**
Tryed to change the font, opacity etc... but not good way at all.

**Additional context**
Try to set a 

```dart
pw.Paragraph(
                textAlign: pw.TextAlign.center,
                  text:
                      'Random text', 
                      style: pw.TextStyle(  fontWeight: pw.FontWeight.w200),)
```

**Comment by DavBfr** [comment]
This is just for normal and bold. To use thinner fonts, just download one and load it.
https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
