### ISSUE TITLE
Cannot add image to PDF document

### ISSUE THREAD

**Issue by flutternoob** [DavBfr/dart_pdf#254]
I have imported the image and PDF libraries. I also entered the code for adding an image to PDF exactly as per the instructions on the pub.dev PDF package page. However I cannot add an image to the PDF document. It will also be nice if it were possible to add a custom logo to the PDF page. I tried adding the image as per the instructions on the package page, but couldn't. Please help. Everything else works fine, so far. Thanks

**Comment by DavBfr** [comment]
What code do you use for that?

**Comment by flutternoob** [comment]
Here is the code:

```
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';
import 'dart:async';
import 'package:path_provider/path_provider.dart';
import 'package:image/image.dart';

Future PDFCheck() async{

//Beginning of code from pub.dev link, image is a custom image
  final Document pdf = Document();
  final img = decodeImage(File('images/money.png').readAsBytesSync());
  final image = PdfImage(
    pdf.document,
    image: img.data.buffer.asUint8List(),
    width: img.width,
    height: img.height,
  );

  pdf.addPage(Page(
      build: (Context context) {
        return Center(
          child: Image(image),
        ); // Center
      }));
//End of code from pub.dev link

  String pdfFilePath = '${(await getTemporaryDirectory()).path}/pdfFile.pdf';
  File pdfFile = File('${(await getTemporaryDirectory()).path}/pdfFile.pdf');
  pdfFile.writeAsBytesSync(pdf.save());
}
```

**Comment by DavBfr** [comment]
Use:
```dart
import 'package:image/image.dart' as im;
```
and
```dart
final img = im.decodeImage(File('images/money.png').readAsBytesSync());
```

**Comment by flutternoob** [comment]
Thanks for replying. The errors in red are no longer there. However when I run the application, I not get the following exception:

`E/flutter (21269): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = 'images/money.png' (OS Error: No such file or directory, errno = 2)`

The project consists of two Dart files, main.dart and pdfcheck.dart. I use AssetImage in the main.dart file, like so:

`
```
Widget getImageAsset() {
    AssetImage assetImage = AssetImage('images/money.png');
    Image image = Image(image: assetImage, width: 75, height: 75);
    return Container(
        margin: EdgeInsets.all(_minimumPadding * 10), child: image);
}
````

Here is the pubspec.yaml
  assets:
     - images/money.png

In pdfcheck.dart, I am using the following code:

`final img = im.decodeImage(File('images/money.png').readAsBytesSync());`

The path is the same in both cases, yet I get the error for the while using the path in pdfcheck.dart. When I call the getImageAsset() widget method in main.dart, there are no problems with the path.

**Comment by flutternoob** [comment]
Thanks for replying. The errors in red are no longer there.
