### ISSUE TITLE
No Colspan & Rowspan in Table 

### ISSUE THREAD

**Issue by Spepardy** [DavBfr/dart_pdf#256]
I couldn't find colspan and rowspan in which I could merge multiple columns into one as well as merging multiple rows as one in table. 
Thank you.

**Comment by DavBfr** [comment]
You're right, it's not implemented.

**Comment by DavBfr** [comment]
It's not supported on flutter

**Comment by DavBfr** [comment]
Duplicate of #167

**Comment by Spepardy** [comment]
Okay, thanks.
