### ISSUE TITLE
html widget to parse HTML content

### ISSUE THREAD

**Issue by yahya31415** [DavBfr/dart_pdf#257]
**Is your feature request related to a problem? Please describe.**
Ability to add html content to the pdf page

**Describe the solution you'd like**
an HTML(String content) widget that parses html content to the page

**Describe alternatives you've considered**
There is a separate html to pdf package that doesn't have the widget builder functionality

**Additional context**
None

**Comment by DavBfr** [comment]
Sorry, this is out of scope
