### ISSUE TITLE
I can't create a PDF in iOS

### ISSUE THREAD

**Issue by Noedsondutra** [DavBfr/dart_pdf#261]
I've found that the future:

await file.writeAsBytes(pdf.save());

is not finishing. 
Android works, iOS don't.

Does anyone have this problem too?

Dart version: 3.9.0
Flutter: 1.12.13+hotfix.9
iOS: 13.3.1
dart_pdf: ^1.6.0

**Comment by Noedsondutra** [comment]
I've found the problem.

Conditional type: pw.Text(anyBool ? "Great!" : "Nop") makes the future file.writeAsBytes(pdf.save()) await infinitely.

This bug is only for iOS, Android it works perfectly.

**Comment by DavBfr** [comment]
maybe this is because you run the iOS code using release or profile builds. If you use a debug build, you will have some assert that checks you are not doing something wrong. These checks are disabled in release builds for performance reasons.
