### ISSUE TITLE
Chart Widget for Pdf

### ISSUE THREAD

**Issue by lunaticcoding** [DavBfr/dart_pdf#264]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A widget that renders simple Charts. 
Should render at least 
- [ ] ScatterChart
- [x] LineChart
- [x] BarChart
Other chart types can be added on an as-needed basis. 

**Describe alternatives you've considered**
The alternative would have been rendering a flutter widget as an image and then adding that widget to the pdf (using the imageWrapper from printing - #251 ). This has the downside of needing to render the widget on your application before exporting it (it needs to be visible on the screen). 

**Additional context**

**Comment by lunaticcoding** [comment]
@DavBfr You can assign this issue to me if you'd like

**Comment by DavBfr** [comment]
Implemented in #278

**Comment by lunaticcoding** [comment]
@DavBfr When will it be available via pub.dev? :)

**Comment by DavBfr** [comment]
Maybe today.

**Comment by lunaticcoding** [comment]
Nice :D Thanks a lot :)

**Comment by robospot** [comment]
@lunaticcoding is there any chance of doing this for Flutter web?
Currently image.toByteData is not available for the web, can this be avoided?

**Comment by DavBfr** [comment]
@robospot check the latest 1.7.0 version, it has a new Chart Widget that draws line charts and should work on web.

https://github.com/DavBfr/dart_pdf/blob/master/test/golden/widgets-chart.pdf

**Comment by robospot** [comment]
Amazing! Thanks a lot!

**Comment by cenezoic123** [comment]
Hi, I'm really with flutter then I want to achieve adding chart in the PDF, kindly give me any sample of dataset that i will pass to the Chart widget..  thanks.

**Comment by cenezoic123** [comment]
Hi, I'm really with flutter then I want to achieve adding chart in the PDF, kindly give me any sample of dataset that i will pass to the Chart widget..  thanks.

**Comment by cenezoic123** [comment]
![chartpdf](https://user-images.githubusercontent.com/64458514/80473856-9e000300-893e-11ea-9fdc-58dbbb54ce6d.PNG)

May I knw the correct way how to call the Chart widget?, because i tried to call the chart widget in that way but I always got an error... :(

**Comment by lunaticcoding** [comment]
@cenezoic123 There is a valid example in the example/main.dart. The interface changed slightly: 
```
Container(
          width: 200,
          height: 100,
          child: Chart(
            grid: LinearGrid(
              xAxis: <double>[0, 2, 4, 8, 10],
              yAxis: <double>[0, 2, 4], 
            ),
            data: <DataSet>[
              LineDataSet(
                data: <LineChartValue>[
                    LineChartValue(x1, y1),
                    LineChartValue(x2, y2),
                    ...
                ],
              ),
            ],
          ),
        ),
```

@DavBfr Maybe a simple example in the example/main.dart would be good. (Or in the Readme.md)?

**Comment by DavBfr** [comment]
A document in the wiki would work too.

**Comment by lunaticcoding** [comment]
@DavBfr I can't edit the wiki though right? :O Will you add it then?

**Comment by DavBfr** [comment]
I just added curved lines:

<img width="965" alt="Screen Shot 2020-04-28 at 09 14 58" src="https://user-images.githubusercontent.com/1387855/80491489-c97bf100-8930-11ea-9fcb-6e1d3de5982c.png">

**Comment by DavBfr** [comment]
@lunaticcoding If you want to write documentation, the best is certainly to use dartdoc comments in the code.

**Comment by DavBfr** [comment]
I will add an example like this, which is actually generated using the pdf library:

<img width="445" alt="Screen Shot 2020-04-28 at 19 20 25" src="https://user-images.githubusercontent.com/1387855/80547121-610b2f00-8985-11ea-8454-4a5eab2d8e79.png">

**Comment by lunaticcoding** [comment]
@DavBfr wow that looks amazing. I’d add a dedicated scatterChart (dotsize in data point, shape object,...) as well as a pie chart over the following days if that is okay with you :)

**Comment by cenezoic123** [comment]
@lunaticcoding thanks a lot!

**Comment by cenezoic123** [comment]
Is there's a way that we can set string in the x-axis? cuz currently it's only accept double..

**Comment by lunaticcoding** [comment]
> Is there's a way that we can set string in the x-axis? cuz currently it's only accept double..

Currently not but I can add this functionality.

**Comment by cenezoic123** [comment]
> > Is there's a way that we can set string in the x-axis? cuz currently it's only accept double..
> 
> Currently not but I can add this functionality.

@lunaticcoding  That will be great Sir!, I'm looking forward to that Sir.

Thank you..

**Comment by DavBfr** [comment]
@cenezoic123 The master branch has some code to do it:

```dart
const dataTable = ['mon', 'tue', 'wed', 'thu', 'fri'];

Chart(
          grid: pw.LinearGrid(
            xAxis: [0, 1, 2, 3, 4],
            yAxis: [0, 1, 2, 3, 4],
            xAxisFormat: (v) {
                final iv = v.toInt();
                return dataTable[iv];
              },
          ),
          data: [
            pw.LineDataSet(
              data: your_data,
              ),
            ),
          ],
        );
```

**Comment by DavBfr** [comment]
https://davbfr.github.io/dart_pdf/

**Comment by cenezoic123** [comment]
@DavBfr I hope it will be available in the next version.

**Comment by DavBfr** [comment]
It's now available in pdf 1.8.0

**Comment by cenezoic123** [comment]
@DavBfr , Thank you Sir, but do you have  any documentation or just sample codes how to call the Chart Widget, cuz LinearGrid is no longer in the new version then I really don't know what data that I'm gonna supply for grid.

**Comment by DavBfr** [comment]
Yes, you can check the unit test here:

https://www.github.com/DavBfr/dart_pdf/tree/master/pdf/test/widget_chart_test.dart

And the demo page:

https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/report.dart

**Comment by cenezoic123** [comment]
@DavBfr  Thank you so much Sir

**Comment by gtuceturan** [comment]
> @cenezoic123 The master branch has some code to do it:
> 
> ```dart
> const dataTable = ['mon', 'tue', 'wed', 'thu', 'fri'];
> 
> Chart(
>           grid: pw.LinearGrid(
>             xAxis: [0, 1, 2, 3, 4],
>             yAxis: [0, 1, 2, 3, 4],
>             xAxisFormat: (v) {
>                 final iv = v.toInt();
>                 return dataTable[iv];
>               },
>           ),
>           data: [
>             pw.LineDataSet(
>               data: your_data,
>               ),
>             ),
>           ],
>         );
> ```

When grapich values is different from 0,1,2,3 how can change?
values=[0,3,5,10,15] String [ Normal,High....] like this I want to see texts
