### ISSUE TITLE
Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.

### ISSUE THREAD

**Issue by hs029** [DavBfr/dart_pdf#265]
**Describe the bug**
Got below exception when add big picture.
I/flutter (19191): Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.
I/flutter (19191): #0      MultiPage.generate.<anonymous closure> (package:pdf/widgets/multi_page.dart:183:11)
I/flutter (19191): #1      MultiPage.generate (package:pdf/widgets/multi_page.dart:187:8)
I/flutter (19191): #2      Document.addPage (package:pdf/widgets/document.dart:65:10)

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// 
final img = imageLib.decodeImage(File(imagePath).readAsBytesSync());
            final image = PdfImage(
              doc.document,
              image: img.data.buffer.asUint8List(),
              width: img.width,
              height: img.height,
            );
            bodies.add(pw.Center(child: pw.Image(image)));
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hs029** [comment]
My pic size is 1080 * 1920, I use A4.

**Comment by DavBfr** [comment]
Must be something else, can you put a fully working example I can reproduce?

**Comment by hs029** [comment]
static Future<pw.Document> generatePraxisPDF(pw.Document doc, Praxis praxis) async {
    final font = await rootBundle.load("static/font/MicrosoftYaqiHeiLight.ttf");
    final ttf = pw.Font.ttf(font);
    final pw.Theme theme = pw.Theme.withFont(
      base: ttf,
    );

    List<pw.Widget> contents = await _buildPraxisBody(doc, praxis);

    doc.addPage(pw.MultiPage(
        theme: theme,
        pageFormat: PdfPageFormat.a4,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        header: (pw.Context context) {
          if (context.pageNumber == 1) {
            return null;
          }
          return pw.Container(
              alignment: pw.Alignment.centerRight,
              margin: const pw.EdgeInsets.only(bottom: 3.0 * PdfPageFormat.mm),
              padding: const pw.EdgeInsets.only(bottom: 3.0 * PdfPageFormat.mm),
              decoration: const pw.BoxDecoration(
                  border: pw.BoxBorder(bottom: true, width: 0.5, color: PdfColors.grey)
              ),
              child: pw.Text(praxis.course.name, style: pw.Theme.of(context).defaultTextStyle.copyWith(color: PdfColors.grey)
              ),
          );
        },
        footer: (pw.Context context) {
          return pw.Container(
              alignment: pw.Alignment.centerRight,
              margin: const pw.EdgeInsets.only(top: 1.0 * PdfPageFormat.cm),
              child: pw.Text('第 ${context.pageNumber} 页（共 ${context.pagesCount} 页）',
                  style: pw.Theme.of(context).defaultTextStyle.copyWith(color: PdfColors.grey)
              )
          );
        },
        build: (pw.Context context) => <pw.Widget>[
          pw.Header(
              level: 0,
              child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: <pw.Widget>[
                    pw.Text(praxis.course.name, textScaleFactor: 2),
                    pw.Text(praxis.grade.name, style: pw.Theme.of(context).defaultTextStyle.copyWith(color: PdfColors.grey)),
                  ]
              )
          ),
          pw.Wrap(
            children: contents
          ),
        ]
      )
    );

    return doc;
  }


  static Future<ui.Image> _toQrImage(String text) async {
    try {
      final image = await QrPainter(
        data: text,
        version: QrVersions.auto,
        gapless: false,
        color: Colors.black,
        emptyColor: Colors.transparent,
      ).toImage(40);
      return image;
    } catch (e) {
      throw e;
    }
  }


  static Future<List<pw.Widget>> _buildPraxisBody(pw.Document doc, Praxis praxis) async {
    List<PraxisContent> list = praxis.body;

    List<pw.Widget> bodies = [];

    ui.Image uiImage = await _toQrImage(praxis.sn);
    PdfImage image = await pdfImageFromImage(pdf: doc.document, image: uiImage);

    bodies.add(
      pw.Padding(
        padding: pw.EdgeInsets.fromLTRB(0, 5, 0, 3),
        child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: <pw.Widget>[
              pw.Header(level: 2, text: praxis.id.toString()),
              pw.Image(image),
            ]
        ),
      )
    );
    for (int i = 0; i < list.length; i++) {
      PraxisContent content = list[i];

      if (list == null || list.isEmpty) {
        bodies.add(pw.Paragraph(text: "None....",),);
        return bodies;
      }

      _logger.info("Content Type: ${content.type}");
      switch (content.type) {
        case "TEXT":
          bodies.add(
            pw.Paragraph(text: content.content,),
          );
          break;
        case "IMAGE":
          PraxisStorage storage = PraxisStorage.instance;
          storage.currentDir = content.praxisSn;
          String imagePath = content.address + '/' + content.content;
          if (content.address == "praxis") {
            imagePath = storage.currentDir + '/' + content.content;
          } else {
            imagePath = content.address + '/' + content.content;
          }
          _logger.info("Imagefile: $imagePath");
          if (!File(imagePath).existsSync()) {
            _logger.info("Something wrong");
            bodies.add(
              pw.Container(
                decoration: pw.BoxDecoration(
                  border: pw.BoxBorder(width: 1.0, color: PdfColors.black),
                ),
                child: pw.Center(
                  child: pw.Paragraph(text: "Something wrong....."),
                )
              )
            );
          } else {
            //both below code work
//            final PdfImage image = await pdfImageFromImageProvider(
//              pdf: doc.document,
//              image: FileImage(File(imagePath)),
//            );
//            _logger.info("add image content....");
//            bodies.add(pw.Center(child: pw.Image(image)));
            imageLib.Image img = imageLib.decodeImage(File(imagePath).readAsBytesSync());
            _logger.info("pic size: ${img.width} * ${img.height}");
            PdfPageFormat fmt = PdfPageFormat.a4;
            _logger.info("doc size: availavbleHeight: ${fmt.availableHeight}, availableWidth${fmt.availableWidth}, height: ${fmt.height}, width: ${fmt.width}");
            if (img.height > fmt.availableHeight) {
///I tried this way, it works, ===========================================
              img = imageLib.copyResize(img, height: fmt.availableHeight.toInt() - 150); 
              _logger.info("pic resize: ${img.width} * ${img.height}");
            }
            final image = PdfImage(
              doc.document,
              image: img.data.buffer.asUint8List(),
              width: img.width,
              height: img.height,
            );
            bodies.add(pw.Center(child: pw.Image(image)));
          }
          break;
      }
    }
    return bodies;
  }

**Comment by hs029** [comment]
In my code, I tried resize image, then it works. 

if (img.height > fmt.availableHeight) {
///I tried this way, it works, ===========================================
img = imageLib.copyResize(img, height: fmt.availableHeight.toInt() - 150);
_logger.info("pic resize: ${img.width} * ${img.height}");
}

**Comment by hs029** [comment]
This issue can be reproduced with 1.7.1, same code and same picture in my APP.

**Comment by DavBfr** [comment]
Can you give me a **minimal** example that reproduces the bug? With an example image if you like, or Placeholder()
