### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by RSP20SCM68S** [DavBfr/dart_pdf#266]
I would like to see an implementation/example to add a watermark to the pdf document background.

If the solution is not there then maybe pdf.document() could take a Widget (Image) with black and white or color option.
document(watermark: (image, boolean black)) and then maybe use a stack widget.
For example:
Stack( widgets : [
 WaterMark()
]) 
then add rest of the contents later. 
I know easier said than done, but it's a useful feature.  Thanks for this repo BTW.

**Comment by DavBfr** [comment]
You can use this unit test as an example:

https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_watermark_test.dart

**Comment by RSP20SCM68S** [comment]
Thanks a lot!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
