### ISSUE TITLE
Logo in PDF file

### ISSUE THREAD

**Issue by cherifburette** [DavBfr/dart_pdf#267]
**Describe the bug**
I want to add a logo in the PDF file of the organization of the PDF and it's impossible without using the Uint8list image which added a picture of colored dots that ruined the pdf

I'm planning to use a network image to do so

**Comment by DavBfr** [comment]
Is there a question, or a bug?

**Comment by cherifburette** [comment]
@DavBfr   don't actually know i'm sorry sir if i mistitled my issue but it's confusing me i don't know if its a bug or a question,,It's my first time to post on github as i couldn't find any appropriate solution on the internet and this is my graduation project and it's really stressing me out 
this is what i have done in the code 
![code1](https://user-images.githubusercontent.com/49873734/78998529-1eee8a80-7b49-11ea-8435-1005fd186ffb.JPG)
![code2](https://user-images.githubusercontent.com/49873734/78998530-201fb780-7b49-11ea-98ea-32750a4fd230.JPG)
![code3](https://user-images.githubusercontent.com/49873734/78998531-20b84e00-7b49-11ea-8921-7c37ba813b8e.JPG)
![code4](https://user-images.githubusercontent.com/49873734/78998536-2150e480-7b49-11ea-8190-0f6d5f972e02.JPG) 
and this is is my code output
![code6](https://user-images.githubusercontent.com/49873734/78998609-3fb6e000-7b49-11ea-9390-ba47091f3c00.jpg)
I'm really sorry again if i mistitled my issue ..
thanks in advance

**Comment by DavBfr** [comment]
Ok, your issue is because you try to display a png or jpeg encoded image instead of actual raw pixel information.

You can create your PdfImage instance using:
```dart
final image1 = PdfImage.file(
  pdf.document,
  bytes: byteImage1,
);
```

**Comment by cherifburette** [comment]
PdfImage.file(); the vs code is giving me an error on the .file in this part, does it require any additional dependency ?

**Comment by DavBfr** [comment]
run `flutter pub upgrade` or update your pubspec.yaml to depend on `pdf: ^1.6.0`

**Comment by cherifburette** [comment]
it worked! thank you so much

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
