### ISSUE TITLE
Error with latest flutter web

### ISSUE THREAD

**Issue by steveroderickIntrohive** [DavBfr/dart_pdf#268]
**Describe the bug**
Getting compiler error when running Flutter Web app

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
var document = await generatePdf(context, recordsStream);

await for (var page in Printing.raster(document.save(), pages: [0, 1], dpi: 72)) {
  final image = page.toPng(); // ...or page.toPng()
  print(image);
 }
```

**Expected behavior**
Code runs

**Actual Behaviour**

Compiler message:
../../../../../.pub-cache/hosted/pub.dartlang.org/printing-3.3.0/lib/src/widget_wrapper.dart:74:5: Error: No named parameter with the name 'targetWidth'.
    targetWidth: width,
    ^^^^^^^^^^^

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E266, locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2020.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Desktop (please complete the following information):**
 - [ ] Browser - Chrome Version 83.0.4103.7

**Additional context**

**Comment by DavBfr** [comment]
Oh, yes, I forgot to publish version 3.3.1 with the fix.

**Comment by DavBfr** [comment]
Please run `flutter pub upgrade` to fix your issue.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by steveroderickIntrohive** [comment]
Got it to compile, but now getting:

`:49432/dart_sdk.js:5314 Uncaught (in promise) Error: UnimplementedError
    at Object.throw_ [as throw] (:49432/dart_sdk.js:4040)
    at printing_web.PrintingPlugin.new.raster (:49432/packages/printing/src/printing_web.dart.lib.js:119)
    at Function.raster (:49432/packages/printing/src/printing.dart.lib.js:100)
    at :49432/packages/nutrasys/src/ui/records/records_web_view.dart.lib.js:3150
    at Generator.next (<anonymous>)
    at onValue (:49432/dart_sdk.js:41673)
    at _RootZone.runUnary (:49432/dart_sdk.js:41558)
    at _FutureListener.thenAwait.handleValue (:49432/dart_sdk.js:37044)
    at handleValueCallback (:49432/dart_sdk.js:37545)
    at Function._propagateToListeners (:49432/dart_sdk.js:37577)
    at _Future.new.[_completeWithValue] (:49432/dart_sdk.js:37439)
    at async._AsyncCallbackEntry.new.callback (:49432/dart_sdk.js:37456)
    at Object._microtaskLoop (:49432/dart_sdk.js:41774)
    at _startMicrotaskLoop (:49432/dart_sdk.js:41780)
    at :49432/dart_sdk.js:37782`

Steve

**Comment by steveroderickIntrohive** [comment]
And thanks for replying so quickly to my issue. I'm in New Brunswick and finding I have nothing else to do but occupy myself coding.

**Comment by DavBfr** [comment]
Yes, raster is not supported on flutter-web: it would require a huge js library to do that.
