### ISSUE TITLE
drawString and long TextFields

### ISSUE THREAD

**Issue by biancashouse** [DavBfr/dart_pdf#27]
I have a long description field. The user is given maxLines: 5.
But the entered text does not have line breaks, so would you have any suggestion as to how I could extract / calc the individual lines for rendering with drawString ?

Anyway, great library. Many thanks.

**Comment by biancashouse** [comment]
Just stumbled upon the widget: OffStage.
Perhaps I could do some measuring offscreen...

**Comment by DavBfr** [comment]
the font object has some measurements functions to calculate the text size and allow you to cut in the right position for your needs.
