### ISSUE TITLE
Form Fields/Editable text fields. Maybe related to issue #104

### ISSUE THREAD

**Issue by MarcelReckmannBG** [DavBfr/dart_pdf#270]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We would be able do define form fields that can be filled later on by an end-user/customer. 
If the field already has input the user should be able to edit it. Could be an additional flag that makes a text-field a form-field. 

**Additional context**
Our application is a digital checklist. Our app takes speech-to-text input. At the end of an inspection a pdf-report is to be created. After the pdf-report is created it will be send/made available to download for certain people. The speech-to-text parts should be editable so that if there are mistakes they can be edited even in the pdf. Other example would be application forms where you have to fill out certain information like name, Date of birth etc.
Example: http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

**Comment by DavBfr** [comment]
I can send you a quote for that.

**Comment by DavBfr** [comment]
Duplicates #104

**Comment by DavBfr** [comment]
Implemented in pdf-1.13.0
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by jlubeck** [comment]
Is there an example somewhere on how to use this new feature?

**Comment by DavBfr** [comment]
@jlubeck look at this: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_form_test.dart

**Comment by jlubeck** [comment]
Thank you for that @DavBfr . `TextField` is what I was using but I found it strange that the preview window was not showing anything. I now tried downloading the generated pdf and opening it with the operating system, and I can see the TextFields there. But NOT on the preview window (`Printing.layoutPdf()`). 

Is that expected?

**Comment by DavBfr** [comment]
@jlubeck It depends on the OS implementation, but I think iOS, Android, and macOS will not show it.

**Comment by jlubeck** [comment]
Hey @DavBfr can you please have a look at this and let me know if it's something that can be fixed and send me a quote for it if needed? https://www.loom.com/share/fb454b47ddd842dc998478a8e60f4ccc

Thank you!

**Comment by jlubeck** [comment]
Another option is being able to fill this pre-existing PDF instead of creating a new one?
[CMS1500- United- UBH editable-Template.pdf](https://github.com/DavBfr/dart_pdf/files/5999155/CMS1500-.United-.UBH.editable-Template.pdf)

So whatever option is easier/faster/doable please quote either one (or both!)

Thank you

**Comment by DavBfr** [comment]
@jlubeck Can you send me the source for this healthform.pdf at dev.nfet.net@gmail.com? Maybe something is wrong.
I'll work on a quote for both options too.

**Comment by jlubeck** [comment]
@DavBfr I just sent it. The subject of the email is "Editable Forms"
