### ISSUE TITLE
Modify an existing pdf

### ISSUE THREAD

**Issue by ramsestom** [DavBfr/dart_pdf#271]
Hi.
Is it possible with this plugin to modify a preexisting pdf file like with pdf-lib in javascript (https://pdf-lib.js.org/) ? 
For example I would like to be able to open a pdf file and draw some text at some coordinates of one of its page before saving it back.

**Comment by DavBfr** [comment]
It's not possible. I plan to implement that as a separate premium library.

**Comment by DavBfr** [comment]
Implemented as part of the premium library.

**Comment by EmaniaRaouf** [comment]
> Implemented as part of the premium library.

@DavBfr which premium library it is?

**Comment by DavBfr** [comment]
It's a paid library that includes existing pdf modification, digital signature, and password protection.

**Comment by Manguelo** [comment]
Hi, what is the name of your premium library?

**Comment by venicemove4u** [comment]
Hi @DavBfr what are the costs for the premium library and where/how can we purchase this?
