### ISSUE TITLE
PdfGraphics and OpenSans

### ISSUE THREAD

**Issue by flowcharterappowner** [DavBfr/dart_pdf#273]
I'm using PdfGraphics.drawString(), and it requires a PDFFont argument.
The default is helvetica.
When I run my app, I get an error:

Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

How can I use OpenSans with drawString() ?

**Comment by DavBfr** [comment]
You have to create a PdfFont object first, as described in the link.

**Comment by flowcharterappowner** [comment]
Sorted thanks.
