### ISSUE TITLE
Exception: type 'PdfGraphicState' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by tomascardenal** [DavBfr/dart_pdf#275]
Hello! First of all thanks for this library and it's amazing potential.

We've had an issue while generating a pdf with multiple opacities. The exception leaves the following stack trace.

`flutter: Exception: type 'PdfGraphicState' is not a subtype of type 'bool'
flutter: StackTrace: #0      PdfGraphicState.== (package:pdf/src/graphic_state.dart:43:9)
#1      ListMixin.indexOf (dart:collection/list.dart:461:19)
#2      PdfGraphicStates.stateName (package:pdf/src/graphic_state.dart:61:25)
#3      PdfGraphics.setGraphicState (package:pdf/src/graphics.dart:316:56)
#4      Opacity.paint (package:pdf/widgets/basic.dart:763:11)
#5      Stack.paint (package:pdf/widgets/stack.dart:192:13)
#6      Flex.paint (package:pdf/widgets/flex.dart:496:13)
#7      Padding.paint (package:pdf/widgets/basic.dart:120:13)
#8      Flex.paint (package:pdf/widgets/flex.dart:496:13)
#9      Flex.paint (package:pdf/widgets/flex.dart:496:13)
#10     Padding.paint (package:pdf/widgets/basic.dart:120:13)
#11     Flex.paint (package:pdf/widgets/flex.dart:496:13)
#12     StatelessWidget.paint (package:pdf/widgets/widget.dart:146:14)
#13     Page.paint (package:pdf/widgets/page.dart:224:13)
#14     Page.postProcess (package:pdf/widgets/page.dart:159:7)
#15     Document.save (package:pdf/<…>
`

This is code snippet throwing the exception
```dart
Pdf.Column(children: [
              Pdf.Text(title + "  " + rate.roundToDouble().toString() + "%", style: Pdf.TextStyle(fontSize: 12)),
              //Progress bar
              Pdf.Stack(children: [
                Pdf.Opacity(
                    opacity: .1,
                    child: Pdf.Container(
                      height: 6,
                      width: 150,
                      color: PdfColor(rgb[0] * 0.7, rgb[1] * 0.7, rgb[2] * 0.7),
                    )),
                Pdf.Container(
                  height: 6,
                  width: rate * 1.5,
                  color: PdfColor(rgb[0], rgb[1], rgb[2]),
                )
              ])
            ]),
```

The issue, as we've discovered, has something to do with the operator override in PdfGraphicState, since it has the following line

```dart
    if (!other is PdfGraphicState) {
```
It seems as is dart interprets the "!other" operator first, and tries to interpret the "other" parameter as a boolean, hence the exception. We've come up with the following workaround. But since we don't know if this does the trick for you, I'd rather inform you.

Our workaround consists on the following syntax for the operator override 

```dart
@override
  bool operator ==(dynamic other) {
    if (!(other is PdfGraphicState)) {
      return false;
    }
    return other.opacity == opacity;
  }
```

This seems to work properly. But we'd rather have you informed and take feedback from you since this is only a quickfix that might not be taking into account the actual expected behaviour.

**Flutter Doctor**

```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.83, on Mac OS X 10.15.3 19D76, locale en-ES)
    • Flutter version 1.18.0-6.0.pre.83 at /Users/tomaspumpun/Development/flutter
    • Framework revision 8e5b575174 (2 days ago), 2020-04-19 17:20:01 -0400
    • Engine revision 2b75c6d111
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 4814f000de)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tomaspumpun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[!] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPad Air (3rd generation) • 394F085E-8B05-4BD7-B4C0-C2939B8302D5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome                    • chrome                               • web-javascript • Google Chrome 81.0.4044.113
    • Web Server                • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
flutter doctor -v  7.77s user 2.79s system 96% cpu 10.943 total

```

**Desktop:**
 - [ X ] iOS
 - [ X ] Android
 - [ X ] Browser

**Smartphone:**
 - Device: [iPad Air (3rd generation) and Web]
 - OS: [iOS 13.3 and macOS Catalina]
 - Browser [Chrome]
 - Version [Chrome Version 80.0.3987.163 (Official Build) (64-bit)]

Thank you in advance. We'll wait for your feedback.

**Comment by DavBfr** [comment]
Thanks, I added your fix to the next release.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by tomascardenal** [comment]
Thanks a lot! Glad I could contribute ;)
