### ISSUE TITLE
Flutter Web support

### ISSUE THREAD

**Issue by flowcharterappowner** [DavBfr/dart_pdf#276]
getApplicationDocumentsDirectory not available with flutter web obviously - i.e. can't use dart:io

i guess this isn't specifically an issue with your library, but any ideas on how to generate an image or a data uri so the pdf can be emailed ?

**Comment by DavBfr** [comment]
The [printing](https://pub.dev/packages/printing) library works on iOS, Android, macOS and Flutter WEB.

No need for js specific code on your side, just use `Printing.share()` to let the user download the pdf or `Printing.layoutPdf()` to open the browser print dialog when possible, depending on the browser support.

**Comment by flowcharterappowner** [comment]
My app wants to be able to generate the pdf and email it to the user.
Is there a way to generate a byte[] of the pdf, which could then attached to an email message ?

**Comment by flowcharterappowner** [comment]
I'd use document.save() to get a List<int>, right ?

**Comment by DavBfr** [comment]
Yes, exactly.
