### ISSUE TITLE
Print/PDF generation with images in Flutter Web

### ISSUE THREAD

**Issue by CRStayton** [DavBfr/dart_pdf#277]
Piecing together other questions on the topic has led me to try the following: 

`ByteData byteData = await rootBundle.load('assets/totals_check.png');
  Uint8List k = byteData.buffer.asUint8List();
  image.Image img = image.decodeImage(k);
  PdfImage check = PdfImage(pdf.document, image: k, height: img.height, width: img.width);`

This is failing with a null height/width.  The same image used as an ImageProvider for mobile is working well.  

Is this the right way to handle this?  Using the image library to generate an image for the purpose of feeding an accurate height/width?  Could you possibly provide a quick sample on loading an image from assets for use in web?

**Comment by DavBfr** [comment]
This should work:

```dart
ByteData byteData = await rootBundle.load('assets/totals_check.png');

final image = PdfImage.file(
  pdf.document,
  bytes: byteData.buffer.asUint8List(),
);
```

**Comment by CRStayton** [comment]
Thanks for the quick turn around David,

**Comment by CRStayton** [comment]
Using the above, I'm seeing the image returned null.

> Caught exception: Assertion failed: file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.6.1/lib/widgets/image.dart:87:16
           image != null
           is not true

Any version requirements? Using Flutter 1.17.0 Beta Chan / Dart 2.8.0 / Printing 3.3.1

**Comment by DavBfr** [comment]
I don't understand how this can happened. Can you put here your code that generates the issue?

**Comment by DavBfr** [comment]
So depending on the rest of the code, `check` can be null. Do you await everything?

**Comment by DavBfr** [comment]
So depending on the rest of the code, `check` can be null. Do you await everything?

**Comment by CRStayton** [comment]
Ok, I'll dig in, thanks again!

**Comment by DavBfr** [comment]
So depending on the rest of the code, `check` can be null. Do you await everything?

**Comment by CRStayton** [comment]
Not sure why, but this appears to be isolated to some images and not others, Possibly bad encoding, unfortunately I drew an unlucky first test image.  I'm attaching examples corresponding to the log below.   Here was my test method:

```dart
Future<PdfImage> getPdfImage(String path, Document pdf) async {
  try {
    ByteData byteData = await rootBundle.load(path);
    Uint8List list = byteData.buffer.asUint8List();
    PdfImage img = PdfImage.file(
      pdf.document,
      bytes: list,
    );
    print('success for: $path');
    return img;
  } catch (e) {
    print('failure for: $path - $e');
  }
}

final PdfImage radioOff = await getPdfImage('assets/radio_off.png', pdf);
final PdfImage radioOn = await getPdfImage('assets/radio_on.png', pdf);
final PdfImage checkOff = await getPdfImage('assets/check_off.png', pdf);
final PdfImage checkOn = await getPdfImage('assets/check_on.png', pdf);
final PdfImage unchecked = await getPdfImage('assets/unchecked.png', pdf);
final PdfImage checked = await getPdfImage('assets/checked.png', pdf);
tableCheckImg = await getPdfImage('assets/totals_check.png', pdf);
```

Log: 
[ +153 ms] success for: assets/1/banner.png

[  +71 ms] success for: assets/2/banner.png

[  +18 ms] success for: assets/radio_off.png

[   +6 ms] success for: assets/radio_on.png

[   +7 ms] failure for: assets/check_off.png - Assertion failed: file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.6.2/lib/src/image.dart:117:12
           image != null
           is not true

[   +4 ms] failure for: assets/check_on.png - Assertion failed: file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.6.2/lib/src/image.dart:117:12
           image != null
           is not true

[   +8 ms] success for: assets/unchecked.png

[   +8 ms] success for: assets/checked.png

[   +6 ms] failure for: assets/totals_check.png - Assertion failed: file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.6.2/lib/src/image.dart:117:12
           image != null
           is not true

radioOff -![radio_off](https://user-images.githubusercontent.com/64164887/80117253-f4db9600-8554-11ea-9495-9b29bffc71bb.png)
radioOn - ![radio_on](https://user-images.githubusercontent.com/64164887/80117290-00c75800-8555-11ea-90d6-6c186457b9c5.png)
checkOff - ![check_off](https://user-images.githubusercontent.com/64164887/80118436-6536e700-8556-11ea-958e-db163e4ea453.png)
checkOn - ![check_on](https://user-images.githubusercontent.com/64164887/80118435-6536e700-8556-11ea-908b-145d1d24b877.png)
unChecked - ![unchecked](https://user-images.githubusercontent.com/64164887/80118468-7122a900-8556-11ea-88c2-1a274dc09e2b.png)
checked - ![checked](https://user-images.githubusercontent.com/64164887/80118470-7122a900-8556-11ea-8934-859f2d4406bd.png)
tableCheckImg - ![totals_check](https://user-images.githubusercontent.com/64164887/80118471-7122a900-8556-11ea-8920-9f766f64280f.png)

**Comment by DavBfr** [comment]
Please report the bug to https://github.com/brendan-duncan/image/issues with your checkoff image, the image library cannot load this png file.

ImageMagick raises a warning too:
convert: bKGD: invalid `checkoff.png' @ warning/png.c/MagickPNGWarningHandler/1748.

you should try to re-encode the problematic images with a tool like [pngcrush](https://pngcrush.com/).

**Comment by jlubeck** [comment]
Thank you @DavBfr for the pngcrush recommendation. That fixed an issue for me as well
