### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by gaganstha81** [DavBfr/dart_pdf#279]

**Comment by DavBfr** [comment]
What is the issue? Unicode is fully supported.

**Comment by gaganstha81** [comment]
The text displayed can be in any language, Universal support needed.

**Comment by DavBfr** [comment]
https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by gaganstha81** [comment]
What about dynamic? User can input any language font.(multiple fonts in same pdf)

**Comment by DavBfr** [comment]
Then use a font that supports all languages, but it will be huge: https://www.google.com/get/noto/
