### ISSUE TITLE
Print view that is longer than the screen

### ISSUE THREAD

**Issue by gedw99** [DavBfr/dart_pdf#28]
I saw printscreen in the example.
I need to print a scrolling listview where some of the lines are longer than the screen size.

Does this plugin support that ?

**Comment by DavBfr** [comment]
For now, the only thing it supports is you to draw text and lines with your code. I'm working on a higher level printing system, but it is not ready yet, in the branch widget.

**Comment by gedw99** [comment]
Wow impressive stuff.

I will have a look.

I think that I can get this working on flutter desktop as I saw the non dart code was pretty simple. Bonus :)
