### ISSUE TITLE
Can't add gradient color to pdf

### ISSUE THREAD

**Issue by madscs11** [DavBfr/dart_pdf#280]
**Describe the bug**
The 'gradient' value within a BoxDecoration widget does not exist. Is there any other way to use gradient colors within the PDF?

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
                  Container(
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        colors: [
                          AppColors.backgroundGradientLight,
                          AppColors.backgroundGradientDark
                        ],
                        begin: const FractionalOffset(0.0, 0.0),
                        end: const FractionalOffset(0.0, 1.0),
                        stops: [0.0, 1.0],
                        tileMode: TileMode.clamp,
                      ),
                    ),
                    height: 200,
                  ),
```

**Expected behavior**
I would've expected to be able to use the gradient value of the BoxDecoration widget as I do elsewhere in my app where I don't use PDF specific widgets.

**Comment by DavBfr** [comment]
Implemented in master.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
