### ISSUE TITLE
How to change the language of the share options from the pdf share dialog

### ISSUE THREAD

**Issue by RussianHamster** [DavBfr/dart_pdf#283]
Hi,
is it possible to change the language of the share options from the pdf share dialog? I need to change the language to German. I also set the language on the iPad to German, but it does not change anything. It would be great if it would be possible.
Many thanks in advance

**Comment by DavBfr** [comment]
I think you have to configure the iOS project in xcode to enable German and other languages.
The share button opens a system popup, so it should be translated.

**Comment by RussianHamster** [comment]
You are right! I had to add German to the Localizations section inside the build settings in Xcode. Now it is working fine, thanks a lot!
