### ISSUE TITLE
Xcode Compiler Warning

### ISSUE THREAD

**Issue by leidig54** [DavBfr/dart_pdf#285]
Hi Everyone.

Am getting the following Xcode warning when adding Printing to my flutter project; 

/Users/george/development/flutter/.pub-cache/hosted/pub.dartlang.org/printing-3.3.1/ios/Classes/PrintJob.swift:250:22: 'withUnsafeMutableBytes' is deprecated: use `withUnsafeMutableBytes<R>(_: (UnsafeMutableRawBufferPointer) throws -> R) rethrows -> R` instead

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-9.0.pre.98, on Mac OS X 10.15.4 19E287, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.0)
[✓] Connected device (1 available)

• No issues found!

Any ideas? I've tried the suggested replacement but to no avail.

First post so please let me know if i've left out any useful information. The app is extremely basic and the warning seems independent of any changes to the flutter project itself.

**Comment by DavBfr** [comment]
Try this:

```swift
data.withUnsafeMutableBytes { (outputBytes: UnsafeMutableRawBufferPointer) in
                    let rgb = CGColorSpaceCreateDeviceRGB()
                    let context = CGContext(
                        data: outputBytes.baseAddress?.assumingMemoryBound(to: UInt8.self),
                        width: width,
                        height: height,
                        bitsPerComponent: 8,
                        bytesPerRow: stride,
                        space: rgb,
                        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
                    )
```

**Comment by leidig54** [comment]
Perfect! thank you very much :)
