### ISSUE TITLE
PdfPreviewAction not being able to import

### ISSUE THREAD

**Issue by rshrc** [DavBfr/dart_pdf#286]
PdfPreviewAction this class is not accessible

Using pdf: 1.7.1 in pubspec. Which I think requires an update and a new release

**Comment by DavBfr** [comment]
I don't understand how can't it be imported. It's exported with PdfPreview.
Can you give me more explainations?

**Comment by rshrc** [comment]
Yes, I am using AndroidStudio and when I use both 
```
import 'package:pdf/pdf.dart'; 
import 'package:pdf/widgets.dart' as pw;
```

I cannout use PdfPreviewAction and also PdfPreview, all other widgets seem to be available. It does not even come with the auto suggestion of Android Studio. So I looked into your demo app that you have added in the repo. I saw that you have some overriden dependencies. 

```
dependency_overrides:
  printing:
    path: ../printing
  pdf:
    path: ../pdf
```

Which surely works on your demo app, but not in any other project where we are using version 1.7.1

Now, coming back to the point, the last release of this package was on April 28th, 2020. And you have made a change to a few classes and functions in the repo recently which might not be reflecting when fetched through dart pub. This commit might be breaking it https://github.com/DavBfr/dart_pdf/commit/93cf24c3fa4330aa004d2160ab6e311fbe177275

So all in all, I guess you just have to make a new release. Nothing else.

**Comment by DavBfr** [comment]
you have to import printing:
```dart
import 'package:printing/printing.dart';
```

**Comment by rshrc** [comment]
> you have to import printing:
> 
> ```dart
> import 'package:printing/printing.dart';
> ```

this is also imported

**Comment by rshrc** [comment]
> > you have to import printing:
> > ```dart
> > import 'package:printing/printing.dart';
> > ```
> 
> this is also imported

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:sanrachna_web/providers/oq_provider.dart';
import 'package:flutter/foundation.dart';
//import 'package:google_fonts/google_fonts.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

**Comment by DavBfr** [comment]
ok, I see. this PdfPreview widget is not yet published. It's for a future release.
What do you want to do with it?

**Comment by rshrc** [comment]
> ok, I see. this PdfPreview widget is not yet published. It's for a future release.
> What do you want to do with it?

I want to use it. We are gonna deliver a product, and this PdfPreview plays an important role in it. Would it be possible you make a release. Would be really great.

**Comment by DavBfr** [comment]
you can use it as preview for now. Add this to your pubspec.yaml
```dart
dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf
      path: printing
```

Then you can use it like this:

```dart
PdfPreview(
          maxPageWidth: 600,
          build: (pageFormat) {
            final doc = pw.Document();

            doc.addPage(
              pw.Page(
                build: (pw.Context context) => pw.Center(
                  child: pw.Text('Hello World!'),
                ),
              ),
            );

            return doc.save();
          },
        )
```

**Comment by rshrc** [comment]
Oh cool

**Comment by DavBfr** [comment]
Can I ask how PdfPreview plays an important role? This can help me to decide on future evolutions.

**Comment by DavBfr** [comment]
This is now published.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
