### ISSUE TITLE
Can I print using Epson TM-P20 2" Mobile Thermal POS Receipt Printer?

### ISSUE THREAD

**Issue by john-ravi** [DavBfr/dart_pdf#29]
I need to print receipts over wifi or bluetooth. Thank you!
https://www.epson.co.in/For-Work/Printers/POS-Printers/Epson-TM-P20-2%22-Mobile-Thermal-POS-Receipt-Printer/p/C31CE14061

**Comment by DavBfr** [comment]
You will have to use the Epson SDK for that.

**Comment by john-ravi** [comment]
Do I need to write custom code in Native Android? Should I use MethodChannel for that? I have Epson SDK with me. Thank you!

**Comment by DavBfr** [comment]
Yes, you just have to write java code for Android using MethodChannel to push the pdf to the Epson SDK.
