### ISSUE TITLE
No Spacer widget?

### ISSUE THREAD

**Issue by PritishSawant** [DavBfr/dart_pdf#294]
The Spacer widget does not work for pdf generation. IS there any equivalent widget which could put a Text at the bottom which is present inside a Column

**Comment by DavBfr** [comment]
Spacer is implemented here:
https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/widgets/flex.dart#L583

**Comment by DavBfr** [comment]
You're right, it's not working. You can replace it with Expanded:

```dart
    pdf.addPage(
      Page(
        build: (Context context) => Column(
          children: <Widget>[
            Text('Begin'),
            // Spacer(),
            Expanded(child: SizedBox.shrink()),
            Text('End'),
          ],
        ),
      ),
    );
```

**Comment by DavBfr** [comment]
Fixed in pdf 1.8.0
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by peterstojanowski** [comment]
@DavBfr Is there a way to do something similar using `MultiPage`? I have a widget that needs to be at the bottom of the last page. Using `footer` parameter of `MultiPage` and checking for last page doesn't work as looks like footer can't have variable height depending of the page it's in.

**Comment by DavBfr** [comment]
Can you create a proper feature request? I think it would be possible.

**Comment by peterstojanowski** [comment]
Done in #338.
