### ISSUE TITLE
Content bigger that page

### ISSUE THREAD

**Issue by ClaudineiOlSantos** [DavBfr/dart_pdf#295]
Hi..

When the content is bigger that page, does not create one more page. How can i resolve this?

**To Reproduce**
Create document with long text.

```dart
 doc.addPage(pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Center(
              child: pw.Text(BuildOrderMail(order)),
            ); // Center
          })); // Page
    });
```

**Expected behavior**
PDF docment with 2 pages

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser

**Comment by maine98** [comment]
@ClaudineiOlSantos Use MultiPage instead of Page
```dart
doc.addPage(
   MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (Context context) {
          return List.generate(400, (index) => Text(index.toString()));
        },
  )
)
```

**Comment by ClaudineiOlSantos** [comment]
@maine98  thank you vary much :)
