### ISSUE TITLE
The text goes out of the pdf

### ISSUE THREAD

**Issue by maine98** [DavBfr/dart_pdf#296]
**Describe the bug**
I tried to insert a long string in a Text and instead of creating a new line the text goes out of the margins.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
static Document initFakePdf() {
    final doc = Document();
    doc.addPage(
      MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (Context context) => Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "Fake Data",
              style: TextStyle(fontSize: 30),
            ),
            Divider(height: 20),
          ],
        ),
        build: (Context context) {
          return _generateList(context);
        },
      ),
    );
    return doc;
  }
static _generateList(Context context) {
    List<Widget> list = new List.generate(25, (index) => Text(index.toString()));
    list.add(Text("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
    return list;
  }
```

**Expected behavior**
I expect the text to come to the end every time a string exceeds the size of the page.

**Screenshots**
![Screenshot_1589378922](https://user-images.githubusercontent.com/46499668/81823367-8d51ae80-9534-11ea-921e-d31eba9ec850.png)

**Flutter Doctor**

```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Versione 10.0.18363.836], locale it-IT)
    • Flutter version 1.17.0 at C:\SDK\flutter
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Maine\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

```

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [ ] Browser

**Comment by ClaudineiOlSantos** [comment]
@maine98 try to use the paragraph instead of Text

**Comment by maine98** [comment]
@ClaudineiOlSantos I try use Paragraph but the result is the same

**Comment by DavBfr** [comment]
@maine98 you need to add some spaces in your text, otherwise the widget cannot split into lines.

**Comment by maine98** [comment]
@DavBfr So in a nutshell if I put a phrase like "aaaaaaaaa aaaaaaa aaaaaaa aaaaaa" etc. is it divided into lines?

**Comment by DavBfr** [comment]
yes!

**Comment by maine98** [comment]
@DavBfr Why is this particularity needed?🤔

**Comment by DavBfr** [comment]
@maine98 to cut the lines at word boundaries.
https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/widgets/text.dart#L570
If you have a better solution, feel free to provide a pull request.

But that's more complicated than what you think:
https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages

**Comment by maine98** [comment]
@DavBfr I can imagine how complicated it can be, it was only out of my curiosity, thanks anyway to the help💪🏽

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
