### ISSUE TITLE
Google Fonts not supported?

### ISSUE THREAD

**Issue by PritishSawant** [DavBfr/dart_pdf#298]
Any chance of supporting Google Fonts in the future?

**Comment by DavBfr** [comment]
I created a bug report on their repo to be able to use it:
https://github.com/material-foundation/google-fonts-flutter/issues/102
Please do comment on this ticket to increase visibility.

**Comment by oom-** [comment]
And `.woff format would be cool too

**Comment by ganeshchenniah** [comment]
any update ?

**Comment by DavBfr** [comment]
Implemented in printing 5.4.0
