### ISSUE TITLE
how to make a column like in microsoft word?

### ISSUE THREAD

**Issue by erwintan96** [DavBfr/dart_pdf#299]
hi sir, i want to ask..
is this package have a feature to make columns like microsoft word?

![Untitled](https://user-images.githubusercontent.com/14256134/82125087-5fe54a80-9758-11ea-837d-11803f897aea.png)

if this package have this feature, how to make it?
if this package doesn't have this feature, is this feature possible in the future?

thank you :)

**Comment by DavBfr** [comment]
Yes, it's possible using Wrap:

```dart
final math.Random rnd = math.Random(42);

pdf.addPage(
  MultiPage(
    pageFormat: PdfPageFormat.standard,
    build: (Context context) => <Widget>[
      Wrap(
        direction: Axis.vertical,
        spacing: 5,
        runSpacing: 20,
        children: List<Widget>.generate(
          100,
          (int n) => Container(
            // color: PdfColors.blue,
            width: PdfPageFormat.standard.availableWidth / 3 - 20,
            // padding: EdgeInsets.only()
            child: Lorem(
              length: rnd.nextInt(30) + 10,
              random: rnd,
              textScaleFactor: .7,
              textAlign: TextAlign.justify,
            ),
          ),
        ),
      )
    ],
  ),
);
```

**Comment by erwintan96** [comment]
it worked well with your example or using text inside the container.
but when i modify like this :
`  pdf.addPage(
    MultiPage(
      pageFormat: PdfPageFormat.legal,
      build: (Context context) => <Widget>[
        Wrap(
          direction: Axis.vertical,
          spacing: 5,
          runSpacing: 20,
          children: productGroups.map((productGroup) {
            return new Container(
                width: PdfPageFormat.standard.availableWidth / 3,
                child: new Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      new Text(productGroup.name),
                      new Table(
                        border: TableBorder(width: 1.0),
                        defaultVerticalAlignment:
                        TableCellVerticalAlignment.middle,
                        children: productGroup.products.map((product){
                          return new TableRow(
                              children: [
                                new Container(
                                  padding : const EdgeInsets.all(2.0),
                                  child: new Wrap(
                                      children: <Widget>[
                                        new Text(
                                          product.name ?? "",
                                          style: new TextStyle(fontSize: 16),
                                          textAlign: TextAlign.center,
                                        )
                                      ]
                                  ),
                                ),
                                new Container(
                                    padding : const EdgeInsets.all(2.0),
                                    child: new Wrap(
                                        children: <Widget>[
                                          new Text(
                                            CurrencyUtil.parseDoubleToIDRWithout00(product.sellPrice ?? 0.0) ?? 0,
                                            style: new TextStyle(fontSize: 16),
                                            textAlign: TextAlign.center,
                                          ),
                                        ]
                                    )
                                ),
                              ]);
                        }).toList(),
                      ),
                    ]));
          }).toList(),
        )
      ],
    ),
  );`

it become like this : 
![WhatsApp Image 2020-05-17 at 5 37 48 AM](https://user-images.githubusercontent.com/14256134/82147057-fe79b600-9801-11ea-8f00-eb374402ad24.jpeg)

do you have any idea sir?

**Comment by DavBfr** [comment]
if you use legal as paper width, use legal too to divide in 3 columns:
width: PdfPageFormat.legal.availableWidth / 3.

The remove runSpacing: 20 or remove some width as I did.

use `Document.debug = true` to find how it renders.

**Comment by erwintan96** [comment]
that's cool , thank you  sir it works... 
btw, how do i find the documentation?

And i want to ask again sir..
Can a Table widget be split into multiple pages like the picture below when table's height is longer than my paper's height?
![Untitled](https://user-images.githubusercontent.com/14256134/82159408-ad3de680-9842-11ea-9d2f-73797f8e8395.png)

**Comment by DavBfr** [comment]
No, it's not possible with some columns.

**Comment by erwintan96** [comment]
thank you for your help sir..
