### ISSUE TITLE
Flutter package install error

### ISSUE THREAD

**Issue by summy1991** [DavBfr/dart_pdf#3]
Hi,
When  I install Package showing some error.
Running "flutter packages get" in pdf_test...
Because every version of flutter_test from sdk depends on vector_math 2.0.6 and pdf_test depends on vector_math ^2.0.7, flutter_test from sdk is forbidden.
So, because pdf_test depends on flutter_test any from sdk, version solving failed.
pub get failed (1)

pubspec.yaml 
dependencies:
  ttf_parser: ^1.0.0
  meta: ^1.1.5
  vector_math: ^2.0.7
  pdf: ^1.0.0
  flutter:
    sdk: flutter

**Comment by DavBfr** [comment]
This should be fixed with version 1.0.1.

**Comment by summy1991** [comment]
Thanks

**Comment by summy1991** [comment]
Thanks
