### ISSUE TITLE
Generating a QR and add it to PDF page

### ISSUE THREAD

**Issue by Eng-aous-6006** [DavBfr/dart_pdf#301]
I am Building a Flutter App, and one of the Functionalities includes the following:

1- Generating Qr codes  (Using qr package)- no problem here if I am showing it on the screen. 2- Generating PDF file, then saving it and sharing it using native device Sharing, No problem here until I tried to include the Qr code in the PDF page!

I have been stuck with this for two days and tried too many approaches to solve this, sadly with no luck.

please help and thank you all in advance.

**Comment by DavBfr** [comment]
Yes, there is a Widget for that:
```dart
BarcodeWidget(
            barcode: Barcode.qrCode(),
            data: 'here is a qrcode',
)
```

You can use the same widget for Flutter too: https://pub.dev/packages/barcode_widget

**Comment by Eng-aous-6006** [comment]
Thank you So much, for your Valuable feedback, really appreciate it.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
