### ISSUE TITLE
Enhancements to the PDFPreview Widget

### ISSUE THREAD

**Issue by marcos930807** [DavBfr/dart_pdf#303]
**Is your feature request related to a problem? Please describe.**
I would like to have the possibility to configure the decoration of the ScrollView container, and the decoration of _PdfPreviewPage

**Describe the solution you'd like**
add the possibility to pass both decoration as a parameter in the constructor

**Describe alternatives you've considered**
For the moment i have a fork with my own decoration.

**Additional context**
Thaks again for this awesome work,

**Comment by DavBfr** [comment]
Thanks, If you have a fork, can you create a PR?

**Comment by marcos930807** [comment]
Hi again #304

**Comment by marcos930807** [comment]
Hi there, I added the comma to keep the alignment.I have seen a couple of additional details that are not problematic for the moment but I tell you, the color of the actions depends on accentIconTheme which is deprecated after flutter 1.17 and i Have a warning when configuring ThemeData with custon accentInconTheme.Another thing is that sometimes the rendering of the PreviewWidget tries to update after the Widget get disposed, it would be great if before calling setState we check if (mounted).
Tanks Again for this Great Work.

**Comment by DavBfr** [comment]
OK, I can merge this change and let you see the other issues.
