### ISSUE TITLE
Support save to excel file xlsx

### ISSUE THREAD

**Issue by hayhv** [DavBfr/dart_pdf#305]
Any app need create such as report and preview it and users need save report to excel  file
We need support save as to any file format xlsx. Pdf ..

**Comment by DavBfr** [comment]
This library allows you to export to pdf. Other file formats would be other libraries.

**Comment by kawal7415** [comment]
For creating excel file, You can use : https://pub.dev/packages/excel

**Comment by hayhv** [comment]
> For creating excel file, You can use : https://pub.dev/packages/excel

I want integrate function save as xls like save as pdf because we are only use one code to preview, print, export pdf, export xls. Such as flutter use one code to make and run for multiple platform.
it will save time writing code.

**Comment by kawal7415** [comment]
In the coming week, I will be adding the functionality **export as pdf** to excel.

So, then you can use power of **pdf from this awesome library** via **excel**, thus exporting to **xlsx and pdf both in one click easier.**

I am unable to **span tables cells** with this library **(pdf)**.

Any help is appreciated.

**Comment by DavBfr** [comment]
see https://github.com/kawal7415/excel
