### ISSUE TITLE
Multipage with long text 

### ISSUE THREAD

**Issue by Dev-Owl** [DavBfr/dart_pdf#307]
I tried multiple Widgets for the build method, Paragraph/Text with and without Wrap. Got the same as described below for each of them:

**Describe the bug**
Code generates more pages as required and runs into the maxPages limit.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
void generateReport() {
    final pdf = pw.Document();
    final text = pw.LoremText().sentence(700); // 600 words will fit on the page, 700 should be 2 pages but breaks
    pdf.addPage(pw.MultiPage(
      maxPages: 4,
      pageFormat: PdfPageFormat.a4,
     // header: _buildHeader,
     // footer: _buildFooter,
      build: (pw.Context context) => [
        Wrap(children: [
          pw.Text(text),
        ]),
      ],
    )); // Page

    final file = File('helloWorld.pdf');
    if (file.existsSync()) {
      file.delete();
    }
    file.writeAsBytesSync(pdf.save());
  }
```

**Expected behavior**
I would expect the text to split over two pages and not generating more.

**Screenshots**
N/A

**Flutter Doctor**
Not using Flutter -> just dart

**Desktop (please complete the following information):**
Command line

**Smartphone (please complete the following information):**
N/A

**Additional context**
I increased the maxPages number to something around the 50000 and it still runs into this exception

**Comment by DavBfr** [comment]
Yes, one widget cannot be splitted, it has to fit on a page, except table, wrap and column that can pass some of their children to another page

**Comment by Dev-Owl** [comment]
My above example is using the Wrap widget but I guess you mean that even inside of the widgets you mentioned child's can't be multipage sizes. Did I got this right?
If so, this would actually be an issue as I can't make sure that a text might get quite big, do you have any suggestions how to handle this?

**Comment by DavBfr** [comment]
Yes, the LoremText widget here cannot be bigger than a page, but you can create many of them as children of a Wrap

**Comment by Dev-Owl** [comment]
Okay so how would you handle the case that a text might get to big on a page? Even splitting text by line breaks or similar chars would not directly solve this issue. I could imagine measuring the size of the text and compare it with the page size for this way of course the position in the page needs to be available and it's quite a lot of work for every text field.

**Comment by DavBfr** [comment]
you can cut the text at a fixed length and pass all Text(substrings) to Wrap. the result should quite similar.

**Comment by Dev-Owl** [comment]
True, that would be a  possible way to handle this. Thanks for the clarification

**Comment by DavBfr** [comment]
That's how _flutter_markdown_ renders text actually.
