### ISSUE TITLE
Page orientation not working as expected.

### ISSUE THREAD

**Issue by raul26** [DavBfr/dart_pdf#308]
**Describe the bug**
I need to generate a PDF from images, and I need to preserve the original orientation of the image, to make this happen I found the orientation parameter in addPage method, but instead of display a PDF page as landscape it only change the orientation of the image.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
      final pdf = pw.Document();
      _filesList.forEach((_file) {
        final image = PdfImage.file(
          pdf.document,
          bytes: _file.readAsBytesSync()
        );
        final orientation = image.width > image.height ? pw.PageOrientation.landscape : pw.PageOrientation.portrait;
        pdf.addPage(pw.Page(build: (pw.Context context) {
          return pw.Center(
            child: pw.Image(image),
          );
        }, orientation: orientation));
      });
```

**Expected behavior**
The page of the PDF adjust to image orientation.

**Screenshots**
![image](https://user-images.githubusercontent.com/7293874/83157369-2225e180-a0c9-11ea-92f9-015d56e5ef37.png)

As you can see in the image, the first image is portrait and is displayed as expected, but the second image is landscape and the PDF page is portrait, only changed the image orientation.

**Flutter Doctor**

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.17.1 at /Users/developer/flutter-dev/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [ ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - OS: [iOS13.4]

**Additional context**
The Idea is preserve image orientation and make the PDF page portrait or landscape based on the image.

Any help would be appreciated.

**Comment by DavBfr** [comment]
use pw.Page(pageFormat: pw.PageFormat.a4.portrait, build .......)

or pw.Page(pageFormat: pw.PageFormat.a4.landscape, build .......)

**Comment by raul26** [comment]
@DavBfr I really appreciate your help, it works as expected.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
