### ISSUE TITLE
Table Header and data is cut in some row

### ISSUE THREAD

**Issue by hitendigi** [DavBfr/dart_pdf#309]
Some of the Header value is not showing complete ex. STATUS is displayed ad STATU,
Date Value is also cutting ex. The start Date value is 28-05-2020, but it is displayed as 28-05-20, Same for end Date.
<img width="557" alt="pdfCut" src="https://user-images.githubusercontent.com/49969242/83321822-20e2e900-a270-11ea-94cb-6d2b57a293a6.png">

**Comment by DavBfr** [comment]
What do you expect? You have 2 options: use landscape to have more space, or use a smaller font.
