### ISSUE TITLE
pdfImageFromImage

### ISSUE THREAD

**Issue by biancashouse** [DavBfr/dart_pdf#31]
Dave,

I have hit a brick wall with this.
I was hoping to be able to add flutter image assets to my pdf.
Is the only way to achieve this via the RenderRepaintBoundary.toImage() ?

Cheers in hope there's a more straightforward way...

Ian

**Comment by biancashouse** [comment]
also, trying the following gives a needsRepaint assertion error:

Future<PDFImage> _printWidget(PDFGraphics g, GlobalKey theWidgetKey) async {
    RenderRepaintBoundary boundary = theWidgetKey.currentContext.findRenderObject();
    final im = await boundary.toImage();
    final bytes = await im.toByteData(format: ui.ImageByteFormat.rawRgba);
    print("Print Widget ${im.width}x${im.height} ...");
    return PDFImage(FlowcharterBloc.pdf,
        image: bytes.buffer.asUint8List(), width: im.width, height: im.height);
  }

**Comment by biancashouse** [comment]
Woo Hoo. Works like a dream. So easy to incorporate our asset images now. Thank you.

Just realised I was using an older version of your packages (prefix was PDF rather than Pdf). I tended to not put the version numbers in my yaml file, and was assuming that would just use the latest version of each package, but it seems I need to explicitely upgrade packages. Anyway refactored to your improved api and all seems good (except printer preview is blank, so I'll check out your sample code ...).

Many thanks for the fast response.

**Comment by pptavozl** [comment]
> You can use the new function pdfImageFromImageProvider:
> 
> ```dart
> PdfImage im = await pdfImageFromImageProvider(pdf: pdf, image: AssetImage('theimage.png'))
> ```

The function 'pdfImageFromImageProvider' isn't defined.dart(undefined_function)
 
  pdf: ^1.3.4

**Comment by DavBfr** [comment]
You have to use the plugin `printing`, or copy the source from there:
https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/src/asset_utils.dart#L21

**Comment by pptavozl** [comment]
I think this is not i want to do, iwant to add Image asset to a document pdf, can you please tell me how to do it ? :/

**Comment by DavBfr** [comment]
Then it is the second function: https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/src/asset_utils.dart#L34

```dart
var image = pdfImageFromImageProvider(pdf: document, image: AssetImage('logo.png'));
```

**Comment by Lawati97** [comment]
> Then it is the second function: https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/src/asset_utils.dart#L34
> 
> ```dart
> var image = await pdfImageFromImageProvider(pdf: document, image: AssetImage('assets/logo.png'));
> ```

for some reason in using Flutter 2.2.3 I cannot find this function (pdfImageFromImageProvider)

**Comment by fllaryora** [comment]
Please re-open this topic, 
because it is not clear to me what to do when I cannot find pdfImageFromImageProvider.
Thanks in advance.
