### ISSUE TITLE
can I convert it to png?

### ISSUE THREAD

**Issue by wrjcs** [DavBfr/dart_pdf#311]
Hello,
Could I convert the pdf to image?

**Comment by DavBfr** [comment]
Yes, use the library "printing", then do something like:

```dart
var data = pdf.save();

var page = 1;
await for (var page in Printing.raster(data, dpi: 72)) {
  var png = page.toPng();

  await File('page-$page.png').writeAsBytes(png);
  page++;
}
```

**Comment by wrjcs** [comment]
Thanks you very much.

**Comment by rafaelmpessoa** [comment]
it's possible to create one single image with a pdf that has many pages?

**Comment by DavBfr** [comment]
Yes, you'll have to write the code to merge the images ;)

**Comment by ganeshchenniah** [comment]
Photos are not getting displayed after conversion .
