### ISSUE TITLE
Merging / Spanning a cell in table

### ISSUE THREAD

**Issue by justkawal** [DavBfr/dart_pdf#313]
First of all thanks for this awesome library.

I am unable to **span or merge cells** in table.
Is it even supported yet ?

If yes, then any example to achieve the same?

Thanks again.

**Comment by DavBfr** [comment]
This is not supported.
Duplicates #256 #167

**Comment by kawal7415** [comment]
Ok thanks.

**Comment by justkawal** [comment]
Would love to get notified as soon as this functionality is available.

**Comment by muasif80** [comment]
@justkawal There is one way to achieve it. Use multiple tables, under a column. Like if first row is 4 columns and 2nd row is 2 columns, then put the first row in a table and then put the 2nd row in another table. Add the two tables as children to a column. This has worked for me.
