### ISSUE TITLE
How to open and generate pdf file on Flutter WEB

### ISSUE THREAD

**Issue by DSMan97** [DavBfr/dart_pdf#314]
**Describe the bug**
I can't create a pdf file or open it on flutter web, but this work on android an IOS

**Expected behavior**
Openen a new page with the PDF file or a popup OS windows to save the pdf file

**Screenshots**

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.38, on Mac OS X 10.15.4 19E287, locale es-ES)
    • Flutter version 1.19.0-4.0.pre.38 at /Users/dsman97/Library/flutter
    • Framework revision 997a6ffc00 (30 minutes ago), 2020-06-03 23:12:32 +0100
    • Engine revision 859d892f1f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 54adfeb93f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dsman97/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dsman97/Library/Android/sdk
    • Java binary at: /Users/dsman97/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Users/dsman97/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Users/dsman97/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ x] Browser

**Smartphone (please complete the following information):**
- Chrome

Thanks in advanced

**Comment by DavBfr** [comment]
Nothing specific to do.
Have you tested https://davbfr.github.io/dart_pdf/ ? 
It's just using `Printing.sharePdf(bytes: .... );`

**Comment by DSMan97** [comment]
I use these methods, nothing happend.

await Printing.layoutPdf(
         onLayout: (PdfPageFormat format) async => pdf.save());

     await Printing.sharePdf(bytes: pdf.save(), filename: 'document.pdf');

Thanks in advanced

**Comment by DavBfr** [comment]
Any error in chrome's console?

**Comment by DSMan97** [comment]
No nothing, I try putting a print on the method but nothing occurs, I mean i can't see the prints

**Comment by DavBfr** [comment]
Can you post some code?

**Comment by DSMan97** [comment]
Yes, I am investigating about and any print or method like sharePDF or layout pdf works, unless I comment the pdf images.

If I comment the pdf images the  method share PDF workds

**Comment by DavBfr** [comment]
please post a simplified sample code, maybe you're doing something wrong

**Comment by DSMan97** [comment]
`
 Future<String> posterGenerator(
      String petImage) async {

    pdfWidgets.Document pdf = pdfWidgets.Document();

    final roboto = pdfWidgets.Font.ttf(await rootBundle.load("assets/fonts/Roboto-Bold.ttf"));
    var imageUni8;


    if(!kIsWeb){
       imageUni8 = await mPetImgCachetoPDF(petFoto);
    }else{
    //TODO How to convert NetworkImage to uint8list for PDF image 
    
    }




      const imageProvider = const AssetImage(
          'assets/icons/FinderPet_poster.png');


/*

      final PdfImage imageBrand = await pdfImageFromImageProvider(
        pdf: pdf.document,
        image: imageProvider,
      );


 */



      final petImage = PdfImage(
        pdf.document,
        image: imageUni8,
        width: 300,
        height: 300,
      );



      pdf.addPage(pdfWidgets.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pdfWidgets.Context context) {
            return new pdfWidgets.Center(
                child: pdfWidgets.Column(
                  children: <pdfWidgets.Widget>[
                    
                
                    pdfWidgets.Text('\n'),
                    //pdfWidgets.Image(petImage),
                    pdfWidgets.Text('\n'),
                    pdfWidgets.Text('\n'),
             
                    pdfWidgets.Text('\n'),
                    pdfWidgets.Text('Creado con ',
                        style: pdfWidgets.TextStyle(
                            fontSize: 25,
                            fontWeight: pdfWidgets.FontWeight.bold,
                            color: PdfColors.blue)),
                    pdfWidgets.Text('\n'),
                    pdfWidgets.Expanded(
                      child: pdfWidgets.Row(children: <pdfWidgets.Widget>[
                        pdfWidgets.SizedBox(width: 120),
                       // pdfWidgets.Image(imageBrand, height: 512, width: 512),
                        pdfWidgets.Text(' FinderPet',
                            style: pdfWidgets.TextStyle(
                                fontSize: 40,
                                fontWeight: pdfWidgets.FontWeight.bold,
                                color: PdfColors.blue,
                                font: roboto)),
                      ]),
                    ),
                  ],
                )); // Center
          }));


      File file;
      if (kIsWeb) {
        await Printing.layoutPdf(
            onLayout: (PdfPageFormat format) async => pdf.save());
        await Printing.sharePdf(bytes: pdf.save(), filename: '$petName.pdf');
      } else {
        try {
          final output = await getTemporaryDirectory();
          file = File('${output.path}/$petName.pdf');
        } catch (e) {
          print(e);
        }
      }

      print('PDF guardado en:' + file.path);
      file.writeAsBytesSync(pdf.save());
      return file.path;

  }
`
Thanks in advance

**Comment by DavBfr** [comment]
Do something like:
```dart
Future<Uint8List> posterGenerator() {
.....
return pdf.save();
}

Future<void> print() async {
 await Printing.layoutPdf(
            onLayout: (PdfPageFormat format) async => await posterGenerator());
}
```

The full pdf must be designed within the latoutPdf callback, because it can be called multiple times with different setting

And pdf.save() can be called only once.

**Comment by DSMan97** [comment]
Thanks, you know any way to convert ImageNetwork to uint8list to use on the pdf, I tried with http.get solution but didn't work. Thanks in advance

**Comment by DavBfr** [comment]
```dart
 final image = await pdfImageFromImageProvider(
    pdf: pdf.document,
    image: NetworkImage(url),
);
```

**Comment by DSMan97** [comment]
Thanks

**Comment by DSMan97** [comment]
Sorry for disturbing you again, I will to pay you another coffee don't worry 😉 .

I implemented your suggestions and is working but without images, I mean I have to comment that pieces of code and comment on the pdf.Image part (red color).  

I have to comment these code:
`
PdfImage imageBrand = await pdfImageFromImageProvider(
      pdf: pdf.document,
      image: AssetImage('assets/icons/FinderPet_poster.png'),
    );


    PdfImage petImage;

    if(kIsWeb){

      petImage = await pdfImageFromImageProvider(
        pdf: pdf.document,
        image: NetworkImage(petFoto),
      );

    }else{

      petImage = PdfImage(
        pdf.document,
        image: await mPetImgCachetoPDF(petFoto),
        width: 300,
        height: 300,
      );

    }

On the PDF body I have to comment
 //pdfWidgets.Image(image),
`
If I do that the PDF works, but If I uncomment I obtain the following exception:
`
Exception: Image.toByteData is not supported in Flutter for Web
`
Thanks in advance

**Comment by DavBfr** [comment]
Ok, I can try to fix that.

**Comment by DavBfr** [comment]
It's not possible to fix it for Flutter web. See: 

Alternatively, you can use the `http` package:
```dart
        final response = await http.get('https://image.com');
        final petImage = PdfImage.file(
          doc.document,
          bytes: response.bodyBytes,
        );
```

Make sure your image server has the right CORS headers set:
Access-Control-Allow-Origin: *

**Comment by DSMan97** [comment]
I am using http package, and set header as yiu told me, but I am reciving this error:
 XMLHttpRequest error

That is my code:
`  var response = await http.get(

         petFoto,
         headers: {
           "Access-Control-Allow-Origin": "*" ,
         },
       );


       petImage = PdfImage(
        pdf.document,
        image: response.bodyBytes,
         width: 300,
         height: 300,`

**Comment by DavBfr** [comment]
Access-Control-Allow-Origin must be set on the server that hosts the image.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by DSMan97** [comment]
But the images are on firebase storage, how I can enable it on Firebase Storage?

**Comment by DavBfr** [comment]
I don't know.

**Comment by DSMan97** [comment]
Okey thanks any way, I will investigate about that, thanks for your help again

**Comment by jans-y** [comment]
@DSMan97  –  in case you haven't found it already:
https://cloud.google.com/storage/docs/configuring-cors
