### ISSUE TITLE
Print font error if the font screen display setting is large

### ISSUE THREAD

**Issue by vnlevanduoc** [DavBfr/dart_pdf#316]
I used the html string to print on the app and it got an error like the picture (1)

`https://upanh.vn-z.vn/images/2020/06/05/1.png`

But if I set the font on the screen display to be smaller then print it as I intended

Everyone has overcome, please guide me

Thanks

**Comment by DavBfr** [comment]
I don't know what you're doing, I need more info.

**Comment by vnlevanduoc** [comment]
Sorry I'm not good at English, so I can't explain it in detail
But I sent you video error status

`https://youtu.be/d3QMDvV8DiA`

When installing "Font size system" to "Large" when printed letters being delivered to faulty interface overlap or broken

But when converting "Font size system" to "Default", the interface will print as expected

**Comment by DavBfr** [comment]
I see, interesting, thanks.

**Comment by vnlevanduoc** [comment]
> I see, interesting, thanks.

I don't think there will be a quick response. I'm very happy

Hope you help me

Thanks very much

**Comment by DavBfr** [comment]
@vnlevanduoc this should be fixed in printing version 2.5.0.

**Comment by vnlevanduoc** [comment]
Thanks.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
