### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Rodgerkilzone** [DavBfr/dart_pdf#317]
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.8.1/lib/src/image.dart:121:40: Error: Getter not found: 'Format'.
      image: image.getBytes(format: im.Format.rgba),
                                       ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.8.1/lib/src/image.dart:124:35: Error: Getter not found: 'Channels'.
      alpha: image.channels == im.Channels.rgba,
                                  ^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.8.1/lib/src/image.dart:121:29: Error: No named parameter with the name 'format'.
      image: image.getBytes(format: im.Format.rgba),
                            ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.8.1/lib/src/image.dart:124:20: Error: The getter 'channels' isn't defined for the class 'Image'.
 - 'Image' is from 'package:image/src/image.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.7/lib/src/image.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'channels'.
      alpha: image.channels == im.Channels.rgba,

**Comment by DavBfr** [comment]
`flutter doctor -v` and `flutter pub outdated` please

**Comment by Rodgerkilzone** [comment]
Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 32-bit edition
    • Flutter extension version 3.9.1

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Note 7P • 3080SH2002046216 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
PS C:\Users\RODGER MANHATTAN\Desktop\test_print> flutter pub outdated 
Dependencies               Current  Upgradable  Resolvable  Latest   
printing                   *1.3.5   *1.3.5      3.4.0       3.4.0

dev_dependencies: all up-to-date

transitive dependencies
crypto                     *2.1.4   *2.1.4      *2.1.4      2.1.5
flutter_web_plugins        -        -           0.0.0       0.0.0
image                      *2.1.12  *2.1.12     *2.1.12     2.1.13
js                         -        -           0.6.1+1     0.6.1+1
path                       *1.6.4   *1.6.4      *1.6.4      1.7.0
petitparser                *2.4.0   *2.4.0      *2.4.0      3.0.4
plugin_platform_interface  -        -           1.0.2       1.0.2
xml                        *3.6.1   *3.6.1      *3.6.1      4.2.0

transitive dev_dependencies
test_api                   *0.2.15  *0.2.15     *0.2.15     0.2.16

1 dependency is constrained to a version that is older than a resolvable version.
To update it, edit pubspec.yaml.

**Comment by DavBfr** [comment]
Please use printing version 3.4.0

**Comment by Rodgerkilzone** [comment]
👍Thanks alot it's now working, I guess I had mixed the versions in pubspecs.yaml

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
