### ISSUE TITLE
Turn text into Vector

### ISSUE THREAD

**Issue by robertnem** [DavBfr/dart_pdf#319]
Hi, im trying to turn text into vectors (outline), and i don't know how. The print shop who i send my files only receives if the text isn't a vector.  Any ideia how to do it?

**Comment by DavBfr** [comment]
sorry, I don't know.

**Comment by westy92** [comment]
@robertnem I came here wondering the same thing. After some research, I found that you can use Ghostscript to convert fonts to vectors (with `-dNoOutputFonts`). Here's some more information: https://stackoverflow.com/a/28798374/453314.
