### ISSUE TITLE
Any idea how to access Border.all(), Image.network(), GoogleFonts and boxShadow property of Container.

### ISSUE THREAD

**Issue by DevyankShaw** [DavBfr/dart_pdf#320]
Any idea how to access Border.all(), Image.network(), GoogleFonts and boxShadow property of Container.

**Comment by DavBfr** [comment]
That's too many questions. Short answer: it's not implemented.

**Comment by DevyankShaw** [comment]
Thanks for your quick reply. But is there any alternative for that?

**Comment by DavBfr** [comment]
* Border.all() : use Border()

* Image.network()
```dart
image = await pdfImageFromImageProvider(
    pdf: pdf.document,
    image: NetworkImage(petFoto),
  );
```

* GoogleFonts: #298

* boxShadow: use some gradients and transparency do achieve the same effect, but printing shadow is usually not that nice

**Comment by DevyankShaw** [comment]
Thanks. But how to assign the PdfImage as a child to Expanded widget or how to convert PdfImage to a Widget?

`image = await pdfImageFromImageProvider(
    pdf: pdf.document,
    image: NetworkImage(petFoto),
  );`

**Comment by DavBfr** [comment]
like this:

```dart
final image = await getImage();

...

pw.Expanded(
flex: 1,
child: pw.Image(image),
)
```

**Comment by DevyankShaw** [comment]
Thanks, it worked!

Initially it showed the UI but after that it's only showing loading screen.

![WhatsApp Image 2020-06-08 at 9 36 49 AM](https://user-images.githubusercontent.com/47057254/83991829-a7cc4b80-a96b-11ea-990b-ed9eed8d2dd4.jpeg)
 it worked!.

On the console it's showing this: Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by DevyankShaw** [comment]
> Thanks, it worked!
> 
> Initially it showed the UI but after that it's only showing loading screen.
> 
> ![WhatsApp Image 2020-06-08 at 9 36 49 AM](https://user-images.githubusercontent.com/47057254/83991829-a7cc4b80-a96b-11ea-990b-ed9eed8d2dd4.jpeg)
> 
> On the console it's showing this: Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

Hey I fixed it.

By changing this:
` - assets/ `
to this: 
` - assets/Abel-Regular.ttf`

**Comment by Azzeccagarbugli** [comment]
I would love to understand how to do some basic shadow to any container too!

**Comment by firatcetiner** [comment]
> * Border.all() : use Border()
> * Image.network()
> 
> ```dart
> image = await pdfImageFromImageProvider(
>     pdf: pdf.document,
>     image: NetworkImage(petFoto),
>   );
> ```
> 
> * GoogleFonts: #298
> * boxShadow: use some gradients and transparency do achieve the same effect, but printing shadow is usually not that nice

Are there any news about web support for this functionality?
