### ISSUE TITLE
Add `PdfPreview` example to docs/readme.

### ISSUE THREAD

**Issue by divan** [DavBfr/dart_pdf#321]
Hey, thanks for an awesome library,

I want to propose to add `PdfPreview` widget code example to the README and pub text. Rendering PDF and previewing it in a widget might be the very first and obvious thing users want to try (before getting to actual printing/sharing functionality). At least that was the case for me, and I found it hard to find that PdfPreview widget even exists. (I read the readme page, example page, then went to github, issues, searched for "preview", found the some old issue that mention `PdfPreview` widget, went to look for API docs on it, but couldn't find it, and ended up reading up example code on github).

**Describe the solution you'd like**
 - Add the short example of using `PdfPreview` to the docs and readme page.

Thanks again for an incredible module!

**Comment by DavBfr** [comment]
Hi, yes if you want to add an example to the readme, please do a pull request. That's a great idea.

A small explanation on how to use it with flutter web would be good too, as I think no other package can do it.

Thanks.

**Comment by PraneethChandra18** [comment]
Could you pls write an example for the PdfPreview. I am unable to figure out how to do it.

**Comment by DavBfr** [comment]
Added in printing 3.6.1
