### ISSUE TITLE
No Margin When Printing via Printing.layoutPdf and BuildTheme prop ignoreMargins is true,

### ISSUE THREAD

**Issue by marcos930807** [DavBfr/dart_pdf#323]
**Describe the bug**
By enabling the ignoreMargins property to true in the pdf theme, for the sake of customizing the background borders etc, printing from PDF via Printing.layoutPdf used in PDFPreviewWidget, get a bad result(No margin), however when using the deprecated method Printing.printPdf (bytes : bytes); pdf printing preview looks good (No margin Issue).

This Code is the work around i am using, the curent method using Printing.layoutPdf has  the issue
Future<void> _print() async {
    final bytes = await widget.build(pageFormat);
    await Printing.printPdf(bytes: bytes);
    if (widget.onPrinted != null) {
      widget.onPrinted(context);
    }
  }

**Comment by DavBfr** [comment]
Can you send some screenshots? I don't get what's wrong.

**Comment by marcos930807** [comment]
![Screenshot_20200608-151809](https://user-images.githubusercontent.com/14100692/84071217-589e0f00-a99b-11ea-9a76-236cb79af5dc.jpg)
![Screenshot_20200608-151817](https://user-images.githubusercontent.com/14100692/84071221-5a67d280-a99b-11ea-8dd1-de268522d741.jpg)

**Comment by DavBfr** [comment]
Which one is right?

**Comment by marcos930807** [comment]
The first is the previewWidget, what I hope to get and the pdf that is generated by sharing, the second is the issue when using print.

**Comment by marcos930807** [comment]
if i use this:
**Future _print() async {
final bytes = await widget.build(pageFormat);
await Printing.printPdf(bytes: bytes);
if (widget.onPrinted != null) {
widget.onPrinted(context);
}
}**
I Get my espected result.

![Screenshot_20200608-153055](https://user-images.githubusercontent.com/14100692/84072303-f9d99500-a99c-11ea-86a1-767095d106f6.jpg)

**Comment by DavBfr** [comment]
That is strange. The Android preview will adapt the margins according to your real printer's physical margins, but it can only grow the margins, not stretch them.
Does your PR #324 improves things?

**Comment by marcos930807** [comment]
That PR is only to be able to customize the name of the generated pdf, if you want I can upload the method using
**final bytes = await widget.build (pageFormat);
await Printing.printPdf (bytes: bytes);**
But I didn't because it is a deprecated method.
What we can do?

**Comment by DavBfr** [comment]
it was more about the added pageFormat parameter.

Anyways, if you look at printPdf, it's just calling layoutPdf:

```dart
  /// Prints a [PdfDocument] or a pdf stream to a local printer
  /// using the platform UI
  @Deprecated('use Printing.layoutPdf(onLayout: (_) => document.save());')
  static Future<void> printPdf({
    @Deprecated('use bytes with document.save()') PdfDocument document,
    Uint8List bytes,
  }) async {
    assert(document != null || bytes != null);
    assert(!(document == null && bytes == null));

    layoutPdf(
        onLayout: (PdfPageFormat format) =>
            document != null ? document.save() : bytes);
  }
```

So I don't see how it could be different, except if your android device forces some margins.

Do you use `format` in your `onLayout` callback?

**Comment by marcos930807** [comment]
Hi I am here agai with some news.
This solve my Problem
Future<void> _print() async {
    final result = await Printing.layoutPdf(
      **onLayout: (PdfPageFormat _) => widget.build(pageFormat),**
      name: widget.pdfFileName,
      format: pageFormat,
    );

    if (result && widget.onPrinted != null) {
      widget.onPrinted(context);
    }
  }
I will open a pull request.

**Comment by DavBfr** [comment]
Can you send me the minimal example you have to reproduce?

**Comment by marcos930807** [comment]
Just run your demo proyect on Android device, be awere that logo and font assets on your demo dont exists. So i commented those lines.
