### ISSUE TITLE
Change backgroundColor of PDF

### ISSUE THREAD

**Issue by iamnishanth** [DavBfr/dart_pdf#326]
**How do i change the backgroundColor of Multipage PDF?** 

I want to change the backgroundColor for the following code.

**pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.fromLTRB(30, 30, 30, 30),
        build: (pw.Context context) {
          return [
            pw.Wrap(
              children: listOfWidgets,
            )
          ];
        }));**

**Comment by DavBfr** [comment]
Use the theme property, see #168

**Comment by iamnishanth** [comment]
Thank you!
