### ISSUE TITLE
how to change the color of the who page from white to diffrenert color 

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_pdf#329]
hi, i want to change baground color of the pdf page, 

i tried using PageTheme to return Container with color green but got below result , still not the whole page if covered.

![image](https://user-images.githubusercontent.com/47334522/84148367-923c4c00-aa67-11ea-8468-b302df23ea2d.png)

[prayer_time46.pdf](https://github.com/DavBfr/dart_pdf/files/4752170/prayer_time46.pdf)

**Comment by DavBfr** [comment]
Wrap the container with 
pw.FullPage(
        ignoreMargins: true,
        child: ......
)

**Comment by DavBfr** [comment]
Duplicates #329
