### ISSUE TITLE
How can I use rich text in MultiPage() ?

### ISSUE THREAD

**Issue by keshav1611** [DavBfr/dart_pdf#33]
I am creating a pdf in which I want a part of the text to be **Bold**. It can be done using rich text, but I guess support for rich text is not given in this plugin. Can you help me with that.

I tried to use multiple Text widgets but then the second Text widget goes to another line. Please tell me how to solve this.

_Expected:_
I want **something** like this.

_What I get:_
I am getting
**something**
like this

**Comment by DavBfr** [comment]
I guess you will have to write a RichText widget with Span child having a different font style.

**Comment by keshav1611** [comment]
But there is no RichText widget in **import 'package:pdf/widgets.dart'**.

**Comment by DavBfr** [comment]
Yes, you can contribute and create it.

**Comment by DavBfr** [comment]
I'm working on it

**Comment by DavBfr** [comment]
That's fixed in this repository, will be part of version 1.3.3
