### ISSUE TITLE
Reduce pdf size while saving

### ISSUE THREAD

**Issue by maxbhoria** [DavBfr/dart_pdf#335]
Hello,
I want to compress the pdf size containing multiple photos when saving into directory.

**Comment by DavBfr** [comment]
Convert your photos in jpeg, they will use less space.

**Comment by maxbhoria** [comment]
> Convert your photos in jpeg, they will use less space.

Yes i have reduced the image size but i have to store extra images in pdf file so i need to reduce the pdf size.

**Comment by DavBfr** [comment]
There is not much you can do then: Pdf is already a compressed file format.

**Comment by maxbhoria** [comment]
ok hope we will  get this update in future.

Thanks
