### ISSUE TITLE
Horizontally creating pdf

### ISSUE THREAD

**Issue by serdargu** [DavBfr/dart_pdf#337]
How can I create pdf as horizontal? I have applied the pageFormat as following (swapping the width, height)
PdfPageFormat(29.7 * cm, 21.0 * cm, marginAll: 2.0 * cm)
But it does not work.

**Comment by DavBfr** [comment]
How do you generate your Pdf?

**Comment by serdargu** [comment]
```
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
final doc = pw.Document();
doc.addPage(
  pw.Page(
    pageFormat: PdfPageFormat(29.7 * cm, 21.0 * cm, marginAll: 2.0 * cm),
    build: (pw.Context context) {
      return _buildPDFCalendar(_selectedDay, _events);
    },
  ),
);
await Printing.layoutPdf(
  onLayout: (PdfPageFormat format) async => doc.save(),
);
```
I am also using printing package to print the generated PDF

**Comment by DavBfr** [comment]
Ok, First you should put all your generation code inside the callback:
```dart
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
await Printing.layoutPdf(
  onLayout: (PdfPageFormat format) async {
final doc = pw.Document();
doc.addPage(
  pw.Page(
    pageFormat: PdfPageFormat(29.7 * cm, 21.0 * cm, marginAll: 2.0 * cm),
    build: (pw.Context context) {
      return _buildPDFCalendar(_selectedDay, _events);
    },
  ),
);

return  doc.save();
},
);
```

Next thing is that you can't force a page format, as it does not depends on you (the developer) but on what the actual paper the user has on their printer.
What you can do is to get the real paper format returned by the callback, and force the landscape orientation:

```dart
...

  pw.Page(
    pageFormat: format,
    orientation: PageOrientation.landscape,
    build: (pw.Context context) {
      return _buildPDFCalendar(_selectedDay, _events);
    },
  ),
...
```

**Comment by serdargu** [comment]
@DavBfr 
Thank you so much, that worked as I want.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
