### ISSUE TITLE
pdf Widgets Giving Errors.

### ISSUE THREAD

**Issue by ShubhamHande99** [DavBfr/dart_pdf#34]
The return type 'Container' isn't a 'Widget', as defined by anonymous closure

**Comment by ShubhamHande99** [comment]
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'dart:async';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';

import 'dart:ui' as ui;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pWidget;

class ExcelWrite extends StatefulWidget {
  _ExcelWriteState createState() => _ExcelWriteState();
}

class _ExcelWriteState extends State<ExcelWrite> {
  File imgFile;
  ByteData byteData;
  var rawImageData;
  var pdfHeight = 40;
  var dir;
  static GlobalKey previewContainer = new GlobalKey();
  final pWidget.Document pdf = pWidget.Document(deflate: zlib.encode);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('excel'),
      ),
      body: RepaintBoundary(
        key: previewContainer,
        child: Column(
          children: <Widget>[
            RaisedButton(
              onPressed: writePdf,
              child: const Text('Take a Screenshot'),
            ),
          ],
        ),
      ),
    );
  }

  writePdf() {
    final pdf = pWidget.Document()
      ..addPage(pWidget.MultiPage(
          pageFormat: PdfPageFormat.a4,
          header: (pWidget.Context context) {
            if (context.pageNumber == 1) {
              return null;
            }
            return Container(
              alignment: Alignment.center,
            );
            
          }));
  }

}

**Comment by DavBfr** [comment]
Because you have to prefix every pdf widgets with pWidget.

**Comment by ShubhamHande99** [comment]
Thanks Solved.

**Comment by Balthazar33** [comment]
> pWidget



> Because you have to prefix every pdf widgets with pWidget.
Thanks.
But what if I have a custom widget? How must one get that on the PDF?
