### ISSUE TITLE
Doesn't recognize the imported library.

### ISSUE THREAD

**Issue by tomasbaran** [DavBfr/dart_pdf#340]
**Describe the bug**

I need to save a QR code into a pdf. I'm importing the package `import 'package:qr_flutter/qr_flutter.dart';` yet it tells me I need to import the library.

I'm using this QR package: https://pub.dev/packages/qr_flutter 

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
 doc.addPage(pw.Page(
      build: (pw.Context context) => pw.QrImage(
              data: "http://google.com",
              version: QrVersions.auto,
              size: 200.0,
            ),
    ));
```

**Expected behavior**

**Screenshots**

<img width="952" alt="Captura de pantalla 2020-06-18 a las 13 57 55" src="https://user-images.githubusercontent.com/25743901/85023190-52165100-b16c-11ea-9e56-1eb24be07df6.png">

**Flutter Doctor**

```
[✓] Flutter (Channel dev, 1.19.0-4.0.pre, on Mac OS X 10.15.5 19F101, locale es-ES)
    • Flutter version 1.19.0-4.0.pre at /Users/tomas/Development/flutter
    • Framework revision 2f7a59a8da (13 days ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
The Pdf library can draw QRCodes already:
```dart
pw.BarcodeWidget(
            barcode: Barcode.qrCode(),
            data: "http://google.com",
            width: 200,
            height: 200,
),
```

**Comment by tomasbaran** [comment]
Cool. Thanks @DavBfr However now I get a different error:
<img width="611" alt="Captura de pantalla 2020-06-18 a las 14 28 51" src="https://user-images.githubusercontent.com/25743901/85025999-0a91c400-b170-11ea-920e-0b83e9de62b5.png">

**Comment by tomasbaran** [comment]
Never mind. I or you or both of us actually forgot to add `pw.` as a prefix.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by tomasbaran** [comment]
I also have problems with styling. These don't work:

## Styling issue 1

`style: TextStyle(color: pw.Colors.black,),`
### Error
The name 'Colors' is being referenced through the prefix 'pw', but it isn't defined in any of the libraries imported using that prefix.
Try correcting the prefix or importing the library that defines 'Colors'.

## Styling issue 2
`style: tsQRcode.copyWith(fontWeight: FontWeight.w500),` 
```
TextStyle tsQRcode = GoogleFonts.nunitoSans(
  textStyle: TextStyle(
    color: Colors.black,
    letterSpacing: 1,
    fontSize: 24,
    fontWeight: FontWeight.w900,
  ),
);

```
### Error
The argument type 'TextStyle (where TextStyle is defined in /Users/tomas/Development/flutter/packages/flutter/lib/src/painting/text_style.dart)' can't be assigned to the parameter type 'TextStyle (where TextStyle is defined in /Users/tomas/.pub-cache/hosted/pub.dartlang.org/pdf-1.8.1/lib/widgets/text_style.dart)'.
