### ISSUE TITLE
App freezes for like 10 secs before showing the preview screen anytime i create a new pdf

### ISSUE THREAD

**Issue by ifeoluwajoshua** [DavBfr/dart_pdf#343]
i used the following code to add my image as the background of my pdf :

final PdfImage backImage = PdfImage.file(
      pdf.document,
      bytes: (await rootBundle.load('images/axon1.png')).buffer.asUint8List(),
    );
    pdf.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a5,
      margin: pw.EdgeInsets.all(32),
      build: (pw.Context context) {
        return <pw.Widget>[
          pw.Container(
            decoration: pw.BoxDecoration(
              image: pw.DecorationImage(
                image: backImage,
                fit: pw.BoxFit.cover,
              ),
            ), ....................*/

**Comment by DavBfr** [comment]
Maybe you have too much image processing.
You can try to generate your pdf in an isolate.

check this example: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/isolate_test.dart

**Comment by ifeoluwajoshua** [comment]
and again....

i have been trying to show a list of pdfs files that have been generated by the same app on a new screen can you help with that

**Comment by ifeoluwajoshua** [comment]
i only added one image

**Comment by DavBfr** [comment]
Maybe a release build on a real device will be faster.

**Comment by ifeoluwajoshua** [comment]
> and again....
> 
> i have been trying to show a list of pdfs files that have been generated by the same app on a new screen can you help with that

this

**Comment by DavBfr** [comment]
I don't know about that.

**Comment by ifeoluwajoshua** [comment]
what adding signature to the pdf contents before saving

**Comment by DavBfr** [comment]
Like a cryptographic digital signature?

**Comment by ifeoluwajoshua** [comment]
Yeah like a hand signature.....
writing signature

**Comment by DavBfr** [comment]
It's an image then. I think you can find flutter plugins for users to draw on screen
