### ISSUE TITLE
 Unhandled Exception: FileSystemException: Cannot open file, path = 'example.pdf' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by kratipandey57** [DavBfr/dart_pdf#344]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Looks like you're doing something wrong with the file.
