### ISSUE TITLE
how to loop data in package pdf data display on table

### ISSUE THREAD

**Issue by deddyprianto** [DavBfr/dart_pdf#348]
i to try loop data in package pdf but , i find error. is there anyone who wants to help me
please

**Comment by rsmaximiliano** [comment]
What code are you using? I am using this and works
```
 ListView.separated(
                  padding: const EdgeInsets.all(8),
                  separatorBuilder: (_, int index) => Divider(),
                  itemCount: CartModel().productsShopped.length,
                  itemBuilder: (_, int index) {
                    return Container()
```

**Comment by deddyprianto** [comment]
tks, for your respons , i have using dart code

**Comment by deddyprianto** [comment]
where you place your code , 
I place the code in 

 pdf.addPage(
        pdfLib.MultiPage(pageTheme: pageTheme, build: (context) => items));
    Printing.sharePdf(bytes: pdf.save(), filename: 'dataabsenonline.pdf');
  }


Is this true ? 

please help me  , whoever the person is I really appreciate it

**Comment by rsmaximiliano** [comment]
Using inside of builder:
 ```
 pdf.addPage(
      Page(
          pageFormat: PdfPageFormat.a4,
          build: (Context context) {
            return ListView.separated
```

In this file, you need to use pdf library widgets, NOT MATERIAL nor CUPPERTINO
`import 'package:pdf/widgets.dart';`

**Comment by deddyprianto** [comment]
![code](https://user-images.githubusercontent.com/59042228/85987694-2d499580-ba18-11ea-9d68-aefa5e1f7bad.png)

I'm still having an error, sir

**Comment by deddyprianto** [comment]
this is the error sir
The return type 'ListView' isn't a 'List<Widget>', as defined by anonymous closure.dart(return_of_invalid_type_from_closure)

**Comment by deddyprianto** [comment]
I have done what you told me to, and have imported this package
import 'package:pdf/widgets.dart' as pdfLib;

**Comment by deddyprianto** [comment]
and i'm still having error , in builder

**Comment by rsmaximiliano** [comment]
Where is your list for iterate? You need also define itemBuilder and itemCount

**Comment by deddyprianto** [comment]
![code2](https://user-images.githubusercontent.com/59042228/85989689-0e003780-ba1b-11ea-9c7d-682a8a339782.png)

i loop data from cloudfirestore firebase

**Comment by rsmaximiliano** [comment]
ListView.separated(
                  padding: const EdgeInsets.all(8),
                  separatorBuilder: (_, int index) => Divider(),
                  itemCount: **items**.length,
                  itemBuilder: (_, int index) {
                    return Text(**items**[index].yourProp)

**Comment by deddyprianto** [comment]
thanks a lot  for your respons sir , i I really appreciate it. 
i try, sir

**Comment by deddyprianto** [comment]
![code4](https://user-images.githubusercontent.com/59042228/86034427-cbfbe380-ba64-11ea-9c15-e20bdc0050b8.PNG)

sir , i find error only this , i try to display data , but error , pls help me , i try so hard to finish it but i not find the solution , pls help me

**Comment by rsmaximiliano** [comment]
Use:
` querySnapshot.documents[index]`

**Comment by deddyprianto** [comment]
thankyou for you attention sir , the program will be finished , thank's a lot for your  help for me


but I am still confused about text (''), the word text ('') must not be null. I can solve this problem, by adding conditions to text (), but creating a dart conditioning like this ? :  both if and else conditions are executed, so when I add an empty string or add another string, it will still be displayed

how is it, so that the data is displayed without any other string

please help, sir
I will thank you very much for your help

**Comment by rsmaximiliano** [comment]
`return (querySnapshot.documents[index].data == null) ? Container() : Text(querySnapshot.documents[index].data);`

**Comment by deddyprianto** [comment]
![code](https://user-images.githubusercontent.com/59042228/86338783-f2946700-bc7c-11ea-9d0f-dcd4b3920f24.png)

sir may i ask again , it is different from package pdf , it is the problem about flutter material
type 'Container' is not a subtype of type 'String'
can you help me sir ,

**Comment by deddyprianto** [comment]
![Capture](https://user-images.githubusercontent.com/59042228/86340636-6b94be00-bc7f-11ea-8ec4-9558589a933c.PNG)

This is a error that I got, sir

**Comment by rsmaximiliano** [comment]
Because you write wrong...

```
Center(child: 
    (task['name'] == null) ? Container() : Text(task['name'])
)
```

**Comment by deddyprianto** [comment]
i so sorry sir , i am late reply your message
thank u so much for that your help sir , all your help very much help me.
may i ask something sir i have a problem i hope you can help me

<https://stackoverflow.com/posts/62957218/timeline>

I work on flutter and develop an Android application that is absent online,
but I have a problem when the first user is absent and the data in the
application. other users can read the user data first. please help,

how to make user data inaccessible to other users even though using the
application on flutter and dart, please help

i ask that in forum stackoverflow but i try ask to you sir,

can you help me?? or can you give me a reference for my problem

i appreciate your help sir

Pada tanggal Rab, 15 Jul 2020 pukul 19.23 David PHAM-VAN <
notifications@github.com> menulis:

**Comment by DavBfr** [comment]
Sorry I don't know about that.

**Comment by deddyprianto** [comment]
oke sir , thank you very much

Pada tanggal Sab, 18 Jul 2020 pukul 10.13 David PHAM-VAN <
notifications@github.com> menulis:
