### ISSUE TITLE
Long words don't get wrapped in Text widget

### ISSUE THREAD

**Issue by roxifas** [DavBfr/dart_pdf#349]
**Describe the bug**
Words, that are longer than what can fit in a single line, don't get wrapped in the Text widget and go outside of the given constraints. With shorter words wrapping works correctly.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
SizedBox(
  width: 50,
  child: Row(children: [
    Expanded(child: Text('XXXXXXXXXXXXX')),
    Expanded(child: Text('OOOOOOOOOOOOO')),
  ]),
)
```

**Expected behavior**
I'd expect the word to be wrapped to a new line

**Screenshots**
The given code snippet produces this:
![image](https://user-images.githubusercontent.com/58729309/85684287-a5415400-b6d6-11ea-8b68-12d02667f95a.png)

**Comment by DavBfr** [comment]
The library will not wrap text that does not contain spaces.
