### ISSUE TITLE
Set the filename for sharing

### ISSUE THREAD

**Issue by rmtmckenzie** [DavBfr/dart_pdf#35]
It would be nice to be able to set a (default) filename for saving instead of the "document##############.pdf" it currently does when you share.

I couldn't see anything that would do this, but if I missed it I'd be happy to find that out =). I tried setting the PDFInfo.title and that didn't do it.

**Comment by DavBfr** [comment]
Good point! I'll add that.

**Comment by DavBfr** [comment]
Added in next 1.3.4 version

**Comment by rmtmckenzie** [comment]
That's awesome, thanks 😄
