### ISSUE TITLE
Custom Font | error on assert(left <= right) | FontMetrics

### ISSUE THREAD

**Issue by gastrolize** [DavBfr/dart_pdf#350]
Hello I tried to create a PDF and loaded my fonts like

`harlow = pw.Font.ttf(await rootBundle.load("fonts/harlow.ttf"));
    sansMedium = pw.Font.ttf(await rootBundle.load("fonts/sansMedium.ttf"));
    sansBold = pw.Font.ttf(await rootBundle.load("fonts/sansBold.ttf"));`

Now I get this error when trying to save the PDF:

`Failed Assertion: line 38 pos 16: left <= right: is not true`

**Comment by DavBfr** [comment]
Looks like one of your fonts is not really a ttf file.
