### ISSUE TITLE
Show network image?

### ISSUE THREAD

**Issue by rsmaximiliano** [DavBfr/dart_pdf#351]
I load images from an API to display products, when user proceeds to checkout can generate a pdf with only product images that selected... How can achieve this? PdfImage.network is not available, is there any other way?

**Comment by DavBfr** [comment]
You can use a download function like this: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/utils.dart#L27

**Comment by rsmaximiliano** [comment]
Thanks! Recently I used this:
 ```
Response response = await get(imageUrl);
Uint8List imgBytes = response.bodyBytes;
```
...

```
 Image(PdfImage.file(pdf.document, bytes: imgBytes)),
```
