### ISSUE TITLE
Strange Line in TableRow Center 

### ISSUE THREAD

**Issue by Peet-A** [DavBfr/dart_pdf#352]
**Describe the bug**
 some time i found a line in the middle of a table row , like the following picture  , this is not happening every time , some times   , any idea what is the issue here ?
I am using the latest version 1.9.0 .   

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
 mainTable.add(
    pdfLib.TableRow(
        verticalAlignment: pdfLib.TableCellVerticalAlignment.middle,
        decoration: pdfLib.BoxDecoration(
          border: pdfLib.BoxBorder(
              right: true, left: true, top: true, bottom: true),
        ),
        children: [

          pdfLib.Center(
            child: pdfLib.Image(detailsTitle, width: 50, height: 40),
          ),

```

**Expected behavior**

**Screenshots**

<img width="679" alt="Screen Shot 2020-06-26 at 3 32 43 PM" src="https://user-images.githubusercontent.com/22204356/85863619-b6b45a00-b7c3-11ea-9130-93dd2d1a7dce.png">

**Comment by DavBfr** [comment]
Sorry, I can't reproduce that.
