### ISSUE TITLE
jpg image not loading from cashe or internal storage

### ISSUE THREAD

**Issue by tuhincse08** [DavBfr/dart_pdf#353]
**Describe the bug**

Image not loading properly broken image. The image path is like Its image path is like "/data/user/0/com.abc.pdfdevelop/app_flutter/Images/1593177139472.jpg" 
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code

 PdfImage image = new PdfImage.file(
                doc.document,
                bytes: (File(imageName).readAsBytesSync()),
              );

```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [ ] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Can you send this image?

**Comment by tuhincse08** [comment]
Hi Dave,
Thanks for your reply. The image is any image that I take from camera.
The issue is solved using async pdfImageFromImageProvider() function. The example code usually don't work properly even for asset image.

**Comment by DavBfr** [comment]
I can't reproduce.
