### ISSUE TITLE
(somewhat) Fail to use Chinese TTF to generate PDF 

### ISSUE THREAD

**Issue by zwchenlong** [DavBfr/dart_pdf#355]
Dear Sir,

I've been trying to use the pdf package to generate a PDF in Chinese and print it out.

Everything was working fine until I add more content using the widget approach, then the document.save() return nothing.

I've try track the problem and I got and 'RangeError (byteOffset): Index out of range: index should be less than 276: 276' error.  Please find the trace as below.  It seems the problem lies on the TTF part, but I don't know how to fix.

I've been using three different TTF file for testing purpose, and all get the same result.

#0      _ByteDataView.setUint8 (dart:typed_data-patch/typed_data_patch.dart:4509:7)
#1      TtfWriter.withChars (package:pdf/src/ttf_writer.dart:203:18)
#2      PdfTtfFont._buildType0 (package:pdf/src/ttffont.dart:95:38)
#3      PdfTtfFont._prepare (package:pdf/src/ttffont.dart:136:7)
#4      PdfObject._write (package:pdf/src/object.dart:53:5)
#5      PdfOutput.write (package:pdf/src/output.dart:69:8)
#6      SetMixin.forEach (dart:collection/set.dart:142:30)
#7      PdfDocument._write (package:pdf/src/document.dart:179:13)
#8      PdfDocument.save (package:pdf/src/document.dart:187:5)
#9      Document.save (package:pdf/widgets/document.dart:76:21)
#10     pdfDocument (package:zwchenlongapp/widgets/pdf_widget.dart:41:14)
<asynchronous suspension>
#11     HomeScreen._printDocument.<anonymous closure> (package:zwchenlongapp/screens/home_screen.dart:135:33)
#12     MethodChannelPrinting._handleMethod (package:printing/src/method_channel.dart:57:41)
#13     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:432:55)
#14     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:385:33)
#15     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
#16     _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _invoke3 (dart:ui/hooks.dart:281:10)
#21     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)

**Comment by zwchenlong** [comment]
I tried with another font, like: https://github.com/ButTaiwan/genyo-font/raw/master/TW/GenYoMinTW-Heavy.ttf as listed on issue #224 but still got the same result.

**Comment by zwchenlong** [comment]
After several try and error, I discover the issue only appear provided the Chinese characters is over a particular number.  By deducing the characters the issue disappeared and the document can show up.

**Comment by idootop** [comment]
Same problem. This problem arises when I have more than one page of Chinese documents. But I don't think that by reducing the number of Chinese characters is the solution, in fact I need to display more Chinese characters in my
![Snipaste_2020-08-10_19-33-50](https://user-images.githubusercontent.com/35302658/89778631-707f4400-db40-11ea-9502-1260fa432d95.png)
 document, so the problem still exists.

**Comment by idootop** [comment]
> 
> 
> After several try and error, I discover the issue only appear provided the Chinese characters is over a particular number. By deducing the characters the issue disappeared and the document can show up.

Here's how I solved it.

![Snipaste_2020-08-10_20-08-45](https://user-images.githubusercontent.com/35302658/89781138-598f2080-db45-11ea-9dcf-a342d6f8fe86.png)

**Comment by zwchenlong** [comment]
> > After several try and error, I discover the issue only appear provided the Chinese characters is over a particular number. By deducing the characters the issue disappeared and the document can show up.
> 
> Here's how I solved it.
> 
> ![Snipaste_2020-08-10_20-08-45](https://user-images.githubusercontent.com/35302658/89781138-598f2080-db45-11ea-9dcf-a342d6f8fe86.png)

Thank you!  You really save my day!

**Comment by DavBfr** [comment]
Can you provide an example that fails so I can create a unit-test?

**Comment by idootop** [comment]
> 
> 
> Can you provide an example that fails so I can create a unit-test?

Here's one.
[https://github.com/idootop/resume_flutter](https://github.com/idootop/resume_flutter)

**Comment by DavBfr** [comment]
Fixed in pdf-1.10.1
