### ISSUE TITLE
Did not work on Android.(Works fine on iOS)

### ISSUE THREAD

**Issue by Slymn10** [DavBfr/dart_pdf#356]
This is my error :
/Users/suleymankocak/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/printing-2.1.9/android/src/main/java/net/nfet/flutter/printing/PrintingPlugin.java:91: error: cannot find symbol
            Log.e("PrintingPlugin", "Registration failed", e);
            ^
  symbol:   variable Log
  location: class PrintingPlugin
1 error

FAILURE: Build failed with an exception.

 What went wrong:
Execution failed for task ':printing:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 28s
Exited (sigterm)
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by DavBfr** [comment]
Please update your dependencies, the latest version is 3.6.0.
