### ISSUE TITLE
Adding  a spacer in cm in the PDF

### ISSUE THREAD

**Issue by Peet-A** [DavBfr/dart_pdf#357]
How can i add a fixed heights spaces in cm unit as a spacer between pdf widgets while creating it  , to manage to create the same pdf dimensions from different devices , thanks .

**Comment by DavBfr** [comment]
Use the cm modifier: `PdfPageFormat.cm`.
for 3 cm:

```dart
SizedBox(height: 3 * PdfPageFormat.cm)
```

**Comment by Peet-A** [comment]
thanks a lot david , you are very helpful , i wish you a great day .
