### ISSUE TITLE
Merge pdfs

### ISSUE THREAD

**Issue by phcs971** [DavBfr/dart_pdf#358]
**Is your feature request related to a problem? Please describe.**
I am building an app for an industry, and the user might be creating about 18-30 pdfs per construction, but they want to recieve one pdf only for better organization. So I would need a way to merge those pdfs into one.

**Describe the solution you'd like**
It would be really helpful to have a way to add a page from a pdf file, or a way to open a pdf document, like pw.Document.fromFile(File file) and then merge two Documents.

**Describe alternatives you've considered**
I considered making the pdf an image and then adding the image, but that would be better and less costly. I also tried to use a database to store the pdfs variables, but each pdf would have 6-7 photos and they don't want me to use network based ones.

**Additional context**
If there is already a way to do it, even if it is by saving the pdf as image, please help me. Thank you.

**Comment by DavBfr** [comment]
Sorry, there is no way to do it. See #271 
A workaround is to use Printing.raster to create some images from an existing pdf and include them in a new file as you suggested.
