### ISSUE TITLE
childrens Of Column widget  won't fit into the page

### ISSUE THREAD

**Issue by pathakvivek7865** [DavBfr/dart_pdf#36]

**Comment by pathakvivek7865** [comment]
i was using Column widget inside which i was putting data dynamically into Table.
But when the tables are more than 3 it throws error like
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (30608): Exception: Widget won't fit into the page
E/flutter (30608): #0      MultiPage.generate 
../…/widgets/document.dart:222
E/flutter (30608): #1      Document.addPage 
../…/widgets/document.dart:42
E/flutter (30608): #2      saveAsPdf

**Comment by DavBfr** [comment]
Yes, if your page is too short for the content, this exception will show.

**Comment by DCubix** [comment]
How do we work around this? I have a big amount of data and this exception doesn't let me put the table in the document and my app crashes.

**Comment by DavBfr** [comment]
A column is limited to one page only, a table alone can spread across pages in a MultiPage(), only as a direct child.

**Comment by DCubix** [comment]
Oh thank you very much
