### ISSUE TITLE
PdfPreview renders inaccurate colors on Android

### ISSUE THREAD

**Issue by jans-y** [DavBfr/dart_pdf#360]
**Describe the bug**

I am succesfully using your plugin on iOS, Android, Web & macOS platforms.

However, when previewing the generated document in your PdfPreview widget on Android, colors of "vectors" (text, chart, container borders) have high brightness or gamma - raster images are rendered correctly.

The problem is only with the PdfPreview widget and only on Android. When the generated file is shared, it's ok on other devices.

I can send you the screenshots on email if you are unable to reproduce the problem.

**Flutter Doctor**

```
 Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.2)
```

**Smartphone (please complete the following information):**
 - Device: Huawei P smart 2019
 - OS: 10.0.0.179
- versions:
```
printing: 3.5.0
pdf: 1.9.0
```

**Thank you for your great work.**

**Comment by DavBfr** [comment]
Hi @jans-y, yes I'd like to see what you're experiencing.

**Comment by DavBfr** [comment]
Looks like transparency is not properly supported.

**Comment by jans-y** [comment]
Hello,

the issue is still present for me in the latest releases.

Can you recommend possible solutions?

Thank you.

**Comment by DavBfr** [comment]
@jans-y I can't reproduce it. Can you try the Printing.raster() method and save the image to a png file. Then see if the generated file is correct.

**Comment by marlonmartina** [comment]
Experiencing the same problem. When i use a stack and add containers with colors, and on top of that plot a bar chart. The colors will appear perfectly fine in the previewer on iOS, but on Android are very vague or completely invisible. But when i use the share to printing button and open the print view example, the colors show normal.

```
pw.Container(
              height: 320,
              width: 470,
              child: pw.Stack(
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.only(top: 15),
                    child: pw.Column(
                      children: [
                        pw.Opacity(
                          opacity: 0.5,
                          child: pw.Align(
                            alignment: pw.Alignment.topRight,
                            child: pw.Container(
                              height: 85,
                              width: 415,
                              color: PdfChartColors.bad.pick(),
                            ),
                          ),
                        ),
                        pw.Opacity(
                          opacity: 0.5,
                          child: pw.Align(
                            alignment: pw.Alignment.topRight,
                            child: pw.Container(
                              height: 197,
                              width: 415,
                              color: PdfChartColors.good.pick(),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  pw.Chart(
                    title: pw.Text('title'),
                    grid: pw.CartesianGrid(
                      xAxis: pw.FixedAxis.fromStrings(
                        [],
                        margin: 10,
                        ticks: true,
                      ),
                      yAxis: pw.FixedAxis(
                        [1, 2, 3],
                        divisions: true,
                        format: (value) => value.toStringAsFixed(0),
                      ),
                    ),
                    datasets: [
                      pw.BarDataSet(
                        color: PdfChartColors.own.pick(),
                        width: 40,
                        offset: -25,
                        borderColor: PdfChartColors.own.pick(),
                        data: List<pw.PointChartValue>.generate(
                          5,
                          (i) {
                            return pw.PointChartValue(i.toDouble(), 1);
                          },
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
```
In app preview
![Screenshot 2023-03-30 at 12 42 18](https://user-images.githubusercontent.com/45872721/228811850-57f1a415-0820-44e4-931b-bb5900f8c980.png)

In printer preview
![Screenshot 2023-03-30 at 12 42 09](https://user-images.githubusercontent.com/45872721/228811879-b88e5e5f-4d84-4930-8327-ff5ccabe76d3.png)
