### ISSUE TITLE
Samsung Internet 12.0.1.47 Browser unable to export PDF

### ISSUE THREAD

**Issue by tomasbaran** [DavBfr/dart_pdf#362]
**Describe the bug**
After you click on download the pdf, it doesn't do anything. Works perfectly on the same phone (Samsung A20, Android 9) on Chrome browser.

**Expected behavior**

**Mobile (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser

**Smartphone (please complete the following information):**
 - Device: Samusung A20
 - OS: Android 9
 - Browser Samsung Internet 
 - Version 12.0.1.47

**Additional context**

**Comment by DavBfr** [comment]
I have no way to test this. But you can fix the issue and create a PR.

**Comment by tomasbaran** [comment]
@DavBfr I wish I could... but I'm only a novice programmer, so won't be helpful here.

**Comment by tomasbaran** [comment]
@DavBfr but I'm happy to test the functionality once you fix it.

**Comment by DavBfr** [comment]
Could you find the UserAgent for the Samsung and Xiaomi browsers?

**Comment by tomasbaran** [comment]
Xiaomi I can do in a few weeks if it's okay since it's on my friend's phone. But if you need it sooner, let me know I'll do my best to get it sooner.

In the meantime, this is Samsung Browser User Agent:

![Screenshot_20200706-204513_Samsung Internet](https://user-images.githubusercontent.com/25743901/86634802-9d38bc80-bfd2-11ea-905e-2eab71ac842f.jpg)

**Comment by DavBfr** [comment]
Fixed in pdf-1.13.0
