### ISSUE TITLE
xiaomi redmi note 8T' default/stock Browser can't export pdf

### ISSUE THREAD

**Issue by tomasbaran** [DavBfr/dart_pdf#363]
**Describe the bug**
I have tried iPhone, macOS, Windows, Google chrome and all worked. Where it's not working is xiaomi redmi note 8T's stock browser. Works perfectly on the same phone on Chrome browser.

**Actual behavior**
![WhatsApp Image 2020-07-03 at 16 12 49 (2)](https://user-images.githubusercontent.com/25743901/86482394-24c3c880-bd52-11ea-9ce8-6a76f5fc3920.jpeg)

**Additional Screenshots**
Maybe this has something to do with it? This QTAudioEngine takes browser to my Flutter URL...
![WhatsApp Image 2020-07-03 at 17 26 04](https://user-images.githubusercontent.com/25743901/86482652-ab78a580-bd52-11ea-8304-e02f854c89b4.jpeg)

**Flutter Doctor**

```
```

**Mobile (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [x] Browser

**Smartphone (please complete the following information):**
 - Device: xiaomi redmi note 8T
 - OS: Android 9
 - Browser  stock browser
 - Version 12.2.6-g

**Additional context**

**Comment by DavBfr** [comment]
I have no way to test this. But you can fix the issue and create a PR.

**Comment by tomasbaran** [comment]
@DavBfr I wish I could... but I'm only a novice programmer, so won't be helpful here.

**Comment by tomasbaran** [comment]
here is the UserAgent:
![WhatsApp Image 2020-07-07 at 23 25 50](https://user-images.githubusercontent.com/25743901/86845505-e6a80b00-c0a9-11ea-8eb4-56aa431f4fdb.jpeg)

**Comment by DavBfr** [comment]
Fixed in pdf-1.13.0
