### ISSUE TITLE
Pass parameter dinamically, using the example

### ISSUE THREAD

**Issue by ElaineSchwner** [DavBfr/dart_pdf#364]
Thank you for this awesome lib!

I am trying to use the example with the resume. But I need to pass parameters to change the text in the document.

Map info = Map();

I am trying to do this:

    return Scaffold(
      appBar: Layout().appbar(''),
      body: PdfPreview(
        maxPageWidth: 700,
        build: generateResume(info),
        actions: actions,
        onPrinted: _showPrintedToast,
        onShared: _showSharedToast,
      ),
    );

I can't pass any parameter to change the pdf.
Warning:     The argumet type 'Future<Uint8List>' can't be assigned to the parameter type 'FutureOr<Uint8List> Function(PdfPageFormat)'.

What cant I do to correct this?
Thank you

**Comment by DavBfr** [comment]
build takes a function, so you can do:
```dart
return Scaffold(
  appBar: Layout().appbar(''),
  body: PdfPreview(
    maxPageWidth: 700,
    build: (f) => generateResume(f, info),
    actions: actions,
    onPrinted: _showPrintedToast,
    onShared: _showSharedToast,
  ),
);
```

**Comment by ElaineSchwner** [comment]
> build takes a function, so you can do:
> 
> ```dart
> return Scaffold(
>   appBar: Layout().appbar(''),
>   body: PdfPreview(
>     maxPageWidth: 700,
>     build: (f) => generateResume(f, info),
>     actions: actions,
>     onPrinted: _showPrintedToast,
>     onShared: _showSharedToast,
>   ),
> );
> ```

It works well!
Thank you!
