### ISSUE TITLE
Page numbers and footnotes in each page converted from html

### ISSUE THREAD

**Issue by rlbartz** [DavBfr/dart_pdf#367]
I'm struggling to include page numbers and footer text in a html text converted to pdf by the Printing library (printing: ^3.5.0). I think this option is not available yet, and could be included in future. Here is my code:

` String myHtmlText = "<html>Here are lots of tags which gererate more than one pdf page</html>"; 
  String targetPath = (await getApplicationDocumentsDirectory()).path;
  var targetFileName = "myReport";
  File pdfFile = new File(targetPath + "/" + targetFileName + ".pdf");
    Uint8List pdfData = await Printing.convertHtml(
          format: PdfPageFormat.a4,
          html: myHtmlText,
    );

   await arquivoPdf.writeAsBytes(pdfData);`

I would like to print in each page a text like the following:

Page 1 of 20
Printend by myAPP

**Comment by DavBfr** [comment]
If you use the Html converter, you have to write the page numbers using html and css. I can't help.
