### ISSUE TITLE
demo assets missing

### ISSUE THREAD

**Issue by AnotherCodeSegment** [DavBfr/dart_pdf#368]
**Describe the bug**
I like the demo, it is very good and serves the purpose of demonstrating the lib. It compiles out of the box but running is less fun as it does not provide any of the needed assets, e.g. roboto font files, open-sans font files, images... all missing in the asset folder just containung a ".gitkeep".

**Expected behavior**
I do not know if licenses permit adding these files into the repo, if not, maybe you could add URL pointers pointing to sources of these assets? Expected behavior would be an out-of-the-box testing experience (optimal) or collecting the assets via your list of URLs, dropping them into the project folder and then running it (that's ok, too).

**Screenshots**
Red screens on (Android) device: "Unable to load asset: assets/open-sans-bold.ttf".

**Comment by DavBfr** [comment]
just run `make` in the root of the project, it will download all assets. At least on Linux/macOS. Should work with WSL too though.

**Comment by AnotherCodeSegment** [comment]
Indeed, there is a Makefile in the root directory, did not see that coming... thanks for the quick reply! :)
