### ISSUE TITLE
Direct print implementation

### ISSUE THREAD

**Issue by TristanPct** [DavBfr/dart_pdf#37]
I'm currently developing an iOS Flutter app who need background printing.  
I look at this plugin and starting a fork to implement the iOS `UIPrintInteractionController` `printToPrinter` method allowing to print without showing the native UI.

I simply made a copy of `printPdf` method (in `PrintingPlugin.m`) and replacing 
```objective-c
[controller presentAnimated:YES completionHandler:completionHandler];
```
with
```objective-c
NSURL* printerURL = [NSURL URLWithString:printerID];
UIPrinter* printer = [UIPrinter printerWithURL:printerURL];

[controller printToPrinter:printer completionHandler:completionHandler];
```
Having `printerID` a `NSString` passed as parameter.

But when I call this method, a popup show up saying:
> Printing to "my-printer.local."
> Contacting printer...

And the popups "Cancel" button doesn't work...

Anyone seeing what's happens?

Here is my fork with `PrintingPlugin.m` and `printing/example` modified: https://github.com/TristanPct/dart_pdf

Here is the StackOverflow issue referencing the same issue: https://stackoverflow.com/questions/54810047/ios-uiprintinteractioncontroller-printtoprinter-contacting-printer

**Comment by DavBfr** [comment]
If you end up with something, I'd be happy to integrate it into this plugin.

**Comment by DavBfr** [comment]
@TristanPct Could you make something that works?

**Comment by TristanPct** [comment]
Hi, I'm still investigating on this.
I'm currently looking at that Cordova plugin which implements this functionality (and make it works) to find some answers: https://github.com/katzer/cordova-plugin-printer

**Comment by DavBfr** [comment]
The iOS code is now full Swift.

**Comment by TristanPct** [comment]
I saw it recently, I rebase my fork to continue with the Swift version, but the issue is still there for the moment...

**Comment by TristanPct** [comment]
Problem seems to come from: 
https://github.com/DavBfr/dart_pdf/blob/924ff54388d91c25886f719848d874a57c180672/printing/ios/Classes/PageRenderer.swift#L69
On a normal print (with print preview) `invokeMethod` is called and trigger the Dart `onLayout` callback, but using the direct print `invokeMethod` is called but the Dart callback is never triggered... 
(And `lock?.unlock()` is not called so the UI stays frozen.)

A breakpoint here is never hit with direct print:
https://github.com/DavBfr/dart_pdf/blob/924ff54388d91c25886f719848d874a57c180672/printing/lib/src/printing.dart#L26

Have you an idea why in this use case the `invokeMethod` doesn't trigger the Dart callback ?

**Comment by DavBfr** [comment]
It is because controller.print does not spawn a new thread and you are stuck in a deadlock.

The best would be to:

1.  get the paper size and margins from the UIPrinter,
2.  start a new thread to wait the onWrite finishes (lock.lock())
3.  call onLayout
4.  call  controller.print(..)

If we can also have a list of printers on the dart side, that would be better instead of relying on iOS default interface, but that's the second part.

Then we need the same for Android ;)

**Comment by TristanPct** [comment]
I'm not very comfortable with Swift (first time using it, same with Objective-C), I don't fully understand the thread system here...

On the code, `onLayout` is called by the `renderer` which is called by `controller.print()`, do we have to change call order?

I've not look yet for a Dart side list of printers, I don't know if you can get printer without using native UI.

For Android a native printer picker UI exist but apparently no native way to make a background print...

**Comment by DavBfr** [comment]
I'm not the pose experienced iOS developer too.
I think the order must be a little different: We might need the full page rendered before calling the controller.print() method. And as we control every aspect before that, it's fine.
With the dialog print, the OS calls the rendering in a separated thread, that's why I have some locks to synchronize and simulate an event system like on Android.

**Comment by TristanPct** [comment]
`UIPrinter` doesn't give information about paper size and margin.
I tried to get `renderer.paperRect` to give it to `onLayout` before calling `controller.print` but size and margins are set to 0 at this point.

I tried all combinations of `lock?.lock()` around `onLayout` invocation, the Dart code is fully executed (contrary to what I said before), but when the Dart code run `await _channel.invokeMethod('writePdf', params);` the Swift `writePdf` method is not called (with and without lock around invoke).

For what I understood, a first lock is needed before `onLayout` invocation, to make invocation thread safe, then a second lock is needed to wait for `writePdf` invocation, this one is unlock in `renderer.setDocument()` and then an another unlock for the first lock.

Also, `controller.print()` trigger `renderer.numberOfPages` which call `onLayout` too.

**Comment by DavBfr** [comment]
Yes, it was quite tricky to make it work correctly with the print dialog. The Android version is much more simple.

**Comment by joeblew99** [comment]
i am working on Windows and Mac versions, so a NON Native Print Window is really helpful.

Will let you knwo when i get somewhere with it.
Yell if you are interested...

**Comment by DavBfr** [comment]
NON-Native Print Window seems to be impossible with Android, and Apple messed-up the threading model on iOS and it is hard to say if it will be possible.
So you can implement some new functions in the `Printing` class for your Desktop version.

By the way, AHHHHHHHHH 😱!!!!

**Comment by joeblew99** [comment]
no worries :)

I ended up using the Native PDF Viewer for now on desktop. Life is too short !

What about this as a quick and dirty one for now...
Convert the PDF to a Bitmap and display it in a Flutter View. If the Bitmap is 2 to 3 times larger than the screen size it will still be sort of OK for previewing and then printing.

**Comment by DavBfr** [comment]
Implemented in Printing version 2.1.7

**Comment by KevinBeckers** [comment]
Is there a way to hide the `Printing to "my-printer.local."` and `Contacting printer...` popups on iOS?

**Comment by DavBfr** [comment]
I don't think it's possible. This is part of iOS, not the plugin.
