### ISSUE TITLE
Flutter problem to create a PDF

### ISSUE THREAD

**Issue by gasparotto93** [DavBfr/dart_pdf#370]
I´m trying to create a pdf, but i´m experiencing a issue on my code, but I´can´t find where, i´m new on that. 

 class Pdf {
  final doc = pw.Document();

  void GerarPdf(DocumentSnapshot snapshot){

  doc.addPage(
    pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(20.0),
        build: (pw.Context context){
          return <pw.Widget>[
            pw.Header(
              child: pw.Text("TEXT\n\n"
                  "TEXT\n\n"
                  "TEXT\n\n", textAlign: pw.TextAlign.center,
                style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text("TEXT "+ (snapshot["TEXT"])),
                pw.Text("TEXT: " +(snapshot["TEXT"])),
                pw.Text("TEXT "+ (snapshot["TEXT"])),
                pw.Text("TEXT "+ (snapshot["TEXT"])),
                pw.Text("TEXT "+ (snapshot["TEXT"])),
                pw.Text("TEXT "+ (snapshot["TEXT"]) ),
                pw.Text("TEXT "+(snapshot["TEXT "])+ (snapshot["TEXT"])),
                pw.Text("TEXT " + (snapshot["TEXT"])),
                pw.Text("TEXT "+ (snapshot["TEXT"])),
              ],
            ),
          ];
        },
    )
  );
  }
  Future savePdf()async{
  Directory documentDirectory = await getApplicationDocumentsDirectory();
  String documentPath = documentDirectory.path;
  
    File file = File('$documentPath/newpdf');
file.writeAsBytesSync(doc.save());
  }

}

Error: Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.9.0/lib/widgets/decoration.dart:437:5: Error: Method not found: 'fillCircle'.
    im.fillCircle(
    ^^^^^^^^^^

**Comment by DavBfr** [comment]
You need to update your dependencies.
Try `flutter outdated`

**Comment by villiel27th** [comment]
hey bro i have the same issue as you and i tried to downgrade my pdf dependencies in pubspec.yaml from pdf: ^1.9.0 to pdf: 1.5.0 and try to re run the flutter pub get. It works for me, you should try it

**Comment by gasparotto93** [comment]
try flutter upgrade. Its worked for me.
