### ISSUE TITLE
Build Failed due to pdf package.

### ISSUE THREAD

**Issue by ritvij-saxena** [DavBfr/dart_pdf#373]
I am using your package in my application to generate a pdf file. However, recently I started facing this error.

..../pdf-1.9.0/lib/widgets/decoration.dart:437:5: Error: **Method not found**: 'fillCircle'.
    im.fillCircle(
    ^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed, due to which the entire application build is failing.
Please help.

**Comment by DavBfr** [comment]
You have to update the image package dependency to the latest version.

**Comment by ritvij-saxena** [comment]
I have. **pdf-1.9.0**/lib/widgets/decoration.dart:437:5: Error: **Method not found: 'fillCircle'.**

**Comment by DavBfr** [comment]
Try to set this dependency in your pubspec.yaml:

image: ^2.1.10

**Comment by ritvij-saxena** [comment]
Response =>

Because every version of flutter_test from sdk depends on image 2.1.4 and testproject depends on image ^2.1.10, flutter_test from sdk is forbidden.

So, because testproject depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because testproject depends on flutter_test any from sdk, version solving failed.)

**Comment by DavBfr** [comment]
Maybe you have to update your flutter_test project too

**Comment by ritvij-saxena** [comment]
Any tips to upgrade the flutter_test. I updated flutter using flutter upgrade and then used the command flutter pub upgrade.

**Comment by DavBfr** [comment]
Remove flutter_test from your project.

**Comment by ritvij-saxena** [comment]
I commented out the flutter_test from pubspec.yaml, it was showing errors widget_test.dart and other widget test files.
