### ISSUE TITLE
Add support for PagedJS

### ISSUE THREAD

**Issue by rlbartz** [DavBfr/dart_pdf#375]
I'm trying to print html to pdf with page numbers using pagedJS (https://www.pagedjs.org/documentation/04-how-pagedjs-works/). The following code works on Firefox, Chrome and Edge, but when using with printing library, it doesn't work, maybe because this function is not supported yet. Would be great to add it to this library.

<html>
<head>
<script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
<style>

@page {
  size: 210mm 297mm;
  margin-top: 0mm;
  margin-right: 0mm;
  margin-bottom: 10mm;
  margin-left: 0mm;

  @bottom-center{
    content: 'Page' counter(page) ' of ' counter(pages);
  }
}
</style>
<body>
    ...Several html tags here to fill many A4 pages...
</body>
</html>

**Comment by DavBfr** [comment]
On what operating system?

**Comment by rlbartz** [comment]
Android and iOS

**Comment by savs90** [comment]
I`m also looking for someway to add page numbers to a html and convert it to pdf. Right now i`m using something similar to @rlbartz `s example but the end result is the same number for all pages and the numbers are overlapping the content

**Comment by DavBfr** [comment]
Out of scope.
