### ISSUE TITLE
Font Awesome icons is not rendering as expected. It only render sometime. 

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#377]
When trying to generate the PDF using HTML content FontAwesome icon is not rendering as expected. It only renders _sometime like 2/10 times_. Can you please help me with this issue?

It might sounds wired, When we use Image tag the FA-Icons renders as expected but without the Image tag it won't render as expected in Android platform.

_Sample Example:_
 
**Font Awesome Icons without Image NOT renders properly in Android OS**

    await Printing.layoutPdf(
    onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
          format: format,
          html: '<!DOCTYPE html> <html> <head> <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> </head> <body> <h2>Font Awesome Icons without Image NOT renders properly in Android OS</h2>  <i class="fa fa-car"></i> <i class="fa fa-car" style="font-size:48px;"></i> <i class="fa fa-car" style="font-size:60px;color:red;"></i> </body> </html>',
        ));

**Font Awesome Icons with Image renders in Android OS** 

    await Printing.layoutPdf(
    onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
          format: format,
          html: '<!DOCTYPE html> <html> <head> <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> </head> <body> <h2>Font Awesome Icons with Image renders in Android OS</h2> <img src="https://www.w3schools.com/images/w3schools_green.jpg" alt="W3Schools.com" style="width:104px;height:142px;"> <i class="fa fa-car"></i> <i class="fa fa-car" style="font-size:48px;"></i> <i class="fa fa-car" style="font-size:60px;color:red;"></i> </body> </html>',
        ));

**Comment by DavBfr** [comment]
On what operating system?

**Comment by jazzbpn** [comment]
Not render properly in Android OS. Work fine on iOS.

**Comment by jazzbpn** [comment]
https://stackoverflow.com/questions/63071723/font-awesome-icons-are-not-rendering-when-trying-to-convert-html-to-pdf-in-flutt

**Comment by jazzbpn** [comment]
@DavBfr Thank you so much for this awesome plugin.  I just want to know, Is this the plugin issue? It works on other third-party plugins. Thanks!

**Comment by DavBfr** [comment]
I'll have to look. Can you give me a plugin that works? This way I can apply the same fix.
