### ISSUE TITLE
Feature Request: Configurable Theme

### ISSUE THREAD

**Issue by sma** [DavBfr/dart_pdf#38]
I noticed that a `Paragraph` (and other Widgets) have hardcoded text styles. Please make them configurable. Adding a `style` parameter (and also `textAlign` and `margin` would be helpful. In addition, a way to define my own defaults would be great.

Because the current `Theme` cannot be changed, this is my workaround I came up with. I'm sharing it in case somebody wants to do the same:

```dart
class MyTheme extends Theme {
  MyTheme(PdfDocument document) : super(document);

  TextStyle get paragraphStyle => TextStyle(
        font: PdfFont.courier(document),
        fontSize: 12,
        lineSpacing: 5,
      );
}

class DefaultTheme extends StatelessWidget {
  final Theme theme;
  final Widget child;

  DefaultTheme({this.theme, this.child});

  @override
  Widget build(Context context) {
    context.inherited[Theme] = theme;
    return child;
  }
}
```

Using `context.inherited` feels be a bit hacky, but I couldn't use `return child.build(context.inheritFrom(theme)`because `Widget` has no `build` method and because this would use `MyTheme` as key, not `Theme`, which would be required to use this.

BTW, if `Parapgraph` has its own default in `Theme`, `Header` also should have a some kind of `headerStyle` instead of using `defaultTextStyle`. 

PS: I really like the idea to use Flutter-compatible widgets for creating pages.

**Comment by DavBfr** [comment]
Context is immutable, so you're not supposed to be able to do that.
In the Document object, you can pass a custom theme.

**Comment by sma** [comment]
While you indeed can pass a `Theme` object, it cannot be changed so you still need to create your own subclass, and you cannot really create a theme instance to pass without the PDF document that is created by the `Document` class internally. I think, the API could be more straight forward.

Futhermore, passing a subclass of `Theme` does not work as the `context`'s `inherited` map then contains a key `MyTheme` instead of `Theme`, the my theme isn't found by `Theme.of`.

**Comment by DavBfr** [comment]
I've pushed an improved version of the theming system on GitHub. Let me know if it suits your needs better.
