### ISSUE TITLE
Unable to add a Shadow to Container 

### ISSUE THREAD

**Issue by ab-dev-github** [DavBfr/dart_pdf#382]
I am unable to use Shadow to the Container, am I doing something wrong or this is something not available in this package? Trying to create something like in attached screenshot, can someone help please?

- AB
![Screenshot 2020-07-24 at 9 50 17 AM](https://user-images.githubusercontent.com/22760709/88360440-51886000-cd93-11ea-9fe8-134c58d438aa.png)

**Comment by DavBfr** [comment]
There is no support for shadows in the PDF files. All applications that create shadows generate a bitmap image to create the illusion.

**Comment by ab-dev-github** [comment]
Spent sometime on this and it works perfectly well. Try below code incase anyone is looking to achieve this using. @DavBfr Thanks for creating a great package for Flutter. 

```
 decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: 10,
        boxShadow: [
          pw.BoxShadow(
            color: PdfColors.grey,
            blurRadius: 10,
            spreadRadius: 20,
          ),
        ],
```

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
