### ISSUE TITLE
Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

### ISSUE THREAD

**Issue by galloperx** [DavBfr/dart_pdf#384]
**Describe the bug**
Hello, I saw other reports on this issue and I understand that it has a workaround, however, I'd like to know why is it happening in the first place? Is it a bug? I think so.
I'm using Flutter with Android Studio as editor, I didn't try to use any specific fonts or anything like that, just wanted to try it out and create a simple PDF with just one line of text.

In pubspec.yaml I have specified the 1.10.0 version of the lib.
I tried the simplest code (the Hello World example from https://pub.dev/packages/pdf) to create a pdf file with it and got the
"Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management"
console msg instead. Actually, this happens on calling pdf.save(). Why is it happening? I mean out of the box basic functionality - just following the examples on that page, is there something wrong?

**Comment by DavBfr** [comment]
This is not a bug, it's a warning for you as a developer, to tell you that if you ever try to write Chinese or eastern European language, for example, the default PDF fonts can't do it and you'll have to load a proper font for that.
If your app targets only the US, that's fine, but if any of your users has something like Ł or ñ it will fail.

**Comment by galloperx** [comment]
I see, but why does it show this warning on a text that has no such symbols, is it supposed to do so anyway?

**Comment by DavBfr** [comment]
Yes, because during your tests you may use only English text, but your Spanish users might not be able to enter their names.

**Comment by emanuelmarlon** [comment]
How to solve this problem I have it too
