### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by emerysilb** [DavBfr/dart_pdf#385]
Whenever trying to render a PDF that has an emoji in text, the PDF doesn't render. 

It would be great to add emoji support!

**Comment by DavBfr** [comment]
It would, yes. But that means writing code to read and draw the emoji fonts in pure dart, which is out of scope.

**Comment by emerysilb** [comment]
That makes sense. I was considering trying a font that includes emojis, but I haven't tried it yet. 

Thanks for considering.

**Comment by jeanadam** [comment]
Just to add some info of my take on this, OpenMoji has a TTF with **glyphs** for simple black and white emojis compatible with basic emojis. It works with current pdf package. As some modern fonts may use CBDT/CBLC which is not support by current package, in order to fully support a wide range of coloured emojis, I am on my way to develop a dirty method that will load png of emojis in use and swap emoji unicodes (base on dart default UTF16, String.codeUnits, List<int>) with png/svg equivalents. Png unicode emoji library are easily accessible from open source emoji libraries.

**Comment by DavBfr** [comment]
CBDT/CBLC should be easy to implement. It's just embedded PNG images in the font. But is it enough to support emojis? Aren't they stored in a vector format?

**Comment by jeanadam** [comment]
The font that I was looking forward to implement with CBDT/CBLC was Noto Emoji Color ([Google Font](https://www.google.com/get/noto/help/emoji/)). But yes, just supporting emojis is not enough as fonts need to be changed to emoji font when writing emojis (although maybe combining/generating my own emoji font + normal font would do). It is my first time trying to understand how ttf works, so it will take time and I feel it will be easier to use png/svg libraries and just substitute emoji chars, this could also make it easier to swap emoji libraries.

**Comment by jeanadam** [comment]
Just want to update that my workaround worked. It gets a bit slow with a lot of emojis (I will probably refactor and improve code later), but it is fine for now.

So what I did was create a function that generate a RichText with an array of TextSpan for text parts and WidgetSpan for emoji parts (loading png). So I use regEx to split text where emojis starts/ends then Characters library to identify individual/emoji characters, which are mapped to unicode `_unicodeCode = character.toString().runes.map((e) => e.toRadixString(16)).join('-')` this is the hex unicode name in png/svg files, so I load then if they are not loaded and add to WidgetSpan. Doing like this makes images part of the text so no worries with line breaks, etc.

**Comment by emerysilb** [comment]
By asking this question I've realized how little I know about the ins and outs of fonts, but it makes a lot of sense to find and replace the emojis with pngs so that way the style of emoji can be picked out for printing. 

I think for now, I'll implement a regex removal function so the pdf still renders correctly.  

It'd be great to hear what improvements you make to the find/replace function!

**Comment by deepak786** [comment]
any update on this?

**Comment by DavBfr** [comment]
It's now implemented.
