### ISSUE TITLE
Image to occupy maximum available size

### ISSUE THREAD

**Issue by anirudh-t4** [DavBfr/dart_pdf#387]
I am trying to insert images to pages in the pdf. How can i get my image to occupy the maximum size available.
Code:'

            pdf.addPage(pw.MultiPage(
                    pageFormat: PdfPageFormat.a5,
             build: (pw.Context context) {
                return <pw.Widget>[

            pw.SizedBox(height: 400,
              child: pw.Center(
                  child: pw.Image(image)
              ),
            ),

            pw.SizedBox(height: 20),
            pw.Footer(
                trailing: pw.Text("Scanned by Scan Karo",)
            ),
          ];
        },
      ));

**Comment by DavBfr** [comment]
Use the page format to get the available dimensions with the margins, and set the SizedBox dimensions to this.
The Image() widget get a fit you can use to change the way the image scale.

**Comment by anirudh-t4** [comment]
> Use the page format to get the available dimensions with the margins, and set the SizedBox dimensions to this.
> The Image() widget get a fit you can use to change the way the image scale.

**Comment by anirudh-t4** [comment]
can you give an example of the page format. I mean it gives the options like a4,a5,a3 etc.how do I get the dimensions?

**Comment by DavBfr** [comment]
context.page.pageFormat.availableWidth and context.page.pageFormat.availableHeight

**Comment by anirudh-t4** [comment]
i used this as follows:

pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a5,
        build: (pw.Context context) {

          var ht = context.page.pageFormat.availableHeight;
          var wt = context.page.pageFormat.availableWidth;
          return <pw.Widget>[

            pw.SizedBox(
              height: ht,
              width: wt,
              child: pw.Center(child: pw.Image(image,fit: pw.BoxFit.fill)),
            ),
            pw.SizedBox(height: 20),
            pw.Footer(
                trailing: pw.Text(
              "Scanned by Scan Ease",
            )),
          ];
        },
      ));

but it still shows the error:


[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'pageFormat' was called on null.
E/flutter ( 7746): Receiver: null
E/flutter ( 7746): Tried calling: pageFormat
E/flutter ( 7746): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 7746): #1      _PdfCreate.writeOnPdf.<anonymous closure> (package:internship/Screens/pdf.dart:35:33)
E/flutter ( 7746): #2      MultiPage.generate (package:pdf/widgets/multi_page.dart:172:45)
E/flutter ( 7746): #3      Document.addPage (package:pdf/widgets/document.dart:65:10)
E/flutter ( 7746): #4      _PdfCreate.writeOnPdf (package:internship/Screens/pdf.dart:31:11)
E/flutter ( 7746): #5      _PdfCreate.build.<anonymous closure> (package:internship/Screens/pdf.dart:85:13)
E/flutter ( 7746): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter ( 7746): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 7746): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7746): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter ( 7746): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 7746): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 7746): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 7746): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 7746): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 7746): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 7746): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 7746): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 7746): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 7746): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 7746): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7746): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7746): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7746): #23     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 7746): #24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7746): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 7746): #26     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 7746): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

**Comment by anirudh-t4** [comment]
what is it that i am doing wrongly

**Comment by DavBfr** [comment]
You can use:
```dart
var ht = PdfPageFormat.a5.availableHeight;
var wt = PdfPageFormat.a5.availableWidth;
```

**Comment by anirudh-t4** [comment]
Thanks a lot mate

**Comment by mwerder** [comment]
Hey @DavBfr I am doing it like this and the image still have margins on every side.

````
pdf.addPage(pw.Page(
        pageFormat: PdfPageFormat.a4.applyMargin(left:0, top:0, right:0, bottom:0),
        build: (pw.Context context) {

        var ht = context.page.pageFormat.availableHeight;
        var wt = context.page.pageFormat.availableWidth;
        
        return pw.SizedBox(
          height: ht,
          width: wt,
          child: pw.Center(child: pw.Image.provider(image,fit: pw.BoxFit.contain)),
        );
        },
      ));
````

**Comment by DavBfr** [comment]
`PdfPageFormat.a4.applyMargin()`  will not set the margins, but increase them if needed. Use `PdfPageFormat.a4.copyWith()` instead.

**Comment by mwerder** [comment]
@DavBfr Thank you so much
