### ISSUE TITLE
Can i do a header like this?

### ISSUE THREAD

**Issue by joaovmeneses** [DavBfr/dart_pdf#389]
Hey folks, anybody can help me to make a header like this? Thanks!

![header_pdf](https://user-images.githubusercontent.com/58236175/89785814-5702db80-daf1-11ea-82e7-6772a33c5f1c.png)

**Comment by DavBfr** [comment]
Yes, no problem. Use a series of Column() and Row() with decorations to draw the lines.

**Comment by joaovmeneses** [comment]
Thanks bro, it worked !!

**Comment by joaovmeneses** [comment]
Just one more thing, can i set this header in every page, using MultiPage?

**Comment by DavBfr** [comment]
Yes, use the header builder.
