### ISSUE TITLE
Instantaneous printing in web 

### ISSUE THREAD

**Issue by JTPenn-EG** [DavBfr/dart_pdf#393]
**Is your feature request related to a problem? Please describe.**
I am developing a Flutter web app that has a lot of document creation and printing, each time the user has to print a document he gets asked for which printer and printing options he would like (Printing dialog).

**Describe the solution you'd like**
The document to be printed instantaneous(I believe it's called silent print) without requesting the user (Printer name and printing options are known in advance and passed as arguments to the print method).

**Describe alternatives you've considered**
I couldn't find any alternatives using Flutter, but I think I can upload this PDF document to a server and have a windows script running all the time and once it sees the documents fetches it and prints it silently outside of web. (but that would mean that I require the users to install that script separately and I don't think it's a good idea) 

**Additional context**
None

**Comment by DavBfr** [comment]
Sorry, that's not possible to print without user interaction. That would be really annoying if a malicious website could print some random ads on your printer while browsing.

**Comment by anandsubbu007** [comment]
will this possible for windows app?
without any interaction printing documents
