### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by shah-xad** [DavBfr/dart_pdf#395]
**Describe the bug**

Whenever I try to use the custom font for flutter web, It works fine in debug mode but after deploying my application to the Firebase hosting I get the following error:

```
js_helper.dart:1129 Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at dk.dH (native_typed_data.dart:509)
    at dk.rF (native_typed_data.dart:508)
    at aaP.Vr (ttf_parser.dart:47)
    at Object.apV (ttf_parser.dart:42)
    at aaO.LV (ttffont.dart:24)
    at aaO.x_ (font.dart:133)
    at a7n.$2 (text.dart:581)
    at O2.aez (text.dart:429)
    at NR.dg (text.dart:575)
```

**To Reproduce**
Code snippet to reproduce the behavior:
```dart

        final doc = Document(
            theme: Theme.withFont(
          base: Font.ttf(
              await rootBundle.load("fonts/open_sans/OpenSans-Regular.ttf")),
          bold: Font.ttf(
              await rootBundle.load("fonts/open_sans/OpenSans-Bold.ttf")),
          italic: Font.ttf(
              await rootBundle.load("fonts/open_sans/OpenSans-Italic.ttf")),
          boldItalic: Font.ttf(
              await rootBundle.load("fonts/open_sans/OpenSans-BoldItalic.ttf")),
        ));

```

**Comment by DavBfr** [comment]
Are your fonts declared in the assets section of your pubspec?

```yaml
flutter:
  assets:
    - fonts/open_sans/
```

**Comment by shah-xad** [comment]
> Are your fonts declared in the assets section of your pubspec?
> 
> ```yaml
> flutter:
>   assets:
>     - fonts/open_sans/
> ```

Yes those are declared there, and working fine for debug mode.

**Comment by Heinrich-vanNieuwenhuizen** [comment]
Hi I'm having the same issue any solutions?

**Comment by salvadorbarb1** [comment]
Having same issue here too..

**Comment by DavBfr** [comment]
Which font are you loading?

**Comment by salvadorbarb1** [comment]
Nunito.Regular
https://fonts.google.com/specimen/Nunito

**Comment by DavBfr** [comment]
@salvadorbarb1 can you give me the link to the file you use?

**Comment by salvadorbarb1** [comment]
https://fonts.google.com/specimen/Nunito?sidebar.open=true&selection.family=Nunito

**Comment by DavBfr** [comment]
That's still not a link to a .ttf file.

**Comment by salvadorbarb1** [comment]
[https://drive.google.com/file/d/1GPE_mCIFDeTlABaQripU7wXgyMbs7P-K/view?usp=sharing](url)

??

**Comment by DavBfr** [comment]
I don't have any issue with this file.

**Comment by salvadorbarb1** [comment]
How are you loading it into the PDF?, 
I'm using this...
`
final font1 = await rootBundle.load('fonts/Nunito-Regular.ttf');
 pw.Page(
        pageTheme: _buildTheme(
          pageFormat,
          font1 != null ? pw.Font.ttf(font1) : null,
), build: (context) {
          return pw.Column(
        mainAxisSize: pw.MainAxisSize.min,
        mainAxisAlignment: pw.MainAxisAlignment.start,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: <pw.Widget>[
          _idRow(order),
          pw.Padding(
            padding: const pw.EdgeInsets.all(8.0),
            child: pw.Text(
              'Data',
            ),
          ),
        });
`

**Comment by DavBfr** [comment]
```dart
Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    final pdf = pw.Document();
    final font = pw.Font.ttf(await rootBundle.load('fonts/Nunito-Regular.ttf'));

    pdf.addPage(
      pw.Page(
        pageTheme: pw.PageTheme(theme: pw.ThemeData.withFont(base: font)),
        build: (context) =>
            pw.Text('Hello ${font.fontName}', textScaleFactor: 4),
      ),
    );

    return pdf.save();
  }
```

**Comment by Ainiuso** [comment]
Have same error: works on debug builds, but fails if build with `flutter build web` and deployed to firebase hosting.
Using Roboto Regular: https://fonts.google.com/specimen/Roboto?sidebar.open=true&selection.family=Roboto

**Comment by Ainiuso** [comment]
In my case, I resolved it by specifying full asset path: `rootBundle.load("assets/fonts/roboto/Roboto-Regular.ttf")` instead of `rootBundle.load("fonts/roboto/Roboto-Regular.ttf")`.

**Comment by FreddyStraub** [comment]
Hi, I have the same problem but if I put in the full path like @Ainiuso said I get the following error: 
`Error while trying to load an asset: Failed to load asset at "assets/assets/fonts/OpenSans-Regular.ttf" (404)
`

Does somebody has a soloution?

**Comment by luizjunior05** [comment]
> Hi, I have the same problem but if I put in the full path like @Ainiuso said I get the following error: `Error while trying to load an asset: Failed to load asset at "assets/assets/fonts/OpenSans-Regular.ttf" (404) `
> 
> Does somebody has a soloution?

I solved it that way:
`Font.ttf(await rootBundle.load(kReleaseMode ? "assets/fonts/OpenSans-Regular.ttf" : "fonts/OpenSans-Regular.ttf")),`
