### ISSUE TITLE
Change Orientation

### ISSUE THREAD

**Issue by Ahmedmedhat187** [DavBfr/dart_pdf#396]
Dears,

I want to add action to change orientaion:

    return PdfPreview(
      allowSharing: true,
      canChangePageOrientation: true,
      build: generateReport,
    );

  final bool canChangePageOrientation;

    if (widget.canChangePageOrientation) {
      actions.add(
        IconButton(
          icon: Icon(Icons.screen_rotation, color: theme.accentIconTheme.color,),
          onPressed: (){
                   
          }),
      );
    }

**Comment by DavBfr** [comment]
Just change your pdf generation and set the orientation attribute of each Page/MultiPage object.

**Comment by Ahmedmedhat187** [comment]
Thanks DavBfr for helping :)


but The build function signature is

Future<Uint8List> generateReport(PdfPageFormat)

it is not accepting other attributes
how to add orientation attribute to this function

**Comment by DavBfr** [comment]
Use a variable outside the function.
