### ISSUE TITLE
Text unable to overflow in pdf 1.11.0 plugin

### ISSUE THREAD

**Issue by budescode** [DavBfr/dart_pdf#397]
Hi, I'm having issues overflowing a text when creating pdf, It's supposed to go to the next line when the width has reach, but it overlaps to the next widget.
I'm using pw.Row widget then pw.Expanded with flex of 3 and pw.Expanded with flex of 7.
When I put long text without space in the first expanded, it overlaps and enter the next expanded instead of going to the next line.
Below is my code

Future<Uint8List> generateDocument() async {
  // writeOnPdf(){
  final pw.Document doc = pw.Document();
  final PdfImage profileImage = PdfImage.file(
    doc.document,
    bytes: (await rootBundle.load('images/profile.png')).buffer.asUint8List(),
  );
  pdf.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      build: (pw.Context context) => <pw.Widget>[
            pw.Header(
                level: 0,
                child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: <pw.Widget>[
                      pw.Text('Victor O Samuel', textScaleFactor: 2),
                      pw.PdfLogo()
                    ])),

            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.start,
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: <pw.Widget>[        
  
                        pw.Expanded(
                          flex: 3,
                          child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          mainAxisAlignment: pw.MainAxisAlignment.start,
                          children: <pw.Widget>[
                          pw.Wrap(children: <pw.Widget>[
                            pw.Text('ospeltrythhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh'
                            ),
                          ]),                         
                         
                          pw.Text('20, Izekor street off 2nd powerlineeet off 2nd powerline, Isiohor quarteet off 2nd powerline, Isiohor quarteet off 2nd powerline, Isiohor quart, Isiohor quarters, Benin city, Edo State, Nigeria', style: pw.TextStyle(
                            fontSize: 13,
                            
                          )),
                          
                        ])),
                        pw.SizedBox(width: 10),
                        pw.Expanded(
                          flex: 7,
                          child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          mainAxisAlignment: pw.MainAxisAlignment.start,
                          children: <pw.Widget>[
                          pw.Text('Victor .O. Samuel', style: pw.TextStyle(
                            fontSize: 17,
                            fontWeight: pw.FontWeight.bold,
                          )),
                          pw.Text('gospeltruth18@gmail.com', style: pw.TextStyle(
                            fontSize: 13,                            
                          )),
                          pw.Text('09032841265', style: pw.TextStyle(
                            fontSize: 13,                            
                          )),
                          pw.Text('20, Izekor street off 2nd powerline, Isiohor quarters, Benin city, Edo State, Nigeria', style: pw.TextStyle(
                            fontSize: 13,
                            
                          )),
                         
                        ])),
                      
                    ]
            ),  

             ]));

 
}
**Expected behavior**
When I put long text without space in the first expanded, it overlaps and enter the next expanded instead of going to the next line.

**Screenshots**
![WhatsApp Image 2020-08-20 at 4 09 54 PM](https://user-images.githubusercontent.com/32739408/90798488-e5edd000-e309-11ea-9604-f29e2b388d8d.jpeg)

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Android Studio (version 3.5)
[√] VS Code (version 1.48.0)
[√] VS Code, 32-bit edition (version 1.41.0)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```
```

**Smartphone (please complete the following information):**
 - Infinix X626 android version 9

**Additional context**

**Comment by DavBfr** [comment]
Yes, Text without space will not split to a new line.

**Comment by budescode** [comment]
> Yes, Text without space will not split to a new line.

But I'm getting the data to display from user input.
Please what do you suggest

**Comment by DavBfr** [comment]
You can use a clip widget to prevent the text to overlap with the next elements.

**Comment by budescode** [comment]
> You can use a clip widget to prevent the text to overlap with the next elements.

Please will it go to the next line?

**Comment by DavBfr** [comment]
no, it will clip.

**Comment by budescode** [comment]
> no, it will clip.

I noticed it.
So there's no way to go to the next line without adding space?

**Comment by DavBfr** [comment]
no, except if you want to implement that in the library.
