### ISSUE TITLE
adding multiple images by loop

### ISSUE THREAD

**Issue by divid0n1** [DavBfr/dart_pdf#399]
Hi Sir - I have been working on this point how can I add images from the list, I did hard work but not getting success. Only I get below is working fine but the problem is It add new page every time which shouldn't be. Please give me a way to add multiple image from list without adding new page. Thank you.

```dart
writeOnPdf() async {
    for (var i = 0; i < exdata.length; i++) {
    var imag = PdfImage.file(
      pdf.document,
      bytes: File(exdata[i].path).readAsBytesSync(),
    );

    var myTheme = pw.Theme.withFont(
      base: pw.Font.ttf(await rootBundle.load("assets/arimo.ttf")),
    );

    pdf.addPage(pw.MultiPage(
      theme: myTheme,
      pageFormat: PdfPageFormat.a5,
      margin: pw.EdgeInsets.all(32),
      build: (pw.Context context) {
        return <pw.Widget>[
          pw.Header(level: 0, child: pw.Text("new pdf Title")),
          pw.Image(imag),
        ];
      },
    ));
    }}
```

**Comment by ankitpanwar8979** [comment]
Use while loop instead of for loop.

**Comment by divid0n1** [comment]
Thank you Ankitpanwar - I am little bit new, can you please give me a sample. I would be thank ful to you.

**Comment by ankitpanwar8979** [comment]
final List<PdfImage> attachmentList = List();
    int i=0;
    while(i<invoiceData.attachment.length){
      attachmentList.add(PdfImage.file(pdf.document, bytes: invoiceData.attachment[i].attachment.readAsBytesSync()));
      i++;
    }

**Comment by divid0n1** [comment]
Sir its also adding new page, I tried below code.

int i=0;
         while(i < exteriorImgNotifier.exteriorImgList.length){
        var imag = PdfImage.file(
          pdf.document,
          bytes: File(exteriorImgNotifier.exteriorImgList[i].imagesfloor.path).readAsBytesSync(),
        );
        i++;
        var myTheme = pw.Theme.withFont(
          base: pw.Font.ttf(await rootBundle.load("assets/arimo.ttf")),
        );

        pdf.addPage(pw.MultiPage(
          theme: myTheme,
          pageFormat: PdfPageFormat.a5,
          margin: pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return <pw.Widget>[
              pw.Header(level: 0, child: pw.Text("new pdf Title")),
              pw.Container(height: 200,width: 200,
                child: pw.Image(imag),),
            ];
          },
        ));
      }

**Comment by DavBfr** [comment]
Each time you call `pdf.addPage(...)` it adds a new page. That's why the method is called "add page".

**Comment by divid0n1** [comment]
Yes sir - But tried couple of method to not call pdf.addPage but I couldn't get success. Please can you help me here so I can add multiple image without adding page

**Comment by DavBfr** [comment]
You should try using Wrap and a list generator. Something like:

```dart
  pdf.addPage(pw.MultiPage(
      build: (pw.Context context) => [
            Wrap(
              children: List<Widget>.generate(
                exteriorImgNotifier.exteriorImgList.length,
                (int n) {
                  var imag = PdfImage.file(
                    pdf.document,
                    bytes: File(exteriorImgNotifier
                            .exteriorImgList[i].imagesfloor.path)
                        .readAsBytesSync(),
                  );

                  return pw.Container(
                      height: 200, width: 200, child: pw.Image(imag));
                },
              ),
            ),
          ]));
```

**Comment by divid0n1** [comment]
I was thinking about this solution from your given example but you saved my alot of time.
Thank you soo much Sir. I will try it letter I know it will work definitely.

**Comment by prabha024** [comment]
@divid0n1 did you solve? i am facing similar issue. help me if you solved.

**Comment by 1Fenix** [comment]
Thank you @DavBfr.
I will try it.
Will keep get back to you with the result.

**Comment by divid0n1** [comment]
Yes @prabha024  its solved by DavBfr

```
pdf.addPage(pw.MultiPage(
      build: (pw.Context context) => [
            Wrap(
              children: List<Widget>.generate(
                exteriorImgNotifier.exteriorImgList.length,
                (int i) {
                  var imag = PdfImage.file(
                    pdf.document,
                    bytes: File(exteriorImgNotifier
                            .exteriorImgList[i].imagesfloor.path)
                        .readAsBytesSync(),
                  );

                  return pw.Container(
                      height: 200, width: 200, child: pw.Image(imag));
                },
              ),
            ),
          ]));
```

**Comment by prabha024** [comment]
@divid0n1 i faced similar problem and get solution by below code. thank you @divid0n1 and @DavBfr .

            
 ` doc.addPage(pw.MultiPage(
      build: (pw.Context context) => [
              pw.Wrap(children: 
                  List.generate(
                pdfImages.length,
                (int n) {
                  return pw.Container(
                      height: 200, width: double.infinity, child: pw.Column(children: [
                        pw.Container(height: 200,width: 200,child: pw.Image(pdfImages[n])), 
                      ]));
                },
              ),
              ),   
          ]));`
