### ISSUE TITLE
No Dart 2 Support

### ISSUE THREAD

**Issue by ConProgramming** [DavBfr/dart_pdf#4]
When Trying to use it on my new AngularDart app, I get the error

```
The current Dart SDK version is 2.0.0.

Because sourcerer_web depends on pdf >=1.0.1 which requires SDK version >=1.8.0 <2.0.0, version solving failed.
```

**Comment by DavBfr** [comment]
Yes, it should be compatible with dart 2.0.0. Can you try?

**Comment by ConProgramming** [comment]
Nope, I'm getting this error now
```
The current Dart SDK version is 2.0.0.

Because pdf >=1.0.2 depends on ttf_parser any which requires SDK version <2.0.0, pdf >=1.0.2 is forbidden.
So, because sourcerer_web depends on pdf ^1.0.2, version solving failed.
```

**Comment by DavBfr** [comment]
Now your problem is about ttf_parser which needs to be updated.
You should create an Issue there: https://github.com/coderespawn/dart-ttf-parser

**Comment by DavBfr** [comment]
@ConProgramming, If they don't come back to you in few days, let me know and I'll do something!
