### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by woellij** [DavBfr/dart_pdf#40]
Hi,

first of all: thanks for that great library. It's a breeze to work with it through it's awesome widget layer.

I was wondering, whether (and how) it would be possible to add a hyperlink to a PDF.

Thanks in advance.

**Comment by DavBfr** [comment]
Thanks,
hyperlink are bearly supported through the PdfAnnot class.
You have an example in
https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/annotations.dart

**Comment by woellij** [comment]
Thanks for the quick response.

It appear that web links are not supported yet, or am i wrong?

**Comment by DavBfr** [comment]
Exact, they are not supported.

**Comment by DavBfr** [comment]
Use Anchor(name: 'your anchor name') and Link(destination: 'your anchor name') for internal links
Url are supported using UrlLink(destination: 'https://www.wikipedia.com', child:Text('Wikipedia'))
