### ISSUE TITLE
Multiple Images from different sources. 

### ISSUE THREAD

**Issue by 1Fenix** [DavBfr/dart_pdf#401]
Hi. I would like to import multiple images into my pdf. Its basically an invoice app. 
I want to add a client signature (from the cache) into the pdf but I cant seem to get it right. I suspect its because "PdfImage.file" is already used by the "var assetImage"?
Please help.

```dart
final pdf = pw.Document();
  writeOnPdf() async {
    var assetImage;
    if (insuranceValueHolder == 'AA'){assetImage = PdfImage.file(
      pdf.document,
      bytes: (await rootBundle.load('assets/aa.png')).buffer.asUint8List(),);
    } else if (insuranceValueHolder == 'BB') {assetImage = PdfImage.file(
      pdf.document,
      bytes: (await rootBundle.load('assets/bb.png')).buffer.asUint8List(),);
    }
    final signatureImage = PdfImage.file(
      pdf.document,
      bytes: (await rootBundle.load('/data/user/0/com.jobcard/cache/signature.png')).buffer.asUint8List(),);

    pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Column(........
```

**Comment by DavBfr** [comment]
This should work. Maybe your issue is somewhere else.

**Comment by 1Fenix** [comment]
Thank you for replying.
Unfortunately i can't get it to work. I tried everything i can think of. There is no errors given, but the final pdf does not open at all. 
I double checked the paths to the images and they all work. I just can't get them to work together.

**Comment by DavBfr** [comment]
can you get a simplified version of your code that reproduces the issue and past it here?

**Comment by 1Fenix** [comment]
Ok.
This is the simplified code.

`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'PdfPreviewScreen.dart';
import 'SignaturePage.dart';
import 'package:intl/intl.dart';
import 'package:flutter_email_sender/flutter_email_sender.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(
                backgroundColor: Colors.red,
                title: Text('Biker Boys Job Card')),
            body: Center(child: HomeScreen())));
  }
}

class HomeScreen extends StatefulWidget {
  HomeScreenState createState() => HomeScreenState();
}

class HomeScreenState extends State<HomeScreen> {
  String dateHolder(DateTime date) {
    final format = DateFormat('dd-MM-yyyy');
    return format.format(date);
  }
  final jobNo = TextEditingController();
  var insuranceValue;

  getItemAndNavigate(BuildContext context) {
    Navigator.push(
        context,
        MaterialPageRoute(
            builder: (context) => SecondScreen(
              dateHolder: dateHolder(DateTime.now()),
                jobNoHolder: jobNo.text,
                insuranceValueHolder: insuranceValue,)));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
          child: ListView(
            children: <Widget>[
              Container(
                  width: 280,
                  padding: EdgeInsets.all(10.0),
                  child: TextField(
                    style: TextStyle(fontSize: 26.0, color: Colors.black),
                    controller: jobNo,
                    autocorrect: true,
                    decoration: InputDecoration(hintText: 'Job No.'),
                  )),
              Container(
                  width: 280,
                  padding: EdgeInsets.fromLTRB(10.0, 20.0, 10.0, 0),
                  child: DropdownButton<String>(
                    value: insuranceValue,
                    hint: Text('Insurance'),
                    style: TextStyle(
                        fontSize: 26.0,
                        color: Colors.black
                    ),
                    onChanged: (String newValue1) {
                      setState(() {
                        insuranceValue = newValue1;
                      });
                    },
                    items: <String>['AA', 'Discovery', 'Global', 'Outsurance', 'Santam', 'COD']
                        .map<DropdownMenuItem<String>>((String value1) {
                      return DropdownMenuItem<String>(
                        value: value1,
                        child: Text(value1),
                      );
                    })
                        .toList(),
                  )),

              RaisedButton(
                onPressed: () => getItemAndNavigate(context),
                color: Colors.red,
                textColor: Colors.white,
                padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
                child: Text('Preview'),
              ),

            ],
          ),
        ));
  }
}

class SecondScreen extends StatelessWidget {
  final dateHolder;
  final jobNoHolder;
  final insuranceValueHolder;

  SecondScreen(
      {Key key,
        this.dateHolder,
        this.jobNoHolder,
        this.insuranceValueHolder,
      })
      : super(key: key);

  goBack(BuildContext context) {
    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.red,
          title: Center(child: Text('Preview')),
        ),
        body: Center(
          child: ListView(children: <Widget>[
            Center(
                child: Text(
                  'Date: ' + dateHolder,
                  style: TextStyle(fontSize: 22),
                  textAlign: TextAlign.center,
                )),
            Center(
                child: Text(
                  'Job No.: ' + jobNoHolder,
                  style: TextStyle(fontSize: 22),
                  textAlign: TextAlign.center,
                )),
            Center(
                child: Text(
                  'Insurance: ' + insuranceValueHolder,
                  style: TextStyle(fontSize: 22),
                  textAlign: TextAlign.center,
                )),

            RaisedButton(
              color: Colors.red,
              onPressed: () async {
                writeOnPdf();
                await savePdf();

                Directory documentDirectory =
                await getApplicationDocumentsDirectory();
                String documentPath = documentDirectory.path;
                String fullPath = '$documentPath/$jobNoHolder.pdf';

                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) =>
                            PdfPreviewScreen(path: fullPath)));
              },
              child: Icon(Icons.check, color: Colors.white),
            ),
            RaisedButton(
              color: Colors.red,
              onPressed: (){

                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) =>
                            SignaturePage()));
              },
              child: Icon(Icons.check, color: Colors.white),
            ),
          ]),
        )
    );
  }

  final pdf = pw.Document();
  writeOnPdf() async {
    var assetImage;
    if (insuranceValueHolder == 'AA'){assetImage = PdfImage.file(
      pdf.document,
      bytes: (await rootBundle.load('assets/aa.png')).buffer.asUint8List(),);
    } else if (insuranceValueHolder == 'BB') {assetImage = PdfImage.file(
      pdf.document,
      bytes: (await rootBundle.load('assets/bb.png')).buffer.asUint8List(),);
    }
    final signatureImage = PdfImage.file(
      pdf.document,
      bytes: (await rootBundle.load('/data/user/0/com.jobcard/cache/signature.png')).buffer.asUint8List(),);

    pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: <pw.Widget>[
                  pw.ClipRect(
                    child: pw.Container(
                      width: 550,
                      height: 250,
                      child: pw.Image(assetImage),
                    ),
                  ),
                ]),
            pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: <pw.Widget>[
                  pw.Text(
                      '________________________________________________________________________________'),
                  pw.Text(
                      '.')
                ]),
            pw.Wrap(direction: pw.Axis.vertical, children: <pw.Widget>[
              pw.Text('     Date: ' + dateHolder, textScaleFactor: 1.3),
              pw.Text('     Job No.: ' + jobNoHolder, textScaleFactor: 1.3),
              pw.Text('     Insurance: ' + insuranceValueHolder, textScaleFactor: 1.3)
            ]),
            pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: <pw.Widget>[
                  pw.ClipRect(
                    child: pw.Container(
                      width: 550,
                      height: 250,
                      child: pw.Image(signatureImage),
                    ),
                  ),
                ]),
          ];
        }));
  }
  final bool isHTML = false;

  Future savePdf() async {
    Directory tempDir = await getTemporaryDirectory();
    String tempPath = tempDir.path;
    File file = File('$tempPath/$jobNoHolder.pdf');
    file.writeAsBytesSync(pdf.save());
    print(tempDir.listSync());

      final Email email = Email(
        body: 'Please find invoice for job no. $jobNoHolder attached.',
        subject: 'Job No. $jobNoHolder Invoice',
        recipients: ['.......'],
        attachmentPaths: ['/data/user/0/com.jobcard/cache/$jobNoHolder.pdf',],
        isHTML: isHTML,
      );

      final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
      String platformResponse;

      try {
        await FlutterEmailSender.send(email);
        platformResponse = 'Email Sent';
      } catch (error) {
        platformResponse = error.toString();
      }
    tempDir.deleteSync(recursive: true);


      _scaffoldKey.currentState.showSnackBar(SnackBar(
        content: Text(platformResponse),
      ));
  }
}`

**Comment by 1Fenix** [comment]
Hi DavBfr.

Could you replicate the error?

I still can't find the solution. I really don't know what else to try.

**Comment by DavBfr** [comment]
Sorry, your code is too complicated, and requires external data. I can't test it.
