### ISSUE TITLE
Pdf created with too much margin

### ISSUE THREAD

**Issue by anirudh-t4** [DavBfr/dart_pdf#403]
I am creating multi page pdf's and facing the error that the images are occupying very little space in pdf and there is a lot of margin as shown in screenshot below
[
![WhatsApp Image 2020-08-23 at 11 44 02 AM](https://user-images.githubusercontent.com/55625660/90972566-ba502d00-e537-11ea-8e9c-07975afc6a7b.jpeg)
](url)

the code:
                  

                         pdf.addPage(pw.MultiPage(
                              mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                       pageFormat: PdfPageFormat.a5,
                           build: (pw.Context context) {
                           return <pw.Widget>[
                      pw.Column(
                               children: <pw.Widget>[
                    pw.Stack(
                        children: <pw.Widget>[
                        pw.SizedBox(
                          height: PdfPageFormat.a5.availableHeight,
                          width: PdfPageFormat.a5.availableWidth,
                          child: pw.Center(child: pw.Image(image,fit: pw.BoxFit.fitHeight)),
                        ),

                        pw.Center(
                          child: pw.SizedBox(
                            height: PdfPageFormat.a5.availableHeight,
                            width: PdfPageFormat.a5.availableWidth/1.5,
                            child: pw.Watermark(
                              child: pw.Text(text.text,style: pw.TextStyle(fontSize: 10,)),angle: 50,),
                          ),
                        )
                      ]
                  ),

                ]
            ),

          ];
        },
      ));

how can i maximize the space?

**Comment by DavBfr** [comment]
It's the default margin for the A5 page format.
You can alter it using: `PdfPageFormat.a5.applyMargin(left:0, top:0, right:0, bottom:0)`
