### ISSUE TITLE
Text inside pdf isn't breaking line

### ISSUE THREAD

**Issue by Natanlimap** [DavBfr/dart_pdf#404]
![image](https://user-images.githubusercontent.com/52389405/91217440-e1505f80-e6ed-11ea-938f-68a6731e653e.png)
![image](https://user-images.githubusercontent.com/52389405/91217504-fe852e00-e6ed-11ea-977e-d4058352068b.png)

do you know any reason why this text isn't breaking line?

**Comment by DavBfr** [comment]
Because you have no space in your text

**Comment by DavBfr** [comment]
Duplicate #397
