### ISSUE TITLE
Can't find option to disable the save as pdf option in layout previewer

### ISSUE THREAD

**Issue by ShkSalmanAhmad** [DavBfr/dart_pdf#406]
Hi,
I am trying to use this library. I generated my document successfully. One additional requirement of my program demands that a certain user cannot select the "save as pdf" option. How can I disable this save feature? Is there a way to do that? Thanks a lot.

**Comment by DavBfr** [comment]
That's Android/iOS, nothing I can do.

**Comment by ShkSalmanAhmad** [comment]
ok, thanks anyways.
