### ISSUE TITLE
plugin causes app crash in release mode

### ISSUE THREAD

**Issue by menezes85** [DavBfr/dart_pdf#409]
**Describe the bug**
Hello guys, first i want to congratulate you for this awesome package, and if possble ask for help , i am experiencing a trouble with printing in release mode, package works perfectly in debug mode, but in release iam receiving a crash, and after a long search over a week, i was unable to solve the issue,can you please help  me?

![crash](https://user-images.githubusercontent.com/43157391/91622546-f89d8000-e96d-11ea-8418-70b35d3d8664.PNG)

**Comment by menezes85** [comment]
please disconsider this, after more search , i discover its flutter bug in current version. thanks.

**Comment by daaniiieel** [comment]
Hey @menezes85, how did you solve this? I have the same problem
