### ISSUE TITLE
Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.

### ISSUE THREAD

**Issue by budescode** [DavBfr/dart_pdf#411]
hi, I'm trying to create multiple pdf pages based on user contents, I've seen this error before and the solution was to use Wrap widget or table. I'm using wrap and it works fine in the second page, after adding more contents, it throws me this error

**Comment by DavBfr** [comment]
Because you generate more than 20 pages. If you want to create more pages, there is an option on MultiPage() to increase the number. Nevertheless, this error is disabled in release builds.
