### ISSUE TITLE
Option to specific the orientation of the pdf file when saving.

### ISSUE THREAD

**Issue by UliPrantz** [DavBfr/dart_pdf#413]
**Is your feature request related to a problem? Please describe.**
The problem is that it's possible to specific the orientation of the generated pdf file while creating it but when saving the file every single page still is in portrait mode. This means I/my users would have to rotate the document every single time with some third party pdf viewer and then save it again.

**Describe the solution you'd like**
Just add an option to the Document().save() function with a parameter of type PdfPageFormat and rotate every page according to this parameter before saving it.

I also looked into the API references but couldn't find anything. If this kind of feature already exists or I missed something then please point me in the right direction.

**Comment by DavBfr** [comment]
You have 2 options: Page( orientation: ) allows you to rotate the content regardless of the page format.
And Page(format: PdfPageFormat.a4.landscape()) will define the paper format.

**Comment by UliPrantz** [comment]
Thank you very much. Solved it!
