### ISSUE TITLE
Ability to create a lot (and I mean a lot) of pages?

### ISSUE THREAD

**Issue by fenchai23** [DavBfr/dart_pdf#414]
Hi I would like to know if there is a solution in creating a lot of pages. Atm if I'm trying to create 2 pages it takes about 1.5 seconds to create. If I am trying to create say 500 pages (ok maybe not 500) or maybe more. My App freezes.

if it's images I think 20 pages is the perfect spot, anything more and the app crashes.

I have yet to find how many pages for pdf it can create before crashing but I'm guessing maybe 40 as pdf pages are easier to create than images.

- **images**: max 15-16 pages before crash
- **pdf** : 114 pages still no crash.

is there a way to prevent the freeze?

**Comment by DavBfr** [comment]
To prevent the freeze, the only solution is to use `Isolates`.

**Comment by fenchai23** [comment]
can you show an example of using `isolates` ?

I would appreciate it.

I was thinking a more silly approach like separating the work in batches.

**Comment by DavBfr** [comment]
There is one in the unit tests:
https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/isolate_test.dart

**Comment by fenchai23** [comment]
testing
