### ISSUE TITLE
Exception on two or more paper size formats in PdfPreview

### ISSUE THREAD

**Issue by divan** [DavBfr/dart_pdf#416]
**Describe the bug**

I'm trying to add few paper sizes to the PdfPreview widget like that:
```dart
 return PdfPreview(
                  pageFormats: <String, PdfPageFormat>{
                                    'A4': PdfPageFormat.a4,
                                    'A3': PdfPageFormat.a3,
                  },
                  initialPageFormat: PdfPageFormat.a4,
                  build: ....
);
```
This code throws an exception:
```
 There should be exactly one item with [DropdownButton]'s value: Page 841.8897637795275x595.275590551181 margins:56.69291338582677, 56.69291338582677, 56.69291338582677, 56.69291338582677. 
```

I'm using latest plugin version (pdf: ^1.11.0)

**Flutter Doctor**
<details>
<summary>flutter doctor</summary>
[✓] Flutter (Channel master, 1.21.0-9.0.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.21.0-9.0.pre at /Users/divan/flutter
    • Framework revision bc079c162c (4 weeks ago), 2020-08-09 00:56:01 -0400
    • Engine revision ece904289b
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/divan/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/divan/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/divan/Library/Android/sdk/ndk-bundle/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83
</details>
```

**Desktop**
MacOS X

**Comment by DavBfr** [comment]
I don't have that issue at all. Can you update your flutter version, or use the stable release?

**Comment by divan** [comment]
@DavBfr interesting. I have this bug in the desktop app, which means it can use either `dev` or `master` channel. Just checked with `master` on iOS and Android and it works well. The bug, hence, is only in the desktop (macos for now) build.

Any ideas how is that can be related?

**Comment by DavBfr** [comment]
macOS desktop is what I usually use.
I'll check again.

**Comment by divan** [comment]
Wait, I figured it out. It seems to be a Dart hot reload bug.

I was adding new paper sizes and reloading an app (in debug mode), and immediately saw this error. If I stop the app and run it again – everything works, on master, on desktop and iOS.

**Comment by divan** [comment]
Thanks for the quick response and hints. Happy it works fine. This package is impressive! Thanks for terrific work!
