### ISSUE TITLE
Table.fromTextArray() doesn't align text in center when given 'cellAlignment: pw.Alignment.center'

### ISSUE THREAD

**Issue by UliPrantz** [DavBfr/dart_pdf#417]
**Describe the bug**
The pdf widget Table with the constructor fromTextArray() doesn't center text if the property alignment is set to Alignment.center. The code below generates following [pdf](https://imgur.com/a/FQkgXzW).

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  doc.addPage(
    pw.Page(
      build: (pw.Context context) => pw.Table.fromTextArray(
        cellAlignment: pw.Alignment.center,
        data: [
          ['asdfadsfadf', 'adsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\n'],
          ['asdfadsfadf', 'adsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\n'],
          ['asdfadsfadf', 'adsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\n'],
          ['asdfadsfadf', 'adsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\n'],
          ['asdfadsfadf', 'adsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\nadsf\n\n\n']
        ]
      )
    ),
  );
```

**Expected behavior**
The text should be in the center of the cell.

**Screenshots**
https://imgur.com/a/FQkgXzW

**Additional context**
I believe which ever widget used to display the text in the cell just doesn't expand to the full size of the table cell and therefore can't center the text in the table cell.

**Comment by DavBfr** [comment]
I fixed it in the master branch.

**Comment by UliPrantz** [comment]
The issue is still there. The problem is that the height of the rows is intrinsic but the widgets inside one cell still shrink to be as small as the given text. I tried to fix it myself but couldn't find a way since Expanded can't be used in a TableRow/TableCell and the only other way I could think about was LayoutBuilder but this widget is not available. If you have any idea how to do it tell me then I could implement it and make another pull request. Sorry to bother you again. Thanks for this great package anyways.

Attached is a new pdf generated with the master branch (as you can see the first column still aligns top center and not center)
[Test.pdf](https://github.com/DavBfr/dart_pdf/files/5189355/Test.pdf)
