### ISSUE TITLE
Horizontal Bar Chart

### ISSUE THREAD

**Issue by danielbrito1987** [DavBfr/dart_pdf#418]
**Is your feature request related to a problem? Please describe.**
Currently I had the need to create a bar graph, however horizontally, and print it in pdf. Unfortunately I realized that with this library it is not possible.

**Describe the solution you'd like**
I've seen some graphics generation libraries that have this type of graphics, but here I can only use the widgets of your library. My suggestion would be to implement this type of graph, or to allow the use of other widgets.

**Describe alternatives you've considered**

**Additional context**

**Comment by DavBfr** [comment]
You can implement it in the library and create a PR.

**Comment by DavBfr** [comment]
Implemented in pdf-1.12.0
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
