### ISSUE TITLE
Is it possible to directly trigger the printing function without entering the printer preview interface ?

### ISSUE THREAD

**Issue by wenxiangjiang** [DavBfr/dart_pdf#421]
Hello DavBfr,

As the title describes, is it possible to directly trigger the printing function without entering the printer preview interface ?

Thank you.

**Comment by DavBfr** [comment]
It's not possible on Android. On iOS you still have to choose a printer using the Apple dialog.

**Comment by wenxiangjiang** [comment]
@DavBfr Thanks.
