### ISSUE TITLE
hope PdfPreview support zoom

### ISSUE THREAD

**Issue by fanzhouyou** [DavBfr/dart_pdf#422]
just like the  title,in PdfPreview,hope support zoom

**Comment by cassioseffrin** [comment]
@DavBfr,

I have an idea to make your lib pdf  support zoom. Using this package https://pub.dev/packages/flutter_full_pdf_viewer/example. I have tested and it works!

 If do you agree to use a 3th party package I will make a PR and implement it. The idea will be replace the classe _PdfPreviewPage extends StatelessWidget from your package to the preview with zoom of the flutter_full_pdf_viewer. 

I will be waiting for you response, thks in advance.

**Comment by DavBfr** [comment]
No, it won't work, this work only on ios and android. PdfPreview work on ios, android, macos, windows and web. linux is coming.
Additionally it has not been updated since more than a year. It's likely to never have null-safety support in the coming months.

**Comment by cassioseffrin** [comment]
@DavBfr understood!

**Comment by wanjm** [comment]
could this package load pdf from file instead of creation and then display it;

**Comment by DavBfr** [comment]
Sure it can, you just have to read the bytes from the file and return that to the builder function.

**Comment by wanjm** [comment]
sorry which builder function to should i  pass the content in bytes to, is there any example?

**Comment by DavBfr** [comment]
Like this:

```dart
PdfPreview(build: (_) => File('my-document.pdf').readAsBytes());
```

**Comment by DavBfr** [comment]
The master branch supports zoom in PdfPreview with a double tap on a page, then pan and pinch to zoom.

**Comment by wanjm** [comment]
@DavBfr  thanks;

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
