### ISSUE TITLE
Unable to use parent height for container

### ISSUE THREAD

**Issue by budescode** [DavBfr/dart_pdf#423]
Hi Dav, thanks for your help so far.
I'm having issues using the height of my parent widget for my container, I've tried pw.BoxConstraints.expand(),
and double.infinity, both are throwing errors.

I'm using Partition widget to divide my screen, then column and a container, 
The image below is a container with fixed height, but I wanted it to occupy the whole height of the pdf.
Please tell me what to do thanks.

![WhatsApp Image 2020-09-08 at 11 57 09 AM](https://user-images.githubusercontent.com/32739408/92468568-49617400-f1cb-11ea-92c3-9beb1078546a.jpeg)

**Comment by DavBfr** [comment]
What I would do is to use a fixed page margin on the right, and draw the black content using the page background. This way you have full control over the two parts.

**Comment by budescode** [comment]
the height is not fixed, its based on contents from the users.
I need help here please

**Comment by DavBfr** [comment]
I updated the demo to use Partitions: https://davbfr.github.io/dart_pdf/ it's now multi-pages.
