### ISSUE TITLE
web enable the demo

### ISSUE THREAD

**Issue by jrheisler** [DavBfr/dart_pdf#424]
**Is your feature request related to a problem? Please describe.**
Currently the demo seems to have a MediaQuery issue if it is run from Chrome. 

**Describe the solution you'd like**
Make your web app the demo

**Describe alternatives you've considered**
I'm too lame to figure out what's wrong. I wish I knew. It is very cool, and our web only app is in desperate need of a report engine output.

**Additional context**
Thank you so much!

**Comment by DavBfr** [comment]
This demo: https://davbfr.github.io/dart_pdf/#/ ?
What's wrong with chrome?

**Comment by jrheisler** [comment]
The demo runs great with your online link, but when I grab it from github and run it on chrome I get a MediaQuery error. 







    On Tuesday, September 8, 2020, 11:55:15 AM PDT, David PHAM-VAN <notifications@github.com> wrote:  
 
 


This demo: https://davbfr.github.io/dart_pdf/#/ ?
What's wrong with chrome?

**Comment by DavBfr** [comment]
Do you have a backtrace?

**Comment by jrheisler** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════The following assertion was thrown building DoIt(state: DoItState#c7802(ticker inactive)):MediaQuery.of() called with a context that does not contain a MediaQuery.
No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.The context used was: Scaffold  dirty  state: ScaffoldState#118dd(lifecycle state: initialized, tickers: tracking 2 tickers)The relevant error-causing widget was:   DoIt file:///Users/jrheisler/AndroidStudioProjects/flutter_app_demo_pdf/lib/main.dart:25:10When the exception was thrown, this was the stack: dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49  throw_packages/flutter/src/widgets/media_query.dart 819:5                           ofpackages/flutter/src/material/scaffold.dart 2195:50                           didChangeDependenciespackages/flutter/src/widgets/framework.dart 4723:12                           [_firstBuild]packages/flutter/src/widgets/framework.dart 4538:5                            mount...════════════════════════════════════════════════════════════════════════════════════════════════════

    On Tuesday, September 8, 2020, 12:02:27 PM PDT, David PHAM-VAN <notifications@github.com> wrote:  
 
 


Do you have a backtrace?

**Comment by jrheisler** [comment]
I'm an idiot, I downloaded wrong. It's all good. Coffee is on me, you should market this as a report writer.
Sorry!
    On Tuesday, September 8, 2020, 12:02:27 PM PDT, David PHAM-VAN <notifications@github.com> wrote:  
 
 


Do you have a backtrace?

**Comment by DavBfr** [comment]
main.dart line 25? It's not my file: https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/main.dart#L25

**Comment by jrheisler** [comment]
You're write, I had made a change, it's all me. So sorry!!!
