### ISSUE TITLE
Add to Install docs

### ISSUE THREAD

**Issue by jrheisler** [DavBfr/dart_pdf#426]
**Is your feature request related to a problem? Please describe.**
The install directions do not mention this:

  <script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
  <script type="text/javascript">
     pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
  </script>

**Describe the solution you'd like**
Add to install directions:
  <script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
  <script type="text/javascript">
     pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
  </script> 

Thanks, this is really a class act of a package, and I will be buying you more coffee, Amazing job!

**Comment by DavBfr** [comment]
That's added to the master branch.
Thanks.
