### ISSUE TITLE
Table.fromTextArray() doesn't vertical align the text

### ISSUE THREAD

**Issue by UliPrantz** [DavBfr/dart_pdf#427]
The issue is still there. The problem is that the height of the rows is intrinsic but the widgets inside one cell still shrink to be as small as the given text. I tried to fix it myself but couldn't find a way since Expanded can't be used in a TableRow/TableCell and the only other way I could think about was LayoutBuilder but this widget is not available. If you have any idea how to do it tell me then I could implement it and make another pull request. Sorry to bother you again. Thanks for this great package anyways.

Attached is a new pdf generated with the master branch (as you can see the first column still aligns top center and not center)
[Test.pdf](https://github.com/DavBfr/dart_pdf/files/5189355/Test.pdf)

EDIT:
Also as [image on imgur](https://imgur.com/a/HxAeA4A) if somebody don't wanna download a pdf

_Originally posted by @UliPrantz in https://github.com/DavBfr/dart_pdf/issues/417#issuecomment-688964304_

**Comment by DavBfr** [comment]
Should be fixed now
