### ISSUE TITLE
Can't load image using plugin

### ISSUE THREAD

**Issue by izukanjisinks** [DavBfr/dart_pdf#428]
Whenever I try to load an image using the code shown for loading image using image provider it fails ,need help on how to load image

**Comment by izukanjisinks** [comment]
![20200914_115812](https://user-images.githubusercontent.com/36952422/93075059-8c1cc380-f685-11ea-94d2-a4e6a85092bc.jpg)

**Comment by DavBfr** [comment]
I'll need more information.
