### ISSUE TITLE
Versioning and pub.dev plugin.

### ISSUE THREAD

**Issue by UliPrantz** [DavBfr/dart_pdf#430]
Somehow the plugin pdf-1.11.1 from the pub.dev doesn't reflect the changes which are mentioned in the CHANGELOG.md.
The version 1.11.1 should have fixed the vertical alignment issue but these changes aren't reflected in the pub.dev version.

**Comment by DavBfr** [comment]
Version 1.11.2 is not published yet.

**Comment by UliPrantz** [comment]
Yeah but what is about version 1.11.1? This version (1.11.1) says in the CHANGLELOG.md _1.11.1
Fix Table.fromTextArray vertical alignment_. And the changes that were made to do this like this one `enum TableCellVerticalAlignment { bottom, middle, top, full }` aren't included in the pub release. This means something is off with the versioning or with the pub mirror of the plugin or am I wrong?

**Comment by DavBfr** [comment]
Yes, one fix was applied, but it's not enough.
