### ISSUE TITLE
Exception: Image.toByteData is not supported in Flutter for Web

### ISSUE THREAD

**Issue by biancashouse** [DavBfr/dart_pdf#431]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
This is a bug in Flutter and can't be fixed.
