### ISSUE TITLE
Pdf Enhancement

### ISSUE THREAD

**Issue by Sparshagarwal12** [DavBfr/dart_pdf#434]
I want to ask 2 things
1. How to change the Background Color from white to black on which Image is added for pdf
2. I used Pdfformat a3 and after that i am adding footer but the footer is added in next page, so i want to add the footer on same page having a3 page size

**Comment by DavBfr** [comment]
1. Wrap the image into a Container with black color.
2. Can you put some code that reproduces the issue?
