### ISSUE TITLE
Table.fromTextArray nested

### ISSUE THREAD

**Issue by marko-mlinarevic** [DavBfr/dart_pdf#437]
Is it possible to nest rows. For example 

| Title | Subtitle | ---- | <= split third column diagonally in half. Is it possible with .fromTextArray method?

**Comment by DavBfr** [comment]
Table nesting is not supported, sorry.

**Comment by marko-mlinarevic** [comment]
I found a workaround, I cannot use fromTextArray but if I write it manually I can use Table inside table row and then it works
