### ISSUE TITLE
Not working in Flutter Web

### ISSUE THREAD

**Issue by fabioselau077** [DavBfr/dart_pdf#441]
I created a basic example just for testing but on Android it works and on Flutter Web it doesn't.
How to solve?
Reading other issues I saw that there is no File for Flutter Web, since the browser does not have access to memory.
There is no error but nothing happens when I click the button
![image](https://user-images.githubusercontent.com/57275833/95005277-4daf6000-05c4-11eb-82ca-ca0a092eb0d1.png)
![image](https://user-images.githubusercontent.com/57275833/95005282-5c961280-05c4-11eb-93ff-42471480a2ce.png)

**Comment by DavBfr** [comment]
You cannot save to a file on web.

**Comment by fabioselau077** [comment]
> You cannot save to a file on web.

I started now with Flutter Web, how would it look to replace and solve this?
Thanks!

**Comment by DavBfr** [comment]
Use the printing plugin to print or share the file
