### ISSUE TITLE
Decrease Plugin size

### ISSUE THREAD

**Issue by 123dma** [DavBfr/dart_pdf#444]
**Describe the solution you'd like**

Hello I really like the plugin, but I would like to know if it is possible to reduce the size of the package, when it includes plugin printing 3.6.1 the size of my application, increased by 600kb. We all know how important size is for users. appreciate

**Comment by DavBfr** [comment]
On which platform?
For iOS/Android, the native code is really small.

**Comment by 123dma** [comment]
the platform is Android.  I'm migrating an app to the flutter and any additional kb will help.  This plugin is very well developed.  But I only use it to transform from simple HTML to PDF and print.

**Comment by DavBfr** [comment]
Ok. Have you tested a release build? The unnecessary dart code should be stripped off.

**Comment by 123dma** [comment]
Hello DavBfr

Yes, the release version. 
I created a new App and added only the plugin for a small test, to show better.

4.9 before
5.5 after

![imagem 1](https://user-images.githubusercontent.com/8977954/95458361-729b2e80-0948-11eb-9b66-6fef3997455f.PNG)

Im my app I use this code (convert html to pfd and printing). My pfd is very basic and I don´t need to layouts, colors. etcc

```
 await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
              format: format,
              html: '<html><body>' + dd + '</body></html>',
  ));

```

**Comment by DavBfr** [comment]
I don't have a difference that big, around 100k.
What you can do is to remove `pdf` as a dependency and remove PdfPageFormat from your callback.
Other than that, I don't see any simple way to reduce the size. Maybe a more recent version of Dart will do a better tree shaking.

**Comment by DavBfr** [comment]
Fixed in printing v3.6.4

**Comment by 123dma** [comment]
Great.

the request remains open on github.  we can include that it was fixed in
version 3.6.4 and I can write the reduction and close.

Regards


Em dom, 18 de out de 2020 16:49, David PHAM-VAN <notifications@github.com>
escreveu:

**Comment by 123dma** [comment]
Version 1.6.4 fixed the problem. Now the plugin is only 51 kb.

Thank you
