### ISSUE TITLE
Error in none US or West-European characters.

### ISSUE THREAD

**Issue by MstrZeroOne** [DavBfr/dart_pdf#445]
I want to create a PDF that contains Persain words and when I save the PDF I have got this error.
`[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument (string): Contains invalid characters.`

**Comment by DavBfr** [comment]
A crash in the flutter code, nothing I can do, sorry.

**Comment by MstrZeroOne** [comment]
Answer: I solved this problem by using a font that supports Persian language. The default font that used with to create PDF supports only  US or West-European characters.
