### ISSUE TITLE
 Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.

### ISSUE THREAD

**Issue by royhayek** [DavBfr/dart_pdf#446]
I am trying to generate a pdf containing recipe details (image, ingredients, steps...), now the problem is that I am getting an error saying that the widget created more than 20 pages, when ingredients fit on one page there is no error but when it is bigger and should be split into 2 pages it is not working, it is giving me that error. It is not creating more than 20 pages! it should create a maximum of 3 pages, I don't know base on what you are displaying this error. Please help me fix it

**Comment by DavBfr** [comment]
This means your top-level widget is too big and can't fit a page.

**Comment by royhayek** [comment]
Which widget should be used in order to split a Listview into different pages?

**Comment by royhayek** [comment]
I tried commenting everything and keeping a listview wrapped with the Wrap widget and I am still getting the same error

` pw.Wrap(children: [
            pw.ListView.builder(
              //spacing: 7,
              itemBuilder: (ctx, index) => pw.Container(
                child: pw.Text(
                  '${index + 1}. ${steps[index].trim()}',
                  style: pw.TextStyle(
                    fontSize: 16.5,
                    fontWeight: pw.FontWeight.bold,
                    font: ttf,
                  ),
                  textAlign: pw.TextAlign.left,
                ),
              ),
              itemCount: steps.length,
            ),
          ])`

**Comment by DavBfr** [comment]
The pdf library cannot split child widgets, only top levels: your Wrap widget, but every children of the wrap must fit within a page.

**Comment by SmiffyKMc** [comment]
Hey guys, I'm just getting this now myself. I'm new to flutter and widget creating. Is there a way to see if a page has hit it's max count and then just create a new page and continue? I have a list of entries but it's not creating a new page. What is your recommendation to create new pages? Should every widget be wrapped in an Expanded widget?

**Comment by ahorseman** [comment]
Hello,

I'm trying to split the text myself, but that sometimes doesn't look good as I don't know in advance when it's enough. If I simply do it by paragraph then it sometimes creates a large blank space on the bottom of the page as the next paragraph only fitted on a new page.

I would like to split therefore in the middle of a sentence at the max-position. Is there any way to "ask" whether the text I'm putting is is too large already or still fits in? That way I could figure out the sweetspot.

Thx in advance and for this great library.

**Comment by DavBfr** [comment]
You can put your paragraphs in a Wrap, like this:

```dart
const text = 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a first-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical, improper Latin.';

pw.Wrap(children: text.split(' ').map<Widget>((e) => pw.Text(e)).toList());
```

**Comment by DavBfr** [comment]
This usually means you have at least one widget that's larger than a page. You need to make it fit into a page.
