### ISSUE TITLE
TextStyle can't be assigned

### ISSUE THREAD

**Issue by atishpaul** [DavBfr/dart_pdf#447]
When adding TextStyle it is showing this error -

The argument type 'TextStyle (where TextStyle is defined in C:\src\flutter\packages\flutter\lib\src\painting\text_style.dart)' can't be assigned to the parameter type 'TextStyle (where TextStyle is defined in C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\pdf-1.11.2\lib\widgets\text_style.dart)'.

Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (12 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

**Comment by DavBfr** [comment]
use `pw.TextStyle`

**Comment by atishpaul** [comment]
Got it! 
Thanks!

**Comment by DavBfr** [comment]
No problem, don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
