### ISSUE TITLE
Problem to show RTL languages.

### ISSUE THREAD

**Issue by MstrZeroOne** [DavBfr/dart_pdf#449]
I had an error When I was using the Persian character in the PDF and I solved that by changing the font.  But now the problem is that the Persian characters don't show correctly. For example. سلام = Hello, That shows سلام Like this م ا ل س.

**Comment by ttpho** [comment]
@MstrZeroOne I think, the problem is the config of application. 
Have you tried this way yet?
https://stackoverflow.com/a/54689825
Please  consider it with `Directionality` widget of application or set up `flutter_localizations`  with Persian languages.
🙇
