### ISSUE TITLE
Custom Width and Height 

### ISSUE THREAD

**Issue by imakevirtual** [DavBfr/dart_pdf#450]
How to set custom width and height instead of using A4, A3 and A5?

**Comment by ForceGT** [comment]
You can use the ```PdfPageFormat``` Constructor in both the Page as well as the MultiPage variants of the widgets.dart file

Here's an example of how to do it

![image](https://user-images.githubusercontent.com/31688051/95838651-aa96dd00-0d5f-11eb-88ce-d6d479f152aa.png)
where ```width``` and ```height``` are your custom widths and heights respectively

**Comment by SoCaliOS** [comment]
Question: I created this pageFormat: PdfPageFormat(295.0, 295.0, marginAll: 12.0), this 4" by 4" prints beautifully on AirPrint compatible printers via the share link on iOS devices. The image will be printed automatically based on the printers and the type of papers loaded. But the print function will work strangely. For example, the image will be printed in a 2 by 3 width to height ratio.

To be more exact:

1. Using share to print: I tested it on a Brother QL-820NWB printer with 2.4" wide continuous roll. It will fit the 4"x4" image to a 2.4" by 2.4" label and automatically cut to the square. On a Brother QL-1110NWB printer with 4.1" wide continuous roll, it will print exactly a 4.1" x 4.1" label.

2. Using print to print: on a Brother QL-820NWB printer with 2.4" wide continuous roll. It will print part of the 4"x4" image to a 2.4" by 2.4" label, but the cut size will be 2.4" x 3.2". On a Brother QL-1110NWB printer with 4.1" wide continuous roll, it will print the entire image correctly, but the cut size will be a 4.1" x 5.2" label.

Any help to solve the mystery will be appreciated.

**Comment by SoCaliOS** [comment]
> How to set custom width and height instead of using A4, A3 and A5?

Here is an example of a 4.1" by 4.1" pageFormat. 
 
pageFormat: PdfPageFormat(295.0, 295.0, marginAll: 12.0),

The first number is width in points, the second number is height in points. 1 inch = 72 points. For more information, you can see page_format.dart inside the pdf package.

**Comment by imakevirtual** [comment]
I got it thanks, guys. @SoCaliOS @ForceGT

**Comment by jlubeck** [comment]
> Question: I created this pageFormat: PdfPageFormat(295.0, 295.0, marginAll: 12.0), this 4" by 4" prints beautifully on AirPrint compatible printers via the share link on iOS devices. The image will be printed automatically based on the printers and the type of papers loaded. But the print function will work strangely. For example, the image will be printed in a 2 by 3 width to height ratio.
> 
> To be more exact:
> 
> 1. Using share to print (from pdfPreview): I tested it on a Brother QL-820NWB printer with 2.4" wide continuous roll. It will fit the 4"x4" image to a 2.4" by 2.4" label and automatically cut to the square. On a Brother QL-1110NWB printer with 4.1" wide continuous roll, it will print exactly a 4.1" x 4.1" label.
> 2. Using print to print (from pdfPreview): on a Brother QL-820NWB printer with 2.4" wide continuous roll. It will print part of the 4"x4" image to a 2.4" by 2.4" label, but the cut size will be 2.4" x 3.2". On a Brother QL-1110NWB printer with 4.1" wide continuous roll, it will print the entire image correctly, but the cut size will be a 4.1" x 5.2" label.
> 3. Kid of a strange thing: the square image will look square in the preview no matter what pageFormat (A4 or Letter) I chose.
> 
> Any help to solve the mystery will be appreciated.

I'm seeing this exact same problem with custom page format. Printing through share works fine. Printing through print button cuts it off
