### ISSUE TITLE
Share Pdf Without Download (Flutter Web)

### ISSUE THREAD

**Issue by imakevirtual** [DavBfr/dart_pdf#451]
@DavBfr Appreciate your job regarding this **PDF** package development. In addition to that, I just want to send the Pdf file which is generated **(document.save())** to the backend using HTTP. Is there any way to achieve this without downloading and share? If it's a no, should add as a feature to this plugin, please. Thank you and great job.

**Comment by DavBfr** [comment]
Using `document.save()`, you already have the binary data making the pdf file, you can upload this directly to your backend server.
