### ISSUE TITLE
Formatting chart x-Axis Timestamps

### ISSUE THREAD

**Issue by marcel-bluestone** [DavBfr/dart_pdf#454]
Hello,

Sorry for not posting on stackoverflow, but I am not allowed to post as I don't have enough credit to create a new tag.

I have data, which is taken on an irregular basis and loaded from a database.
E.g. 01.10.2020 14:42, 01.10.2020 23:00, 15.10.2020 05:23
If I set the x-Axis value type to String (which I have done now), the values are spread evenly without paying respect to the time distribution. 
Therefore I need to have the x-axis values to remain timestamp (int), but these values should be formatted using DateFormat().

Is there any way to achieve this?
I could not find an appropriate function so far. Maybe someone does have a hint?

**Comment by DavBfr** [comment]
If I remember correctly, there is a format callback, somewhere

**Comment by marcel-bluestone** [comment]
> If I remember correctly, there is a format callback, somewhere

Thanks David. Would you have an example on how to use this? 
I don't understand, on how I would be able to set the format here...

**Comment by DavBfr** [comment]
Maybe that can be useful: https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/report.dart#L86b

**Comment by marcel-bluestone** [comment]
Thanks, that worked!
