### ISSUE TITLE
printing on iOS

### ISSUE THREAD

**Issue by biancashouse** [DavBfr/dart_pdf#46]
Works on Android but not iOS (both Simulators)

I have added   use_frameworks! to PodFile.

On the iOS ipad simulator I get the following then app termnates:

flutter: build
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104b071e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010419c031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104b88784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000104a895f8 ___forwarding___ + 760
	4   CoreFoundation                      0x0000000104a89278 _CF_forwarding_prep_0 + 120
	5   Flutter                             0x00000001023567ba __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
Lost connection to device.
	6   Flutter                             0x00000001023734ac _ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 166
	7   Flutter                       <…>

**Comment by biancashouse** [comment]
FYI

printing:
    dependency: "direct main"
    description:
      name: printing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"

**Comment by DavBfr** [comment]
Try to debug with Xcode. This call stack is useless.
