### ISSUE TITLE
Adding custom metadata

### ISSUE THREAD

**Issue by Pask00** [DavBfr/dart_pdf#460]
How It Is possible to write/read custom metadata?

**Comment by ForceGT** [comment]
Can you give an example of your use case?

**Comment by Pask00** [comment]
I'm looking to embed some JSON data in a PDF in the form of XMP custom key value pairs.

**Comment by Pask00** [comment]
Maybe it's possible to modify the PdfInfo class by adding a new method that add a new field (for the custom metadata) in params dict?

**Comment by Pask00** [comment]
Ok, yes it works. I access to params dict to add custom metadata.

**Comment by Pask00** [comment]
I achieved that in this way:
`doc.document.info.params['/Custom'] = PdfSecString.fromString(doc.document.info, "my data");`

But now I don't know how to read that, for example I tried to do:
`doc.document.info.params.values['/Custom']`
But this return the PdfDataType object. Any idea?

**Comment by DavBfr** [comment]
Why do you want to read that data?

**Comment by Pask00** [comment]
I am creating an app that do some actions based on that field.
So I need to read that field

**Comment by Pask00** [comment]
Do you know something for this use case?

**Comment by DavBfr** [comment]
No, sorry.

**Comment by Pask00** [comment]
So I think there is no way to add page to (or edit) an existing pdf file too, right?

**Comment by DavBfr** [comment]
Exact. We have a ticket for that: #271

**Comment by Pask00** [comment]
Ok sorry. So I can close, thanks.
