### ISSUE TITLE
can i fill the remaining space in content per page ?

### ISSUE THREAD

**Issue by anandsubbu007** [DavBfr/dart_pdf#462]

**Comment by iamjithinjohnson** [comment]
same issue i have

**Comment by iamjithinjohnson** [comment]
![alt text](https://raw.githubusercontent.com/iamjithinjohnson/flutter/master/Screenshot_20201031-135305.png)

**Comment by DavBfr** [comment]
If you don't share any code, I don't know what you're doing.

**Comment by iamjithinjohnson** [comment]
import 'dart:io';
import 'dart:ui';

import 'package:DocScanner/custom_widgets/custom_button.dart';
import 'package:DocScanner/screens/about.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';

class GeneratePage extends StatefulWidget {
  final List imagePath;
  const GeneratePage({Key key, this.imagePath}) : super(key: key);

  @override
  _GeneratePageState createState() => _GeneratePageState();
}

// A widget that displays the picture taken by the user.
@override
class _GeneratePageState extends State<GeneratePage> {
  var screenHeight = window.physicalSize.height / window.devicePixelRatio;
  var screenWidth = window.physicalSize.width / window.devicePixelRatio;
  final bugController = TextEditingController();
  final pw.Document pdf = pw.Document();

  bool doneProcessing = false;
  int pageCount = 0;
  int totalPage = 1;
  String appDocPath;
  String searchText;

  @override
  void initState() {
    initiateScraping(PdfPageFormat.a4);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;

    return Scaffold(
      // appBar: AppBar(
      //     title: Text(
      //       'DocScanner',
      //       style: TextStyle(color: Colors.black),
      //     ),
      //     actions: <Widget>[],
      //     iconTheme: new IconThemeData(color: Colors.black),
      //     backgroundColor: Colors.white),
      body: SafeArea(
        child: Center(
          child: doneProcessing
              ? Column(
                  children: <Widget>[
                    Image.asset(
                      'images/logo.png',
                      width: width,
                    ),
                    SizedBox(height: 20.0),
                    CustomButton(
                      onPressed: () {
                        _printPdf();
                      },
                      width: 260.0,
                      title: 'Save Document',
                      icon: Icons.print,
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        CustomButton(
                          onPressed: () {
                            sharePdf();
                          },
                          width: 120.0,
                          title: 'Share',
                          icon: Icons.share,
                        ),
                        SizedBox(width: 20.0),
                        CustomButton(
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => AboutPage(),
                              ),
                            );
                          },
                          width: 120.0,
                          title: 'About',
                          icon: Icons.info,
                        ),
                      ],
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        CustomButton(
                          onPressed: () {
                            showDialog(
                              context: context,
                              builder: (BuildContext context) {
                                return Dialog(
                                  shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(
                                          20.0)), //this right here
                                  child: Container(
                                    height: 200,
                                    child: Padding(
                                      padding: const EdgeInsets.all(12.0),
                                      child: Column(
                                        mainAxisAlignment:
                                            MainAxisAlignment.center,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          TextField(
                                            decoration: InputDecoration(
                                                border: InputBorder.none,
                                                labelText: 'Report Bug'),
                                            controller: bugController,
                                          ),
                                          SizedBox(
                                            width: 320.0,
                                            child: RaisedButton(
                                                onPressed: () =>
                                                    _sendBugReportMail(
                                                        bugController.text),
                                                child: Text(
                                                  "Report",
                                                  style: TextStyle(
                                                      color: Colors.white),
                                                ),
                                                color: Colors.black),
                                          )
                                        ],
                                      ),
                                    ),
                                  ),
                                );
                              },
                            );
                          },
                          width: 260.0,
                          title: 'Bug report',
                          icon: Icons.bug_report,
                        ),
                      ],
                    ),
                  ],
                )
              : Center(child: CircularProgressIndicator()),
        ),
      ),
      // drawer: Drawer(
      //   // Add a ListView to the drawer. This ensures the user can scroll
      //   // through the options in the drawer if there isn't enough vertical
      //   // space to fit everything.
      //
      //   elevation: 1.5,
      //   child: CDrawer(),
      // ),
    );
  }

  Future initiateScraping(PdfPageFormat format) async {
    List imageUrl = widget.imagePath;
    for (String item in imageUrl) {
      await addPage(pdf, format, item);
    }
  }

  Future<void> addPage(
      pw.Document pdf, PdfPageFormat format, String imageUrl) async {
    final File file = new File(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: FileImage(file));

    pdf.addPage(pw.MultiPage(
        maxPages: imageUrl.length,
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Column(children: <pw.Widget>[
              pw.Image(image, width: screenWidth, height: screenHeight)
            ])
          ];
        }));
    setState(() {
      if (imageUrl != '') doneProcessing = true;
    });
  }

  void _printPdf() {
    Printing.layoutPdf(onLayout: (PdfPageFormat format) async {
      return pdf.save();
    });
  }

  Future sharePdf() async {
    await Printing.sharePdf(
        bytes: pdf.save(), filename: '${DateTime.now()}.pdf');
  }
}

**Comment by iamjithinjohnson** [comment]
> If you don't share any code, I don't know what you're doing.
```
import 'dart:io';
import 'dart:ui';

import 'package:DocScanner/custom_widgets/custom_button.dart';
import 'package:DocScanner/screens/about.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';

class GeneratePage extends StatefulWidget {
  final List imagePath;
  const GeneratePage({Key key, this.imagePath}) : super(key: key);

  @override
  _GeneratePageState createState() => _GeneratePageState();
}

// A widget that displays the picture taken by the user.
@override
class _GeneratePageState extends State<GeneratePage> {
  var screenHeight = window.physicalSize.height / window.devicePixelRatio;
  var screenWidth = window.physicalSize.width / window.devicePixelRatio;
  final bugController = TextEditingController();
  final pw.Document pdf = pw.Document();

  bool doneProcessing = false;
  int pageCount = 0;
  int totalPage = 1;
  String appDocPath;
  String searchText;

  @override
  void initState() {
    initiateScraping(PdfPageFormat.a4);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;

    return Scaffold(
      // appBar: AppBar(
      //     title: Text(
      //       'DocScanner',
      //       style: TextStyle(color: Colors.black),
      //     ),
      //     actions: <Widget>[],
      //     iconTheme: new IconThemeData(color: Colors.black),
      //     backgroundColor: Colors.white),
      body: SafeArea(
        child: Center(
          child: doneProcessing
              ? Column(
                  children: <Widget>[
                    Image.asset(
                      'images/logo.png',
                      width: width,
                    ),
                    SizedBox(height: 20.0),
                    CustomButton(
                      onPressed: () {
                        _printPdf();
                      },
                      width: 260.0,
                      title: 'Save Document',
                      icon: Icons.print,
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        CustomButton(
                          onPressed: () {
                            sharePdf();
                          },
                          width: 120.0,
                          title: 'Share',
                          icon: Icons.share,
                        ),
                        SizedBox(width: 20.0),
                        CustomButton(
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => AboutPage(),
                              ),
                            );
                          },
                          width: 120.0,
                          title: 'About',
                          icon: Icons.info,
                        ),
                      ],
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        CustomButton(
                          onPressed: () {
                            showDialog(
                              context: context,
                              builder: (BuildContext context) {
                                return Dialog(
                                  shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(
                                          20.0)), //this right here
                                  child: Container(
                                    height: 200,
                                    child: Padding(
                                      padding: const EdgeInsets.all(12.0),
                                      child: Column(
                                        mainAxisAlignment:
                                            MainAxisAlignment.center,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          TextField(
                                            decoration: InputDecoration(
                                                border: InputBorder.none,
                                                labelText: 'Report Bug'),
                                            controller: bugController,
                                          ),
                                          SizedBox(
                                            width: 320.0,
                                            child: RaisedButton(
                                                onPressed: () =>
                                                    _sendBugReportMail(
                                                        bugController.text),
                                                child: Text(
                                                  "Report",
                                                  style: TextStyle(
                                                      color: Colors.white),
                                                ),
                                                color: Colors.black),
                                          )
                                        ],
                                      ),
                                    ),
                                  ),
                                );
                              },
                            );
                          },
                          width: 260.0,
                          title: 'Bug report',
                          icon: Icons.bug_report,
                        ),
                      ],
                    ),
                  ],
                )
              : Center(child: CircularProgressIndicator()),
        ),
      ),
      // drawer: Drawer(
      //   // Add a ListView to the drawer. This ensures the user can scroll
      //   // through the options in the drawer if there isn't enough vertical
      //   // space to fit everything.
      //
      //   elevation: 1.5,
      //   child: CDrawer(),
      // ),
    );
  }

  Future initiateScraping(PdfPageFormat format) async {
    List imageUrl = widget.imagePath;
    for (String item in imageUrl) {
      await addPage(pdf, format, item);
    }
  }

  Future<void> addPage(
      pw.Document pdf, PdfPageFormat format, String imageUrl) async {
    final File file = new File(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: FileImage(file));

    pdf.addPage(pw.MultiPage(
        maxPages: imageUrl.length,
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Column(children: <pw.Widget>[
              pw.Image(image, width: screenWidth, height: screenHeight)
            ])
          ];
        }));
    setState(() {
      if (imageUrl != '') doneProcessing = true;
    });
  }

  void _printPdf() {
    Printing.layoutPdf(onLayout: (PdfPageFormat format) async {
      return pdf.save();
    });
  }

  Future sharePdf() async {
    await Printing.sharePdf(
        bytes: pdf.save(), filename: '${DateTime.now()}.pdf');
  }
}
```

**Comment by iamjithinjohnson** [comment]
@DavBfr  please help

**Comment by DavBfr** [comment]
Don't use MultiPage but just Page.

**Comment by iamjithinjohnson** [comment]
yaaa its worked. thankyou

 <img src="https://raw.githubusercontent.com/iamjithinjohnson/flutter/master/IMG-20201110-WA0008.jpg" alt="Girl in a jacket" width="180" height="400"> 

can i fill remaining whitespace ?

**Comment by DavBfr** [comment]
Try with pw.Center instead of pw.Column. If you want to fill the entire page, remove the margins.

**Comment by iamjithinjohnson** [comment]
yes i changed still same
```
Future<void> addPage(
      pw.Document pdf, PdfPageFormat format, String imageUrl) async {
    final File file = new File(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: FileImage(file));

    pdf.addPage(pw.Page(build: (pw.Context context) {
      return pw.Center(child: pw.Image(image));
    }));
    setState(() {
      if (imageUrl != '') doneProcessing = true;
    });
  }

**Comment by iamjithinjohnson** [comment]
> yes i changed still same
> 
> ```
> Future<void> addPage(
>       pw.Document pdf, PdfPageFormat format, String imageUrl) async {
>     final File file = new File(imageUrl);
>     final PdfImage image = await pdfImageFromImageProvider(
>         pdf: pdf.document, image: FileImage(file));
> 
>     pdf.addPage(pw.Page(build: (pw.Context context) {
>       return pw.Center(child: pw.Image(image));
>     }));
>     setState(() {
>       if (imageUrl != '') doneProcessing = true;
>     });
>   }
> ```
![](https://github.com/iamjithinjohnson/flutter/blob/master/Screenshot_20201113-104641.png?raw=true)

**Comment by DavBfr** [comment]
What do you want to achieve?

**Comment by iamjithinjohnson** [comment]
I want to fill entire page
![](https://raw.githubusercontent.com/iamjithinjohnson/samples/main/Screenshot_20201113-104641.png)
'''

Future<void> addPage(
      pw.Document pdf, PdfPageFormat format, String imageUrl) async {
    final File file = new File(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: FileImage(file));

    pdf.addPage(pw.Page(build: (pw.Context context) {
      return pw.Center(child: pw.Image(image));
    }));
    setState(() {
      if (imageUrl != '') doneProcessing = true;
    });
  }

**Comment by ForceGT** [comment]
> I want to fill entire page
> 
> ![](https://raw.githubusercontent.com/iamjithinjohnson/samples/main/Screenshot_20201113-104641.png)
> 
> ```
> Future<void> addPage(
>       pw.Document pdf, PdfPageFormat format, String imageUrl) async {
>     final File file = new File(imageUrl);
>     final PdfImage image = await pdfImageFromImageProvider(
>         pdf: pdf.document, image: FileImage(file));
> 
>     pdf.addPage(pw.Page(build: (pw.Context context) {
>       return pw.Center(child: pw.Image(image));
>     }));
>     setState(() {
>       if (imageUrl != '') doneProcessing = true;
>     });
>   }

Umm I guess this is the Android Pdf Preview that comes in with AOSP
You'll have to look in there if any changes are possible

**Comment by DavBfr** [comment]
Try like this:

```dart
Future<void> addPage(pw.Document pdf, PdfPageFormat format, String imageUrl) async {
    final File file = new File(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: FileImage(file));

    pdf.addPage(pw.Page(build: (pw.Context context) {
      return FullPage(
        ignoreMargins: true,
        child: pw.Image(image, fit: pw.BoxFit.cover));
    }));
    setState(() {
      if (imageUrl != '') doneProcessing = true;
    });
  }
```

**Comment by Aman-zishan** [comment]
![Screenshot_1605451178](https://user-images.githubusercontent.com/55238388/99187770-87a48200-277e-11eb-9485-d9dc2b2985c7.png)




### how do i get rid of the white space in the right side of the page?

Code:

    Future<void> addPage(
      pw.Document pdf, PdfPageFormat format, String imageUrl) async {
    final File file = new File(imageUrl);
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: FileImage(file));

    pdf.addPage(pw.Page(build: (pw.Context context) {

      return pw.Container(
          child: pw.Center(
            child: pw.Image(
              image,
              fit: pw.BoxFit.fill,
            ),
          ),);

    }));
    setState(() {
      if (imageUrl != '') doneProcessing = true;
    });
  }

@DavBfr

**Comment by iamjithinjohnson** [comment]
> Try like this:
> 
> ```dart
> Future<void> addPage(pw.Document pdf, PdfPageFormat format, String imageUrl) async {
>     final File file = new File(imageUrl);
>     final PdfImage image = await pdfImageFromImageProvider(
>         pdf: pdf.document, image: FileImage(file));
> 
>     pdf.addPage(pw.Page(build: (pw.Context context) {
>       return FullPage(
>         ignoreMargins: true,
>         child: pw.Image(image, fit: pw.BoxFit.cover));
>     }));
>     setState(() {
>       if (imageUrl != '') doneProcessing = true;
>     });
>   }
> ```
## I tried but right side can fill ?
![](https://raw.githubusercontent.com/iamjithinjohnson/samples/main/IMG-20201115-WA0006.jpg)

**Comment by Aman-zishan** [comment]
> ![Screenshot_1605451178](https://user-images.githubusercontent.com/55238388/99187770-87a48200-277e-11eb-9485-d9dc2b2985c7.png)
> 
> ### how do i get rid of the white space in the right side of the page?
> Code:
> 
> ```
> Future<void> addPage(
>   pw.Document pdf, PdfPageFormat format, String imageUrl) async {
> final File file = new File(imageUrl);
> final PdfImage image = await pdfImageFromImageProvider(
>     pdf: pdf.document, image: FileImage(file));
> 
> pdf.addPage(pw.Page(build: (pw.Context context) {
> 
>   return pw.Container(
>       child: pw.Center(
>         child: pw.Image(
>           image,
>           fit: pw.BoxFit.fill,
>         ),
>       ),);
> 
> }));
> setState(() {
>   if (imageUrl != '') doneProcessing = true;
> });
> ```
> 
> }
> 
> @DavBfr

@DavBfr help pls!

**Comment by DavBfr** [comment]
This is because you have to generate the full document inside the layoutPdf's builder. Not just save().
