### ISSUE TITLE
Adding a list as children in widgets

### ISSUE THREAD

**Issue by joselisn** [DavBfr/dart_pdf#463]
Hello

I'm using dart_pdf to generate a pdf with a list of images. Here's my list:

``` 
        final List items = []..add(list.map((element) async {

          final ByteData bytes = await rootBundle.load(element['image']);
          final Uint8List uint8List = bytes.buffer.asUint8List();

          return pw.Image(
            PdfImage.file(
              doc.document,
              bytes: uint8List,
            ),
            width: 80,
            height: 50,
          );
        }).toList());
```

However when I add the list (of type List<dynamic<Widget>>) as children of any widget (List<Widget<Widget>> expected) it throws an exception

```
           pw.Wrap(
              spacing: 1.0, // gap between adjacent chips
              runSpacing: 30.0, // gap between lines
              children: items)
```

```
E/flutter ( 6542): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<Widget>'
```
It only works if I manually type a list like this:
```
             pw.Wrap(
                  spacing: 1.0, // gap between adjacent chips
                  runSpacing: 30.0, // gap between lines
                  children: [
                    pw.Image(
                      logo,
                      width: 80,
                      height: 50,
                    ),
                   ...
                  ])
```
Any thoughts on what am I missing here?

**Comment by DavBfr** [comment]
It's a dart programming issue:
You're creating a list of Futures and not a list of Widgets.
You should always declare the generics:
final items = <pw.Widget>[]..add(list.map<pw.Widget>(...).toList());

this way you'll have a list of Widgets. But you will not be able to use async/await.

**Comment by joselisn** [comment]
It worked, thank you!

At first I was using list.map<Widget<Widget>> instead of list.map<pw.Widget<Widget>>
I have also replaced add with addAll

```
final items =  <pw.Widget>[]..addAll(list.map<pw.Widget>(...).toList());
```
