### ISSUE TITLE
Bar graph issue

### ISSUE THREAD

**Issue by skelt** [DavBfr/dart_pdf#466]
Hi,

there seems to be padding on the bars as when a value is set to 0, it is not flat to the y axis and can be seen.  The example also has this issue e.g. phone budget is 80, but appears to be over 100 on the graph.

Thanks

**Comment by DavBfr** [comment]
Fixed in pdf-1.12.0
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
