### ISSUE TITLE
Chinese and Japanese cannot wrap

### ISSUE THREAD

**Issue by RCLOVETMH** [DavBfr/dart_pdf#467]
Chinese and Japanese cannot wrap。
However, we cannot add spaces between words，
Hope to support
thank you very much！

**Comment by DavBfr** [comment]
I don't read/write Chinese and Japanese so it's hard for me to implement this. Would you be able to implement it if I point you in the right direction?

**Comment by RCLOVETMH** [comment]
I think I can.For Latin,I guess it's through the space character,Then draw the characters one by one.

**Comment by DavBfr** [comment]
Words are actually separated here:
https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/widgets/text.dart#L594
using a regexp. Maybe we can find something more clever. I would first make a function that takes a string and returns a list of strings as an iterable.

**Comment by kcchenkd** [comment]
Sorry to hijack this thread. 
I would like to print Chinese characters, I understand I need to load TrueType font, so I followed instructions from https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management with the fonts I downloaded from fonts.google.com, but I keep getting the following error

I/flutter ( 5062): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter ( 5062): ---------------------------------------------
I/flutter ( 5062): Cannot decode the string to Latin1.
I/flutter ( 5062): This font does not support Unicode characters.
I/flutter ( 5062): If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
I/flutter ( 5062): See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter ( 5062): ---------------------------------------------

@RCLOVETMH Any idea what I am missing?

Thanks in advance!

**Comment by DavBfr** [comment]
@kcchenkd That's because you did not follow properly the page [Fonts-Management](https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management).

**Comment by kcchenkd** [comment]
It turned out that I set the font to PageTheme instead of to Document, and also fonts from fonts.google.com does not work.  Finally I found a font that works.  So I am allset now. Thanks!

**Comment by zisean** [comment]
@kcchenkd May I know which font is supported? Thanks. I have tried Noto San SC but it didn't work. https://en.bestfonts.pro/font/noto-sans-sc

**Comment by DavBfr** [comment]
Relates to #630
