### ISSUE TITLE
Printing does not seem to be implemented for Linux

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [DavBfr/dart_pdf#468]
**Describe the bug**

When accessing `Printing.layoutPdf()` on Linux, the following Error occurs.
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method printPdf on channel net.nfet.printing)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannelPrinting.layoutPdf (package:printing/src/method_channel.dart:146:5)
<asynchronous suspension>
```

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
await Printing.layoutPdf(
     onLayout: (f) => contentBinary,
     name: filename)
```

**Expected behavior**
*Print the document...* A dialog for printing should appear.

**Screenshots**
*Nope*

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [x] Linux

**Additional context**
*None*

**Comment by DavBfr** [comment]
No, it's not. Can you help to implement it?

**Comment by TheOneWithTheBraid** [comment]
Trying... Not sure whether my knowledge is good enough.

**Comment by TheOneWithTheBraid** [comment]
Oh, I realized Flutter in general does not support native PlatformViews on Linux yet. See https://github.com/flutter/flutter/issues/41724 .

**Comment by DavBfr** [comment]
No need for a platform view. This lib uses the lib pdfium to convert the pdf pages to images, and use flutter Image to display them.
Look at the Windows code.

**Comment by TheOneWithTheBraid** [comment]
I see. I am playing around in the source currently but there seems to be not understandable information about *what* the single methods are supposed to do.

Could you please provide information, what **data types** are returned and what should be **contained** in the data returned by
`printingInfo`, `rasterPdf`, `listPrinters`, `sharePdf`, `directPrintPdf`, `printPdf`?

**Comment by DavBfr** [comment]
Sure. I just pushed a branch `linux` where I was testing a few things. The Makefile can download the right library.

The 2 first to implement are:
`printingInfo` which takes no parameter and outputs a map like this:
```json
{  
            "directPrint": false,
            "dynamicLayout": false,
            "canPrint": false,
            "canConvertHtml": false,
            "canShare": false,
            "canRaster": true
}
```

The second is `rasterPdf` which takes a map with these keys:
```
{
             "doc": uint8_t[], // binary pdf data
             "pages": int[], // list of the pages to raster. Omitted or empty to raster all the pages
             "scale": double, // Image scaling factor
             "job": int, // Job number for reference
}
```
it returns the int value `1`.

When the raster of one page is done, the function calls the channel method `onPageRasterized` with a map:
```
{
            "image": uint8_t[], // raw RGBA pixel data
            "width": int, 
            "height": int,
            "job": int, // Job number passed at `rasterPdf`
}
```

And when all the pages have been resterized, it calls the  channel method `onPageRasterEnd` with a map:
```
{
            "job": int, // Job number passed at `rasterPdf`
}
```

The goal would be to share the c++ class from the Windows implementation as much as possible. The rasterPdf function will be exactly the same on linux, as it uses the same library and uses no win32 API https://github.com/DavBfr/dart_pdf/blob/master/printing/windows/print_job.cpp#L306.

**Comment by TheOneWithTheBraid** [comment]
I have a generally different idea for implementing preview on Linux. Unlike on Windows, macOS or Android, on Linux it is popular to *depend* on externally installed libraries instead of including/bundling them with own software. That's why I would propose to depend on e.g. the native libraries of ImageMagick, as they are installed on most of Linux systems instead of bundling an own PDF library.

**Comment by DavBfr** [comment]
Linux is fully implemented.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
