### ISSUE TITLE
Error: Invalid argument(s): Invalid status code 0.

### ISSUE THREAD

**Issue by edwinaceron** [DavBfr/dart_pdf#470]
**Describe the bug**
I got Error: Invalid argument(s): Invalid status code 0. after calling "final baseFont = await rootBundle.load('fonts/NanumGothic-Regular.ttf');" in which the font was placed inside assets/fonts/.

**To Reproduce**

Future<Uint8List> buildPdf(PdfPageFormat pageFormat) async {
    final pw.Document doc = pw.Document(title: "Edwin's Set Report");

    final baseFont = await rootBundle.load('fonts/NanumGothic-Regular.ttf');
    final boldFont = await rootBundle.load('fonts/OpenSans-Bold.ttf');
    final italicFont = await rootBundle.load('fonts/OpenSans-Italic.ttf'); 
    final boldItalicFont = await rootBundle.load('fonts/OpenSans-BoldItalic.ttf');

    doc.addPage(
      pw.MultiPage(
         pageTheme: _buildTheme(
           pageFormat,
           baseFont != null ? pw.Font.ttf(baseFont) : null,
           boldFont != null ? pw.Font.ttf(boldFont) : null,
           italicFont != null ? pw.Font.ttf(italicFont) : null,
           boldItalicFont != null ? pw.Font.ttf(boldItalicFont) : null,
        ),
        header: _buildLCHeader,
        footer: _buildFooter,
        build: (context) => [
          _contentHeader(context, scoreLC, countLC),
          _contentTable(context, itemsLC),
        ]
      )
    );

    doc.addPage(
      pw.MultiPage(
         pageTheme: _buildTheme(
           pageFormat,
           baseFont != null ? pw.Font.ttf(baseFont) : null,
           boldFont != null ? pw.Font.ttf(boldFont) : null,
           italicFont != null ? pw.Font.ttf(italicFont) : null,
           boldItalicFont != null ? pw.Font.ttf(boldItalicFont) : null,
        ),
        header: _buildRCHeader,
        footer: _buildFooter,
        build: (context) => [
          _contentHeader(context, scoreRC, countRC),
          _contentTable(context, itemsRC),
        ]
      )
    );

    doc.addPage(
      pw.MultiPage(
         pageTheme: _buildTheme(
           pageFormat,
           baseFont != null ? pw.Font.ttf(baseFont) : null,
           boldFont != null ? pw.Font.ttf(boldFont) : null,
           italicFont != null ? pw.Font.ttf(italicFont) : null,
           boldItalicFont != null ? pw.Font.ttf(boldItalicFont) : null,
        ),
        header: _buildGrammarHeader,
        footer: _buildFooter,
        build: (context) => [
          _contentHeader(context, scoreGrammar, countGrammar),
          _contentTable(context, itemsGrammar),
        ]
      )
    );

    return doc.save();
  }

**Expected behavior**

Placing break point on "final baseFont = await rootBundle.load('fonts/NanumGothic-Regular.ttf');" and step into it would result to the following error:

Error: Invalid argument(s): Invalid status code 0.
    at Object.throw_ [as throw] (http://localhost:55263/dart_sdk.js:4328:11)
    at streamed_response.StreamedResponse.new.base_response.BaseResponse.new (http://localhost:55263/packages/http/src/browser_client.dart.lib.js:317:17)
    at new streamed_response.StreamedResponse.new (http://localhost:55263/packages/http/src/browser_client.dart.lib.js:655:54)
    at http://localhost:55263/packages/http/src/browser_client.dart.lib.js:206:32
    at _RootZone.runUnary (http://localhost:55263/dart_sdk.js:37447:58)
    at _FutureListener.then.handleValue (http://localhost:55263/dart_sdk.js:32424:29)
    at handleValueCallback (http://localhost:55263/dart_sdk.js:32971:49)
    at Function._propagateToListeners (http://localhost:55263/dart_sdk.js:33009:17)
    at _Future.new.[_complete] (http://localhost:55263/dart_sdk.js:32843:25)
    at Object._cancelAndValue (http://localhost:55263/dart_sdk.js:37857:24)
    at http://localhost:55263/dart_sdk.js:18561:17
    at Object._checkAndCall (http://localhost:55263/dart_sdk.js:4538:16)
    at Object.dcall (http://localhost:55263/dart_sdk.js:4543:17)
    at FileReader.<anonymous> (http://localhost:55263/dart_sdk.js:104997:23)

**Screenshots**

**Flutter Doctor**

[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.18363.1139], locale ko-KR)
    • Flutter version 1.22.0 at C:\flutter
    • Framework revision d408d302e2 (6 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\edwin\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\edwin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.183
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.61

• No issues found!

```
```

**Desktop (please complete the following information):**
 - [x] Browser

**Smartphone (please complete the following information):**
 - Browser [Chrome]

**Comment by DavBfr** [comment]
Looks like your fonts are not declared as assets.
