### ISSUE TITLE
[Flutter Web] - when i do deploy its showing unable to display document

### ISSUE THREAD

**Issue by echomartha** [DavBfr/dart_pdf#471]
**Describe the bug**
already added the js library
https://pub.dev/packages/printing#display-your-pdf-document

version : 
pdf: ^1.11.2
printing: ^3.7.1

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Scaffold(
      appBar: AppBar(
        title: const Text(''),
      ),
      body: PdfPreview(
        build: (format) async => await generateInvoice(format),
        actions: actions,
        allowPrinting: false,
        onShared: _showSharedToast,
      ),
    )
```

**Expected behavior**

**Screenshots**
this is if open my flutter web in my laptop 
![image](https://user-images.githubusercontent.com/71472725/98633786-0f445800-235d-11eb-96a5-8be77f99149f.png)

and this is when open browser in my phone
![image](https://user-images.githubusercontent.com/71472725/98633816-284d0900-235d-11eb-832a-b5944fe548e8.png)

**Flutter Doctor**
```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1139], locale en-ID)
    • Flutter version 1.23.0-18.1.pre at C:\Resource\flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-30-2, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.193
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!

```

**Desktop (please complete the following information):**

 - [*] Browser

**Additional context**
it working fine when open my project flutter at my laptop , but when i try open the flutter web at my phone it showing like this
![image](https://user-images.githubusercontent.com/71472725/98633618-bbd20a00-235c-11eb-8f67-c0fdf60c0faa.png)

**Comment by DavBfr** [comment]
Can you check the JS console errors?

**Comment by Masangula** [comment]
hello @DavBfr am facing the same error as @echomartha Am using the pdf 3.10.3 and printing 5.11.0 I have adding the script to the index.html but still I get the same error and there is no JS logs on the console...Can you help me out with this issue.

**Comment by dengurev** [comment]
Hi !
In flutter web development mode pdf preview show pdf document, but in web deploy show "Unable to display the document".
I was looking for information and try add js script in index.html, but no result...

What need add to index.html ?
