### ISSUE TITLE
Accessibility Support 

### ISSUE THREAD

**Issue by AhmedWahdanZ** [DavBfr/dart_pdf#472]
**Is your feature request related to a problem? Please describe.**

When I enable Accessibility it cant detect the pdf 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavBfr** [comment]
What do you mean?

**Comment by AhmedWahdanZ** [comment]
when I enable Accessibility on the device, the talkback on android can't read pdf

**Comment by DavBfr** [comment]
Using the PdfPreview widget?

**Comment by AhmedWahdanZ** [comment]
yes

**Comment by DavBfr** [comment]
Yes, makes sense. It's just an image.

**Comment by DavBfr** [comment]
Ok, for tooltips, that's easy to add. I'm sure you can provide a PR.

**Comment by AhmedWahdanZ** [comment]
yes sure, but there's no way make PdfPreview support Accessibility?

**Comment by DavBfr** [comment]
With some work, it should be possible.

**Comment by DavBfr** [comment]
Relates to #949

**Comment by martinogarrizzo5** [comment]
Hi,
is there a way to add tags to improve accessibility? 
I would like to improve support for screen readers
