### ISSUE TITLE
Flutter Directionality with MultiPage PDF

### ISSUE THREAD

**Issue by ajawhar20** [DavBfr/dart_pdf#473]
I can not use Directionality with MultiPage pdf export from database sqlite.
what I want to change text directions to rtl.
 pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        theme: pw.ThemeData.withFont(
          base: arabicFont,
        ),
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Header(level: 0, child: pw.Text("Document")),
            pw.Table.fromTextArray(
              headerStyle: pw.TextStyle(fontSize: 6),
              headers: <dynamic>[
                'الحقل الاول',
                'الحقل الثاني',
                'الحقل الثالث',
                'الحقل الرابع',
                'الحقل الخامس'
              ],
              cellAlignment: pw.Alignment.center,
              cellStyle: pw.TextStyle(fontSize: 5, font: arabicFont),
              data: <List<String>>[
                ...taskList.map((msg) => [
                      msg.filed1,
                      msg.filed2.toString(),
                      msg.filed3.toString(),
                      msg.filed4.toString(),
                      msg.filed5.toString()
                    ])
              ],
            )
          ];
        },
      ),
    );
// please your helpe

**Comment by DavBfr** [comment]
This would require a default text direction in the theme maybe.

**Comment by DavBfr** [comment]
Implemented in pdf-1.12.0
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
