### ISSUE TITLE
Size of the PDF. 

### ISSUE THREAD

**Issue by MalteMagnussen** [DavBfr/dart_pdf#474]
## The Size of our generated PDF is very large. 

Our current PDF is 35 mb. And we're only on page 1 of 5. 

How do we reduce the size of the PDF when generated? 

I suspect that the images are the culprit here. 

### Media of the PDF Page 

![image](https://user-images.githubusercontent.com/11192971/99524758-33c1b500-2999-11eb-89d4-3ff29fb63437.png)

@DavBfr Thanks for making this package.

**Comment by DavBfr** [comment]
You should use jpeg images for best results. And change the dimensions to match what you want to print: no need to have a 3000 pixels wide image for 3 cm.

**Comment by MalteMagnussen** [comment]
Thanks @DavBfr , we will try that. Closing for now.
