### ISSUE TITLE
Support adding SVG images to the PDF in the Dart version

### ISSUE THREAD

**Issue by rocboronat** [DavBfr/dart_pdf#475]
**Is your feature request related to a problem? Please describe.**
We're making a paper book using this awesome library. We have several illustrations in Illustrator. To put them in the printable book, we export them in huge images with a huge density, and then we're adding them to the PDF. But it would be great if we could just use the SVGs to achieve the same xxxhigh density.

**Describe the solution you'd like**
To be able to import SVG as we do with PNG and JPEG.

**Comment by DavBfr** [comment]
That's a huge work, and the SVG format can do a lot that is not possible with the PDF format, like shadows.

**Comment by rocboronat** [comment]
Totally agree 😄 Just leaving it there. Thanks for the library! It's so easy to use. Really impressive 🥰

**Comment by DavBfr** [comment]
Happy to hear!
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by DavBfr** [comment]
Implemented in pdf-1.13.0

**Comment by DavBfr** [comment]
See https://github.com/DavBfr/dart_pdf/blob/master/test/golden/widgets-svg.pdf

**Comment by ArvindGundimajalu** [comment]
@DavBfr can you point me to an sample code that does this?

**Comment by DavBfr** [comment]
@ArvindGundimajalu https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_svg_test.dart

**Comment by ArvindGundimajalu** [comment]
@DavBfr thanks a lot!!!
