### ISSUE TITLE
Load image from sharedPreferences to pdf in Flutter

### ISSUE THREAD

**Issue by 1Fenix** [DavBfr/dart_pdf#477]
Hi. I posted on Stackoverflow as suggested  but i didn't get any definitive answer.
https://stackoverflow.com/questions/64799642/load-image-from-sharedpreferences-to-pdf-in-flutter

I'm need to load a image from sharedPreferences to the pdf document. The image loads normally when in normal use, but I don't know how to make it load in the pdf. When I try to load it like a normal image I get "Unhandled Exception: type 'Image' is not a subtype of type 'PdfImage'"

This is how I use it normally.
```dart
       import 'package:flutter/material.dart';
        import 'package:flutter_settings_screens/flutter_settings_screens.dart';
        import 'package:image_picker/image_picker.dart';
        import 'package:shared_preferences/shared_preferences.dart';
        import 'package:MyApp/SharedPrefUtility.dart';
  
    Future<void> initSettings() async {
    await Settings.init(
    cacheProvider: SharePreferenceCache(),
      );
      }

    class ProfilePage extends StatefulWidget {
    @override
      _ProfilePageState createState() => _ProfilePageState();
     }

     class _ProfilePageState extends State<ProfilePage> {
     Image logo;

     pickImage(ImageSource source) async {
     final _image = await ImagePicker.pickImage(source: ImageSource.gallery);

    if (_image != null) {
      setState(() {
        logo = Image.file(_image);
      });
      ImageSharedPrefs.saveImageToPrefs(
          ImageSharedPrefs.base64String(_image.readAsBytesSync()));
    } else {
      print('Error picking image!');
    }
    }

    loadImageFromPrefs() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    final imageKeyValue = prefs.getString(IMAGE_KEY);
    if (imageKeyValue != null) {
      final imageString = await ImageSharedPrefs.loadImageFromPrefs();
      setState(() {
        logo = ImageSharedPrefs.imageFrom64BaseString(imageString);
      });
    }
    }

       @override
        void initState() {
        super.initState();
        loadImageFromPrefs();
        }

        @override
        Widget build(BuildContext context) {
          return Scaffold(
            appBar: AppBar(
              backgroundColor: Colors.red,
              title: Text('Profile Settings'),
            ),
      body: Center(
        child: ListView(
          children: [
            Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                ClipRect(
                  child: Container(
                    width: 300,
                    height: 300,
                    child: logo == null ? Text('No image selected.') : logo,
                  ),
                ),
                RaisedButton(
                  onPressed: () {
                    pickImage(ImageSource.gallery);
                  },
                  child: Text('Pick Company Logo'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
    }
    } 
```

With SharedPrefUtility.dart

```dart
     import 'dart:convert';
      import 'dart:typed_data';
      import 'package:flutter/widgets.dart';
      import 'package:shared_preferences/shared_preferences.dart';

    const IMAGE_KEY = 'IMAGE_KEY';

    class ImageSharedPrefs {
       static Future<bool> saveImageToPrefs(String value) async {
        SharedPreferences prefs = await SharedPreferences.getInstance();

        return await prefs.setString(IMAGE_KEY, value);
      }


      static Future<String> loadImageFromPrefs() async {
        SharedPreferences prefs = await SharedPreferences.getInstance();
        return prefs.getString(IMAGE_KEY);
      }

      static String base64String(Uint8List data) {
        return base64Encode(data);
      }

      static imageFrom64BaseString(String base64String) {
        return Image.memory(
          base64Decode(base64String),
           fit: BoxFit.contain,
        );
      }
    } 
```

Then I tried the suggestion I was given on stackoverflow.

```dart
      Future<Uint8List> writeOnPdf() async {
       final pdf = pw.Document();

    final logo = ImageSharedPrefs.imageFrom64BaseString(await ImageSharedPrefs.loadImageFromPrefs());

    PdfImage logoSmogo = PdfImage.fromImage(pdf.document, image: logo);
    pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(20),
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: <pw.Widget>[
                  pw.ClipRect(
                    child: pw.Container(
                      width: 275,
                      height: 230,
                      child: pw.Image(logoSmogo),
                    ),
                  ),]),];
        }));
```

But got this error: 
E/flutter (19695): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'Image' is not a subtype of type 'Image' where
E/flutter (19695):   Image is from package:flutter/src/widgets/image.dart
E/flutter (19695):   Image is from package:image/src/image.dart

Please help. 
I basically want to put the profile image (logo) into the pdf.

**Comment by DavBfr** [comment]
Use pdfImageFromImage onstead of PdfImage.fromImage

**Comment by 1Fenix** [comment]
Hi @DavBfr .
Thank you, I will try it now.

**Comment by 1Fenix** [comment]
Hi @DavBfr 
I get "the method 'pdfImageFromImage' isn't defined for the type 'SecondScreen'"
SecondScreen is the name of the class.

**Comment by DavBfr** [comment]
It's from the package `printing`

**Comment by 1Fenix** [comment]
Hi @DavBfr 
I get " a value of type 'Future<PdfImage>' can't be assigned to a variable of type 'PdfImage'"

**Comment by DavBfr** [comment]
Well add `await` then

**Comment by 1Fenix** [comment]
Good morning @DavBfr .
I tried that also.     
PdfImage logoSmogo = await pdfImageFromImage(pdf: pdf.document, image: logo);
Gives: 
E/flutter (14958): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'Image' is not a subtype of type 'Image' where
E/flutter (14958):   Image is from package:flutter/src/widgets/image.dart
E/flutter (14958):   Image is from dart:ui

**Comment by davey06** [comment]
Hello , I also got trouble with pdfImage.FromImage before.

**Comment by 1Fenix** [comment]
Hi @davey06 . Thank you for the advice, but I'm still getting errors. "The argument type 'List<Uint8List>' can't be assigned to the parameter type 'Uint8List'." I must be doing something wrong, but i don't know what. Could you maybe give an example of how you got it to work?

**Comment by davey06** [comment]
Sorry, I give a bad example.
the bytes parameter suppose to get Uint8List type. just put your image variable there without '<Uint8List>'
```
Uint8List myImage
pw.Image(PdfImage.file(document.document, bytes: myImage))
```

**Comment by 1Fenix** [comment]
Thank you @davey06, I will try it and get back to you.

**Comment by 1Fenix** [comment]
Thank you @davey06, I will try it and get back to you.

**Comment by 1Fenix** [comment]
Hi @davey06 . I tried your suggestion but no luck. 
I also tried so many other thing but either get "Class 'Image' has no instance method 'toByteData'" or "Image' is not a subtype of type .....". I really don't know what to do now. 
Ps: I am somewhat new to coding (If it wasn't obvious, hahaha).

**Comment by davey06** [comment]
Ok, I've tried your code.

Here is the working Code:
```
final imageString = await ImageSharedPrefs.loadImageFromPrefs(); // Create a PDF document.

    final document = pw.Document();

    // Add page to the PDF
    document.addPage(pw.Page(build: (context) {
      return pw.Center(
        child: pw.Image(
          PdfImage.file(document.document, bytes: base64Decode(imageString)),
        ),
      );
    }));

    // Return the PDF file content
    return document.save();
```
`base64Decode` return `Uint8List` type for the bytes, while your function `imageFrom64BaseString(String base64String)` return `Image` type.

**Comment by 1Fenix** [comment]
@davey06 Its Working!!!!!!!!!
I have no idea what i did wrong earlier, but it's working now.
Thank you so much for your help and  patience!

**Comment by Arefinsaidul** [comment]
> Ok, I've tried your code.
> 
> Here is the working Code:
> 
> ```
>     final imageString = await ImageSharedPrefs.loadImageFromPrefs(); 
>     // Create a PDF document.
>     final document = pw.Document();
> 
>     // Add page to the PDF
>     document.addPage(pw.Page(build: (context) {
>       return pw.Center(
>         child: pw.Image(
>           PdfImage.file(document.document, bytes: base64Decode(imageString)),
>         ),
>       );
>     }));
> 
>     // Return the PDF file content
>     return document.save();
> ```
> 
> > final imageString = await ImageSharedPrefs.loadImageFromPrefs();
> > PdfImage.file(document.document, bytes: base64Decode(imageString)),
> 
> `base64Decode` return `Uint8List` type for `bytes` parameter, while your function `imageFrom64BaseString(String base64String)` return `Image` type.
> 
> Screenshot: <img alt="" height="500" src="https://user-images.githubusercontent.com/32833275/101145770-d4c49700-364c-11eb-988c-452ade5ded87.jpeg"> <img alt="" height="500" src="https://user-images.githubusercontent.com/32833275/101145794-dd1cd200-364c-11eb-9b2c-7df129d90964.jpeg">
> 
> Let me know if you need the full code.

Can you give me the full source code??? I am highly in need of it.
