### ISSUE TITLE
List Printers and send directly to specific printer Windows

### ISSUE THREAD

**Issue by mjafartp** [DavBfr/dart_pdf#478]
add functionality to list all available printers and send document directly to connected specific printer.

**Comment by jackselvam** [comment]
Yes this feature useful in windows, every time click print default letter size changed so every time manually need to change the paper size & printer name 
pls work on this.

**Comment by DavBfr** [comment]
I think it's already possible:

```dart
final printers = await Printing.listPrinters();

for (final p in printers) {
  print('Printer: ${p.name} Model: ${p.model}');
}

final r = await Printing.directPrintPdf(
    printer: printers.first,
    onLayout: generatePdf,
);

print(r);
```

**Comment by jackselvam** [comment]
Thanks, it's very useful

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
