### ISSUE TITLE
The app freezes when working with multiple tables with more data while creating pdf.

### ISSUE THREAD

**Issue by ShubhamHande99** [DavBfr/dart_pdf#48]

**Comment by ShubhamHande99** [comment]
its works fine with small data but when data grows it freezes app while creating pdf.

**Comment by DavBfr** [comment]
I guess you have to use some Isolates (https://api.dartlang.org/stable/2.2.0/dart-isolate/dart-isolate-library.html)

**Comment by parthvora25** [comment]
How to implement isolate from flutter app for generating pdf on click of ui button. 
I tried it and there is one issue of having that function to be a top level function.
Also how can i pass multiple parameters for calling the function which will create the pdf?

Any help you both can do to me about this?

**Comment by DavBfr** [comment]
Look at this example: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/isolate_test.dart

**Comment by parthvora25** [comment]
> Look at this example: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/isolate_test.dart

where is test.dart file?

**Comment by DavBfr** [comment]
It's the dart unit-test framework!
You can remove it

**Comment by parthvora25** [comment]
> It's the dart unit-test framework!
> You can remove it

ok i tested it, but i want to use it on click of a button after that this process needs to be started. How can i achieve that? I dont want to use it from my main.dart

**Comment by DavBfr** [comment]
Create a static function that you call from your button callback.
