### ISSUE TITLE
 Sample Example Exception: java.lang.ClassCastException: java.util.ArrayList cannot be cast to int[]

### ISSUE THREAD

**Issue by intelryzen** [DavBfr/dart_pdf#481]
follow is sample Example:

**await for (var page in Printing.raster(doc.save(), pages: [0, 1], dpi: 72)) {
  final image = page.toImage(); // ...or page.toPng()
  print(image);
}**

That code does not generate bugs on ios, but on Android it does.

I think the bug came from 'pages'.
Without 'pages' no bug will occur.

Exception :

E/MethodChannel#net.nfet.printing(14949): Failed to handle method call
E/MethodChannel#net.nfet.printing(14949): java.lang.ClassCastException: java.util.ArrayList cannot be cast to int[]
E/MethodChannel#net.nfet.printing(14949): 	at net.nfet.flutter.printing.PrintingHandler.onMethodCall(PrintingHandler.java:92)
E/MethodChannel#net.nfet.printing(14949): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#net.nfet.printing(14949): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#net.nfet.printing(14949): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#net.nfet.printing(14949): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#net.nfet.printing(14949): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#net.nfet.printing(14949): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#net.nfet.printing(14949): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#net.nfet.printing(14949): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#net.nfet.printing(14949): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#net.nfet.printing(14949): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (14949): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.util.ArrayList cannot be cast to int[], null, java.lang.ClassCastException: java.util.ArrayList cannot be cast to int[]
E/flutter (14949): 	at net.nfet.flutter.printing.PrintingHandler.onMethodCall(PrintingHandler.java:92)
E/flutter (14949): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (14949): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (14949): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (14949): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14949): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (14949): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (14949): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (14949): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14949): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (14949): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (14949): )

**Comment by DavBfr** [comment]
I'm not sure I ever tested that on Android.

**Comment by DavBfr** [comment]
Fixed in pdf-1.13.0
