### ISSUE TITLE
Unable to use Image Provider even though image_provider.dart exists in folder

### ISSUE THREAD

**Issue by lowwailum123** [DavBfr/dart_pdf#482]
I have tried to follow through the examples given, however, I cannot seem to use Image Provider in my project. 
I have tried updating the package to the newest version but it still didn't work. I have noticed that in the gitHub project, in the widgets.dart, there exists an export of widgets/image_provider.dart but mine does not. It seems that there is a difference of library between my library and the one on gitHub.

**Comment by DavBfr** [comment]
Yes, the master branch is not published as a version yet. Use a tag or a release link to download a published version
