### ISSUE TITLE
Images from internet

### ISSUE THREAD

**Issue by DmitriyGavrilov** [DavBfr/dart_pdf#485]
Hello!

Can i use images from internet? I didn't find any information about that. And this code doesn't work - 

`final PdfImage headerImage = await pdfImageFromImageProvider(
      pdf: pdf.document,
      image: NetworkImage(
          'https://raw.githubusercontent.com/DavBfr/dart_pdf/master/pdf/example.jpg'),
    );`

`pw.Image(
              headerImage,
            ),`

Please help.

**Comment by themumy10** [comment]
Hi i managed to do this by adding an image to Units8List converter on the sender side by this code:
First i added package 
https://pub.dev/packages/network_image_to_byte
It converts image to bytes.


  Future<Uint8List> generateInvoice(PdfPageFormat pageFormat) async {

  Future<Uint8List> _networkImageToByte(String url) async {
    ImageProvider image=  NetworkImage(url);

     Uint8List byteImage = await networkImageToByte(url);
    return byteImage;

  }

    Uint8List temp = await _networkImageToByte("_YOUR URL_");

      final invoice = LabelPDFCreatorForProduct(
    
        baseColor: PdfColors.lightGreen600,
        accentColor: PdfColors.lightGreen100,
        photoURL: temp
      );

      return await invoice.buildPdf();

  }

and in the buildPdf

I wrote a function for decoding it into image.



  pdfImageConverter(Uint8List photoURL, pw.Document doc) {
    PdfImage x = PdfImage.file(doc.document, bytes: photoURL);

    return pw.Container(
      alignment: pw.Alignment.center,
      child: pw.Image(
        x,
        alignment: pw.Alignment.center,
      ),
    );
  }

and use this widget like


   pw.Positioned(
        top: 8.5 * oneCm,
        child: pw.Container(
            height: oneCm * 3,
            width: 7.5*oneCm,
            child: pdfImageConverter(photoURL, document)),
      ),


But this is not very effective and very time consuming. We need a more efficent way of doing this. Also this method does not work for the web. Hope this helps for now.

**Comment by DmitriyGavrilov** [comment]
> Hi i managed to do this by adding an image to Units8List converter on the sender side by this code:
> First i added package
> https://pub.dev/packages/network_image_to_byte
> It converts image to bytes.
> 
> Future generateInvoice(PdfPageFormat pageFormat) async {
> Future _networkImageToByte(String url) async {
> ImageProvider image= NetworkImage(url);
> Uint8List byteImage = await networkImageToByte(url);
> return byteImage;
> }
> 
> ```
> Uint8List temp = await _networkImageToByte("_YOUR URL_");
> 
>   final invoice = LabelPDFCreatorForProduct(
>     baseColor: PdfColors.lightGreen600,
>     accentColor: PdfColors.lightGreen100,
>     photoURL: temp
>   );
>   return await invoice.buildPdf();
> ```
> 
> }
> 
> and in the buildPdf
> 
> I wrote a function for decoding it into image.
> 
> pdfImageConverter(Uint8List photoURL, pw.Document doc) {
> PdfImage x = PdfImage.file(doc.document, bytes: photoURL);
> return pw.Container(
> alignment: pw.Alignment.center,
> child: pw.Image(
> x,
> alignment: pw.Alignment.center,
> ),
> );
> }
> 
> and use this widget like
> 
> pw.Positioned(
> top: 8.5 * oneCm,
> child: pw.Container(
> height: oneCm * 3,
> width: 7.5*oneCm,
> child: pdfImageConverter(photoURL, document)),
> ),
> 
> But this is not very effective and very time consuming. We need a more efficent way of doing this. Also this method does not work for the web. Hope this helps for now.

Thank you! Now it works)

**Comment by ailtoncunhasilva** [comment]
DmitriyGavrilov or  themumy10...

Please, help me!! I have same problem...
I need to show a image in the document pdf.
This is my cod:


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text('Gerar PDF'),
          centerTitle: true,
        ),
        body: PdfPreview(
          build: (format) => _generatePdf(format),
        ),
      ),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    Future _networkImageToByte(String url) async {
      ImageProvider image = NetworkImage(url);
      Uint8List byteImage = await networkImageToByte(url);
      return byteImage;
    }

    Uint8List temp = await _networkImageToByte('${widget.checklist.photos[0]}');

    final photoChecklist = LabelPDFCreatorForProduct(
      baseColor: PdfColors.lightGreen600,
      accentColor: PdfColors.lightGreen100,
      photoURL: temp,
    );
    await photoChecklist.buildPdf();

    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.Container(
            padding: pw.EdgeInsets.all(6),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                _containerForm2(
                    500, 'DEV-DOCUMENTO DE ENTRADA DE VEÍCULOS(CHECKLIST)'),
                pw.Row(children: [
                  _containerForm(234.90, 'ENTRADA DO VEÍCULO: ___/___/_____'),
                  _containerForm(234.90, 'PREVISÃO DE ENTREGA: ___/___/_____'),
                ]),
                pw.Row(children: [
                  _containerForm(234.90, 'PPLACA: ${widget.checklist.placa}'),
                  _containerForm(234.90, 'N.OS: ${widget.checklist.id}'),
                ]),
                _containerForm2(500, 'DADOS DO CLIENTE'),
                pw.Row(children: [
                  _containerForm(300, 'NOME: ${widget.checklist.name}'),
                  _containerForm(169.80, 'CPF: ${widget.checklist.cpf}')
                ]),
                pw.Row(children: [
                  _containerForm(
                      234.90, 'FONE/WHATSAPP: ${widget.checklist.phone}'),
                  _containerForm(234.90, 'E-MAIL: ${widget.checklist.email}')
                ]),
                _containerForm2(500, 'DADOS DO VEÍCULO'),
                pw.Row(children: [
                  _containerForm(
                      169.80, 'MARCA/MODELO: ${widget.checklist.marca}'),
                  _containerForm(150, 'ANO: ${widget.checklist.yearModel}'),
                  _containerForm(
                      150, 'TIPO COMBUSTÍVEL: ${widget.checklist.combustivel}'),
                ]),
                _containerForm(500, 'CHASSIS: ${widget.checklist.chassis}'),
              ],
            ),
          );
        },
      ),
    );
    return pdf.save();
  }

  pdfImageConverter(Uint8List photoURL, pw.Document doc) {
    PdfImage images = PdfImage.file(doc.document, bytes: photoURL);
    return pw.Container(
      alignment: pw.Alignment.center,
      child: pw.Image(
        images, //<= this is the problem... 
        alignment: pw.Alignment.center,
      ),
    );
  }

  // ignore: non_constant_identifier_names
  LabelPDFCreatorForProduct(
      {PdfColor baseColor, PdfColor accentColor, Uint8List photoURL}) {
    return LabelPDFCreatorForProduct(
      baseColor: baseColor,
      accentColor: accentColor,
      photoURL: photoURL,
    );
  }
}

pw.Widget _containerForm(double width, String text) {
  return pw.Container(
    height: 14,
    width: width,
    child: pw.Container(
      padding: pw.EdgeInsets.only(left: 1, top: 3),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 8,
        ),
      ),
    ),
    decoration: pw.BoxDecoration(
      border: pw.Border.all(
        width: 1,
        color: PdfColors.black,
        style: pw.BorderStyle.solid,
      ),
    ),
  );
}

pw.Widget _containerForm2(double width, String text) {
  return pw.Container(
    height: 14,
    width: width,
    child: pw.Center(
      child: pw.Text(
        text,
        textAlign: pw.TextAlign.center,
        style: pw.TextStyle(
          fontSize: 8,
          color: PdfColors.white,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    ),
    decoration: pw.BoxDecoration(
      color: PdfColors.black,
      border: pw.Border.all(
        width: 1,
        color: PdfColors.black,
        style: pw.BorderStyle.solid,
      ),
    ),
  );
}

**Comment by DmitriyGavrilov** [comment]
Now i use Dio package for downloading image - https://pub.dev/packages/dio

`Future<Uint8List> downloadImg(String url) async {

    Response response;
    try {
      response = await Dio().get<List<int>>(
        url,
        options: Options(
          responseType: ResponseType.bytes,
        ),
      );
    } catch (e) {
      print(e);
    }
    if (response.isNull) {
      return null;
    }
    return response.data;
  }`

and then 

`Uint8List byteImage = await downloadImg(url);`

**Comment by DmitriyGavrilov** [comment]
@ailtoncunhasilva 
or try to use this -

```
pdf: ^1.12.0
printing: ^3.0.0
```

**Comment by ailtoncunhasilva** [comment]
@DmitriyGavrilov 
I´m using "printing"
I see than you use a @themumy10 solution.
I put the same solution, but it not work...
I´m need help... How do you did after use Dio?

**Comment by ailtoncunhasilva** [comment]
@DmitriyGavrilov 
Do you use this solution?:

Future generateInvoice(PdfPageFormat pageFormat) async {
Future _networkImageToByte(String url) async {
ImageProvider image= NetworkImage(url);
Uint8List byteImage = await networkImageToByte(url);
return byteImage;
}

Uint8List temp = await _networkImageToByte("_YOUR URL_");

  final invoice = LabelPDFCreatorForProduct(
    baseColor: PdfColors.lightGreen600,
    accentColor: PdfColors.lightGreen100,
    photoURL: temp
  );
  return await invoice.buildPdf();

}

and in the buildPdf

I wrote a function for decoding it into image.

pdfImageConverter(Uint8List photoURL, pw.Document doc) {
PdfImage x = PdfImage.file(doc.document, bytes: photoURL);
return pw.Container(
alignment: pw.Alignment.center,
child: pw.Image(
x,
alignment: pw.Alignment.center,
),
);
}

and use this widget like

pw.Positioned(
top: 8.5 * oneCm,
child: pw.Container(
height: oneCm * 3,
width: 7.5*oneCm,
child: pdfImageConverter(photoURL, document)),
),

**Comment by ailtoncunhasilva** [comment]
@DmitriyGavrilov 
Do would you can show me how you did with the "printing"? i'm using this same package

**Comment by DmitriyGavrilov** [comment]
@ailtoncunhasilva 
Hm, I'm now don't use printing package, but I'm tried to create new project and past your code. What errors do you have now?

**Comment by ailtoncunhasilva** [comment]
Basically, I´m can´t to use image pdf in the document pdf with printing package... pdf: ^1.12.0
printing: ^3.0.0

**Comment by ailtoncunhasilva** [comment]
Do you used @themumy10's solution? I see above that @themumy10 help you. I got same solution above, but it not works.

**Comment by DmitriyGavrilov** [comment]
Now i don't use it( Now I use Dio package for downloading image

**Comment by ailtoncunhasilva** [comment]
I´m also using Dio. But i need take this image and convert at bytes. After i need show this image in the document pdf

**Comment by ailtoncunhasilva** [comment]
I use package printing to visual the document and share the document pdf

**Comment by ailtoncunhasilva** [comment]
I´m problem with it

**Comment by DmitriyGavrilov** [comment]
This works - 
```
pdf: ^1.12.0
printing: ^3.0.0
dio: ^3.0.10
```

```
import 'dart:typed_data';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  Future<Uint8List> downloadImg(String url) async {
    Response response;
    try {
      response = await Dio().get<List<int>>(
        url,
        options: Options(
          responseType: ResponseType.bytes,
        ),
      );
    } catch (e) {
      print(e);
    }
    if (response == null) {
      return null;
    }
    return response.data;
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final pdf = pw.Document();
    Uint8List temp = await downloadImg(
        'https://images.unsplash.com/photo-1610717077228-39c7b13e07cb?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80');
    PdfImage image = PdfImage.file(pdf.document, bytes: temp);

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.Center(
            child: pw.Image(image),
          );
        },
      ),
    );

    return pdf.save();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('title')),
        body: PdfPreview(
          build: (format) => _generatePdf(format, 'title'),
        ),
      ),
    );
  }
}
```
Can you test this? And If everything ok, add another code and test it after every step.

**Comment by ailtoncunhasilva** [comment]
I'm going test...

**Comment by DavBfr** [comment]
Using the latest pdf and printing versions will work like this:

```dart
import 'dart:typed_data';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  Future<Uint8List> downloadImg(String url) async {
    Response response;
    try {
      response = await Dio().get<List<int>>(
        url,
        options: Options(
          responseType: ResponseType.bytes,
        ),
      );
    } catch (e) {
      print(e);
    }
    if (response == null) {
      return null;
    }
    return response.data;
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final pdf = pw.Document();
    final temp = await downloadImg(
        'https://images.unsplash.com/photo-1610717077228-39c7b13e07cb?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80');
    final image = pw.MemoryImage(temp);

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.Center(
            child: pw.Image(image),
          );
        },
      ),
    );

    return pdf.save();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('title')),
        body: PdfPreview(
          build: (format) => _generatePdf(format, 'title'),
        ),
      ),
    );
  }
}

```
