### ISSUE TITLE
How to apply borderRadius on an image?

### ISSUE THREAD

**Issue by Obaydahm** [DavBfr/dart_pdf#487]
Hi

Is it possible to apply border radius on an image for more rounded edges?

Thanks for making this package.

**Comment by DavBfr** [comment]
You can wrap your image in a ClipRRect() widget

**Comment by Obaydahm** [comment]
Damn my bad, forgot to see if it existed in the pdf package. Thank you very much for such a quick answer!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
