### ISSUE TITLE
How to use Printing.directPrintPdf method ?

### ISSUE THREAD

**Issue by teenking** [DavBfr/dart_pdf#488]
I want to print receipt on paper roll57.
I have to use method Printing.directPrintPdf(printer ......
How can i find Printer url

Printer printer = Printer(url: ???)

My Printer is PQ1 Handheld POS Terminal (Android 6.0 LTE)

When i use Printing.layoutPdf, It's show PaperSize ISO A4, so the character is too small.

**Comment by DavBfr** [comment]
Sorry, Android does not support direct print.

**Comment by teenking** [comment]
> Sorry, Android does not support direct print.

How can i Print Roll57 Paper ?
When i use Printing.layoutPdf, It's show PaperSize ISO A4, so the character is too small.

**Comment by DavBfr** [comment]
Maybe your printer driver is not correct

**Comment by teenking** [comment]
> Maybe your printer driver is not correct

**Comment by UsmanAfzal8** [comment]
Printer? pri = await Printing.pickPrinter(context: context);
use this one for find printer

**Comment by UsmanAfzal8** [comment]
final Uint8List bytes = await pdf.save();
Printer? pri = await Printing.pickPrinter(context: context);
    await Printing.directPrintPdf(
        printer: pri!, onLayout: (PdfPageFormat format) async => bytes);
complete solution

**Comment by Manikandan88564** [comment]
> final Uint8List bytes = await pdf.save(); Printer? pri = await Printing.pickPrinter(context: context); await Printing.directPrintPdf( printer: pri!, onLayout: (PdfPageFormat format) async => bytes); complete solution

hi @UsmanAfzal8... it showing error in context..

then the error was when i use bulidcontext in the function... and then build succesfully... but it showing error like this

E/flutter (15115): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method pickPrinter o
n channel net.nfet.printing)
E/flutter (15115): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (15115): <asynchronous suspension>
E/flutter (15115): #1      MethodChannelPrinting.pickPrinter (package:printing/src/method_channel.dart:226:21)
E/flutter (15115): <asynchronous suspension>
E/flutter (15115): #2      Printing.pickPrinter (package:printing/src/printing.dart:116:12)
E/flutter (15115): <asynchronous suspension>
E/flutter (15115): #3      SaveBtnBuilder._printPdf (package:printapp/Presentation/Screens/Widgets/save_btn.dart:60:20)
E/flutter (15115): <asynchronous suspension>
