### ISSUE TITLE
Is it possible to make a widget "fixed"

### ISSUE THREAD

**Issue by Obaydahm** [DavBfr/dart_pdf#491]
Hi Dav

Is it possible to make a widget fixed when using MultiPage?
I have this widget in the yellow on the right side, which I want to be included when the content exceeds the limit and creates a new page.

I'm using pw.Partitions and pw.Partitions. Both the blue and yellow are wrapped in a pw.Partition each, and they're childs of pw.Partitions.

Thank you :)

![image](https://user-images.githubusercontent.com/44967014/101642697-93106380-3a33-11eb-89c6-71b6ada160b8.png)

**Comment by DavBfr** [comment]
If they are always the same content, use the background property of the pageTheme

**Comment by Obaydahm** [comment]
Thank it works good!

Is there a way to find out if the content exceeds the limit and continues on a new page?

As you can see on the gif, I've positioned it with margins, but once it continues on a new i page, i'd like for at to be aligned at the top.

![pdfpagetheme](https://user-images.githubusercontent.com/44967014/101928790-4fa22a80-3bd6-11eb-9c7b-33ef60d49f9c.gif)

**Comment by Obaydahm** [comment]
I found a solution. Thanks!

**Comment by DavBfr** [comment]
Your PDF looks awesome!
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
