### ISSUE TITLE
Undefined class 'pw.MemoryImage'. Try changing the name to the name of an existing class,   and i have  import 'package:pdf/widgets.dart' as pw??

### ISSUE THREAD

**Issue by boosroot** [DavBfr/dart_pdf#495]

**Comment by hetthummar** [comment]
I am facing same issue Did you find any solution?

**Comment by boosroot** [comment]
const imageProvider = const AssetImage('assets/image.png');
final PdfImage image = await pdfImageFromImageProvider(pdf: doc.document, image: imageProvider);

doc.addPage(pw.Page(
    build: (pw.Context context) {
      return pw.Center(
        child: pw.Image(image),
      ); // Center
    }));

**Comment by Miko2x** [comment]
> const imageProvider = const AssetImage('assets/image.png');
> final PdfImage image = await pdfImageFromImageProvider(pdf: doc.document, image: imageProvider);
> 
> doc.addPage(pw.Page(
> build: (pw.Context context) {
> return pw.Center(
> child: pw.Image(image),
> ); // Center
> }));


Where did the doc come from?

**Comment by DavBfr** [comment]
`pw.MemoryImage` is part of the upcoming version 1.13.0, but not yet published.
