### ISSUE TITLE
Undefined class 'pw.MemoryImage'. Try changing the name to the name of an existing class,   and i have  import 'package:pdf/widgets.dart' as pw??

### ISSUE THREAD

**Issue by boosroot** [DavBfr/dart_pdf#496]
Undefined class 'pw.MemoryImage'. Try changing the name to the name of an existing class,   and i have  import 'package:pdf/widgets.dart' as pw  
any help ? 
i want add image to my pdf file

**Comment by DavBfr** [comment]
```dart
const imageProvider = const AssetImage('assets/image.png');
final PdfImage image = await pdfImageFromImageProvider(pdf: doc.document, image: imageProvider);

doc.addPage(pw.Page(
    build: (pw.Context context) {
      return pw.Center(
        child: pw.Image(image),
      ); // Center
    })); // Page
```

**Comment by boosroot** [comment]
Thanks so much for your kind replay
this error  show up!
The method 'pdfImageFromImageProvider' isn't defined for the type 'Invoice'.?

**Comment by boosroot** [comment]
Thanks found it 
import 'package:printing/printing.dart';

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by erperejildo** [comment]
> import 'package:printing/printing.dart';

where are you taking that printing package from?
