### ISSUE TITLE
How to use Arabic Language With tableHeaders in pw.Table.fromTextArray?

### ISSUE THREAD

**Issue by boosroot** [DavBfr/dart_pdf#497]
Hi i want to add Some Word in tableHeaders With Arabic Language 
Any Suggesting? 
    const tableHeaders = [
      'الرقم',
      ' البيان',
      'المبلغ',
      'العدد',
      'المجموع'
    ];
but in pdf file not work

**Comment by DavBfr** [comment]
You can use the `textDirection` attribute of the `Page` object and set it to `TextDirection.rtl`
