### ISSUE TITLE
How can I get the width of the document?

### ISSUE THREAD

**Issue by vadrian89** [DavBfr/dart_pdf#499]
Hello,
First of all, thank you for your packages, it's an awesome work you've done.
Secondly, I'm sorry I opened an issue for this but I tried finding a solution in the past days and I couldn't find one.

Basically I cannot find a way to get width of the document as generated from your package.
Is there a getter or method somewhere?

I am asking because I need to add the following table into the PDF.
![pdf-crop](https://user-images.githubusercontent.com/8177798/102374943-9757f600-3fca-11eb-8723-0ab6fc489910.png)

I made the top part of the table now I need to add that last row so I am thinking of doing the following thing:
1. Set the table's columns width as percentages of total width to ensure fill the width of the document;
2. Sum up the columns width percentages and use that for last row;
3. Use the last column's percentage value for the second column in last row;

What I am missing is the value of the document's width.

Alternative solution I thought of is that I should get the document's format size from the internet, subtract the margin and get the size. But I think this is a bit dirty as I have get sizes for every format.

**Comment by DavBfr** [comment]
You can use the context:
```dart
context.page.pageFormat.availableWidth
```
will give you the page width without margins.

**Comment by vadrian89** [comment]
Hello, sorry for not answering, I haven't managed to test it yet.
Thank you for help :)

**Comment by vadrian89** [comment]
Hello, I managed to test and it doesn't work because availableWidth returns null.

This is how I generate de document:
```
Future<Uint8List> _generatePdf(
    BuildContext mContext, {
    @required UserModel user,
  }) async {
    final pdf = pw.Document(
      theme: await generatePdfTheme(),
    );

    List<pw.Widget> pdfHead = await _pdfHead(pdf: pdf);
    pdf.addPage(
      pw.MultiPage(
        margin: pw.EdgeInsets.all(40),
        pageFormat: PdfPageFormat.a4,
        build: (context) => pdfHead
          ..addAll(_pdfBodyPart1(mContext, context, pdf: pdf, user: user))
          ..addAll(_pdfBodyPart2(mContext, context, pdf: pdf))
          ..addAll(_pdfBodyPart3(context, pdf: pdf))
          ..addAll(_pdfBodyPart4(context, pdf: pdf)),
      ),
    );

    return pdf.save();
  }
```

**Comment by DavBfr** [comment]
You can create a LayoutBuilder:

```dart
typedef LayoutWidgetBuilder = pw.Widget Function(
    pw.Context context, pw.BoxConstraints constraints);

class LayoutBuilder extends pw.StatelessWidget {
  LayoutBuilder({this.builder});

  final LayoutWidgetBuilder builder;

  pw.BoxConstraints _constraints;

  @override
  void layout(pw.Context context, pw.BoxConstraints constraints,
      {bool parentUsesSize = false}) {
    _constraints = constraints;
    super.layout(context, constraints);
  }

  @override
  pw.Widget build(pw.Context context) => builder(context, _constraints);
}
```

And use it like this:

```dart
pdf.addPage(
      pw.Page(
          margin: const pw.EdgeInsets.all(40),
          pageFormat: format,
          build: (context) => LayoutBuilder(
                builder: (context, constraints) =>
                    pw.Text(constraints.toString()),
              )),
    );
```

I will add this widget to the next release.
