### ISSUE TITLE
Remove dart:io dependency from pdf/lib?

### ISSUE THREAD

**Issue by rbishop-bah** [DavBfr/dart_pdf#5]
I would love to use this package in a web app to dynamically create a PDF and download it right from the browser.  This is not possible currently due to dart:io not being available in the browser.  Would it be possible to replace dart:io with the `archive` package which also has a ZLib encoder?  The resulting code would be able to be run on the web, Flutter and VM.
https://pub.dartlang.org/packages/archive

Also `ByteBuffer` from dart_types instead of `BytesBuilder` from dart:io?

**Comment by DavBfr** [comment]
You seem to know what you need. Would you do a pull request?

**Comment by rbishop-bah** [comment]
Yes, I can give it a shot, thanks.

**Comment by rbishop-bah** [comment]
It's not letting me push my branch (web-enable).  I think you need to make me a collaborator in the settings.

**Comment by DavBfr** [comment]
It is now compatible with dart/web. Use any zlib compression function you like to pass to deflate argument like `PDFDocument(deflate: (List<int> data) => new Deflate(data)..getBytes())`
