### ISSUE TITLE
Feature Request: Wrap widget

### ISSUE THREAD

**Issue by BufferUnderflower** [DavBfr/dart_pdf#50]
Wrap widget [Source](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/wrap.dart)

**Describe alternatives you've considered**
Couldn't find any alternatives

**Comment by DavBfr** [comment]
You can use GridView. It can overflow to multiple pages.

**Comment by MichalMisiaszek** [comment]
GridView requires defined height, Wrap does not.

**Comment by DavBfr** [comment]
Implemented in Pdf 1.3.16.
