### ISSUE TITLE
borderRadiusEx and Border doesn't want to play together

### ISSUE THREAD

**Issue by Obaydahm** [DavBfr/dart_pdf#502]
Hi,

For some reason borderRadiusEx and Border doesn't work as intended. It seems like the Border is applied on the outside while is applied radius on the inside:
![image](https://user-images.githubusercontent.com/44967014/102794779-25a5f080-43ac-11eb-8f6d-076e0a771bab.png)

![image](https://user-images.githubusercontent.com/44967014/102795070-91885900-43ac-11eb-8df8-00075d648ded.png)

`pw.Container(
                  margin: pw.EdgeInsets.only(top: 7),
                  decoration: pw.BoxDecoration(
                    color: pdfColors.whiteBlue,
                    border: pw.Border(
                      top: pw.BorderSide(
                        width: 1,
                        color: pdfColors.veryLightBlue,
                      ),
                      left: pw.BorderSide(
                        width: 1,
                        color: pdfColors.veryLightBlue,
                      ),
                      right: pw.BorderSide(
                        width: 1,
                        color: pdfColors.veryLightBlue,
                      ),
                    ),
                    borderRadiusEx: pw.BorderRadius.only(
                      topLeft: pw.Radius.circular(5),
                      topRight: pw.Radius.circular(5),
                    ),
                  ),
                  height: 10,
                ),`

**Comment by DavBfr** [comment]
It's the same with Flutter: A borderRadius can only be given for a uniform Border (same color and width for all 4 borders).
