### ISSUE TITLE
Convert pw.Context to BuildContext

### ISSUE THREAD

**Issue by erperejildo** [DavBfr/dart_pdf#503]
How can I get the BuildContext or convert the pw.Context to a normal BuildContext? I have a shared providing with some taxes in it that I need to display in the pdf. For that I need to do:
`Provider.of<MyRents>(context, listen: false).getBillingInfo();`

If I pass the pw.Context I get a type error

**Comment by DavBfr** [comment]
Yes, both contexts has nothing to do, you'll have to pass the Flutter BuildContext instance somehow.
