### ISSUE TITLE
Android App Closes when trying to print using printing package

### ISSUE THREAD

**Issue by jitenders859** [DavBfr/dart_pdf#504]
**Describe the bug**
when trying to print using Printing.layoutPdf app closes and doesn't show any errors as you can see in the video

https://user-images.githubusercontent.com/41188075/102967765-a8e45500-4518-11eb-845d-e0429750c89e.mp4

**Comment by ForceGT** [comment]
For the stacktrace/error
Start a debug process
This is not the correct way of putting your issue as we cannot find out what happened by magic

**Comment by jitenders859** [comment]
Thanks The problem got solved I was getting issue because I wrote onPause function in MainActivity  which was calling undefined function
