### ISSUE TITLE
Error C3861 identificator not found 

### ISSUE THREAD

**Issue by ezechieldef** [DavBfr/dart_pdf#507]
Hi ! Please I would like to ask you for help with a problem I have while wanting to use the printing plugins, I have an '' error c3861 identifier not found '' error when I try to add the dependency on the pub.yaml file. Make me apologize for the inconvenience

**Comment by DavBfr** [comment]
I'll need more information. I don't know what you're talking about.

**Comment by ezechieldef** [comment]
i am working on a flutter project. I need to be able to print a PDF file from the application and I wanted to use the '' printing '' plugins, described <a href="https://pub.dev/packages/printing"> here </a>
But after adding the '' printing: ^ 3.7.2 '' dependency to my pubspec.yaml file, I can no longer run the application.
I have the error below

**Comment by ezechieldef** [comment]
![Capture](https://user-images.githubusercontent.com/59524025/103243553-87d99500-495a-11eb-9331-1515379c92f4.PNG)

**Comment by DavBfr** [comment]
Ok, on Windows then.
Do you try to build a 32 bits application?

**Comment by ezechieldef** [comment]
No
You can help me do that Please ?

**Comment by DavBfr** [comment]
Not really, I don't why it would not build. Try to run `flutter clean`

**Comment by ezechieldef** [comment]
😔
I don't know if it's only in my case that I have this problem, but when I run "flutter clean", a lot of errors that didn't exist in the past appear.


![Capture0](https://user-images.githubusercontent.com/59524025/103260363-a1e89700-499d-11eb-92ad-99e4d12abc31.PNG)

**Comment by ezechieldef** [comment]
Merci beaucoup, 
Thank you very much 
That's worked after flutter clean

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
