### ISSUE TITLE
put an image in a cell (Table.fromTextArray)

### ISSUE THREAD

**Issue by franzsc** [DavBfr/dart_pdf#509]
I would like to put an image in a cell when building a table.

The cell data only supports string. As it can be seen below, the row only accepts a Container containing a Text type.
![image](https://user-images.githubusercontent.com/3905958/103396565-fb69d680-4b01-11eb-90a7-827b785cf23f.png)

My question is: can we override this function and add a support for an Image, so we can support both?. Would that work?

Thank you

**Comment by DavBfr** [comment]
If you want to use something else than text, don't use `Table.fromTextArray` but construct the Table by yourself.

```dart
    pdf.addPage(Page(
      build: (Context context) => Table(
        children: [
          TableRow(children: [
            PdfLogo(),
            PdfLogo(),
            PdfLogo(),
          ]),
          TableRow(children: [
            PdfLogo(),
            Text('Hello'),
            PdfLogo(),
          ]),
          TableRow(children: [
            PdfLogo(),
            PdfLogo(),
            Text('World'),
          ])
        ],
        border: TableBorder.all(),
        tableWidth: TableWidth.max,
      ),
    ));
```
