### ISSUE TITLE
import androidx.annotation.RequiresApi

### ISSUE THREAD

**Issue by henninggaus** [DavBfr/dart_pdf#512]
I haven't changed the source code since October.
Compiling into an apk no longer works.

`C:\flutter\.pub-cache\hosted\pub.dartlang.org\printing-3.7.2\android\src\main\java\android\print\PdfConvert.java
:25: error: cannot find symbol
import androidx.annotation.RequiresApi;
                          ^
  symbol:   class RequiresApi
  location: package androidx.annotation
C:\flutter\.pub-cache\hosted\pub.dartlang.org\printing-3.7.2\android\src\main\java\android\print\PdfConvert.java
:33: error: cannot find symbol
@RequiresApi(api = Build.VERSION_CODES.KITKAT)
 ^
`

Settings in file gradle.properties are set to:
`org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true`

Target and compile sdk are set to:
`compileSdkVersion 29`
`targetSdkVersion 29`

**Comment by DavBfr** [comment]
What if you remove `android.enableR8=true`?

**Comment by henninggaus** [comment]
Thank you for your answer. I removed the line. The error message still exists. Unfortunately, this does not work.
Do you have another approach I could try?

**Comment by DavBfr** [comment]
You can temporarly remove or rename the android folder and run `flutter create .` to see if something changes.

**Comment by henninggaus** [comment]
Thanks you for your answer. In the past, I copied all the files of the lib folder (and the contents of pubspec.yaml) into a new project. The same error occurs there.

When I rename the folder 'android', I get the following error message.




`[!] The build process for Android has changed, and the current project configuration is no longer valid. Please consult`

`https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-to-build-with-gradle`

`for details on how to upgrade the project.`

**Comment by DavBfr** [comment]
That's not an issue with the printing library, I can't help.
