### ISSUE TITLE
Failing to decode JPEGs if `bytes.offsetInBytes != 0`

### ISSUE THREAD

**Issue by derolf** [DavBfr/dart_pdf#515]
*PROBLEM*

iOS: I am using the package `file_picker` to pick files. For some pictures, the returned buffer is not starting at `0`. Displaying them using a Flutter `MemoryImage` works.

When adding such a JPEG to a PDF using ` pw.Image.provider(pw.MemoryImage(jpeg))`, I get the error `Unhandled Exception: Unable to find a Jpeg image at `package:pdf/src/exif.dart:77`.

*WORKAROUND*

`pw.Image.provider(pw.MemoryImage(jpeg))`
->
` pw.Image.provider(pw.MemoryImage(jpeg.sublist(0)))`

*REMEDY*

Looking at the code, it doesn't properly handle cases where the passed `bytes` has `offsetInBytes != 0`.

**Comment by DavBfr** [comment]
Fixed in the master branch, thanks.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by derolf** [comment]
I am pretty sure there are other places where `offsetInBytes` is not observed...

**Comment by DavBfr** [comment]
@derolf please provide a PR if you find any other issues.
