### ISSUE TITLE
Print Bytes to Printer other than PDF Feature to print using ESC/POS commands or print image on Windows & Linux

### ISSUE THREAD

**Issue by mjafartp** [DavBfr/dart_pdf#516]
**Is your feature request related to a problem? Please describe.**
Print image or Esc/POS commands based printing

**Describe the solution you'd like**
Send Bytes to printer

**Comment by DavBfr** [comment]
See this: https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin
