### ISSUE TITLE
Network Image for web

### ISSUE THREAD

**Issue by Ansonhkg** [DavBfr/dart_pdf#517]
Is it currently possible to use `NetworkImage` as the imageProvider for web?

The following code should be working but it isn't

```
    const imageProvider = const NetworkImage(
        'https://i.picsum.photos/id/796/536/354.jpg?hmac=BbrUsTILKhB6ZK_Ek2TLohBsUCW9sDXdwkmzLvzDDME');
    final image = await flutterImageProvider(imageProvider);
```

I have also tried to turn the image into bytes using your `Future<Uint8List> download` function and it also doesn't work. (for web)

```
  final Uint8List response = await download(imageUrl);
  Response response = await get(imageUrl);
  Uint8List imgBytes = response.bodyBytes;
```

Please advise.

Thanks.

**Comment by DavBfr** [comment]
Cross-domain image downloading is not always possible, and getting access to the pixels is usually forbidden by the web browser.

**Comment by Ansonhkg** [comment]
Is there any workaround I could do?

**Comment by DavBfr** [comment]
a server-side script to download the remote image and serve it to your application from the same domain.

**Comment by edwin0401** [comment]
[import 'package:dio/dio.dart';

Response<Uint8List>? image;
image= await Dio().get(url,
          options: Options(responseType: ResponseType.bytes));

child: pw.Image(pw.MemoryImage(image!.data!)),](url)

**Comment by edwin0401** [comment]
`import 'package:dio/dio.dart';

Response<Uint8List>? image;
image= await Dio().get(url,
          options: Options(responseType: ResponseType.bytes));

child: pw.Image(pw.MemoryImage(image!.data!)),`

**Comment by edwin0401** [comment]
```
import 'package:dio/dio.dart';

Response<Uint8List>? image;
image= await Dio().get(url,
          options: Options(responseType: ResponseType.bytes));

child: pw.Image(pw.MemoryImage(image!.data!)),
```
