### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by adarsh-technocrat** [DavBfr/dart_pdf#520]
### **Description**

- Migrate to sound null safety
- Bump up package version

**Comment by DavBfr** [comment]
That's planned, as soon as the dependent packages `image` and `archive` are sound null safe.

```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies:
archive       ✗2.0.13  ✗2.0.13     -           ✗2.0.13
barcode       ✗1.17.1  ✗1.17.1     -           ✓2.0.0-nullsafety
crypto        ✗2.1.5   ✗2.1.5      -           ✓3.0.0-nullsafety.0
image         ✗2.1.19  ✗2.1.19     -           ✗2.1.19
meta          ✗1.2.4   ✗1.2.4      -           ✓1.3.0-nullsafety.6
path_parsing  ✗0.1.4   ✗0.1.4      -           ✓0.2.0-nullsafety.0
vector_math   ✗2.0.8   ✗2.0.8      -           ✓2.1.0-nullsafety.5
xml           ✗4.5.1   ✗4.5.1      -           ✓5.0.0-nullsafety.1

dev_dependencies:
pedantic      ✗1.9.2   ✗1.9.2      -           ✓1.10.0-nullsafety.3
test          ✗1.15.7  ✗1.15.7     -           ✓1.16.0-nullsafety.13
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```

**Comment by technolion** [comment]
`image` and `archive` now have null-safety packages available:
https://pub.dev/packages/image/versions/3.0.0-nullsafety.0
https://pub.dev/packages/archive/versions/3.0.0-nullsafety.0

Would be great, if this package also supports sound null-safety

**Comment by DavBfr** [comment]
Excellent, I'll work on that.

**Comment by DavBfr** [comment]
Migrated to null-safety. Let me know if you encounter any issues.

**Comment by technolion** [comment]
> Migrated to null-safety. Let me know if you encounter any issues.

That's great, thank you. We'll test right away.

**Comment by jlubeck** [comment]
How can I help test this? I'm getting this error: `Because archive >=3.0.0 depends on crypto ^3.0.0 and pdf >=1.3.14 <2.1.0 depends on crypto ^2.0.6, archive >=3.0.0 is incompatible with pdf >=1.3.14 <2.1.0.` and I'm just assuming it should be fixed with the migration?

**Comment by jlubeck** [comment]
Nevermind, misread the error where it says `<2.1.0` not `<=`
Using 2.1.0 fixed it. Thank you
