### ISSUE TITLE
iOS: The Printing library does not print anything but (a4 portrait, a4 landscape) mode, and if you try to print (a5 portrait) it will layout it on (a4 portrait) which will print in a wrong way ( a5 landscape) it will layout it on (a4 landscape) which will print in a wrong way.

### ISSUE THREAD

**Issue by xSuperMu** [DavBfr/dart_pdf#521]
Usinge Print: ^4.0.0

I've tried this code to test (a5 portrait), knowing that pdfLink have (a5 landscape pdf):

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    format: PdfPageFormat.a5,
    onLayout: (PdfPageFormat format)
    async => pdfData
);
```

**And this was the result: (Still behave in a wrong & unexpected way)**

![1](https://user-images.githubusercontent.com/17935590/104123429-d4a66e00-5353-11eb-9017-73dbb67e8f24.png)

Then, I've tried this code to test (a5 landscape):

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    format: PdfPageFormat.a5.landscape,
    onLayout: (PdfPageFormat format)
    async => pdfData
);
```
**And this was the result:**

![2](https://user-images.githubusercontent.com/17935590/104123443-dcfea900-5353-11eb-9f67-afe57f4e2711.png)

**Comment by DavBfr** [comment]
What if you select a printer that has A5 paper on this screen?

**Comment by DavBfr** [comment]
<img width="850" alt="Screen Shot 2021-01-10 at 09 14 47" src="https://user-images.githubusercontent.com/1387855/104123934-f126b400-531b-11eb-8afd-be4f115d1fc6.png">

<img width="606" alt="Screen Shot 2021-01-10 at 09 15 43" src="https://user-images.githubusercontent.com/1387855/104123956-0dc2ec00-531c-11eb-942d-db0ff7036151.png">

**Comment by xSuperMu** [comment]
> What if you select a printer that has A5 paper on this screen?

These are (a5) paper sheets.

**this is when I print using the Print library:**

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/17935590/104124203-1afdcc00-5358-11eb-8b1c-b9da25396838.jpeg)


**this is when I print from Safari:**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/17935590/104124204-1e915300-5358-11eb-9ebf-507584f6e760.jpeg)

**Comment by xSuperMu** [comment]
I'm using iPads.
