### ISSUE TITLE
pdf Image widget no longer accepts PdfImage - how to layout PdfImage in Document?

### ISSUE THREAD

**Issue by mikeesouth** [DavBfr/dart_pdf#522]
So. I've been printing 3.3.1 and pdf 1.8.0. I just upgraded to printing 4.0.0 and pdf 2.0.0 and now the Image widget no longer accepts PdfImage, how can I circumvent this? I want to layout a custom Flutter Widget that I've built using Flutter widgets. I have converted that widget using the "wrapWidget" method that gives me a PdfImage. In printing 3.3.1 and pdf 1.8.0 I just put this center on the page and it worked perfectly.

Here's my code that works for old versions but not with printing 4.0.0 and pdf 2.0.0:
```
void _printWidgetTreeByKey() {
  Printing.layoutPdf(
    format: PdfPageFormat.a4,
    onLayout: (format) => _buildPdfFromWidgetKeys(),
  );
}

Future<Uint8List> _buildPdfFromWidgetKeys() async {
  final doc = pw.Document();

  for (int i = 0; i < profileGlobalKeys.length; i++) {
    final image = await wrapWidget(
      doc.document,
      key: profileGlobalKeys[i],
      pixelRatio: 2.0,
    );

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Image(image),
          );
        },
      ),
    );
  }

  return doc.save();
}
```

**Comment by mikeesouth** [comment]
Found a solution to my own problem. pw.ImageProxy() takes an PdfImage as argument and returns a pw.ImageProvider.
So I changed the pw.Image line to this: `child: pw.Image(pw.ImageProxy(image)),`

And btw, pw is imported like this:
```
import 'package:printing/printing.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
```

Hopes this helps someone.

**Comment by DavBfr** [comment]
I missed this one, maybe wrapWidget should return an ImageProvider.
