### ISSUE TITLE
Printing pdf from url

### ISSUE THREAD

**Issue by qbait** [DavBfr/dart_pdf#523]
I would like to print and share a pdf, but from the URL, not created by myself. Is there a way to achieve that using `printing` package?

**Comment by DavBfr** [comment]
Yes, you can download the file and pass that UInt8Bytes blob to the Printing functions:

```dart
final data = await download('https://server.com/document.pdf');

await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => data,
);
```

**Comment by qbait** [comment]
Great, but is there also a way to display that pdf file using `dart_pdf`?

**Comment by DavBfr** [comment]
Yes, same way using the PdfPreview widget. It's all on the page: https://pub.dev/packages/printing
