### ISSUE TITLE
Image not rendering for web

### ISSUE THREAD

**Issue by Derrick56007** [DavBfr/dart_pdf#524]
**Describe the bug**

The image will display correctly and then disappear after a few seconds

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  final imageProvider = NetworkImage('$imageUrl');
  final image = await flutterImageProvider(imageProvider);
```

**Expected behavior**
The image should stay rendered

**Screenshots**
![Untitled (2)](https://user-images.githubusercontent.com/5177280/104257131-8ebfd780-5431-11eb-9838-fa088bcb238e.png)

**Flutter Doctor**
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.13.6 17G8029 darwin-x64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.

```
```

**Comment by Derrick56007** [comment]
![Untitled 2](https://user-images.githubusercontent.com/5177280/104257222-cb8bce80-5431-11eb-9372-034818ad7ff7.png)

This appears in the console

**Comment by DavBfr** [comment]
This very looks like a missing await somewhere.
