### ISSUE TITLE
Pdf file size too big

### ISSUE THREAD

**Issue by NighttCoder** [DavBfr/dart_pdf#527]
I am converting a jpg file ~2.2MB , my output pdf file size almost 13MB.
The resolution of file is 2160x3840

I am using, 
  printing: ^3.7.2
The problem also happens in 3.6.1

Problem also happens both in iOS and Android.

This is the code snippet
`
    var imageProvider = FileImage(File(filename));
    final image = await flutterImageProvider(imageProvider);

    pdfdoc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.undefined,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Image.provider(image),
          ); // Center
        },
      ),
    ); 
  await File(fullpath).writeAsBytes(pdfdoc.save());

`
The code is pretty standard as suggested in example.
Any idea why the output file size could be really big when the input jpg is only 2.2MB.

**Comment by DavBfr** [comment]
Don't use flutterImageProvider, as it will recompress the image. The PDF can embed the jpeg as is using this:

```dart

    final image = pw.MemoryImage(await File(filename).readAsBytes());

    pdfdoc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.undefined,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Image(image),
          ); // Center
        },
      ),
    );
```

**Comment by NighttCoder** [comment]
> Don't use flutterImageProvider, as it will recompress the image. The PDF can embed the jpeg as is using this:
> 
> ```dart
>     final image = pw.MemoryImage(await File(filename).readAsBytes());
> 
>     pdfdoc.addPage(
>       pw.Page(
>         pageFormat: PdfPageFormat.undefined,
>         build: (pw.Context context) {
>           return pw.Center(
>             child: pw.Image(image),
>           ); // Center
>         },
>       ),
>     );
> ```

@DavBfr This is great and my file size is reasonable now. Thanks a lot!!

On a sidenote : I believe 'flutterImageProvider' is removed from 4.0.0 but pub example page still use this api.
