### ISSUE TITLE
Image network

### ISSUE THREAD

**Issue by marcelocajaiba** [DavBfr/dart_pdf#529]
hi
Is it possible to put image netWork?

**Comment by DavBfr** [comment]
That should be possible.

**Comment by aldogdl** [comment]
Excuse me sir, thank you for answering, but I also want to show an image from network but I have not found in your documentation the way to do it, it would be so kind to give an example, thanks for your attention.
Sorry translation from google.

**Comment by yasinakca** [comment]
Hi @DavBfr, can you give an example about how to put an image to pw variable? Best regards.

**Comment by DavBfr** [comment]
Try this: https://github.com/DavBfr/dart_pdf/wiki/Network-Image

**Comment by aldogdl** [comment]
thanks for your time, it was very helpful.

**Comment by marcelocajaiba** [comment]
thanks

**Comment by marcelocajaiba** [comment]
I managed to do it like this:
import 'package:flutter/material.dart' as pw;
reportView(context) async {
  final imageProvider = pw.NetworkImage('https://');
  final image = await flutterImageProvider(imageProvider);

  pdf.addPage(MultiPage(
      pageFormat: PdfPageFormat.a4,
      crossAxisAlignment: CrossAxisAlignment.start,
      header: (Context context) {
        if (context.pageNumber == 1) {
          return null;
        }
      },
      build: (Context context) => <Widget>[
            Header(
                child: Row(
              children: [
                Image(image, height: 100, width: 130),
                Column(
                  children: [
                    Text(
                      '${ass.nome} - ${ass.cnpj}',
                      style:
                          TextStyle(fontWeight: FontWeight.bold, fontSize: 8),
                    ),
                    Text(
                      'Tel.:${ass.fone} / ${ass.fone2} - Whats App: ${ass.celular}',
                      style:
                          TextStyle(fontWeight: FontWeight.bold, fontSize: 8),
                    ),
                    Text(
                      '${ass.endereco}, ${ass.numero} -  ${ass.bairro}, ${ass.cidade} - ${ass.estado} CEP: ${ass.cep}',
                      style:
                          TextStyle(fontWeight: FontWeight.bold, fontSize: 8),
                    )
                  ],
                )
              ],
            )),
}

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by deepak786** [comment]
To display the network image, we have to first download the image and then image data will be passed to the pdf widget and the image will be displayed.
This is fine.

But What if we want to display 10 or more network images then the pdf viewer will take a lot of time to get displayed.

So if we have a NetworkImage widget for PDF just like we have in Flutter itself then it would be easy to display the images from the network.

**Comment by devmfouad** [comment]
> Try this: https://github.com/DavBfr/dart_pdf/wiki/Network-Image

the image appear like a black background and not work with me as expected  :(

**Comment by devmfouad** [comment]
> Image(image, height: 100, width: 130),

this work with me awesome ! 👍
