### ISSUE TITLE
How to add a PdfImage into a Document (not a PdfDocument)

### ISSUE THREAD

**Issue by callumclift** [DavBfr/dart_pdf#53]
**Describe the bug**
I'm having some trouble adding my Uint8List image into my Document, the PdfImage constructor expects a PdfDocument value but my PDF is a Document not a PdfDocument

**To Reproduce**
Code snippet to reproduce the behavior:

`Document pdf;`
`  Uint8List customerImageBytes;
`
`Image(PdfImage(pdf, image: customerImageBytes, width: 100, height: 20)));`

**Expected behavior**
I need a way to be able to add the Image to the Document as I have constructed the whole document using the Document.addPage method I need to find a way to add an image inside of the addPage build constructor:

`````
pdf = Document().addPage(Page(
          pageFormat: PdfPageFormat.a4,
          build: (Context context) {
```



            return Container(decoration: BoxDecoration(border: BoxBorder(width: 2.0, top: true, right: true, bottom: true, left: true)), child: Container(color: PdfColors.grey300, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [
              Container(width: 300.0, color: PdfColors.black, child: Text('MAINTENANCE/SERVICE CHECK LIST', textAlign: TextAlign.center ,style: TextStyle(font: Font(), color: PdfColor(255, 255, 255)))),
              Container(height: 10.0),`

**Comment by DavBfr** [comment]
You have the instance of PdfDocument in the Document class:
```dart
pdf.document
```

**Comment by callumclift** [comment]
@DavBfr Ok i've got the instance of the PdfDocument now but for some reason it doesn't like my Uint8List image:
`PdfDocument pdfDoc = pdf.document;
    PdfImage imagee = PdfImage(pdfDoc, image: customerImageBytes, width: 100, height: 30);`

I'm getting the following error in the console:

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: RangeError (index): Index out of range: index should be less than 5548: 5548
#0      _Uint8ArrayView.[] (dart:typed_data/runtime/libtyped_data_patch.dart:3637:7)
#1      PdfImage._prepare (file:///Users/callumclift/appDevelopment/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.3.4/lib/src/image.dart:107:27)
#2      PdfObject._write (file:///Users/callumclift/appDevelopment/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.3.4/lib/src/object.dart:52:5)
#3      PdfOutput.write (file:///Users/callumclift/appDevelopment/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.3.4/lib/src/output.dart:54:8)
#4      __CompactLinkedHashSet&_HashFieldBase&_HashBase&_OperatorEqualsAndHashCode&SetMixin.forEach (dart:collection/set.dart:150:30)
#5      PdfDocument._write (file:///Users/callumclift/appDevelopment/flutter/.pub-cache/hosted/pub.dartlang.org/pdf-1.3.4/lib/src/document.dart:139:13)
#6      PdfDocument.save (file:///Users/callumclift/appDevelopment/flutte<…>`

**Comment by DavBfr** [comment]
What is the content of your customerImageBytes?
PdfImage takes raw RGBA image data

**Comment by callumclift** [comment]
@DavBfr false alarm i've managed to get the image loaded and showing on the page which is a relief! however I was wanting to know if there was a way to place the image inside of a Container inside the pdf page? So far i've seen you can only place is using x & y. The chances are my PDF will vary in size depending on how much data the user inputs and i need the signature to always fit inside the specified signature box. Is there a way to get the x and y of the container I want the image to be place within?

**Comment by DavBfr** [comment]
The same as you do with flutter: put it in a container with the size you want, a FittedBox as the child and then your image. It should easily always get the right size.

**Comment by callumclift** [comment]
@DavBfr excellent, that worked a treat thanks so much for your help!

**Comment by iosdev04** [comment]
@callumclift how did you solve the issue of showing image in PDF. Im still struggle to show image in PDF. Could you help me?

**Comment by dipak4912** [comment]
how i can add image on pdf at perticular loaction in flutter?

**Comment by DavBfr** [comment]
To position your image at 100 millimeters from the left margin and 120 millimeters from the top margin:

```dart
Container(
margin: EdgeInsets.only(
   left: 100*PdfPageFormat.mm,
   top: 120*PdfPageFormat.mm)
child: Image( image ))
```

**Comment by dipak4912** [comment]
thanks David, But my issue is embed image into pdf anywhere to create new pdf file?

**Comment by DavBfr** [comment]
@dipak4912 that's what this code does.

**Comment by PRANAV-PANU** [comment]
I am clicking an image from camera and I want to load the image into the pdf how can I do it.

**Comment by tjcode19** [comment]
Can you drop your full code on how you added the imade to pdf document please?
