### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by Fabrizio1407** [DavBfr/dart_pdf#530]
**Is your feature request related to a problem? Please describe.**
Is already there a way to protect the pdf with password?

Thank you

**Comment by DavBfr** [comment]
Yes, it has password protection, as part of an additional plugin I sell.

**Comment by Fabrizio1407** [comment]
Thank you. Can you give me more info?

**Comment by DavBfr** [comment]
Yes, send me an email.

**Comment by Fabrizio1407** [comment]
You don't seem to have e-mail in your profile. What is your e-mail address? Thank you

**Comment by DavBfr** [comment]
You will find it here: https://pub.dev/publishers/nfet.net/packages
