### ISSUE TITLE
Alignment of Specific Column

### ISSUE THREAD

**Issue by farooqaziz20** [DavBfr/dart_pdf#532]
HI, i want to know the how i can set the specific column alignment in the Table.
I am loading the table from the List, and i want to show balance.
I need to align it to the right.

**Comment by DavBfr** [comment]
Look at this example:
https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/invoice.dart#L455

**Comment by farooqaziz20** [comment]
Thanks, got the solution.
