### ISSUE TITLE
customization of text in cell

### ISSUE THREAD

**Issue by ankitpanwar8979** [DavBfr/dart_pdf#533]
**I want to customize the text in cell**
I am creating an invoice pdf using Table `Table.fromTextArray(...)` and currently it is showing like below where the item name and item description is of same style.
<img width="289" alt="Screenshot 2021-01-21 at 7 50 52 PM" src="https://user-images.githubusercontent.com/56531099/105364553-4cfa1280-5c23-11eb-9dc5-af1c86066bfb.png">

Can you suggest any solution where I can customize this cell with a different `TextStyle` so I can differentiate between name and description like below?
<img width="288" alt="Screenshot 2021-01-21 at 7 50 42 PM" src="https://user-images.githubusercontent.com/56531099/105364931-bb3ed500-5c23-11eb-9d0e-4372dfce7237.png">
The above image is created using `ListView` and `Row` but it's not working properly when the item rate is of bigger value.

It may be possible if the `cellFormat` return `RichText` and directly pass in cell's child in `Table`

**Comment by DavBfr** [comment]
Don't use `fromTextArray` for complex tables, but build the table structure directly.
https://api.flutter.dev/flutter/widgets/Table-class.html

**Comment by ankitpanwar8979** [comment]
Yeah, that worked
Thanks.

**Comment by nisargdesai15** [comment]
@DavBfr complex tables are failing on multipage.
