### ISSUE TITLE
Code don't work in released .exe

### ISSUE THREAD

**Issue by roketstorm** [DavBfr/dart_pdf#534]
Hi! 👋

Our team meet the problem: when we run code inside Visual Studio Code, functions `Printing.directPrintPdf()` or `Printing.layoutPdf()` work well.
But in release and debug builds, if we run executable outside of VSCode (via Explorer) same functions become silent and nothing happens. We tried to copy MSVCR dlls in the same directory, but no effect.

What could it be?

We are using `Flutter 1.26.0-8.0.pre` with `Flutter Windows Desktop`

Thank you!

**Desktop (please complete the following information):**
 - [X] Windows

**Comment by DavBfr** [comment]
I don't have this issue. I used VisualStudio 2019 Community to build my application.

**Comment by roketstorm** [comment]
We are using the same version of Visual Studio. Even if we reinstall it we have the same issue: working inside environment / not working launching from explorer

**Comment by roketstorm** [comment]
We found problem! Everything's work fine!
When Pdf package loads assets (from pubspec) it works correctly if we run project from VSCode environment. In this case package uses relative addresses to files.
But if we run project under Visual Studio solution or run from executable, library can't find the same files and just stops the runtime. We should copy `assets` folder to `release` directory. Assets load successfully if we use Flutter native code.


Maybe this is because of `dev` channel of Flutter.
