### ISSUE TITLE
Load page from pdf file and join it

### ISSUE THREAD

**Issue by kleinpetr** [DavBfr/dart_pdf#535]
Is there any chance to add another pdf below the create one?

For example I have 3 pages created manually and then I want to join another pages from PDF file.

Thanks for help

**Comment by DavBfr** [comment]
Yes, I'm working on a PDF loader to be able to modify an existing PDF file.
This will be part of another package that is not opensource. Drop me an email for more info.

**Comment by kleinpetr** [comment]
Ok, sound good. petr@develit.io

**Comment by Shahriyar13** [comment]
is it available to add existing pdf file **without modify**? just add it to our pdf as an attachment?
