### ISSUE TITLE
Multi pages support

### ISSUE THREAD

**Issue by moatazfouad** [DavBfr/dart_pdf#536]
Hi sir , I spent about one week trying to support Multi pages, but I get this error
**I/flutter ( 2448): Exception: This widget created more than 20 pages. This may be an issue in the widget or the document**
and i tried all solutions mentioned on StackOverFlow
this is the first part of my code 
`pdf.addPage(
    MultiPage(
      build: (pw.Context context) => <pw.Widget>[
        pw.Wrap(
            children: [
              pw.Container(
///My Content here
)
])
]
))`
Can you please help me!

**Comment by DavBfr** [comment]
You should put your content directly as children of Wrap. A container cannot be spanned into multiple pages.

**Comment by Carle2** [comment]
Hello how can we do a break page ? please

**Comment by moatazfouad** [comment]
@DavBfr thank you! it worked!

**Comment by moatazfouad** [comment]
@Carle2 What do you mean by break page?
may be I can help you

**Comment by Carle2** [comment]
Hello thank you for your help
I would like to list a sqtlite table I have a lot of data and I would like to list many pages with number page I dont know how can I do thank you

**Comment by moatazfouad** [comment]
@DavBfr 
Hi, your solution worked for me, but when I put my content directly as a children of Wrap widget I get big space between elements
I found someone face this issue before and you provided him with  [this](https://github.com/DavBfr/dart_pdf/issues/162#issuecomment-544951051)
solution, but it is old and did not work for me, can u please help me?
what should I do?
thanks in advance

**Comment by DavBfr** [comment]
I don't know what you want to do, can you explain?

**Comment by moatazfouad** [comment]
@DavBfr Simply lets say that I have **Text widget** and **ListView.builder widget**, when I put them inside **Wrap widget**
I get Too much space between them, The **Text widget** in the first page of PDF file and the **ListView.builder widget** in the second page and I do not need this big space between them
and this is a very simple code 
`List myList = ['A',  'B', 'C', 'D'];
pdf.addPage( 
  MultiPage( 
     build: (pw.Context context) => <pw.Widget>[ 
pw.Wrap( children: [ 
pw.Text('Hello World:(' ),
pw.ListView.builder(
builder: ( context, index){
return pw.Text(myList[index]);
}
)
]
) ] 
))`
I hope you understand what is my problem 
waiting your answer
thank you!

**Comment by DavBfr** [comment]
You can do that instead, using Column or Wrap depending on what you want to do:

```dart
pdf.addPage(
    MultiPage(
      build: (pw.Context context) => <pw.Widget>[
        pw.Column(
          children: [
            pw.Text('Hello World:('),
            ...List<Widget>.generate(
              myList.length,
              (index) => pw.Text(myList[index]),
            ),
          ],
        )
      ],
    ),
  );
```

**Comment by abdulrahmanHatem911** [comment]
I want to add gridview to a PDF file, but when generating PDF, this problem appears to me, and I do not know how to solve it.
"Unhandled Exception: Instance of 'TooManyPagesException'"
📍I want a solution to a problem that when the gridview exceeds the size of one page, it moves to the next page automatically..
my code :
```
pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          orientation: pw.PageOrientation.portrait,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          build: (context) {
            return [
              pw.Container(
                height: PdfPageFormat.a4.availableHeight,
                child: pw.GridView(
                  crossAxisCount: 2,
                  mainAxisSpacing: 3,
                  crossAxisSpacing: 3,
                  childAspectRatio: 1.5,
                  children: chunk
                      .map(
                        (e) => pw.Container(
                          decoration: pw.BoxDecoration(
                            border:
                                pw.Border.all(color: PdfColors.black, width: 1),
                          ),
                          child: pw.Column(
                            mainAxisAlignment: pw.MainAxisAlignment.start,
                            crossAxisAlignment: pw.CrossAxisAlignment.center,
                            children: [
                              pw.Text(
                                e.name,
                                maxLines: 1,
                                style: pw.TextStyle(
                                  font: ttf,
                                  fontSize: 11,
                                ),
                              ),
                            ],
                          ),
                        ),
                      )
                      .toList(),
                ),
              )
            ];
          },
        ),
      );
```

**Comment by R4F43Lv** [comment]
@abdulrahmanHatem911 I was facing a similar issue. Upon researching, I understood that it is necessary to use 'pw.Warp' instead of 'pw.GridView.' When the GridView exceeds the page size, you encounter an error, whereas the Warp is designed to automatically adjust to the pages.
![code-snapshot](https://github.com/DavBfr/dart_pdf/assets/86110534/93dfa030-c280-4694-ae50-f458c0ee241b)

**Comment by Jhoscy** [comment]
> You can do that instead, using Column or Wrap depending on what you want to do:
> 
> ```dart
> pdf.addPage(
>   pw.MultiPage(
>     build: (pw.Context context) => <pw.Widget>[
>       pw.Column(
>         children: [
>           pw.Text('Hello World:('),
>           ...List<pw.Widget>.generate(
>             myList.length,
>             (index) => pw.Text(myList[index]),
>           ),
>         ],
>       )
>     ],
>   ),
> );
> ```

This is working. Trying to set a "higher" maxPages (default is 20) and displaying using List<pw.Widget>.generate fix my problem.
