### ISSUE TITLE
Add example to pritining labels using this library.

### ISSUE THREAD

**Issue by DhavalRKansara** [DavBfr/dart_pdf#537]
Can you please add an example to print labels(roll) using this package? Also Is there any option using which I can print only one label at a time?

**Comment by DavBfr** [comment]
What about this example?
https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin

**Comment by DhavalRKansara** [comment]
What I can see in the above example is like we have to create a label using [printing](https://pub.dev/packages/printing) and to print that label in the roll form we have to use [esc_pos_printer](https://pub.dev/packages/esc_pos_printer). Right?

The owner of the [esc_pos_printer](https://pub.dev/packages/esc_pos_printer) are not providing any updates for it, So I think that will be great if you provide direct support to print roll label with given heights from this package.

**Comment by DavBfr** [comment]
I updated the example page, but I don't know if it works as I don't have such a printer.
