### ISSUE TITLE
How to add HTML inside a pdf (convertHtml)

### ISSUE THREAD

**Issue by jeffaknine** [DavBfr/dart_pdf#538]
Hi, thanks for your package, it works great.
I'm trying to add some text from HTML inside the pdf i'm generating. From my understanding, convertHtml creates a pdf directly ?
This is what i'm trying to achieve
```
var myHtml = await Printing.convertHtml(
      html: '<html><body><p>Hello!</p></body></html>',
);
final pdf = pw.Document(theme: myTheme);
pdf.addPage(pw.Page(
    pageFormat: PdfPageFormat.a4,
     margin: pw.EdgeInsets.zero,
    build: (pw.Context c) {
          return pw.Center(child: myHtml)
    }));
return pdf.save();
```
Thanks

**Comment by DavBfr** [comment]
That's not possible, it's either full HTML or full dart code.

**Comment by jeffaknine** [comment]
Alright that's what I thought.
So the best solution would be to parse the html myself and use pw.RichText to build it ?

**Comment by DavBfr** [comment]
If that's the only thing you have, yes.

**Comment by jeffaknine** [comment]
Alright thanks again for your package !
