### ISSUE TITLE
Adjust page size.

### ISSUE THREAD

**Issue by olintosergio** [DavBfr/dart_pdf#539]
Is it possible to adjust the page size and the number of pages to be printed via variables? Thanks.

**Comment by DavBfr** [comment]
I don't understand this question, I need more context.

**Comment by olintosergio** [comment]
I would like to know, if I can determine the height and width of the page in pdf, as I intend to make a product label.

**Comment by DavBfr** [comment]
Yes, you can set any size you need:

```dart
  pdf.addPage(
    pw.Page(
      pageFormat: const PdfPageFormat(60 * PdfPageFormat.mm, 30 * PdfPageFormat.mm),
      build: (pw.Context context) => pw.Center(
        child: pw.Text('Hello World!'),
      ),
    ),
  );
```

This will create a page with 6 cm wide and 3 cm tall.
