### ISSUE TITLE
In PdfPreview adding pageFormats throws error

### ISSUE THREAD

**Issue by rishisinghal** [DavBfr/dart_pdf#541]
**Describe the bug**
In PdfPreview adding pageFormats throws error

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
              child: PdfPreview(
                pageFormats: <String, PdfPageFormat>{
                  'A3': PdfPageFormat.a3,
                  'Roll': PdfPageFormat.roll57,
                },
                build: (format) => _generatePdf(format, tokenQue, tokenCode),))```

--
    pdf.addPage(
      pw.Page(
        pageFormat: format,
```

**Expected behavior**
New formats are to be shown instead of defaults

**Screenshots**
![image](https://user-images.githubusercontent.com/1136350/106129537-58e75680-6186-11eb-9af5-3f08db63f697.png)

**Flutter Doctor**

$ flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.3.pre at /softwares/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rishisinghal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser - Chrome
 - [ ] Windows
 - [ ] Linux

**Additional context**
  pdf: ^2.0.0
  printing: ^4.0.0

**Comment by DavBfr** [comment]
That's because you have to set a default page format too. And the default value is A4 which does not exist in your list.

**Comment by rishisinghal** [comment]
Thanks a lot. Adding initialPageFormat fixed the issue
