### ISSUE TITLE
How do I stop text from overflowing in Table?

### ISSUE THREAD

**Issue by arpit-d** [DavBfr/dart_pdf#542]
How do I stop text from overflowing in table & instead of going out of document, go to the next line?
![Screenshot_20210129-151209821](https://user-images.githubusercontent.com/14919396/106259491-5435a780-6245-11eb-82bf-eb27c827573d.jpg)

**Comment by DavBfr** [comment]
You have to give it a maximum width.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
