### ISSUE TITLE
Where to find the Icon codes for the pdf Icons

### ISSUE THREAD

**Issue by Elelan** [DavBfr/dart_pdf#543]
Where can I find the Icon codepoint values? 
The material icon codes are not working correctly!
`pw.Icon(const pw.IconData(0xe90a))`

**Comment by DavBfr** [comment]
It depends on the icon file you use.
For this material icon set: https://github.com/google/material-design-icons/tree/master/font
use the file MaterialIcons-Regular.codepoints to find the right code.

**Comment by Elelan** [comment]
Thank you

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by chinmay2505** [comment]
@DavBfr , By putting your solution and also the same is mentioned by other users, I am not able to see the correct icon in the release mode of app although it works perfectly in debug mode.
Did you have any solution for this?

I am using Flutter SDK v1.22.6 and pdf: ^2.0.0
