### ISSUE TITLE
add the ability to embed audio and video files

### ISSUE THREAD

**Issue by rmgit** [DavBfr/dart_pdf#544]
**Is your feature request related to a problem? Please describe.**

PDF files can embed audio an video files. I didn't find a way to do that with this package. 

**Describe the solution you'd like**

Add the ability to embed audio and video files.

**Describe alternatives you've considered**

Not generating PDF but zipped htlm+media files but that's way less usable in many cases. 

**Additional context**

**Comment by DavBfr** [comment]
That's out of scope for multi-platform printing
