### ISSUE TITLE
PDF to Image wrong color

### ISSUE THREAD

**Issue by NighttCoder** [DavBfr/dart_pdf#546]
I am trying to save pages in pdf to image file. But sometimes I get wrong colors.
I am using - printing: ^4.0.0

PrintingInfo info = await Printing.info();
 print(info);
 canPrint: true
  directPrint: true
  dynamicLayout: false
  canConvertHtml: true
  canListPrinters: false
  canShare: true
  canRaster: true

==Code for conversion===

await for (final page
   in Printing.raster(filename.readAsBytesSync())) {
  var image = await page.toPng();
File(fileFullPath).writeAsBytesSync(image);
}

========
I also tried page.asImage , but no luck.

Any idea.

**Comment by DavBfr** [comment]
On what device are you experiencing that?

**Comment by NighttCoder** [comment]
This is happening in iPhone XS with 14.3 and iPad Pro(10.5inch with 14.2). Thanks.

**Comment by DavBfr** [comment]
Can you reproduce it with the simulator? I don't have an iOS device.

**Comment by NighttCoder** [comment]
Hi David,
Unfortunately I don't have the simulator setup working. Currently I am avoiding this problem by using a different plugin to get "PDF to Image" operation and use "printing" plugin for "Image to PDF".

Thanks for your support.

**Comment by DavBfr** [comment]
What plugin do you use for "PDF to Image"?

**Comment by NighttCoder** [comment]
I used native_pdf_renderer: ^2.4.0.

**Comment by DavBfr** [comment]
Can you try again, adding "context!." to the line 277 of printing/ios/Classes/PrintJob.swift

```swift
self.printing.onPageRasterized(printJob: self, imageData: context!.data, width: width, height: height)
```
