### ISSUE TITLE
margin issue while printing 

### ISSUE THREAD

**Issue by swash52125** [DavBfr/dart_pdf#549]
some margin issues are there in printing. while saving and sharing margin is perfect but while printing the margin is disbalanced. this problem is occuring while running your demo of invoice.  what may be the problem?

![Screenshot_20210202-141900](https://user-images.githubusercontent.com/43603447/106573527-de418100-6561-11eb-90d1-98cf1cf57755.jpg)
![Screenshot_20210202-141850](https://user-images.githubusercontent.com/43603447/106573626-fc0ee600-6561-11eb-9e54-3f3df6aa0f5f.jpg)

**Comment by DavBfr** [comment]
That's due to the printer you use. The printing library will return a pageFormat that matches the real printer margins. If you want to apply your own margins on top of that, you can use the method applyMargin on the pageFormat object to give the minimum margins you want.
