### ISSUE TITLE
Footer pageCount getting different value for each page

### ISSUE THREAD

**Issue by cetorres** [DavBfr/dart_pdf#55]
**Describe the bug**
When using MultiPage and, inside footer, trying to show the page number and total pages of the document, the context.pageCount variable is showing the total pages until the current page, not getting the whole number of pages of the document.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
footer: (Context context) {
    return Container(
         child: Text("Page ${context.pageNumber} of ${context.pagesCount}"),
    );
},
```
It shows on the first page: Page 1 of 1
On the second page: Page 2 of 2
On the third page: Page 3 of 3
And so on...

**Expected behavior**
It was supposed to show:
On the first page: Page 1 of 3
On the second page: Page 2 of 3
On the third page: Page 3 of 3
...

**Screenshots**

**Desktop (please complete the following information):**
 - [X] iOS
 - [X] Android
 - [ ] Browser

**Smartphone (please complete the following information):**
 - Device: Note 9, iPhone 6 and emulators
 - OS: Newest versions

**Additional context**
-

**Comment by DavBfr** [comment]
Yes, pageCount is just the number of pages currently processed. You have to guess the total number of pages, by using your heuristic or by generating the PDF 2 times.

**Comment by cetorres** [comment]
Oh.. I see. Guess I'll have to generate 2 times, because the number of pages can vary a lot, accordingly to the data. Do you have any ideas on how to improve this in the future? Thanks.

**Comment by cetorres** [comment]
Issue resolved. Thanks.
