### ISSUE TITLE
Dash Line

### ISSUE THREAD

**Issue by imakevirtual** [DavBfr/dart_pdf#551]
Please provide a Dash Line option for the horizontal and vertical dividers like the below package. Thank you.

https://pub.dev/packages/flutter_dash

**Comment by Derrick56007** [comment]
@DavBfr Any pointers on how to begin to implement this? I can try to tackle this when I get the time.

**Comment by DavBfr** [comment]
@Derrick56007 That should be fairly easy. You'll have to add the BorderStyle property to:
https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/src/widgets/basic.dart#L792 as well as HorizontalDivider and VerticalDivider

Then in the paint function, set the border style accordingly.

**Comment by imakevirtual** [comment]
@DavBfr @Derrick56007 Thanks a lot.

**Comment by Derrick56007** [comment]
@imakevirtual 
https://github.com/DavBfr/dart_pdf/pull/559 adds the borderStyle parameter to dividers
