### ISSUE TITLE
Can't use FutureBuilder in pdf screen?

### ISSUE THREAD

**Issue by yasinakca** [DavBfr/dart_pdf#552]
I would like to get data to pdf screen but can't accomplish it. pw object does not has FutureBuilder widget.

Also I couldn't be able to use Provider in pdf screen because there is no context in _build method? Can anyone help pls?

**Comment by DavBfr** [comment]
You can get your resources before creating the pdf, it's a one-time process, no need to update things when the user changes an option, you always have to recreate the full document from the beginning.
