### ISSUE TITLE
How to get the height of the container?

### ISSUE THREAD

**Issue by glennmichaelmejias** [DavBfr/dart_pdf#553]
Is it possible to get the height of the container? There is no key parameter on container widgets, which is suppose to be so it can get the renderbox;

**Comment by DavBfr** [comment]
If you use RenderBox in your app, something is wrong and you don't understand how Flutter works.

**Comment by glennmichaelmejias** [comment]
It's my client requirement.
Here is what I want to achieve,
I have four pictures, 2 rows and 2 columns all the same sizes, and I want that if there is only 1 picture, I want that it will still be the same size to those if four pictures and centered. I don't want to have it fixed sized value because the page is adjusting depending on the contents. So I want to get the size of the parent widget so that I can divide it and get the right value.

**Comment by DavBfr** [comment]
Then LayoutBuilder is your friend, both for Flutter and the Pdf widgets. Look at the doc/video here:
https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html

It will save you a lot of headaches with RanderBox.
