### ISSUE TITLE
getting "Don't import implementation files from another package" info warning on generated_plugin_registrant.dart

### ISSUE THREAD

**Issue by bsz0206** [DavBfr/dart_pdf#554]
Flutter for Android returns the following info warn on
"Don't import implementation files from another package" info warning on generated_plugin_registrant.dart

import 'package:printing/src/printing_web.dart';

**Expected behavior**
This is just an extra warning and harmless however strange that printing_web is used for Android implementation

**Flutter Doctor**
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.52.1)
[√] Connected device (3 available)

**Desktop (please complete the following information):**
 - [ X] Android

**Smartphone (please complete the following information):**
 - Flutteer Version 1.26.0-17.3.pre

**Comment by DavBfr** [comment]
If you have any idea on how to fix that, if it is fixable, let me know.

**Comment by DavBfr** [comment]
Fixed in printing-5.0.2
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
