### ISSUE TITLE
Cahnge color of table border? 

### ISSUE THREAD

**Issue by osamasado** [DavBfr/dart_pdf#556]
I 'm trying to change the color of the table by using this part of code 
`  border: pw.TableBorder(
                                horizontalInside: pw.BorderSide(width: 0.5, color: PdfColors.grey50),
                                verticalInside: pw.BorderSide(width: 0.5, color: PdfColors.grey50))`

It seems not to work, i hope that you can help me.
I know that i can use  **pw.Table.fromTextArray** and use **rowDecoration** attribute to change the border , but in my case i can't use it becuase i have some values that are not string.

**Comment by DavBfr** [comment]
That's fixed in the branch `stable-24`.
