### ISSUE TITLE
Landscape Pdf doesn't rotate in PdfPreview when device is in landscape mode

### ISSUE THREAD

**Issue by PandaGeek1024** [DavBfr/dart_pdf#557]
**Describe the bug**

As you can see from the screenshot when the device rotates the pdf still points down. Have to disable device rotation for it, which is not really what I want. Is there a way to show landscape horizontally in PdfPreview?
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-02-08 at 23 36 18](https://user-images.githubusercontent.com/3827781/107208898-0dc32280-6a67-11eb-95ca-157f3d8e92c6.png)

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pdf.PdfPageFormat pdfFormat = pdf.PdfPageFormat.a4.copyWith(
    marginTop: 1.0 * pdf.PdfPageFormat.cm,
    marginBottom: 1.0 * pdf.PdfPageFormat.cm,
    marginLeft: 1.0 * pdf.PdfPageFormat.cm,
    marginRight: 1.0 * pdf.PdfPageFormat.cm);

PdfPreview(
  initialPageFormat: pdfFormat,
  canChangePageFormat: false,
  build: (format) => generateMjraPdf(format, riskAssessment),
  pdfFileName: pdfFileName,
)
```

**Comment by DavBfr** [comment]
Why would it rotate with the device? You created the document like this.

**Comment by PandaGeek1024** [comment]
true. Then, is there a way to create a landscape page but shows horizontally? 

I'm finding two inconveniences with the current config
1. when creating the page as landscape, it always shows vertically unless you disable auto-rotation of the device. It is a bit inconvenient for the users.
2. When the landscape pdf is sent through email, the receiver still sees a vertical page unless he rotates it back so he can read. 

Would be great if we can somehow set it to be placed horizontally from the beginning.

**Comment by DavBfr** [comment]
Yes you have an orientation property on the page object

**Comment by PandaGeek1024** [comment]
![image](https://user-images.githubusercontent.com/3827781/107360478-dcb42200-6b3a-11eb-9117-2a9fede6e492.png)

I did set it as landscape, and it is placed vertically(which is hard to read)

![image](https://user-images.githubusercontent.com/3827781/107361001-914e4380-6b3b-11eb-9b74-32d0c10d8302.png)

Is there a way to keep the page as landscape but when showing it is placed horizontally?

**Comment by DavBfr** [comment]
try with `pageFormat.format.landscape`

**Comment by PandaGeek1024** [comment]
@DavBfr thanks, that does the trick!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by PandaGeek1024** [comment]
@DavBfr Sure my friend, enjoy the coffee.

**Comment by antoniosap** [comment]
enjoy

**Comment by luciano-cervantes** [comment]
Thanks @antoniosap, it really worked, but there is another very good parameter to generate PDF in landscape. `orientation: PageOrientation.landscape`
