### ISSUE TITLE
Hello i m testing the basic ,but i m getting file not found error

### ISSUE THREAD

**Issue by atta1234** [DavBfr/dart_pdf#558]
this is the error
FileSystemException (FileSystemException: Cannot open file, path = 'example.pdf' (OS Error: Read-only file system, errno = 30))

Future<void> pdff() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) => pw.Center(
          child: pw.Text('Hello World!'),
        ),
      ),
    );

    final file = File('example.pdf');
    await file.writeAsBytes(await pdf.save());
  }

**Comment by DavBfr** [comment]
It's a Flutter issue: you can't write files anywhere on a mobile device, you have to set the fill path to the documents directory, or somewhere else.

**Comment by atta1234** [comment]
> It's a Flutter issue: you can't write files anywhere on a mobile device, you have to set the fill path to the documents directory, or somewhere else.

Hello,how to save this file in document directory, i tried that path provider package but no luck

**Comment by DavBfr** [comment]
```dart
final output = await getTemporaryDirectory();
final file = File("${output.path}/example.pdf");
await file.writeAsBytes(await doc.save());
```
