### ISSUE TITLE
Table not being split between pages

### ISSUE THREAD

**Issue by cetorres** [DavBfr/dart_pdf#56]
**Describe the bug**
Table is not being split between pages. When it doesn't fit in one page, it's going in full to the next page.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Table table = Table.fromTextArray(context: context, data: contents);
```

**Expected behavior**
It was supposed to split its contents between the first page it was created and the next page, accordingly. Calculating the number of TableRows that will fit in the first page and plotting the rest of TableRows on the next page.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/533661/55893824-0c80f000-5b87-11e9-84c9-96e16eecc8d3.png)

**Desktop (please complete the following information):**
 - [X] iOS
 - [X] Android
 - [ ] Browser

**Comment by DavBfr** [comment]
Have you wrapped the table in another widget?

**Comment by cetorres** [comment]
Hi @DavBfr, yes, it's inside a Column. Because I'm using a header on top of each one table and there are more tables beneath it. So this whole list of headers and tables are inside a Column, that is inside the body of the page.

**Comment by cetorres** [comment]
Hum, I tested to add a Table directly inside the page body and it does the splitting.. The problem is that the tables are being created dynamically based on the data I'm passing. It can be many tables of items. How can I add them to the page body that way then? Without adding to another widget.

**Comment by DavBfr** [comment]
You can create the list of widgets before you create the MultiPage()

**Comment by cetorres** [comment]
Alright, I'll try. Thanks! Could you also take a look at the other issue I created about the pageCount, please? Thanks!

**Comment by cetorres** [comment]
Issue resolved. Thanks.

**Comment by DCubix** [comment]
> You can create the list of widgets before you create the MultiPage()

How?

**Comment by DCubix** [comment]
Table.fromTextArray requires a context, and I only get then in the MultiPage build. How can we create the widgets before the MultiPage()?
