### ISSUE TITLE
How to fit more than 20 pages?

### ISSUE THREAD

**Issue by mateusfmfm** [DavBfr/dart_pdf#560]
Hi!
I'm trying to generate this big text on emulator with the PDF package, using the code below. But it was returning "Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document."

What is wrong with my code? The parameter "header" is the title of the text and the "body" is the text of the screen.

`pdf.addPage(
      pw.MultiPage(
        pageFormat:
            PdfPageFormat.letter.copyWith(marginBottom: 1.5 * PdfPageFormat.cm),
        build: (pw.Context context) => <pw.Widget>[
          pw.Wrap(
            children: [
              pw.Container(
                child: pw.Column(
                  children: <pw.Widget>[
                    pw.Header(text: header, textStyle: myStyle),
                    pw.Text(body, textAlign: pw.TextAlign.left, style: myStyle),
                  ],
                ),
              ),
            ],
          )
        ],
      ),
    );`

![error](https://user-images.githubusercontent.com/44587544/107454412-bd61c880-6b2b-11eb-8e83-dbd13be605c1.jpg)

**Comment by DavBfr** [comment]
A Text widget is one leaf object and cannot be split into two pages, you have to generate multiple Text widgets with smaller text, one per paragraph for example each time you have a newline, create a new text object.

**Comment by mateusfmfm** [comment]
> 
> 
> A Text widget is one leaf object and cannot be split into two pages, you have to generate multiple Text widgets with smaller text, one per paragraph for example each time you have a newline, create a new text object.

Thank you @DavBfr. I will pay you a coffee.
