### ISSUE TITLE
Color attribute in Textstyle with alpha does not work!

### ISSUE THREAD

**Issue by osamasado** [DavBfr/dart_pdf#561]
I have tried to change th alpha of the color in textStyle by using:
` style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 35, color: PdfColor(1,1,1,0.3))))`

It has no effect on the color.

**Comment by DavBfr** [comment]
Yes, there are no alpha color support in Pdf. Use the Opacity() widget instead
