### ISSUE TITLE
Not an expected behaviour when specifying headerAlignment and cellAlignments in Table.fromTextArray

### ISSUE THREAD

**Issue by rithviknishad** [DavBfr/dart_pdf#564]
**Describe the bug**
When `headerAlignment` property and `cellAlignments` property is specified, `headerAlignment` is ignored and `cellAlignments` are used instead. To bypass this not expected behavior, one must use `headerAlignments` instead of `headerAlignment`, which seems to not be an efficient method.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  Widget buildInvoiceEntries(Context context) {
    return Table.fromTextArray(
      headerAlignment: Alignment.center,
      cellAlignments: {
        0: Alignment.center,
        1: Alignment.centerLeft,
        2: Alignment.center,
        3: Alignment.center,
        4: Alignment.center,
        5: Alignment.center,
        6: Alignment.center,
        7: Alignment.centerRight,
      },
    // ...
    );
  }
```

**Expected behavior**
All header cells to have alignment: `Alignment.center` regardless of what the `cellAlignments` are.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/107737656-ee5c1c00-6d2a-11eb-993d-a2ec482b2117.png)
The header of `col=7` is having `Alignment.centerRight` (same as the `cellAlignments[7]`), and not using the specified `headerAlignment` i.e., `Alignment.center`.

**Flutter Doctor**

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_IN)
    • Flutter version 1.24.0-10.2.pre at /home/coffeelake/development/flutter
    • Framework revision 022b333a08 (3 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/coffeelake/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • BKK LX2 (mobile) • --- • android-arm64  • Android 8.1.0 (API 27)
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```

**Platform**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: Huawei Honor 8C
 - OS: Android 8.1.0
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by DavBfr** [comment]
Just add this argument to fromTextArray: `headerAlignments: {},`

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
