### ISSUE TITLE
Use of PdfDocument.load

### ISSUE THREAD

**Issue by rirjkl19** [DavBfr/dart_pdf#565]
Upon reading the library implementations I came across an undocumented method which I think I need. `PdfDocument.load()`
I was able to use it by inheriting the `PdfDocumentParserBaseBase` to my `CustomPdfDocument`
```
Document document = pdfWidget.Document.load(CustomPdfDocument(pdfData));
```

But I failed to even load the pdf document.

What I wanted to do is open an existing pdf or at least have the pdf properties such as size. Is there any way for me to edit the pdf or at least get the actual size of the PDF? Thank you

**Comment by DavBfr** [comment]
I have a second package that implements PdfDocumentParserBase and encryption, digital signature. It's a commercial package. Drop me an email if you're interested.

**Comment by rirjkl19** [comment]
> I have a second package that implements PdfDocumentParserBase and encryption, digital signature. It's a commercial package. Drop me an email if you're interested.

Thank you for the reply! I have been enlightened by the answer you have provided and now understood its purpose. It made me rethink my objectives as the commercial package you offer is bit too much to my needs. But in case I reach an absolute limitation with this amazing package you have made, I may take up the offer and just email you.

 I'll be closing this thread. Thank you for everything you have contributed for the flutter community. You have my deepest respect.

**Comment by Hamdi-FAKHFAKH** [comment]
@rirjkl19 can you share with us the code?
thanks

**Comment by DavBfr** [comment]
@Hamdi-FAKHFAKH it's here: https://pub.nfet.net/pdf_crypto/

**Comment by moodstubos** [comment]
> Existing PDF modification, for adding pages, and updating existing pages.

Does this also allow you to add text to existing pages, for example, or just completely replace an existing page?

**Comment by DavBfr** [comment]
@moodstubos Yes you can also add text/images on top of an existing page, using the same Widget system. It creates a kind of layer on top of the page to draw whatever you want.

**Comment by moodstubos** [comment]
> @moodstubos Yes you can also add text/images on top of an existing page, using the same Widget system. It creates a kind of layer on top of the page to draw whatever you want.

Thx, order incomming....
