### ISSUE TITLE
how to fill page with empty rows?

### ISSUE THREAD

**Issue by wrjcs** [DavBfr/dart_pdf#566]
Hello,
I create invoice with pdf.Table, 
In the body of invoice, I want to fill the space with empty rows.
How could I do it?
![image](https://user-images.githubusercontent.com/7202194/108358582-2eba0f00-71ef-11eb-9cd9-5194d92e756a.png)

this image is I want:
![image](https://user-images.githubusercontent.com/7202194/108358692-53ae8200-71ef-11eb-987d-29b0010c647d.png)

Thanks.

**Comment by DavBfr** [comment]
I'm not sure that's possible with _MultiPage_ but with a standard _Page_, I'd try with:

```
Column
   Header
   Expanded
      Table
         TableRow
         TableRow
         TableRow
            Spacer
   Total
```

The last table row has just a spacer cell, to expand the size.
The _Expanded_ widget is used to layout the _Table_ as the last item, giving it a bounded constraints.

**Comment by wrjcs** [comment]
Thank you very much.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by jaykukadiya99** [comment]
Hello @DavBfr,

I had the same issue. I tried as per your message but it's not working for me.
![image](https://github.com/DavBfr/dart_pdf/assets/52033777/7af114f6-c804-43b0-8a04-e58a67461f64)

I am adding manualTable widget in the page
