### ISSUE TITLE
How to send pdf to a print specific directly?

### ISSUE THREAD

**Issue by wrjcs** [DavBfr/dart_pdf#567]
Hello,
How could I send an PDF file to a printer specific directly?
Without the pop page of system?

Thanks.

**Comment by DavBfr** [comment]
Yes, with iOS, Windows, Linux, and macOS. But not for Web and Android.

```dart
 Future<void> _printPdf(Uint8List data) async {
    final printers = await Printing.listPrinters();
    print(printers);
    await Printing.directPrintPdf(
        printer: printers.first, onLayout: (_) => data);
  }
```

data is your pdf file loaded by any means.

**Comment by wrjcs** [comment]
don't support android?

**Comment by DavBfr** [comment]
Direct print without dialog is not possible on Android.

**Comment by wrjcs** [comment]
Do you have solution for android?

**Comment by wrjcs** [comment]
My app run under Android.

**Comment by DavBfr** [comment]
It's just not possible, no API to do it.
