### ISSUE TITLE
Weird unicode error character in normal text

### ISSUE THREAD

**Issue by jeffaknine** [DavBfr/dart_pdf#568]
**Describe the bug**
Hi, first of all thank you for your package.
I'm having a character issue when rendering simple text.
I am importing and applying my theme with 
```
var myTheme = pw.ThemeData.withFont(
      base:
          pw.Font.ttf(await rootBundle.load("fonts/SourceSansPro-Regular.ttf")),
      bold: pw.Font.ttf(await rootBundle.load("fonts/SourceSansPro-Bold.ttf")),
      italic:
          pw.Font.ttf(await rootBundle.load("fonts/SourceSansPro-Italic.ttf")),
      boldItalic: pw.Font.ttf(
          await rootBundle.load("fonts/SourceSansPro-BoldItalic.ttf")),
);
final pdf = pw.Document(theme: myTheme);
```

But when I'm displaying the following text : 
```
RichText(
  text: TextSpan(
     text:
       "GAGNANT SUR 1300M À 1600M. TIMEFORM 131. DOUBLE GAGNANT DE GR.1 A 3 & 4ANS, invaincu et gagnant de Gr.2 à 2ans et Champion Européen à 3ans. Un superbe modèle et un pedigree irréprochable. ​ LE PLUS HAUT RATING POUR UN MILER EN EUROPE EN 2015. Valeur Timeform 131. Plus rapide que Frankel dans les Queen Anne Stakes Gr.1 et les Sussex Stakes Gr.1. ​ L’UNE DES MEILLEURS SOURCES DE GAGNANTS DE 2 ANS EN EUROPE. En 2020, ses meilleurs 2 ans sont TACTICAL, gagnant des July St. Gr.2 à Newmarket et des Windsor Castle St. LR durant Royal Ascot, ainsi que MOUILLAGE, second du Prix des Chênes Gr.3. ​ PÈRE DE 21 PERFORMERS BLACKTYPE dans le monde, et de 40% de gagnants par partants en Europe avec ses trois premières générations. EN EUROPE, ses 7 perfomers blacktype de 2020 incluent WASMYA, TORO STRIKE et WATAN. EN AUSTRALIE, ses meilleurs produits sont la gagnante de Gr.2 et placée Classique des Schweppes Oaks Gr.1  AFFAIR TO REMEMBER ainsi que la multiple gagnante de Stakes STILL A STAR.",
    style: TextStyle(
      color: primaryColor,
      fontSize: 8,
    ),
  ),
  maxLines: 14,
  softWrap: true,
);
```

I get weird characters :
Am i missing something ?
![IMG_FB8FF9BACBFC-1](https://user-images.githubusercontent.com/11058286/108511086-ad7e7d00-72bf-11eb-9cf7-bdfeb4ba3559.jpeg)

**Comment by DavBfr** [comment]
No issue in your code, just that you copy/paste the text and it has some strange Unicode characters:

<img width="592" alt="Screen Shot 2021-02-19 at 09 39 32" src="https://user-images.githubusercontent.com/1387855/108511621-8b243980-7296-11eb-8797-1990ed447d7f.png">

The font you use has no glyph to draw them, and fallback to the square.

**Comment by jeffaknine** [comment]
Thanks for your quick answer @DavBfr , is there a way to clean up the Unicode ? The text in coming from an TextField on the app.

**Comment by DavBfr** [comment]
if you iterate through the string, each codepoint is supposed to be a Unicode character, you should be able to find the wrong ones.

**Comment by jeffaknine** [comment]
Thanks @DavBfr, i found this ```replaceAll(RegExp(r'[^\x20-\x7E]'), '')``` which cleans it up perfectly!
