### ISSUE TITLE
Not able to load 2 images from at the same time

### ISSUE THREAD

**Issue by chirag-chopra** [DavBfr/dart_pdf#569]
**Describe the bug**

I am able to a image from assets. But the issue is that I am only able to load only 1 image at a time.

**To Reproduce**
Code snippet to reproduce the behavior:
image only shows in PDF if I try to place one image. But I want place both the images.

```dart
final pw.Image ganesha = await getLogoAsImage('lib/assets/ganesha.webp');
final pw.Image ascendantLord = await getLogoAsImage('lib/assets/zodic_signs/capricorn.webp');
```

**Expected behavior**

If it's working for one then it should work for both. Right?

**Screenshots**

It throws blank screen without any ERROR.

**Flutter Doctor**

```
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: Mi A3
 - OS: Android SDK 30

**Additional context**

Please look into this problem as soon as possible.

**Comment by DavBfr** [comment]
Seems to work correctly:

```dart
    final image1 = await networkImage('https://stock.flashmode.tn/wp-content/uploads/2020/06/nasa-logo-png-298.png');
    final image2 = await networkImage('https://upload.wikimedia.org/wikipedia/fr/thumb/3/3b/Logo_Carrefour.svg/120px-Logo_Carrefour.svg.png');

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.Center(
            child: pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
              children: [
                pw.Image(image1),
                pw.Image(image2),
              ],
            ),
          );
        },
      ),
    );
```

**Comment by chirag-chopra** [comment]
> Seems to work correctly:
> 
> ```dart
>     final image1 = await networkImage('https://stock.flashmode.tn/wp-content/uploads/2020/06/nasa-logo-png-298.png');
>     final image2 = await networkImage('https://upload.wikimedia.org/wikipedia/fr/thumb/3/3b/Logo_Carrefour.svg/120px-Logo_Carrefour.svg.png');
> 
>     pdf.addPage(
>       pw.Page(
>         pageFormat: format,
>         build: (context) {
>           return pw.Center(
>             child: pw.Column(
>               mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
>               children: [
>                 pw.Image(image1),
>                 pw.Image(image2),
>               ],
>             ),
>           );
>         },
>       ),
>     );
> ```

Can you please share **networkImage()** function? as it's says method not defined

**Comment by DavBfr** [comment]
It's here: https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/src/asset_utils.dart#L143

**Comment by chirag-chopra** [comment]
Current version of printing which is
 ` printing: ^4.1.0
`
does't have that functions I checked the recent commits. I found that that networkImage method recenetly commited but not released on PUB.DEV yet. Kindly give update. So that I could able to use it.

Thank you for your efforts.
God bless you

**Comment by DavBfr** [comment]
It's not published yet, but you can copy the relevant functions.
