### ISSUE TITLE
Scrambled text when printing PDF from some devices

### ISSUE THREAD

**Issue by madscs11** [DavBfr/dart_pdf#572]
**Describe the bug**

We are currently experiencing an issue where the text of our PDFs gets scrambled, but only when printing from specific devices. 

Our app can currently output PDF files and send them to a given user's email.
In some few cases users are experiencing that the text on the PDF looks scrambled when they print this file (I will attach an image of this below).

I can print it just fine from my Mac, Android and iOS devices with no issues at all, but a coworker reported that he gets the issue whenever he's printing from iPhone but not from his Mac.

Do you have any ideas of what could be causing this issue? Have you seen this issue before?

**To Reproduce**

We embed the font in the PDF like this:

```dart
latoItalic = pw.Font.ttf(
      await rootBundle.load('assets/fonts/Lato-Italic.ttf'),
    );
```

**Screenshots**

In Adobe Acrobat Reader DC under "File -> Properties -> Fonts" we can see the embedded fonts on the file.

![image](https://user-images.githubusercontent.com/49268074/108985788-bab9b400-7691-11eb-99b7-10ef8837e1fc.png)

Here you can see the scrambled text:

![image](https://user-images.githubusercontent.com/49268074/108985989-f48aba80-7691-11eb-9e4f-4022eaa71097.png)

**Comment by DavBfr** [comment]
No idea, maybe a printer driver problem.

**Comment by madscs11** [comment]
Hmpf... Thanks for the response, has something similar been reported before or has anyone else experienced something like this?

The printer in question would print the PDF just fine when sent from a Mac but not when sent from an iPhone. (Not sure if that was clear from the initial post)

**Comment by DavBfr** [comment]
No one experienced this. Can you try with another font?

**Comment by AllinGaming** [comment]
@DavBfr I have experienced this as well when sending from an iPhone but not from mac. Just wanted to notify

**Comment by AllinGaming** [comment]
@madscs11 This occurs for me too when printing with  HP LASERJET PRO MFP M283fdw. On other devices, I had no issue. I am very confused why this is happening exactly. If I print the same PDF from the mail app using AirPrint it prints it out normally, but if I do it through the app with AirPrint it comes out scrambled. Any thoughts on why this might be happening?

**Comment by Abdallah-al-hallak** [comment]
i am facing the same problem on android device

**Comment by RichardSV15** [comment]
Facing the same problem on iPhone devices.   Could it be a font issue? I am using OpenSans-Regular.ttf

**Comment by madscs11** [comment]
We ended up using another font as a workaround.

Would still be nice to be able to use all fonts, but oh well.

**Comment by RichardSV15** [comment]
Yes, I was also able to fix the issue on the IPhone using the pw.ThemeData.base() as the default theme/font.  It must be an issue with how the font is rendered
