### ISSUE TITLE
Overwrite the same PDF file even if it has a different Path

### ISSUE THREAD

**Issue by bichoalexis** [DavBfr/dart_pdf#573]
Hey! Im not Sure if this is a bug problem or Is something that im writing wrong.
I want to create different PDFs, the problem is that even though I change the path, a new file is created but I see the information of the first PDF created and add a blank sheet

**Comment by bichoalexis** [comment]
Here is the code:


> Uint8List archivoPDF;

>  archivoPDF = await pdfCreator();
>                     fullPath =
>                         "$pathSeleccionado/${controller.text}_${DateTime.now().toIso8601String()}.pdf";
>                     File file = File(fullPath);
> 
>                     await file.writeAsBytes(archivoPDF);
> 
>                     Navigator.pop(context);
>                     Navigator.push(
>                         context,
>                         MaterialPageRoute(
>                           builder: (context) =>
>                               PdfPreviewScreen(path: fullPath),
>                         ));

**Comment by DavBfr** [comment]
You have to create a new Document() object each time you want to create an empty document. If you reuse the object, it will just add a new page to it. Isn't it obvious?
