### ISSUE TITLE
Replacing the same pdf file

### ISSUE THREAD

**Issue by shahid31346** [DavBfr/dart_pdf#574]
**Describe the bug**

If a print a pdf file just only one page its working fine but if i print like two pages document its working fine, now the issue is if i print that first single page pdf document then the second page print will be added from that second print. any suggestions how to fix it
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
You have to create a Document() each time you want to create a new empty document.

**Comment by shahid31346** [comment]
Future<void> orderReceiptPrint(String title) async {
    var pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.only(left: 50, right: 0, top: 0, bottom: 0),
        build: (pw.Context context) => <pw.Widget>[
          pw.Wrap(
            children: [
              pw.Center(
                child: pw.Text(
                  Constants.restName,
                  textAlign: pw.TextAlign.center,
                  style: pw.TextStyle(fontSize: 50),
                ),
              ),

              pw.Container(height: 5),

              pw.Center(
                child: pw.Text(
                  Constants.restAddress,
                  textAlign: pw.TextAlign.center,
                  style: pw.TextStyle(fontSize: 30),
                ),
              ),

              pw.Container(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'order'.tr() + ' #${widget.orderNo}',
                    style: pw.TextStyle(fontSize: 28
                        //color:  pw.Colors.black87,
                        ),
                  ),
                  pw.Column(
                    children: [
                      pw.Text(
                        widget.orderReceivingTime,
                        style: pw.TextStyle(fontSize: 28
                            // color: Colors.black87,
                            ),
                      ),
                      pw.Text(
                        '(${widget.timeString})',
                        style: pw.TextStyle(fontSize: 22
                            // color: Colors.red,
                            ),
                      ),
                    ],
                  ),
                  pw.Text(
                    widget.orderPlacingTime,
                    style: pw.TextStyle(fontSize: 28
                        // color: Colors.black38,
                        ),
                  ),
                ],
              ),
              pw.SizedBox(
                height: 6,
              ),
              // pw.MySeparator(
              //     // color: Colors.grey
              //     ),
              pw.Divider(),
              pw.SizedBox(
                height: 6,
              ),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  widget.transactionBy == 'cash_on_delivery'
                      ? pw.Text(
                          'cash_on_delivery1'.tr(),
                          style: pw.TextStyle(fontSize: 28
                              // color: Colors.orange
                              ),
                        )
                      : pw.Text(
                          'card_payment1'.tr(),
                          style: pw.TextStyle(fontSize: 28
                              // color: Colors.green
                              ),
                        ),
                ],
              ),
              pw.SizedBox(height: 4),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                mainAxisAlignment: pw.MainAxisAlignment.start,
                children: widget.catDetails
                    .map((i) => pw.Wrap(
                          children: [
                            pw.Column(
                              crossAxisAlignment: pw.CrossAxisAlignment.start,
                              mainAxisAlignment: pw.MainAxisAlignment.start,
                              children: [
                                pw.Text(
                                  '${i.name}',
                                  style: pw.TextStyle(
                                    //fontWeight: FontWeight.w500,
                                    fontSize: 30,
                                    //color: Colors.black45
                                  ),
                                ),
                                pw.SizedBox(height: 8),
                                pw.Column(
                                  crossAxisAlignment:
                                      pw.CrossAxisAlignment.start,
                                  mainAxisAlignment: pw.MainAxisAlignment.start,
                                  children: i.orderDetails
                                      .map((i) => pw.Column(
                                            crossAxisAlignment:
                                                pw.CrossAxisAlignment.start,
                                            mainAxisAlignment:
                                                pw.MainAxisAlignment.start,
                                            children: [
                                              pw.Row(
                                                children: [
                                                  pw.Text(
                                                    '${i.quantity}x  ',
                                                    style: pw.TextStyle(
                                                        fontSize: 30
                                                        //color:    pw.Colors.black54,
                                                        ),
                                                  ),
                                                  pw.Text(
                                                    '${i.name}',
                                                    style: pw.TextStyle(
                                                        fontSize: 29
                                                        // color: Colors.black,
                                                        ),
                                                  ),
                                                ],
                                              ),

                                              pw.Padding(
                                                  padding:
                                                      const pw.EdgeInsets.only(
                                                          top: 2,
                                                          bottom: 2,
                                                          left: 22.0),
                                                  child: i.options.isNotEmpty
                                                      ? pw.Text(
                                                          i.options
                                                              .map(
                                                                  (o) => o.name)
                                                              .join(", "),
                                                          style: pw.TextStyle(
                                                              // color: Colors.black,
                                                              fontSize: 27),
                                                        )
                                                      : pw.Container()),
                                              pw.Container(height: 4),
                                              pw.Column(
                                                crossAxisAlignment:
                                                    pw.CrossAxisAlignment.start,
                                                children: i.extra
                                                    .map(
                                                      (e) => pw.Padding(
                                                          padding: const pw
                                                                  .EdgeInsets.only(
                                                              left: 22.0),
                                                          child: i.extra
                                                                  .isNotEmpty
                                                              ? pw.Text(
                                                                  '+ ${e.name}',
                                                                  style: pw.TextStyle(
                                                                      // color: Colors
                                                                      //     .black87,
                                                                      fontSize: 27),
                                                                )
                                                              : pw.Container()),
                                                    )
                                                    .toList(),
                                              ),
                                              pw.Container(
                                                height: 10,
                                              ),
                                              // const MySeparator(color: Colors.grey),
                                            ],
                                          ))
                                      .toList(),
                                ),
                              ],
                            ),
                          ],
                        ))
                    .toList(),
              ),

              pw.SizedBox(
                height: 10,
              ),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'status'.tr().toUpperCase(),
                    style: pw.TextStyle(fontSize: 28
                        // color: Colors.black54,
                        ),
                  ),
                  pw.Text(
                    orderStatus,
                    style: pw.TextStyle(
                        fontSize: 28,
                        // color: statusColor,
                        fontWeight: pw.FontWeight.bold),
                  ),
                ],
              ),
              pw.SizedBox(
                height: 10,
              ),
              pw.Divider(),
              // const pw.MySeparator(
              //     //color: Colors.grey
              //     ),
              pw.SizedBox(
                height: 10,
              ),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'subtotal'.tr().toUpperCase(),
                    style: pw.TextStyle(
                      fontSize: 28,
                      //color: Colors.black54,
                    ),
                  ),
                  pw.Text('${Constants.currency} ${widget.subtotal}',
                      style: pw.TextStyle(fontSize: 34)),
                ],
              ),
              pw.SizedBox(
                height: 10,
              ),

              widget.deliveryCharges != '0.00'
                  ? pw.Column(
                      children: [
                        pw.Divider(),
                        //  const MySeparator(color: Colors.grey),
                        pw.SizedBox(
                          height: 10,
                        ),
                        pw.SizedBox(
                          height: 10,
                        ),
                        // const MySeparator(color: Colors.grey),

                        pw.Row(
                          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                          children: [
                            pw.Text(
                              'delivery_charges'.tr().toUpperCase(),
                              style: pw.TextStyle(fontSize: 28
                                  // color: Colors.black54,
                                  ),
                            ),
                            pw.Text(
                                '${Constants.currency} ${widget.deliveryCharges}',
                                style: pw.TextStyle(fontSize: 34)),
                          ],
                        ),
                        pw.SizedBox(
                          height: 10,
                        ),
                      ],
                    )
                  : pw.Container(),
              pw.Divider(),
              pw.SizedBox(
                height: 10,
              ),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'totall'.tr().toUpperCase(),
                    style: pw.TextStyle(
                      fontSize: 26,
                      // color: Colors.black,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.Text(
                    '${Constants.currency} ${widget.total}',
                    style: pw.TextStyle(fontSize: 36),
                  ),
                ],
              ),
              pw.SizedBox(
                height: 10,
              ),

              pw.Divider(),
              // const MySeparator(color: Colors.grey),
              pw.SizedBox(
                height: 10,
              ),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(''),
                  pw.Text(
                    widget.deliveryType,
                    style: pw.TextStyle(
                        fontSize: 26,
                        // color: Colors.green,
                        fontWeight: pw.FontWeight.bold),
                  ),
                ],
              ),
              widget.status == '10'
                  ? pw.Column(
                      children: [
                        pw.Row(
                          children: [
                            pw.Text(
                              'statusr'.tr(),
                              textAlign: pw.TextAlign.center,
                              style: pw.TextStyle(fontSize: 24),
                            ),
                            pw.Text(
                              'rejectted'.tr(),
                              style: pw.TextStyle(fontSize: 24
                                  // color: Colors.red
                                  ),
                              textAlign: pw.TextAlign.center,
                            ),
                          ],
                        ),
                        pw.SizedBox(
                          height: 8,
                        ),
                        pw.Row(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          children: [
                            pw.Text(
                              'reason'.tr(),
                              // style: TextStyle(color: Colors.red),
                              textAlign: pw.TextAlign.center,
                              style: pw.TextStyle(fontSize: 24),
                            ),
                            pw.Text(
                              widget.rejectionReason,
                              style: pw.TextStyle(fontSize: 24
                                  //color: Colors.red
                                  ),
                              textAlign: pw.TextAlign.center,
                            ),
                          ],
                        ),
                      ],
                    )
                  : pw.Padding(
                      padding: const pw.EdgeInsets.only(top: 8.0),
                      child: pw.Container(),
                    ),
              // pw.Divider(
              //   // color:    pw.Constants.gradient2,
              //   thickness: 2,
              // ),
              pw.SizedBox(
                height: 25,
              ),

              pw.Center(
                child: pw.Text(
                  'thank_you'.tr(),
                  textAlign: pw.TextAlign.center,
                  style: pw.TextStyle(fontSize: 30),
                ),
              )

              // pw.SizedBox(height: 8),
            ],
          ),
        ],
      ),
    );

    // pdf.addPage(
    //   pw.Page(
    //     pageFormat: PdfPageFormat.a4,
    //     margin: pw.EdgeInsets.only(left: 50, right: 0, top: 0, bottom: 0),
    //     build: (context) {
    //       return
    //     },
    //   ),
    // );

    await Printing.layoutPdf(
   
        onLayout: (PdfPageFormat format) async => pdf.save());
  }

**Comment by shahid31346** [comment]
hi thank you for replying so quickly, this is my code i am generating the document each time, appreciated

**Comment by DavBfr** [comment]
Yes, onLayout is a callback that's called multiple times, so you have to create the pdf from zero each time.
Move all your pdf code generation inside the callback and you'll be fine.

**Comment by shahid31346** [comment]
Sorry i did not understand, can you show me how to do it, or elaborate a little bit thank you very much

**Comment by shahid31346** [comment]
Future<void> orderReceiptPrint(String title) async {
    var pdf = pw.Document();

    // pdf.addPage(
    //   pw.Page(
    //     pageFormat: PdfPageFormat.a4,
    //     margin: pw.EdgeInsets.only(left: 50, right: 0, top: 0, bottom: 0),
    //     build: (context) {
    //       return
    //     },
    //   ),
    // );
    Printing.layoutPdf(onLayout: (pageFormat) {
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: pw.EdgeInsets.only(left: 50, right: 0, top: 0, bottom: 0),
          build: (pw.Context context) => <pw.Widget>[
            pw.Wrap(
              children: [
                pw.Center(
                  child: pw.Text(
                    Constants.restName,
                    textAlign: pw.TextAlign.center,
                    style: pw.TextStyle(fontSize: 50),
                  ),
                ),

                pw.Container(height: 5),

                pw.Center(
                  child: pw.Text(
                    Constants.restAddress,
                    textAlign: pw.TextAlign.center,
                    style: pw.TextStyle(fontSize: 30),
                  ),
                ),

                pw.Container(height: 20),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'order'.tr() + ' #${widget.orderNo}',
                      style: pw.TextStyle(fontSize: 28
                          //color:  pw.Colors.black87,
                          ),
                    ),
                    pw.Column(
                      children: [
                        pw.Text(
                          widget.orderReceivingTime,
                          style: pw.TextStyle(fontSize: 28
                              // color: Colors.black87,
                              ),
                        ),
                        pw.Text(
                          '(${widget.timeString})',
                          style: pw.TextStyle(fontSize: 22
                              // color: Colors.red,
                              ),
                        ),
                      ],
                    ),
                    pw.Text(
                      widget.orderPlacingTime,
                      style: pw.TextStyle(fontSize: 28
                          // color: Colors.black38,
                          ),
                    ),
                  ],
                ),
                pw.SizedBox(
                  height: 6,
                ),
                // pw.MySeparator(
                //     // color: Colors.grey
                //     ),
                pw.Divider(),
                pw.SizedBox(
                  height: 6,
                ),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.end,
                  children: [
                    widget.transactionBy == 'cash_on_delivery'
                        ? pw.Text(
                            'cash_on_delivery1'.tr(),
                            style: pw.TextStyle(fontSize: 28
                                // color: Colors.orange
                                ),
                          )
                        : pw.Text(
                            'card_payment1'.tr(),
                            style: pw.TextStyle(fontSize: 28
                                // color: Colors.green
                                ),
                          ),
                  ],
                ),
                pw.SizedBox(height: 4),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  mainAxisAlignment: pw.MainAxisAlignment.start,
                  children: widget.catDetails
                      .map((i) => pw.Wrap(
                            children: [
                              pw.Column(
                                crossAxisAlignment: pw.CrossAxisAlignment.start,
                                mainAxisAlignment: pw.MainAxisAlignment.start,
                                children: [
                                  pw.Text(
                                    '${i.name}',
                                    style: pw.TextStyle(
                                      //fontWeight: FontWeight.w500,
                                      fontSize: 30,
                                      //color: Colors.black45
                                    ),
                                  ),
                                  pw.SizedBox(height: 8),
                                  pw.Column(
                                    crossAxisAlignment:
                                        pw.CrossAxisAlignment.start,
                                    mainAxisAlignment:
                                        pw.MainAxisAlignment.start,
                                    children: i.orderDetails
                                        .map((i) => pw.Column(
                                              crossAxisAlignment:
                                                  pw.CrossAxisAlignment.start,
                                              mainAxisAlignment:
                                                  pw.MainAxisAlignment.start,
                                              children: [
                                                pw.Row(
                                                  children: [
                                                    pw.Text(
                                                      '${i.quantity}x  ',
                                                      style: pw.TextStyle(
                                                          fontSize: 30
                                                          //color:    pw.Colors.black54,
                                                          ),
                                                    ),
                                                    pw.Text(
                                                      '${i.name}',
                                                      style: pw.TextStyle(
                                                          fontSize: 29
                                                          // color: Colors.black,
                                                          ),
                                                    ),
                                                  ],
                                                ),

                                                pw.Padding(
                                                    padding: const pw
                                                            .EdgeInsets.only(
                                                        top: 2,
                                                        bottom: 2,
                                                        left: 22.0),
                                                    child: i.options.isNotEmpty
                                                        ? pw.Text(
                                                            i.options
                                                                .map((o) =>
                                                                    o.name)
                                                                .join(", "),
                                                            style: pw.TextStyle(
                                                                // color: Colors.black,
                                                                fontSize: 27),
                                                          )
                                                        : pw.Container()),
                                                pw.Container(height: 4),
                                                pw.Column(
                                                  crossAxisAlignment: pw
                                                      .CrossAxisAlignment.start,
                                                  children: i.extra
                                                      .map(
                                                        (e) => pw.Padding(
                                                            padding: const pw
                                                                    .EdgeInsets.only(
                                                                left: 22.0),
                                                            child: i.extra
                                                                    .isNotEmpty
                                                                ? pw.Text(
                                                                    '+ ${e.name}',
                                                                    style: pw.TextStyle(
                                                                        // color: Colors
                                                                        //     .black87,
                                                                        fontSize: 27),
                                                                  )
                                                                : pw.Container()),
                                                      )
                                                      .toList(),
                                                ),
                                                pw.Container(
                                                  height: 10,
                                                ),
                                                // const MySeparator(color: Colors.grey),
                                              ],
                                            ))
                                        .toList(),
                                  ),
                                ],
                              ),
                            ],
                          ))
                      .toList(),
                ),

                pw.SizedBox(
                  height: 10,
                ),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'status'.tr().toUpperCase(),
                      style: pw.TextStyle(fontSize: 28
                          // color: Colors.black54,
                          ),
                    ),
                    pw.Text(
                      orderStatus,
                      style: pw.TextStyle(
                          fontSize: 28,
                          // color: statusColor,
                          fontWeight: pw.FontWeight.bold),
                    ),
                  ],
                ),
                pw.SizedBox(
                  height: 10,
                ),
                pw.Divider(),
                // const pw.MySeparator(
                //     //color: Colors.grey
                //     ),
                pw.SizedBox(
                  height: 10,
                ),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'subtotal'.tr().toUpperCase(),
                      style: pw.TextStyle(
                        fontSize: 28,
                        //color: Colors.black54,
                      ),
                    ),
                    pw.Text('${Constants.currency} ${widget.subtotal}',
                        style: pw.TextStyle(fontSize: 34)),
                  ],
                ),
                pw.SizedBox(
                  height: 10,
                ),

                widget.deliveryCharges != '0.00'
                    ? pw.Column(
                        children: [
                          pw.Divider(),
                          //  const MySeparator(color: Colors.grey),
                          pw.SizedBox(
                            height: 10,
                          ),
                          pw.SizedBox(
                            height: 10,
                          ),
                          // const MySeparator(color: Colors.grey),

                          pw.Row(
                            mainAxisAlignment:
                                pw.MainAxisAlignment.spaceBetween,
                            children: [
                              pw.Text(
                                'delivery_charges'.tr().toUpperCase(),
                                style: pw.TextStyle(fontSize: 28
                                    // color: Colors.black54,
                                    ),
                              ),
                              pw.Text(
                                  '${Constants.currency} ${widget.deliveryCharges}',
                                  style: pw.TextStyle(fontSize: 34)),
                            ],
                          ),
                          pw.SizedBox(
                            height: 10,
                          ),
                        ],
                      )
                    : pw.Container(),
                pw.Divider(),
                pw.SizedBox(
                  height: 10,
                ),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'totall'.tr().toUpperCase(),
                      style: pw.TextStyle(
                        fontSize: 26,
                        // color: Colors.black,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(
                      '${Constants.currency} ${widget.total}',
                      style: pw.TextStyle(fontSize: 36),
                    ),
                  ],
                ),
                pw.SizedBox(
                  height: 10,
                ),

                pw.Divider(),
                // const MySeparator(color: Colors.grey),
                pw.SizedBox(
                  height: 10,
                ),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(''),
                    pw.Text(
                      widget.deliveryType,
                      style: pw.TextStyle(
                          fontSize: 26,
                          // color: Colors.green,
                          fontWeight: pw.FontWeight.bold),
                    ),
                  ],
                ),
                widget.status == '10'
                    ? pw.Column(
                        children: [
                          pw.Row(
                            children: [
                              pw.Text(
                                'statusr'.tr(),
                                textAlign: pw.TextAlign.center,
                                style: pw.TextStyle(fontSize: 24),
                              ),
                              pw.Text(
                                'rejectted'.tr(),
                                style: pw.TextStyle(fontSize: 24
                                    // color: Colors.red
                                    ),
                                textAlign: pw.TextAlign.center,
                              ),
                            ],
                          ),
                          pw.SizedBox(
                            height: 8,
                          ),
                          pw.Row(
                            mainAxisAlignment: pw.MainAxisAlignment.center,
                            children: [
                              pw.Text(
                                'reason'.tr(),
                                // style: TextStyle(color: Colors.red),
                                textAlign: pw.TextAlign.center,
                                style: pw.TextStyle(fontSize: 24),
                              ),
                              pw.Text(
                                widget.rejectionReason,
                                style: pw.TextStyle(fontSize: 24
                                    //color: Colors.red
                                    ),
                                textAlign: pw.TextAlign.center,
                              ),
                            ],
                          ),
                        ],
                      )
                    : pw.Padding(
                        padding: const pw.EdgeInsets.only(top: 8.0),
                        child: pw.Container(),
                      ),
                // pw.Divider(
                //   // color:    pw.Constants.gradient2,
                //   thickness: 2,
                // ),
                pw.SizedBox(
                  height: 25,
                ),

                pw.Center(
                  child: pw.Text(
                    'thank_you'.tr(),
                    textAlign: pw.TextAlign.center,
                    style: pw.TextStyle(fontSize: 30),
                  ),
                )

                // pw.SizedBox(height: 8),
              ],
            ),
          ],
        ),
      );

      return pdf.save();
    });

    // await Printing.layoutPdf(

    //     onLayout: (PdfPageFormat format) async => pdf.save());
  }

**Comment by shahid31346** [comment]
i moved the code as you suggest still the same problem.

**Comment by DavBfr** [comment]
So I don't understand what's wrong. Your issue description is confusing.

**Comment by shahid31346** [comment]
When i installed the app and print two pages so its print two pages , the problem is now if i print 1 page so it will print two pages the first one will be the new content and the second page will be picked up from the first print, basically its replacing the content in  same pdf. I mean if the content of new print is short than the previous print so its will pick the remaining content from previous pdf.

**Comment by DavBfr** [comment]
@shahid31346 I don't see how this is possible.

I just tested with this code:

```dart
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() => runApp(const MyApp('Printing Demo'));

class MyApp extends StatelessWidget {
  const MyApp(this.title);

  final String title;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text(title)),
        body: Column(
          children: [
            TextButton(
              onPressed: () => Printing.layoutPdf(onLayout: _generatePdf),
              child: Text('One page'),
            ),
            TextButton(
              onPressed: () => Printing.layoutPdf(onLayout: _generatePdf1),
              child: Text('Two pages'),
            ),
          ],
        ),
      ),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        build: (context) => [pw.Text('Page')],
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> _generatePdf1(PdfPageFormat format) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        build: (context) => List<pw.Widget>.generate(
          200,
          (i) => pw.Text('Item $i'),
        ),
      ),
    );

    return pdf.save();
  }
}
```

It's all fine. Please give me a full standalone example I can run with no modifications if you still believe there is a bug in the library.
