### ISSUE TITLE
How can i load pdf from specified url ?

### ISSUE THREAD

**Issue by bobykurniawan11** [DavBfr/dart_pdf#575]

**Comment by DavBfr** [comment]
You mean like download a pdf from a web server?
=> Use the HTTP package.

**Comment by bobykurniawan11** [comment]
I just wonder, is it possible to "load" pdf file via internet ? so i need to download it first right ?

**Comment by DavBfr** [comment]
you'll have to download it first.

**Comment by bobykurniawan11** [comment]
ok thanks
