### ISSUE TITLE
Issues with Dart 2.12.0

### ISSUE THREAD

**Issue by ahorseman** [DavBfr/dart_pdf#580]
Hello,

after an upgrade to Dart 2.12.0 I noticed several issues. For instance, the usage of pw.BorderBox results in

`Abstract classes can't be instantiated.`
and it's not possible any more to add images using child:

```
          pw.Image(PdfImage.file(
            doc.document,
            bytes: image.image,
          ))

```
which results in an error

`The argument type 'PdfImage' can't be assigned to the parameter type 'ImageProvider*'.`

Is there any plans to updating dart_pdf for 2.12.0 soon, or do we have to account for staying on a legacy version for some time?

**Comment by DavBfr** [comment]
You can replace pw.BorderBox with pw.Border.
The former pw.BorderBox is deprecated for some time.

**Comment by fenchai23** [comment]
what about the pw.Image() widget? does it no longer work?
