### ISSUE TITLE
No implementation found for method convertHtml for Windows

### ISSUE THREAD

**Issue by pluzmedia** [DavBfr/dart_pdf#582]
We are glad to have support for Windows. We hit the road the block. Thanks in advance.

**Comment by kechankrisna** [comment]
Please add a method that can convert html to pdf.

**Comment by DavBfr** [comment]
Microsoft does not provide any API to convert HTML to PDF.

Maybe using Chrome:
https://github.com/puppeteer/puppeteer/blob/v8.0.0/docs/api.md#pagepdfoptions

**Comment by santhoshrao519** [comment]
Please add a method for converting html to pdf for flutter web, waiting...

**Comment by DavBfr** [comment]
@santhoshrao519 It's a new function to write in this file:
https://github.com/DavBfr/dart_pdf/blob/master/printing/windows/print_job.cpp

**Comment by santhoshrao519** [comment]
Thanks for replying, where should I add this code in my project? I have knowledge on flutter and Android only

**Comment by DavBfr** [comment]
You can fork this repo, and update the plugin. When done you can create a pull request.
