### ISSUE TITLE
Open File not Working after upgrade please update 

### ISSUE THREAD

**Issue by abdulrehmananwar** [DavBfr/dart_pdf#587]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

open file not working please update as soon as possible thanks

**Comment by DavBfr** [comment]
What are you talking about?

**Comment by abdulrehmananwar** [comment]
open_file work in debug mode when i build apk--release then open_file package not work . i am facing this issue since 2 months. please upgrade this package and remove this bug as soon as possible thanks.

**Comment by DavBfr** [comment]
Sorry, I'm not the author of the package open_file
