### ISSUE TITLE
Annotation in TextSpan not working

### ISSUE THREAD

**Issue by Doflatango** [DavBfr/dart_pdf#588]
**Describe the bug**
Annotation in TextSpan not working

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pw.RichText(
  text: pw.TextSpan(
    annotation: pw.AnnotationUrl('https://google.com'),
    children: [
      pw.TextSpan(text: 'Google'),
    ]
  ),
),
```

**Expected behavior**
Click the text should open an internet explorer.
I have tried `UrlLink` and it working as expected, does `Annotation` in `TextSpan` should working as well as `UrlLink`?

**Comment by DavBfr** [comment]
@Doflatango It's fixed in the master branch, can you try, adding this to your pubspec.yaml:

```dart
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf
```

**Comment by Doflatango** [comment]
@DavBfr Yes, it fixed now! Will you merge this fixed to branch `stable-24`? My app is not ready for `Null safety`, use 3.x version will cause dependencies conflict(such as image, crypto)

**Comment by DavBfr** [comment]
@Doflatango I don't plan to support the version stable-24
