### ISSUE TITLE
add image properties in BoxDecoration

### ISSUE THREAD

**Issue by kiko555** [DavBfr/dart_pdf#59]
**Describe the solution you'd like**
I want set image as background.
`decoration: BoxDecoration(
            image: DecorationImage(
                image: AssetImage("images/logo.png"), fit: BoxFit.cover)),`

**Comment by sueboy19** [comment]
Need same function BoxDecoration for pdf

**Comment by DavBfr** [comment]
Added in pdf version 1.3.9
