### ISSUE TITLE
Hello sir

### ISSUE THREAD

**Issue by atta1234** [DavBfr/dart_pdf#597]
i can see you have added the pie chart, i have upgraded the package in flutter ,but i don't know how to use that pie chart you have added can you please help, what set i should follow to achieved that, i installed the package from pub,

**Comment by DavBfr** [comment]
It's not published yet.

You can try it using this in your pubspec.yaml:

```dart
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf
```

**Comment by atta1234** [comment]
> It's not published yet.
> 
> You can try it using this in your pubspec.yaml:
> 
> ```dart
> dependency_overrides:
>   pdf:
>     git:
>       url: https://github.com/DavBfr/dart_pdf.git
>       ref: master
>       path: pdf
> ```

Hello sir did that, and copy the resport.dart page , but getting this error grid: pw.PieGrid(),     The function 'PieDataSet' isn't defined.

**Comment by DavBfr** [comment]
Try this:

```dart
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PdfPreview(build: (format) {
        final pdf = pw.Document();

        pdf.addPage(pw.Page(
          pageFormat: format,
          build: (context) => pw.Chart(
            grid: pw.PieGrid(),
            datasets: [
              pw.PieDataSet(value: 2, color: PdfColors.green),
              pw.PieDataSet(value: 2, color: PdfColors.purple),
              pw.PieDataSet(value: 2, color: PdfColors.orange),
            ],
          ),
        ));

        return pdf.save();
      }),
    );
  }
}
```

**Comment by atta1234** [comment]
that's worked many thanks sir,   i have only one issue now,    

for somereason , i want to show the data[0] above or one the side of chart as well, but it's return only ,so is thire is any easy hack,

i mean the chart is ok, but i want show the the title of value above on that chat in from dataset


 return pw.Column(children: [
          pw.SizedBox(
            height: 400,
            child: pw.Chart(
              title: pw.Text(
                'Income & Expenditure',
                style: pw.TextStyle(
                  color: baseColor,
                  fontSize: 20,
                ),
              ),
              grid: pw.PieGrid(),
              datasets:
                  List<pw.Dataset>.generate(dataTablincom.length, (index) {
                final data = dataTablincom[index];
                final color = chartColors[index % chartColors.length];
                final textColor =
                    color.luminance < 0.2 ? PdfColors.white : PdfColors.black;

                final value = (data[1] as num).toDouble();
                final pct = (value / incomexpenditure * 100).round();
                pw.Text('$data[0]',
                    style: pw.TextStyle(
                      color: color,
                      fontSize: 20,
                    ));
              return   pw.PieDataSet(
                  legend: '${data[0]}\n$pct%',
                  value: value,
                  color: color,
                  legendStyle: pw.TextStyle(fontSize: 10, color: textColor),
                );
              }),
            ),
          ),
        ]);
      },
    ),
  );

**Comment by DavBfr** [comment]
This is not implemented, feel free to implement it.
