### ISSUE TITLE
How to write List<Widget> in PDF

### ISSUE THREAD

**Issue by rohit0700** [DavBfr/dart_pdf#599]
First of all thank you so much for this package.. 

In my project I am facing a problem while adding List<Widget> in build.

for eg:
v0 is declared as a List of Widget type where I'm storing multiple widgets like containers and rows. 
List<Widget> v0=[] ;

Now I want to generate a pdf file from this v0 list. But while adding the list in build I'm getting the below mentioned error: 
Error: 
The argument type 'List<Widget> (where Widget is defined in C:\flutter\packages\flutter\lib\src\widgets\framework.dart)' can't be assigned to the parameter type 'List<Widget> (where Widget is defined in C:\flutter\.pub-cache\hosted\pub.dartlang.org\pdf-1.13.0\lib\widgets\widget.dart)'.

Code:
      build: (pw.Context context) => [
          // _contentDetails(context),
          pw.Center(
            child: pw.Column(
              children: v0
            )
          ),
          pw.SizedBox(height: 20)
        ]

Please guide me. How to generate a pdf from this List.

**Comment by DavBfr** [comment]
You cannot add Flutter's widgets, only widgets from the pdf package: prefixed with pw

So you have to recreate a widget list like `final v1 = <pw.Widget>[];`

**Comment by navrit** [comment]
Thanks for the package!

@DavBfr This seems sensible to include in the README.md since it's an easily resolvable and basic point which isn't immediately obvious.

**Comment by DavBfr** [comment]
@navrit Please write something would have needed as a beginner with this library. For me, it's too obvious.
You can update the README in a Pull Request.

**Comment by navrit** [comment]
@DavBfr I just noticed your examples in ([pdf/](https://github.com/DavBfr/dart_pdf/tree/master/pdf)). This is clear now, no need to change anything!
