### ISSUE TITLE
Error with example code when tapping on Print

### ISSUE THREAD

**Issue by aureliopetrone** [DavBfr/dart_pdf#6]
Hi, thanks for the plugin but i can't make it work. When tapping on the print button i get this error

> "Exception has occurred. PlatformException(error, java.util.ArrayList cannot be cast to byte[], null)".

Please, how can i solve this?

**Comment by DavBfr** [comment]
Do you have more information? It can be a lot of things.

**Comment by aureliopetrone** [comment]
This is the debug console output:


> E/MethodChannel#printing(14199): Failed to handle method call
> E/MethodChannel#printing(14199): java.lang.ClassCastException: java.util.ArrayList cannot be cast to byte[]
> E/MethodChannel#printing(14199): 	at net.nfet.flutter.printing.PrintingPlugin.onMethodCall(PrintingPlugin.java:76)
> E/MethodChannel#printing(14199): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
> E/MethodChannel#printing(14199): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
> E/MethodChannel#printing(14199): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#printing(14199): 	at android.os.MessageQueue.next(MessageQueue.java:325)
> E/MethodChannel#printing(14199): 	at android.os.Looper.loop(Looper.java:142)
> E/MethodChannel#printing(14199): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
> E/MethodChannel#printing(14199): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#printing(14199): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
> E/MethodChannel#printing(14199): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by DavBfr** [comment]
Fixed in printing 1.0.5
Thanks.

**Comment by aureliopetrone** [comment]
Thanks to you.
