### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.

### ISSUE THREAD

**Issue by srkakadiya** [DavBfr/dart_pdf#600]
Hey! I'm trying to achieve multiple pages in pdf I also used wrap widget, but it doesn't work.

[You can check my code via this URL](https://dpaste.org/EFiv)

Thank you! ;)

**Comment by berguisonpaiva** [comment]
Também usei o widget wrap, mas não funciona

**Comment by DavBfr** [comment]
@srkakadiya just read the documentation: 
https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html

**Comment by srkakadiya** [comment]
@DavBfr Thanks! For your reply, I already read. Can you tell me what I am missing in my code?

**Comment by DavBfr** [comment]
Each wrap has only one child and it happens that this child is bigger than a full page, therefore it can't be layout properly.

**Comment by srkakadiya** [comment]
Thank you! I solved it...
