### ISSUE TITLE
Pass data from TextField to another screen for pdf generation

### ISSUE THREAD

**Issue by alistairholmes** [DavBfr/dart_pdf#601]
Hi, 

I'm trying to generate an invoice based on user input.
I have a screen with some textfields where I can enter my name and some contact info. 
The data from the text field will be used to populate the pdf once i navigate to the preview screen.
Wanted to find out how I can implement this as I'm not sure how to transfer the data into the pdf.

Any help will be appreciated, thanks.

**Comment by DavBfr** [comment]
This is just State management questions:
https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple

**Comment by srkakadiya** [comment]
Hey! @DavBfr please answer my question, I issued 3 days ago and still you not give me an answer

**Comment by DavBfr** [comment]
@srkakadiya I did, 2 days ago.

**Comment by srkakadiya** [comment]
No, you don't [this is my issue link](https://github.com/DavBfr/dart_pdf/issues/600)

**Comment by alistairholmes** [comment]
@DavBfr thanks for the suggestion, I managed to get it working using the controller attribute in TextFieldForm and doing all the functionality from one class.
