### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by eaedev** [DavBfr/dart_pdf#602]
Hello,

Everytime I try to generate a pdf I get the same result: "I/flutter (11891): Times-Roman has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management". I tryed different fonts defined but I always get the same result.

I try to follow the site but I have no clue what I am doing wrong. Any help will be appreciated. Here is part of the code:

`import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

List<pw.Widget> pwestatutosBubbles = [];
final myFont = pw.Font.times();

Future savePdf() async {
    final pdf = pw.Document();

    pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pwestatutosBubbles; // Center
        }));

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/estatutos.pdf');
    await file.writeAsBytes(await pdf.save());}`

and text fields are defined as:

`
final pw.Widget pwtitulo = pw.Header(
                    level: 0,
                    child: pw.Text(element.data()['titulo'],
                        style: pw.TextStyle(font: myFont)),
                  );
pwestatutosBubbles.add(pwtitulo);
`

**Comment by DavBfr** [comment]
@eaedev it's just a warning, if you're fine with Latin characters, there is nothing more to do. If you want to use characters from Western Europe, or Asian languages, you'll have to use a true-type font file.
