### ISSUE TITLE
problem with table This widget created more than 20 pages. This may be an issue in the widget or the document.

### ISSUE THREAD

**Issue by Jliberatomex** [DavBfr/dart_pdf#603]
**Describe the bug**
 I have the problem when I try create a table 

  `   

         doc.addPage(   

             pw.MultiPage(
        
        pageFormat: PdfPageFormat.letter,
       margin: pw.EdgeInsets.all(20.0),
       crossAxisAlignment: pw.CrossAxisAlignment.start,
        //pageFormat: format,
        //pageFormat: PdfPageFormat.a4,
        //maxPages: 100,
        build: (pw.Context context)  => <pw.Widget>[
          
           pw.Wrap(
             
          children:<pw.Widget>[
            pw.Wrap(
             children: [
               pw.Row(
                 //mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                 mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                 children: <pw.Widget>[
                   pw.Align(
                    alignment: pw.Alignment.topLeft,
                   child: pw.Container(
                   child:pw.Image(profileImage,height: 50 ),
                   )
                 ),
                 pw.Align(
                   alignment: pw.Alignment.center,
                   child: pw.Container(
                     child:pw.Text('   ')
                   )
                 ),
                 
                 ]
               ),
               //pw.SizedBox(height: 20.0),
                 pw.Align(
                   alignment: pw.Alignment.center,
                   child: pw.Container(
                     child:pw.Text('Informe de resultados')
                   )
                 ),
               pw.SizedBox(height: 20.0),
               pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                    pw.Align(alignment:pw.Alignment.topLeft, child: pw.Container(child: pw.Text("Paciente: " +nombrePacie,style: pw.TextStyle(fontSize: 12.0,) ))),
                    pw.Container(child: pw.Text("Edad: " + edadP ,style: pw.TextStyle(fontSize: 12.0,) )),
                   // pw.Align(alignment: pw.Alignment.center, child: pw.Container(child: pw.Text("Medico: " + nombreDoc ,style: pw.TextStyle(fontSize: 12.0,) ))), 
                  
                  
                  ]

               ),
               pw.SizedBox(height: 20.0),
                 pw.Row(
                  //mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                 mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                    pw.Align(child: pw.Container(child: pw.Text("Medico: " + nombreDoc ,style: pw.TextStyle(fontSize: 12.0,) ))), 
                     pw.Align(alignment: pw.Alignment.center, child: pw.Container(child: pw.Text('   '))), 
                     pw.Align(alignment: pw.Alignment.center, child: pw.Container(child: pw.Text('   '))), 
                    
                  ]

               ),
               pw.SizedBox(height: 20.0),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                    pw.Align(
                    alignment:pw.Alignment.topLeft,
                    child:pw.Container(
                      child: pw.Text("Fecha Recepción: " + fechaRec ,style: pw.TextStyle(fontSize: 12.0, )  ))),
                    pw.Align(
                      alignment:pw.Alignment.topLeft,child: pw.Container(child: pw.Text("Hora Recepción: " + horaRec ,style: pw.TextStyle(fontSize: 12.0, )   ))),
                    
                  ],
                ),
                pw.SizedBox(height: 20.0),
                 pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                    pw.Align(alignment: pw.Alignment.topLeft, child: pw.Container(child: pw.Text("Fecha toma: " + fechaToma,style: pw.TextStyle(fontSize: 12.0) ))),
                    pw.Container(child: pw.Text("Hora Toma: " +horaToma,style: pw.TextStyle(fontSize: 12.0) )),
                  ],
                ),
                pw.SizedBox(height: 20.0),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                    pw.Container(child: pw.Text("Fecha Reporte: " + fechaRepo ,style: pw.TextStyle(fontSize: 12.0) )),
                    pw.Container(child: pw.Text("Hora Reporte: " +horaRepo,style: pw.TextStyle(fontSize: 12.0) )),
                  ],
                ),
                pw.SizedBox(height: 20.0),

                pw.Table.fromTextArray(
                    border: pw.TableBorder.all(),
                    cellAlignment: pw.Alignment.centerLeft,
                     headerDecoration: pw.BoxDecoration(
                   borderRadius: const pw.BorderRadius.all(pw.Radius.circular(2)),
                  // color: baseColor,
                 ),
                 headerHeight: 25,
                 cellHeight: 40,
                 cellAlignments: {
                    0: pw.Alignment.centerLeft,
                    1: pw.Alignment.center,
                    2: pw.Alignment.center,
                    3: pw.Alignment.center,
                 },
                /* headers: List<String>.generate(
                   tableHeaders.length, (col) => tableHeaders[0]
                  ), */
                  //data: List<List<String>>.generate(estudi.length, (row) => List<String>.generate(tableHeaders.length, (col) => estudi[row]))
                data: <List<String>>[
                  <String>[
                       'Elemento',
                       'Resultado',
                       'Unidades',
                       'Valores de referencia' 
                  ],
                  for(var res in estudi)
                    <String>[
                      res['elemento'],
                      res['resultado'],
                      res['unidades'],
                       res['valor']
                    
                    ]
                ]
                ),
                pw.SizedBox(height: 20.0),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                   // pw.Text('Analista de Laboratorio  '),
                    pw.Image(firmaImageAnalista,height: 40.0),
                    pw.Image(firmaResponsable, height: 40.0),
                  ]
                ),
                pw.SizedBox(height: 10.0),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                   // pw.Text('Analista de Laboratorio  '),
                    pw.Text('Analista de Laboratorio'),
                    pw.Text('Responsable Sanitario'),
                  ]
                ),
                pw.SizedBox(height: 5.0),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                   // pw.Text('Analista de Laboratorio  '),
                    pw.Text('L.B.G. Kharen Guardiola González'),
                    pw.Text('Dra. Ana Carolina Ramírez  Cazáres'),
                  ]
                ),
                pw.SizedBox(height: 5.0),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
                  children: <pw.Widget>[
                   // pw.Text('Analista de Laboratorio  '),
                    pw.Text('Cédula Profesional: 11230229'),
                    pw.Text('Cédula Profesional: 5737003'),
                  ]
                ),
             ]
          
          )
          ]
          )//cierre de wrap
        ]
        
      ),
    );`

**Comment by DavBfr** [comment]
If you remove the wrap widget it should work.
