### ISSUE TITLE
Printing freezes in iOS 14.4.1

### ISSUE THREAD

**Issue by arisbartee** [DavBfr/dart_pdf#605]
**Describe the bug**
The app freezes in the printing dialog.
The console prints out the following:
```
+[PKPrinter(PKPrinterPrivate) getAttributes:count:fromURI:]: Unable to connect to (null):443: No such file or directory
3
[tcp] tcp_input [C1.1:3] flags=[R] seq=3631601528, ack=0, win=0 state=CLOSING rcv_nxt=3631601529, snd_una=697519107
[tcp] tcp_input [C1.1:3] flags=[R] seq=3631601529, ack=0, win=0 state=CLOSING rcv_nxt=3631601529, snd_una=697519107

```

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
              format: format,
              html: html,
            ));
  }
```

**Expected behavior**
The ability to select a printer of cancel

**Flutter Doctor**
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

```
```

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.4.1

**Comment by DavBfr** [comment]
use `dynamicLayout = false` on your `Printing.layoutPdf`

**Comment by mhrst** [comment]
> use `dynamicLayout = false` on your `Printing.layoutPdf`

Can we get some more info about this in documentation? It's not clear what `dynamicLayout` does or why printing hangs without it on iOS 14. Maybe `dynamicLayout = false` should be the default?
