### ISSUE TITLE
Positioned.fill is not working

### ISSUE THREAD

**Issue by chirag-chopra** [DavBfr/dart_pdf#606]
I am facing an issue in implementing
```
Positioned.fill(
)
```

I checked the internal files of positioned, nothing is written related to 

> Positioned.fill

**Comment by DavBfr** [comment]
You can just use: `Positioned(left:0, top:0, right:0, bottom:0)` for the same result.

**Comment by DavBfr** [comment]
Implemented in pdf-3.2.0

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
