### ISSUE TITLE
Hello sir 

### ISSUE THREAD

**Issue by atta1234** [DavBfr/dart_pdf#607]
I need an other help from you, i need another sizebox just above the one,

where i only want to display the {data[0]}    value mean the the title of list, like salry bonus etc from the same dataset,
what the hack i need to do can you please guide it's the last issue, i need fix by the help you,

 return pw.Column(children: [

here i want i need the size box,

```
   pw.SizedBox(
            height: 650,
            child: pw.Chart(
              title: pw.Text(
                'Assets',
                style: pw.TextStyle(
                  color: baseColor,
                  fontSize: 20,
                ),
              ),
              grid: pw.PieGrid(),
              datasets:
                  List<pw.Dataset>.generate(dataTabassets.length, (index) {
                final data = dataTabassets[index];
                final color = chartColors[index % chartColors.length];
                final textColor =
                    color.luminance < 0.2 ? PdfColors.white : PdfColors.black;

                final value = (data[1] as num).toDouble();
                final pct = (value / assets * 100).round();

              i want to retur here somthing like text
               return pw.text($data[0]); with color 
            ),
```

          pw.SizedBox(
            height: 650,
            child: pw.Chart(
              title: pw.Text(
                'Assets',
                style: pw.TextStyle(
                  color: baseColor,
                  fontSize: 20,
                ),
              ),
              grid: pw.PieGrid(),
              datasets:
                  List<pw.Dataset>.generate(dataTabassets.length, (index) {
                final data = dataTabassets[index];
                final color = chartColors[index % chartColors.length];
                final textColor =
                    color.luminance < 0.2 ? PdfColors.white : PdfColors.black;

                final value = (data[1] as num).toDouble();
                final pct = (value / assets * 100).round();

                return pw.PieDataSet(
                  legend: '${data[0]}\n$pct%',
                  value: value,
                  color: color,
                  legendStyle: pw.TextStyle(fontSize: 10, color: textColor),
                );
              }),
            ),
          ),
        ]);
like any of this one
![pieeee](https://user-images.githubusercontent.com/30271205/112726028-0b485980-8f3d-11eb-8ce8-e3b06b4f2be2.PNG)

**Comment by DavBfr** [comment]
You can put the legend where you like. It's just a Widget.

pw.Chart(right: pw.ChartLegend(), .....)
