### ISSUE TITLE
Getting error while build  windows

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#609]
flutter build windows command throwing below error 

CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:23 (download_project)

**Comment by DavBfr** [comment]
Looks like you don't have internet access to download the dlls.
