### ISSUE TITLE
Center align the text inside a container

### ISSUE THREAD

**Issue by arazinger** [DavBfr/dart_pdf#61]
Is there any way to properly center the text inside a container?

Say we have a code like this:
```dart
Container(
      width: 50.0,
      height: 50.0,
      color: PdfColors.grey,
      child: Center(
        child: Text('X',
            style: Theme.of(context).header0),
      ),
    )
```
When using custom font (in my case:  https://fonts.google.com/specimen/Quicksand), text doesn't get centered.

See screenshot below.

<img width="130" alt="center_text" src="https://user-images.githubusercontent.com/6533512/56389984-2a0b2500-622b-11e9-9ded-7906090a423e.png">

**Comment by DavBfr** [comment]
Please test the latest version

**Comment by arazinger** [comment]
Thanks, it works as intended now.

Keep up doing great work!
