### ISSUE TITLE
How to display material icons

### ISSUE THREAD

**Issue by schechtere** [DavBfr/dart_pdf#611]
Thanks first for providing this library.

I've been trying, without much success, to display material icons on a pdf page.

This does not compile

      viewModel.csData.isolation
          ? pdf.Icon(material.Icons.ac_unit)
          : pdf.Icon(material.Icons.ac_unit))

Because the pdf IconData type is different from the material IconData Type,

and this

      viewModel.csData.isolation
          ? pdf.Icon(pdf.IconData(material.Icons.ac_unit.codePoint))
          : pdf.Icon(pdf.IconData(material.Icons.ac_unit.codePoint))

compiles but blows up.  I suspect I need to specify the Material font, but am not sure how to.  Have played around with font parameter and with IconThemes, but haven't hit on the answer.

**Comment by schechtere** [comment]
Ok, found a couple of other answers and resolved this.  First of all, flutter app.

Should anyone else stumble across this:

Downloaded MaterialIcons-Regular.ttf from https://github.com/google/material-design-icons/tree/master/font,
Put this in folder asset/fonts under the project base,
Defined assets: --asset/fonts/ in pubspec.yaml
Called
     final materialIcons = await rootBundle.load("assets/fonts/MaterialIcons-Regular.ttf");
     final materialFont = pdf.Font.ttf(materialIcons);
in code that wrapped my widget that generates the pdf,
Added materialFont as a parameter to the widget
drew icons like:

      pdf.Row(children: [
        pdf.Text('Isolation of Truck/Trailer with Lockout/Tagout'),
        // codes from https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints
        viewModel.csData.isolation
            ? pdf.Icon(pdf.IconData(0xe5ca), font: materialFont)
            : pdf.Icon(pdf.IconData(0xe835), font: materialFont),
      ]),

The codes are contained in the .codepoints files in the download link mentioned above.

----------------------

My only question:  doesn't feel like I should need to import the file separately.  Flutter already is able to draw the Icons, and I should probably be able to pull from same fonts as these reference.  If obvious answer would be glad to hear it, but looks like I'm in business.

**Comment by chinmay2505** [comment]
@schechtere , By putting your solution and also the same is mentioned by other users, I am not able to see the correct icon in the release mode of app although it works perfectly in debug mode.
Did you also face a similar issue?

**Comment by DavBfr** [comment]
> My only question: doesn't feel like I should need to import the file separately. Flutter already is able to draw the Icons, and I should probably be able to pull from same fonts as these reference. If obvious answer would be glad to hear it, but looks like I'm in business.

Yes, Flutter already has the material font file, but they don't provide any way to get access to the font, so the pdf library can't read it. Also they will tree-shake the file and remove all unused glyfs, but will not detect the icons used by this library.
