### ISSUE TITLE
How to display AssetImage in PDF?

### ISSUE THREAD

**Issue by MuhammadAliKust** [DavBfr/dart_pdf#614]
Hi Dav,
I want to add asset Image in PDF flutter, but dont know how to add it, Kindly help me in this regard.
Thanks

**Comment by DavBfr** [comment]
It's on the README here:
https://github.com/DavBfr/dart_pdf/tree/master/printing#examples

```dart
final image = await imageFromAssetBundle('assets/image.png');

doc.addPage(pw.Page(
    build: (pw.Context context) {
      return pw.Center(
        child: pw.Image(image),
      ); // Center
    })); // Page
```
