### ISSUE TITLE
Flutter web listPrinters() method not worked (unimplemented)

### ISSUE THREAD

**Issue by kkumarvaghela08** [DavBfr/dart_pdf#615]
**Describe the bug**

**To Reproduce**
List<Printer> arrPrinters = await Printing.listPrinters();
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

[✓] Flutter (Channel stable, 2.0.3, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/imac/Downloads/Apps/flutter
    • Framework revision 4d7946a68d (12 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    ! Xcode 11.5.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [* ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari] - Chrome

**Additional context**

**Comment by kkumarvaghela08** [comment]
Flutter web listPrinter() method not worked (unimplemented)

**Comment by DavBfr** [comment]
It's not a bug, a web browser can't list the printers, no API for that.

**Comment by kkumarvaghela08** [comment]
So, how can i print without chrome print popup dialog ?

**Comment by DavBfr** [comment]
That's impossible, have you ever seen a website printing without user interaction?

**Comment by kkumarvaghela08** [comment]
ok ok thanks for support
