### ISSUE TITLE
Unable to add color to SvgImage. It will be great you add color attributes in SvgImage class.

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#618]
It will be very useful when we want to change the template theme color with it's SVG images. 
Example:
1. Changing assets/resume.svg color dynamically. OR
2. Changing this [DART_PDF_SVG_ICONS](https://github.com/DavBfr/dart_pdf/blob/master/test/golden/widgets-icons.pdf) color dynamically. OR
3. Or the last option, can we change png icon color according to the theme color dynamically?

class SvgImage extends Widget {
      factory SvgImage({
        @required String svg,
        BoxFit fit = BoxFit.contain,
        Alignment alignment = Alignment.center,
        bool clip = true,
        double width,
        double height,
      }) {
        assert(clip != null);
        assert(alignment != null);

        final xml = XmlDocument.parse(svg);
        final parser = SvgParser(xml: xml);

        return SvgImage._fromParser(
          parser,
          fit,
          alignment,
          clip,
          width,
          height,
        );
      }

**Comment by jazzbpn** [comment]
I just wan to know, 
1. Do you have any plans to work on this svg-image icons color attributes?
2. I found that we can use the [Icon data](https://github.com/DavBfr/dart_pdf/issues/543) to display icons where we can change the color attributes. But, lots of google icons are not supported. So, any plans to work on icon-data feature which support all this [google icons](https://fonts.google.com/icons) .

**Comment by DavBfr** [comment]
Yes, the master branch on GitHub has SvgImage with a colorFilter attribute already.

**Comment by jazzbpn** [comment]
So, Can we change the SVG icons color dynamically using that this?

**Comment by DavBfr** [comment]
Yes!

**Comment by jazzbpn** [comment]
Waao!! Thank you so much.

**Comment by jazzbpn** [comment]
@DavBfr I just want to know, Do we need to load all SVG icons before we call doc.addPage(...) like 
 ` final bgShape = await rootBundle.loadString('assets/resume.svg');  `?

Let's say, we have large dynamic json object that includes many icons in it's sub hierarchy of the child json object. Do we need to get all the svg icons path and load all icons before calling doc.addPage(...) or there are some other options?

**Comment by DavBfr** [comment]
Yes, you have to load them all before. They stay in memory anyway and are rendered when calling `pdf.save()`
