### ISSUE TITLE
Windows desktop - Printing - No Margin

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#619]
Hi, i'm using this plugin in windows desktop to print pdf  using printing plugin.

In my pdf there is no margin but after printing, in a paper is coming with margin.
how to solve this.

**Comment by DavBfr** [comment]
That's because your printer has physical margins where it can't print.

**Comment by selvam920** [comment]
Then how to override the default margin, i need zero margin in page setup

**Comment by DavBfr** [comment]
force a PdfPageFormat with no margins when you create your pages.

**Comment by selvam920** [comment]
i used format: PdfPageFormat.undefined, still default margin taken in the printer,
can you provide sample code to override
