### ISSUE TITLE
Esc/POS or Direct send to printer (Other than PDF)

### ISSUE THREAD

**Issue by mjafartp** [DavBfr/dart_pdf#620]
need option to send esc/pos commands or byte data directly  send to printer, for Esc/POS Printing.

**Comment by DavBfr** [comment]
Try this: https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin

**Comment by mjafartp** [comment]
This can do only for printing. 

in esc/pos we have to send commands like dishdrawer open, Beep on printer, Cut Paper Etc..

all this commands send by bytes.

**Comment by mjafartp** [comment]
Add a function to send bytes directly to printer.

**Comment by DavBfr** [comment]
@mjafartp use a dedicated plugin for ESC/POS. This plugin is designed to print using the OS print spooler.

**Comment by fabiodrs** [comment]
@mjafartp did you manage how to send ESC/POS directly to usb printer?
