### ISSUE TITLE
PdfPreview not showing fonts on linux

### ISSUE THREAD

**Issue by zigapk** [DavBfr/dart_pdf#623]
**Describe the bug**
When using PdfPreview on linux, all the text is missing in some pdf files. However, some other features features like lines remain visible. For example:
- [This file](http://africau.edu/images/default/sample.pdf) works fine.
- [Latex pdf sample](http://mathlab.cit.cornell.edu/support/latex/sample/sample.pdf) is missing all the text.

I suspect this is an issue with missing font files, but can't find any documentation regarding this issue.

The same files work fine on web.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
final ByteData doc = await rootBundle.load('assets/asdf.pdf');
PdfPreview(
    build: (context) => doc.buffer.asUint8List(),
),
```

**Expected behavior**
All text should be visible. If there is a font missing, I'd expect to receive some kind of error or warning message.

**Screenshots**
![image](https://user-images.githubusercontent.com/5074514/113484099-e2791480-94a6-11eb-8e04-6e4869efc2bf.png)

**Flutter Doctor**
```
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-12.1.pre at /opt/flutter
    • Framework revision 8264cb3e8a (3 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/zigapk/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /opt/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

**Desktop:**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [x] Linux

Tested on Ubuntu 20.10 and Arch Linux.

**Comment by DavBfr** [comment]
On Linux and Windows, it's using Google's Pdfium library, maybe an issue there.

**Comment by Y0ngg4n** [comment]
@DavBfr I see you did commented on the Google Pdfium Library and it did worked for mara004. Do you already worked out why this happens?

**Comment by DavBfr** [comment]
No, I don't understand what's wrong. Maybe some incompatibilities with the way Flutter configures the environment.
Let me know if you find more information.
