### ISSUE TITLE
PDF Multipage

### ISSUE THREAD

**Issue by softplace-io** [DavBfr/dart_pdf#624]
Hello, 
for some reason i can't create continuation of pages.
Not work...

`import 'dart:io';

import 'package:flutter/services.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

Future generatePDF(double subtotal, String selectedTypePayment, String ctlCep, String ctlAddress, String ctlDistrict, String ctlCityCountry, String ctlNumber, String ctlReferencePoint, String ctlPhone_1, String ctlPhone_2) async {
  // # PDF DOC
  pw.Document pdfDoc;
  pdfDoc = pw.Document();
  print('Situação do PDF: $pdfDoc');

  // # DATA & HORA
  DateTime dateHourNow = DateTime.now();

  // # LOGO DA EMPRESA
  ByteData bytes = await rootBundle.load('assets/soon/002.png');
  final logoPDF = PdfImage.file(
    pdfDoc.document,
    bytes: bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes),
  );

  // # CRIAR PÁGINA DO PDF
  pdfDoc.addPage(
    pw.MultiPage(
      // MARGENS DO PDF
      pageFormat: PdfPageFormat.a4.copyWith(
        marginLeft: 0.5 * PdfPageFormat.cm,
        marginRight: 0.5 * PdfPageFormat.cm,
        marginTop: 0.5 * PdfPageFormat.cm,
        marginBottom: 0.5 * PdfPageFormat.cm,
      ),
      // CORPO DO PDF
      build: (context) => [
        pw.ListView(
          children: <pw.Widget>[
            pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.start,
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  decoration: pw.BoxDecoration(
                    border: pw.BoxBorder(
                      top: true,
                      bottom: true,
                      left: true,
                      right: true,
                    ),
                  ),
                  width: double.infinity,
                  child: pw.Padding(
                    padding: pw.EdgeInsets.fromLTRB(10, 10, 10, 0),
                    child: pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.start,
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Image(logoPDF),
                        pw.Padding(
                          padding: pw.EdgeInsets.fromLTRB(5, 5, 5, 0),
                          child: pw.Column(
                            mainAxisAlignment: pw.MainAxisAlignment.start,
                            crossAxisAlignment: pw.CrossAxisAlignment.start,
                            children: <pw.Widget>[
                              pw.Text(
                                'Bomboniere Leão',
                                textAlign: pw.TextAlign.left,
                              ),
                              pw.Text(
                                'CNPJ: XX.XXX.XXX/XXXX-XX',
                                textAlign: pw.TextAlign.left,
                              ),
                              pw.Text(
                                'Contato: (XX) XXXX-XXXX',
                                textAlign: pw.TextAlign.left,
                              ),
                              pw.Text(
                                'Endereço: XXXXX',
                                textAlign: pw.TextAlign.left,
                              ),
                              pw.Text(
                                'CEP: XXXXX-XXX',
                                textAlign: pw.TextAlign.left,
                              ),
                              pw.Text(
                                "Maceió/AL",
                                textAlign: pw.TextAlign.left,
                              ),
                              pw.SizedBox(
                                height: 15,
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
            // INFORMACOES DO FUNCIONARIO
            pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.start,
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  width: double.infinity,
                  decoration: pw.BoxDecoration(
                    border: pw.BoxBorder(
                      top: true,
                      bottom: true,
                      left: true,
                      right: true,
                    ),
                  ),
                  child: pw.Padding(
                    padding: pw.EdgeInsets.fromLTRB(10, 10, 10, 10),
                    child: pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.start,
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Padding(
                          padding: pw.EdgeInsets.fromLTRB(5, 5, 5, 5),
                          child: pw.Column(
                            mainAxisAlignment: pw.MainAxisAlignment.start,
                            crossAxisAlignment: pw.CrossAxisAlignment.start,
                            children: <pw.Widget>[
                              pw.Text('Hora do Pedido: ' + dateHourNow.toString()),
                              pw.Row(children: <pw.Widget>[
                                pw.Text('Pagamento: '),
                                pw.Text(selectedTypePayment, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                              ]),
                              pw.Text('CEP: ' + ctlCep),
                              pw.Text('Endereço: ' + ctlAddress + ', Nº ' + ctlNumber),
                              // pw.Text('Número: ' + ctlNumber),
                              pw.Text('Ponto de Referência: ' + ctlReferencePoint),
                              pw.Text('Bairro: ' + ctlDistrict),
                              pw.Text('Cidade: ' + ctlCityCountry),
                              pw.Text('Contato 1: ' + ctlPhone_1),
                              pw.Text('Contato 2: ' + ctlPhone_2),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
            // COMPETENCIA
            pw.Container(
              width: double.infinity,
              padding: pw.EdgeInsets.all(10),
              alignment: pw.Alignment.center,
              decoration: pw.BoxDecoration(
                border: pw.BoxBorder(
                  top: true,
                  bottom: true,
                  left: true,
                  right: true,
                ),
              ),
              child: pw.Column(
                children: [
                  pw.Text('LISTA DE PRODUTOS'),
                ],
              ),
            ),
            // INFORMACOES DO CONTRACHEQUE
            pw.Container(
              height: 450,
              padding: pw.EdgeInsets.all(8),
              decoration: pw.BoxDecoration(
                border: pw.Border(
                  top: pw.BorderSide(width: 1.0),
                  bottom: pw.BorderSide(width: 1.0),
                  left: pw.BorderSide(width: 1.0),
                  right: pw.BorderSide(width: 1.0),
                ),
              ),
              child: pw.Row(
                children: [
                  // # CONTADOR
                  pw.Container(
                    width: 35,
                    decoration: pw.BoxDecoration(border: pw.Border(right: pw.BorderSide(width: 1.0))),
                    child: pw.Column(
                      children: [
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          crossAxisAlignment: pw.CrossAxisAlignment.center,
                          children: <pw.Widget>[
                            pw.Text(
                              'Nº',
                              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                            ),
                            pw.Divider(indent: 5.0, endIndent: 10.0, thickness: 2.5),
                          ],
                        ),
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          crossAxisAlignment: pw.CrossAxisAlignment.center,
                          children: productCount(),
                        ),
                      ],
                    ),
                  ),

                  // # PRODUTO
                  pw.Container(
                    width: 225,
                    padding: pw.EdgeInsets.only(left: 10),
                    decoration: pw.BoxDecoration(border: pw.Border(right: pw.BorderSide(width: 1.0))),
                    child: pw.Column(
                      mainAxisAlignment: pw.MainAxisAlignment.start,
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          crossAxisAlignment: pw.CrossAxisAlignment.center,
                          children: <pw.Widget>[
                            pw.Text('Produto', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                            pw.Divider(indent: 5.0, endIndent: 10.0, thickness: 2.5),
                          ],
                        ),
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.start,
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: productName(),
                        ),
                      ],
                    ),
                  ),

                  // # PRECO
                  pw.Container(
                    width: 50,
                    decoration: pw.BoxDecoration(border: pw.Border(right: pw.BorderSide(width: 1.0))),
                    child: pw.Column(
                      children: [
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          crossAxisAlignment: pw.CrossAxisAlignment.center,
                          children: <pw.Widget>[
                            pw.Text(
                              'Peso',
                              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                            ),
                            pw.Divider(indent: 5.0, endIndent: 10.0, thickness: 2.5),
                          ],
                        ),
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.start,
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: productSize(),
                        ),
                      ],
                    ),
                  ),

                  // # QUANTIDADE
                  pw.Container(
                    width: 50,
                    decoration: pw.BoxDecoration(border: pw.Border(right: pw.BorderSide(width: 1.0))),
                    child: pw.Column(
                      children: [
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          crossAxisAlignment: pw.CrossAxisAlignment.center,
                          children: <pw.Widget>[
                            pw.Text(
                              'Qtd.',
                              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                            ),
                            pw.Divider(indent: 5.0, endIndent: 10.0, thickness: 2.5),
                          ],
                        ),
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.start,
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: productQuantity(),
                        ),
                      ],
                    ),
                  ),

                  // # PRECO
                  pw.Container(
                    width: 85,
                    decoration: pw.BoxDecoration(border: pw.Border(right: pw.BorderSide(width: 1.0))),
                    child: pw.Column(
                      children: [
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          crossAxisAlignment: pw.CrossAxisAlignment.center,
                          children: <pw.Widget>[
                            pw.Text(
                              'Preço Unit.',
                              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                            ),
                            pw.Divider(indent: 5.0, endIndent: 10.0, thickness: 2.5),
                          ],
                        ),
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.start,
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: productPrice(),
                        ),
                      ],
                    ),
                  ),

                  // # SUBTOTAL
                  pw.Container(
                    width: 85,
                    decoration: pw.BoxDecoration(border: pw.Border(right: pw.BorderSide(width: 1.0))),
                    child: pw.Column(
                      children: [
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.center,
                          crossAxisAlignment: pw.CrossAxisAlignment.center,
                          children: <pw.Widget>[
                            pw.Text(
                              'Subtotal',
                              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                            ),
                            pw.Divider(indent: 5.0, endIndent: 10.0, thickness: 2.5),
                          ],
                        ),
                        pw.Column(
                          mainAxisAlignment: pw.MainAxisAlignment.start,
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: productPriceSub(),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            // # TOTAL
            pw.Container(
              padding: pw.EdgeInsets.symmetric(vertical: 10),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: <pw.Widget>[
                  pw.Row(
                    children: <pw.Widget>[
                      pw.Text(
                        'Total:',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.Text(
                        ' R\$ ',
                      ),
                      pw.Text(
                        subtotal.toStringAsFixed(2),
                      ),
                    ],
                  ),
                  pw.Text(' | '),
                  pw.Row(
                    children: <pw.Widget>[
                      pw.Text(
                        'Frete: ',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.Text('Grátis'),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ],
    ),
  );

  Directory documentDirectory = await getApplicationDocumentsDirectory();
  print('Diretório: $documentDirectory');
  String documentPath = documentDirectory.path;
  File file = File("$documentPath/BomboniereLeao.pdf");
  file.writeAsBytesSync(pdfDoc.save());

  await OpenFile.open("$documentPath/BomboniereLeao.pdf");
}

// # FUNCOES
productCount() {
  List<pw.Widget> listValue = [];
  int count = 0;

  objCart.forEach(
    (element) {
      count = count + 1;
      listValue.add(pw.Text("$count"));
    },
  );
  return listValue;
}

productName() {
  List<pw.Widget> listValue = [];

  objCart.forEach(
    (element) {
      listValue.add(pw.Text(element.name.toString()));
    },
  );
  return listValue;
}

productSize() {
  List<pw.Widget> listValue = [];

  objCart.forEach(
    (element) {
      listValue.add(pw.Text(element.size.toString() + element.type.toString()));
    },
  );
  return listValue;
}

productQuantity() {
  List<pw.Widget> listValue = [];

  objCart.forEach(
    (element) {
      listValue.add(pw.Text(element.quantity.toString()));
    },
  );
  return listValue;
}

productPrice() {
  List<pw.Widget> listValue = [];

  objCart.forEach(
    (element) {
      listValue.add(pw.Text('R\$ ' + element.price.toStringAsFixed(2)));
    },
  );
  return listValue;
}

productPriceSub() {
  List<pw.Widget> listValue = [];

  objCart.forEach(
    (element) {
      listValue.add(pw.Text('R\$ ' + (element.quantity * element.price).toStringAsFixed(2)));
    },
  );
  return listValue;
}

productSubtotal() {
  double subtotal = 0.00;

  objCart.forEach((element) {
    subtotal = subtotal - (element.quantity * element.price);
  });
  return subtotal;
}
`

**Comment by DavBfr** [comment]
What's wrong?
