### ISSUE TITLE
Font Fallback

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#626]
We are using the Font Family 'Ubuntu' in our entire app.
There are some glyphs that are not supported by this 'Ubuntu' font such as 

```
- Ẽ ẽ (U+1EBC and U+1EBD)
- ◌̃ (U+0303, the combining tilde, for use in the letters G̃ and g̃, which don’t have separate codepoints)
- Ỹ ỹ (U+1EF8 and U+1EF9)
- ₲ (U+20B2)
```

In the Flutter, we can pass `fontFamilyFallback` https://api.flutter.dev/flutter/painting/TextStyle/fontFamilyFallback.html to the Text Style.

How can we achieve the same in PDF so that Glyphs can be rendered?

**Comment by deepak786** [comment]
@DavBfr Also there is no way to have the light and medium Font in the Pdf document theme.
Only base, bold, italic, and boldItalic is allowed.

**Comment by DavBfr** [comment]
I see your issue. I don't plan to implement that at the moment.

**Comment by DavBfr** [comment]
It's implemented.

**Comment by deepak786** [comment]
Great, When you are planning to release this update on the pub.dev

**Comment by Kabariya** [comment]
@DavBfr Thanks for implementing this, Can you tell us when it can be release or any ongoing PR for this

@deepak786 Did you find out anything to use this implementtion?
