### ISSUE TITLE
Allow to pass the subject, To (email address) when sharing the document

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#627]
We can share the document using 
```
Printing.share()
```
And here we can just pass the name of the document.

It would be better if we can pass the subject and email addresses so that if the user selects the email option from the chooser then the subject and To address will be filled already.

**Comment by DavBfr** [comment]
Looks like you know what you're talking about. Can you make a PR?

**Comment by DavBfr** [comment]
Added to printing 5.1.0

**Comment by deepak786** [comment]
@DavBfr but version 5.1.0 is not released yet, right?

**Comment by DavBfr** [comment]
No, I was just waiting for the automated tests to pass.

**Comment by DavBfr** [comment]
It's live now: https://pub.dev/packages/printing/versions/5.1.0
