### ISSUE TITLE
I need checkbox as checked. I used the value param as true for the CheckBox,but its not getting as checked..can anyone please suggest me how to achieve this.

### ISSUE THREAD

**Issue by nagasaidurga** [DavBfr/dart_pdf#629]
I am creating the checkbox like below.
pw.Checkbox(name: "test",value: true,activeColor:PdfColor.fromHex("#00FF00"),checkColor:PdfColor.fromHex("#00FF00")))

**Comment by DavBfr** [comment]
It's just that CheckBox creates an interactive form, and PdfPreview can't display them properly.
If you just want a static checkbox, it's best to draw one with an SvgImage().
