### ISSUE TITLE
Print format and paper size needs to be chosen by the user first

### ISSUE THREAD

**Issue by gedw99** [DavBfr/dart_pdf#63]
The only issue is that the Print Format is not known until you get to the PDF Printing stage.
This causes lots of issues in the example for Print Screen but also Print PDF, because you cant / dont reflow the PDF when they change the Printer Format or Paper size.

- Instead you want to ask the Print size before hand, and render the Screenshot using:
	- The required DPI for the Paper size
	- The orientation ( Landscape or Portrait)

If there is a smarter way would love to know your thoughts.

**Comment by gedw99** [comment]
There is a PDF Viewer written in FLutter.
In that viewer is where the user selects the Papr Format, so we can render the PDF based on their Papr Format

**Comment by DavBfr** [comment]
I don't understand what the problem is.
In order to print, you need to know the paper size first. That is what the Printing API does.

**Comment by gedw99** [comment]
Hey @DavBfr 

Its not obvious, but when i played with the your examples you can see the PDF messing up depending on the Paper size to print to.

So in order to make a PDF; you need to know the paper size first, and you dont know that until you know what they are printing to.

This is why Google Chrome opens a Preview with the Printer options on the Left.
SO as you change the Printer options, the PDF is re-rendered.
Like this:
http://cdn.osxdaily.com/wp-content/uploads/2014/12/chrome-custom-print-window-mac-os-x.jpg

---

Then in your flutter widgets, you can write the PDF output, but make it parametric to allow for different Paper sizes, Orinetiations, and it will print perfectly.

**Comment by DavBfr** [comment]
That is exactly how this framework works:
When you want to print, you call 
```dart
Printing.layoutPdf(onLayout: (format) { ... });
```
The `onLayout` callback is called by the operating system when it knows the page dimensions and margins. The function is also called again when the user changes the paper size and orientation.

It is up to you to layout according to the `format` you receive.

**Comment by gedw99** [comment]
@DavBfr thank you for explaining that and being so patient about it.

I think i now know how to make this work on Desktop and Mobile then.

1. Open print preview with:
- left pane having Printers and their options
- right pane having the PDF Preview as RASTER

* to get the Printers and options for each i just need to write OS specific calls as a Flutter Plugin

2. As the User changes Print options:
- `OnLayout` is called and the Widgets rerender as PDF and output a Raster again

3. When they hit Print:
- Send the actual PDF ( not the raster to the Printer)

Note this means we need no Native OS things, because we are displaying the PDF as Raster inside FLutter

Makes sense ???

**Comment by DavBfr** [comment]
No worries!

In relation to the issue #37 Direct print implementation, it would also be nice to define the flutter api to list the printers and request a direct print from code.

From there, we can have a generic print dialog as you describe. With or without a preview, depending on the difficulty.

How do you plan to raster the pdf? On flutter for mobile, it's easy to do with a pdf viewer plugin, but not sure they have a desktop equivalent.

**Comment by gedw99** [comment]
Ok seems we are getting our ducks in a row :)

1. Yes Flutter API for Get Printers ( and their options). Good idea.

2 Print Dialog with Preview. I don't see any obstacles.

- The Google cloud connector has the code already in golang for gettign the printer list of local & network printers. https://github.com/google/cloud-print-connector. They dont make it obvious but its there.

- PDF --> Raster. This does it well: https://github.com/catherinelu/evangelist.
  - BTW Can you link to the place you do it for Mobile, so i can try to match the API, etc.

Also can you link to any widgets that are PDF aware in that they can render at different page orientations. I am unsure of the best way to do this so its easy for people to make Widgets that are PDF aware.

**Comment by DavBfr** [comment]
Raster using Ghostscript is the right approach for Linux, but maybe not for Windows and macOS. On macOS, you have the same API as iOS, but on Windows, they have nothing to render a Pdf.

@TristanPct and I tried some solutions for iOS direct print without any luck: Apple's threading model is really strange... And Google does not provide any API to print directly on Android. So you are free to create the methods you need.

I guess we can have 
* A `Printer` class with some info like name, location, id, list of supported pages format.
* A method that returns a `Future<List<Printer>>` to retrieve the list.
* Some new parameters to `Printing.layoutPdf()` to select the `Printer` and set options

The Pdf Widget system is basically the same as Flutter's and can draw on any provided canvas size. They are not aware of any orientation: only the page size, and margins matters.

**Comment by gedw99** [comment]
@DavBfr 
I will work on the PDF --> Raster stuff and get back to you. I am not using ANY OS specific libs, and so wont have those issues. 

For the PDF Widget system, it would be helpful to have more examples designed as Tests. Once we go cross platform you need "golden test data"

**Comment by DavBfr** [comment]
Please move the discussion on #9
