### ISSUE TITLE
Add support to advanced breaking characters in texts

### ISSUE THREAD

**Issue by bkmeneguello** [DavBfr/dart_pdf#630]
**Is your feature request related to a problem? Please describe.**
I need to break texts in more advanced ways, like hyphenation and long word hard breaks.

**Describe the solution you'd like**
Text wrap is done at whitespace level, but it could consider other characters too, like [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) to hard break long words (like long e-mails) and [soft-hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) to implement dynamic syllable separation. The same should apply to [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) to prevent word separation.

**Describe alternatives you've considered**
I'm implementing them at a higher level using RichText and TextSpan.

**Comment by DavBfr** [comment]
Don't hesitate to hack this [text.dart](https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/src/widgets/text.dart) directly and provide a PR.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=LLBoRBAQIw0
