### ISSUE TITLE
Chinese character support

### ISSUE THREAD

**Issue by Shadow404** [DavBfr/dart_pdf#631]
i want use it to preview cash ticket,

**Comment by DavBfr** [comment]
What's not working?

**Comment by xiongw1987** [comment]
自己添加ttf即可

**Comment by Shadow404** [comment]
> What's not working?

i use ttf to it down ,now it's ok,another question is how can preview pdf in a3 paper?

**Comment by DavBfr** [comment]
Add the A3 paper format to PdfPreview

**Comment by longfit** [comment]
> > What's not working?
> 
> i use ttf to it down ,now it's ok,another question is how can preview pdf in a3 paper?

I have problem using pdf package and try to change example

flutter generating pdf medicine list
  at pdf package demo
  https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/document.dart
   final font1 = await PdfGoogleFonts.openSansRegular();
  final font2 = await PdfGoogleFonts.openSansBold();
 change
  final font1 = await PdfGoogleFonts.notoSansTCRegular();
  final font2 = await PdfGoogleFonts.notoSansTCBold();
  when  pw.Text('Portable Document Format 中文字'
   previous invalid character , after empty space
   
   Could you  give some hint how to find out the problem

**Comment by longfit** [comment]
I have problem using pdf package and try to change example

flutter generating pdf medicine list
at pdf package demo
https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/document.dart
final font1 = await PdfGoogleFonts.openSansRegular();
final font2 = await PdfGoogleFonts.openSansBold();
change
final font1 = await PdfGoogleFonts.notoSansTCRegular();
final font2 = await PdfGoogleFonts.notoSansTCBold();
when pw.Text('Portable Document Format 中文字'
previous invalid character , after empty space

Could you give some hint how to find out the problem

**Comment by DavBfr** [comment]
@longfit notoSansTCRegular and notoSansHKRegular are not TrueType fonts but OpenType fonts. This Library does not support this format.
