### ISSUE TITLE
Digital Signature Field

### ISSUE THREAD

**Issue by corusm** [DavBfr/dart_pdf#632]
Is it possible to add a field where I can add a digital signature in with an PDF Annotator.

**Comment by DavBfr** [comment]
Do you have an example of such pdf?

**Comment by corusm** [comment]
Signature Fields like these
https://helpx.adobe.com/sign/using/digital-signatures.html

**Comment by DavBfr** [comment]
So you want to create a PDF document with a signature, or a PDF document to be signed later?

**Comment by corusm** [comment]
A Signature field to be signed later

**Comment by DavBfr** [comment]
Yes, I can add that, it's not possible at the moment.

**Comment by DavBfr** [comment]
It's implemented in the master branch.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by deepak786** [comment]
@DavBfr How to use this digital signature field and how it will work? any documentation?

**Comment by deepak786** [comment]
@DavBfr could you please help me on that?

**Comment by DavBfr** [comment]
You can just use it as any other widget:

```dart
pw.Signature(
  name: 'signature',
  child: pw.Text('Please sign here'),
),
```
