### ISSUE TITLE
How can I do this what pw.Text() softwarp can not work?

### ISSUE THREAD

**Issue by xiongw1987** [DavBfr/dart_pdf#633]
pw.Text(
'123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789',  
softWrap: true),

can not wrap！

**Comment by DavBfr** [comment]
Yes, it wraps only on new lines (\n) or spaces.

**Comment by DavBfr** [comment]
Fixed in pdf-3.3.0
