### ISSUE TITLE
A4 dimensions are wrong in Android

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#635]
In the demo app, There is an option to select the page format between "Letter" and "A4".

To print the Pdf, width and height are passed to the print function in Android.

```
void printPdf(@NonNull String name, @NonNull Double width, @NonNull Double height) {
        jobName = name;

        PrintAttributes.Builder attrBuilder = new PrintAttributes.Builder();
        if (width > height) {
            attrBuilder.setMediaSize(PrintAttributes.MediaSize.UNKNOWN_LANDSCAPE);
        }
        PrintAttributes attrib = attrBuilder.build();
        printJob = printManager.print(name, this, attrib);
}
```

As we have the issue https://github.com/DavBfr/dart_pdf/issues/74 and according to the Android documentation we can pass the MediaSize to PrintAttributes.
So I'm trying to solve this issue.

But converting the width and height from double to integer Mils is giving the wrong values for A4.

**Letter:**

Expected media Size = 8500 * 11000 (in Mils)
```
/** North America Letter media size: 8.5" x 11" (279mm x 216mm) */
        public static final MediaSize NA_LETTER =
                new MediaSize("NA_LETTER", "android", R.string.mediasize_na_letter, 8500, 11000);
```
https://developer.android.com/reference/android/print/PrintAttributes.MediaSize#NA_LETTER

converting the width and height to Mils

```
int width = Double.valueOf(width * 1000.0 / 72.0).intValue(); // outputs 8500
int height = Double.valueOf(height * 1000.0 / 72.0).intValue(); // outputs 11000
```

This is correct.

**A4**

Expected media Size = 8270 * 11690 (in Mils)
```
/** ISO A4 media size: 210mm x 297mm (8.27" x 11.69") */
        public static final MediaSize ISO_A4 =
                new MediaSize("ISO_A4", "android", R.string.mediasize_iso_a4, 8270, 11690);
```
https://developer.android.com/reference/android/print/PrintAttributes.MediaSize#ISO_A4

converting the width and height to Mils

```
int width = Double.valueOf(width * 1000.0 / 72.0).intValue(); // outputs 8267
int height = Double.valueOf(height * 1000.0 / 72.0).intValue(); // outputs 11692
```

This is wrong. It should be 8270 and 11690.

Why the values are wrong for A4?

**Comment by DavBfr** [comment]
Because 210 mm is around 8.267717 inch
and 297 mm is 11.69291 inch which corresponds to the calculs.

**Comment by deepak786** [comment]
So how can we correct this behavior for calculations?

**Comment by DavBfr** [comment]
For me, 8267 and 11692 are correct.

**Comment by deepak786** [comment]
I will try to round the width and height to 2 decimal places.

**Comment by deepak786** [comment]
So then how can we match these values with Android ones?

**Comment by DavBfr** [comment]
Just create a PdfPageFormat that matches:
```dart
const A4 = PdfPageFormat(8.270*PdfPageFormat.inch, 11.690*PdfPageFormat.inch)
```

**Comment by deepak786** [comment]
I'm trying to solve the issue https://github.com/DavBfr/dart_pdf/issues/74
Whatever page format we apply to Pdf document but when printing in Android it always shows the Letter format.

**Comment by deepak786** [comment]
@DavBfr is there a way to pass the page format in the method channel so that when printing in Android, we know that this is the page format to be selected to print? because calculating the page format from width and height will not work because of the wrong values in Android and from the library (main issue).

**Comment by DavBfr** [comment]
You can compare the page format with some error approximations:
```java
int err = 20;
if (width + err >= 8270 && width - err <= 8270 /* &&  same for height */)  {
  format = A4;
}
```

**Comment by deepak786** [comment]
submitted pull request by considering the above err parameter.
