### ISSUE TITLE
socket produces strange characters using the ethernet

### ISSUE THREAD

**Issue by AriaShishegaran** [DavBfr/dart_pdf#637]
**Describe the bug**
first of all thanks for your work on the library. using this library and while connecting via USB and generating a pdf and sending it to the printer works perfectly well. but when utilizing the socket to send the exact same data/pdf, the output is strange characters (tested on PDF, the same file prints ok on USB connection).
I'm using the method `socket.add` to transfer data to the printer.

I would appreciate it if you could resolve the bug or help me navigate through this problem.
![image](https://user-images.githubusercontent.com/15879200/114737334-28ae5d80-9d5c-11eb-8151-27d7b4417894.png)

**Comment by DavBfr** [comment]
Must be that your printer does not support PDF printing through ethernet. It prints the binary content of the file.
