### ISSUE TITLE
unrecognized selector send to instance

### ISSUE THREAD

**Issue by allanwolski** [DavBfr/dart_pdf#64]
App crash on iOS running the current version.
Works only with version 1.3.2

Error:
`[printing.SwiftPrintingPlugin handleMethodCall:result:]: unrecognized selector send to instance`

**Comment by DavBfr** [comment]
Any backtrace or a way to reproduce that?

**Comment by allanwolski** [comment]
The issue was resolved by updating Xcode from version 9.6 to 10.2
