### ISSUE TITLE
Printing.layoutPdf() returns true but nothing happens on Safari on iPad/iPhone (tested on iOS 12 + iOS 14)

### ISSUE THREAD

**Issue by mikeesouth** [DavBfr/dart_pdf#640]
**Describe the bug**
I'm using Flutter for web and I'm trying to print a pdf file (I've tried with different pdf files but it does not change the behavior). Printing works great in all browsers except Safari on iOS. I've tested on an iPad with iOS 12.5.2 and an iPhone 12 Pro with iOS 14.4.2 - both devices have the same behavior: nothing happens when I print.

**To Reproduce**
```dart
var result = await Printing.layoutPdf(
  name: 'test',
  format: PdfPageFormat.a4,
  onLayout: (format) => pdf,
);
```
pdf is of type Uint8List and I'm sure that it contains a correct pdf as printing works in Chrome on the same devices and it works on desktops (I haven't tested Safari on desktop though). I've also tested `dynamicLayout: true` and `dynamicLayout: false` - no change in behavior.
**The returned result is `true` and no exception is thrown.**

**Expected behavior**
That the browser opens a printing modal for the pdf.

**Screenshots**
N/A

**Flutter Doctor**
```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19043.906], locale sv-SE)
    • Flutter version 2.0.4 at C:\Stuff\flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Stuff\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Stuff\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at C:\Program Files (x86)\Google\Chrome\Application)
    ! C:\Program Files (x86)\Google\Chrome\Application is not executable.

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\micke\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.906]
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.63

! Doctor found issues in 2 categories.
```

**Smartphone (please complete the following information):**
 - Device: [iPad, iPhone]
 - OS: [iOS 14.4.2]
 - Browser [Safari]
 - Version [N/A]

**Additional context**
I've tested with printing: ^5.0.3 + pdf: ^3.0.1 and I've also tested with latest versions printing: ^5.1.0 + pdf: ^3.2.0 - same behavior in both cases. I am running flutter stable (see flutter doctor above) and I've not yet converted to NNBD.

**Comment by DavBfr** [comment]
Is this working? https://davbfr.github.io/dart_pdf/ I don't have an iOS device, but it works with the simulator

**Comment by mikeesouth** [comment]
@DavBfr Yep, that example is working for me in Safari on physical iOS devices. Did you change something there or is it just an example to prove that something is wrong with my code? 😄

**Comment by DavBfr** [comment]
No change, it's just a basic example.

**Comment by san-stha** [comment]
@DavBfr i tried this package to print images in a label printer. It kept on searching for printers. I also tried to add the printer through ip address, but the printer could not be found. If you could help me then i would be grateful for your help.

**Comment by SaMMaHeTa** [comment]
i am having exact same issue in iOS, in android it's working perfectly
