### ISSUE TITLE
Hebrew ( right to left ) becoming mirror in Text()

### ISSUE THREAD

**Issue by priyeshstackapp** [DavBfr/dart_pdf#643]
When i create pdf with Hebrew language text that time it become **mirror**.

Ive tried TextDirection.rtl and also tried wrap with Directivity but nothing changed.
Ive also changed font but nothing happened. 
Currently I'm stuck in this issue.

If anyone have solution for **Hebrew** ( right to left ) then please let me know.

**Comment by DavBfr** [comment]
Duplicate of #443

**Comment by SaeedIsa** [comment]
@priyesh-bit Hi,
did you solve the issue ? if so, can you please summarize what you have done ? and which font you have used ?

Thanks!
