### ISSUE TITLE
Have to show the PDF in container, after creation.

### ISSUE THREAD

**Issue by farooqaziz20** [DavBfr/dart_pdf#644]
HI, i am using this package to create the PDF in flutter. I want to view the created pdf in the container. Can you please suggest any solution?

**Comment by DavBfr** [comment]
Yes, use the printing package.

**Comment by farooqaziz20** [comment]
I am trying to use printing library, but it showing error.

**Comment by DavBfr** [comment]
What error?

**Comment by farooqaziz20** [comment]
Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (20409): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (20409): Courier has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (20409): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20409): The following assertion was thrown during performLayout():
I/flutter (20409): RenderFlex children have non-zero flex but incoming height constraints are unbounded.
I/flutter (20409): When a column is in a parent that does not provide a finite height constraint, for example if it is
I/flutter (20409): in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
I/flutter (20409): flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
I/flutter (20409): space in the vertical direction.
I/flutter (20409): These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
I/flutter (20409): cannot simultaneously expand to fit its parent.
I/flutter (20409): Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
I/flutter (20409): children (using Flexible rather than Expanded). This will allow the flexible children to size
I/flutter (20409): themselves to less than the infinite remaining space they would otherwise be forced to take, and
I/flutter (20409): then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
I/flutter (20409): constraints provided by the parent.
I/flutter (20409): If this message did not help you determine the problem, consider using debugDumpRenderTree():
I/flutter (20409):   https://flutter.dev/debugging/#rendering-layer
I/flutter (20409):   http://api.flutter.dev/flutter/rendering/debugDumpRenderTree.html
I/flutter (20409): The affected RenderFlex is:
I/flutter (20409):   RenderFlex#3f2e0 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE(creator: Column ← PdfPreview ← Column ← _BodyBuilder 
← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#f089a ink renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯, parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size), constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity), size: MISSING, direction: vertical, mainAxisAlignment: center, mainAxisSize: max, crossAxisAlignment: center, verticalDirection: 
down)
I/flutter (20409): The creator information is set to:
I/flutter (20409):   Column ← PdfPreview ← Column ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter (20409):   CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (20409):   _InkFeatures-[GlobalKey#f089a ink renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯
I/flutter (20409): The nearest ancestor providing an unbounded width constraint is: RenderFlex#89bcd relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (20409):   creator: Column ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter (20409):     CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (20409):     _InkFeatures-[GlobalKey#f089a ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (20409):     PhysicalModel ← AnimatedPhysicalModel ← ⋯
I/flutter (20409):   parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
I/flutter (20409):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=654.0)
I/flutter (20409):   size: MISSING
I/flutter (20409):   direction: vertical
I/flutter (20409):   mainAxisAlignment: start
I/flutter (20409):   mainAxisSize: max
I/flutter (20409):   crossAxisAlignment: center
I/flutter (20409):   verticalDirection: down
I/flutter (20409): See also: https://flutter.dev/layout/
I/flutter (20409): If none of the above helps enough to fix this problem, please don't hesitate to file a bug:
I/flutter (20409):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20409):
I/flutter (20409): The relevant error-causing widget was:
I/flutter (20409):   Column
I/flutter (20409):   file:///C:/Users/EliteBook/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/printing-4.1.0/lib/src/pdf_preview.dart:424:12
I/flutter (20409):
I/flutter (20409): When the exception was thrown, this was the stack:
I/flutter (20409): #0      RenderFlex.performLayout.<anonymous closure> (package:flutter/src/rendering/flex.dart:712:11)
I/flutter (20409): #1      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:739:10)
I/flutter (20409): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:765:15)
I/flutter (20409): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #5      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
I/flutter (20409): #6      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:495:7)
I/flutter (20409): #7      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
I/flutter (20409): #8      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
I/flutter (20409): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #13     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
I/flutter (20409): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #30     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:13)
I/flutter (20409): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #34     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
I/flutter (20409): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #62     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3226:14)
I/flutter (20409): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20409): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20409): #66     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
I/flutter (20409): #67     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (20409): #68     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
I/flutter (20409): #69     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
I/flutter (20409): #70     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
I/flutter (20409): #71     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (20409): #72     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (20409): #73     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
I/flutter (20409): #74     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
I/flutter (20409): #78     _invoke (dart:ui/hooks.dart:253:10)
I/flutter (20409): #79     _drawFrame (dart:ui/hooks.dart:211:3)
I/flutter (20409): (elided 3 frames from dart:async)
I/flutter (20409): 
I/flutter (20409): The following RenderObject was being processed when the exception was fired: RenderFlex#3f2e0 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (20409):   creator: Column ← PdfPreview ← Column ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>]
I/flutter (20409):     ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (20409):     _InkFeatures-[GlobalKey#f089a ink renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯
I/flutter (20409):   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
I/flutter (20409):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity)
I/flutter (20409):   size: MISSING
I/flutter (20409):   direction: vertical
I/flutter (20409):   mainAxisAlignment: center
I/flutter (20409):   mainAxisSize: max
I/flutter (20409):   crossAxisAlignment: center
I/flutter (20409):   verticalDirection: down
I/flutter (20409): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (20409):     child 1: RenderConstrainedBox#e5bd0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):       child: RenderDecoratedBox#c0990 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):         child: RenderPositionedBox#7ecdd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):           child: RenderPositionedBox#3b68c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):             child: RenderParagraph#1ec28 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (20409):     child 2: RenderPhysicalModel#6d752 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):       child: _RenderInkFeatures#b94d3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):         child: RenderPadding#0383b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):           child: RenderFlex#a58ff NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):             child 1: RenderSemanticsAnnotations#cecb7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409):             child 2: RenderMouseRegion#ed88f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (20409): Another exception was thrown: RenderBox was not laid out: RenderFlex#3f2e0 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409): Another exception was thrown: RenderBox was not laid out: RenderFlex#89bcd relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20409): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
I/flutter (20409): Another exception was thrown: Updated layout information required for RenderConstrainedBox#e5bd0 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.

**Comment by farooqaziz20** [comment]
Above is the complete error statement, I have tried to use the  Open sans as you have mentioned in the solution at https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management, but it  still giving me the same error.

**Comment by DavBfr** [comment]
Try to wrap PdfPreview with Flexible().

**Comment by farooqaziz20** [comment]
I am still getiing the same error while i have wraped it with the flexible(flex:1, child : PdfPreview()) .
 
 
 The following assertion was thrown while looking for parent data.:
I/flutter (22220): Incorrect use of ParentDataWidget.
I/flutter (22220): The following ParentDataWidgets are providing parent data to the same RenderObject:
I/flutter (22220): - Flexible(flex: 1) (typically placed directly inside a Flex widget)
I/flutter (22220): - LayoutId-[<_ScaffoldSlot.body>](id: _ScaffoldSlot.body) (typically placed directly inside a
I/flutter (22220): CustomMultiChildLayout widget)
I/flutter (22220): However, a RenderObject can only receive parent data from at most one ParentDataWidget.
I/flutter (22220): Usually, this indicates that at least one of the offending ParentDataWidgets listed above is not
I/flutter (22220): placed directly inside a compatible ancestor widget.
I/flutter (22220): The ownership chain for the RenderObject that received the parent data was:
I/flutter (22220):   Column ← PdfPreview ← Flexible ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter (22220): CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← ⋯
I/flutter (22220):

**Comment by Leleocastro** [comment]
> I am still getiing the same error while i have wraped it with the flexible(flex:1, child : PdfPreview()) .

I really can't replicate the error, can you post a part of your code?

I tried here and work very well, look the default code with PdfViewer inside a Container, with size manipulation of Container:

```
import 'dart:typed_data';


import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() => runApp(const MyApp('Printing Demo'));

class MyApp extends StatelessWidget {
  const MyApp(this.title);

  final String title;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text(title)),
        body: Container(
          height: 800,
          width: 500,
          child: PdfPreview(
            allowPrinting: false,
            allowSharing: false,
            canChangeOrientation: false,
            canChangePageFormat: false,
            build: (format) => _generatePdf(format, title),
          ),
        ),
      ),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final doc = pw.Document();

    doc.addPage(pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Text('Hello World'),
          ); // Center
        })); // Pa

    return doc.save();
  }
}
```

Look print image:
![image](https://user-images.githubusercontent.com/24722339/115499750-560c7700-a246-11eb-9987-67dc1584bba3.png)

Expected could help.

**Comment by farooqaziz20** [comment]
Yes, it helped. Thanks for the help.
