### ISSUE TITLE
Adding metadata about pdf file

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#647]
It would be better if we can add metadata to the pdf file being saved (such as author, creator, subject, keywords, etc.)

**Comment by deepak786** [comment]
got it, we can pass such properties while initializing the document

```
pw.Document(theme: await _getFontTheme(), subject: , title: );
```

**Comment by DavBfr** [comment]
👍 I like autoclosing issues!
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
