### ISSUE TITLE
Os error : error code 1

### ISSUE THREAD

**Issue by Yogesh-333** [DavBfr/dart_pdf#648]
**Describe the bug**

Os error happens only on android 11 (SDK 30) . SDK 29  or lesser works properly  
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```
import 'dart:io';
import 'dart:math';
import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:downloads_path_provider/downloads_path_provider.dart';
import 'package:flutter/services.dart';
import 'package:ihl/views/teleconsultation/pdf_viewer.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';
import 'package:flutter/material.dart' as material;
import 'package:printing/printing.dart';
import 'package:shared_preferences/shared_preferences.dart';

var consultantNameFromHistory;
String appointmentStartTimeFromHistory;
var appointmentEndTimeFromHistory;
var consultationFeesFromHistory;
var modeOfPaymentFromHistory;
var userFirstNameFromHistory;
var userLastNameFromHistory;
var userEmailFromHistory;
var userContactFromHistory;
String dd, mm, yyyy, time;
String appointmentOn;
String appointmentOnPdfSave;
var appointId;
bool clickedFromPastInvoiceAppointments = false;

getDataFromHistory() async {
  SharedPreferences prefs = await SharedPreferences.getInstance();

  clickedFromPastInvoiceAppointments =
      prefs.getBool("clickedFromPastInvoiceAppointments");

  consultantNameFromHistory = prefs.getString("consultantNameFromHistory");
  appointmentStartTimeFromHistory =
      prefs.getString("appointmentStartTimeFromHistory");
  appointmentEndTimeFromHistory =
      prefs.getString("appointmentEndTimeFromHistory");
  consultationFeesFromHistory = prefs.getString("consultationFeesFromHistory");
  modeOfPaymentFromHistory = prefs.getString("modeOfPaymentFromHistory");
  userFirstNameFromHistory = prefs.getString("userFirstNameFromHistory");
  userLastNameFromHistory = prefs.getString("userLastNameFromHistory");
  userEmailFromHistory = prefs.getString("userEmailFromHistory");
  userContactFromHistory = prefs.getString("userContactFromHistory");
  appointId = prefs.getString("appointIdFromHistory");

  dd = appointmentStartTimeFromHistory.substring(8, 10);
  mm = appointmentStartTimeFromHistory.substring(5, 7);
  yyyy = appointmentStartTimeFromHistory.substring(0, 4);
  time = appointmentStartTimeFromHistory.substring(11, 19);
  appointmentOn = dd + "/" + mm + "/" + yyyy;
  appointmentOnPdfSave = dd + "-" + mm + "-" + yyyy;
}

billView(context) async {
  getDataFromHistory();
  final Document pdf = Document();
  final DateTime now = DateTime.now();
  String date = now.day.toString() +
      "/" +
      now.month.toString() +
      "/" +
      now.year.toString();
  const imageProvider = const material.AssetImage('assets/images/ihl-plus.png');
  final image = await flutterImageProvider(imageProvider);

  pdf.addPage(Page(
      theme: ThemeData.withFont(
        base: Font.ttf(await rootBundle.load("assets/fonts/arial.ttf")),
      ),
      pageFormat: PdfPageFormat.a4,
      build: (Context context) {
        return Expanded(
            child:
                Column(mainAxisAlignment: MainAxisAlignment.start, children: <
                    Widget>[
          Align(
              alignment: Alignment.topLeft,
              child: Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(date, style: TextStyle(fontSize: 6.0)),
                    Padding(
                        padding: EdgeInsets.only(top: 5.0),
                        child: Row(
                            mainAxisAlignment: MainAxisAlignment.start,
                            children: <Widget>[
                              Image(image, width: 40.0, height: 40.0),
                              Padding(
                                  padding:
                                      EdgeInsets.only(left: 3.0, right: 3.0),
                                  child: Container(
                                    width: 0.2,
                                    height: 40,
                                    color: PdfColors.grey300,
                                  )),
                              Column(
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: <Widget>[
                                    Text("IsfgsgA",
                                        style: TextStyle(
                                            color:
                                                PdfColor.fromInt(0xff2768a9))),
                                    Text("GJ",
                                        style:
                                            TextStyle(color: PdfColors.grey)),
                                    Text("sfg",
                                        style: TextStyle(
                                            color:
                                                PdfColor.fromInt(0xff2768a9))),
                                  ])
                            ])),
                    Padding(
                      padding: EdgeInsets.only(left: 70.0),
                      child: Center(
                          child: Text("sfsdfds",
                              style: TextStyle(fontSize: 6.0))),
                    )
                  ])),
          Padding(
            padding: EdgeInsets.only(left: 265.0, bottom: 5.0, top: 0.0),
            child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[Text("Contact : +91 80-47485152")]),
          ),
          Padding(
            padding: EdgeInsets.only(left: 265.0, bottom: 5.0),
            child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  Text("Email : info@iwrtwtwrt.com"),
                ]),
          ),
          Padding(
            padding: EdgeInsets.only(left: 265.0, bottom: 5.0),
            child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  Text("Web : sfgsfgk.com"),
                ]),
          ),
          Padding(
            padding: EdgeInsets.only(left: 265.0, bottom: 5.0),
            child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  Text("Address : ety"),
                ]),
          ),
          Padding(
            padding: EdgeInsets.only(left: 265.0),
            child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  Text("etyety."),
                ]),
          ),
          SizedBox(
            height: 20.0,
          ),
          Row(mainAxisAlignment: MainAxisAlignment.center, children: <Widget>[
            Text("Payment Receipt",
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                ))
          ]),
          Divider(
              thickness: 0.5,
              color: PdfColors.grey300,
              indent: 3.0,
              endIndent: 1.0),
          Table(
            children: [
              TableRow(children: [
                RichText(
                  text: TextSpan(
                    children: [
                      TextSpan(
                        text: 'Name: ',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      TextSpan(
                        text: userFirstNameFromHistory.toString() +
                            " " +
                            userLastNameFromHistory.toString(),
                        style: TextStyle(),
                      ),
                    ],
                  ),
                ),
                Spacer(),
                Padding(
                  padding: EdgeInsets.only(left: 50.0),
                  child: RichText(
                    text: TextSpan(
                      children: [
                        TextSpan(
                          text: 'Date: ',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        TextSpan(
                          text: appointmentOn,
                          style: TextStyle(),
                        ),
                      ],
                    ),
                  ),
                ),
              ]),
              TableRow(children: [
                RichText(
                  text: TextSpan(
                    children: [
                      TextSpan(
                        text: 'Phone Number: ',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      TextSpan(
                        text: userContactFromHistory.toString(),
                        style: TextStyle(),
                      ),
                    ],
                  ),
                ),
                Spacer(),
                Padding(
                  padding: EdgeInsets.only(left: 50.0),
                  child: RichText(
                    text: TextSpan(
                      children: [
                        TextSpan(
                          text: 'GST Number: ',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        TextSpan(
                          text: '0fghfghfZ7',
                          style: TextStyle(),
                        ),
                      ],
                    ),
                  ),
                ),
              ]),
              TableRow(children: [
                RichText(
                  text: TextSpan(
                    children: [
                      TextSpan(
                        text: 'Email: ',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      TextSpan(
                        text: userEmailFromHistory.toString(),
                        style: TextStyle(),
                      ),
                    ],
                  ),
                ),
                Spacer(),
                Padding(
                  padding: EdgeInsets.only(left: 50.0),
                  child: RichText(
                    text: TextSpan(
                      children: [
                        TextSpan(
                          text: 'fjhj fhjme: ',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        TextSpan(
                          text: consultantNameFromHistory.toString(),
                          style: TextStyle(),
                        ),
                      ],
                    ),
                  ),
                ),
              ])
            ],
          ),
          Divider(thickness: 0.5, color: PdfColors.grey300),
          Table(
            children: [
              TableRow(children: [
                Text('Item Description',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                    )),
                Row(children: <Widget>[
                  SizedBox(width: 25.0),
                  Padding(
                    padding: EdgeInsets.only(left: 155.0),
                    child: Text('Payment Method',
                        style: TextStyle(fontWeight: FontWeight.bold)),
                  ),
                  SizedBox(width: 30.0),
                  Text("Amount",
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                      )),
                ]),
              ]),
            ],
          ),
          Divider(thickness: 0.5, color: PdfColors.grey300),
          Expanded(
            child: Table(children: [
              TableRow(children: [
                Text("Video Consultation Fees" +
                    "\n" +
                    "Appointment on " +
                    appointmentOn +
                    ", " +
                    time +
                    "\t \t \t \t \t \t \t \t \t\t\t\t\t\t\t" +
                    modeOfPaymentFromHistory +
                    "\t \t\t \t \t \t \t \t \t \t \t\t \t \t\t \t" +
                    consultationFeesFromHistory.toString()),
              ]),
            ]),
          ),
          Divider(thickness: 0.5, color: PdfColors.grey300),
          Table(children: [
            TableRow(children: [
              Text(""),
              Expanded(
                  child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                    SizedBox(width: 23.0),
                    Padding(
                      padding: EdgeInsets.only(left: 260.0),
                      child: Text("Total"),
                    ),
                    SizedBox(width: 90.0),
                    Text(" ₹ " +
                        consultationFeesFromHistory.toString() +
                        "(includes\nall tax)")
                  ]))
            ])
          ]),
          Divider(thickness: 0.5, color: PdfColors.grey300),
          Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[Text("Note- This is an electronic receipt")]),
          SizedBox(height: 340.0),
          Align(
              alignment: Alignment.bottomLeft,
              child: Row(children: <Widget>[
                Text("fhmfhmfhmfhmfhm",
                    style: TextStyle(fontSize: 6)),
              ]))
        ]));
      }));

  String fileName = appointId + "_" + appointmentOnPdfSave + " " + time;

  Directory downloadsDirectory1 =
      await DownloadsPathProvider.downloadsDirectory;
  final String dir = downloadsDirectory1.path;
  final String path = '$dir/' + fileName + ".pdf";
  final File file = File(path);
  await file.writeAsBytes(await pdf.save());
  SharedPreferences prefs = await SharedPreferences.getInstance();
  prefs.setString("pathFromBillView", path);

  if (clickedFromPastInvoiceAppointments) {
    var maxStep = 1;
    for (var simulatedStep = 1; simulatedStep <= maxStep + 1; simulatedStep++) {
      await Future.delayed(Duration(seconds: 1), () async {
        if (simulatedStep > maxStep) {
          await AwesomeNotifications().createNotification(
              content: NotificationContent(
                  id: 1,
                  channelKey: 'bill_progress',
                  title: 'Download finished',
                  body: fileName + '.pdf',
                  payload: {'file': fileName + '.pdf', 'path': path},
                  locked: false));
        } else {
          await AwesomeNotifications().createNotification(
              content: NotificationContent(
                  id: 1,
                  channelKey: 'bill_progress',
                  title:
                      'Downloading file in progress (${simulatedStep} of $maxStep)',
                  body: fileName + '.pdf',
                  payload: {'file': fileName + '.pdf', 'path': path},
                  notificationLayout: NotificationLayout.ProgressBar,
                  progress: min((simulatedStep / maxStep * 100).round(), 100),
                  locked: true));
        }
      });
    }
    prefs.setBool("clickedFromPastInvoiceAppointments", false);

    material.Navigator.of(context).push(
      material.MaterialPageRoute(
        builder: (_) => PdfViewerPage(path: path),
      ),
    );
  } else {
    material.Navigator.of(context).push(
      material.MaterialPageRoute(
        builder: (_) => PdfViewerPage(path: path),
      ),
    );
  }
}

**Expected behavior**

E/flutter ( 1252): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/storage/emulated/0/Download/2f7f76595d8f46b3bd50af4223b49298_20-04-2021 12:21 PM.pdf' (OS Error: Operation not permitted, errno = 1)
E/flutter ( 1252): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 1252): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 1252): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 1252): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 1252): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 1252): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 1252): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 1252): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 1252): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 1252): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 1252): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 1252): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 1252): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 1252): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Screenshots**

**Flutter Doctor**

D:\flutterapps\userapp>flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • SM M015G (mobile) • R9ZNA017LRF • android-arm   • Android 10 (API 29)
    • SM M307F (mobile) • RZ8M921KZAY • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [*] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: [samsung M30s]
 - OS: [android 11]

**Additional context**

**Comment by DavBfr** [comment]
That's not related to this pdf library, it's android permissions to tweak in your app to be able to save a file on the Download folder.

**Comment by Yogesh-333** [comment]
This is my android mainfest file . Which permission do i need to add ?


<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.xyz.dbd" xmlns:tools="http://schemas.android.com/tools">
  
  <uses-permission android:name="android.permission.INTERNET" />
  
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

  
  <uses-permission android:name="android.permission.CAMERA" />
  
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  
  <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />

  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
  <uses-permission android:name="android.permission.VIBRATE" />

  <application tools:replace="android:label" android:name="io.flutter.app.FlutterApplication" android:label="xyz" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:requestLegacyExternalStorage="true" android:preserveLegacyExternalStorage="true">
    <meta-data android:name="com.google.android.geo.API_KEY" android:value="xvbxvbxvbxbIvxb"/>
    <activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:screenOrientation="portrait" android:windowSoftInputMode="adjustResize">
      
      <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
      
      <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <intent-filter>
        <action android:name="FLUTTER_NOTIFICATION_CLICK"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>
    </activity>
    <activity android:name="com.yalantis.ucrop.UCropActivity" android:screenOrientation="portrait" android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
    
    <meta-data android:name="flutterEmbedding" android:value="2" />

    <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
          <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"/>
        <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
        </intent-filter>
      </receiver>

<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
  </application>
</manifest>
