### ISSUE TITLE
I want to add Image.network('url'). Does pw.Image also support network images?

### ISSUE THREAD

**Issue by SilkeNL** [DavBfr/dart_pdf#649]
pw is import 'package:pdf/widgets.dart' as pw; as shown in the example

**Comment by SilkeNL** [comment]
Found it:

https://github.com/DavBfr/dart_pdf/wiki/Network-Image

**Comment by edwin0401** [comment]
import 'package:dio/dio.dart';

Response<Uint8List>? image;
image= await Dio().get(url,
          options: Options(responseType: ResponseType.bytes));

child: pw.Image(pw.MemoryImage(image!.data!)
