### ISSUE TITLE
[FONT] Unhandled Exception: Invalid argument (string): Contains invalid characters.: ""

### ISSUE THREAD

**Issue by ande4485** [DavBfr/dart_pdf#650]
**Describe the bug**
I copy/paste your code from demo project.
https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/resume.dart
I download this font :
https://fonts.google.com/specimen/Open+Sans
And I have always this bug when I try to create pdf.
2021-04-20 19:27:24.615 19887-20059/com.ande.flutter_test_cv I/flutter: Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
2021-04-20 19:27:24.642 19887-20059/com.ande.flutter_test_cv I/flutter: ---------------------------------------------
    Cannot decode the string to Latin1.
    This font does not support Unicode characters.
    If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
    See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
    ---------------------------------------------
2021-04-20 19:27:24.661 19887-20059/com.ande.flutter_test_cv E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: ""

I'll try to change many things but I can get it.

**To Reproduce**
copy/paste https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/resume.dart
download https://fonts.google.com/specimen/Open+Sans
change assets/open-sans.ttf by assets/OpenSans-Regular.ttf and assets/open-sans-bold.ttf by assets/OpenSans-Bold.ttf 
and run app

**Expected behavior**
no error and this font can work

**Flutter Doctor**
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale fr_FR.UTF-8)
    • Flutter version 2.1.0-12.1.pre at /home/antoine/snap/flutter/common/flutter
    • Framework revision 8264cb3e8a (il y a 6 semaines), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/antoine/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/antoine/Bureau/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/antoine/Bureau/android-studio
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 4.1)
    • Android Studio at /home/antoine/android-studio
    • Flutter plugin version 55.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • SM A520F (mobile) • 5210a904b44db41f • android-arm64  • Android 8.0.0 (API 26)
    • Linux (desktop)   • linux            • linux-x64      • Linux
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 90.0.4430.72

 
 iOS
 - [X] Android
 - [X] Browser
 - [ ] Windows
 - [X] Linux

**Comment by DavBfr** [comment]
You made no modification compared to `resume.dart`? It uses only ttf fonts and never builtin Helvetica.
You should try a simple example first.

**Comment by ande4485** [comment]
@DavBfr , sorry for this non-bug !! It was because line  icons: pw.Font.ttf(await rootBundle.load('assets/material.ttf')), was commented. So it's not bug, just an error from me !
But thank you for your answer so quick and for your work ( I'll buy you a coffee very soon)
