### ISSUE TITLE
Resize Text based on SizedBox Constraints

### ISSUE THREAD

**Issue by ATmare** [DavBfr/dart_pdf#653]
I am trying to resize a Text inside a SizedBox, so that I can avoid it from overflowing the constraints of the SizedBox. Is there any way to do this? I have not found a solution yet. The textScaleFactor should be adjusted if needed and scale the text down if it is too large to fit in the box.

My code looks like this: 

```
pw.SizedBox(
        height: 25,
        width: 30,
        child: pw.Container(
          child: pw.Center(
            child: pw.Text(
              myText,
              textScaleFactor: 0.8,
            ),
          ),
        ),
      );
```

Thanks in advance!

**Comment by DavBfr** [comment]
Try FittedBox() widget https://api.flutter.dev/flutter/widgets/FittedBox-class.html

**Comment by ATmare** [comment]
thanks a lot! I totally forgot that FittedBox could do the trick!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by deverlex** [comment]
> Try FittedBox() widget https://api.flutter.dev/flutter/widgets/FittedBox-class.html
> 
> ```dart
>         pw.SizedBox.expand(
>             child: pw.FittedBox(
>               child: pw.Transform.rotateBox(
>                 angle: 0.2,
>                 child: pw.Text(
>                   title,
>                   tightBounds: true,
>                 ),
>               ),
>             ),
>           )
> ```

It doesn't break line, I want to set max 2 lines when my text is long, thanks
