### ISSUE TITLE
Table not splitting across pages

### ISSUE THREAD

**Issue by arif2k17** [DavBfr/dart_pdf#655]
Hi, First of all It's a great library. However, i am facing some issues with table. I have a large dataset to show in a table but whenever the rows can't fit in one page the full table goes to next page (cont.) and the previous page becomes blank.

Any solution for that?

Piece of code i am using for table: 
```
pw.Table.fromTextArray(
                      headers: [
                        "Medicine",
                        "Dosage",
                        "Duration",
                        "Instruction"
                      ],
                      data: [
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"],
                        ["Napa Extra", "1+0+1", "7 Days", "After meal"]
                      ],
                    ),
```

**Comment by BenPoell** [comment]
I also just figured out that it doesn't print the table at all, when it's wider then the page.

**Comment by deepak786** [comment]
@arif2k17 @BenPoell How are you guys using the pw.Table? Is it a direct child of MultiPage build?

**Comment by arif2k17** [comment]
@deepak786 Yes. It is a direct child of Multipage build.

**Comment by deepak786** [comment]
@arif2k17 please make sure you are not returning the pw.Table from custom pw.StatelesWidget or you are not wrapping the pw.Table with any other widget such as pw.Padding.

**Comment by arif2k17** [comment]
@deepak786 you are right. I wrapped it using padding inside another column. However, i took it out and placed in build method and it splits accordingly. 

Can i wrap it with a Row in build method anyway?

**Comment by arif2k17** [comment]
@deepak786  wrapping it with a pw.Row() is not working. But i need to wrap it with a pw.Row() any workaround for that?

**Comment by deepak786** [comment]
@arif2k17 I don't know but you can try with pw.Partitions

**Comment by DavBfr** [comment]
The master branch should have no issues adding a Padding() widget as the parent of a Table(), if it simplifies.

**Comment by arif2k17** [comment]
@DavBfr i need to wrap the Table with pw.Row() is that also supported with pdf-3.3.0?

**Comment by arif2k17** [comment]
@deepak786 Thanks mate. Using partitions fixed the problem and working as expected.

**Comment by deepak786** [comment]
@arif2k17 Great :)
