### ISSUE TITLE
Pdf file is damaged when the height of image is bigger than 100.

### ISSUE THREAD

**Issue by NuclearGear** [DavBfr/dart_pdf#66]
**Describe the bug**
When I use the picture which the height is smaller than 100, the pdf is built correctly. If the height of picture is bigger than 100, the file will be damaged.

```dart
pdf.addPage(Page(
      pageFormat: PdfPageFormat.a4,
      build: (Context context) {
        return Column(
          children: [


            
            Padding(padding: const EdgeInsets.symmetric(vertical: 10),),

            // CHART
             Container(
              padding: const EdgeInsets.only(bottom: 10),
              alignment: Alignment.centerLeft,
              child: Text(
                "Chart",
                style: TextStyle(
                  fontSize: 20,
                  font: Font.timesBold(),
                ),
              ),
            ),
            // Container(height: image.height.toDouble(),child: 
            //   FittedBox(
            //     child: 
            Expanded(
              child:
                Image(image),
            ),
            //   ),
            // ),
 
          ],
        ); // Center
      })); // Page
```

**Expected behavior**
Save as a regular pdf file with picture

**Desktop:**
 - [x] iOS
 - [x] Android

**Comment by DavBfr** [comment]
How do you get the image?

**Comment by NuclearGear** [comment]
> How do you get the image?

generate image
` RenderRepaintBoundary boundary =
        _chartKey.currentContext.findRenderObject();
    var chart = await boundary.toImage();
    print("origin height: ${image.height} origin width: ${image.width}");
`
post the UIImage to the function
` final ByteData bytes = await chart.toByteData(format: ui.ImageByteFormat.rawRgba);
  final PdfImage image = PdfImage(pdf.document,image: bytes.buffer.asUint8List(),width: chart.width,height:chart.height );
`

**Comment by DavBfr** [comment]
I still can't make it crash.
Can you provide the resulting pdf file or a full example?
