### ISSUE TITLE
Unhandled Exception: Unable to find a Jpeg image in the file

### ISSUE THREAD

**Issue by Vishu29star** [DavBfr/dart_pdf#664]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
Future<pw.ImageProvider> networkImage(
    String url, {
      bool cache = true,
      PdfImageOrientation orientation,
      double dpi,
    }) async {
  final img = await download(url, cache: cache);
  print("img");
  print(img);
  return await pw.MemoryImage(img, orientation: orientation, dpi: dpi);
}



Future<Uint8List> download(
    String url, {
      bool cache = true,
    }) async {
  File file;
  if (cache) {
    final tmp = await getTemporaryDirectory();
    file = File('${tmp.path}/${url.hashCode}');
    if (file.existsSync()) {
      return await file.readAsBytes();
    }
  }

  print('Downloading $url');
  final client = HttpClient();
  final request = await client.getUrl(Uri.parse(url));
  final response = await request.close();
  final builder = await response.fold(
      BytesBuilder(), (BytesBuilder b, List<int> d) => b..add(d));
  final List<int> data = builder.takeBytes();

  if (cache) {
    await file.writeAsBytes(data);
  }
  return Uint8List.fromList(data);
}
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

/home/vishal/Documents/softwares/flutter_linux_2.0.5-stable/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_IN)
    • Flutter version 2.0.5 at /home/vishal/Documents/softwares/flutter_linux_2.0.5-stable/flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/vishal/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/vishal/Documents/softwares/android-studio-ide-201.6858069-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/vishal/Documents/softwares/android-studio-ide-201.6858069-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/vishal/Documents/softwares/android-studio-ide-201.6858069-linux/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • vivo 1820 (mobile) • SWJ7CUKZ9PMFO7RS • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
Process finished with exit code 0
```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [y] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
vivo 1820 (mobile) • SWJ7CUKZ9PMFO7RS • android-arm64  • Android 8.1.0 (API 27)

**Additional context**
i also check your same issue regarding this in jan month and you said updated
please help need urgent

**Comment by DavBfr** [comment]
Seems to be the PNG file you refer to is not found.

**Comment by Vishu29star** [comment]
Got issue it is in my site
thanks for you help
i really appreciate this.
Thanks again
