### ISSUE TITLE
iOS print issue

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#667]
Print Preview in iOS is not taking the provided page size.
Similar issue https://github.com/DavBfr/dart_pdf/issues/124

Print Code:
```
/// default page format
final _pageFormat = PdfPageFormat.a4.copyWith(
    marginTop: 20.0,
    marginBottom: 20.0,
);

// print the document
Printing.layoutPdf(
    onLayout: (_) => _documentBytes,
    name: widget.getDocumentName(),
    format: _pageFormat,
);
```

Output:
<img src="https://user-images.githubusercontent.com/14223997/116542472-4bb74080-a90a-11eb-9013-6f42738d50f8.png" width="300">

Default Print:
if I select the default print option from the share dialog then 
<img src="https://user-images.githubusercontent.com/14223997/116543080-0c3d2400-a90b-11eb-9a47-980ba33d319b.png" width="300">

**Comment by deepak786** [comment]
ok, So based on a similar issue https://github.com/DavBfr/dart_pdf/issues/124
I updated the print code to:
```
Printing.layoutPdf(
   // relayout the pdf document here
   // instead of using [_documentBytes]
   //
   // see [https://github.com/DavBfr/dart_pdf/issues/124] and
   // [https://github.com/DavBfr/dart_pdf/issues/667]
   onLayout: (PdfPageFormat format) {
       return _generateDocument(format);
   },
   name: widget.getDocumentName(),
   format: _pageFormat,
);
```

And it works fine.

But my concern is, why the default print option is working fine but for Printing.layout, we have to re-layout the PDF?

**Comment by DavBfr** [comment]
@deepak786 This is because it all depends on the paper format available on the actual printer connected to the mobile device. layoutPdf will give you the right format selected by the user. You can then generate the PDF according to this.

**Comment by deepak786** [comment]
ok.

We can add the margin to the document. But selecting the default print option from the default share options (OS Share Controller), the page adds more margin. One provided by us and one from the print Page format itself.

**Comment by deepak786** [comment]
@DavBfr ok, understood. 
But can't we apply the predefined format in iOS printing, just like we do in Android?

**Comment by DavBfr** [comment]
@deepak786 I think iOS will not take the format into account. It's possible to resize/center the PDF on the target page, though.
