### ISSUE TITLE
Share functionality accesible from a custom button

### ISSUE THREAD

**Issue by francesctovar** [DavBfr/dart_pdf#668]
I'd need to remove the actions bar but keeping the pdf sharing functionality in a custom button. 

Having the ability to detect when the share panel has appeared would be nice to be able to display a loader to avoid dead time between the button being pressed and the panel appearing.

I had tried to make an extension of PdfPreview class to encapsulate the share functionality but I only make it working on Mac, and without being able to correctly position the share dialog :S

Sorry if there's any solution working... I've tried calling Printing.sharePdf but I can't manage to get the bytes and bounds parameters.

**Comment by DavBfr** [comment]
Your document takes time to generate?
You can build it in advance and call `Printing.sharePdf`. bytes is the result of an `await pdf.save()` or a pdf document on disk. Every other parameter is optional.

**Comment by francesctovar** [comment]
Thanks @DavBfr for some reason the share button on the default action panel was taking too much time to respond when the user's tap. Now I've created my own button and I'm saving the result of the _pdf.save()_ into a variable so when the user tap on my button I'm passing the _Uint8List_ resulto to a new _Printing.sharePdf_ call.
