### ISSUE TITLE
How to print an image file stored on device's storage

### ISSUE THREAD

**Issue by Priyank-Sharma-89** [DavBfr/dart_pdf#669]
I want to print an image, which is stored in dowloads folder of device. I checked the documentation, and I see 
```dart
final pdf = await rootBundle.load('document.pdf');
```
but, this will not access file by giving path to storage.

I checked this question: https://github.com/DavBfr/dart_pdf/issues/184 , but it talks about pdf file.

Does this package works strictly only with pdf files?

**Comment by DavBfr** [comment]
This package works strictly with pdf files, yes. But you can convert your image to a pdf file easily.

```dart
final pdf = pw.Document();

final image = await rootBundle.load('assets/image.jpg');

pdf.addPage(pw.Page(
  pageFormat: format,
  build: (context) => pw.Center(
    child: pw.Image(
      pw.MemoryImage(
        image.buffer.asUint8List(),
      ),
    ),
  ),
));

final bytes = await pdf.save();
```

**Comment by soubinkittiphanh** [comment]
Can you please code on how to convert pdf to image ?

**Comment by DavBfr** [comment]
It's in the README:

```dart
await for (var page in Printing.raster(await doc.save(), pages: [0, 1], dpi: 72)) {
  final image = page.toImage(); // ...or page.toPng()
  print(image);
}
```
