### ISSUE TITLE
FlutterErrorDetails takes DiagnosticsNode as context in new version of flutter 

### ISSUE THREAD

**Issue by rmtmckenzie** [DavBfr/dart_pdf#67]
**Describe the bug**
Any project including this plugin won't compile in new version of flutter (v1.5.9-pre.135) due to FlutterErrorDetails needing a DiagnosticsNode for the 'context' property instead of what it used to need - a String.

**To Reproduce**
Switch to master flutter channel and upgrade.

**Expected behavior**
Compiles

**Comment by DavBfr** [comment]
Thanks!
