### ISSUE TITLE
Bluetooth printer not found

### ISSUE THREAD

**Issue by FilipKvestak** [DavBfr/dart_pdf#670]
Hi, my bluetooth printer is connected and works normally with other apps (Quick Printer), however it is not found when i try print with "layoutPdf" method, also listPrinters doesn't give me anything. 

Is this Android related? I don't even know where to start with this

**Comment by DavBfr** [comment]
Quick Printer is dedicated to Bluetooth ESC/POS printers. This Flutter library only works with printers installed on the system.
