### ISSUE TITLE
Printing not working in some windows devices on release mode

### ISSUE THREAD

**Issue by mjafartp** [DavBfr/dart_pdf#672]
not printing in some devices.

**Comment by DavBfr** [comment]
Any more information?

**Comment by mjafartp** [comment]
I got the issue cleared by copying fonts folder from data/flutter_assets/fonts to root folder, then the issue cleared.

on release fonts and all assets automatically copying to data/flutter_assets

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
