### ISSUE TITLE
Unable to refresh PdfPreview after changing the ui theme color.

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#677]
createPdf() {
    return PdfPreview(
      initialPageFormat: PdfPageFormat.a4,
      maxPageWidth: 700,
      build: generatePDF,
    );
  }
  
  I am trying to change the PDF theme color and update the PdfPreview(..)  with setState(){} but it is showing the old content until I reopen the PDFWidget.

**Comment by DavBfr** [comment]
@jazzbpn Can you test with the master branch?

**Comment by jazzbpn** [comment]
After testing in _master_ branch, the PDF is not getting updated with **setState(){}** callback.
