### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid page index

### ISSUE THREAD

**Issue by soubinkittiphanh** [DavBfr/dart_pdf#680]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Any reproduction code?
