### ISSUE TITLE
Working with existing PDFs

### ISSUE THREAD

**Issue by avbk** [DavBfr/dart_pdf#681]
Hi @DavBfr,

first of all thanks for your awesome work! On the pub.dev page it says that you would also provide a parsing component for a fee and one should contact you via email, but I couldn't find any on the page. Thus I'm using this issue (sorry for that). What would be the best way to get in contact?

Best regards
Alex

**Comment by Palm-Web** [comment]
Same here, interested in the signature piece. Don’t see any contact info
