### ISSUE TITLE
How to Convert a Widget to Image and Renderizar em um arquivo pdf com o dart_pdf

### ISSUE THREAD

**Issue by daniloaspk** [DavBfr/dart_pdf#682]
Guy,

I would like to ask for your help.
I am using the code in the video below to convert the widget into an image.

https://www.youtube.com/watch?v=DSJ5vONP3XM&t=13s

Everything is working fine, when I render the image on a page of my application.

Now I am trying to pass the same image to a pdf file inside the application. To achieve this goal, I am using the dart_pdf package.

I can generate a pdf file and view it in the App, but when I try to pass the image to the pdf I cannot view the pdf file, it gives an error. I've tried it in several ways but I still haven't been successful

Does anyone have any idea how I can combine the video codes with this package to be able to view the widget as an image within the pdf file?

**Comment by DavBfr** [comment]
Try with this: https://pub.dev/documentation/printing/latest/printing/WidgetWraper/fromKey.html

**Comment by daniloaspk** [comment]
Thanks for the support.

DavBrf, I saw I'm also trying to implement the solution using the code presented at https://pub.dev/packages/pdf:

`final image = pw.MemoryImage(
  File('test.webp').readAsBytesSync(),
);

pdf.addPage(pw.Page(build: (pw.Context context) {
  return pw.Center(
    child: pw.Image(image),
  ); // Center
}));`

But when we call the MemoryImage Constructor, it has an error, even when I import the painting package.

Do you know how to tell me if this error is normal is this error happening?

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by justkawal** [comment]
> Try with this: https://pub.dev/documentation/printing/latest/printing/WidgetWraper/fromKey.html

@DavBfr It will not work on web as there is no option for download to a temporary storage from the flutter web.

**Comment by d-apps** [comment]
@DavBfr Does it work with MultiPage? I have a SingleChildScrollView > Column, with big list of contents.

**Comment by d-apps** [comment]
@DavBfr Could you help me with this question about your package please? https://stackoverflow.com/questions/67680801/how-to-create-a-multi-page-pdf-in-flutter-from-widgets

**Comment by DavBfr** [comment]
@d-apps I don't know. Never tested.
