### ISSUE TITLE
Printing long POS receipt 

### ISSUE THREAD

**Issue by Maged12** [DavBfr/dart_pdf#683]
**Describe the bug**
when i try to printing a log POS receipt it only print the first part of it 

**To Reproduce**
Code snippet to reproduce the behavior:

await Printing.directPrintPdf(
          printer: Printer(url: usbPrinter),
          onLayout: (PdfPageFormat format) async => _pdf.save(),
          dynamicLayout: false,
          format: PdfPageFormat.roll80);

**Expected behavior**
it should print all the pdf because when i use my browser to print it ,it printing all of it not only a small part as this package

**Screenshots**

![WhatsApp Image 2021-05-08 at 9 35 30 PM](https://user-images.githubusercontent.com/34436039/117554480-54b9b780-b058-11eb-8fd5-e73240ef827d.jpeg)

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [*] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
I don't have a POS printer.

**Comment by luis901101** [comment]
I have a similar problem here, the thing in my case is that `directPrintPdf` is ignoring the specified format. This is my code:
```dart
Printing.directPrintPdf(
  printer: selectedPrinter,
  onLayout: (format) => pdfBytes,
  format: PdfPageFormat(3.15 * PdfPageFormat.inch , 6.62 * PdfPageFormat.inch),
  dynamicLayout: true,
);
```
The output is not taking into account the width/height specified in format but the printer page size format.
If I try with `dynamicLayout: false,` then output is blank and format remains the same as printer page size format.
**Note: I'm testing with Printer Simulator cause I don't have a physical AirPrint printer at hand**
Is this problem because of using Printer Simulator?, or custom format can't be specified in `directPrintPdf` for all printers? How to know when I can set custom format for `directPrintPdf` or is this not possible?

**Comment by DavBfr** [comment]
@luis901101 the format here is just a hint for the platform, but in the end, only the real paper format is used.
Your issue is certainly because of the simulator, but you can use a different paper format with the simulator.

**Comment by anandsubbu007** [comment]
facing same issue
may i know how to print a long POS Receipt?

**Comment by Maged12** [comment]
it is just because of the format so i had searched for a suitable format and i made it like that :
format: const PdfPageFormat(204, 842),
and it works pretty well for me so you can try it and tell me

**Comment by anandsubbu007** [comment]
still facing same issue

> it is just because of the format so i had searched for a suitable format and i made it like that : format: const PdfPageFormat(204, 842), and it works pretty well for me so you can try it and tell me

**Comment by techttiru** [comment]
> still facing same issue
> 
> > it is just because of the format so i had searched for a suitable format and i made it like that : format: const PdfPageFormat(204, 842), and it works pretty well for me so you can try it and tell me

@anandsubbu007 I tried the below setting for thermal printer (USB) and its aligned to default settings.

i just took the default setting of PdfPageFormat.roll80 and adjusted the right side margin based on the need because i saw truncation on the right side alone when we print in real device. Since this setting had default margin of 5 * mm in all side. so adjusted the right side margin alone 15 times instead of 5 times.

```
    const double inch = 72.0;
    const double mm = inch / 25.4;

      pageFormat: const PdfPageFormat(80 * mm, double.infinity,
              marginTop: 5 * mm,
              marginBottom: 5 * mm,
              marginLeft: 5 * mm,
              marginRight: 15 * mm),
```

**Comment by techttiru** [comment]
How to connect the USB POS printer? I dont want to connect via ip address. if USB printer is connect in widows system, then i should be able to send the print to default assigned printer. is that possible in flutter web application?

**Comment by techttiru** [comment]
> usbPrinter

@Maged12 Hi, in my flutter web app, i am unable to connect the USB printer. can you share how did you connect the USB printer in your applications? how did you find the url for USB printer? my printer does not support anything other than USB interface. I see the below in your post but how did you find the URL for USB printer?
printer: Printer(url: usbPrinter),

Can we connect USB printer in flutter web app?

**Comment by Doublelae** [comment]
I found  solution for long slip voucher  =>

  await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => doc.save(),format:is80? PdfPageFormat.roll80: PdfPageFormat.roll57); 
    
  
![20240524-154814](https://github.com/DavBfr/dart_pdf/assets/107450659/5440b984-d52c-4690-8a84-0d59362741de)
![20240524-154830](https://github.com/DavBfr/dart_pdf/assets/107450659/7d3c4ebb-c2cb-4894-b4c4-92af24cf6430)

**Comment by shobhit207200** [comment]
> I found solution for long slip voucher =>
> 
> await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => doc.save(),format:is80? PdfPageFormat.roll80: PdfPageFormat.roll57);
> 
> ![20240524-154814](https://private-user-images.githubusercontent.com/107450659/333529385-5440b984-d52c-4690-8a84-0d59362741de.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjY2NzcsIm5iZiI6MTcxNjYyNjM3NywicGF0aCI6Ii8xMDc0NTA2NTkvMzMzNTI5Mzg1LTU0NDBiOTg0LWQ1MmMtNDY5MC04YTg0LTBkNTkzNjI3NDFkZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMDgzOTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE1Yjg5ZGU0Mzk1Mjc5MDI4ZDJmZmMyZWQ4MDIwNTJiNWE4NzgzYjkxZWY2OWJmNDhiZjBjMTYxN2QwYzRlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vo30o2vDEzpFNharI7-PD2czWLDXU0jxFpq_HGB2qyY) ![20240524-154830](https://private-user-images.githubusercontent.com/107450659/333529400-7d3c4ebb-c2cb-4894-b4c4-92af24cf6430.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjY2NzcsIm5iZiI6MTcxNjYyNjM3NywicGF0aCI6Ii8xMDc0NTA2NTkvMzMzNTI5NDAwLTdkM2M0ZWJiLWMyY2ItNDg5NC1iNGM0LTkyYWYyNGNmNjQzMC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMDgzOTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U5YWU0NDU2YmJhNGUwZDE2YzYyYmVmMjgxMWM5OThiZjAxNmFjNmVlNjBjYjljNjI1MmZiYjJmNWMxZDQwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7L60v8oX-fa-TjbuavrhwSEV6g9ktOP0vgdUDJHRsrc)



Hi, 
Im using pageFormat: PdfPageFormat.roll80, this as well but my paper print size is less.
What exactly did you use?
Could you share your code snipet?

**Comment by Doublelae** [comment]
@shobhit207200  

 first create doc  with PdfPageFormat.roll80 then  add  follow code 
 await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => doc.save(),format: PdfPageFormat.roll80);

**Comment by alimcomp** [comment]
Everyone face this issue 
Just play with width 
like 
Use format like ` PdfPageFormat(72 * PdfPageFormat.mm, double.infinity, marginAll: 5 * PdfPageFormat.mm`) instead of `PdfPageFormat.roll80`

**Comment by josianascanio** [comment]
Hi, i have the same issue and i resolve this whit 

```
   await Printing.directPrintPdf(
                      printer: defaultPrinter,
                      usePrinterSettings: true,
                      dynamicLayout: true,
                      onLayout: (_) => pdfBytes,
                    );
```

the key its  **usePrinterSettings: true** , plus you can use **dynamicLayout: true**
whit that the driver of the printer have the control to cut at the end of the document
