### ISSUE TITLE
PDF files are not generated when trying to express superscript numeric characters

### ISSUE THREAD

**Issue by daniloaspk** [DavBfr/dart_pdf#685]
DavBfr,

I was here trying to implement an output in pdf file with some numbers in superscript. However, when using unicode characters, the pdf is not generated.

Was it a bug?

**Comment by DavBfr** [comment]
What is the code, and the error?

**Comment by daniloaspk** [comment]
DavBfr I'm sorry. I just found out that some unicode codes for characters in sub or superscript don't work, even in the basic use of the flutter. So it is not a bug.

I saw some suggestions in this link:

So I'm implementing the RichText () widget to solve sub and superscript character editing

> What is the code, and the error?
