### ISSUE TITLE
Multiple image in single table row cell error

### ISSUE THREAD

**Issue by jpChan015** [DavBfr/dart_pdf#688]
**Describe the bug**
Table with a table row of column of images throw an error. 
`Exception: This widget created more than 20 pages. This may be an issue in the widget or the document. See https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html`

**To Reproduce**
Code snippet to reproduce the behavior

`final doc = Document();

    var tempImage = await imageFromAssetBundle('assets/image.png');

    final tableRows = [
      TableRow(
        children: [
          Text(
            '1',
          ),
          Text(
            '1',
          ),
          Text(
            '1',
          ),
          Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Flexible(
                child: Image(
                  tempImage,
                ),
              ),
              Flexible(
                child: Image(
                  tempImage,
                ),
              ),
            ],
          ),
        ],
      ),
      TableRow(
        children: [
          Text(
            '2',
          ),
          Text(
            '2',
          ),
          Text(
            '2',
          ),
          Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Flexible(
                child: Image(
                  tempImage,
                ),
              ),
              Flexible(
                child: Image(
                  tempImage,
                ),
              ),
            ],
          ),
        ],
      ),
    ];

    final _tempTable = Table(
      border: TableBorder.all(),
      children: tableRows,
    );

    doc.addPage(
      MultiPage(
        pageFormat: PdfPageFormat(
          PdfPageFormat.legal.height,
          PdfPageFormat.legal.width,
          marginAll: PdfPageFormat.legal.height * 0.01,
        ),
        crossAxisAlignment: CrossAxisAlignment.start,
        orientation: PageOrientation.landscape,
        build: (Context context) {
          return <Widget>[
            _tempTable,
          ];
        },
      ),
    );`

**Comment by DavBfr** [comment]
That's because your image is bigger than a page, try to use SizedBox or ConstrainedBox with your image to limit its size.
