### ISSUE TITLE
Where I can get basic Flutter app Example using pdf plugin?

### ISSUE THREAD

**Issue by NTMS2017** [DavBfr/dart_pdf#69]
I am new to this plugin please bear with me.

I have basic flutter app. It has a small form with collects 4 value from user. Also user provides 2 images using camera.  I need to create a pdf file before sending via email.

The example is using void main to create a pdf page. In my scenario user must save the form and after saving form and capturing 2 images I need to send the values to another stateful dart file (my_pdf.dart) In new stateful dart file I need to create a pdf and save it to temp directory.

After saving the file I need to send file name (maybe path) to another stateful dart file. The last dart file will loads the pdf file from temp directory and attach to email so user can send the mail with created pdf file.

So being to new this plugin, I can't work it out how to create a pdf file from another stateful class (dart file).

I will be glad if you can show me detail instruction for creating a pdf. Thanks

Kind Regards

**Comment by DavBfr** [comment]
See https://pub.dev/packages/printing
