### ISSUE TITLE
IOS Issue

### ISSUE THREAD

**Issue by profiteroles** [DavBfr/dart_pdf#690]
**Describe the bug**

    /Users/erol/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/printing-5.2.1/ios/Classes/PrintJob.swift:200:96: error: editor placeholder in source file
            let activityViewController = UIActivityViewController(activityItems: [fileURL, body ?? <#default value#>], applicationActivities: nil)
                                                                                          ^
    /Users/erol/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/printing-5.2.1/ios/Classes/PrintJob.swift:200:96: error: editor placeholder in source file
            let activityViewController = UIActivityViewController(activityItems: [fileURL, body ?? <#default value#>], applicationActivities: nil)

target 'Runner' do
   use_frameworks!

is already in the podfile

**Comment by DavBfr** [comment]
@profiteroles that is not my code, something has been modified on your computer.
Please delete the folder /Users/erol/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/printing-5.2.1 and try again.

**Comment by profiteroles** [comment]
Thank you very much you David. That solved the problem 👯

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
