### ISSUE TITLE
Corrupted PDF

### ISSUE THREAD

**Issue by Nikhil277** [DavBfr/dart_pdf#691]
I have been trying to integrate the pdf library. So I just copy pasted the example provided to create a pdf file. On save, the pdf is generated, but the file cannot be opened, it says it is corrupted. Tried on iOS as well as android. Both case fails. It seems no one else have a similar issue, so must be something I am doing wrong. 

Please find my code below:

`import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class GeneratePDF {
  final pdf = pw.Document();

  writeOnPdf(){
    final pdf = pw.Document();

    pdf.addPage(pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Text("Hello World"),
          ); // Center
        }
      )
    ); // Pa
  }

  savePdf() async{
    Directory documentDirectory = await getApplicationDocumentsDirectory();
    String documentPath = documentDirectory.path;
    File file = File("$documentPath/example.pdf");
    await file.writeAsBytes(await pdf.save());
  }
}`

The error message when I try to open the file: "It may be damaged or use a file format that Preview doesn’t recognise."

**Comment by DavBfr** [comment]
Your code is wrong. Don't store the variable `pdf` into a class member and you'll see your error.
