### ISSUE TITLE
Special Characters Like Rupees Symbol is Giving Error

### ISSUE THREAD

**Issue by keshavOneLap** [DavBfr/dart_pdf#697]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavBfr** [comment]
Not enough information.

**Comment by WasimMemon** [comment]
Is this feature added ?
I am still facing issue while printing rupee symbol and '\u20B9' with this also.

library
pdf: ^3.8.4
printing: ^5.9.3

Flutter version - 3.3.10

Getting error message "flutter: Unable to find a font to draw "₹" (U+20b9) try to provide a TextStyle.fontFallback"

<img width="185" alt="image" src="https://user-images.githubusercontent.com/6543095/214112469-d7f7ed8f-5fd2-4040-9c05-653aa2e95d1a.png">
