### ISSUE TITLE
[Question] Margin when convertHtml to PDF on android device

### ISSUE THREAD

**Issue by HaoLC** [DavBfr/dart_pdf#698]
I try convert html to PDF, However, I still see margin in the PDF page. Is there any way to remove it?

My code: 
```dart
Future<Uint8List> generatePdf() async {
    var _response =
        await ProductHubPKG.of(state).getOrderInvoice(state.widget.orderID);
    if (_response != null) {
      htmlValue = _response.toString();
      var _data = await Printing.convertHtml(
        format: PdfPageFormat(PaperSize.mm58.width.toDouble(), 25 * 110 / 100,
            marginAll: 0),
        html: htmlValue,
      );
      _pdfHeight = await Printing.raster(_data, dpi: 300).length;
    }
    image = await Printing.convertHtml(
      format: PdfPageFormat(
              PaperSize.mm58.width.toDouble(), 25 * 110 / 100 * _pdfHeight,
              marginTop: 0.0,
              marginBottom: 0.0,
              marginLeft: 0.0,
              marginRight: 0.0,
              marginAll: 0)
          .applyMargin(left: 0, top: 0, right: 0, bottom: 0),
      html: htmlValue.replaceFirst("background-color: #FFFFFF", "background-color: #FFDFFF"),
    );
    return image;
  }
```

And result:
![image](https://user-images.githubusercontent.com/26896377/119601694-e3c61e00-be13-11eb-92f8-62dbe192a0d1.png)

**Comment by DavBfr** [comment]
Can it be a default HTML margin on <html> or <body>?

**Comment by supermnemonic** [comment]
this also happens to me. the problem only exist on Android. any idea?

**Comment by winneze1** [comment]
> I try convert html to PDF, However, I still see margin in the PDF page. Is there any way to remove it?
> 
> My code:
> 
> ```dart
> Future<Uint8List> generatePdf() async {
>     var _response =
>         await ProductHubPKG.of(state).getOrderInvoice(state.widget.orderID);
>     if (_response != null) {
>       htmlValue = _response.toString();
>       var _data = await Printing.convertHtml(
>         format: PdfPageFormat(PaperSize.mm58.width.toDouble(), 25 * 110 / 100,
>             marginAll: 0),
>         html: htmlValue,
>       );
>       _pdfHeight = await Printing.raster(_data, dpi: 300).length;
>     }
>     image = await Printing.convertHtml(
>       format: PdfPageFormat(
>               PaperSize.mm58.width.toDouble(), 25 * 110 / 100 * _pdfHeight,
>               marginTop: 0.0,
>               marginBottom: 0.0,
>               marginLeft: 0.0,
>               marginRight: 0.0,
>               marginAll: 0)
>           .applyMargin(left: 0, top: 0, right: 0, bottom: 0),
>       html: htmlValue.replaceFirst("background-color: #FFFFFF", "background-color: #FFDFFF"),
>     );
>     return image;
>   }
> ```
> 
> And result:
> ![image](https://user-images.githubusercontent.com/26896377/119601694-e3c61e00-be13-11eb-92f8-62dbe192a0d1.png)

Can I have for the print function. The image I print is not the right format and blurry.
