### ISSUE TITLE
Support for otf fonts

### ISSUE THREAD

**Issue by Paul-cbt** [DavBfr/dart_pdf#699]
**Issue:**
I have found no way to use otf fonts with Flutter pdf

**Possible solutions:**
The best would be if we could import otf fonts the same was as ttf fonts

**Possible alternatives:**
Allow us to give a secondary font incase the character isn't supported by the main font, when I declare the font in ThemeData.withFont and then with Font.ttf("pathToFont"), I didn't find any way to declare a secondary font.

**Additional context**
The only solution I found way using a massive ttf font such as arial unicode ms, but it would add 100 mo to the app.... Eventually it could be downloaded afterward, but then it will use a massive amount of data on the web version..

If you can add support for otf it would be amazing, or if anyone has another solution...
Thanks a lot, you're package is really great!

**Comment by DavBfr** [comment]
The PDF file format only supports TTF fonts

**Comment by cuishijie1991** [comment]
> The PDF file format only supports TTF fonts

otf fonts was supported since pdf 1.6, is there any plan to support otf fonts?
