### ISSUE TITLE
Arabic fonts support

### ISSUE THREAD

**Issue by NafissaBHJ** [DavBfr/dart_pdf#700]
**Describe the bug**
Hello, I'm trying to create a file with arabic strings but I'm getting an error 
" Unhandled Exception: 'package:pdf/src/pdf/ttf_writer.dart': Failed assertion: line 93 pos 18: 'glyph.compounds.isEmpty': This is not a simple glyph"

**To Reproduce**

 final Uint8List fontData =   File('assets/fonts/ReemKufi-Regular.ttf').readAsBytesSync();
    final ttf = pw.Font.ttf(fontData.buffer.asByteData());
    final pdf = pw.Document();
   
    pdf.addPage(
      pw.Page(
          build: (pw.Context context) => pw.Container(
                child: pw.Column(
                  children: [
                    pw.Column(
                      children: [
                        pw.Text(
                          "اهلا و سهلا",
                          style: pw.TextStyle(
                              font: ttf,
                              fontSize: 40),
                        ),
                        pw.Text(
                          " مرحبا",
                          style: pw.TextStyle(
                              font:ttf,
                              fontSize: 20),
                        )
                      ],
                    ),
                    pw.Text(
                      "طلب تسجيل",
                      style: pw.TextStyle(
                          font: ttf,
                          fontSize: 20),
                    ),
                  ],
                ),
              )),
  final output = await getApplicationDocumentsDirectory();
    final file = File("${output.path}/example.pdf");
    await file.writeAsBytes(await pdf.save());

**Flutter Doctor**
all right

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [x ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by doppio** [comment]
@NafissaBHJ Did you find a fix for this? I have a similar issue.

**Comment by HuseynHuseyni** [comment]
@NafissaBHJ Did you find a fix for this? I have a similar issue.

**Comment by NafissaBHJ** [comment]
Yes I used the below code instead :
   final ByteData fontData = await rootBundle.load("fonts/arial.ttf");
    final ttf = pw.Font.ttf(fontData);
    final pdf = pw.Document();
