### ISSUE TITLE
Failed to capture the image from the screen using WidgetWraper.fromKey

### ISSUE THREAD

**Issue by d-apps** [DavBfr/dart_pdf#701]
**Describe the bug**
I am trying to capture the image from the screen using WidgetWraper.fromKey but I always get empty and null values from it and the PdfPreview gets stuck in loading.

I already tried to move the RepaintBoundary to other childs but I had the same problem.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Future<void> generatePdf() async {

    final image = await WidgetWraper.fromKey(
      key: repaintBoundaryKey,
    );

    final pdf = pw.Document();

    pw.Page(
        build: (context){
          return pw.Container(
            child: pw.Image(
               image
            )
          );
        }
      );


    Get.dialog(PdfPreview(build: (format) =>  pdf.save()));

  }
```

**Screenshots**

![image](https://user-images.githubusercontent.com/20110433/119837682-33225200-bed9-11eb-983e-0fcf402e5521.png)

I got stuck on this loading when I call `PdfPreview()`

![image](https://user-images.githubusercontent.com/20110433/119837434-f6565b00-bed8-11eb-9624-6226b481ba54.png)

When I debug what is returning from WidgetWraper.fromKey I have this:

![image](https://user-images.githubusercontent.com/20110433/119837573-184fdd80-bed9-11eb-8d79-19367e9b5ea7.png)

**Flutter Doctor**
Flutter (Channel stable, 2.2.0, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (13 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.985]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anandsubbu007** [comment]
when using above code
```
════════ Exception caught by printing ══════════════════════════════════════════
The following _CastError was thrown while generating a PDF:
type 'Future<ByteData?>' is not a subtype of type 'FutureOr<ByteData>' in type cast

When the exception was thrown, this was the stack
#0      WidgetWraper.fromKey
package:printing/src/widget_wrapper.dart:82
<asynchronous suspension>
#1      _DetReportPGState._printScreen.<anonymous closure>
package:billing_app/…/DetailedReport/DetReportPG.dart:88
<asynchronous suspension>
#2      MethodChannelPrinting._handleMethod
package:printing/src/method_channel.dart:63
...
PageFormat: "Page 595.3199999999999x841.92 margins:0.0, 0.0, 0.0, 0.0"
════════════════════════════════════════════════════════════════════════════════

```

**Comment by DavBfr** [comment]
Fixed in the master branch.
