### ISSUE TITLE
Delete page at index from the document

### ISSUE THREAD

**Issue by AhmedAbouelkher** [DavBfr/dart_pdf#702]
**Is your feature request related to a problem? Please describe.**
I want to be able to edit my pages in the document [add, edit and delete].

**Describe the solution you'd like**
Add a delete method like `addPage` and `editPage`, and give the developers access to the private property `_pages` in `Document` class.

**Describe alternatives you've considered**
I don't see that the issue is complicated to consider an alternative.

**Comment by DavBfr** [comment]
A  `deletePage()` method is possible, but it will only delete the page from the catalog, all the content and images will still be embedded into the document.
What is the use case? Why can't you just omit the page when you generate the document?

**Comment by AhmedAbouelkher** [comment]
> A `deletePage()` method is possible, but it will only delete the page from the catalog, all the content and images will still be embedded into the document.
> What is the use case? Why can't you just omit the page when you generate the document?

I think omitting the page when you generate the document is a great idea.
