### ISSUE TITLE
[feature-request] Render to SVG instead of PNG in layout pdf

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [DavBfr/dart_pdf#703]
**Is your feature request related to a problem? Please describe.**
Sometimes, users might like to zoom into the rendered pdf. Theoretically, that's possible but there are quite a few issues:
- either the zoomed pdf gets pixilated (as soon as you zoom in too much)
- or the pdf needs to be re-rendered again and again (which is very inefficient and even almost impossible on low-end devices)

**Describe the solution you'd like**
My idea is to render PDFs to SVGs in the native code instead of a bitmap. This would allow to zoom in as much as users want and would decrease rendering effort for the devices.

**Describe alternatives you've considered**
Good questions... I am currently workarounding the issue by re-rendering the pdf when zooming in too much. But the more you zoom in the larger the rendered bitmap becomes and the more laggy the application becomes.

**Additional context**
*Nope.*

**Comment by DavBfr** [comment]
I don't think that's possible, and it can result in a huge SVG file. You can use another pdf preview plugin based on platform view if this one is not enough for you. If you target WEB, there is no alternative.
