### ISSUE TITLE
Roboto Font

### ISSUE THREAD

**Issue by tsinis** [DavBfr/dart_pdf#705]
**Describe the solution you'd like**
Hey! @DavBfr, thanks for a great package. Since Flutter offering a whole **_Roboto_** Font Family (all weights + italics) by default — can you provide a way to use it in generated PDF?

**Describe alternatives you've considered**
Roboto can be used as external asset font, but it's pretty ugly since it will be duplicated (near the default font)...

**Additional context**
It might very helpful since Roboto supports almost all languages.

**Comment by DavBfr** [comment]
The flutter-provided fonts are not available to dart, only to the c++ engine.

**Comment by tsinis** [comment]
:( ok then, I'm closing it. Thanks for the info anyway!
