### ISSUE TITLE
Lost connection to device

### ISSUE THREAD

**Issue by SayeedAfridi** [DavBfr/dart_pdf#706]
I want to print a flutter widget in Linux machine.
My dependencies:
`pdf: ^3.3.0
  printing: ^5.2.1
`

My build function
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: PdfPreview(
        build: (format) => _generatePdf(format, 'test'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          await Printing.layoutPdf(
              onLayout: (format) => _generatePdf(format, 'Test'));
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }

And my _generatePdf function:
Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) => pw.Center(
          child: pw.Text('Hello World!'),
        ),
      ),
    );

    return pdf.save();
  }

And the error I get from the printing:

/build/libproxy-1BEpaZ/libproxy-0.4.15/libmodman/module_manager.hpp:58: std::vector<T*> libmodman::module_manager::get_extensions() const [with T = libproxy::network_extension]: Assertion `obj != NULL' failed.
Lost connection to device.

TIA.

**Comment by DavBfr** [comment]
Yes I had this too. If you run the code from the command line (flutter run) or a release build: it works.

**Comment by SayeedAfridi** [comment]
Thanks..
