### ISSUE TITLE
Discover index for first page of a `MultiPage`

### ISSUE THREAD

**Issue by ShannonHall** [DavBfr/dart_pdf#707]
**Is your feature request related to a problem? Please describe.**

When adding various `MultiPage` items to a PDF there is no way to know how many pages the multipage consumes or access the first page of the MultiPage in order to modify the header of only the first page of the `MultiPage`.

**Describe the solution you'd like**

```...
myPdf.addPage(
  MultiPage(
    header: (Context context) {
      //discover first page of this MultiPage here ???
      if(isFirstPage) {
        return Header()
      }
    }
  )
)

myPdf.addPage(
  MultiPage(
    header: (Context context) {
      //discover first page of this MultiPage here ???
      if(isFirstPage) {
        return Header()
      }
    }
  )
)
...
```
**Describe alternatives you've considered**

I have considered not using a header and having the first child of the `MultiPage` act as a header, this doesn't work because all other pages of the `MultiPage` will now be missing a header.
I tried to find data to achieve my goal from the `Context` however i cannot find a way to distinguish the first page of a `MultiPage`.

**Additional context**

Perhaps there is a different approach to achieve my goal i am unaware of. I have different sections in the pdf that begin on a new page. Currently i add a `MultiPage` for each section.

**Comment by DavBfr** [comment]
You can use `context.pageNumber`

**Comment by ShannonHall** [comment]
> You can use `context.pageNumber`

Is this example here the first `MultiPage`  is a dynamic length. How do i use `context.pageNumber` to find the **first** page of the following `MultiPage` ? I understand it holds the current page, but is that page the first page of the given `MultiPage`?

```myPdf.addPage(
  MultiPage(
    header: (Context context) {
      //discover first page of this MultiPage here ???
      if(isFirstPage) {
        return Header()
      }
    }
  )
)

myPdf.addPage(
  MultiPage(
    header: (Context context) {
      //discover first page of this MultiPage here ???
      if(isFirstPage) {
        return Header()
      }
    }
  )
)```

**Comment by DavBfr** [comment]
It's the global page number starting from 0. The goal is to print the page number on the page in the header or footer. The body of MultiPage doesn't know about the page number.

In all cases, you can do something like: 

```dart
var isFirstPage = true;

myPdf.addPage(
  MultiPage(
    header: (Context context) {
      //discover first page of this MultiPage here ???
      if(isFirstPage) {
        isFirstPage = false;
        return Header()
      }
    }
  )
)
```

**Comment by ShannonHall** [comment]
> It's the global page number starting from 0. The goal is to print the page number on the page in the header or footer. The body of MultiPage doesn't know about the page number.
> 
> In all cases, you can do something like:
> 
> ```dart
> var isFirstPage = true;
> 
> myPdf.addPage(
>   MultiPage(
>     header: (Context context) {
>       //discover first page of this MultiPage here ???
>       if(isFirstPage) {
>         isFirstPage = false;
>         return Header()
>       }
>     }
>   )
> )
> ```

I understand this. What I am asking is for a way to know the first page of a given `MultiPage` So we can customise the header of that section.

Is there a way to get the page of a given  _widget_? That would also provide the same functionality.
