### ISSUE TITLE
onLayout is not called again when the user changes a printer setting on web

### ISSUE THREAD

**Issue by doppio** [DavBfr/dart_pdf#709]
**Describe the bug**
The `onLayout` callback provided to `Printing.layoutPdf` is not called when the user changes a setting like page format or orientation in Chrome. This can be demonstrated in the official Live Demo by selecting the print icon button, then changing the page format in the Chrome print window. The document will still be laid out using the old page format, not adjusted for the new settings. The same behavior can be observed in Safari.

**Expected behavior**
The documentation for `Printing.layoutPdf` states "the Pdf document is re-built in a LayoutCallback each time the user changes a setting like the page format or orientation" but this doesn't seem to be the case. It is only once, and the document does not get laid out again when the user changes their print settings in the system UI.

**Flutter Doctor**
<details>
[✓] Flutter (Channel dev, 2.3.0-12.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.3.0-12.1.pre at /Users/bryson/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9c825981c (2 weeks ago), 2021-05-18 14:07:52 -0700
    • Engine revision 26e217e6c3
    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bryson/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
</details>

**Environment (please complete the following information):**
MacOS Big Sur 11.2.3 using Chrome Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by DavBfr** [comment]
@doppio Chrome will not trigger any event when the user changes a setting. There is no real print API on web browsers.

**Comment by doppio** [comment]
@DavBfr Okay, I thought maybe that was the case. Thanks for the response, I'll close this.
