### ISSUE TITLE
Does printing example supports ISO-8859-9 - Latin 5?

### ISSUE THREAD

**Issue by NTMS2017** [DavBfr/dart_pdf#71]
I download the  printing example and run. I got bellow error saying that invalid characters.
Does printing examples supports ISO-8859-9 - Latin 5 (Same as 8859-1 except for Turkish instead of Icelandic)? 

Do you plan to support ISO-8859-9 - Latin 5? 

Thank you for great plugin

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following ArgumentError was thrown running a test:
Invalid argument (string): Contains invalid characters.: "İş"

**Comment by DavBfr** [comment]
If you want to use non-Latin characters, you need to use TTF font that supports them. I think any TTF font will work for ISO-8859-9.
Look at the file https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/ttf_test.dart

**Comment by NTMS2017** [comment]
Thank you I will try.
