### ISSUE TITLE
 [feature-request] Need to render network image in to pdf

### ISSUE THREAD

**Issue by agrawalharsh90** [DavBfr/dart_pdf#710]
Is your feature request related to a problem? Please describe.
Sometimes, We might like to generate pdf of your portfolio as there are images uploaded by users. 

Describe the solution you'd like
My idea is to render PDFs and allow us to render network image in it.

Describe alternatives you've considered
Nope.

Additional context
Nope.

**Comment by DavBfr** [comment]
You can generate a SVG and render it with the pdf library

**Comment by agrawalharsh90** [comment]
> You can generate a SVG and render it with the pdf library

But, as I have a use case as to generate portfolio of every users so there are many image(>10) in it so unable to handle loading. 

Can you please help me in the above?

**Comment by DavBfr** [comment]
I don't understand what you need

**Comment by agrawalharsh90** [comment]
As, i need to create a catalogue/portfolio pdf for a particular business, so that user can share it for there business expansion.
So, i am taking user's business details and all the item details including there images, i am facing issue in creation of such pdf which contains all that items image.

**Comment by DavBfr** [comment]
And what's your issue? Just adding an image?

**Comment by agrawalharsh90** [comment]
yes network image in grid format

**Comment by DavBfr** [comment]
Use a Grid or Wrap widget and load the images with `networkImage` from the package printing.

**Comment by agrawalharsh90** [comment]
network image is not working in pdf

**Comment by DavBfr** [comment]
Look at this example:
https://github.com/DavBfr/dart_pdf/wiki/Network-Image
