### ISSUE TITLE
Header and footer builder functions called twice for each page generated 

### ISSUE THREAD

**Issue by bruntzcreative** [DavBfr/dart_pdf#712]
**Describe the bug**

When adding a multipage the header and footer builders are called twice for each page. 

**To Reproduce**
Code snippet to reproduce the behavior:
runnable repo: https://github.com/bruntzcreative/pdf_issue

```dart
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'dart:math' as math;

import 'package:printing/printing.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return PdfPreview(
        allowPrinting: false,
        allowSharing: true,
        canChangePageFormat: false,
        canChangeOrientation: false,
        build: (format) => createPDF().save());
  }

  final random = math.Random();

  pw.Document createPDF() {
    var pdf = pw.Document();
    var bodyMultiPageCount = 0;
    var headerMultiPageCount = 0;
    var footerMultiPageCount = 0;
    pdf.addPage(
      pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          header: (context) {
            headerMultiPageCount++;
            return pw.Header(level: 0, text: 'MULTIPAGE HEADER COUNT: $headerMultiPageCount, PAGE NUMBER: ${context.pageNumber}');
          },
          build: (context) {
            bodyMultiPageCount++;
            return List.generate(
              random.nextInt(100 - 50),
              (index) => pw.Padding(
                padding: pw.EdgeInsets.symmetric(horizontal: 30, vertical: 150),
                child: pw.Text(
                    'Dynamic Content\nLIST INDEX: ${index + 1}\nMULTIPAGE BODY COUNT, $bodyMultiPageCount '),
              ),
            );
          },
          footer: (context) {
            footerMultiPageCount++;
            return pw.Header(level: 0, text: 'MULTIPAGE FOOTER COUNT: $footerMultiPageCount, PAGE NUMBER: ${context.pageNumber}', );
          }),
    );
    return pdf;
  }
}

```

**Expected behavior**

Header and footer builders to be called once so we can perform operations there based on a local count or boolean. 

**Screenshots**

**Flutter Doctor**

```
➜  pdf_issue git:(main) ✗ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale en-AU)
    • Flutter version 2.2.0 at /Users/shannonhall/Desktop/development/flutter
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shannonhall/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

```

**Desktop (please complete the following information):**
 - [✓] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by flabbyandroid** [comment]
my bug using this pdf plugin, ~
in my current activity, i passed a list for my table, and when i run generate the pdf the data is correct ,
but without changing to another screen, when i tried to generate again the pdf after changing the data list, my pdf printed out the same old data, but only some blank page was added below the new pdf file generated,, hmmm

**Comment by bruntzcreative** [comment]
> my bug using this pdf plugin, ~
> in my current activity, i passed a list for my table, and when i run generate the pdf the data is correct ,
> but without changing to another screen, when i tried to generate again the pdf after changing the data list, my pdf printed out the same old data, but only some blank page was added below the new pdf file generated,, hmmm
> mybe im very new in these flutter, so not have that much knowledge in android activity..

Is this related to the issue?

**Comment by DavBfr** [comment]
@flabbyandroid That's because you reuse a Document() object multiple times. You have to recreate a new one each time you create a new pdf document.

**Comment by DavBfr** [comment]
This is not a bug, it's required in order to get the page number.
The first build is not painted but used to calculate the final header size.
The second build is for the final paint, and `context.pageNumber` is populated correctly.

**Comment by flabbyandroid** [comment]
> @flabbyandroid That's because you reuse a Document() object multiple times. You have to recreate a new one each time you create a new pdf document.

thank you soo much for this, it explained a lot, still need more to learn, thank you sir @DavBfr !!

**Comment by bruntzcreative** [comment]
> This is not a bug, it's required in order to get the page number.
> The first build is not painted but used to calculate the final header size.
> The second build is for the final paint, and `context.pageNumber` is populated correctly.

OK thanks
