### ISSUE TITLE
Request for pull request.

### ISSUE THREAD

**Issue by bruntzcreative** [DavBfr/dart_pdf#713]
**Is your feature request related to a problem? Please describe.**
Cannot hide the debug switch in `Printing` package `PdfPreview` widget.

**Describe the solution you'd like**
Add a boolean value `canDebug` to `PdfPreview` to allow it to be toggled.

**Describe alternatives you've considered**
I have made the adjustments in a fork and would like to do a pull request.

**Comment by DavBfr** [comment]
@bruntzcreative yes, please do a PR.

**Comment by DavBfr** [comment]
PR #715 merged
