### ISSUE TITLE
convert flutter widget to pw widget 

### ISSUE THREAD

**Issue by hussam132** [DavBfr/dart_pdf#714]
Is there possible way to redraw Flutter widget inside PDF file automatically whit out doing this manually 
for example a method that will take this widget as argument 

```dart
class TestingPDFFile extends StatelessWidget {
  const TestingPDFFile({ Key key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(children: [Text('one'),Image.file(File('path to image')),Text('image title'),],
      
    );
  }
}
```
and this method will create pdf file with one page that contain the column with text ,image and text as the column children
if this's possible I want some hints to start with
thanks in advance

**Comment by DavBfr** [comment]
No that's not possible: The Pdf library mimics the Flutter library but it's not the same Widgets at all.
