### ISSUE TITLE
Problem with width of columns in Table.fromTextArray

### ISSUE THREAD

**Issue by jmpavan** [DavBfr/dart_pdf#716]
873 / 5000
Resultados de traducción
I am generating a PDF file with an A4 size sheet containing tables of the type Table.fromTextArray. If the number of columns in the table are 4 or 5 I do not find major problems, but if the table contains many columns, 20 for example, they adjust to the width of the page (A4) by wrapping them, and being unfriendly to the sight and very difficult to understand. How can I get the first 5 columns to be generated on page 1, the next 5 on page 2, the next ... and so on.

Attached examples:

- Test_1.pdf: Generated on an A4 size sheet and showing my problem

- [Test_2.pdf:]([Test_2.pdf](https://github.com/DavBfr/dart_pdf/files/6599274/Test_2.pdf)
[Test_1.pdf](https://github.com/DavBfr/dart_pdf/files/6599275/Test_1.pdf)
) The same table printed on a size sheet:

PdfPageFormat pf = PdfPageFormat (120 * PdfPageFormat.cm, 120 * PdfPageFormat.cm, marginAll: 2.0 * PdfPageFormat.cm);

I hope you can guide me, I await your comments. Thank you

**Comment by DavBfr** [comment]
You'll have to do it manually, there is no magic rendering here.
