### ISSUE TITLE
Image Assets and Designing

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [DavBfr/dart_pdf#718]
I am very new to pdf package and I want to see the limits of this package firstly I want to know how can I use asset images I searched YouTube videos but can not find anything can anyone help me?

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

is how I imported ^

also I wanted to know can you do and create anything with pw widgets that you can with flutter widgets for example making containers using gradients shadow  using rich texts. dividers. etc etc. like I said im very new thanks

**Comment by DavBfr** [comment]
The documentation explains how to use asset images. Most Flutter layout widgets are implemented, but no material widgets as they are mostly useful for the user interface.
