### ISSUE TITLE
MissingPluginException(No implementation found for method convertHtml on channel net.nfet.printing)

### ISSUE THREAD

**Issue by hbakarsu** [DavBfr/dart_pdf#721]
When I'm running on any Android device, the printing library works perfectly. However, on Windows, **the print configuration window** opens smoothly but when I click on the "Print" button, it throws this error.

![image](https://user-images.githubusercontent.com/32145047/121586936-ec863900-ca3c-11eb-86a4-3b004a6d1023.png)
_This is the print configuration window._

I have already tried flutter clean, deleting cache and getting my library reference from the original "printing" library git page.
Thanks already...

![photo_2021-06-10_22-23-30](https://user-images.githubusercontent.com/32145047/121586395-4c301480-ca3c-11eb-8651-b3db8b2e93e5.jpg)

**Here is my Flutter Doctor**
![photo_2021-06-10_22-23-33](https://user-images.githubusercontent.com/32145047/121587376-63bbcd00-ca3d-11eb-9f5c-bc639a74d50d.jpg)

 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 -   Windows
 - [ ] Linux

**Comment by hbakarsu** [comment]
Okay thanks for the quick response. Why do the library shows a support tag of Desktop then?

**Comment by DavBfr** [comment]
Because it supports everything else. It also has a PrintingInfo structure to get at runtime what is supported.
