### ISSUE TITLE
Unable to load Asset while printing existing pdf

### ISSUE THREAD

**Issue by Kedar-27** [DavBfr/dart_pdf#723]
Getting following error on Android 11 

  `final pdf = await rootBundle.load('badge.pdf');
    await Printing.layoutPdf(onLayout: (_) => pdf.buffer.asUint8List());`

Unhandled Exception: Unable to load asset: /data/user/0/com.example.xyz/app_flutter/badge.pdf

**Comment by DavBfr** [comment]
Looks like this file does not exist on your device.

**Comment by Kedar-27** [comment]
Its there..working fine in ios

**Comment by DavBfr** [comment]
This is not working?
```dart
await rootBundle.load('badge.pdf');
```
If so, you have to look at the Flutter side, not this package.

**Comment by Kedar-27** [comment]
> This is not working?
> 
> ```dart
> await rootBundle.load('badge.pdf');
> ```
> 
> If so, you have to look at the Flutter side, not this package.

nope
