### ISSUE TITLE
How can I change the page header color?

### ISSUE THREAD

**Issue by mickey-ichi** [DavBfr/dart_pdf#724]
How can I change the page header color?

![Screenshot_20210615-215117_Print Spooler](https://user-images.githubusercontent.com/13127169/122075593-698e2580-ce24-11eb-8362-529647766e38.jpg)

**Comment by DavBfr** [comment]
@mickey-ichi I don't know, this is not part of your application but managed by the OS. Look at the Android API if find something.

**Comment by mickey-ichi** [comment]
> @mickey-ichi I don't know, this is not part of your application but managed by the OS. Look at the Android API if find something.
Tks br.
