### ISSUE TITLE
pdfImageFromImageProvider new implementation

### ISSUE THREAD

**Issue by burntblark** [DavBfr/dart_pdf#728]
I updated the flutter version (now v1.20.2) of a legacy application of ours and found this method pdfImageFromImageProvider no longer exists. Can anyone help with the alternative?

See current implementation below:

```
var img = await pdfImageFromImageProvider(
      pdf: pdf.document,
      image: AssetImage('assets/images/image.png'),
    );
```

**Comment by DavBfr** [comment]
Use 

```dart
var img = await imageFromAssetBundle('assets/images/image.png');
```

**Comment by burntblark** [comment]
@DavBfr Thanks for the reply. However, your suggestion still says the function (`imageFromAssetBundle`) is not available. I went on to use this: `flutterImageProvider` after getting an answer from StackOverflow ([here](https://stackoverflow.com/q/68042870/471064)).
