### ISSUE TITLE
error with some language's 

### ISSUE THREAD

**Issue by hussam132** [DavBfr/dart_pdf#729]
what's the supported languages for the pdf package because I'm facing some error with some languages like Arabic , chines and Russian 
`I/flutter (24719): errorInvalid argument (string): Contains invalid characters.: "तस्वीरें"
`
and its possible to this  use languages for writing in my pdf file 
thanks in advance

**Comment by DavBfr** [comment]
You have this error doing what?

**Comment by hussam132** [comment]
I'm facing this error when I try to save pdf file contains those languages

**Comment by DavBfr** [comment]
Show me some code.
