### ISSUE TITLE
need async build

### ISSUE THREAD

**Issue by biancashouse** [DavBfr/dart_pdf#73]
I addPage(some pdf widgets), which while building, populates an array of comments from my 
model.
My 2nd page relies on that array, but its addPage() gets called before the 1st page build() is finished.
How to wait for the first page build to finish ?
Apologies if this is a dumb question by a dart newbie.

**Comment by biancashouse** [comment]
addPage(Page()) seems to work synchronously, whereas using addPage(MultiPage()) seems to do its build async.

**Comment by DavBfr** [comment]
None of Page() or MultiPage() are async. You have to do your async stuff outside of the page build functions.

**Comment by biancashouse** [comment]
So the MultiPage build is completely synchronous ?
It looked to me that my 2nd page build was started before the first build
completed, which I assumed was due to the native functionality you are
calling.
Anyway, a workaround for me is to use a Future.delay for now.
In fact, by not using MultiPage for now, the issue goes away.

**Comment by biancashouse** [comment]
Righto, thanks for the clarification.
I'll revisit this a little later.
For now, just using Page() rather than MultiPage() avoids my issue.
Wrapped up with trying to get the damn app onto the Stores for testing.
Since your pdf package is integral to the app, could I send you a
TestFlight link ?

Cheers

Ian

**Comment by DavBfr** [comment]
You can send me a TestFlight link, yes.

**Comment by biancashouse** [comment]
Dave, what email address can I use to add you to my TestFlight testers ?

**Comment by DavBfr** [comment]
you can find my mail on the plugin page at https://pub.dev/packages/pdf "Uploader"

**Comment by biancashouse** [comment]
Righto. In the meantime, I created a public testflight link:

https://testflight.apple.com/join/FWuSUxKX
