### ISSUE TITLE
How can I pass values to invoice.dart from firestore?

### ISSUE THREAD

**Issue by issmapp** [DavBfr/dart_pdf#730]
`  final invoice = Invoice(
    invoiceNumber: '982347',
    products: products,
    customerName: 'Abraham Swearegin',
    customerAddress: '54 rue de Rivoli\n75001 Paris, France',
    paymentInfo:
        '4509 Wiseman Street\nKnoxville, Tennessee(TN), 37929\n865-372-0425',
    tax: .15,
    baseColor: PdfColors.teal,
    accentColor: PdfColors.blueGrey900,
  );
`

I want the values from firestore placed here. Is it possible?

**Comment by DavBfr** [comment]
Yes, fetch the values before creating the PDF.

**Comment by issmapp** [comment]
> 
> 
> Yes, fetch the values before creating the PDF.

In what file can I fetch it? I really can't do it right now without help. Thank you

**Comment by issmapp** [comment]
I can't put my fetch code in invoice.dart file even with function or using a widget, the futurebuilder doesnt work.

**Comment by DavBfr** [comment]
You get the data before even building the PDF, and pass all the data as arguments to the function.
