### ISSUE TITLE
How can i use this library with angularDart or pure dart on web

### ISSUE THREAD

**Issue by GMChristo** [DavBfr/dart_pdf#731]
I'm running this lib (version ^2.1.0) with angulardart 6.0 and it's compiling and running normally without any error, but the generated pdf is corrupted, I can't open the pdf in any program.

```dart
Future<void> testePDF() async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        build: (pw.Context context) => pw.Center(
          child: pw.Text('Hello World!'),
        ),
      ),
    );
    var array = await pdf.save();
    print(array);
    var blob = html.Blob(array, 'application/pdf');
    var link = html.AnchorElement();
    var url = html.Url.createObjectUrl(blob);
    link.download = 'teste.pdf';
    link.href = url;
    link.click();
  }
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
This what I have here: https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/printing_web.dart#L158

```dart
...


    final pdfFile = html.Blob(
      <Uint8List>[Uint8List.fromList(array)],
      'application/pdf',
    );
    final pdfUrl = html.Url.createObjectUrl(pdfFile);
    final html.HtmlDocument doc = js.context['document'];
    final link = html.AnchorElement(href: pdfUrl);
    link.download = filename;
    doc.body?.append(link);
    link.click();
    link.remove();
```

**Comment by GMChristo** [comment]
I changed my code and it worked, thanks
