### ISSUE TITLE
iOS build error using the Printing package

### ISSUE THREAD

**Issue by Petitt88** [DavBfr/dart_pdf#732]
**Describe the bug**
Great plugin, lovin' it on Android. However if I use this plugin from my iOS application the flutter build does not succeed, saying: **"Undefined symbols for architecture arm64: _OBJC_CLASS_$_GULAppEnvironmentUtil"**. 

Now this is the tip of the iceberg, this error comes when compiling a Firebase package but is caused by this plugin. I know this by removing the printing plugin everything is fine.
My application contains Firebase dependencies and some embedded native (C++) code, so I use the "_use_frameworks!_" in my podfile. I think this is what contributes to the build failure.

I've managed to find out that the cause of this issue is the lack of a "_**PrintingPlugin.h**_" header file. 
Is there some reason why this file is missing? I find it strange, because if I create a new flutter plugin in Swift via the Android Studio wizard (File --> New Flutter Plugin) the generated code contains 3 files: 
- XXXPlugin.h
- XXXPlugin.m
- XXXPlugin.swift

So I went on and created this PrintingPlugin.h header like so:
```dart
#import <Flutter/Flutter.h>

@interface PrintingPlugin : NSObject<FlutterPlugin>
@end
```

And modified the "**PrintingPlugin.m**" like this: (basically just importing the header file)
```dart
... copyrights comments

#import "PrintingPlugin.h"
#if __has_include(<printing/printing-Swift.h>)
#import <printing/printing-Swift.h>
#else
// Support project import fallback if the generated compatibility header
// is not copied when this plugin is created as a library.
// https://forums.swift.org/t/swift-static-libraries-dont-copy-generated-objective-c-header/19816
#import "printing-Swift.h"
#endif

@implementation PrintingPlugin
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
  [SwiftPrintingPlugin registerWithRegistrar:registrar];
}
@end


// Dart:ffi API

void net_nfet_printing_set_document(uint32_t job,
                                    const uint8_t* doc,
                                    uint64_t size) {
  [SwiftPrintingPlugin setDocumentWithJob:job doc:doc size:size];
}

void net_nfet_printing_set_error(uint32_t job, const char* message) {
  [SwiftPrintingPlugin setErrorWithJob:job message:message];
}
```

After this the printing plugin can be built from my iOS application as well.
I tried it out in a Hello world application which has no C++ code, no "use_frameworks!" and the printing worked there as well.

Thanks in advance!

**To Reproduce**
This I cannot tell, the plugin works in a "hello world" like iOS app, but mine is farily large, with a good amount of dependencies in it.

**Expected behavior**
iOS compilation works.

**Desktop (please complete the following information):**
 - [X] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14
 - Version Flutter 2.2.2

**Comment by DavBfr** [comment]
Is this related to #720? @WilliamMaybe Any thoughts?

**Comment by WilliamMaybe** [comment]
Need demo..
If project is only using Objective-C, maybe creating a swift file is a good try.

**Comment by DavBfr** [comment]
I don't have any issues myself with a Firebase project.

**Comment by Petitt88** [comment]
@DavBfr No it is not related, I still had this issue when I first tried out the printing plugin which version was 5.2.1. With the latest version 5.4.1 it is still present.

I think it is caused by my application having embedded C++ code, which requires an Objective-C++ (and not just normal Objective-C) application. Maybe the C++ header resolutions works differently in this case, but this really is just a guess.

But one thing is certain, using a PrintingPlugin.h header which is imported by the .m Objective-C file described above solved the build issue.

**Comment by DavBfr** [comment]
Can you share the dependency section of your pubspec.yaml?

**Comment by WilliamMaybe** [comment]
> @DavBfr No it is not related, I still had this issue when I first tried out the printing plugin which version was 5.2.1. With the latest version 5.4.1 it is still present.
> 
> 
> 
> I think it is caused by my application having embedded C++ code, which requires an Objective-C++ (and not just normal Objective-C) application. Maybe the C++ header resolutions work differently in this case, but this really is just a guess.
> 
> 
> 
> But one thing is certain, using a PrintingPlugin.h header which is imported by the .m Objective-C file as described above solved the build issue.

I think it's not related C++,my project also uses C++

**Comment by DavBfr** [comment]
@Petitt88 Maybe you have to upgrade your CocoaPod and/or Xcode?

**Comment by Petitt88** [comment]
@WilliamMaybe My C++ code is embedded in a custom plugin of mine, which had to be an Objective-C++ plugin -because regular Objective-C cannot invoke embed C++, only standard C, nor can Swift only through a bridging-header.h file-. 
Therefore the extension of my plugin is ".mm" instead of ".m" and I had to make some C compilation Flags adjustments in the past in order to make it work. Maybe this is the root cause of this, because with the C compilation Flags changed, my Application requires every plugin to have a ".h" header file.

I'm using quite a lot of plugins, all of them have a header file as I checked them in Github.

@DavBfr My Xcode and CocoaPod is the latest, these are my dependencies

```dart
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: ^2.0.0
  auto_size_text: ^2.1.0
  carousel_slider: ^4.0.0
  catcher: ^0.6.6
  collection: ^1.14.13
  diacritic: ^0.1.1
  dropdown_search: ^0.6.3
  environment_config: ^3.0.0
  expandable: ^5.0.1
  file_picker: ^3.0.1
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  flutter_appauth: ^1.0.0
  flutter_appcenter_bundle: ^3.3.1+2
  flutter_beacon: ^0.5.0
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.22.0	
  flutter_typeahead: ^3.1.3
  get_it: ^7.1.3
  geojson_vi: ^1.6.0
  hive: ^2.0.4
  http: ^0.13.3
  json_annotation: ^4.0.0
  mapbox_gl: ^0.12.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler: ^8.0.0+1
  
  printing: ^5.4.1

  provider: ^5.0.0
  pull_to_refresh: ^2.0.0
  rounded_loading_button: ^2.0.4
  rxdart: 0.27.0
  scrollable_positioned_list: ^0.1.10
  url_launcher: ^6.0.4
  wakelock: ^0.5.2
  workmanager: ^0.4.1
  xml: ^5.1.2
  
  # This is my Objective-C++ plugin
  calculation: 
	path: ../plugins/calculation
	
dependency_overrides:
  args: '^2.0.0'
  built_collection: 5.0.0
  built_value: 8.0.0
  crypto: '^3.0.0'
  rxdart: 0.27.0
  uuid: '^3.0.0'
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.3
  hive_generator: ^1.1.0
  json_serializable: ^4.1.2
  pedantic: ^1.9.2
```

**Comment by DavBfr** [comment]
@Petitt88 is this still an issue? If yes, please provide a PR with your fix.
