### ISSUE TITLE
Printing Does not work on Safari. Blank White screen

### ISSUE THREAD

**Issue by kenthinson** [DavBfr/dart_pdf#733]
**Describe the bug**

Printing a PDF file works on Native, Google Chrome, Firefox, but fails on Safari.
The PDF shows as a blank white screen. I have tested with multiple different PDF files.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
 onPressed: () async {
          ByteData data = await rootBundle.load('assets/test.pdf');
          Printing.layoutPdf(onLayout: (_) => data.buffer.asUint8List());
        },
```

**Expected behavior**

Printing should work the same in Safari as on the other Browsers / Platforms.

**Screenshots**

Safari failure
<img width="1325" alt="Screen Shot 2021-06-23 at 2 40 49 PM" src="https://user-images.githubusercontent.com/2245494/123158482-749f1200-d431-11eb-8eb5-75490296e502.png">
Chrome working
<img width="1201" alt="Screen Shot 2021-06-23 at 2 39 50 PM" src="https://user-images.githubusercontent.com/2245494/123158485-75d03f00-d431-11eb-9765-db369db4604c.png">

**Flutter Doctor**

```
➜  print_test flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-US)
    • Flutter version 2.2.2 at /Users/kent/Developer/flutter
    • Framework revision d79295af24 (12 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kent/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [X] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: MacBook Air
 - OS: MacOS 11.4
 - Browser: Safari
 - Version:  14.1.1 (Possible others as well)

**Comment by DavBfr** [comment]
I have Safari 14.1.1 too and Printing works.
Have you tested with: https://davbfr.github.io/dart_pdf/ ?

**Comment by kenthinson** [comment]
@DavBfr That website doesn't seem to work.

<img width="1324" alt="Screen Shot 2021-06-23 at 2 51 39 PM" src="https://user-images.githubusercontent.com/2245494/123159370-8df48e00-d432-11eb-8603-449de347a13f.png">

**Comment by DavBfr** [comment]
Strange: it works the first time, then it shows a popup asking if you want to print and shows this white page.

**Comment by DavBfr** [comment]
Seems we are not the only one: https://github.com/crabbly/Print.js/issues/561

**Comment by DavBfr** [comment]
I think it's a bug in Safari 14.1.1. I updated the package with the alternative print method until the bug is fixed.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
