### ISSUE TITLE
header is a list of dynamic

### ISSUE THREAD

**Issue by feemagdev** [DavBfr/dart_pdf#734]
**Describe the bug**

I want to know how i use ttf font in header. below i have given my header code.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
final headers = ['تاريخ', 'چکر', 'ٹوٹل بلاک', 'نمکين بلاک'];
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [x] Windows
 - [ ] Linux
Windows

**Smartphone (please complete the following information):**

**Additional context**

**Comment by feemagdev** [comment]
i solved this issue.

**Comment by ashskr1984** [comment]
> i solved this issue.

how ??

**Comment by feemagdev** [comment]
> > i solved this issue.
> 
> how ??

change the text  direction from left to right from right to left. it should solve your issue.
