### ISSUE TITLE
Set paper and orientation beforehand

### ISSUE THREAD

**Issue by SwiftingDuster** [DavBfr/dart_pdf#74]
**Describe the bug**
My app generates PDF that only targets A4 Landscape. However regardless of what value is passed into `MultiPage`'s constructor it always show the print preview screen with default values (Letter, Portrait). This extra step seems unnecessary for my app so is there any way to change the print settings beforehand?

**To Reproduce**
```dart
final pdf = Document(deflate: zlib.encode);
pdf.addPage(
  MultiPage(
    pageFormat: PdfPageFormat.a4.landscape,
    orientation: PageOrientation.landscape,
    build: (context) => [Container()],
  ),
);
```

**Expected behavior**
Print preview screen should launch with A4 Landscape set by default
![Screenshot_1558027247](https://user-images.githubusercontent.com/25877083/57875024-79ea0580-7844-11e9-9ad6-de4432a0701f.png)

**Smartphone (please complete the following information):**
 - Device: Android only

**Comment by DavBfr** [comment]
Sorry, There is no way to provide that in the Android or iOS API. The only workaround is `orientation: PageOrientation.landscape` as you do.

**Comment by SwiftingDuster** [comment]
Since its out of your control I will close this then.

**Comment by deepak786** [comment]
@DavBfr we can pass the Print settings in Android

```
PrintAttributes.Builder builder = new PrintAttributes.Builder();
builder.setMediaSize(PrintAttributes.MediaSize.ISO_A4);
or
builder.setMediaSize(PrintAttributes.MediaSize.ISO_A4.asLandscape());
```
