### ISSUE TITLE
Is there a way to stretch a Table or GridView across two pages?

### ISSUE THREAD

**Issue by westy92** [DavBfr/dart_pdf#741]
I want to stretch a Table or GridView vertically to fill two pages. Is such a thing possible? I've tried multiple approaches without any luck.

Example:
![2-pages-3-rows](https://user-images.githubusercontent.com/290167/123973620-875d9d80-d981-11eb-8aa5-7f2fb0785821.png)

**Comment by DavBfr** [comment]
Not really, each cell has to fit entirely on a page.

**Comment by westy92** [comment]
Is this possible with the Wrap widget or anything else?

**Comment by westy92** [comment]
Nevermind, I found this:

https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html

>An inner widget tree cannot be bigger than a page: A Widget cannot be drawn partially on one page and the remaining on another page: It's insecable.

I'd like this to then be a feature request.

**Comment by westy92** [comment]
Related: https://github.com/DavBfr/dart_pdf/issues/684

**Comment by westy92** [comment]
A widget may be insecable, but wouldn't it be possible to clone the split widget and draw it in such a way that there is one copy per page that overhangs the edges?

**Comment by DavBfr** [comment]
Yes but the text will be cut anywhere using this technique. Like the top of the letters on one page and the bottom on the next page.

**Comment by westy92** [comment]
That is desired in my case.

**Comment by westy92** [comment]
For now I just made the page twice as tall, filled the page, then used `ghostscript` after to split the page in half.

**Comment by DavBfr** [comment]
You can write a new Page() descendant that implements what you describe.
