### ISSUE TITLE
How to make page break within a loop?

### ISSUE THREAD

**Issue by YxLee611** [DavBfr/dart_pdf#745]
I would like to break my pdf page to a new page when loop

**Comment by DavBfr** [comment]
You can try the `NewPage()` widget.

**Comment by YxLee611** [comment]
Hi, thanks for reply. I had try with this widget. But it still unable to break after the image. As below is my function...

`static Future<File> generatePdf() async {
    final pdf = pw.Document();
    final image = await imageFromAssetBundle('assets/icons/happy.png');

    pdf.addPage(
      pw.MultiPage(
        maxPages: 300,
        build: (pw.Context context) => [
          pw.Column(
            children: [
              for (int count = 0; count < 1000; count++) 
                pw.Column(
                  children: [
                    pw.Text('Hello World ooo!'),
                    pw.Text('Hello World pp !'),
                    pw.Text('Hello World aaa!'),
                    pw.Image(image),
                    pw.NewPage()
                  ]
                )
                
            ]
          ),
        ],
      )
    );

    return saveDocument(name: 'my_example.pdf', pdf: pdf);
  }`

**Comment by YxLee611** [comment]
![WhatsApp Image 2021-07-10 at 6 44 23 PM](https://user-images.githubusercontent.com/28710791/125160347-f5d70280-e1ae-11eb-89e5-9290ffa67124.jpeg)
i would like to break a new page after the image... but it is not working

**Comment by YxLee611** [comment]
I also tried with Wrap widget... but it still not working

 pdf.addPage(
      pw.MultiPage(
        maxPages: 300,
        build: (pw.Context context) => [
          pw.Wrap(
            children: [
              for (int count = 0; count < 1000; count++) 
              pw.Wrap(
                children: [
                  pw.Text('Hello'),
                  pw.Text('World'),
                  pw.Image(image),
                  pw.NewPage(),
                ]
              )
            ]
          )
        ],
      )
    );

**Comment by DavBfr** [comment]
What about this?

```dart
pdf.addPage(
  pw.MultiPage(
    maxPages: 300,
    build: (pw.Context context) => [
      pw.Column(
        children: [
          for (int count = 0; count < 1000; count++) 
            ... [
                pw.Text('Hello World ooo!'),
                pw.Text('Hello World pp !'),
                pw.Text('Hello World aaa!'),
                pw.Image(image),
                pw.NewPage()
              ]
        ]
      ),
    ],
  )
);
```

**Comment by YxLee611** [comment]
i try with this, but it still cannot break

`pdf.addPage(
      pw.MultiPage(
        maxPages: 300,
        build: (pw.Context context) => [
          pw.Column(
            children: [
              for (int count = 0; count < 1000; count++) 
                pw.Wrap(
                  children: [
                    pw.Text('Hello World ooo!'),
                    pw.Text('Hello World pp !'),
                    pw.Text('Hello World aaa!'),
                    pw.Image(image),
                    pw.NewPage()
                  ]
                )
            ]
          ),
        ],
      )
    );`

And it will become like this... 
![WhatsApp Image 2021-07-10 at 8 29 34 PM](https://user-images.githubusercontent.com/28710791/125163027-bcf25a00-e1bd-11eb-81d7-12a8350c6ac7.jpeg)

**Comment by Markt61** [comment]
I tried to work out your issue the problem is the column in the column and where you place the pw.Newpage().
This works fine.

![image](https://user-images.githubusercontent.com/66099642/126101073-c59753d4-47c9-4c92-97b9-6f88cfb39843.png)

**Comment by Markt61** [comment]
To stop the blank page at the end...sorry about that   

 pdf.addPage(
      pw.MultiPage(
          maxPages: 5,
          build: (pw.Context context) => [
                for (int count = 0; count < 5; count++) ...[
                  pw.Column(
                    children: [
                      pw.Text('Hello World ooo!'),
                      pw.Text('Hello World pp !'),
                      pw.Text('Hello World aaa!'),
                      pw.Image(img2, height: 50, width: 50),
                    ],
                  ),
                  if (count< 4)pw.NewPage(),
                ]
              ]),
    );

    return pdf.save();
  }

**Comment by YxLee611** [comment]
> I tried to work out your issue the problem is the column in the column and where you place the pw.Newpage().
> This works fine.
> 
> ![image](https://user-images.githubusercontent.com/66099642/126101073-c59753d4-47c9-4c92-97b9-6f88cfb39843.png)

it works!!!! Thank you so much! Thanks for your help!
