### ISSUE TITLE
PDF generation speed slow the first time in any browser 

### ISSUE THREAD

**Issue by karthikgs-in** [DavBfr/dart_pdf#748]
Hello! 

I am generating PDFs for my application which includes generating between 10-100 pages based on small images (about 400 of them) 

Based on issues raised in the past, I have made all these images into small jpegs. 

I have also put pdf generation in an isolate. Both these steps based on code samples here have sped up the generation process. 

One odd issue I've had is the first time the user tries to generate the pdf, it takes a very long time/crashes/doesn't generate at all. But on loading the page again/simply trying again after a reset, pdf generation is fast. Not sure if this has to do with browsers & javascript/if i can do something in dart/dart_pdf. 

Any pointers are much appreciated.

**Comment by DavBfr** [comment]
Maybe you download a lot of fonts and images when printing.
You can try to preload all the images first.

**Comment by karthikgs-in** [comment]
Yes that is the bottleneck, I didn't think it was, since the images were all < 1KB. Preloading does well as far as the browser can support it! Thanks for your input.
