### ISSUE TITLE
How to make PDFs not selectable? Is there a way in the package? 

### ISSUE THREAD

**Issue by karthikgs-in** [DavBfr/dart_pdf#749]
I was looking around old issues and couldn't find anything. Would i use printing. raster?

**Comment by DavBfr** [comment]
What do you want to do exactly?

**Comment by karthikgs-in** [comment]
The pdfs generated have selectable components (like text). How would i disallow selecting, copy pasting of text?

**Comment by DavBfr** [comment]
You cannot make text non-selectable, but you can prevent copy/paste using: the `protect` attribute of the `TtfFont` object.
It will create a font with no glyph to text mapping, making it difficult to copy/paste.

**Comment by karthikgs-in** [comment]
Oh I see, thanks! Will try that! I guess the alternative is to make the pdf from images of everything which defeats the purpose.
