### ISSUE TITLE
How to print from a PDF file already existing on device 

### ISSUE THREAD

**Issue by JonathanJude** [DavBfr/dart_pdf#75]
How do I print from a already existing PDF file 
?

**Comment by DavBfr** [comment]
use something like:
```dart
var myFile = new File('file.pdf');
var pdfBytes = await myFile.readAsBytes();
await Printer.layoutPdf(onLayout: (_) => pdfBytes);
```

**Comment by JonathanJude** [comment]
It worked well.. Thanks for this!

**Comment by premy** [comment]
` var myFile = new File(generatedPdfFilePath);
var pdfBytes = await myFile.readAsBytes();
await Printer.layoutPdf(onLayout: (_) => pdfBytes);
`
I'm getting a squiggly red line under Printer saying it's undefined.

I'm simply trying to print a pdf created from html (using https://pub.dev/packages/flutter_html_to_pdf). For my use case this package is just a lot simpler to create my pdf files.

**Comment by DavBfr** [comment]
Maybe you just need to import the package?
```dart
import 'package:printing/printing.dart';
```

**Comment by premy** [comment]
Well I did. Imported pdf package as well, just in case...

`import 'package:printing/printing.dart';`
`import 'package:pdf/pdf.dart';`
