### ISSUE TITLE
 This widget created more than 20 pages.

### ISSUE THREAD

**Issue by kholyphoenix1** [DavBfr/dart_pdf#751]
Hello, 
I'm generating a 3 Page PDF and for some reason I get an error saying:
This widget created more than 20 pages. 

An exception occurred. 
_Exception (Exception: This widget created more than 20 pages. This may be an issue in the widget or the document. See https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html)

Mesmo com informando **pw.MultiPage()** continuo recebendo erros.
O que eu preciso fazer para corrigir esse erro?
<
`pw.Document pdfDoc;
  pdfDoc = pw.Document();
  var now = DateTime.now();
  String dateHourNow = DateFormat('yyyy-MM-dd hh:mm:ss').format(now);
  final soon = await imageFromAssetBundle('assets/soon/002.png');
  final ObjAccess objAccess = ObjAccess();

  pdfDoc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4.copyWith(
        marginLeft: 0.5 * PdfPageFormat.cm,
        marginRight: 0.5 * PdfPageFormat.cm,
        marginTop: 0.5 * PdfPageFormat.cm,
        marginBottom: 0.5 * PdfPageFormat.cm,
      ),
      build: (pw.Context context) {
        return <pw.Widget>[
          pw.Container(
            decoration: pw.BoxDecoration(
              border: pw.Border(
                top: pw.BorderSide(width: 1.0),
                left: pw.BorderSide(width: 1.0),
                right: pw.BorderSide(width: 1.0),
                bottom: pw.BorderSide(width: 1.0),
              ),
            ),
            width: double.infinity,
            child: pw.Padding(
              padding: pw.EdgeInsets.fromLTRB(10, 10, 10, 0),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.start,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Container(
                    margin: pw.EdgeInsets.symmetric(vertical: 10, horizontal: 30),
                    color: PdfColors.white,
                    child: pw.Image(soon, width: 100, height: 100),
                  ),
                  pw.Container(
                    margin: pw.EdgeInsets.symmetric(vertical: 10),
                    padding: pw.EdgeInsets.fromLTRB(5, 5, 5, 0),
                    child: pw.Column(
                      mainAxisAlignment: pw.MainAxisAlignment.start,
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: <pw.Widget>[
                        pw.Text(
                          'Recanto das Plantas',
                          textAlign: pw.TextAlign.left,
                        ),                        
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
  );`>

**Comment by DavBfr** [comment]
An inner widget tree cannot be bigger than a page: A Widget cannot be drawn partially on one page and the remaining on another page: It's insecable.

A small set of Widget can automatically span over multiple pages, and can be used as a direct child of the build method: Flex, Partition, Table, Wrap, GridView, and Column.

```dart
final pdf = Document();
pdf.addPage(MultiPage(build: (context) {
  return [
    Text('Hello'),
    Wrap(
      children: [
        Text('One'),
        Text('Two'),
        Text('Three'),
      ]
    ),
  ];
}));
```

The Wrap Widget here is able to rearrange its children to span them across multiple pages. But a child of Wrap must fit in a page, or an error will raise.

**Comment by senthilraja570** [comment]
How can we tell a child can fit a single page when the content is dynamic?
