### ISSUE TITLE
Printing.listPrinters in Android Device: No implementation found for method listPrinters on channel net.nfet.printing

### ISSUE THREAD

**Issue by rezins** [DavBfr/dart_pdf#753]
**Describe the bug**
When I try to call Printing.listPrinters(), there is an error say : Unhandled Exception: MissingPluginException(No implementation found for method listPrinters on channel net.nfet.printing). I'd search for method channel in PrintingHandler.java there is not method channel 'listPrinters' like you write in method_channel.dart

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
final printers = await Printing.listPrinters();
print(printers);
await Printing.directPrintPdf(
                printer: printers.first, onLayout: (_) => pdf.buffer.asUint8List());
```

**Flutter Doctor**

```
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [Version 10.0.19042.1083], locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1.0)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ✓] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: Samsung A8

**Comment by DavBfr** [comment]
@rezins unfortunately, there is no API on Android to get a list of printers and directly send a job. That's only available on Flutter desktop.

**Comment by elliotrtd** [comment]
@DavBfr It seems there is a PrinterDiscoverySession as part of the Android PrinterService in which you can get and add printers: 
https://developer.android.com/reference/android/printservice/PrinterDiscoverySession#public-methods

Maybe I am missing the obvious but it seems that would be what's needed?

**Comment by NeoSoftix** [comment]
Don't we have any update on this feature?
