### ISSUE TITLE
Printing freezes in iOS at App store

### ISSUE THREAD

**Issue by shankaratisoftcell** [DavBfr/dart_pdf#755]
**Describe the bug**

I am trying to print the pdf in a mobile application (iOS). I will share the snippets below,
after being uploaded to the app store it's hanged but android working fine. I got this bug in ios

WF: === Starting WebFilter logging for process Runner
WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
WF: _WebFilterIsActive returning: NO
+[PKPrinter(PKPrinterPrivate) getAttributes:count:fromURI:]: Unable to connect to (null):443: Undefined error: 0
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
    String dir = (await getTemporaryDirectory()).path;

    var targetPath = "$dir";
    var targetFileName = "printing";

    var generatedPdfFile = await FlutterHtmlToPdf.convertFromHtmlContent(
        printContent, targetPath, targetFileName);
    Uint8List bytes = generatedPdfFile.readAsBytesSync();

    await Printing.layoutPdf(onLayout: (_) => bytes.buffer.asUint8List());
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Use this:

```dart
await Printing.layoutPdf(onLayout: (_) => bytes.buffer.asUint8List(), dynamicLayout: false);
```

**Comment by shankaratisoftcell** [comment]
Hi,

I am using the latest printing version like (printing: any) it doesn't 
have dynamicLayout.

Which version i have to use?
