### ISSUE TITLE
How to generate tableRow rich styles

### ISSUE THREAD

**Issue by 978740431** [DavBfr/dart_pdf#757]
![image](https://user-images.githubusercontent.com/11803404/126254060-57df61dd-c45c-4c4d-91e0-a3caca2f2f85.png)

I want two rows of data in a cell to have different colors, fonts and sizes. 
I am using the factory Table.fromTextArray({}) method, what do I need to do?

**Comment by DavBfr** [comment]
Don't use fromTextArray but build the table yourself as you would do with Flutter.
