### ISSUE TITLE
Rendering Flutter Widgets as Preview

### ISSUE THREAD

**Issue by Klabauterman** [DavBfr/dart_pdf#758]
My application uses this package for pdf-creation and it works pretty well. But when my app renders multiple pages (10+) on a smartphone it takes some time.
One nice feature would be able to render pdf-widgets directly into Flutter widgets to make some kind of live-preview and let the user make changes to the layout before creating the pdf-file.

What are your thoughts on this potential new feature? Does that make sense? I am willing to build it.

**Comment by DavBfr** [comment]
I don't really understand what you want to do.
