### ISSUE TITLE
String contains invalid characters

### ISSUE THREAD

**Issue by callumclift** [DavBfr/dart_pdf#76]
**Describe the bug**
I'm trying to generate a PDF for a form I have created in Flutter however whenever I enter either single or double quotation marks (" ') this seems to break the PDF and gives the following message:

flutter: Invalid argument (string): Contains invalid characters.: "testing’"

Is there an easy way to get around this as I need to be able to accept single and double quotation marks? I'm hoping this is something really simple i'm missing here!

**Comment by DavBfr** [comment]
Can give me a code example?

**Comment by callumclift** [comment]
`Text formText(String text, [bool bold = false]){
      
      Text returnedValue;
      
      if(text == null || text == '' || text.isEmpty){
        returnedValue = Text('');
      } else if (bold){
        returnedValue = Text(text, style: TextStyle(fontSize: 9, font: Font.helveticaBold()));
      } else {

        returnedValue = Text(text, style: TextStyle(fontSize: 9));

      }
      
      return returnedValue;
    }`

Any fields in the form are passed through this function and the end result is that the string from the field is displayed but whenever a string containing ' or " comes through here it throws the error and fails to generate the PDF

**Comment by DavBfr** [comment]
No issue on my side. Are you using real quotes ' and " or some fancy Unicode quotes from MS Word?

**Comment by callumclift** [comment]
No i'm just using the standard ' and " that are found on the keyboard of my iPhone. I have a form that the user fills out and in my testing I am putting the quotations in the fields and then submitting the form which then generates the PDF and it is failing

**Comment by callumclift** [comment]
<img width="428" alt="Screenshot 2019-05-17 at 18 49 31" src="https://user-images.githubusercontent.com/40245055/57946630-b36a5180-78d4-11e9-8485-77a64d3c943f.png">

**Comment by DavBfr** [comment]
On your screenshot, they look like Unicode like  ’ and ” which are different from ' and "
Your solution is to load a TTF font and use it, as the standard Helvetica font in the Pdf is for Latin1 only.

**Comment by DavBfr** [comment]
```dart
final Uint8List fontData = File('open-sans.ttf').readAsBytesSync();
final Font ttf = Font.ttf(fontData.buffer.asByteData());
final Uint8List fontDataBold = File('open-sans-bold.ttf').readAsBytesSync();
final Font ttfBold = Font.ttf(fontData.buffer.asByteData());

Text formText(String text, [bool bold = false]) {
  Text returnedValue;

  if (text == null || text == '' || text.isEmpty) {
    returnedValue = Text('');
  } else if (bold) {
    returnedValue = Text(text, style: TextStyle(fontSize: 9, font: ttfBold));
  } else {
    returnedValue = Text(text, style: TextStyle(fontSize: 9, font: ttf));
  }

  return returnedValue;
}
```

**Comment by callumclift** [comment]
Thank you for your solution, I tried to use it but I got the following error:

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot open file, path = 'open-sans.ttf' (OS Error: No such file or directory, errno = 2)`

Am I missing something here I just copied the code provided.

**Comment by DavBfr** [comment]
Yes, you have to get the font file from the assets.

**Comment by callumclift** [comment]
`final Uint8List fontData = File('assets/OpenSans-Regular.ttf').readAsBytesSync();`

i've downloaded the open sans ttf from google fonts, placed them in my assets folder but i'm still getting the same error message, never done this before so excuse me if i'm being dumb

**Comment by DavBfr** [comment]
```dart
final Uint8List fontData = await rootBundle.load("assets/OpenSans-Regular.ttf");
```

**Comment by callumclift** [comment]
Ok that's done the trick! Thanks so much for all your help with this 🙏

**Comment by SEMHussain** [comment]
> 
> 
> ```dart
> final Uint8List fontData = await rootBundle.load("assets/OpenSans-Regular.ttf");
> ```

**dear sir, where i put this code line in my app ? ? ? please help me**
