### ISSUE TITLE
Change color of action bar

### ISSUE THREAD

**Issue by winneze1** [DavBfr/dart_pdf#761]
![image](https://user-images.githubusercontent.com/54367091/127468527-04e76513-cb1e-4190-af25-2c14830e2ca0.png)
Hi sir, how do I change the color of the Action bar.

**Comment by cansavrun** [comment]
How did you solve it @winneze1

**Comment by varunbhalerao56** [comment]
@cansavrun you know how to solve it?

**Comment by xrb21** [comment]
try changing the theme's primary color to the desired color in the main.dart file as follows:

`void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      theme: ThemeData(
        **primaryColor: Colors.green, //change this color**
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}`
