### ISSUE TITLE
How to change icon color

### ISSUE THREAD

**Issue by winneze1** [DavBfr/dart_pdf#762]
![image](https://user-images.githubusercontent.com/54367091/127476596-4e9cfad0-4f43-4e34-9472-7663613875a1.png)
![image](https://user-images.githubusercontent.com/54367091/127476644-74d46df7-d14e-4a04-9513-dbc409f928bf.png)
Hi sir, how can I change these icons color? Please help me.

**Comment by DavBfr** [comment]
I don't know, this UI is part of Android.
