### ISSUE TITLE
Text is not clear when printed

### ISSUE THREAD

**Issue by sabin26** [DavBfr/dart_pdf#764]
**Describe the bug**
Text is clear on pdf but not on paper printed

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Future<Uint8List> generatePdf() async {
final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);
  final font = await PdfGoogleFonts.openSansLight();

  pdf.addPage(
    pw.Page(
      pageFormat: PdfPageFormat(140, 140),
      build: (context) {
        return pw.Center(
            child: pw.Column(
          mainAxisAlignment: pw.MainAxisAlignment.center,
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Text(
              'Pandav Trade Center',
              style: pw.TextStyle(
                font: font,
                fontSize: 11.0,
              ),
            ),
            pw.Text(
              '2057/10/26 Bihana 5:00',
              style: pw.TextStyle(
                font: font,
                fontSize: 8.0,
              ),
            ),
            pw.Text(
              'Name: Sabin Neupane',
              style: pw.TextStyle(
                font: font,
                fontSize: 8.0,
              ),
            ),
            pw.Text(
              'Qty in ltr: 5',
              style: pw.TextStyle(
                font: font,
                fontSize: 8.0,
              ),
            ),
            pw.Text(
              'Fat: 26.00  SNF: 26.00',
              style: pw.TextStyle(
                font: font,
                fontSize: 8.0,
              ),
            ),
            pw.Text(
              'Rate: 26.00  Add Commission: 26.00',
              style: pw.TextStyle(
                font: font,
                fontSize: 8.0,
              ),
            ),
            pw.Text(
              'Per litre: 26.00  Total: 1026.00',
              style: pw.TextStyle(
                font: font,
                fontSize: 8.0,
              ),
            ),
          ],
        ));
      },
    ),
  );

  return pdf.save();
}
Future<void> printDocument() async {
  var printers = await Printing.listPrinters();
  var validPrinters = printers.where(
      (element) =>
          !element.model!.contains('Microsoft') &&
          !element.model!.contains('AnyDesk') &&
          element.isDefault,
   );
   var pdfData= await generatePdf();
    await Printing.directPrintPdf(
        format: PdfPageFormat(140, 140),
        printer: validPrinters.elementAt(0),
        onLayout: (PdfPageFormat format) => pdfData,
    );
}
```

**Expected behavior**
Text should be clear after printing.

**Screenshots**
Text on pdf:
![image](https://user-images.githubusercontent.com/61322712/127605162-9a051261-e30f-449b-83b3-16a9f0c3b6a3.png)

Text on paper printed:
![IMG_5407](https://user-images.githubusercontent.com/61322712/127604103-d4dd1e7c-2170-44b4-933d-f4695b4a8f40.jpg)

**Flutter Doctor**
flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\donsa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\donsa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ 🗸 ] Windows
 - [ ] Linux

**Additional context**
1. I tried changing fonts like Ariel, Calibri, Open Sans, Roman and few more.
2. I tried setting compress to both true and false.
3. I checked printer and it works as expected when printing from other applications.

The printer I am using is an Epson printer.

**Comment by DavBfr** [comment]
Looks like a driver problem.

**Comment by sabin26** [comment]
But, I tried printing from other applications such as MS-Word and Seagate Crystal Report. There were no issues. The text was clear as expected on the paper after printing.

**Comment by sabin26** [comment]
@DavBfr any updates on this ?

**Comment by DavBfr** [comment]
@sabin26 I can't reproduce it.
The printing operation on Windows is done here:
https://github.com/DavBfr/dart_pdf/blob/master/printing/windows/print_job.cpp#L232

An alternative would be to raster the PDF to images and then print it.

**Comment by sabin26** [comment]
@DavBfr Related to this issue. I want to know if the type of printer is important for printing with this package. I have been using a Dot-Matrix Printer for printing. I have not tried with other kinds.
And do I have to raster the pdf document to image for all pages and again insert the images to a new pdf document for printing ?

**Comment by DavBfr** [comment]
@sabin26 Usually there is no need to raster to images. Using a regular Ink or Laser printer works normally.
