### ISSUE TITLE
[LINUX RELEASE] error while loading shared libraries: libpdfium.so: cannot open shared object file

### ISSUE THREAD

**Issue by mjafartp** [DavBfr/dart_pdf#767]
Error on Linux release `error while loading shared libraries: libpdfium.so: cannot open shared object file: No such file or directory` Build bundle include libpdfium.so in lib folder. but still getting errors. 

issue found when copying files to another system. in the same system (build system) it's working.

**Comment by DavBfr** [comment]
You might have to configure the RPATH manually in CMake, or change it afterward. The Flutter engine is not that good at loading an external library on Linux.

**Comment by mjafartp** [comment]
How to do it. ?

in package [flutter_libserialport](https://github.com/jpnurmi/flutter_libserialport) they are managed external library loading. it's working without any issue.

**Comment by DavBfr** [comment]
Not really, they build the serial port library inside the plugin.

**Comment by DavBfr** [comment]
Fixed in the master branch

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
