### ISSUE TITLE
hello DavBfr , i tared print without using UI and PdfPreview using Printing.layoutPdf(onLayout: .. ) but Still opening page , directPrintPdf({@required Printer printer ( @required url ), but i have not any url to my printer how i can executing the print order without entering this UI ?

### ISSUE THREAD

**Issue by Khaled-Helmy** [DavBfr/dart_pdf#768]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
directPrintPdf is not implemented on Android and Web: there is no API to do that.

**Comment by Khaled-Helmy** [comment]
> directPrintPdf is not implemented on Android and Web: there is no API to do that.

Fine , but now how i can executing the print order without entering this UI ?

**Comment by DavBfr** [comment]
On Android it's not possible. Unless you have a dedicated printer SDK.

**Comment by Khaled-Helmy** [comment]
> On Android it's not possible. Unless you have a dedicated printer SDK.

yes , i have dedicated printer SDK . 
can you example code to do this ?

**Comment by DavBfr** [comment]
It depends on what the SDK expects: can it print a PDF or an image. You'll have to write Java/Kotlin code yourself.

**Comment by Khaled-Helmy** [comment]
> It depends on what the SDK expects: can it print a PDF or an image. You'll have to write Java/Kotlin code yourself
fine , thank you very much for your help .
