### ISSUE TITLE
Printing.layoutPdf Header missing

### ISSUE THREAD

**Issue by JustonJ99** [DavBfr/dart_pdf#769]
I loaded the pdf from url then try to print it but the preview page are not showing the Header. @DavBfr 

![image](https://user-images.githubusercontent.com/37526525/128132491-5e9fe251-d204-4d13-a8b8-460b423562c5.png)

The body preview content is fine and showing the Header however when I click bottom **print icon** it will show like this 
![image](https://user-images.githubusercontent.com/37526525/128132692-9bbc8cff-0ed5-40eb-9354-41989d16eb8a.png)

Therefore, I have added a floatingActionButton with Printing.layoutPdf but the result same as **print icon**.
**floatingActionButton code**

```
void printPdf() async {
    if (GetPlatform.isMobile) {
      final data = await download(
          'http://127.0.0.1:8000/invoices/pdf/MqbLxvjpYqRx7RP6g4eO');
      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => data,
      );
    }
  }

  Future<Uint8List> download(
    String url, {
    bool cache = false,
    String prefix = 'cache_',
    String? suffix,
  }) async {
    late File file;
    if (cache) {
      if (suffix == null) {
        final l = url.lastIndexOf('.');
        if (l >= 0) {
          suffix = url.substring(l);
        }
      }
      file = File('$prefix${url.hashCode}$suffix');
      if (file.existsSync()) {
        return await file.readAsBytes();
      }
    }

    print('Downloading $url');
    final client = HttpClient();
    final request = await client.getUrl(Uri.parse(url));
    print(request);

    final response = await request.close();
    final builder = await response.fold(
        BytesBuilder(), (BytesBuilder b, List<int> d) => b..add(d));
    final List<int> data = builder.takeBytes();
    if (cache) {
      await file.writeAsBytes(data);
    }
    return Uint8List.fromList(data);
  }
```

In addition, If I print from the bottom second tab share icon will be fine and show the Header same as body preview content. I have no idea why it causing this.
![image](https://user-images.githubusercontent.com/37526525/128133255-3b73086c-e766-483e-9ed3-d9715aafc789.png)
![image](https://user-images.githubusercontent.com/37526525/128133288-04099770-832e-4d62-80cf-3725ff2ef52d.png)
![image](https://user-images.githubusercontent.com/37526525/128133321-74fc29a0-e779-4507-9424-9e8239df085a.png)

**Comment by DavBfr** [comment]
That's because the PDF page format is different from the actual paper format.
