### ISSUE TITLE
Custom loading widget in pdf_preview

### ISSUE THREAD

**Issue by Skeemet** [DavBfr/dart_pdf#770]
**Is your feature request related to a problem? Please describe.**
Add possibility to custom loading icon when building the PDF document

**Describe the solution you'd like**
- In PdfPreview constructor : 
```dart
this.loadingWidget = const Center(child: CircularProgressIndicator())
```

- Declare instance variable 
```dart
/// Widget to display when the PDF document is loading
final Widget loadingWidget;
```

- Use it in _createPreview method
```dart
    if (pages.isEmpty) {
++    return widget.loadingWidget;
--    return const Center(child: CircularProgressIndicator();
    }
```

**Describe alternatives you've considered**

**Additional context**
printing/lib/src/preview/pdf_preview.dart

What's your opinion on this ? I can do a PR if you want (I followed code of conduct which state to express feature before doing a PR)...

**Comment by DavBfr** [comment]
Yes, you are welcome to work on a PR.
