### ISSUE TITLE
Rotating widget (Text) does not rotate it really, dimensions does not change

### ISSUE THREAD

**Issue by abdallah-odeh** [DavBfr/dart_pdf#772]
```dart
MultiPage(
        pageFormat: PdfPageFormat.a4,
        textDirection: textDirection,
        build: (Context context) {
          return [
            Container(
              color: PdfColors.red,
              child: Transform.rotate(
                angle: math.pi / 2,
                child: Container(
                  color: PdfColors.blue,
                  child: Text(
                    'THIS IS MY ROTATED TEXT',
                    style: TextStyle(fontSize: 10),
                  ),
                ),
              ),)
          ];
        }
    );
```

**Expected behavior**
Should have a container with height approximately to 100, height approx. 30 and red colored

**Screenshots**
![aaaa](https://user-images.githubusercontent.com/68509938/128628170-30275c1e-9466-4d62-9fa1-3dfa520f9759.png)

**Flutter Doctor**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] Connected device (3 available)

• No issues found!

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
This transform function acts as the Flutter version, so the behavior is expected.
Try with `Transform.rotateBox` instead. This version will update the parent's constraints.

**Comment by abdallah-odeh** [comment]
Sorry, didn't see that option! It works perfectly. Thank you
