### ISSUE TITLE
Allowing direct output to print dialog when trying to print from Flutter PWA

### ISSUE THREAD

**Issue by kcin9** [DavBfr/dart_pdf#773]
**Is your feature request related to a problem? Please describe.**
Currently `Printing.layoutPdf` only send the pdf to the browse and let it decide in what way to handle it. In my case, using iOS device, resulted in a new tab with the pdf BLOB. Redundant of procedures are required to complete the printing action. (i.e. click "Share" -> "Print" -> "Print")

**Describe the solution you'd like**
By utilizing Javascript `.print()`, we can send the iframe content directly to the print dialog. Perhaps we can consider to provide an interface for such behaviour for the dart pdf file case as well?

**Comment by DavBfr** [comment]
If you find a solution, please create a PR.

**Comment by t-kietzmann** [comment]
I have the same issue. When creating a PDF on Flutter Web with an iOS Device, the default option for sharing is "blob:myurl" - so when using this via WhatsApp etc it will not work - the user has to select the Share-Options in the Dialog and have to switch from "auto" to "pdf".

Is there a way to make pdf default and ignore the blob? For now it's intuitiv and my users are not able to work with this.
Thanks!
