### ISSUE TITLE
Align text in low-level Pdf

### ISSUE THREAD

**Issue by pst9354** [DavBfr/dart_pdf#78]
Is there a way to align text when using low-level Pdf?

I specifically would like to be able to right-align texts.

Maybe expand the g.drawString function to include an alignment parameter?

**Comment by DavBfr** [comment]
Hi,
It's low-level, so you will have to right align yourself.

First, get the metrics using PdfFont.stringMetrics() to calculate the width of the string. Multiply by the font size and subtract that to the right position you want.

**Comment by pst9354** [comment]
Yes, that's what I did in the end. 
But wouldn't it be nice to have that functionality in the low-level part?

**Comment by DavBfr** [comment]
Why aren't you using the high-level API?

**Comment by pst9354** [comment]
I'm printing economy forms/reports and thought it would be easier if I could layout printout with millimeter precision.

**Comment by DavBfr** [comment]
You can use the Widgets system with sub-millimeter precision too. It's just easier to use.
