### ISSUE TITLE
Render HTML code as Widget inside PDF created by Printing lib

### ISSUE THREAD

**Issue by Jeferson505** [DavBfr/dart_pdf#784]
I wish that **printing** lib can do support generate PDF file in Widgets mode with HTML code.

# Example:

    import 'package:pdf/pdf.dart';
    import 'package:pdf/widgets.dart' as pw;
    import 'package:printing/printing.dart';
    
    pw.Document doc = pw.Document();
    
    doc.addPage(
        pw.MultiPage(
            pageFormat: PdfPageFormat.a4,
            margin: pw.EdgeInsets.all(12),
            build: (pw.Context context) {
              return [
                pw.Text("I am just an example"),
                pw.HTML("<html><p>This text must be showed without HTML tags in the generated PDF</p></html>"),
              ];
            },
        ),
    );
    
    await Printing.layoutPdf(onLayout: (_) async => await doc.save());

The **pw.HTML** Widget in the example is the what I wish that be implemented, but the name can also be something else.

**Comment by DavBfr** [comment]
This is just out of scope. Rendering simple HTML with no style is easy but useless. Supporting CSS would be huge work. Flutter doesn't support that for a reason.

**Comment by tffajari** [comment]
I have the sampe problem here, did anyone have the solution?

**Comment by alihassan143** [comment]
@DavBfr  you can user the [flutter_html](https://pub.dev/packages/flutter_html) package for they implemented most of the common use cases in the html with styles

**Comment by techkonze** [comment]
> This is just out of scope. Rendering simple HTML with no style is easy but useless. Supporting CSS would be huge work. Flutter doesn't support that for a reason.

Just enable the support for html without css. if possible.
