### ISSUE TITLE
Printer print blank paper

### ISSUE THREAD

**Issue by winneze1** [DavBfr/dart_pdf#786]
**Describe the bug**
Hi sir, i have read this wiki https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin
And apply it to my Test App. I copied exactly like the wiki.  However when i try to print the receipt. It print only blank paper. May I know how to fix this.
**To Reproduce**

```
Future<Uint8List> _generateTicket() async {
  final pdf = Document();

  pdf.addPage(
    Page(
      pageFormat: PdfPageFormat.roll80,
      build: (Context context) => SizedBox(
        height: 300 * PdfPageFormat.mm,
        child: Center(
          child: Text('Hello World'),
        ),
      ),
    ),
  );

  return pdf.save();
}
```
Then i add this

```
Future<void> printTicket() async {
  const PaperSize paper = PaperSize.mm80;
  final profile = await CapabilityProfile.load();
  final printer = NetworkPrinter(paper, profile);

  final PosPrintResult res = await printer.connect('192.168.1.123', port: 9100);

  if (res == PosPrintResult.success) {
    final ticket = await _generateTicket();
    final dpi = paper.width * 72 / PdfPageFormat.roll80.width;

    await for (var page in Printing.raster(ticket, dpi: dpi)) {
      // Convert the page pixels to an image
      final image = page.asImage();

      // Print the image
      printer.image(image);

      // Cut the paper between each pages
      printer.feed(2);
      printer.cut();
    }

    printer.disconnect();
  }
}
```
**Result:** 
![3e36562d206fd6318f7e](https://user-images.githubusercontent.com/54367091/130640713-d1222b44-b4e1-4abf-9524-babc90d6c3b8.jpg)

[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/aime/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/aime/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/aime/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/aime/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 92.0.4515.131

**Comment by DavBfr** [comment]
Maybe it's an issue with the `esc_pos_printer` plugin.

**Comment by edwin0401** [comment]
Changed as below:

    await for (var page in Printing.raster(await generateTicket(), dpi: 203)) {
      final image = decodeImage( await page.toPng());
      ticket += generator.image(image!);
      //ticket += generator.feed(2);
      ticket += generator.cut();
    }

**Comment by thanhhuy0611** [comment]
> Changed as below:
> 
> ```
> await for (var page in Printing.raster(await generateTicket(), dpi: 203)) {
>   final image = decodeImage( await page.toPng());
>   ticket += generator.image(image!);
>   //ticket += generator.feed(2);
>   ticket += generator.cut();
> }
> ```

@[edwin0401](https://github.com/edwin0401) I tried your solution but it doesn't work. The printer still print a blank page

**Comment by thanhhuy0611** [comment]
> Maybe it's an issue with the `esc_pos_printer` plugin.

I very sure the issue come from the method `raster` of Printing. I tried to don't use `esc_pos_printer` as below and it still a blank page

```
await for (final page in Printing.raster(await buildPdf(dataQRCode), dpi: 180)) {
      
      final image = page.asImage();
     
      bytes += generator.image(image);
      bytes += generator.feed(2);
      bytes += generator.cut();

      // ? OS dialog
      await Printing.layoutPdf(
        format: pf.PdfPageFormat.roll80.copyWith(height: 100 * pf.PdfPageFormat.mm),
        dynamicLayout: true,
        onLayout: (pf.PdfPageFormat format) async {
          return image.getBytes();
        },
      );
    }
```
