### ISSUE TITLE
Windows application Unable to generate build files

### ISSUE THREAD

**Issue by BangPei** [DavBfr/dart_pdf#787]
Hi, i try to run in windows application and i got this error.anyone can help?

![image](https://user-images.githubusercontent.com/50818216/130383271-d57dc448-fd60-4951-a278-e6b5f3eff1cf.png)

**Comment by DavBfr** [comment]
Looks like you don't have internet access.

**Comment by BangPei** [comment]
Hi @DavBfr ,thanks for replying.
