### ISSUE TITLE
how to convert image to imageprovider?

### ISSUE THREAD

**Issue by siamandkm** [DavBfr/dart_pdf#789]
hi,How can I convert an image to Imageprovider?

 screenshotController.capture().then((image)async{
                      if (image != null) {
                        final directory=await getExternalStorageDirectory();
                        final imagpath= await File("${directory!.path}/image2.png").writeAsBytes(image.toList());
                        await imagpath.create();
                        doc.addPage(pw.Page(build: (pw.Context context) {
                          return new pw.Center(child: pw.Image(        ));
                        }));
                               }
                    });

**Comment by DavBfr** [comment]
something like: `pw.MemoryImage(bytes: image)`
