### ISSUE TITLE
PdfPageFormat appears static - using CustomPaint

### ISSUE THREAD

**Issue by biancashouse** [DavBfr/dart_pdf#79]
I use CustomPaint to generate my flowchart pdf pages.
I generate a pdf page in A3.
It previews nice.

I generate subsequent pages in a different page size and the canvas items are not positioned correctly. I'm creating each page correctly, with the pageFormat: arg, and I'm passing the correct size: arg to the painter.

Whichever page size I use for the very first page, subsequent pages are wrongly rendered if in a different page size.

Is the page size being cached in the library ?

**Comment by DavBfr** [comment]
Can you attach a faulty pdf file?


On May 26, 2019 8:14:35 PM EDT, Bianca Cat <notifications@github.com> wrote:
>I use CustomPaint to generate my flowchart pdf pages.
>I generate a pdf page in A3.
>It previews nice.
>
>I generate subsequent pages in a different page size and the canvas
>items are not positioned correctly. I'm creating each page correctly,
>with the pageFormat: arg, and I'm passing the correct size: arg to the
>painter.
>
>Whichever page size I use for the very first page, subsequent pages are
>wrongly rendered if in a different page size.
>
>Is the page size being cached in the library ?
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/DavBfr/dart_pdf/issues/79

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by biancashouse** [comment]
I now believe the bug is mine.
I think it's my positioning of widgets on the pdf canvas - they have to be relative to the bottom, and I think I'm not updating the paper height value that should be used to get the top pos... will confirm shortly.

**Comment by biancashouse** [comment]
ok, my bug Fixed.
Apologies for time wasting.

**Comment by biancashouse** [comment]
my bug. sorry to waste your time.
