### ISSUE TITLE
pickPrinter equivalent for androïd platform ?

### ISSUE THREAD

**Issue by gstar10** [DavBfr/dart_pdf#791]
Hi, 
I have a cross platform project where I need to select a printer, save its data to later print a pdf document to the selected device. My project works on IOS. So my question is what is the equivalent of the pickPrinter function for the androïd platform that could help me implement th.is functionnality ?

Thanks in advance.

Best Regards.

**Comment by DavBfr** [comment]
There is no public API on android to pick a printer, if you find one, let me know.

**Comment by gstar10** [comment]
There is maybe this one: 
http://printhand.com/integration.php

Let me know if it's ok

**Comment by DavBfr** [comment]
Yes, looks interesting for the direct-print method.
Can you implement that?

**Comment by gstar10** [comment]
How do you want me to proceed for this implementation ?

**Comment by DavBfr** [comment]
I think of an Integration via PrintHand Intent API to implement `listPrinters` and change `printPdf` methods:

- Declare them in [PrintingHandler.java](https://github.com/DavBfr/dart_pdf/blob/master/printing/android/src/main/java/net/nfet/flutter/printing/PrintingHandler.java)
- Implementation goes in [PrintingJob.java](https://github.com/DavBfr/dart_pdf/blob/master/printing/android/src/main/java/net/nfet/flutter/printing/PrintingJob.java)
- Set `directPrint` and `canListPrinters` to true [here](https://github.com/DavBfr/dart_pdf/blob/master/printing/android/src/main/java/net/nfet/flutter/printing/PrintingJob.java#L86)

`listPrinters`: returns a list of map with: `name`, `url`, `model`, `location`, `comment`, `default`, `available`. Look at the Windows implementation [here](https://github.com/DavBfr/dart_pdf/blob/master/printing/windows/printing_plugin.cpp#L99)

`printPdf` if a `name` is specified (the content of the `url` String returned by `listPrinters`) it will print to this printer without user interaction.

**Comment by gstar10** [comment]
To be sure I understood what you said, Considering I need to have access to an interface to select a printer beforehand then add this previouly selected printer to my settings. 

If I implement the funtion as you explained can I do this ?

**Comment by DavBfr** [comment]
Yes, you'll just have to store the `url` String. You can test that on a Windows build as it's implemented already.

**Comment by gstar10** [comment]
Ok Thanks. 

But I don't know if I can do this implementation. 

I'am relatively new to Flutter and I am still struggling a lot with the basics. 
So updating an existing library is still too complexe at the moment for me.

**Comment by DavBfr** [comment]
PrintHand is a paid app: ± $10 per user. An open-source solution would be preferable.
