### ISSUE TITLE
Change Orientation doesn't change

### ISSUE THREAD

**Issue by gtuceturan** [DavBfr/dart_pdf#792]
Hello, My code is below I use   canChangeOrientation but when I press it doesn't work  

 Scaffold(
              appBar: AppBar(
                title: const Text('Report'),
              ),
              body:PdfPreview(
                maxPageWidth: 700,
                build: (format) async => await _generatePdf(),
              allowPrinting: true,
              allowSharing: true,
              canChangeOrientation: true,
              canDebug: false,
                actions: [
                  PdfPreviewAction(
                    icon: const Icon(Icons.attach_email_outlined)
                  //  onPressed:_askMail,
                  )
                ],
              ),
            );
_generatePdf function ;

 pdf.addPage(
      pw.Page(
          pageFormat: PdfPageFormat.a4,
          orientation: pw.PageOrientation.landscape,
                build: (context) {
                  return pw.Column(
....

**Comment by DavBfr** [comment]
The orientation button will just change the format parameter here: `build: (format) async => await _generatePdf(),`
If you ignore it, nothing will happen.

**Comment by gtuceturan** [comment]
Thanks for your reply, I missed it

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
