### ISSUE TITLE
Add table headers on a new page 

### ISSUE THREAD

**Issue by lxmirmsh1811** [DavBfr/dart_pdf#793]
Is there a way to add table headers when a table spans across many pages ?

**Comment by DavBfr** [comment]
Yes, the `TableRow` widgets have a `repeat` property just for that.

**Comment by lxmirmsh1811** [comment]
That's brilliant! thank you! ^^

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by huongtran84** [comment]
I am using table.fromTextArray .how to only show table header on first page? opposite with @lxmirmsh1811 's question?

**Comment by DavBfr** [comment]
@huongtran84 `Table.fromTextArray` is just a helper function. You should write your own using the `Table` Widget directly.
