### ISSUE TITLE
CartesianGrid Background

### ISSUE THREAD

**Issue by gtuceturan** [DavBfr/dart_pdf#794]
Hello ,

I want to change grid background Image or all divisions different color  is it possible?

**Comment by DavBfr** [comment]
Yes, you can create a new widget that extends `FixedAxis` and override the `paintBackground` method.

Like this:

```dart
class MyFixedAxis<T extends num> extends pw.FixedAxis<T> {
  MyFixedAxis(
    List<T> values, {
    pw.GridAxisFormat? format,
    pw.TextStyle? textStyle,
    double? margin,
    double? marginStart,
    double? marginEnd,
    PdfColor? color,
    double? width,
    bool? divisions,
    double? divisionsWidth,
    PdfColor? divisionsColor,
    bool? divisionsDashed,
    bool? ticks,
    bool? axisTick,
    double angle = 0,
    pw.GridAxisBuildLabel? buildLabel,
  }) : super(
          values,
          format: format,
          textStyle: textStyle,
          margin: margin,
          marginStart: marginStart,
          marginEnd: marginEnd,
          color: color,
          width: width,
          divisions: divisions,
          divisionsWidth: divisionsWidth,
          divisionsColor: divisionsColor,
          divisionsDashed: divisionsDashed,
          ticks: ticks,
          axisTick: axisTick,
          angle: angle,
          buildLabel: buildLabel,
        );

  @override
  void paintBackground(pw.Context context) {
    final grid = pw.Chart.of(context).grid as pw.CartesianGrid;
    const colors = [PdfColors.green200, PdfColors.orange200, PdfColors.red200];
    const accentColors = [
      PdfColors.greenAccent,
      PdfColors.orangeAccent,
      PdfColors.redAccent,
      PdfColors.redAccent
    ];

    if (direction == pw.Axis.vertical) {
      var n = 0;
      num last = toChart(values.first);
      for (final num y in values.sublist(1)) {
        final p = toChart(y);
        final h = p - last;
        context.canvas
          ..drawRect(grid.gridBox.left, p - h, grid.gridBox.width, h)
          ..setFillColor(colors[n++])
          ..fillPath();
        last = p;
      }

      n = 0;

      for (final num y in values) {
        final p = toChart(y);
        context.canvas
          ..drawLine(grid.gridBox.left, p, grid.gridBox.right, p)
          ..setStrokeColor(accentColors[n++])
          ..setLineWidth(divisionsWidth)
          ..setLineJoin(PdfLineJoin.miter)
          ..strokePath();
      }
    }
  }
}
```

**Comment by gtuceturan** [comment]
> Yes, you can create a new widget that extends `FixedAxis` and override the `paintBackground` method.
> 
> Like this:
> 
> ```dart
> class MyFixedAxis<T extends num> extends pw.FixedAxis<T> {
>   MyFixedAxis(
>     List<T> values, {
>     pw.GridAxisFormat? format,
>     pw.TextStyle? textStyle,
>     double? margin,
>     double? marginStart,
>     double? marginEnd,
>     PdfColor? color,
>     double? width,
>     bool? divisions,
>     double? divisionsWidth,
>     PdfColor? divisionsColor,
>     bool? divisionsDashed,
>     bool? ticks,
>     bool? axisTick,
>     double angle = 0,
>     pw.GridAxisBuildLabel? buildLabel,
>   }) : super(
>           values,
>           format: format,
>           textStyle: textStyle,
>           margin: margin,
>           marginStart: marginStart,
>           marginEnd: marginEnd,
>           color: color,
>           width: width,
>           divisions: divisions,
>           divisionsWidth: divisionsWidth,
>           divisionsColor: divisionsColor,
>           divisionsDashed: divisionsDashed,
>           ticks: ticks,
>           axisTick: axisTick,
>           angle: angle,
>           buildLabel: buildLabel,
>         );
> 
>   @override
>   void paintBackground(pw.Context context) {
>     final grid = pw.Chart.of(context).grid as pw.CartesianGrid;
>     const colors = [PdfColors.green200, PdfColors.orange200, PdfColors.red200];
>     const accentColors = [
>       PdfColors.greenAccent,
>       PdfColors.orangeAccent,
>       PdfColors.redAccent,
>       PdfColors.redAccent
>     ];
> 
>     if (direction == pw.Axis.vertical) {
>       var n = 0;
>       num last = toChart(values.first);
>       for (final num y in values.sublist(1)) {
>         final p = toChart(y);
>         final h = p - last;
>         context.canvas
>           ..drawRect(grid.gridBox.left, p - h, grid.gridBox.width, h)
>           ..setFillColor(colors[n++])
>           ..fillPath();
>         last = p;
>       }
> 
>       n = 0;
> 
>       for (final num y in values) {
>         final p = toChart(y);
>         context.canvas
>           ..drawLine(grid.gridBox.left, p, grid.gridBox.right, p)
>           ..setStrokeColor(accentColors[n++])
>           ..setLineWidth(divisionsWidth)
>           ..setLineJoin(PdfLineJoin.miter)
>           ..strokePath();
>       }
>     }
>   }
> }
> ```

Thank you for your answer I just started learning flutter and  I'm confused I'm seen just X axis Do you have any exam?

**Comment by gtuceturan** [comment]
thank you for your answer.But i'm confused I'm started learnin flutter .I can see just x axis Do you have any exam?

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
