### ISSUE TITLE
Unsupport font khmer

### ISSUE THREAD

**Issue by oengmengthong** [DavBfr/dart_pdf#797]
can you tell us what type of file font can support use in pdf?
I try to find a lot files ready. include from google font
https://fonts.google.com/specimen/Khmer#standard-styles

**Comment by DavBfr** [comment]
Any TrueType files (.ttf)

**Comment by DavBfr** [comment]
This font works quite well, but it does not have any Latin characters.

<img width="537" alt="Screen Shot 2021-09-13 at 21 15 40" src="https://user-images.githubusercontent.com/1387855/133173323-b2ecd93c-9644-45fa-824e-016153381c8c.png">

**Comment by DyZak17** [comment]
> This font works quite well, but it does not have any Latin characters.
> 
> <img alt="Screen Shot 2021-09-13 at 21 15 40" width="537" src="https://user-images.githubusercontent.com/1387855/133173323-b2ecd93c-9644-45fa-824e-016153381c8c.png">
