### ISSUE TITLE
Error reporting when text contains Chinese

### ISSUE THREAD

**Issue by Mrfujianfei** [DavBfr/dart_pdf#80]
**Describe the bug**
when my text contains chinese will errors and I want the final report contains Chinese , thanks for your help.

**To Reproduce**
```dart
pdf.addPage(MyPage(
    pageFormat:
        format.applyMargin(left: 10.0, top: 10.0, right: 10.0, bottom: 10.0),
    build: (Context context) => Container(child: Text("中文")),
  ));
```
**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser

**Comment by DavBfr** [comment]
Duplicate of #76
