### ISSUE TITLE
pdf chinese character

### ISSUE THREAD

**Issue by longfit** [DavBfr/dart_pdf#800]
**Describe the bug**

https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/document.dart
I have to change above example 
 final font1 = await PdfGoogleFonts.openSansRegular()  ===>final font1 = await PdfGoogleFonts.notoSansTCRegular();;
  final font2 = await PdfGoogleFonts.openSansBold()  ==> final font2 = await PdfGoogleFonts.notoSansTCBold();;
  
modify  add one chinese character 
into ---> pw.Text('Portable Document Format  中', textScaleFactor: 2)

orginal  final font1 = await PdfGoogleFonts.openSansRegular()  
shown invalid character 
after final font1 = await PdfGoogleFonts.notoSansTCRegular()
shown  empty space at chinese character postition

  

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```
final font1 = await PdfGoogleFonts.notoSansTCRegular();
  final font2 = await PdfGoogleFonts.notoSansTCBold();
**Expected behavior**

can show proper chinese traditional characdter at pdf

**Screenshots**

**Flutter Doctor**

[✓] Flutter (Channel master, 2.6.0-1.0.pre.219, on Ubuntu 20.10
    5.8.0-63-generic, locale en_US.UTF-8)
    • Flutter version 2.6.0-1.0.pre.219 at /home/ykwings/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 58944e6b88 (2 days ago), 2021-09-08 19:37:34 -0700
    • Engine revision 6a3b04632b
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc5)
    • Android SDK at /home/ykwings/android-sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • ANDROID_HOME = /home/ykwings/android-sdk
    • Java binary at: /home/ykwings/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/ykwings/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • SM C9000 (mobile) • 722b49e6 • android-arm64  • Android 8.0.0 (API 26)
    • Linux (desktop)   • linux    • linux-x64      • Ubuntu 20.10
      5.8.0-63-generic
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 93.0.4577.63

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android 12
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

find out any suitable font for Chinese character or solution

**Comment by DavBfr** [comment]
I removed notoSansTCRegular as it's OpenType and not TrueType font.
