### ISSUE TITLE
CSV/Excel

### ISSUE THREAD

**Issue by erperejildo** [DavBfr/dart_pdf#806]
I was wondering how difficult would be to have another plugin like this but in this case creating a CSV/EXCEL file

**Comment by DavBfr** [comment]
I don't see how it's related to PDF.

**Comment by erperejildo** [comment]
> I don't see how it's related to PDF.

it's not, but the options out there to export to those formats are quite poor and it'd be nice to have more options to export. I'm not saying that there should be inside this package (it wouldn't have sense calling it pdf), but if it's not too difficult covering this that should be the perfect package to export.

I'll close the "issue" anyway

**Comment by GiddyNaya** [comment]
What works me....

   ```
 String csv = const ListToCsvConverter().convert(rows); // from package:csv/csv.dart
    final bytes = utf8.encode(csv);
    Uint8List data = Uint8List.fromList(bytes);
    
    // from package:printing/src/printing.dart
    await Printing.sharePdf(
        bytes: data,
        filename: 'MyExcelSheet.csv');
```
