### ISSUE TITLE
Network Images in pdf

### ISSUE THREAD

**Issue by mjwaghmare** [DavBfr/dart_pdf#807]
how can we show images coming from network??

**Comment by DavBfr** [comment]
https://github.com/DavBfr/dart_pdf/wiki/Network-Image

**Comment by roshan9419** [comment]
Hey, @mjwaghmare 

package required: [printing](https://pub.dev/packages/printing)

final myImage = await flutterImageProvider(NetworkImage("https://tech.pelmorex.com/wp-content/uploads/2020/10/flutter.png"));

Usage:
import 'package:pdf/widgets.dart' as pw;
pw.Image(myImage) // place it wherever you want

Hope this works for you in just a few lines.

**Comment by mjwaghmare** [comment]
Thank you 🙏🏻

Thanks & Regards,
Manoj Waghmare
