### ISSUE TITLE
Problem with Flutter version: v1.6.4-pre.16

### ISSUE THREAD

**Issue by Hypercruse** [DavBfr/dart_pdf#81]
Thank you for your great plugin! I recently updated Flutter to the latests stable version, but now im receiving these 2 errors: 

> printing-2.0.2/lib/src/asset_utils.dart:64:32: Error: No named parameter with the name 'onError'.

> printing-2.0.2/lib/src/asset_utils.dart:49:27: Error: The argument type 'Future<void> Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.

Im using your latest version and im testing on an iOS device! 

Flutter Doctor Output:
 [✓] Flutter (Channel master, v1.6.4-pre.16, on Mac OS X 10.14.5 18F132, locale
    de-DE)
    • Flutter version 1.6.4-pre.16 at /Users/apple/Desktop/flutter
    • Framework revision 75d75bfaec (2 days ago), 2019-05-25 19:47:17 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • My iPhone • af06803ef5b50b90b759d82d0d5f60fae40ed0b0 • ios • iOS
      12.2

Any help would be appreciated!

**Comment by DavBfr** [comment]
Please use the stable channel:
```shell
flutter channel stable
flutter upgrade
```

**Comment by DavBfr** [comment]
alternatively, use this branch instead: flutter-v1.6.4 by adding in your pubspec.yaml:
```yaml
dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf
      ref: flutter-v1.6.4
      path: printing
```

**Comment by Hypercruse** [comment]
The swap to stable channel worked for me, thanks!

**Comment by allanwolski** [comment]
When will this be merged?

**Comment by DavBfr** [comment]
When they release the new stable channel. In the meantime, I keep this branch in sync with master.
