### ISSUE TITLE
 Helvetica has no Unicode support and  Helvetica-Bold has no Unicode

### ISSUE THREAD

**Issue by sangduong1412** [DavBfr/dart_pdf#810]
**Describe the bug**

I'm making the pdf generator. just showing simple text and save the file. but anytime i press on the button. the code dose not executed and I get the error like this
  I/flutter ( 5240): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter ( 5240): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

this is the sourcode  link
https://github.com/JohannesMilke/generate_pdf_example
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:generate_pdf_example/api/pdf_api.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';

class PdfParagraphApi {
  static Future<File> generate() async {
    final pdf = Document();

    final font = await rootBundle.load("assets/OpenSans-Regular.ttf");
    final ttf = Font.ttf(font);

    pdf.addPage(
      MultiPage(
        build: (context) => <Widget>[
          buildCustomHeader(),
          SizedBox(height: 0.5 * PdfPageFormat.cm),
          Paragraph(
            text:
                'This is my custom font that displays also',
            style: TextStyle(font: ttf, fontSize: 20),
          ),
          buildCustomHeadline(),
          buildLink(),
          ...buildBulletPoints(),
          Header(child: Text('My Headline')),
          Paragraph(text: LoremText().paragraph(60)),
          Paragraph(text: LoremText().paragraph(60)),
          Paragraph(text: LoremText().paragraph(60)),
          Paragraph(text: LoremText().paragraph(60)),
          Paragraph(text: LoremText().paragraph(60)),
        ],
        footer: (context) {
          final text = 'Page ${context.pageNumber} of ${context.pagesCount}';

          return Container(
            alignment: Alignment.centerRight,
            margin: EdgeInsets.only(top: 1 * PdfPageFormat.cm),
            child: Text(
              text,
              style: TextStyle(color: PdfColors.black),
            ),
          );
        },
      ),
    );
    return PdfApi.saveDocument(name: 'my_example.pdf', pdf: pdf);
  }

  static Widget buildCustomHeader() => Container(
        padding: EdgeInsets.only(bottom: 3 * PdfPageFormat.mm),
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide(width: 2, color: PdfColors.blue)),
        ),
        child: Row(
          children: [
            PdfLogo(),
            SizedBox(width: 0.5 * PdfPageFormat.cm),
            Text(
              'Create Your PDF',
              style: TextStyle(fontSize: 20, color: PdfColors.blue),
            ),
          ],
        ),
      );

  static Widget buildCustomHeadline() => Header(
        child: Text(
          'My Third Headline',
          style: TextStyle(
            fontSize: 24,
            fontWeight: FontWeight.bold,
            color: PdfColors.white,
          ),
        ),
        padding: EdgeInsets.all(4),
        decoration: BoxDecoration(color: PdfColors.red),
      );

  static Widget buildLink() => UrlLink(
        destination: 'https://flutter.dev',
        child: Text(
          'Go to flutter dev',
          style: TextStyle(
            decoration: TextDecoration.underline,
            color: PdfColors.blue,
          ),
        ),
      );

  static List<Widget> buildBulletPoints() => [
        Bullet(text: 'First Bullet'),
        Bullet(text: 'Second Bullet'),
        Bullet(text: 'Third Bullet'),
      ];
}

// your code
```

**Expected behavior**

the pdf file did not show up

**Screenshots**

I/flutter ( 5240): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter ( 5240): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
 this is error 
 can you please help
**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
This is working fine here.

**Comment by sangduong1412** [comment]
yeah I have test on my friend laptop and it work. but this code not work on my laptop. I have no ideal why this problem happen. the pdf file can not generate and just give me the problem like this 
I/flutter ( 5240): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter ( 5240): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by ShubhamAryanBansal** [comment]
I am also facing the same issue.. pdf is getting generated when I am just adding simple text and an image on pdf. But as soon as I create table it breaks and shows the same above exception

**Comment by KinsleySen** [comment]
any workaround? i face the same issue when using MultiPage
