### ISSUE TITLE
How to draw dots

### ISSUE THREAD

**Issue by DowsingUK** [DavBfr/dart_pdf#812]
How to draw dots like this? https://stackoverflow.com/questions/52946962/how-to-create-a-spacer-style-widget-that-prints-dots

**Comment by DavBfr** [comment]
Like this:

```dart
Row(
              children: [
                Text('Start'),
                SizedBox(width: 8),
                Expanded(
                    child: Divider(
                  borderStyle: BorderStyle.dotted,
                  thickness: 0.2,
                )),
                SizedBox(width: 8),
                Text('End'),
              ],
            )
```

**Comment by DowsingUK** [comment]
Hello thank you that's working very well.

How can I use it in a Stack and calculate indent and endIndent so getting the same result?

**Comment by DavBfr** [comment]
Why would you need a stack?

**Comment by DowsingUK** [comment]
Because I'm using a FittedBox and I don't want that Expanded get calculated by this FittedBox, so I just have a Stack behind I have dots an in front I have Start and End I just don't know how to calculate indent I tried with strings length but I think the Expand that contains the Divider changes proportions I guess

`pw.Stack(
        alignment: pw.Alignment.bottomCenter
        children:
        [
            pw.Expanded(
                    child: pw.Divider(
                  borderStyle: pw.BorderStyle.dotted,
                  thickness: 0.2,
                  endIndent: ???? , I tried 'Start'.length
                  indent ????:  I tried 'End'.length
                )),
          pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.stretch,
                  children:
                 [    
                    pw.Expanded(child: pw.FittedBox(child: Text('Start'))),
                   I don't want another Expanded here because it takes space for labels to grow
                    pw.Expanded(child: pw.FittedBox(child: Text('End'))),
                 ]
        ],
      ))`

**Comment by DavBfr** [comment]
You can use a white background for your text to hide the dots.

**Comment by DowsingUK** [comment]
I thought about that, problem is it looks awful because it has a decoration pattern

**Comment by DavBfr** [comment]
I don't see what you're trying to do, sorry.
