### ISSUE TITLE
Name from API can be Chinese, English or Japanese.

### ISSUE THREAD

**Issue by varunbhalerao56** [DavBfr/dart_pdf#815]
Hello, I need some help regarding a PDF I am creating. I am creating a pdf document that has names, some names can be in Chinese or English, or Japanese. I am getting English to print fine but it also gets messed up  (Fig 2)

NotoSansSC or NotoSansTC is what is most popular for Chinese, but those are OTF that is not working, and trying to convert them to TTF does not work either.

**This is the result if I am using normal NotoSans or other fonts like ValeraRound (Fig 1)**
![image](https://user-images.githubusercontent.com/59999892/134465608-d9f3ca24-5ce8-477f-a644-9eddc4e7d9f5.png)

```dart
//Code when using only NotoSans
ThemeData.withFont(
        base: Font.ttf(await rootBundle.load("fonts/NotoSans-Regular.ttf")),
        bold: Font.ttf(await rootBundle.load("fonts/NotoSans-Bold.ttf")),
        boldItalic: Font.ttf(await rootBundle.load("fonts/NotoSans-BoldItalic.ttf")),
        italic: Font.ttf(await rootBundle.load("fonts/NotoSans-Italic.ttf")),
      ),
```

**This is the result when using NotoSansSC after converting to TTF (Fig 2)**
![image](https://user-images.githubusercontent.com/59999892/134465354-5ea68850-ea07-4d1c-9aa8-161c52ff37ea.png)

```dart
//Code when using only NotoSansSC with TTF
ThemeData.withFont(
        base: Font.ttf(await rootBundle.load("fonts/NotoSansSC-Regular.ttf")),
        bold: Font.ttf(await rootBundle.load("fonts/NotoSansSC-Bold.ttf")),
        boldItalic: Font.ttf(await rootBundle.load("fonts/NotoSans-BoldItalic.ttf")),
        italic: Font.ttf(await rootBundle.load("fonts/NotoSans-Italic.ttf")),
      ),
```

```dart
//The data tile widget 
Padding customDataTile(context, String fieldName, String fieldData) {
  return Padding(
    padding: const EdgeInsets.all(5),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(fieldName, style: const TextStyle(fontSize: 9)),
        Text(fieldData,
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 9),
            overflow: TextOverflow.visible,
            maxLines: 1),
      ],
    ),
  );
}
```

Any idea on how I can fix this, as it is important that both the Chinese and English characters are printed properly.

It would be great if I can get help with this, I also don't mind creating documentation on what exactly to do once I get to know how to do so other people won't have the same problem.

**Comment by DavBfr** [comment]
Can be implemented with #626?
