### ISSUE TITLE
GridAxis

### ISSUE THREAD

**Issue by gtuceturan** [DavBfr/dart_pdf#822]
Hello,
I want to create new widget with 3 grid Axis(x,y,z extends CartesianGrid but  ı get error

The setter 'direction=' was called on null.
Receiver: null
Tried calling: direction=Instance of 'Axis'

  CartesianGridSample({
    GridAxis xAxis,
    GridAxis yAxis,
    GridAxis zAxis,
  })  : _xAxis = xAxis..direction = Axis.horizontal,
        _yAxis = yAxis..direction = Axis.vertical,
        _zAxis = zAxis..direction = Axis.horizontal;

  final GridAxis _xAxis;
  final GridAxis _yAxis;
  final GridAxis _zAxis;

what is problem ? Can you help

**Comment by DavBfr** [comment]
I can help, but I'll need the full class. Do you want to draw 3D charts?

**Comment by gtuceturan** [comment]
No I want second x axis for texts I want xAxis divisions but ı want z axis values text
