### ISSUE TITLE
Add CrossAxisAlignment.baseline

### ISSUE THREAD

**Issue by westy92** [DavBfr/dart_pdf#824]
**Is your feature request related to a problem? Please describe.**

I'd like to align the baseline of `Text` elements in a `Row`.

**Describe the solution you'd like**

In flutter, you can specify:

```dart
Row(
  crossAxisAlignment: CrossAxisAlignment.baseline,
  textBaseline: TextBaseline.ideographic,
);
```

Docs:
https://api.flutter.dev/flutter/rendering/CrossAxisAlignment-class.html
https://api.flutter.dev/flutter/dart-ui/TextBaseline-class.html

**Describe alternatives you've considered**

Manually lining up text by adding a `Padding`.

**Comment by tomasweigenast** [comment]
+1 here

**Comment by westy92** [comment]
Please don't close this.
