### ISSUE TITLE
Arabic code range is wrong

### ISSUE THREAD

**Issue by elibyy** [DavBfr/dart_pdf#826]
Hey there
It seems that the range set for Arabic also includes BIDI in it.
It seems that the ranges we're inputted wrong
According to Wikipedia these are the Arabic ranges

Arabic (0600–06FF, 256 characters)
Arabic Supplement (0750–077F, 48 characters)
Arabic Extended-B (0870–089F, 41 characters)
Arabic Extended-A (08A0–08FF, 96 characters)
Arabic Presentation Forms-A (FB50–FDFF, 631 characters)
Arabic Presentation Forms-B (FE70–FEFF, 141 characters)
Rumi Numeral Symbols (10E60–10E7F, 31 characters)
Indic Siyaq Numbers (1EC70–1ECBF, 68 characters)
Ottoman Siyaq Numbers (1ED00–1ED4F, 61 characters)
Arabic Mathematical Alphabetic Symbols (1EE00–1EEFF, 143 characters)

but the function `_isArabicLetter` will return true on RLM (8235) which isn't even a letter, it's BIDI RLE

```dart
 return (letter >= 0x0600 && letter <= 0x06FF) ||
      (letter >= 0x0750 && letter <= 0x077F) ||
      (letter >= 0x08FF && letter <= 0xFB50) ||
      (letter >= 0xFDFF && letter <= 0xFEFF);
```

It would be helpful if you could fix it

**Comment by DavBfr** [comment]
Ok, can you provide a PullRequest with the change?
