### ISSUE TITLE
after use pdf , and open pdf , this message error 

### ISSUE THREAD

**Issue by HamiidrezaRamezani** [DavBfr/dart_pdf#829]
W/MessageQueue( 7406): Handler (android.os.Handler) {4dcc95c} sending message to a Handler on a dead thread
W/MessageQueue( 7406): java.lang.IllegalStateException: Handler (android.os.Handler) {4dcc95c} sending message to a Handler on a dead thread
W/MessageQueue( 7406): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:563)
W/MessageQueue( 7406): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue( 7406): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue( 7406): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue( 7406): 	at android.os.Handler.post(Handler.java:427)
W/MessageQueue( 7406): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2245)
W/MessageQueue( 7406): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:2153)
W/MessageQueue( 7406): 	at android.hardware.camera2.ICameraDeviceCallbacks$Stub.onTransact(ICameraDeviceCallbacks.java:180)
W/MessageQueue( 7406): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
W/MessageQueue( 7406): 	at android.os.Binder.execTransact(Binder.java:1123)
W/MessageQueue( 7406): Handler (android.os.Handler) {4dcc95c} sending message to a Handler on a dead thread
W/MessageQueue( 7406): java.lang.IllegalStateException: Handler (android.os.Handler) {4dcc95c} sending message to a Handler on a dead thread
W/MessageQueue( 7406): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:563)
W/MessageQueue( 7406): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue( 7406): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue( 7406): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue( 7406): 	at android.os.Handler.post(Handler.java:427)
W/MessageQueue( 7406): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2245)
W/MessageQueue( 7406): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:2153)
W/MessageQueue( 7406): 	at android.hardware.camera2.ICameraDeviceCallbacks$Stub.onTransact(ICameraDeviceCallbacks.java:180)

**Comment by DavBfr** [comment]
How to reproduce?
