### ISSUE TITLE
Container Borders are Not Rendered on The Pdf.

### ISSUE THREAD

**Issue by liveaffiliates** [DavBfr/dart_pdf#83]
**Describe the bug**
Borders are not rendered when the pdf is displayed.

**To Reproduce**
 ```
  Pdf.Container (
       decoration: Pdf.BoxDecoration(color: PdfColors.grey, border: Pdf.BoxBorder(color: PdfColors.black, width: 5.0)),
       height: 30,
       width: 100,
  ),
```

**Expected behavior**
Border is rendered

**Comment by DavBfr** [comment]
Because you have to tell Pdf.BoxBorder which border you want to display:
Pdf.BoxBorder(color: PdfColors.black, width: 5.0, left: true, top: true, right: true, bottom: true)

**Comment by liveaffiliates** [comment]
Awesome, that fixed it. Thanks!
