### ISSUE TITLE
View number of pages in the PDF Footer like (1/2)

### ISSUE THREAD

**Issue by ahmed-eg** [DavBfr/dart_pdf#830]
**Is your feature request related to a problem? Please describe.**
I need to view the current page number and the page count in the footer of the PDF file
like 1/2 and 2/2

**Describe the solution you'd like**
I suggest adding a controller to the MultiPage or the Document to get from if the number of pages

**Describe alternatives you've considered**

**Additional context**

**Comment by DavBfr** [comment]
In the footer, the Context object contains the number of pages and the current page.

**Comment by chbloca** [comment]
```

  doc.addPage(
    pw.MultiPage(
      pageTheme: pw.PageTheme(
        pageFormat: format.copyWith(
          marginBottom: 0,
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
        ),
        orientation: pw.PageOrientation.portrait,
        theme: pw.ThemeData.withFont(
          // base: font1,
          // bold: font2,
          icons: await PdfGoogleFonts.materialIcons(),
        ),
      ),
      footer: (context) => pw.Text(
        '${context.pageNumber}/${context.pagesCount}',
        style: const pw.TextStyle(color: PdfColors.grey, fontSize: 8),
      ),
...
```


There is an error when I am trying to use it related to a null check.

Also, I have seen it is not possible to define a footer for a single page, is that correct @DavBfr ?
