### ISSUE TITLE
How can I draw columns in a Multipage Pdf?

### ISSUE THREAD

**Issue by movieator** [DavBfr/dart_pdf#837]
Hi,
 I'm trying to create a multipage pdf like the screenshot below.
The data in the columns are in the same group and their length is dynamic. If this length is larger than the page's length, I want to continue drawing them in the next page.
If I put them in a row, I get an error to use a spanning widget.
I tried with a Wrap and a table but I couldn't get the correct result. 
I want something like TableColumn (if existed)

Any ideas?? Thanks!

![scshot](https://user-images.githubusercontent.com/37368464/138426425-0a3ad9b5-b049-469e-b690-b1420f7e3dca.png)

**Comment by DavBfr** [comment]
You need the "big" widget to be top-level. Just as a child of your Multipage.

**Comment by movieator** [comment]
> You need the "big" widget to be top-level. Just as a child of your Multipage.

Can you be more specific please? I've made a lot of tries but nothing.

**Comment by DavBfr** [comment]
Liske this:

```dart
pdf.addPage(
    pw.MultiPage(
      build: (pw.Context pwContext) => <pw.Widget>[
         pw.Wrap(
           children: [
             //  put your individual cells here, not columns
           ],
        )
      ],
    ),
  );

**Comment by movieator** [comment]
I think you misunderstood what I m trying to do. I m not trying to fill out my 1st page with cells, then go to second page etc. As you can see on the attachment photo, column number 7 for example, stops on the second page, column number 8 stops on the first page. So I want to draw each column, no mater how many cells has it. So, if column 1 has 100 cells, I want to draw all of them in the beginning of each page (maybe there will be 5 pages). If column 2 has not any cell, there will be empty space on second column. That's how it works. Each column has its fixed position.

**Comment by DavBfr** [comment]
Then try with the Partitions widget: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_partitions_test.dart

**Comment by movieator** [comment]
That's it!!! This is exactly what I was looking for! Thank you so much!!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
