### ISSUE TITLE
I will arrange the order of printing for how the web

### ISSUE THREAD

**Issue by aomlovebank1212** [DavBfr/dart_pdf#838]
**Describe the bug**
How do I sort for web printing ( --kiosk-printing)?

**To Reproduce**
Now on the WEB system I print with a thermal printer for the POS system. I set the paper to pageFormat: PdfPageFormat.roll57.copyWith(
          height: 300 * PdfPageFormat.mm
The size of the paper came out good. but in order Each time I have to print two sheets for copy It came out so fast that the first sheet couldn't even be printed. I delayed but it seemed unstable. sometimes it doesn't work
```dart
Printing.layoutPdf(
        onLayout: (format) => Doc1(PdfPageFormat.roll57, title).whenComplete(() async {
        await Future.delayed(Duration(milliseconds: 1500));
 await Printing.layoutPdf(
                onLayout: (format) =>       Doc2(PdfPageFormat.roll57, title))
```

**Comment by DavBfr** [comment]
The javascript API does not give any information if the page has been printed or not.
