### ISSUE TITLE
Saving PDF document from preview page with custom function

### ISSUE THREAD

**Issue by GBergatto** [DavBfr/dart_pdf#839]
I'm using the pdf package to create documents inside my app. 

How can I save the document from the preview page? 
I know about the built-in `print`  and `share` functions, but I need something else. 

I need a function that does the following:
1. save the document to the device
2. upload it to Firebase Storage
3. delete the local file

I know how to do all of these steps, but I'm unable to access the `Uint8List`  bytes of the pdf document that is being previewed... I've tried to add a `PdfPreviewAction`, but I still can't access the bytes of the document from it

In `PdfPreview` > `build` I call a function that returns a `Future<Uint8List>`.  

```
PdfPreviewAction(
            icon: Icon(Icons.upload_file),
            onPressed: (context, build, pageFormat) {
               // in here, build returns a FutureOr<Uint8List> 
               // how can I access the <Uint8List> to then pass it to a function I have created??
            },
          )
```

![Screenshot](https://user-images.githubusercontent.com/69045457/138837102-3c560b62-1c41-4834-a297-9c47410144fb.png)
.

**Comment by DavBfr** [comment]
```dart
PdfPreviewAction(
            icon: Icon(Icons.upload_file),
            onPressed: (context, build, pageFormat) async {
               final data = await build(pageFormat);
               mySaveData(data);
            },
          )
```

**Comment by GBergatto** [comment]
Thanks a lot!
