### ISSUE TITLE
Display VietNamese

### ISSUE THREAD

**Issue by aoeminh** [DavBfr/dart_pdf#840]
Can I display text in Vietnamese? I get errors like this:

======== Exception caught by printing ==============================================================
The following ArgumentError was thrown while generating a PDF:
Invalid argument (string): Contains invalid characters.: "ư‘

When the exception was thrown, this was the stack: 
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      PdfFont.stringMetrics (package:pdf/src/pdf/font.dart:171:28)
#3      RichText.layout.<anonymous closure> (package:pdf/src/widgets/text.dart:703:34)
#4      TextSpan.visitChildren (package:pdf/src/widgets/text.dart:464:19)
#5      RichText.layout (package:pdf/src/widgets/text.dart:672:10)
#6      SingleChildWidget.layout (package:pdf/src/widgets/widget.dart:291:14)
#7      Flex.layout (package:pdf/src/widgets/flex.dart:362:17)
#8      Padding.layout (package:pdf/src/widgets/basic.dart:90:14)
#9      Flex.layout (package:pdf/src/widgets/flex.dart:285:15)
#10     Padding.layout (package:pdf/src/widgets/basic.dart:90:14)
#11     Flex.layout (package:pdf/src/widgets/flex.dart:285:15)
#12     Page.layout (package:pdf/src/widgets/page.dart:187:11)
#13     Page.postProcess (package:pdf/src/widgets/page.dart:141:18)
#14     Document.save (package:pdf/src/widgets/document.dart:125:14)
#15     generatePdf (package:shilin_sale/pages/order_detail/generatePdf.dart:16:20)
#16     PrintPage.build.<anonymous closure>.<anonymous closure> (package:shilin_sale/pages/print/print_page.dart:19:26)
#17     PdfPreviewRaster._raster (package:printing/src/preview/pdf_preview_raster.dart:110:32)
#18     PdfPreviewRaster.raster.<anonymous closure> (package:printing/src/preview/pdf_preview_raster.dart:78:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
PageFormat: "PdfPageFormat 595.275590551181x841.8897637795275 margins:56.69291338582677, 56.69291338582677, 56.69291338582677, 56.69291338582677"

**Comment by dattran-pt19** [comment]
> i fixed this with other font

Which font do you use to display Vietnamese? please share me!
