### ISSUE TITLE
Asking Printer

### ISSUE THREAD

**Issue by yeminsoe** [DavBfr/dart_pdf#842]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

Could I use this with Zebra Bluetooth Printer ?

**Comment by DavBfr** [comment]
If the printer comes with a driver, yes.

**Comment by yeminsoe** [comment]
I connected to the Printer via Bluetooth. So, will it print using this?

**Comment by DavBfr** [comment]
I don't think so. If it's a POS printer, you'll need to use some ESC/POS package for the final printout.
https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin
