### ISSUE TITLE
How can i support Qrcode in my application printing

### ISSUE THREAD

**Issue by 15563988825** [DavBfr/dart_pdf#845]
Just Like library
https://pub.flutter-io.cn/packages/qr_flutter
how can i  use it in printing ?

**Comment by DavBfr** [comment]
The PDF library already support QRCodes via the Barcode widget.

**Comment by 15563988825** [comment]
I've found it 
It's perfect!
Code Like:
`pw.BarcodeWidget(
              data: "This test string",
              width: 40,
              height: 40,
              barcode: pw.Barcode.qrCode(),
            ),`
