### ISSUE TITLE
GridView.builder not implemented .

### ISSUE THREAD

**Issue by wreyford** [DavBfr/dart_pdf#846]
I'm not going to file this as a bug, as I'm not sure why you didn't implement the functionality.
I'm pulling images into a pdf report, and 
`return pw.GridView.builder` fails, with the method builder is not implemented for GridView.

my code:
```dart
pw.GridView _gridViewImages() {
  return pw.GridView.builder(
    gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
      crossAxisSpacing: 10,
      mainAxisSpacing: 10,
      crossAxisCount: 3,
    ),
    itemCount: GlobalConstants.listStoredImages.length,
    itemBuilder: (context, index) {
      var _item = GlobalConstants.listStoredImages[index] as ImageCard;
      return Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            fit: BoxFit.cover,
            image: FileImage(File(_item.path)),
          ),
        ),
      );
    },
  );
}
```

Your advice will be appreciated.

**Comment by DavBfr** [comment]
`pw.GridView.builder` is not implemented because it will not improve the performance on a static Pdf document.

You can replace it with something like:

```dart
pw.GridView( children: [ 
... GlobalConstants.listStoredImages.map<pw.Widget>((_item) => ontainer(
        decoration: BoxDecoration(
          image: DecorationImage(
            fit: BoxFit.cover,
            image: FileImage(File(_item.path)),
          ),
        ),
      ) )
 ] )
```

**Comment by wreyford** [comment]
Thx for the prompt response. I really appreciate your time. That will work just great.
I have run into another issue:
``image: pw.Image.file(File(path));``
down not compile, as .file not supported.
I also tried
``image: pw.FileImage(File(_item.path), scale: 1), but the function FileImage not defined.
Please, be patient with me, this appears to be my last hurdle.

**Comment by wreyford** [comment]
Thx, I solved the problem by passing in the actual paths only, and not my List<ImageCard>
Using MemoryImage to load from file works 100%
