### ISSUE TITLE
How to use TTF fonts with widgets?

### ISSUE THREAD

**Issue by eliezedeck** [DavBfr/dart_pdf#85]
Hi, thanks for this nice library.

So, this is more of a **question** than a bug report. What's proper way to use TTF fonts when you also use the widgets?

I tried creating `TextStyle`, and when I use it, there seems to be a kind of crash and it hangs on the printing preparation screen and nothing is generated.

I'm not sure if this is a bug, but my generated PDF seems to have broken fonts when I tried. I suspect more the fact that I don't really know how to use the library and use Widgets at the same time.

An updated guide to use TTF + Widgets would be much appreciated.

Thanks.

**Comment by DavBfr** [comment]
The readme has been updated:

```dart
final font = await rootBundle.load("assets/open-sans.ttf");
final ttf = Font.ttf(font);

pdf.addPage(Page(
    build: (Context context) {
      return Center(
        child: Text('Dart is awesome', style: TextStyle(font: ttf, fontSize: 40)),
      ); // Center
    })); // Page
```

**Comment by eliezedeck** [comment]
Thanks for the update @DavBfr.

Strangely, I already tried this, but it only worked the first time; subsequent times, I get an empty texts or garbled texts showing-up. This is because I'm caching the `TextStyle` object from being recreated every-time. When I do **recreate the object every time**, it works fine.

For some users, while Dart probably might not be the right tool for the job, apps that do a lot of PDF generation or printing, this limitation it could make things rather inefficient. In all case, I think it could be good idea to mention this as well in the README.

**Comment by DavBfr** [comment]
You can reuse the `font` object but not `ttf`, as it refers directly to the document generated, to include the right glyphs in the pdf.

**Comment by eliezedeck** [comment]
I'm reopening this because I can't produce PDF on a second run using TTF fonts. The first time, it generates a proper PDF, but the second time, I now get an error:

```
'package:pdf/src/ttf_writer.dart': Failed assertion: line 89 pos 16: 'glyph.compounds.isEmpty': This is not a simple glyph
```

I tried to re-organize the code in different ways, but I always end-up having this error, no matter what. What is the basic reason why this happens?

It seems that if I load the same TTF `ByteData` twice with `Font.ttf(data)`, then I get this error. And yet, I'll have to do that as I create different documents for different receipts.

**Comment by DavBfr** [comment]
Yes, the stream is modified during the pdf creation. I forgot that.

**Comment by eliezedeck** [comment]
You leave me clue-less as to what I should do. Is there a way to reset that *stream*?

**Comment by eliezedeck** [comment]
Oh, I got it. By stream, you mean, the TTF Byte stream. I now **made a copy of the TTF bytes before giving it to `Font.ttf()`**. Now, it works with no more crash.

**Comment by DavBfr** [comment]
The copy is no longer needed as of version 1.3.13. The library will not modify the in-memory byte stream anymore.
