### ISSUE TITLE
How to add signature on pdf

### ISSUE THREAD

**Issue by SirChavero** [DavBfr/dart_pdf#852]
Good evening, I am in a project of digitally signing documents, and I need to add the signatures of each user in a pdf document and I did some research and I can't find much information, any ideas? or any library that can help me.

PD: I have the signatures in image format, I capture them with the syncfusion_flutter_signaturepad package

Thanks in advance

**Comment by DavBfr** [comment]
You can just use them as images on the PDF with `pw.MemoryImage`
