### ISSUE TITLE
MultiByteToWideChar "CodePage" param error in fromUtf8 function of print_job.cpp  for windows 

### ISSUE THREAD

**Issue by liqping** [DavBfr/dart_pdf#856]
for windows, MultiByteToWideChar CodePage param should be 'CP_UTF8', rather than 'CP_ACP'.

**Comment by DavBfr** [comment]
Can you give an example where it's not working?

**Comment by liqping** [comment]
1.platform: windows 10
2.plug version: printing: ^5.6.2

example:
`import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
        debugShowCheckedModeBanner: false, home: Scaffold(body: MyHomePage()));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return _MyHomePageState();
  }
}

class _MyHomePageState extends State<MyHomePage> {
  List<Printer>? _printerList;

  Future<List<Printer>> enumPrinter() async {
    _printerList = await Printing.listPrinters();
    return _printerList!;
  }

  int _printerIndex = 0;

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Center(
      child: Column(
        children: [
          Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text('select printer:'),
              FutureBuilder(
                  future: enumPrinter(),
                  builder: (BuildContext context, AsyncSnapshot snapshot) {
                    if(!snapshot.hasData){
                      return const SizedBox();
                    }
                    return Container(
                      margin: const EdgeInsets.only(top: 50, bottom: 50),
                      decoration: BoxDecoration(
                          color: const Color(0xFFffffff),
                          borderRadius:
                              const BorderRadius.all(Radius.circular(2.0)),
                          border: Border.all(color: const Color(0x33000000))),
                      width: 220,
                      height: 48,
                      child: DropdownButtonHideUnderline(
                        child: DropdownButton<int>(
                          menuMaxHeight: 300,
                          isDense: true,
                          isExpanded: true,
                          focusColor: Colors.blue.withOpacity(0.2),
                          icon: const Icon(
                            Icons.keyboard_arrow_down_rounded,
                            color: Color(0xFF666666),
                          ),
                          onChanged: (int? newValue) {
                            if (newValue != null) {
                              if (newValue != _printerIndex) {
                                setState(() {
                                  _printerIndex = newValue;
                                });
                              }
                            }
                          },
                          value: _printerIndex >= 0 ? _printerIndex : null,
                          items: [
                            if (_printerList != null)
                              for (int i = 0; i < _printerList!.length; i++)
                                DropdownMenuItem<int>(
                                    value: i,
                                    child: Text(_printerList![i].url,
                                        style: const TextStyle(fontSize: 13)))
                          ],
                        ),
                      ),
                    );
                  }),
            ],
          ),
          ElevatedButton(onPressed: () async{
            if(_printerList != null && _printerList!.isNotEmpty && _printerIndex >= 0){

              final pdfDoc = PdfDocument(version: PdfVersion.pdf_1_5);
              final docPage = PdfPage(pdfDoc);
              final graphics = docPage.getGraphics();
              graphics.drawRect(0,0 , 100,100);
              graphics.strokePath();

              bool result = await Printing.directPrintPdf(printer: _printerList![_printerIndex],
                  onLayout: (_) => pdfDoc.save()
              );
              /// if the name or url of printer is Chinese, the print code will not call

              print('result:$result');
            }


          }, child: const Text('print'))
        ],
      ),
    );
  }
}`

3.  my printer list
![1637296030(1)](https://user-images.githubusercontent.com/62126718/142570324-cf81b878-f402-45dd-8e0f-d6400e4ae41e.png)

4.use English ,it works!
![1637299337(1)](https://user-images.githubusercontent.com/62126718/142570383-42565ec9-4842-46ad-905a-40dad3588449.png)
![1637299212(1)](https://user-images.githubusercontent.com/62126718/142570414-903e4d60-629a-4ec2-9383-8e03578fa161.png)
![1637299130(1)](https://user-images.githubusercontent.com/62126718/142570422-94d441e0-8dbb-474c-b587-6ff8b32f9014.png)

5. use Chinese, it not works! They are same when convert utf-8 to ansi ; hdc == NULL;
![1637296041(1)](https://user-images.githubusercontent.com/62126718/142570605-f973d849-af54-4de2-b11f-1b7392dd2b4a.png)
![1637299390(1)](https://user-images.githubusercontent.com/62126718/142570611-1b914150-fd6a-4952-8fd6-a16d862eb32d.png)
![1637299433(1)](https://user-images.githubusercontent.com/62126718/142570622-fe83e3b1-5fe9-489d-8e28-6588bb694d45.png)

**Comment by DavBfr** [comment]
Ok, looks good!

**Comment by DavBfr** [comment]
Hey @liqping , can you help with this ticket: #848?

**Comment by DavBfr** [comment]
Fixed in the master branch.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
