### ISSUE TITLE
MissingPluginException(No implementation found for method convertHtml on channel net.nfet.printing)

### ISSUE THREAD

**Issue by Salam-pc** [DavBfr/dart_pdf#857]
when I call printingPdf() function on a button click  and on click I'm getting this error:

════════ Exception caught by printing ══════════════════════════════════════════
The following MissingPluginException was thrown while generating a PDF:
MissingPluginException(No implementation found for method convertHtml on channel net.nfet.printing)

my code is :

class Printer {
  static printingPdf() async {
    await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
              html: '<html><body><p>Hello!</p></body></html>',
              format: format,
            ))

**Comment by DavBfr** [comment]
`convertHtml` is supported only on Android, iOS and macOS.

**Comment by Salam-pc** [comment]
Is there any other method for windows?

**Comment by DavBfr** [comment]
To convert html to pdf, no.

**Comment by danilonogueirateixeira** [comment]
HTML for Windows ?

**Comment by chenw323** [comment]
> Is there any other method for windows?



> HTML for Windows ?

This can use https://pub.dev/packages/puppeteer  for Windows
It's Load HTML using Chromium
