### ISSUE TITLE
Unwanted margins when using printing package. 

### ISSUE THREAD

**Issue by wreyford** [DavBfr/dart_pdf#859]
I suspect this may be a bug. 
When I generate a pdf and save it on flutter desktop Windows, and subsequently print it from within Adobe, it honours my margins all set to 0.0 and the A4 doc prints perfectly. 

When I use the Printing package, to preview it, it previews perfectly. 
If I then print it, from the preview it adds a margin of about 5mm top and 5mm left. 
Why is this?

I notice that the. Cpp file for Printing package for windows uses:
```auto marginLeft =
      static_cast<double>(GetDeviceCaps(hDC, PHYSICALOFFSETX)) / dpiX;
  auto marginTop =
      static_cast<double>(GetDeviceCaps(hDC, PHYSICALOFFSETY)) / dpiY;
```
Perhaps the Printing package is not ignoring the printer hard margins?

**Comment by DavBfr** [comment]
It's not a bug!
It's the actual margins of your printer as reported by Windows. You can ignore the margins in your code if you like.

**Comment by wreyford** [comment]
In my code Iset the margins to zero.
I then save the pdf and when printed from Adobe honours the margins.
If the same doc is printed using printing, the hard margins are enforced and the entire document is offset to bottom and to left.

**Comment by wreyford** [comment]
I have set the margins in my PDFPreview to 0.0
the code as follows:
```dart
const SizedBox(height: 10),
            _startNr.isNotEmpty
                ? SizedBox(
                    height: 500,
                    width: 300,
                    child: PdfPreview(
                        pageFormats: const <String, PdfPageFormat>{
                          'A4': PdfPageFormat.a4
                        },
                        dynamicLayout: false,
                        maxPageWidth: 300,
                        allowPrinting: true,
                        allowSharing: true,
                        canChangeOrientation: false,
                        canChangePageFormat: false,
                        initialPageFormat: PdfPageFormat.a4.copyWith(
                            marginBottom: 0.0 * PdfPageFormat.cm,
                            marginLeft: 0.0 * PdfPageFormat.cm,
                            marginRight: 0.0 * PdfPageFormat.cm,
                            marginTop: 0.0 * PdfPageFormat.cm),
                        build: (format) =>
                            pdfOptiTab(format, context, int.parse(_startNr))),
                  )
                : Image.asset('assets/images/optitab_a4_numeric_tabs.jpg',
                    height: 500),
```

**Comment by DavBfr** [comment]
Ok this might be a bug.

**Comment by selvam920** [comment]
pls when can we expect this bug resolve?

**Comment by DavBfr** [comment]
@wreyford @selvam920 Can you test printing with the master branch to validate the fix?

In your `pubspec.yaml` file, add:

```yaml
dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
    path: printing
```

**Comment by selvam920** [comment]
sure

**Comment by selvam920** [comment]
Error on line 109, column 5 of pubspec.yaml: A dependency may only have one source.
    ╷
109 │ ┌     git:
110 │ │       url: https://github.com/DavBfr/dart_pdf.git
111 │ │       ref: master
112 │ │     path: printing
113 │ └ 
    ╵
pub get failed (65;     ╵)
exit code 65

**Comment by DavBfr** [comment]
you must have another override for this plugin.

**Comment by wreyford** [comment]
> @wreyford @selvam920 Can you test printing with the master branch to validate the fix?
> 
> In your `pubspec.yaml` file, add:
> 
> ```yaml
> dependency_overrides:
>   printing:
>     git:
>       url: https://github.com/DavBfr/dart_pdf.git
>       ref: master
>     path: printing
> ```

I added the dependency overrides:
```
Running "flutter pub get" in prax_optitab...
Warning: You are using these overridden dependencies:
! printing 5.6.3 from git https://github.com/DavBfr/dart_pdf.git at 22432d in printing
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Debug service listening on ws://127.0.0.1:11512/2Ht27seJ32o=/ws
Syncing files to device Windows...
```

I can confirm that it works! Thank you very much David ... Superb!
It now ignores the Hard-Margin, and does not revert to printer defualt.
Great Support!

**Comment by wreyford** [comment]
Thx David, closing issue as fixed.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by selvam920** [comment]
@DavBfr can you publish to pub, i'm unable to override

**Comment by DavBfr** [comment]
@selvam920 done.
