### ISSUE TITLE
print random letters on Android +10

### ISSUE THREAD

**Issue by Abdallah-al-hallak** [DavBfr/dart_pdf#860]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Abdallah-al-hallak** [comment]
![70a252cc-b58c-4773-b168-b7f5c6b54341](https://user-images.githubusercontent.com/57962596/142725574-c513032a-e5d1-440a-a50f-3a6897bf5f39.jpg)

**Comment by DavBfr** [comment]
Can it be an issue with the printer driver?

**Comment by Abdallah-al-hallak** [comment]
Idk actually, maybe it could be

**Comment by Abdallah-al-hallak** [comment]
it was because THe printer didn't print all items, it remains a small part of it, so when you want to print for the second time it will do this (as the pictures), so I fixed it by putting 6 lines of space after finishing printing.
