### ISSUE TITLE
Printer settings for desktop

### ISSUE THREAD

**Issue by cuishijie1991** [DavBfr/dart_pdf#863]
Is there a way to show Printer settings panel for desktop app?
My application is a desktop application..
I use print.directprintpdf () for printing, but I need a feature called "Printer Settings" that displays the printer Settings without printing
Is there a way to implement it? Thank you for any reply

**Comment by DavBfr** [comment]
Yes this can be implemented for all 3 desktop OS.

**Comment by cuishijie1991** [comment]
> Yes this can be implemented for all 3 desktop OS.

That is great!
I known it is ok for windows, but on macOS, I don't know how to do it.
I followed your plugin's implementation, but it is not what I want .
There seems to be no way to convert the print button to Confirm.
<img width="740" alt="截屏2021-11-24 上午10 30 16" src="https://user-images.githubusercontent.com/17976216/143160669-0608567a-2274-4868-85b5-0c932d4564ec.png">

code: 
```  
public func showPrinterSettings(printer: String, withWindow window: NSWindow) -> Void {
        let sharedInfo = NSPrintInfo.shared
        let sharedDict = sharedInfo.dictionary()
        let printInfoDict = NSMutableDictionary(dictionary: sharedDict)
        let printInfo = NSPrintInfo(dictionary: printInfoDict as! [NSPrintInfo.AttributeKey: Any])
        // Print the custom view
        printOperation = NSPrintOperation(view: self, printInfo: printInfo)
        printOperation!.jobTitle = "@@@@@@TEST"
        printOperation!.printPanel.options = [.showsPreview]
        printInfo.printer = NSPrinter(name: printer)!
        printOperation!.showsPrintPanel = true
        printOperation!.showsProgressPanel = false
        
        printOperation!.printPanel.options = [.showsPreview, .showsPaperSize, .showsOrientation]
        printOperation!.runModal(for: window, delegate: self, didRun:#selector(printOperationDidRun(printOperation:success:contextInfo:)), contextInfo: nil)
    }
```

**Comment by DavBfr** [comment]
The Linux printing system is very similar to macOS, so it might not be possible too.

**Comment by farooqaziz20** [comment]
Can you please show some code, for directPrintPdf. 
I am trying to print a pdf via directPrintPdf.
Same document is Working with layoutPdf.

I am Using this Code.
 var res = Printing.directPrintPdf(
                                                printer: Printer(
                                                    url: "192.168.18.50:9100",
                                                    name: "SAficio SP 3510SF"),
                                                onLayout:
                                                    (PdfPageFormat format) {
                                                  return (bulkProductBarCode(
                                                      context, tempList,
                                                      showName: isShowName,
                                                      showBarCodeNumber:
                                                          isShowCodeNumber,
                                                      showPrice: isShowPrice,
                                                      barcodeWidth:
                                                          barCodeWidth));
                                                },
                                              );

**Comment by Shams-Mahmoud** [comment]
any solution
@cuishijie1991 
@DavBfr
