### ISSUE TITLE
[printing] Windows layoutPdf default paper size letter

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#864]
![image](https://user-images.githubusercontent.com/20491308/142850465-3fedc822-0ab2-488b-8209-0f7d2d537248.png)

everytime need to change paper size from letter to a4 or other paper size.

this should be pagesizeformat basis

**Comment by DavBfr** [comment]
The master branch has a fix for that.

**Comment by selvam920** [comment]
thanks, it's working, closing this issue

**Comment by selvam920** [comment]
Hi same issue happening with latest version
