### ISSUE TITLE
[printing] windows directPrintPdf PdfPageFormat  issue

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#865]
[direct print.pdf](https://github.com/DavBfr/dart_pdf/files/7580490/direct.print.pdf)
[oringinal.pdf](https://github.com/DavBfr/dart_pdf/files/7580498/oringinal.pdf)

i have generated a4 size pdf, when i printing using directprintpdf method paper size taken different.
same pdf using layoutPdf method and change paper size to a4 it's working.

the issue not taken PdfPageFormat in directPrintPdf method

**Comment by DavBfr** [comment]
The master branch has a fix for that.

**Comment by selvam920** [comment]
name: sksmarket
description: SKS Market
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+12

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  pdf: any
  printing: any

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  moor_generator: # use the latest version
  build_runner: any
  json_serializable: any
  # analyzer: ^1.7.1

dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
    path: printing

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

**Comment by selvam920** [comment]
[sksmarket] flutter pub get
Running "flutter pub get" in sksmarket...                       
Error on line 37, column 5 of pubspec.yaml: A dependency may only have one source.
   ╷
37 │ ┌     git:
38 │ │       url: https://github.com/DavBfr/dart_pdf.git
39 │ │       ref: master
40 │ │     path: printing
41 │ │ 
42 │ │ # For information on the generic Dart part of this file, see the
43 │ │ # following page: https://dart.dev/tools/pub/pubspec
44 │ │ 
45 │ └ # The following section is specific to Flutter.
   ╵
pub get failed (65;    ╵)
exit code 65

**Comment by selvam920** [comment]
yes, it's working but if we print with undefined page size then default letter page size has taken, this scenario what ever pdf page size it should be.
given sample
[original.pdf](https://github.com/DavBfr/dart_pdf/files/7586125/original.pdf)
[in printing.pdf](https://github.com/DavBfr/dart_pdf/files/7586127/in.printing.pdf)

**Comment by DavBfr** [comment]
Yes, that's expected: you specify what you'd like to print to directPrint then the onLayout callback tells you what's really available in the printer tray.

**Comment by selvam920** [comment]
if the printer does not have paper size but we have roll paper, in that how to perform undefined paper size?

**Comment by DavBfr** [comment]
Use `double.infinity` for the height value.

**Comment by selvam920** [comment]
hi, this bug is working, you can publish to pub

**Comment by selvam920** [comment]
Hi same issue happening with latest version

**Comment by selvam920** [comment]
unable to print a5, always printing a4 size

**Comment by Panca6** [comment]
this issue still present on the latest build 3.8.3,
direct print doesnt print the exact PageFormat specify when creating the document..(when using pdfPreview page format displayed correctly) but when directPrint it went to different size i guess its A4 or Latter
try to pass PageFormat to directPrint method also not working always went back to A4

**Comment by selvam920** [comment]
I'm also facing same issue, with directprintpdf in windows the printer not printing this pdf.

**Comment by Panca6** [comment]
are u able to print long pdf use Roll paper 80? mine always get cut to size of a4

**Comment by Panca6** [comment]
final format = const PdfPageFormat(75 * PdfPageFormat.mm, double.infinity,
      marginAll: 5 * PdfPageFormat.mm);
      
      pass this to Page(format:format) to build doc and directPrintPDF(format:format) to print, and yet the result always a4/letter

**Comment by selvam920** [comment]
in my scenario, i try to print a4 using directpdf, the pdf is sent to printer pool but the printer was printing when i using printdialog with same pdf it's printing.

@DavBfr  pls look into this

**Comment by Panca6** [comment]
i wonder if this issue still persist on latest build

**Comment by DevMensIT** [comment]
Still i am looking for further support.

has Anyone here have found any solution regarding that ? 
@DavBfr  need help regarding this issue. same happening with direct print or indirect print.

**Comment by DavBfr** [comment]
Must be somewhere in this function then: https://github.com/DavBfr/dart_pdf/blob/master/printing/windows/print_job.cpp#L77
See if you can find a fix.

**Comment by DevMensIT** [comment]
![image](https://github.com/DavBfr/dart_pdf/assets/11617013/cfbbd30d-fb6a-40dd-9b80-2575126eceee)


Here in image 1 you can see pdf preview where i set my custom page format while in second the output which save pdf output 
both page size getting different size. but i put same page format in both layout

i checked that link but not found any solution for that
can you help me ?

**Comment by DevMensIT** [comment]
> Must be somewhere in this function then: https://github.com/DavBfr/dart_pdf/blob/master/printing/windows/print_job.cpp#L77 See if you can find a fix.

how can i change this line : 
  ```
if (width > height) {
      dm->dmOrientation = DMORIENT_LANDSCAPE;
      dm->dmPaperWidth = static_cast<short>(round(height * 254 / pdfDpi));
      dm->dmPaperLength = static_cast<short>(round(width * 254 / pdfDpi));
    } else {
      dm->dmOrientation = DMORIENT_PORTRAIT;
      dm->dmPaperWidth = static_cast<short>(round(width * 254 / pdfDpi));
      dm->dmPaperLength = static_cast<short>(round(height * 254 / pdfDpi));
    }
```

with 


```
  dm->dmPaperWidth = static_cast<short>(round(width * 254 / pdfDpi));
  dm->dmPaperLength = static_cast<short>(round(height * 254 / pdfDpi));

```
