### ISSUE TITLE
get length of page for force new page

### ISSUE THREAD

**Issue by longfit** [DavBfr/dart_pdf#867]
Hi
Since I want to print invoice item and follow print buildSignature widget 
, I don't know to last position  enought to print out this widget .

In addition , If I can get last length of page , Can I force new page to print buildSignaure Widget

Thanks you !

static pw.Widget buildSignature() => pw.Container(
          child: pw.Column(children: [
        pw.Container(
            height: 100,
            alignment: pw.Alignment.centerLeft,
            child: pw.Text('ABC Technology Co')),
        pw.Container(
            alignment: pw.Alignment.centerLeft,
            child: pw.Text(' ______________________')),
        pw.Container(
            alignment: pw.Alignment.centerLeft, child: pw.Text('  Authorized Signature')),
      ]));

**Comment by longfit** [comment]
Since I want to add signature Area followed by  Table.fromTextArray , sometimes, the signature area widget will be across between two page.

Can I print this signature widget force new page when it is not enough space  ?

thanks

**Comment by DavBfr** [comment]
Yes, you wrap it inside a Padding widget with the required size for signature, and it will automatically move to the next page if there is not enough space.
