### ISSUE TITLE
Get real sized onto PDF

### ISSUE THREAD

**Issue by PercyMcfly** [DavBfr/dart_pdf#868]
Hey,

so I have objects in the app that have a 1:1 scale with real objects in reality. 
I want to create a PDF that uses those objects to project them onto paper. 
Basically what I have is an image from which I know how many cm make up one pixel and I want to create a pdf that's true to reality.

I have no idea how else to explain this. But I could not find any reference to what sized something will actually have on the PDF and how to specify it programmatically using the dart_pdf package. 
I like the "widget" style compositions, but it's worthless for me, if I can't calculate the size something will have when printing it out.

Is there a reference on that somewhere?

**Comment by DavBfr** [comment]
The size is precise. To have a 10x10 cm box: use 

`SizedBox( width: 10*PdfPageFormat.cm, height: 10*PdfPageFormat.cm)`

**Comment by PercyMcfly** [comment]
@DavBfr oh wow, thanks!:)

**Comment by PercyMcfly** [comment]
@DavBfr An issue I had is, when the container is bigger than the page, it is automatically shrieked down to a certain size smaller than A4. 
Is there a way to have the image centered and displayed in the size specified, even if it is technically bigger than the size of the page?

This is what I'm working with: 
```
pdf.addPage(pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Container(
              width: (_wallMockUp.width)*PdfPageFormat.cm,
              height: (_wallMockUp.height)*PdfPageFormat.cm,
              child: pw.Image(image, fit: pw.BoxFit.cover,),
            )
          ); 
        }
        )
    );
```

**Comment by DavBfr** [comment]
Maybe something like this: 
https://api.flutter.dev/flutter/widgets/OverflowBox-class.html

but it's not implemented.

**Comment by PercyMcfly** [comment]
@DavBfr I found a workaround. If you set the Margin of the Page to a high enough negative number, it blows up the image to the desired size.

example:
```
pdf.addPage(pw.Page(
        margin: pw.EdgeInsets.all(-100*PdfPageFormat.cm), //some high negative number
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Container(
              width: (_mockup.width)*PdfPageFormat.cm,
              height:  (_mockup.height)*PdfPageFormat.cm,
              child: pw.Image(image, fit: pw.BoxFit.cover,),
            )
          ); 
        }
        )
    );
```

I think there is no need to implement an OverflowBox Widget.
