### ISSUE TITLE
4 inch roll page format

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#869]
pls add 4 inch roll paper currently only supported 3 and 2 inch paper size

**Comment by DavBfr** [comment]
Create your own, like `PdfPageFormat(3 * PdfPageFormat.in, , double.infinity, marginAll: 5 * mm)`

**Comment by selvam920** [comment]
ok thanks, how to create table like this

![image](https://user-images.githubusercontent.com/20491308/143688525-16a36759-e1b6-4efe-939c-83147174cb97.png)

**Comment by DavBfr** [comment]
Same as this: https://www.youtube.com/watch?v=_lbE0wsVZSw

**Comment by selvam920** [comment]
i want to print  this table in pdf using Table.fromTextArray

**Comment by selvam920** [comment]
[invoice.pdf](https://github.com/DavBfr/dart_pdf/files/7612056/invoice.pdf)

this pdf generated from C#, samething creating from pdf plugin
pls help on this how to create item list like that table

**Comment by selvam920** [comment]
thanks for your help. i have done that layout using rows and columns.

**Comment by DavBfr** [comment]
For people looking for an example: https://gist.github.com/DavBfr/a25fe7001555818fc1eab04bbc0648a1

**Comment by selvam920** [comment]
wow, great example thanks
