### ISSUE TITLE
TextStyle's letterSpacing / lineSpacing is not honored

### ISSUE THREAD

**Issue by eliezedeck** [DavBfr/dart_pdf#87]
**Describe the bug**
When using TTF fonts with widget and using the `TextStyle`, the `letterSpacing` and `lineSpacing` (and probably other spacings?) do not have any effect.

This is an important feature since every fonts could have their own behavior, and that may not always match your expectations. For example, displaying 2 lines, using a font size of `10.0` with the Google's Font *Nunito-Regular* will cause the fonts to overlap each other.

**Comment by DavBfr** [comment]
I don't see any issue for `lineSpacing` and `wordSpacing`.
`letterSpacing` is not yet implemented, as well as the `background` property.

Can you provide sample code?

**Comment by eliezedeck** [comment]
Hope they get implemented soon.

Anyway, it is possible that there is something wrong with `pdf-1.3.10` ... I have upgraded to `pdf-1.3.11` and it generated a proper PDF. I can ignore the `lineSpacing` for now.
