### ISSUE TITLE
Convert Image

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#870]
can we export to image instead of pdf?

**Comment by DavBfr** [comment]
yes, use `Printing.raster()`

**Comment by selvam920** [comment]
good, thanks

**Comment by selvam920** [comment]
![0](https://user-images.githubusercontent.com/20491308/145202253-659f3c57-ce6d-433e-8ec5-ceab6339194a.png)
[Sales Invoice_#5.pdf](https://github.com/DavBfr/dart_pdf/files/7675724/Sales.Invoice_.5.pdf)
 
 List<String> paths = [];
        int i = 0;
        await for (var page in Printing.raster(bytes!, dpi: 72)) {
          final image = await page.toImage();
          String tempPath = (await getTemporaryDirectory()).path;
          String filePath = '$tempPath/' + i.toString() + '.png';
          File file = File(filePath);
          if (await file.exists()) await file.delete();
          var data = await image.toByteData();

          if (data != null) {
            await file.writeAsBytes(data.buffer.asUint8List());
            paths.add(filePath);
          }
        }

raster can not save pdf as image file

**Comment by DavBfr** [comment]
What's the error?

**Comment by selvam920** [comment]
![image](https://user-images.githubusercontent.com/20491308/145206840-8ea0fc79-6eb7-4b0e-9063-8259c8ac4a63.png)
unable to open the file

**Comment by DavBfr** [comment]
You don't save the image to PNG, but as raw RGBA pixels.

**Comment by selvam920** [comment]
can you provide sample code to export image png file

**Comment by DavBfr** [comment]
```dart
Future<void> save(BuildContext context, LayoutCallback build,
    PdfPageFormat pageFormat) async {
  final pdf = await build(pageFormat);
  final path = (await getTemporaryDirectory()).path;
  var i = 0;
  await for (final page in Printing.raster(pdf, dpi: 72)) {
    final png = await page.toPng();
    final file = File('$path/page-${i.toString().padLeft(3, '0')}.png');
    await file.writeAsBytes(png);
    print('Saved to ${file.absolute.path}');
  }
}
```

**Comment by selvam920** [comment]
thanks, it's working

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
