### ISSUE TITLE
save html to pdf instead of printing

### ISSUE THREAD

**Issue by medalawi** [DavBfr/dart_pdf#871]
is there any way to save pdf on iPhone from html string instead of printing 
```
await Printing.layoutPdf(
    onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
          format: format,
          html: '<html><body><p>Hello!</p></body></html>',
        ));
```
Thank you

**Comment by DavBfr** [comment]
Yes, just remove the print part:
```dart
final pdfBytes = await Printing.convertHtml(
          format: PdfPageFormat.a4,
          html: '<html><body><p>Hello!</p></body></html>',
);
```

**Comment by selvam920** [comment]
is this feature available all platform?

**Comment by selvam920** [comment]
i have created invoice pdf using widget but unicode font not supported so i'm moving to html. will unicode font work using html?

**Comment by DavBfr** [comment]
Unicode fonts are supported. RTL languages are not, except Arabic.
The HTML feature is available on Android, iOS, and macOS.

**Comment by selvam920** [comment]
for other platform can you refer below link
https://github.com/kechankrisna/webcontent_converter

**Comment by selvam920** [comment]
using Pdf widget with tamil unicode font, the exact text is not proper in the pdf like hindi

**Comment by DavBfr** [comment]
Can't use webcontent_converter: it's  GNU AFFERO GENERAL PUBLIC LICENSE which prevents any app to be closed-source and might not be permitted on the Apple stores.

**Comment by selvam920** [comment]
is there any way to use html to pdf in web?

**Comment by DavBfr** [comment]
Maybe, rendering the content inside a frame and converting it to an image.
