### ISSUE TITLE
layoutPdf() does not return when printing is canceled on ChromeOS

### ISSUE THREAD

**Issue by mikeesouth** [DavBfr/dart_pdf#873]
**Describe the bug**
I'm using Printing 5.6.0 and I'm calling layoutPdf like this:
```
    setState(() => _printInProgress = true);
    try {
      await Printing.layoutPdf(onLayout: (format) async => _pdfData);
    } finally {
      setState(() => _printInProgress = false);
    }
```
The future from layoutPdf does not return if I cancel the print preview on ChromeOS. so "_printInProgress" is true forever.

**To Reproduce**
See code example above.

**Expected behavior**
I expect the layoutPdf to return (false) when the printing is cancelled.

**Flutter Doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.1387], locale sv-SE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)

• No issues found!
```

**Chromebook (please complete the following information):**
 - Device: Acer Chromebook (not sure on exact model)
 - OS: ChromeOS 97
 - App from Play Store (not web)

**Comment by orcecso** [comment]
Any updates on this issue?
