### ISSUE TITLE
UrlLink doesn't work as a hyperlink

### ISSUE THREAD

**Issue by ttulka** [DavBfr/dart_pdf#874]
**Describe the bug**
First of all, thank you for a great library!

I am wondering if the class UrlLink is supposed to work as a hyperlink? In your demo (Resume) the links are not working as well and the hyperlink-like appearance is built via Text styling.

Am I right? If yes, are there any plans to render UrlLink as a clickable hyperlink in the next versions?

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pw.UrlLink(child: pw.Text('my link'), destination: 'http://example.com')
```

**Expected behavior**
A clickable hyperlink is been rendered.

**Desktop (please complete the following information):**
 - [x] Browser
 - [x] macOS 
 - [x] Windows
 - [x] Linux

Thanks!

**Comment by DavBfr** [comment]
Yes it's correctly rendered as a link and is clickable. But the PdfPreview widget is not interactive it's only intended for printing. But if you open the resulting PDF file on your desktop computer il will work.

**Comment by ttulka** [comment]
@DavBfr You're right, the issue is caused by the View, it works fine when save into a file.
Thanks!
