### ISSUE TITLE
[Android] onLayout() not called when the user changes the advanced print options

### ISSUE THREAD

**Issue by deakjahn** [DavBfr/dart_pdf#875]
**Describe the bug**

Print services has the right to advertise an extra activity in their XML, `advancedPrintOptionsActivity`. When provided, the Android print dialog will have an extra option at the bottom that calls the activity. The services are free to include settings there that influence the layout. When the uses selects this and goes into the advanced option activity and returns, `onLaoyut()` of `Printing.layoutPdf` doesn't get called again so that the PDF could be regenerated with the changed settings.

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Comment by DavBfr** [comment]
Can you provide a full example app?

**Comment by deakjahn** [comment]
Thinking about it more, not that easy. A client running with `printing` isn't enough. We need a **print service** that uses this extra setting and I can't simply present an empty print service here for you. :-) Do you happen to have a print service in your own codebase? Because I could then tell you what to add to test...

**Comment by deakjahn** [comment]
Basically, to give a bit of a background, when you do the same you do directly on Android, you also have the [`onLayout` callback.](https://developer.android.com/reference/android/print/PrintDocumentAdapter#onLayout)

This gets passed the `PrintAttributes`. You don't do that because, well, orientation is handled by the size, page ranges are handled by the platform, duplex or resolution aren't particularly interesting for a PDF (although, well, some might argue the resolution could be used to change the dpi passed to images, reducing PDF size in some cases) and you decided not to do anything about color/monochrome. :-) But actually, these attributes have one more items that would very well be of interest: margins.
