### ISSUE TITLE
Information about print error and number of copies

### ISSUE THREAD

**Issue by LukaszSieniec** [DavBfr/dart_pdf#878]
Hi! i have 2 questions:

1. Am I able to receive information that the attempt to print the pdf was unsuccessful?

```
PdfPreview(
                onError: (context, error) => Container(child: Text('onError!')),
                onPrinted: (context) => debugPrint('onPrinted!'),
                onPrintError: (context, error) => debugPrint('Print Error!'),
                allowSharing: false,
                canChangePageFormat: false,
                canDebug: false,
                build: (format) =>
                    _generatePdf(format, ''))
```
I have for example:
- onError
- onPrinted
- onPrintError

None of the above provides me with information (false / true) as to whether printing was successful or unsuccessful. How can I get this information?

2. If I press the PRINT ICON, the default print settings window appears. Can I somehow create my own print settings view? For example, I just want to select a printer and specify the number of copies, can I somehow send the number of copies to be printed? (WINDOWS, DESKTOP APPLICATION)

**Comment by DavBfr** [comment]
onError is to display something if the preview cannot be generated. onPrintError is the same but just catches the exceptions.

onPrinted is called only when the document has been printed. There is nothing to know if the user canceled the print or if the printer returned an error. Once it's in the spooler it's considered printed, which cannot be trusted.

You can use Printing.listPrinters and Printing.directPrint but it won't let you change settings like the number of copies, that's not implemented.
