### ISSUE TITLE
Error reporting when text contains Vietnamese

### ISSUE THREAD

**Issue by luongquoctiep** [DavBfr/dart_pdf#88]
**Describe the bug**
When my text contains Vietnamese will errors.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/22144852/59547201-029fb280-8f65-11e9-9b8a-f1628b993f45.PNG)
![Capture2](https://user-images.githubusercontent.com/22144852/59547209-31b62400-8f65-11e9-98aa-b84de5408ba6.PNG)

**Comment by DavBfr** [comment]
Fixed in version 1.3.12, thanks

**Comment by luongquoctiep** [comment]
Thanks for the update.
