### ISSUE TITLE
Variable number of variable length entries parsed over pages...

### ISSUE THREAD

**Issue by espbee** [DavBfr/dart_pdf#880]
I'm trying to lay out X number of entries as text blocks. Each entry is a variably length'd String. It seems that I need to figure out when an entry will overflow a given PDF page--

So, I can use a monospace font and calculate how many characters a page will hold, and then do what I have to do to split any entries that come to a page's end (into two entries, the second of which would start a new page). But it's tricky since these PDF lines break at spaces to show complete words (rather than an old fashioned dash if a word overflows a line). 

Short of writing a thing that parses out when the ends of my own lines would actually come, based on word lengths within each line-- is there by any chance a more immediate way to perhaps do this with your library?

**Comment by espbee** [comment]
Actually I'm reading around in these issues and this seems related to the person who's long word overflow a line. I guess I'd have had to parse through ahead of time anyway in case of any such long words. I'll close this unless anyone has any other thoughts--

**Comment by DavBfr** [comment]
The MultiPage widget does not work for you?

**Comment by espbee** [comment]
Each childs needs to end before the page ends, though, no? Just getting that from a doc comment and a couple trials.

**Comment by DavBfr** [comment]
Each child too big to fit the page will move to a new page.

**Comment by espbee** [comment]
But if a single child is longer than a page, is my potential situation. I'm looking at this MultiPage comment  in the docs:

/// The [Wrap] [Widget] here is able to rearrange its children to span them across
/// multiple pages. But a child of [Wrap] must fit in a page, or an error will raise.

That last part. And I do get an error when testing with an entry who's length exceeds that of a single page.

**Comment by DavBfr** [comment]
You can have a Text() or RichText() widget to automatically create new pages between two lines.

**Comment by espbee** [comment]
That's the thing I need. However,

when try to use a pw.Text() I get this:

Exception: Widget won't fit into the page as its height (1091.2639999999997) exceed a page height (728.5039370078739). You probably need a SpanningWidget or use a single page layout

And when I wrap the pw.Text() in a pw.Column() in a MultiPage situation, I get an out of memory error and the app crashes on an iPhone. (This is just a testing app, it does nothing but make the PDF from a static string on a button press). 

When I run the same on the simulator it says it's trying to make a PDF that exceeds its max pages, even if I set max pages to 100 and am only using twice the amount of text that fit into a single page.

The following works if I halve (or so) the length of that String. But this gives the out of memory error.

  pdf.addPage(pw.MultiPage(maxPages: 20, build: (context) {

      return [
        pw.Column(
            children: [

              pw.Text('estibulum et metus eget nibh dapibus faucibus. Proin sed ligula et metus efficitur viverra. Integer '
                'cursus feugiat mauris, sed cursus mauris finibus eget. Fusce velit lorem, lobortis ac sapien ut, '
                'tincidunt volutpat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, '
                'per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames '
                'ac turpis egestas. Quisque fringilla, lacus at efficitur porta, justo massa accumsan felis, '
                'new fallen rain, coming like light, like winter, and'
                'estibulum et metus eget nibh dapibus faucibus. Proin sed ligula et metus efficitur viverra. Integer '
                'cursus feugiat mauris, sed cursus mauris finibus eget. Fusce velit lorem, lobortis ac sapien ut, '
                'tincidunt volutpat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, '
                'per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames '
                'ac turpis egestas. Quisque fringilla, lacus at efficitur porta, justo massa accumsan felis, '
                'new fallen rain, coming like light, like winter, and'
                'estibulum et metus eget nibh dapibus faucibus. Proin sed ligula et metus efficitur viverra. Integer '
                'cursus feugiat mauris, sed cursus mauris finibus eget. Fusce velit lorem, lobortis ac sapien ut, '
                'tincidunt volutpat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, '
                'per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames '
                'ac turpis egestas. Quisque fringilla, lacus at efficitur porta, justo massa accumsan felis, '
                'new fallen rain, coming like light, like winter, and'
                'estibulum et metus eget nibh dapibus faucibus. Proin sed ligula et metus efficitur viverra. Integer '
                'cursus feugiat mauris, sed cursus mauris finibus eget. Fusce velit lorem, lobortis ac sapien ut, '
                'tincidunt volutpat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, '
                'per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames '
                'ac turpis egestas. Quisque fringilla, lacus at efficitur porta, justo massa accumsan felis, '
                'new fallen rain, coming like light, like winter, and'
                'estibulum et metus eget nibh dapibus faucibus. Proin sed ligula et metus efficitur viverra. Integer '
                'cursus feugiat mauris, sed cursus mauris finibus eget. Fusce velit lorem, lobortis ac sapien ut, '
                'tincidunt volutpat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, '
                'per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames '
                'ac turpis egestas. Quisque fringilla, lacus at efficitur porta, justo massa accumsan felis, '
                'new fallen rain, coming like light, like winter, and'
                'estibulum et metus eget nibh dapibus faucibus. Proin sed ligula et metus efficitur viverra. Integer '
                'cursus feugiat mauris, sed cursus mauris finibus eget. Fusce velit lorem, lobortis ac sapien ut, '
                'tincidunt volutpat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, '
                'per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames '
                'ac turpis egestas. Quisque fringilla, lacus at efficitur porta, justo massa accumsan felis, '
                'new fallen rain, coming like light, like winter, and'
                'estibulum et metus eget nibh dapibus faucibus. Proin sed ligula et metus efficitur viverra. Integer '
                'cursus feugiat mauris, sed cursus mauris finibus eget. Fusce velit lorem, lobortis ac sapien ut, '
                'tincidunt volutpat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, '
                'per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames '
                'ac turpis egestas. Quisque fringilla, lacus at efficitur porta, justo massa accumsan felis, '
                'nec consectetur dui justo at felis.' , style: style,
              
            ),
          ]
        )

      ];

    }));


I appreciate the time you're taking to deal with this. Any ideas?

**Comment by espbee** [comment]
Oh womp, indeed.
I'd only tried that on a Text inside of a Column. 
I see.

Thanks, I got you for a couple coffees.
