### ISSUE TITLE
How to display chart as shown on example

### ISSUE THREAD

**Issue by sxywalkr** [DavBfr/dart_pdf#881]
Hi sir,

I want to know how to display report as shown on dart-pdf example. I need to display on the web before printing the pdf. 
For the printing pdf part is already ok.

**Comment by DavBfr** [comment]
You'll have to use another library for Flutter display.

**Comment by sxywalkr** [comment]
yess, can you tell me please :)

**Comment by DavBfr** [comment]
Maybe this one: https://pub.dev/packages/fl_chart

**Comment by sxywalkr** [comment]
ok many thanks sir,

can I presume that dart-pdf chart can't use as a widget as display except only on printed pdf?

**Comment by sxywalkr** [comment]
hi again sir,

can I hide the value of x or y axis?

**Comment by DavBfr** [comment]
I need more explanations

**Comment by sxywalkr** [comment]
Hi sir, 

I want to make chart like this. The value of x/y axis is hidden or maybe font color can be set to white ?

Also I want to know is dart-pdf chart can combine line and bar like in the picture ?


![image](https://user-images.githubusercontent.com/71500033/146491665-a5987173-b770-40d2-b469-41ed80cd676d.png)
