### ISSUE TITLE
Unable to display the document

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#884]
Some users of our app are facing the issue "unable to display the document". There are no reproducible steps. So we are also not able to identify the issue.
The issue is on Android devices.

![Screenshot_2021-12-14-21-39-59-1](https://user-images.githubusercontent.com/14223997/146419736-cf5c3eeb-7098-48d4-914c-65c8dab7667a.png)

![IMG-20211215-WA0020](https://user-images.githubusercontent.com/14223997/146419740-2713598d-051b-4202-9306-41de975e306a.jpeg)

What could be the reason that they are getting this error?

**Comment by DavBfr** [comment]
This error will show if the device is older than Android Lollipop 5.0 (API 21). Older than that the API is not available.

**Comment by deepak786** [comment]
I will confirm the device OS version.
But is there a way to display the PDF on OS version less than 5.0?
Is it just the display issue or also the pdf generation issue on OS less than 5.0?

**Comment by DavBfr** [comment]
It's just a display issue. Printing a PDF document started with Android KitKat.
