### ISSUE TITLE
directPrintPdf configuration issue (windows)

### ISSUE THREAD

**Issue by lecuivre-alban** [DavBfr/dart_pdf#885]
**Describe the bug**
I'm working developping a Flutter app for Windows, and my goal is to print directly without user interaction.
The printer I'm working with is a Zebra ZT411.

Everything is working fine when I use the method "layoutPdf" and validate the configuration without changing anything. But that's not what I want.

My issue is when using the method "directPrintPdf", somehow something goes wrong with the printer settings. The printer which is initially set to "direct thermal" (what I want) get changed to "thermal transfer".

**Expected behavior**
First what I would like to know is what configuration is used when using the method "directPrintPdf" ?
Then would it be possible to expose printer settings in the Dart API ?

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [X] Windows
 - [ ] Linux

**Comment by DavBfr** [comment]
It's not using anything in particular. It's certainly is possible to expose all the printer settings to Dart.
Some settings would be set here: https://github.com/DavBfr/dart_pdf/blob/master/printing/windows/print_job.cpp#L136

**Comment by lecuivre-alban** [comment]
Hi @DavBfr , I found a way to do what I want and I submitted a PR to add the functionality. See #905 .

**Comment by DavBfr** [comment]
Fixed in pringint-5.7.0

**Comment by faycalbook** [comment]
await Printing.directPrintPdf  ( 
             printer: Printer(url: 'name of your device (printer name)'  ), 
         onLayout: (format) => _generatePdf(format, title));
