### ISSUE TITLE
Option to use custom widgets

### ISSUE THREAD

**Issue by asamedgrl** [DavBfr/dart_pdf#887]
I need some custom widgets that I need to use in the pdf file. But when I create pw.SpecialWidget I don't call it in my widget list. How can I do that? Thanks in advance...

**Comment by DavBfr** [comment]
You need to write your own widgets. They are different from Flutter's.

**Comment by dingyx** [comment]
> You need to write your own widgets. They are different from Flutter's.

hi，I want to print a [chart](https://pub.dev/packages/fl_chart) ，what should I do , is there any examples ?

Thanks!

**Comment by DavBfr** [comment]
@dingyx you have examples here:
- https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/examples/report.dart
- https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/widget_chart_test.dart
