### ISSUE TITLE
convertHtml with image 

### ISSUE THREAD

**Issue by XbIK** [DavBfr/dart_pdf#888]
have an issue when converting html string with image. convertHtml  function does not end up. If I delete the **img** tag, all works fine
```
var stringHtmlKp=""" 
<!DOCTYPE HTML>
<html>   
<head>
<title>Test</title>
</head>
<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Google-flutter-logo.png/320px-Google-flutter-logo.png' alt='LOGO'>"
</html>
""";
var listOfIntPdf = await Printing.convertHtml(
      //  format: const PdfPageFormat(21.0 * cm, 29.7 * cm, marginAll: 0),
        html: stringHtmlKp);
```

**Comment by ayob2k** [comment]
I have same probleme, the thing is the online image doesnt get displayed at all, its like it doesnt convert image

**Comment by DavBfr** [comment]
Have you added internet access rights to your app?

**Comment by XbIK** [comment]
yes, the app send requests by dio without  any errors

**Comment by XbIK** [comment]
convertHtml does not ends up only on html with images when used on Android. No problems with iOs. Pub version: printing: ^5.7.2

**Comment by DavBfr** [comment]
Did you enable Internet access on your Android app?

**Comment by XbIK** [comment]
yes, Internet works, http requests by dio run withous issues. 

Android Manifest has this line

`    <uses-permission android:name="android.permission.INTERNET"/>`

**Comment by Doflatango** [comment]
@XbIK Has your problem been resolved?

**Comment by XbIK** [comment]
sorry, but stiil the same issue (both printing and pdf pub are the latest). The convertHtml stucks only on Android, no problems with iOs
