### ISSUE TITLE
'package:pdf/src/pdf/color.dart': Failed assertion: line 60 pos 12: 'color.length == 3 || color.length == 6 || color.length == 8': is not true. package:pdf/…/pdf/color.dart:1

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#889]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [x] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nabil-ha** [comment]
guys any luck with this issue? it's still present to me, it happens when I remove dart:html package from my imports.

**Comment by DavBfr** [comment]
What's your code?

**Comment by nabil-ha** [comment]
> What's your code?

I solved it, the issue was that I'm using PdfColor while not importing dart:html, I'm not sure what's the relation between them, but that solved my issue by removing all references of PdfColor.
