### ISSUE TITLE
pdf can't show "  

### ISSUE THREAD

**Issue by 978740431** [DavBfr/dart_pdf#890]
I think "is the most basic symbol and should be displayed without setting the font. But there are problems, how do I need to solve this?

![image](https://user-images.githubusercontent.com/11803404/147032751-e9f5b512-2559-4157-a554-c28c29cd4a6b.png)

```
pdf: ^3.6.5

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (10 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```
I didn't set the font
![image](https://user-images.githubusercontent.com/11803404/147032609-d28ed323-4c0a-4a9e-8890-3ea057c5a19b.png)

**Comment by DavBfr** [comment]
It's not a quote as in code string. It's a Unicode oblique quote. You have to use a font.

**Comment by rspilker** [comment]
I do think that the error message can be improved to display the unicode value of the first offending character. I encountered a similar problem (yes, using open-sans solved the problem) but when looking at the error message, initially I was also mislead into thinking all characters were "normal".

**Comment by DavBfr** [comment]
I improved the message, thanks.
