### ISSUE TITLE
Error on adding Qr Code to PDF

### ISSUE THREAD

**Issue by subairlithos** [DavBfr/dart_pdf#899]
` import 'package:pdf/widgets.dart' as pw;`
              ..........
```
             pw.BarcodeWidget(
                     color: PdfColor.fromHex("#000000"),
                     barcode: pw.Barcode.qrCode(),
                     data:"test qr",
                   )
```
       ...........

   getting error when `pdf.save()`

    [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:pdf/src/pdf/data_types.dart': Failed assertion: line 75 pos 16: 'value != double.infinity': is not true.
    #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
    #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
    #2      new PdfNum (package:pdf/src/pdf/data_types.dart:75:16)
    #3      PdfNumList.output (package:pdf/src/pdf/data_types.dart:127:7)
    #4      PdfGraphics.setTransform (package:pdf/src/pdf/graphics.dart:391:64)
    #5      StatelessWidget.paint (package:pdf/src/widgets/widget.dart:242:11)
    #6      Flex.paint (package:pdf/src/widgets/flex.dart:493:13)
    #7      Page.paint (package:pdf/src/widgets/page.dart:232:13)
    #8      Page.postProcess (package:pdf/src/widgets/page.dart:176:5)
    #9      Document.save (package:pdf/src/widgets/document.dart:125:14)

**Comment by DavBfr** [comment]
try to give it a size.

**Comment by thanhhuy0611** [comment]
How to fix it? I tried to give it a size but it doesn't work
```
build: (pw.Context context) {
          return pw.SizedBox(
            height: 300 * PdfPageFormat.mm,
            child: pw.ConstrainedBox(
              constraints: pw.BoxConstraints.expand(),
              child: pw.FittedBox(
                child: pw.BarcodeWidget(
                  color: PdfColor.fromHex("#000000"),
                  barcode: pw.Barcode.qrCode(),
                  data:"test qr",
                ),
              ),
            )
          );
        },
```

**Comment by DavBfr** [comment]
@thanhhuy0611  The `BarcodeWidget` can draw a barcode of any size, from zero to any finite number.
The problem here is that: With `FittedBox` you make sure the `BarcodeWidget` gets undefined constraints, meaning infinite.
The fix is to give it a size, any size will work.

```dart
          return pw.SizedBox(
            height: 300 * PdfPageFormat.mm,
            child: pw.ConstrainedBox(
              constraints: pw.BoxConstraints.expand(),
              child: pw.FittedBox(
                child: pw.BarcodeWidget(
                  width: 1,
                  height: 1,
                  color: PdfColor.fromHex("#000000"),
                  barcode: pw.Barcode.qrCode(),
                  data: "test qr",
                ),
              ),
            ),
          );
```
