### ISSUE TITLE
Feature request: Password protection

### ISSUE THREAD

**Issue by jongkb** [DavBfr/dart_pdf#90]
It would be nice to have the ability to create a password-protected PDF.

**Comment by DavBfr** [comment]
@jongkb, why would you like password protection? What's your use case?

**Comment by jongkb** [comment]
The use case: An app that allows for the generation of confidential or sensitive content which can be exported to PDF and then shared. The objective is to prevent someone without a password from opening the protected/encrypted PDF file generated by the app.

**Comment by DavBfr** [comment]
What do you think about a paid option for this? Plus digital signing and copy protections.

**Comment by jongkb** [comment]
I'm currently evaluating Flutter and seeing what the plugin ecosystem has to offer. I suppose any effort to enable more complex features, hence more use-case possibilities—through paid option or otherwise—is generally a good thing. Perhaps the Flutter/Dart community can also provide feedback on this. :grin: Anyway, keep up the good work!

**Comment by DavBfr** [comment]
Pdf version 1.3.14 implements password protection up to AES 256

**Comment by jongkb** [comment]
Awesome, thanks! Any documentation or code sample on how to use new feature?

**Comment by DavBfr** [comment]
Sure, this example will use AES 256 encryption:

```dart
    final Document pdf = Document();
    pdf.document.encryption = PdfEncryptionAES(
      pdf.document,
      user: '1234',
      owner: '5678',
      accessFlags: Set<PdfAccessFlags>()
        ..add(PdfAccessFlags.Copy)
        ..add(PdfAccessFlags.Print),
    );
```

For now, only the interfaces are published, the implementation PdfEncryptionAES is not public.

**Comment by BisoDevil** [comment]
> Sure, this example will use AES 256 encryption:
> 
> ```dart
>     final Document pdf = Document();
>     pdf.document.encryption = PdfEncryptionAES(
>       pdf.document,
>       user: '1234',
>       owner: '5678',
>       accessFlags: Set<PdfAccessFlags>()
>         ..add(PdfAccessFlags.Copy)
>         ..add(PdfAccessFlags.Print),
>     );
> ```
> 
> For now, only the interfaces are published, the implementation PdfEncryptionAES is not public.

So how can we use it

**Comment by DavBfr** [comment]
It's a paid option, let me know if you're interested.

**Comment by BisoDevil** [comment]
hm?

**Comment by DavBfr** [comment]
Send me a mail, I'll explain.

**Comment by BisoDevil** [comment]
mail, please

**Comment by DavBfr** [comment]
It's on this page: https://pub.dev/publishers/nfet.net/packages

**Comment by MoeezChohan1089** [comment]
hey PdfEncryption is not working in my code
can you guide me how i can solve it

**Comment by DavBfr** [comment]
@MoeezChohan1089 
```dart
final pdf = Document();

// Declare the encryption options
pdf.document.encryption = PdfEncryptionAES(
  pdf.document,
  user: '1234', // The user password (can copy and print)
  owner: '5678', // The owner password (has all rights)
  accessFlags: <PdfAccessFlags>{
    PdfAccessFlags.Copy,
    PdfAccessFlags.Print,
  },
  level: PdfAESLevel.high,
);

pdf.addPage(
  Page(
    build: (Context context) {
      return Text('This text is encrypted using AES 256');
    },
  ),
);

final File file = File('encrypted.pdf');
await file.writeAsBytes(await pdf.save());
```

**Comment by MoeezChohan1089** [comment]
is this a paid plugin

**Comment by DavBfr** [comment]
@MoeezChohan1089 Yes, it is.

**Comment by MoeezChohan1089** [comment]
The function 'PdfEncryptionAES' isn't defined.
Try importing the library that defines 'PdfEncryptionAES', correcting the
name to the name of an existing function, or defining a function named
'PdfEncryptionAES'

i am facing this issue

**Comment by DavBfr** [comment]
https://pub.nfet.net/pdf_crypto/

**Comment by MoeezChohan1089** [comment]
hy sir,
Hope you are fine. Actually i want to ask with you about encryption. if it is possible that we can add encryption free without any cost in pdf widget in flutter.

**Comment by MoeezChohan1089** [comment]
so please tell me i need help for encryption

**Comment by MoeezChohan1089** [comment]
actually i am using this pluggin and i am searching for encryption on this pluggin so that i can add

**Comment by DavBfr** [comment]
Send me an email

**Comment by MoeezChohan1089** [comment]
moeezchohan798@gmail.com

**Comment by MoeezChohan1089** [comment]
this is my email
