### ISSUE TITLE
warnings on print and share: Unable to simultaneously satisfy constraints warnings on iOS device.

### ISSUE THREAD

**Issue by am1tr0r** [DavBfr/dart_pdf#901]
I am getting these following warnings on console whenever I click to share the pdf or I click to print the pdf. 
**Note:** getting these only on device not on simulator.  

**while sharing got these warnings**
 [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x28274e620 _UIActivityActionCellTitleLabel:0x127965340.height >= 22.5   (active)>",
    "<NSLayoutConstraint:0x28274e170 V:|-(15)-[_UIActivityActionCellTitleLabel:0x127965340]   (active, names: '|':UIView:0x127965010 )>",
    "<NSLayoutConstraint:0x28274e1c0 V:[_UIActivityActionCellTitleLabel:0x127965340]-(15)-|   (active, names: '|':UIView:0x127965010 )>",
    "<NSLayoutConstraint:0x2827a0050 'UIView-Encapsulated-Layout-Height' UIView:0x127965010.height == 52   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28274e620 _UIActivityActionCellTitleLabel:0x127965340.height >= 22.5   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-01-07 00:10:23.003166+0530 Agenda BOA[28681:14165140] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x2827b2030 _UIActivityActionCellTitleLabel:0x1209c14e0.height >= 22.5   (active)>",
    "<NSLayoutConstraint:0x2827b1b80 V:|-(15)-[_UIActivityActionCellTitleLabel:0x1209c14e0]   (active, names: '|':UIView:0x1209c0fb0 )>",
    "<NSLayoutConstraint:0x2827b1bd0 V:[_UIActivityActionCellTitleLabel:0x1209c14e0]-(15)-|   (active, names: '|':UIView:0x1209c0fb0 )>",
    "<NSLayoutConstraint:0x2827a0a00 'UIView-Encapsulated-Layout-Height' UIView:0x1209c0fb0.height == 52   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2827b2030 _UIActivityActionCellTitleLabel:0x1209c14e0.height >= 22.5   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**while printing got this warning**

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x2827aaa80 UIView:0x1209b1220.width == UILabel:0x1209a9d40'Page 1'.width + 28   (active)>",
    "<NSLayoutConstraint:0x2827aa620 H:[UIImageView:0x1209b0b40]-(3)-[UILabel:0x1209a9d40'Page 1'](LTR)   (active)>",
    "<NSLayoutConstraint:0x2827aac10 UIImageView:0x1209b0b40.width == 22   (active)>",
    "<NSLayoutConstraint:0x2827aa490 H:|-(0)-[UIImageView:0x1209b0b40](LTR)   (active, names: '|':UIView:0x1209b1220 )>",
    "<NSLayoutConstraint:0x2827aa8a0 UILabel:0x1209a9d40'Page 1'.right == UIView:0x1209b1220.right   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2827aa620 H:[UIImageView:0x1209b0b40]-(3)-[UILabel:0x1209a9d40'Page 1'](LTR)   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**To Reproduce**
Code snippet to reproduce the behavior:
I use Printing.sharePdf() to share the pdf and Printing.layoutPdf() to print.

**Flutter Doctor**
 [✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale en-IN)
    • Flutter version 2.8.0 at /Users/amitkanyan/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/amitkanyan/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • Amit’s iPhoneXR (mobile) • 00008020-001C4D3E0E52002E • ios            • iOS 13.4.1 17E262
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 96.0.4664.110
    ! Error: Amit’s iPhoneXR is busy: Making Amit’s iPhoneXR ready for development. Xcode will continue when Amit’s iPhoneXR
      is finished. (code -10)

• No issues found!
 

Smartphone :
 - Device: iPhoneXR
 - OS: iOS 13.4.1

**Comment by DavBfr** [comment]
Seems to be an issue in Flutter or iOS, this issue shows without the Printing plugin too.
