### ISSUE TITLE
generation failed because network access not accessible

### ISSUE THREAD

**Issue by stephane-couget** [DavBfr/dart_pdf#902]
Hello,

When I generate a fairly beefy pdf, I find that the build fails due to an attempt to access the net while it is cut. Indeed as soon as the net is active, the generation goes correctly. An idea on the reason and how to deactivate this behavior when the tablet network is deactivated, especially when I am in the countryside. ?

thanks in advance

**Comment by DavBfr** [comment]
This library has no network access unless you use Printing with PdfGoogleFonts and networkImage.
