### ISSUE TITLE
Generating PDF with Large data is too slow.

### ISSUE THREAD

**Issue by farooqaziz20** [DavBfr/dart_pdf#903]
Hi, I am build an accounts application, and using the PDF library for making report, but when i am trying to export pdf with large data, like 100+ row in table, it act very slow, like take 1-2 minute to generate PDF.
I am using it on both web and Desktop.
On web it make the browser busy until the report print in popped Up.
And on Desktop, application goes into not responding.

**Comment by farooqaziz20** [comment]
[test pdf.pdf](https://github.com/DavBfr/dart_pdf/files/7837654/test.pdf.pdf)

I am Generating this PDF, but i supposed to have much larger PDFs to be imported by this application

**Comment by DavBfr** [comment]
That's a fairly big document. You can use an Isolate to build it in the background.
An example here: https://github.com/DavBfr/dart_pdf/blob/master/pdf/test/isolate_test.dart

**Comment by subhamjodha** [comment]
pdf.save() consume alot of time even in isolate if no of pages 100+

**Comment by DavBfr** [comment]
The Widget system is quite slow and not intended to generate a lot of pages. You can use the basic API which should be faster, but you'll be in control of what's displayed.
