### ISSUE TITLE
Label paper support

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#904]
is there any example to create roll paper barcode with 2 column and label size 50 * 30 mm

**Comment by DavBfr** [comment]
- Use a roll paper format
- Column() > SizedBox(50 * PdfPageFormat.mm, 30*PdfPageFormat.mm) > Barcode()

**Comment by selvam920** [comment]
What about A4 sheet with multiple page?

**Comment by DavBfr** [comment]
use `PdfPageFormat.a4.copyWith(height: double.infinity)`
