### ISSUE TITLE
Best way to use multiple custom fonts in Flutter web without increasing app size/initial load time

### ISSUE THREAD

**Issue by Adeel-Sultan** [DavBfr/dart_pdf#907]
Hi, I have flutter web application and there almost 25+ fonts need to be used , 
all font folder size more than 35mb so please suggest me best way to implement all font with consuming memory

**Comment by DavBfr** [comment]
I have no solution for that. Any PDF library in any language will do the same. Because all the used glyph or character has to be embedded in the PDF file to be displayed anywhere, including on a printer.
