### ISSUE TITLE
Image not rendering in pdf in most readers, printers

### ISSUE THREAD

**Issue by dashnine** [DavBfr/dart_pdf#91]
I'm currently seeing an issue in which images are not rendering in some readers (or any printers) once they're written to the PDF.  I'm opening the image using AssetImage per the readme (sample to follow).

On android emulators, this is immediately detectable once you print out to PDF.  The image will load fine in the preview, but opening the document (using Files) will show a blank screen.  On my device (Pixel3), it will render the PDF just fine -- the problem is only visible when attempting to send to a printer (via the phone or computer) or uploading the PDF to computers and attempting to open it with a PDF reader *other than Chrome* (Safari, firefox, Edge, Acrobat).  

Attempting to open the image in Acrobat informs me that there is an error in the PDF.  Opening it with all other readers renders the text on a white background (skipping the image).

I've pushed an example PDF demonstrating this to Drive: https://drive.google.com/file/d/1_lnFxsEjwzHCqGnbtmROKdaXH0DY6mSB/view?usp=sharing

At the above link, the file should render fine when you load it in google docs.  If you open it in another reader (probably requires downloading...sorry.  If you want me to record a video and post, let me know!), however, it only shows text.

Code I'm using below:

```
const imageProvider =
        const AssetImage('assets/images/backgroundimage.png');
    final PdfImage image = await pdfImageFromImageProvider(
        pdf: pdf.document, image: imageProvider);

    pdf.addPage(Pdf.Page(
        pageFormat: PdfPageFormat.letter,
        build: (Pdf.Context context) {
          return Pdf.Stack(
            children: [
              ///////////////////////////// SHEET BACKGROUND /////////////////
              Pdf.Center(
                child: Pdf.Image(image),
              ),
```

My next lines write text into the document (they display just fine), even when printing.  I then send it to the printer:

```
    await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save())
```

Thanks!

**Comment by DavBfr** [comment]
The file linked has not been generated with this library, can you send a file from the output of pdf.save()?

**Comment by dashnine** [comment]
Weird--that *should* have been...though it was copied at one point across drive. Here's another generated with cloud print directly up to drive. Does this work?

https://drive.google.com/file/d/1PMM_ATydwyUNXe7vB8Pl-AvzC_P6IVIj/view?usp=drivesdk

(Thanks again!)

**Comment by dashnine** [comment]
And -- I take it all back.  Rather, the problem was there, but it looks like I had an async issue, and wasn't waiting properly (which resulted in certain kinds of asynchronous errors, to boot).  Sorry to waste your time! (And thanks for the impressive plugin).
