### ISSUE TITLE
how i can create  boarder to all pages 

### ISSUE THREAD

**Issue by 24by7abhishek** [DavBfr/dart_pdf#912]
hi 
 i need small help from you guys , i search lot but unable to find solution that why i'm asking from you guys
i want to create pdf with border to all page as given in image bellow  how can i achieve that ,

![image](https://user-images.githubusercontent.com/86393474/149454238-81136089-e542-42a0-a610-208bad498465.png)

**Comment by PrabavathiKalidoss** [comment]
How we set the header and footer outside of the border line ?
