### ISSUE TITLE
Feedback wanted: incoming changes in pdfium-binaries

### ISSUE THREAD

**Issue by bblanchon** [DavBfr/dart_pdf#917]
Hi,

I'm the creator of [pdfium-binaries](https://github.com/bblanchon/pdfium-binaries), which host pre-build binaries of PDFium that this project uses.

You probably noticed that the Windows packages are slightly different from the other packages because the import library is not in `lib/`, but in `lib/x86/`, `lib/x64/` or `lib/arm64/`. Similarly, the DLL is not in the `bin/` but in a subfolder.
I'm currently considering removing this separation so that every package has the same layout, and I'd like to get your feedback before making the change.
I initially made this separation because it allowed me to put x86 and x64 in the same package, but I don't do that anymore, and the subfolders are causing me troubles with CMake where there is no reliable way to detect the target CPU architecture (bblanchon/pdfium-binaries#17).

Please let me know if changing the Windows packages layout is a problem for you and if you think this is going in the right direction or not.

Best regards,
Benoit

**Comment by DavBfr** [comment]
Hi, thanks for that! And for your work aswell.
Yes, I think it's a good way to go. For this particular repo, no issues at all. I didn't even know that difference. I only use the variables published by `PDFiumConfig.cmake`. So as long as this is updated, it's transparent for me.

**Comment by bblanchon** [comment]
I just pushed the change; next Monday's build will have the new layout.
