### ISSUE TITLE
Add a way to select and copy text from PDF just like google chrome and syncfusion pdf viewer do

### ISSUE THREAD

**Issue by insinfo** [DavBfr/dart_pdf#918]
Add a way to select and copy text from PDF just like google chrome and syncfusion pdf viewer do

![image](https://user-images.githubusercontent.com/12227024/149817169-33a8009e-0ec2-46b2-bc60-e1ea4d19df61.png)

![sample](https://user-images.githubusercontent.com/12227024/149836001-2c20f696-e632-4fba-978c-8c880c50478b.png)

**Comment by DavBfr** [comment]
Why not use another plugin for that?

**Comment by insinfo** [comment]
I haven't found any other plugin that works on windows and android as well as this one.

**Comment by DavBfr** [comment]
relates to #949
