### ISSUE TITLE
Preview of the pdf is blurred. How to correct that?

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#925]
The pdf preview is blurred. But the Actual pdf is not.
How can we correct the pdf preview? Is there any parameter or setting which will correct the blurred view?

**Comment by DavBfr** [comment]
Do you have a screenshot, OS, version?

**Comment by deepak786** [comment]
**Android screenshots:**

<img width="412" alt="Screen Shot 2022-01-30 at 10 00 06 PM" src="https://user-images.githubusercontent.com/14223997/151708169-7c1e0425-4995-4b84-8d7d-895e3873355e.png">

<img width="412" alt="Screen Shot 2022-01-30 at 10 09 43 PM" src="https://user-images.githubusercontent.com/14223997/151708611-4d8325de-af6d-449d-8eb8-216cbc33daa3.png">

**iOS screenshots:**

<img width="412" alt="151708331-ff81910a-af55-4d07-86e0-48b0195db2e5.png" src="https://user-images.githubusercontent.com/14223997/151708331-ff81910a-af55-4d07-86e0-48b0195db2e5.png">

<img width="412" alt="Simulator Screen Shot - iPhone 13 - 2022-01-30 at 22 09 05" src="https://user-images.githubusercontent.com/14223997/151708617-9a4e78b5-3a65-4727-92df-cb75fef46aba.png">

**Web screenshots:**
<img width="1108" alt="Screen Shot 2022-01-30 at 10 19 22 PM" src="https://user-images.githubusercontent.com/14223997/151708972-0e747b4f-161a-4a01-94da-c26a3003aad6.png">

<img width="1111" alt="Screen Shot 2022-01-30 at 10 18 20 PM" src="https://user-images.githubusercontent.com/14223997/151708960-09bf7abf-12fe-4566-962b-81fa9b99d3aa.png">


OS:
Android, iOS, Web.

Versions:
```
pdf: 3.6.5
printing: 5.6.6
```

**Comment by DavBfr** [comment]
Can you try again with printing 5.7.0?

**Comment by deepak786** [comment]
I have tried version 5.7.1.
Still, the preview is blurry.

Android:
<img width="408" alt="Screen Shot 2022-01-31 at 2 11 11 PM" src="https://user-images.githubusercontent.com/14223997/151762856-da6c09ca-a0ef-4d5f-b229-7a4c6ee99823.png">

<img width="433" alt="Screen Shot 2022-01-31 at 2 11 56 PM" src="https://user-images.githubusercontent.com/14223997/151762957-beb2322e-7e17-47b2-bddf-aa19a6c07d82.png">

In fact with pdf: 3.7.0 and printing 5.7.1, there are 2 other issues that I will create separately.

**Comment by deepak786** [comment]
on the web, preview seems to be better now.
But on Android, the issue is not fixed.

**Comment by DavBfr** [comment]
Try to change this value, set it to 2.0, 3.0 or more and see if it improves

https://github.com/DavBfr/dart_pdf/blob/master/printing/lib/src/preview/raster.dart#L67

**Comment by deepak786** [comment]
devicePixelRatio: 1.5
Size(320.0, 533.3)
emulator: 4 WVGA Nexus

**Comment by DavBfr** [comment]
so the right value for this would be 2*devicePixelRatio.
maybe only for low-resolution screens.

Have you tested on a real modern device? On my phone, the PDFs look good.

**Comment by deepak786** [comment]
> so the right value for this would be 2*devicePixelRatio.
With `DPR` equal to 3, the quality improved but it's still blurry.
So multiplying the devicePixelRatio with 2 is not a good DPR.

**Comment by DavBfr** [comment]
I Improved this function and added a dpi attribute to PdfPreview to allow some customization.
But still, an A4 page on a 480 pixels display will look bad.
