### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by HugoPowerMex** [DavBfr/dart_pdf#926]
**Describe the bug**

Because every version of flutter_test from sdk depends on meta 1.3.0 and pdf >=3.6.5 depends on meta ^1.7.0, flutter_test from sdk is incompatible with pdf >=3.6.5.
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Fixed.
