### ISSUE TITLE
PDF created in portrait in landscape mode

### ISSUE THREAD

**Issue by liveaffiliates** [DavBfr/dart_pdf#93]
**Describe the bug**
orientation: PageOrientation.landscape text is still vertical so it types from the top down instead of typing horizontally.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pdf.addPage(Page(
      pageFormat: PdfPageFormat.a4,
      orientation: PageOrientation.landscape,
      build: (Context context) {
```

**Expected behavior**
Items to write horizontally

**Additional context**

**Comment by DavBfr** [comment]
That's exactly the expected behavior!

**Comment by liveaffiliates** [comment]
If that is the way it is intended I will close it. I am not sure if my question came across correctly. I don't understand why would anyone want to write vertically on landscaped sheet? It can't be read in landscape. That is still portrait?

**Comment by DavBfr** [comment]
If you print on a mobile device, the page orientation and size is not defined by you, but by the end user, selecting a printer and a paper size.
Then this orientation setting will force the page to be rendered as you intended.
Eg: if your layout is designed to print on an A4 page in landscape, it is likely that the printer still shows portrait to the user and will not print correctly. Setting the orientation to landscape or portrait will give the developer the priority on the end result.

**Comment by liveaffiliates** [comment]
Ok cool thanks very much.
