### ISSUE TITLE
windows Build issue

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#933]
[✓] Flutter (Channel master, 2.10.0-1.0.pre.396, on Microsoft Windows [Version 10.0.22543.1000], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

/C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/printing-5.7.2/lib/printing.dart:34:17:
Error: Member not found: 'buildThemeData'.
[   +1 ms]   if (ThemeData.buildThemeData != null) {
[   +1 ms]                 ^^^^^^^^^^^^^^
[  +14 ms] /C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/printing-5.7.2/lib/printing.dart:52:7:
Error: No named parameter with the name 'fontFallback'.
[   +2 ms]       fontFallback: [emoji, base],
[   +1 ms]       ^^^^^^^^^^^^
[   +1 ms]
/C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pdf-3.6.4/lib/src/widgets/theme.dart:97:11: Context: 
Found this candidate, but the arguments don't match.
[   +2 ms]   factory ThemeData.withFont({
[   +1 ms]           ^^^^^^^^
[   +3 ms] /C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/printing-5.7.2/lib/printing.dart:45:13:   
Error: Setter not found: 'buildThemeData'.
[   +2 ms]   ThemeData.buildThemeData = () {
[   +3 ms]             ^^^^^^^^^^^^^^
[+14691 ms] [+20732 ms]
/C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/printing-5.7.2/lib/printing.dart(34,17): error       
G75B77105: Member not found: 'buildThemeData'. [D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]     
[   +7 ms]   [   +2 ms]   if (ThemeData.buildThemeData != null) {
[   +1 ms]   [        ]                 ^^^^^^^^^^^^^^
[   +1 ms] [  +12 ms]
/C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/printing-5.7.2/lib/printing.dart(52,7): error        
GC6690633: No named parameter with the name 'fontFallback'.
[D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]
[   +2 ms]   [        ]       fontFallback: [emoji, base],
[   +1 ms]   [        ]       ^^^^^^^^^^^^
[   +1 ms]   [        ]
/C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pdf-3.6.4/lib/src/widgets/theme.dart:97:11: Context: 
Found this candidate, but the arguments don't match.
[   +2 ms]   [        ]   factory ThemeData.withFont({
[   +1 ms]   [        ]           ^^^^^^^^
[   +1 ms] [   +6 ms]
/C:/Users/SKS%20Market/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/printing-5.7.2/lib/printing.dart(45,13): error       
GC3CEBF4A: Setter not found: 'buildThemeData'. [D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]     
[   +2 ms]   [        ]   ThemeData.buildThemeData = () {
[   +1 ms]   [        ]             ^^^^^^^^^^^^^^

**Comment by ShreyamMaity** [comment]
Go to `windows\flutter\ephemeral\.plugin_symlinks\printing\windows\CMakeLists.txt`
then replace these lines from line 18-35 with
```
set(ARCH "x64")
set(PDFIUM_VERSION "4634" CACHE STRING "")

if(${PDFIUM_VERSION} STREQUAL "latest")
  set(PDFIUM_URL "https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-windows-${ARCH}.zip")
else()
  set(PDFIUM_URL "https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/${PDFIUM_VERSION}/pdfium-windows-${ARCH}.zip")
endif()

# Download pdfium
include(../windows/DownloadProject.cmake)
download_project(
  PROJ
  pdfium
  URL
  ${PDFIUM_URL}
  )
```
now build

**Comment by DavBfr** [comment]
try `flutter clean` in your project
