### ISSUE TITLE
(RangeError (byteOffset): Invalid value: Not in inclusive range 0..77382: 77384) when trying to write out a PDF file

### ISSUE THREAD

**Issue by DStar-OK** [DavBfr/dart_pdf#938]
When writing out a PDF file, doc.save() crashes with (RangeError (byteOffset): Invalid value: Not in inclusive range 0..77382: 77384). 

**To Reproduce**
```dart
  pw.Font? fontPDF;

  void initFontPDF() async {
    fontPDF ??= await PdfGoogleFonts.cutiveMonoRegular();
  }
            final doc = receiptToPDF();
            savePDF(doc);


  pw.Document receiptToPDF() {
    final doc = pw.Document();
    final style = pw.TextStyle(font: fontPDF, fontSize: 10);

    final List<pw.Widget> body = [
      pw.Text("Feb 7, 2022 11:19:53 AM", style: style)
    ];

    doc.addPage(pw.Page(
        pageFormat: PdfPageFormat.letter,
        build: (pw.Context context) {
          return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start, children: body);
        }));
    return doc;
  }
  void savePDF(pw.Document doc) async {
    final file = io.File("bugreport.pdf");
    await file.writeAsBytes(await doc.save());
  }

Code snippet to reproduce the behavior:
```

**Expected behavior**
It should print out the PDF, or at least give an error in terms of my input, not a mysterious RangeError exception.

**Screenshots**

**Flutter Doctor**

```
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
    • Flutter version 2.10.0 at C:\Users\David\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.20348.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.64.0)
    • VS Code at C:\Users\David\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.   
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [x ] Windows
 - [ ] Linux

**Additional context**
It fails with pdf 3.7.1 and printing 5.7.2, but it works fine with pdf 3.6.5 and printing 5.6.6.

**Comment by DavBfr** [comment]
Fixed in master branch.

**Comment by sutariyaharsh** [comment]
======== Exception caught by printing ============================================
The following IndexError was thrown while generating a PDF:
RangeError (byteOffset): Index out of range: index should be less than 81487: 81496

When the exception was thrown, this was the stack: 
#0      _byteDataByteOffsetCheck (dart:typed_data-patch/typed_data_patch.dart:5102:5)
#1      _ByteDataView.getUint16 (dart:typed_data-patch/typed_data_patch.dart:4880:18)
#2      TtfParser._readSimpleGlyph (package:pdf/src/pdf/font/ttf_parser.dart:466:21)
#3      TtfParser.readGlyph (package:pdf/src/pdf/font/ttf_parser.dart:446:14)
#4      TtfWriter.withChars.addGlyph (package:pdf/src/pdf/font/ttf_writer.dart:94:27)
#5      TtfWriter.withChars (package:pdf/src/pdf/font/ttf_writer.dart:104:7)
#6      PdfTtfFont._buildType0 (package:pdf/src/pdf/obj/ttffont.dart:121:28)
#7      PdfTtfFont.prepare (package:pdf/src/pdf/obj/ttffont.dart:162:7)
#8      PdfDocument._write (package:pdf/src/pdf/document.dart:225:10)
#9      PdfDocument.save.<anonymous closure> (package:pdf/src/pdf/document.dart:259:13)
#10     _RemoteRunner._run (dart:isolate:1090:47)
#11     _RemoteRunner._remoteExecute (dart:isolate:1084:12)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
PageFormat: "PdfPageFormat 595.275590551181x841.8897637795275 margins:56.69291338582677, 56.69291338582677, 56.69291338582677, 56.69291338582677"
==============================================================================



I am encountering an issue while generating a PDF using the pdf and printing packages in Flutter. The error specifically occurs when using some of the PdfGoogleFonts. Below is the error log that is thrown during PDF generation.
