### ISSUE TITLE
When creating Pdf, App froze on Android

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#941]
A user reports that the app froze when he clicked on a button to create the PDF. The user navigates to a new screen where the pdf is generated and displayed.
I'm not able to reproduce the issue. Also, I don't have a similar device.

```
Device: Motorola Edge
OS: Android 11
```

```
pdf: 3.6.5
printing: 5.6.6
```

here is the video

https://user-images.githubusercontent.com/14223997/153273531-8d7cfe86-1b20-4f94-96b3-0b456c5f9acf.mp4

The screen where it froze, is just a screen with PdfPreview.

**Comment by DavBfr** [comment]
Maybe the PDF is too big?

**Comment by deepak786** [comment]
@DavBfr no. I checked the data of the user and imported the same data into my account and generated the pdf. It is working.

**Comment by DavBfr** [comment]
So I don't know, sorry.

**Comment by deepak786** [comment]
@DavBfr I further analyzed it. 
The app froze for 3-4 minutes and then "out of memory" appears.
After that, it shows the "file not in PDF format or corrupted".

**Comment by deepak786** [comment]
I tried a workaround to solve this issue.
The text was very big to display in a table row. But the table row doesn't span to the next page. In debug mode, I'm getting the error "more than 20 pages are created" but in release build, the app is freezing.

So to solve this issue:
I have to break the text from line breaks (\n) and then generated as many table rows as equal to the array length after the split.
This generated the pdf. But it froze the app for 3 or 4 seconds and then generates the pdf.
I think it is because the pdf generation is done on the main thread.

can this library be updated to generate the pdf on another thread?

**Comment by DavBfr** [comment]
@deepak786 You can generate the pdf in an isolate, using compute() should work.
You'll have to pass all assets, though.

**Comment by deepak786** [comment]
I will try. 

But can't this package always generates the pdf as an isolate by default? I think that would be great. This will help a lot of users.

**Comment by MoeezChohan1089** [comment]
hy sir i am facing this issue that when i pressed on button then loader stop and loading how can i solve it

**Comment by MoeezChohan1089** [comment]
i means to say that i circular progress indicator is not rotating during click button and save me data without rotating circular progress indicator

**Comment by mansey7** [comment]
Hey guys, is there any update on this thread? I am experiencing the same issues on web when running pdfDoc.save(). The app freezes while the function is executing. I cannot run an isolate when using Web, the only thing I can do is use a JavaScript Web Worker but I have no experience in this.
