### ISSUE TITLE
IOS 15 ignore PdfPageFormat

### ISSUE THREAD

**Issue by Oleksandr32** [DavBfr/dart_pdf#942]
When I try to use Printing.layoutPdf with IOS 15 it looks like format of my page is ignoring so I get a very long result.

<img width="256" alt="Screenshot 2022-02-10 at 17 27 24" src="https://user-images.githubusercontent.com/24620659/153440389-cd9e12ae-4178-4e88-9d11-35a3bbe433e8.png">

For example, if I print saved pdf file via sharing, the result is ok. In that case I see paper size option.

<img width="381" alt="Screenshot 2022-02-10 at 17 23 05" src="https://user-images.githubusercontent.com/24620659/153440886-758b8d78-02dc-4642-afe8-fc81cc33e011.png">

Printing works ok in IOS 14 and lower. What do you think? any idea?

**Comment by Oleksandr32** [comment]
@DavBfr  here how I use this plugin
```
final format = PdfPageFormat(
    50 * PdfPageFormat.mm,
    54 * PdfPageFormat.mm,
    marginAll: 2 * PdfPageFormat.mm,
  );
  
Uint8List data = await Printing.convertHtml(
      format: format,
      html: response.body, // here result of api call
      baseUrl: '',
    );
    
return Printing.layoutPdf(
        format: format,
        onLayout: (format) {
          return data;
        },
        dynamicLayout: true,
      );
```

**Comment by Oleksandr32** [comment]
I have fixed that by adding this code to ios plugin implementation `PrintJob` class

```
// Workaround
    public func printInteractionController(_ printInteractionController: UIPrintInteractionController, choosePaper paperList: [UIPrintPaper]) -> UIPrintPaper {
        if currentSize == nil {
            return paperList[0]
        }
        
        return UIPrintPaper.bestPaper(forPageSize: currentSize!, withPapersFrom: paperList)
    }
```
where `currentSize` is size from 
```
func printPdf(name: String, withPageSize size: CGSize, andMargin margin: CGRect, withPrinter printerID: String?, dynamically dyn: Bool)
```

I found this workaround here https://developer.apple.com/forums/thread/30197

@DavBfr This behaviour I only notice in IOS 15. Please let me know if you will investigate this.

**Comment by DavBfr** [comment]
Looks good, can you create a PR?

**Comment by Oleksandr32** [comment]
@DavBfr of course, here PR
https://github.com/DavBfr/dart_pdf/pull/944

**Comment by luttmfra** [comment]
I have same Problem. Any news about the PR?
