### ISSUE TITLE
Flutter pdf plugin long text is not going in new line

### ISSUE THREAD

**Issue by AkashMore7427** [DavBfr/dart_pdf#943]
I am using a plugin

> pdf : ^3.7.1

On Using Following Code 

    pw.Text(Very Long Text,
        style: pw.TextStyle(
                  fontSize: 20,
               ),
    ),

The very long text is not going in a new line it's going out of the bound of the page.
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/qxDi7l.png

As you can see the text is cut after reaching the end. Even on using paragraph same happened.

**Comment by DavBfr** [comment]
You need to give it a width in order to allow a new line. Here it has infinite width.
