### ISSUE TITLE
PdfGoogleFonts.notoColorEmoji() has a long return

### ISSUE THREAD

**Issue by REU8ER** [DavBfr/dart_pdf#945]
This is not a problem, but is there a way to reduce the file size?

`final emoji = await PdfGoogleFonts.notoColorEmoji();`

**Comment by REU8ER** [comment]
Maybe it could be the way lining up the resources, if so, help would be greatly appreciated on how to use the fonts and emoji in the same pw.TextStyle

**Comment by DavBfr** [comment]
Yes by removing some emojis from it.

**Comment by REU8ER** [comment]
thanks!

**Comment by mattia-venturini** [comment]
@REU8ER did you achieve to reduce the file size? How? I don't know how to edit a ttf file and I cannot find any help searching on the web...
