### ISSUE TITLE
 Does it also support printing via Bluetooth or USB?

### ISSUE THREAD

**Issue by shinxxxxwon** [DavBfr/dart_pdf#947]
After seeing your example, I succeeded in printing via Wi-Fi. thank you. Does it support Bluetooth or USB printing?

**Comment by DStar-OK** [comment]
It uses the printer support that comes with all major systems; if you can print to it from another program, you should be able to print to it using this package.

**Comment by shinxxxxwon** [comment]
Using the 'printing' package, I succeeded in printing the printer with Android and IOS basic printing (Wi-Fi Direct). I want to print from Bluetooth (android, ios) and USB (only android). Create a pdf with `dart_pdf`. After that, do you have to implement Bluetooth and USB connection, data transmission, and printing yourself? If not, how much support does the package provide?
