### ISSUE TITLE
Circular Border

### ISSUE THREAD

**Issue by BlackBelt2817** [DavBfr/dart_pdf#95]
Is there a way to add a circular border to a widget? I have tried multiple combinations of the _decoration_ and _foregroundDecoration_ properties. It only renders a rectangular border around the circular _Container_.

```
Container(
  child: Text('STUFF'),
  width: 100,
  height: 100,
  decoration: BoxDecoration(
    shape: BoxShape.circle,
    border: BoxBorder(
      left: true,
      top: true,
      right: true,
      bottom: true,
    ),
  ),
),
```

**Comment by DavBfr** [comment]
This is not implemented for the border, but you can use a CustomPaint widget to draw what you need.

**Comment by BlackBelt2817** [comment]
Awesome, thanks!
