### ISSUE TITLE
How to make it silent printing in windows or uwp?

### ISSUE THREAD

**Issue by yozawiratama** [DavBfr/dart_pdf#950]
I create windows app (UWP) using flutter, and finally I can print, using https://pub.dev/packages/printing , but it open print setup. for now what we need is silent printing, how to do that?

**Comment by DavBfr** [comment]
On Windows use listPrinters() and directPrint()

**Comment by yozawiratama** [comment]
sorry I try it, got there is no `listPrinters()` and `directPrint()`

can you share more example code?

thanks for your help
