### ISSUE TITLE
Support horizontal layout or scroll direction

### ISSUE THREAD

**Issue by djoli** [DavBfr/dart_pdf#952]
Problem:
I have created a PDF in landscape orientation. Before printing, I would like to support a zoomable print preview. I am using PdfPreview() to do so, however there is no way to adjust the orientation of the preview to landscape. I am handling Zoom by wrapping PdfPreview() inside an InteractiveViewer().

Proposed solution 1:
When toggling between portrait and landscape page layouts, update the preview to better represent the final product, allowing you to actually rotate the PDF being rendered to be of an easier orientation to read. I've not yet looked into how best to do this in the code.

Proposed solution 2:
Add a custom property to PdfPreviewCustomState() (and parent components to allow it to be passed through from PdfPreview) to support overriding the scrollDirection of the ListView being built. This is a simpler change, which indirectly addresses my issue (supporting horizontal page layouts through rotation of the PdfPreview widget via a RotatedBox()), and allows for more customization of the PdfPreview in general. I am happy to raise a pull request for this change.

**Comment by DavBfr** [comment]
A left/right gesture like the iOS preview would be nice. Don't hesitate to create a PR.

**Comment by DavBfr** [comment]
Relates to #949
