### ISSUE TITLE
Bluetooth print.

### ISSUE THREAD

**Issue by richard457** [DavBfr/dart_pdf#958]
**Is your feature request related to a problem? Please describe.**
In the mobile app, it is common to use Bluetooth as a method of printing
**Describe the solution you'd like**
A way to also print on Bluetooth printer using this package of yours.
**Describe alternatives you've considered**
Tried this https://pub.dev/packages/blue_thermal_printer

**Comment by DavBfr** [comment]
Check this: https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin
Maybe someone should write a plugin to support Bluetooth/USB/network POS printers.
