### ISSUE TITLE
 PdfPreview widget gives error on Microsoft edge browser

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#960]
![image](https://user-images.githubusercontent.com/14223997/155972640-b30bc991-e3be-46bc-a844-191090ac0688.png)

It's working on the Chrome browser.

**Comment by DavBfr** [comment]
I can't reproduce that. The example works fine with Edge.

**Comment by deepak786** [comment]
To make it work I have to do the following:

downloaded the pdf js script and put it manually in the web folder and updated the reference from the path inside the index.html.

![Screen Shot 2022-05-13 at 8 01 30 PM](https://user-images.githubusercontent.com/14223997/168305951-03b3117c-847b-4ddb-a4ff-efeffaa9ff44.png)

And now it's working.
