### ISSUE TITLE
Error on Linux

### ISSUE THREAD

**Issue by kttary** [DavBfr/dart_pdf#961]
Error when building application on linux with following message:

> CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
>   Build step for pdfium failed: 1
> Call Stack (most recent call first):
>   flutter/ephemeral/.plugin_symlinks/printing/linux/CMakeLists.txt:36 (download_project)
> 
> 
> Exception: Unable to generate build files

I'm using PopOs 21.10. Previously work fine, beginning from saturday 26/02/2002 it start throw an error

**Comment by DavBfr** [comment]
Have you tried to run `flutter clean`?

**Comment by kttary** [comment]
yes, many times and not help me much until i read [this](https://github.com/rbcprolabs/packages.flutter/pull/233#issuecomment-970246427)
