### ISSUE TITLE
How to print image?

### ISSUE THREAD

**Issue by surajpunemaha** [DavBfr/dart_pdf#962]
Hello,
I am getting the URL for barcode image. I want to print that image through printer (special printers that can print barcodes on sticker paper)
I am able to get pdf through URL and print it. But i am facing issue with image datatype.
Please assist. thanks.

**Comment by DavBfr** [comment]
You have to create a PDF containing your image.

```dart
/// image is the png or jpeg file content
Future<Uint8List> generatePdf(PdfPageFormat format, Uint8List image) async {
  final pdf = pw.Document();
  final image = pw.MemoryImage(image);

  pdf.addPage(
    pw.Page(
      pageFormat: format,
      build: (context) {
        return pw.Center(child: pw.Image(image));
      },
    ),
  );

  return pdf.save();
}
```

**Comment by ugurberkecan** [comment]
@DavBfr  but this takes like 20 seconds is there any way to reduce this time ?

**Comment by DavBfr** [comment]
Use a jpeg image and/or reduce the size.

**Comment by ugurberkecan** [comment]
`Future<void> printImage(Uint8List imageScreen) async {
  print(DateTime.now());
  final doc = pw.Document();
  final memoryImage = pw.MemoryImage(imageScreen);

  doc.addPage(
    pw.Page(
      build: (context) {
        return pw.Image(memoryImage);
      },
    ),
  ); // Page
  print(DateTime.now());
  await Printing.layoutPdf(
    onLayout: (PdfPageFormat pdfPageFormat) async => doc.save(),
  );
  print(DateTime.now());
}
`

there are 20 seconds between two DateTime functions.

**Comment by DavBfr** [comment]
Do it like that:

```dart
Future<void> printImage(Uint8List imageScreen) async {
  await Printing.layoutPdf(
    onLayout: (PdfPageFormat pdfPageFormat) async {
      final doc = pw.Document();
      final memoryImage = pw.MemoryImage(imageScreen);

      doc.addPage(
        pw.Page(
          pageFormat: format,
          build: (context) {
            return pw.Image(memoryImage);
          },
        ),
      );

      print(DateTime.now());
      final bytes = await   doc.save(),
      print(DateTime.now());
  });
}
'''

Never reuse a Document object. Printing.layoutPdf is an interactive function and will rebuild the PDF document depending on the paper format and orientation selected by the user.

**Comment by ugurberkecan** [comment]
> Do it like that:
> 
> ```dart
> Future<void> printImage(Uint8List imageScreen) async {
>   await Printing.layoutPdf(
>     onLayout: (PdfPageFormat pdfPageFormat) async {
>       final doc = pw.Document();
>       final memoryImage = pw.MemoryImage(imageScreen);
> 
>       doc.addPage(
>         pw.Page(
>           pageFormat: format,
>           build: (context) {
>             return pw.Image(memoryImage);
>           },
>         ),
>       );
> 
>       print(DateTime.now());
>       final bytes = await   doc.save(),
>       print(DateTime.now());
>   });
> }
> ```
> 
> Never reuse a Document object. Printing.layoutPdf is an interactive function and will rebuild the PDF document depending on the paper format and orientation selected by the user.

Unfortunately still takes 20 sec btw I am using this on the web.

**Comment by luizjunior05** [comment]
I'm facing similar problem. The screen freezes for a few seconds.

https://user-images.githubusercontent.com/5141762/157304862-d8a15638-442c-4dba-8847-988acf539de3.mp4

**Comment by luizjunior05** [comment]
```
List result = await Future.wait([
  PointPainter(points: controller.quiz?.answer?.pathOfPain ?? [], type: 1, image: null).getImage(),
  rootBundle.load('assets/images/male_body.png'),
  PointPainter(points: controller.quiz?.answer?.whichApproach ?? [], type: 1, image: null).getImage(),
  rootBundle.load('assets/images/backbone.png'),
  PointPainter(points: controller.quiz?.answer?.vertebraPoints ?? [], type: 2, image: null).getImage(),
  rootBundle.load('assets/images/vertebra.png'),
]);

MemoryImage? points1 = result[0] != null ? MemoryImage(result[0]) : null;
MemoryImage? image1 = result[1] != null ? MemoryImage(result[1].buffer.asUint8List()) : null;
MemoryImage? points2 = result[2] != null ? MemoryImage(result[2]) : null;
MemoryImage? image2 = result[3] != null ? MemoryImage(result[3].buffer.asUint8List()) : null;
MemoryImage? points3 = result[4] != null ? MemoryImage(result[4]) : null;
MemoryImage? image3 = result[5] != null ? MemoryImage(result[5].buffer.asUint8List()) : null;
```

```
if (image1 != null && points1 != null) ...[
  Center(
    child: Stack(
      alignment: Alignment.topCenter,
      children: [
        Image(image1, width: sizeImgs, height: sizeImgs),
        Image(points1, width: sizeImgs, height: sizeImgs),
      ],
    ),
  ),
],
```

If I remove only the widget Image() the screen does not freeze and the CircularProgressIndicator() works normally.
