### ISSUE TITLE
HTML from json don't render 

### ISSUE THREAD

**Issue by anthonymdna** [DavBfr/dart_pdf#966]
AM traying to load and Jason field from an API, but the response is HTML format, I try to call it in diferents forms and whit diferents html packages but some just send me the raw html, and the nearest good way just don't come whit the html format from the API, since it is a complex text, I can't just format it one by one.

When I call it by one o those packages that keep de format, it just don't work and instead send me the method I use to call the instance

there needs to be a way to pass the data with the format, or make the widget works whit the HTML

**Comment by DavBfr** [comment]
I don't understand that.
