### ISSUE TITLE
Failed to run application with lib installed

### ISSUE THREAD

**Issue by ReniDelonzek** [DavBfr/dart_pdf#968]
**Describe the bug**
When I try to run the application in release mode on windows 11 it displays an error message indicating problems in the printing lib dll

**Screenshots**
![WhatsApp Image 2022-03-04 at 11 57 19](https://user-images.githubusercontent.com/16869726/156814959-0615b56c-3087-45b4-b673-c2b8336fd4b6.jpeg)

**Flutter Doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [versÃ£o 10.0.19042.1466], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.5)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.65.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [X] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - OS: WINDOWS 11  

**Additional context**
The problem does not occur on windows 10

**Comment by DavBfr** [comment]
Do you have pdfium.dll?

**Comment by ReniDelonzek** [comment]
yes, it is generated
![image](https://user-images.githubusercontent.com/16869726/156825329-59b6c381-f371-472c-b80e-49e4fa247fa5.png)

**Comment by ReniDelonzek** [comment]
Currently  I use printing in v 5.6.0

**Comment by DavBfr** [comment]
So I don't know. I never tested Windows 11.

**Comment by ReniDelonzek** [comment]
After a check it was observed that the problem was a file corruption during app updates. Closing for no relationship
