### ISSUE TITLE
Background colors in div are not rendered

### ISSUE THREAD

**Issue by lehnen** [DavBfr/dart_pdf#969]
`<div style="height:0.2mm; width:10mm; background: black;"></div> `
should render a small black line, but it doesen't.

Using 
`<div style="height:0.2mm; width:10mm; border-bottom: 0.2mm solid black;"></div>`
is a workarround, but the first one should work too, if possible.

Thx for the great work on this package ;)
Volker

**Comment by DavBfr** [comment]
The HTML renderer is based on the iOS/macOS and Android web engines, they will not produce perfect results.
