### ISSUE TITLE
How to convert Assets Images & Icons to PdfImage in flutter using dart_pdf

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#97]
I tried using this code, but **error, unloaded** image appeared like in the image below.
[StackOverflow](https://stackoverflow.com/questions/56896905/how-to-convert-assets-images-icons-to-pdfimage-in-flutter-using-dart-pdf)

 ByteData data = await rootBundle.load('assets/test.jpg');
  var codec = await instantiateImageCodec(data.buffer.asUint8List());
  var frame = await codec.getNextFrame();

  var imageBytes = await frame.image.toByteData();
  PdfImage assetImage = PdfImage(pdf.document,
      image: imageBytes.buffer.asUint8List(), width: 86, height: 80);

Result: 

![Screenshot_20190705_114546_com example example](https://user-images.githubusercontent.com/11361035/60710262-fee2c880-9f31-11e9-8013-4239ae55cd41.jpg)

**Comment by DavBfr** [comment]
Use this instead:
```dart
final PdfImage assetImage = await pdfImageFromImageProvider(
    pdf: pdf.document, 
    image: const AssetImage('assets/test.jpg'),
);
```

**Comment by jazzbpn** [comment]
Great!! It works for assets image. What if we want to use SVG Images?

**Comment by DavBfr** [comment]
You would have to implement an SVG parser and renderer.

**Comment by jazzbpn** [comment]
I have used this library ignorer to render the SVG Picture [LIBRARY](https://github.com/dnfield/flutter_svg)

**Comment by DavBfr** [comment]
Once you have a picture, you can create an image:
```dart
final String rawSvg = '''<svg viewBox="...">...</svg>''';
final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, rawSvg);
final Picture picture = svgRoot.toPicture();
final size = svgRoot.viewport.size;
var image = picture.toImage(size.width, size.height);
var pdfImage = await pdfImageFromImage(pdf: doc, image: image);
```

**Comment by jazzbpn** [comment]
One more question: Which one will render fast SVG or PNG images ?

**Comment by JittuMistry** [comment]
how to user network image

**Comment by DavBfr** [comment]
final pdfImage = await pdfImageFromImage(pdf: doc, image: NetworkImage( url ));

**Comment by tuhincse08** [comment]
how to use image from local path kept using path provider?

**Comment by riccardopirani** [comment]
> Use this instead:
> 
> ```dart
> final PdfImage assetImage = await pdfImageFromImageProvider(
>     pdf: pdf.document, 
>     image: const AssetImage('assets/test.jpg'),
> );
> ```

it's possibile get path od pdfImage?

**Comment by JittuMistry** [comment]
ok thanks for replying..i will definitely try this
