### ISSUE TITLE
How can we cus CustomPainter in PDF plugin ?

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#970]
In normal widget we will create a backgroundPainter using CustomPainter class and Implement t it where it is needed. But how can we implement this in PDF ? 

Note: This class is created from svg file where the two or more colors are dynamic in one svg image. So, we need to create a widget class to make it dynamic.  

      `import 'package:flutter/widgets.dart';

        class BackgroundPainter extends CustomPainter {
          @override
          void paint(Canvas canvas, Size size) {
            Path path_0 = Path();
            path_0.moveTo(0, 0);
            path_0.lineTo(0, size.height);
            path_0.lineTo(size.width * 0.4000000, 0);
            path_0.close();

            Paint paint_0_fill = Paint()..style = PaintingStyle.fill;
            paint_0_fill.color = Color.fromRGBO(205, 241, 231, 1.0).withOpacity(1.0);
            canvas.drawPath(path_0, paint_0_fill);

            Path path_1 = Path();
            path_1.moveTo(0, 0);
            path_1.lineTo(0, size.height * 0.4347826);
            path_1.lineTo(size.width * 0.6666667, 0);
            path_1.close();

            Paint paint_1_fill = Paint()..style = PaintingStyle.fill;
            paint_1_fill.color = Color.fromRGBO(156, 229, 208, 1.0).withOpacity(1.0);
            canvas.drawPath(path_1, paint_1_fill);

            Path path_2 = Path();
            path_2.moveTo(size.width * 0.2000000, 0);
            path_2.lineTo(size.width * 0.7333333, size.height * 0.2173913);
            path_2.lineTo(size.width, 0);
            path_2.close();

            Paint paint_2_fill = Paint()..style = PaintingStyle.fill;
            paint_2_fill.color = Color.fromRGBO(205, 241, 231, 1.0).withOpacity(1.0);
            canvas.drawPath(path_2, paint_2_fill);
          }

          @override
          bool shouldRepaint(covariant CustomPainter oldDelegate) {
            return true;
          }
        }

        // usage
        // CustomPaint(
        //             size: Size(
        //                 200,
        //                 (200 * 1.5333333333333334)
        //                     .toDouble()), //You can Replace [WIDTH] with your desired width for Custom Paint and height will be calculated automatically
        //             painter: BackgroundPainter(),
        //           )`

**Comment by DavBfr** [comment]
Simply like this:
```dart
    pdf.addPage(Page(
        build: (Context context) => CustomPaint(
              size: const PdfPoint(200, 200),
              painter: (PdfGraphics canvas, PdfPoint size) {
                canvas
                  ..drawEllipse(size.x / 2, size.y / 2, size.x / 2, size.y / 2)
                  ..setFillColor(PdfColors.blue)
                  ..fillPath();
              },
            )));
```
