### ISSUE TITLE
Indian Currency Issue

### ISSUE THREAD

**Issue by NiroopNife** [DavBfr/dart_pdf#971]
I was able to print the Euro currency symbol successfully by using ```String.fromCharCode(128)``` , but when i tried to insert the Inr symbol bu using ```String.fromCharCode(8377)``` it is giving an error stating as 
```Unhandled Exception: Invalid argument (string): Contains invalid characters.: "₹500"```

**Comment by DavBfr** [comment]
Why don't you just use it as a string?:
```dart
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.nunitoExtraLight();

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.Center(
            child: pw.Text('₹500', style: pw.TextStyle(font: font)),
          );
        },
      ),
    );
```

**Comment by NiroopNife** [comment]
Should i need to install any dependency for ```PdfGoogleFonts```?

**Comment by NiroopNife** [comment]
I'm getting an error stating as ```Undefined name 'PdfGoogleFonts'.```

**Comment by DavBfr** [comment]
Yes, you need `printing`

**Comment by NiroopNife** [comment]
It was coming correctly, but now getting an error as ```Unable to find a font to draw "₹" (U+20b9) try to provide a TextStyle.fontFallback```

And this is how I'm initializing

```
    font = await PdfGoogleFonts.nunitoExtraLight();

pw.Padding(
        padding: pw.EdgeInsets.symmetric(vertical: 5.h),
        child: pw.Text('₹$rlCount', style: pw.TextStyle(font: font)),)

pw.Padding(
        padding: pw.EdgeInsets.symmetric(vertical: 5.h),
        child: pw.Text('${String.fromCharCode(8377)} $cashTOOffice', style: pw.TextStyle(font: font)),)
```

**Comment by NiroopNife** [comment]
And also this now ```Error loading Nunito-ExtraLight, fallback to Helvetica.``` in ``` font = await PdfGoogleFonts.nunitoExtraLight();```

**Comment by DavBfr** [comment]
You need to enable internet access to be able to download the font from Google servers at runtime.

**Comment by NiroopNife** [comment]
Ain't there any offline way?

**Comment by DavBfr** [comment]
Yes there is, just add a TTF file to your assets and load it https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
