### ISSUE TITLE
asImage()

### ISSUE THREAD

**Issue by edwin0401** [DavBfr/dart_pdf#974]
asImage() type mismatch:

**final Uint8List pixels;** 

  /// Returns the image as an [Image] object from the pub:image library
  im.Image asImage() {
    return im.Image.fromBytes(width, height, **pixels** ); << pixels need to  convert to List<int>
  }

   Image.fromBytes(this.width, this.height, **List<int> bytes**,
      {ExifData? exif,
      ICCProfileData? iccp,
      Format format = Format.rgba,
      this.channels = Channels.rgba})

**To Reproduce**

Will print the blank page

    await for (var page in Printing.raster(await generateTicket(), dpi: 203)) {
      final image = page.asImage();
      ticket += generator.image(image);
      ticket += generator.feed(2);
      ticket += generator.cut();
    }

Then change this. Can print now correctly.

    await for (var page in Printing.raster(await generateTicket(), dpi: 203)) {
      final image = Image.fromBytes(
          page.width, page.height, Uint8List.fromList(page.pixels));
      ticket += generator.image(image);
      ticket += generator.feed(2);
      ticket += generator.cut();
    }

**Comment by DavBfr** [comment]
I don't see the issue here. `pixels` is already an `Uint8List`

**Comment by thanhhuy0611** [comment]
@DavBfr I have the seem issue on thermal printer. The problem is the printer will print the blank page

**Comment by thanhhuy0611** [comment]
> 
> Then change this. Can print now correctly.
> 
> ```
> await for (var page in Printing.raster(await generateTicket(), dpi: 203)) {
>   final image = Image.fromBytes(
>       page.width, page.height, Uint8List.fromList(page.pixels));
>   ticket += generator.image(image);
>   ticket += generator.feed(2);
>   ticket += generator.cut();
> }
> ```

@edwin0401 I tried your solution but it doesn't work. The printer still print a blank page
