### ISSUE TITLE
Method pdf.save does not work for document printing

### ISSUE THREAD

**Issue by tigranelyazyan** [DavBfr/dart_pdf#98]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**
Paste the output of running `flutter doctor -v` here.

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Please, precise your issue.

**Comment by tigranelyazyan** [comment]
@DavBfr  I am using your example for document printing  >>
await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save());<< 
and .save is undefined

**Comment by DavBfr** [comment]
In my example, pdf is defined as `final pdf = Document();`
