### ISSUE TITLE
Conform to PDF/A

### ISSUE THREAD

**Issue by edwin0401** [DavBfr/dart_pdf#982]
**Describe the bug**
When set the version of document to PdfVersion.pdf_1_5. That pdf seems does not conform to PDF/A.
If set to PdfVersion.pdf_1_4, everything is fine. 

Pdf is open fine and for the human use for both version. Butsome backend of the pdf package can not be open it correctly when default to " PdfVersion.pdf_1_5"

Document pdf = Document(**version: PdfVersion.pdf_1_4 // PdfVersion.pdf_1_5**);

**To Reproduce**
download the pdf from https://davbfr.github.io/dart_pdf/ and upload to https://www.pdf-online.com/osa/validate.aspx for checking.

**PdfVersion.pdf_1_5:**
Result	Document does not conform to PDF/A.
Details	Validating file "document.pdf" for conformance level pdf1.7
The "endobj" keyword is missing.
The document does not conform to the requested standard.
The file format (header, trailer, objects, xref, streams) is corrupted.
The document does not conform to the PDF 1.7 standard.

**PdfVersion.pdf_1_4**
Result	Document validated successfully.
Details	Validating file "document.pdf" for conformance level pdf1.7
The document does conform to the PDF 1.7 standard.

**Comment by DavBfr** [comment]
Fixed in master branch.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
