### ISSUE TITLE
Incorrect words order in mixed sentence Arabic + English 

### ISSUE THREAD

**Issue by Milad-Akarie** [DavBfr/dart_pdf#984]
**Describe the bug**
Incorrect words order in mixed sentence Arabic + English 

**To Reproduce**

```dart
   Text( 'أسمه في اللغة الإنجليزية TextDirection',
                      style: TextStyle(font: arabicFont),
                      textDirection: TextDirection.rtl,
                    ),
```

**Expected behavior**

![Screen Shot 2022-03-21 at 5 47 53 PM](https://user-images.githubusercontent.com/55059449/159304057-3a26209d-8533-4e22-92d6-f4ca5b36d2cd.png)

**Actual  behavior**
![Screen Shot 2022-03-21 at 5 48 26 PM](https://user-images.githubusercontent.com/55059449/159304405-45cd89eb-b590-425b-8dbc-bba660ced383.png)

```
**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!

```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [X] Windows
 - [X] Macos
 - [ ] Linux

**Additional context**
I tried to debug this my self and I got to this line
https://github.com/DavBfr/dart_pdf/blob/bcc07a34a4432ed18b740bab22c16072a85b4868/pdf/lib/src/pdf/font/arabic.dart#L384
```dart
if (isNewWordArabic) {
      isNewWordArabic = false;
      for (final notArabicNewWord in notArabicWords) {
        yield '${String.fromCharCodes(notArabicNewWord)} ';
      }
      notArabicWords.clear();
      yield String.fromCharCodes(_resolveLigatures(newWord));
    } else {
      // notArabicWords.insert(0, newWord);
     //   if I yield the non Arabic word prefixed by a space everything
    //  seems to work fine but I don't know if it breaks something else
      yield ' ${String.fromCharCodes(newWord)}';
    }
```

**Comment by DavBfr** [comment]
I don't know, I don't read Arabic.
Maybe you can create a PR with some test cases.

**Comment by DavBfr** [comment]
Duplicates #739
