### ISSUE TITLE
HTML to PDF

### ISSUE THREAD

**Issue by Jeancr123** [DavBfr/dart_pdf#985]
**Is your feature request related to a problem? Please describe.**
Most JS libraries for pdf offer html to pdf. This allows an easy central document for maintenance of file structure, content, and display, that gets easily transformed into pdf.

**Describe the solution you'd like**
An html to pdf method

**Comment by DavBfr** [comment]
Duplicates #784

**Comment by DavBfr** [comment]
Use this package: https://pub.dev/packages/htmltopdfwidgets

**Comment by techkonze** [comment]
Working Thanks!!!
