### ISSUE TITLE
SwiftCodeGeneration normal arm64 (in target 'printing' from project 'Pods')

### ISSUE THREAD

**Issue by ArslanKhan99** [DavBfr/dart_pdf#988]
LLVM ERROR: out of memory
Allocation failed
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/arslan/Library/Developer/Xcode/DerivedData/Runner-ezaglmiohwmqeqdxmwmvqoekhehy/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/printing.build/Objects-normal/arm64/PrintJob.bc -embed-bitcode -target arm64-apple-ios12.0 -Xllvm -aarch64-use-tbi -O -disable-llvm-optzns -module-name printing -o /Users/arslan/Library/Developer/Xcode/DerivedData/Runner-ezaglmiohwmqeqdxmwmvqoekhehy/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/printing.build/Objects-normal/arm64/PrintJob.o
1.	Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
2.	Compiling with the current language version
3.	Running pass 'Function Pass Manager' on module '/Users/arslan/Library/Developer/Xcode/DerivedData/Runner-ezaglmiohwmqeqdxmwmvqoekhehy/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/printing.build/Objects-normal/arm64/PrintJob.bc'.
4.	Running pass 'ObjC ARC contraction' on function '@UI_USER_INTERFACE_IDIOM'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000108dbade7 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 39
1  swift-frontend           0x0000000108db9e38 llvm::sys::RunSignalHandlers() + 248
2  swift-frontend           0x0000000108dbb440 SignalHandler(int) + 288
3  libsystem_platform.dylib 0x00007ff819f16dfd _sigtramp + 29
4  libsystem_malloc.dylib   0x00007ff819d34abb _malloc_zone_malloc + 125
5  libsystem_c.dylib        0x00007ff819e4cd24 abort + 123
6  swift-frontend           0x0000000108d07cda llvm::report_bad_alloc_error(char const*, bool) + 106
7  swift-frontend           0x0000000108d07cf2 out_of_memory_new_handler() + 18
8  libc++abi.dylib          0x00007ff819ebe96b operator new(unsigned long) + 43
9  swift-frontend           0x0000000108ac8efd llvm::Function::BuildLazyArguments() const + 77
10 swift-frontend           0x00000001068b1e87 llvm::objcarc::BundledRetainClaimRVs::insertRVCallWithColors(llvm::Instruction*, llvm::CallBase*, llvm::DenseMap<llvm::BasicBlock*, llvm::TinyPtrVector<llvm::BasicBlock*>, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, llvm::TinyPtrVector<llvm::BasicBlock*> > > const&) + 151
11 swift-frontend           0x00000001068c4f88 (anonymous namespace)::ObjCARCContract::run(llvm::Function&, llvm::AAResults*, llvm::DominatorTree*) + 1384
12 swift-frontend           0x0000000108b00380 llvm::FPPassManager::runOnFunction(llvm::Function&) + 1488
13 swift-frontend           0x0000000108b07073 llvm::FPPassManager::runOnModule(llvm::Module&) + 67
14 swift-frontend           0x0000000108b00b39 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1161
15 swift-frontend           0x000000010401e6df swift::performLLVMOptimizations(swift::IRGenOptions const&, llvm::Module*, llvm::TargetMachine*) + 3791
16 swift-frontend           0x000000010401f8cc swift::performLLVM(swift::IRGenOptions const&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef, swift::UnifiedStatsReporter*) + 2812
17 swift-frontend           0x0000000104028aa5 swift::performLLVM(swift::IRGenOptions const&, swift::ASTContext&, llvm::Module*, llvm::StringRef) + 213
18 swift-frontend           0x0000000103ae3795 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 16565
19 swift-frontend           0x0000000103aa25d4 swift::mainEntry(int, char const**) + 1108
20 dyld                     0x000000011613651e start + 462
error: Abort trap: 6 (in target 'printing' from project 'Pods')

**Comment by DavBfr** [comment]
Duplicates #977

**Comment by ArslanKhan99** [comment]
Thanks Library updated and issue is sorted

**Comment by ArslanKhan99** [comment]
in new version 5.7.5 issue is gone.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
