### ISSUE TITLE
Add Wrap widget.

### ISSUE THREAD

**Issue by MichalMisiaszek** [DavBfr/dart_pdf#99]
**Is your feature request related to a problem? Please describe.**
I would like to use Wrap widget. The GridView requires height constraint and I would like to use only width.

**Describe the solution you'd like**
Pure Wrap widget.

**Describe alternatives you've considered**
GridView widget but then I need to define height which I am not happy with.

**Comment by DavBfr** [comment]
Duplicate of #50
