### ISSUE TITLE
Table of content doesn't work with MultiPage

### ISSUE THREAD

**Issue by curvednebula** [DavBfr/dart_pdf#993]
**Describe the bug**
I'm trying to insert table of contents - so that it spans multiple pages, which is often the case for large documents. While it renders empty page instead. Works fine if I put it inside pw.Page(...) and if the table of content fits single page.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

void main() {

  final doc = pw.Document(pageMode: PdfPageMode.outlines);

  doc.addPage(pw.MultiPage(
    orientation: pw.PageOrientation.portrait,
    build: (context) => [
      pw.Center(child: pw.Text('Table of content', style: pw.Theme.of(context).header0)),
      pw.SizedBox(height: 20),
      pw.TableOfContent()
    ]
  ));

  final pdfBytes = await doc.save();
  await File('generated.pdf').writeAsBytes(pdfBytes);
}
```

**Expected behavior**
Should add multipage table of content.

**Screenshots**

**Flutter Doctor**
I'm not using Flutter, only pure Dart SDK.

```
```

**Desktop (please complete the following information):**
 - [ yes] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment]
Yes, it's a limitation.

**Comment by richard457** [comment]
Any plan to have this fixed? @DavBfr

**Comment by DavBfr** [comment]
@richard457 not really, you can work on it if you need that. I can help to understand the code and why it's a limitation.

**Comment by richard457** [comment]
Yes, I will love that, why it is a limitation now?

**Comment by DavBfr** [comment]
I'll have to dig into it before answering

**Comment by Elblassy** [comment]
you can solve this issue with this work around 

```
Future<Uint8List> _generateTotalDue(
    PdfPageFormat format,
    List<TotalDueStudents> totalDueList
    ) async {
  
  const pageSize = 26;
  final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);
  final font = await PdfGoogleFonts.cairoRegular();


  Map<int, List<pw.TableRow>> rows = {};

  final numberOfPages = (totalDueList.length / pageSize).ceil();

  for (var page = 0; page < numberOfPages; page++) {
    rows[page] = [
      pw.TableRow(
        children: [
          pw.Center(
            child: pw.Text(
              "المبلغ المتبقي",
              textDirection: pw.TextDirection.rtl,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
          pw.Center(
            child: pw.Text(
              "رقم الهاتف",
              textDirection: pw.TextDirection.rtl,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
          pw.Center(
            child: pw.Text(
              "اسم الطالب",
              textDirection: pw.TextDirection.rtl,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
          pw.Center(
            child: pw.Text(
              "no.",
              textDirection: pw.TextDirection.rtl,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
        ],
      ),
    ];

    var loopLimit =
        totalDueList.length - (totalDueList.length - ((page + 1) * pageSize));

    if (loopLimit > totalDueList.length) loopLimit = totalDueList.length;

    for (var index = pageSize * page; index < loopLimit; index++) {
      rows[page]!.add(pw.TableRow(
        children: [
          pw.Center(
            child: pw.Text(
              "${totalDueList[index].amountDue} ريال ",
              textDirection: pw.TextDirection.rtl,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
          pw.Center(
            child: pw.Text(
              totalDueList[index].mobile ?? "",
              textDirection: pw.TextDirection.rtl,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
          pw.Center(
            child: pw.Text(
              totalDueList[index].name ?? "",
              textDirection: pw.TextDirection.rtl,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
          pw.Center(
            child: pw.Text(
              "${index + 1}",
              textDirection: pw.TextDirection.ltr,
              style: pw.TextStyle(font: font, fontSize: 11),
            ),
          ),
        ],
      ));
    }
  }

  pdf.addPage(
    pw.MultiPage(
      maxPages: 100,
      pageFormat: format,
      build: (context) {
        return List<pw.Widget>.generate(rows.keys.length, (index) {
          return pw.Column(
            children: [
              pw.Table(
                border:
                pw.TableBorder.all(color: PdfColor.fromHex("#000000")),
                children: rows[index]!,
              ),
            ],
          );
        });
      },
    ),
  );
  return pdf.save();
}
```
  
It worked fine for me , let me know if it work for you

**Comment by richard457** [comment]
> you can solve this issue with this work around
> 
> ```dart
> Future<Uint8List> _generateTotalDue(
>     PdfPageFormat format,
>     List<TotalDueStudents> totalDueList
>     ) async {
>   
>   const pageSize = 26;
>   final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);
>   final font = await PdfGoogleFonts.cairoRegular();
> 
> 
>   Map<int, List<pw.TableRow>> rows = {};
> 
>   final numberOfPages = (totalDueList.length / pageSize).ceil();
> 
>   for (var page = 0; page < numberOfPages; page++) {
>     rows[page] = [
>       pw.TableRow(
>         children: [
>           pw.Center(
>             child: pw.Text(
>               "المبلغ المتبقي",
>               textDirection: pw.TextDirection.rtl,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>           pw.Center(
>             child: pw.Text(
>               "رقم الهاتف",
>               textDirection: pw.TextDirection.rtl,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>           pw.Center(
>             child: pw.Text(
>               "اسم الطالب",
>               textDirection: pw.TextDirection.rtl,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>           pw.Center(
>             child: pw.Text(
>               "no.",
>               textDirection: pw.TextDirection.rtl,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>         ],
>       ),
>     ];
> 
>     var loopLimit =
>         totalDueList.length - (totalDueList.length - ((page + 1) * pageSize));
> 
>     if (loopLimit > totalDueList.length) loopLimit = totalDueList.length;
> 
>     for (var index = pageSize * page; index < loopLimit; index++) {
>       rows[page]!.add(pw.TableRow(
>         children: [
>           pw.Center(
>             child: pw.Text(
>               "${totalDueList[index].amountDue} ريال ",
>               textDirection: pw.TextDirection.rtl,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>           pw.Center(
>             child: pw.Text(
>               totalDueList[index].mobile ?? "",
>               textDirection: pw.TextDirection.rtl,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>           pw.Center(
>             child: pw.Text(
>               totalDueList[index].name ?? "",
>               textDirection: pw.TextDirection.rtl,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>           pw.Center(
>             child: pw.Text(
>               "${index + 1}",
>               textDirection: pw.TextDirection.ltr,
>               style: pw.TextStyle(font: font, fontSize: 11),
>             ),
>           ),
>         ],
>       ));
>     }
>   }
> 
>   pdf.addPage(
>     pw.MultiPage(
>       maxPages: 100,
>       pageFormat: format,
>       build: (context) {
>         return List<pw.Widget>.generate(rows.keys.length, (index) {
>           return pw.Column(
>             children: [
>               pw.Table(
>                 border:
>                 pw.TableBorder.all(color: PdfColor.fromHex("#000000")),
>                 children: rows[index]!,
>               ),
>             ],
>           );
>         });
>       },
>     ),
>   );
>   return pdf.save();
> }
> ```
> 
> It worked fine for me , let me know if it work for you

I am getting corrupted PDF file trying to open the generated PDF

**Comment by richard457** [comment]
```
here is the code:
Future<void> generateDocv2({
    String brandName = "shop",
    String brandAddress = "Kigali Rwanda",
    String brandTel = "27131153",
    String brandTIN = "23",
    String brandDescription = "We build app that server you!",
    String brandFooter = "shop",
    String? receiverPhone,
    List<String>? emails,
    String? customerTin = "000000000",
    required List<TableRow> rows,
    required String invoiceType,
    required String df,
  }) async {
    const pageSize = 26;
    final font = await PdfGoogleFonts.cairoRegular();

    Map<int, List<TableRow>> rowsi = {};

    final numberOfPages = (rowsi.length / pageSize).ceil();

    for (var page = 0; page < numberOfPages; page++) {
      rowsi[page] = [
        TableRow(
          children: [
            Center(
              child: Text(
                "A",
                // textDirection: TextDirection.rtl,
                style: TextStyle(font: font, fontSize: 11),
              ),
            ),
            Center(
              child: Text(
                "B",
                // textDirection: TextDirection.rtl,
                style: TextStyle(font: font, fontSize: 11),
              ),
            ),
            Center(
              child: Text(
                "C",
                // textDirection: TextDirection.rtl,
                style: TextStyle(font: font, fontSize: 11),
              ),
            ),
            Center(
              child: Text(
                "no.",
                textDirection: TextDirection.rtl,
                style: TextStyle(font: font, fontSize: 11),
              ),
            ),
          ],
        ),
      ];

      var loopLimit = rowsi.length - (rowsi.length - ((page + 1) * pageSize));

      if (loopLimit > rowsi.length) loopLimit = rowsi.length;

      for (var index = pageSize * page; index < loopLimit; index++) {
        rowsi[page]!.add(rows[index]);
      }
    }

    doc.addPage(
      MultiPage(
        maxPages: 100,
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return List<Widget>.generate(rowsi.keys.length, (index) {
            return Column(
              children: [
                Table(
                  border: TableBorder.all(color: PdfColor.fromHex("#000000")),
                  children: rowsi[index]!,
                ),
              ],
            );
          });
        },
      ),
    );
    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: 'receipt.pdf',
      subject: "receipt",
      body: "Thank you for visiting us",
      emails: emails,
    );
  }
```
@[Elblassy](https://github.com/Elblassy) please let me know what you think I did wrong.

**Comment by richard457** [comment]
I ended-up with the following code working
```dart
Future<void> generateDocv2({
    String brandName = "shop",
    String brandAddress = "CITY CENTER, Kigali Rwanda",
    String brandTel = "",
    String brandTIN = "",
    String brandDescription = "We build app that server you!",
    String brandFooter = "shop",
    String? receiverPhone,
    List<String>? emails,
    String? customerTin = "000000000",
    required List<TableRow> rows,
    required String i,
    required String s,
  }) async {
    const pageSize = 26;
    final font = await PdfGoogleFonts.cairoRegular();

    Map<int, List<TableRow>> rowsi = {};

    final numberOfPages = (rows.length / pageSize).ceil();
    // deal with heading.
    for (var page = 0; page < numberOfPages; page++) {
      rowsi[page] = [
        TableRow(
          children: [
            Center(
              child: Text(
                "heading",
                style: TextStyle(font: font, fontSize: 11),
              ),
            ),
          ],
        ),
      ];
      // end of heading
      var loopLimit = rows.length - (rows.length - ((page + 1) * pageSize));

      if (loopLimit > rows.length) loopLimit = rows.length;

      for (var index = pageSize * page; index < loopLimit; index++) {
        rowsi[page]!.add(rows[index]);
      }
    }

    doc.addPage(
      MultiPage(
        maxPages: 100,
        pageFormat: PdfPageFormat.a4,
        orientation: PageOrientation.portrait,
        build: (context) {
          return List<Widget>.generate(rowsi.keys.length, (index) {
            return Column(
              children: [
                Table(
                  // border: TableBorder.all(color: PdfColor.fromHex("#000000")),
                  children: rowsi[index]!,
                ),
              ],
            );
          });
        },
      ),
    );
    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: 'receipt.pdf',
      subject: "receipt",
      body: "Thank you for visiting us",
      emails: emails,
    );
  }
```
The only problem is that I can't get the heading appear once as I want it only to at the start of the page only.

**Comment by Elblassy** [comment]
pageSize i a number i test it and work in my design if your header is bigger then let pageSize smaller , so you can change it as you can test and get it suitable for you

If you want header in first page only so you can make condition if you in first page create header row else put empty list

I don't try it but i think it will work
