### ISSUE TITLE
Send PDF file print to default Printer without preview

### ISSUE THREAD

**Issue by abdulrehmananwar** [DavBfr/dart_pdf#994]
I have a pdf file . i want to print that file on my default printer in background service.

**Comment by DavBfr** [comment]
That's supported on Windows, Linux, macOS,  and partially on iOS.

Use `Printing.listPrinters()` to get the printers. One of the returned printers will have an `isDefault` property set if any default printer is defined.
You can then use `Printing.directPrintPdf()` with that printer to print without user interaction.

On iOS, `listPrinters` will show a popup to the user to select the printer they want to use.

**Comment by Harishwarrior** [comment]
How to pass already created PDF file in onLayout ?

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
