### ISSUE TITLE
FixedAxis

### ISSUE THREAD

**Issue by ManikandanRajamanickam12** [DavBfr/dart_pdf#997]
I want use LinedataSet and BardataSet  of diiferent value in single chart of different  x-Axispoint of single chart Widget.This package support only X-axis as Fixed Axis as for i see.Is any option for to solve this problem?

**Comment by DavBfr** [comment]
Is the `axis` property of `BarDataSet` not working for you?

**Comment by ManikandanRajamanickam12** [comment]
Not that one...
 grid: pw.CartesianGrid(
      xAxis: pw.FixedAxis.fromStrings(
        List<String>.generate(
            linetable.length, (index) => linetable[index][0] as String),
        marginEnd: 50,
        textStyle: pw.TextStyle(
          color: PdfColor.fromHex("#476241"),
        ),
      ),
      yAxis: pw.FixedAxis(
        [0, 20, 40, 60, 80, 100],
        divisions: true,
      ),
    ),

datasets: [
//X-axis values[1,2,3,.......]
      pw.LineDataSet(
        legend: "HR Plot",
        drawSurface: true,
        isCurved: true,
        drawPoints: false,
        color: baseColor,
        data: List<pw.LineChartValue>.generate(
          linetable.length,
          (i) {
            final v = linetable[i][1] as num;
            return pw.LineChartValue(i.toDouble(), v.toDouble());
          },
        ),
      ),
//X-value[10,20,30.....]
      pw.BarDataSet(
        color: PdfColors.blueGrey100,
        offset: 0,
        width: 5,
        borderColor: PdfColors.blueGrey,
        data: List<pw.LineChartValue>.generate(
          annotation.length,
          (m) {
            final n = annotation[m][1] as num;
            return pw.LineChartValue(m.toDouble(), n.toDouble());
          },
        ),
      ),
    ],
  );

I want to plot these to graph with different x- axis values.Because of grid it takes x-axis values from itself

**Comment by ManikandanRajamanickam12** [comment]
I want to combine linegraph and bargraph in a single chart with different X-axis.Is it possible?

**Comment by ManikandanRajamanickam12** [comment]
but the garph always follow grid x-axis list of STRING poins only.when i generate List of STRING of another points for bar dataset,it takes points from grid only....

List<pw.LineChartValue>.generate(
annotation.length,
(m) {
final n = annotation[m][1] as num;
return pw.LineChartValue(m.toDouble(), n.toDouble());

**Comment by ManikandanRajamanickam12** [comment]
Solved

**Comment by justforworkandstuff** [comment]
hi @ManikandanRajamanickam12, may I ask how did you solve this issue?
